### ISSUE TITLE
Not found theme update

### ISSUE THREAD

**Issue by lawrencegagein** [afragen/github-updater#135]
Hi afragen,

I can't find theme update in my update page.

local style:
/*
Theme Name:       Test
Theme URI:        http://192.168.1.29:8080/
Description:      Child-Theme of TwentyFifteen.
Author:           Law
Version:          1.0.0
GitHub Theme URI: https://github.com/lawrencegagein/TestWPAutoUpload
GitHub Branch:    develop
*/

Please help me, thanks

**Comment by afragen** [comment]
Let me know if you have any other problems.
