### ISSUE TITLE
Thanks for the great work

### ISSUE THREAD

**Issue by mgibbs189** [afragen/github-updater#138]
@afragen Just wanted to say thanks for creating (and maintaining!) this wonderful plugin. I've been using it for over a year with no issues whatsoever.

Happy New Year!

**Comment by Adevade** [comment]
I would also like to thank you very much for your amazing work! I use this on all my own and all my clients sites now, and it works flawless! 

Thank you!

**Comment by afragen** [comment]
Thanks Andréas and thanks for the pending translation. I've updated the POT.

**Comment by aariacarterweir** [comment]
Big props from me too :) It's great work you do here - and much appreciated! x

**Comment by afragen** [comment]
Thanks Aaria!

**Comment by commwork** [comment]
where can i donate some $? and yes this plugin is awesome!! thx a lot for the good work!

**Comment by afragen** [comment]
Thanks @commwork! There is a donate link, http://bit.ly/github-updater

**Comment by afragen** [comment]
@commwork (Andreas) thanks for the donation. Hold off on the translation until I update the POT. Hopefully later today or tomorrow.

**Comment by commwork** [comment]
donation is out some minutes ago ;) (henning fischer) . thx again for the great work!

**Comment by afragen** [comment]
Thanks @commwork I appreciate it.

**Comment by flashadvocate** [comment]
@afragen  I got the opportunity to plug your plugin (no pun intended) at WordCamp Raleigh this past weekend, seems like a lot of folks were happy to hear of this.

Keep up the great work!

**Comment by afragen** [comment]
Thanks @flashadvocate. I'll have to check out the talk on WordPress TV.

**Comment by flashadvocate** [comment]
Awesome, I believe it was the "So you want to build a plugin" session with Ryan Duff, somewhere near the end.

**Comment by kpry** [comment]
I agree. This is one the best best open source WordPress plugins out there!

**Comment by afragen** [comment]
Thanks Kevin

**Comment by pingram3541** [comment]
Thanks for this!
