### ISSUE TITLE
Italian language translation for github-updater

### ISSUE THREAD

**Issue by overclokk** [afragen/github-updater#142]
Hi @afragen 
I have translated github-updater in Italian, Here is a link for po file http://www.megafileupload.com/en/file/596910/github-updater-it-zip.html

Thank you for your work :-)

**Comment by afragen** [comment]
@overclokk I am unable to download this file. The link seems to take me to some video sharing site.

It would be best to fork the project and submit a PR to the `develop` branch.

**Comment by afragen** [comment]
@overclokk I was able to get the translation. Thanks! It'll be in the next update.

**Comment by overclokk** [comment]
@afragen Sorry, I was in a hurry :-P
Next time I will do fork :-)

Thanks again

**Comment by afragen** [comment]
No problem. I greatly appreciate the work.

**Comment by afragen** [comment]
@overclokk I missed a string. You should see it in the new .pot file in `develop` branch.

**Comment by overclokk** [comment]
@afragen done :-)

**Comment by afragen** [comment]
Thanks.

**Comment by overclokk** [comment]
You're welcome :-)
