### ISSUE TITLE
Refresh time?

### ISSUE THREAD

**Issue by jakeleboeuf** [afragen/github-updater#143]
I'm trying to understand how/when the theme is checking github for a new version. Is there some sore of refresh timer/caching issue that would be preventing me from seeing new updates that are available? Some times I see updates are available, and sometimes it tells me I'm on the latest version even when I'm not?

**Comment by afragen** [comment]
The data is cached in transients for 12 hours but the transients can be cleared if you use the **Check Again** button.

**Comment by jakeleboeuf** [comment]
Awesome, thanks @afragen!
