### ISSUE TITLE
i18n: enhancements suggestions

### ISSUE THREAD

**Issue by daniel-menard** [afragen/github-updater#148]
**1. Looking at the code, I found two strings which are *maybe* missing translation**

```php
/includes/GitHub_Updater/Bitbucket_API.php :
- 142: $response->message = 'No tags found';  
- 227: $response['message'] = 'No changelog found'; 
```
They are not printed directly but I guess they are shown somewhere else. Should they be translated?

**2. It's hard to translate pieces of sentences**

It's easier to translate full sentences (see [Otto's Second Law](http://ottopress.com/2012/internationalization-youre-probably-doing-it-wrong/)).

Example:
```php
// includes/GitHub_Updater/Theme.php:306
<?php _e( 'Current version is up to date. Try', 'github-updater' ); ?>
<a href="#" onclick="jQuery('#ghu_versions').toggle();return false;">
    <?php _e( 'another version?', 'github-updater' ); ?>
</a>
```

Should be something like:

```php
printf(
    __( 'Current version is up to date. Try <a %s>another version</a>?', 'github-updater' ),
    'href="#" onclick="jQuery(\'#ghu_versions\').toggle();return false;"'
);
```

Same problem at line `Theme.php:296` (see below).

**3. Avoiding redundancy**

Line at `includes/GitHub_Updater/Theme.php:306` has same problem as above (six strings for 1 sentence):

```php
<strong><br /><?php _e('There is a new version of&nbsp;', 'github-updater' ); echo $theme->name; _e( '&nbsp;available now.', 'github-updater' ); ?> <a href="<?php echo $details_url; ?>" class="thickbox" title="<?php echo $theme->name; ?>"><?php _e( '&nbsp;View version&nbsp;', 'github-updater' ); echo $theme->remote_version; _e( '&nbsp;details', 'github-updater' ); ?></a><?php _e( '&nbsp;or&nbsp;', 'github-updater' ); ?><a href="<?php echo $update_url; ?>"><?php _e( 'update now', 'github-updater' ); ?></a>.</strong>
```

But I think we can re-use the translations used at line 218 (they produce almost the same output):

```php
// new L296
printf(
    __( 'GitHub Updater shows a new version of %1$s available.&nbsp;', 'github-updater' ) . 
    __( '<a %2$s>View version %3$s details</a> or <a href="%4$s">update now</a>.', 'github-updater' ),
    $theme->name, 
	sprintf(
		'href="%1$s" class="thickbox" title="%2$s"',
		esc_url( $details_url ),
		esc_attr( $theme->name )
	),
    $theme->remote_version,
    $update_url
); 
```
It would remove 6 strings in the pot files, less work, happy translators ;-)

**PS:**
Nothing to do with i18n, but my IDE reports some unused vars. It's really insignificant details, but  I still mention them : 

- `/includes/GitHub_Updater.php:190/226/280/322`: variable $key is never used
- `/includes/GitHub_Updater/GitHub_API.php:161`: variable $num is never used
- `/includes/GitHub_Updater/Theme.php:167`: variable $theme_name is never used

(There are others but they are legitimate, e.g. Theme.php:317 $url).

Cheers !

Daniel

**Comment by afragen** [comment]
> 1. Looking at the code, I found two strings which are maybe missing translation
> 
> /includes/GitHub_Updater/Bitbucket_API.php :
> - 142: $response->message = 'No tags found';  
> - 227: $response['message'] = 'No changelog found'; 
> They are not printed directly but I guess they are shown somewhere else. Should they be translated?

These strings aren't for display. They are just something to occupy the transient so the plugin doesn't continually check GitHub for something that doesn't exist.

> 2. It's hard to translate pieces of sentences
> 
> It's easier to translate full sentences (see Otto's Second Law).
> 
> Example:
> 
```php
> // includes/GitHub_Updater/Theme.php:306
> <?php _e( 'Current version is up to date. Try', 'github-updater' ); ?>
> <a href="#" onclick="jQuery('#ghu_versions').toggle();return false;">
>     <?php _e( 'another version?', 'github-updater' ); ?>
> </a>
```
> Should be something like:
> 
```php
> printf(
>     __( 'Current version is up to date. Try <a %s>another version</a>?', 'github-updater' ),
>     'href="#" onclick="jQuery(\'#ghu_versions\').toggle();return false;"'
```
> );
> Same problem at line Theme.php:296 (see below).

I'd be thrilled to get a PR fixing this if it makes it easier. I really don't know JS so a tested PR would be great.

> 3. Avoiding redundancy
> 
> Line at includes/GitHub_Updater/Theme.php:306 has same problem as above (six strings for 1 sentence):

PRs welcome :smile: 

```php
> <strong><br /><?php _e('There is a new version of&nbsp;', 'github-updater' ); echo $theme->name; _e( '&nbsp;available now.', 'github-updater' ); ?> <a href="<?php echo $details_url; ?>" class="thickbox" title="<?php echo $theme->name; ?>"><?php _e( '&nbsp;View version&nbsp;', 'github-updater' ); echo $theme->remote_version; _e( '&nbsp;details', 'github-updater' ); ?></a><?php _e( '&nbsp;or&nbsp;', 'github-updater' ); ?><a href="<?php echo $update_url; ?>"><?php _e( 'update now', 'github-updater' ); ?></a>.</strong>
```
> But I think we can re-use the translations used at line 218 (they produce almost the same output):
> 
```php
> // new L296
> printf(
>     __( 'GitHub Updater shows a new version of %1$s available.&nbsp;', 'github-updater' ) . 
>     __( '<a %2$s>View version %3$s details</a> or <a href="%4$s">update now</a>.', 'github-updater' ),
>     $theme->name, 
>     sprintf(
>         'href="%1$s" class="thickbox" title="%2$s"',
>         esc_url( $details_url ),
>         esc_attr( $theme->name )
>     ),
>     $theme->remote_version,
>     $update_url
> ); 
```

I think the above structure more closely resembles what is the default in WordPress. We certainly don't have to match it exactly.

> It would remove 6 strings in the pot files, less work, happy translators ;-)
> 
> PS:
> Nothing to do with i18n, but my IDE reports some unused vars. It's really insignificant details, but I still mention them :
> 
> /includes/GitHub_Updater.php:190/226/280/322: variable $key is never used
> /includes/GitHub_Updater/GitHub_API.php:161: variable $num is never used

Thanks, I think I've fixed these references locally.

> /includes/GitHub_Updater/Theme.php:167: variable $theme_name is never used

This piece came directly form core. While I know it's not used I think I'm going to leave it as it really doesn't add to overhead and someone else looking at this code may use it in the future.

> (There are others but they are legitimate, e.g. Theme.php:317 $url).

I think I found a way to fix this too.

**Comment by daniel-menard** [comment]
Thanks for your answer,

I will try to do some PR, but I really miss time for now so expect some delay ;-)

**Comment by afragen** [comment]
I think I've come a long way in fixing the strings for easier translation. However, I'm sure it means many of the translations will need fixing. Sorry everyone.

@daniel-menard @fxbenard @overclokk @valeriosouza @andriiryzhkov @Adevade @hyyan

**Comment by daniel-menard** [comment]
Hi Andy!

I'm really sorry for not finding time for a PR as I intended to do.

I had a look at the updated pot file and it looks good to me. You achieved to fix everything: no more redundancy, no partial sentences and so on. Congrats for the good work!

I will update the french translation as soon as possible.

Cheers,

Daniel

**Comment by fxbenard** [comment]
@daniel-menard PR #185 ready to test ;)
Cheers
FX

**Comment by daniel-menard** [comment]
@fxbenard Good work! I left [some comments](https://github.com/afragen/github-updater/pull/185#issuecomment-78893224).

**Comment by overclokk** [comment]
#187 Italian update done :-)

**Comment by afragen** [comment]
Just updated the .pot file. Hopefully strings are simpler and variables are fewer in each string.

**Comment by overclokk** [comment]
Ok, I have downloaded your dev repo because mine was not updated, hope I have not messed something :-)

**Comment by afragen** [comment]
Mine would be most recent.

**Comment by Adevade** [comment]
Updated Swedish translation coming this week.
