### ISSUE TITLE
New Feature: Add ability to install plugins or themes

### ISSUE THREAD

**Issue by afragen** [afragen/github-updater#153]
An interesting new feature would be to add the ability to install plugins or themes. WP Pusher is doing this. We already do most of the heavy lifting and an install page could just have the `<owner>/<repo>` and the `branch`.

Installing a GitHub private repo would require a separate field for an access token. Installing a Bitbucket private repo should just require `read` privileges and the Settings page filled out with Bitbucket user/pass.

Plugins/Themes would update if they have the appropriate header URI for GitHub Updater.

Let me know if you're interested.

@GaryJones @thomasgriffin looks like something that you've already done in https://github.com/thomasgriffin/TGM-Plugin-Activation/blob/master/class-tgm-plugin-activation.php

**Comment by lmoffereins** [comment]
Great idea! Once implemented, you have only one GitHub hosted plugin to upload manually, the rest would be done through this process.

Some time ago I tried to setup my own implementation that required a user/organization's name and then searched its repos for plugins and themes, but the GH API limit was hit real fast. Requiring a repo name would solve that, but it requires users to know what they're looking for.

**Comment by afragen** [comment]
Searching GitHub can be done with @pdclark's https://github.com/pdclark/github-plugin-search

I'll see what I can get started with this weekend. I have some free time.

**Comment by afragen** [comment]
Please see latest push to `develop` and take it for a spin. Feedback appreciated.

Private repos not supported at this time though I think all the code's in there, at least for GitHub Access Tokens.

**Comment by afragen** [comment]
Private repos are now fully supported! Please try to break and let me know the outcome.

BTW, plugin/theme URI may be full or short form, `https://github.com/afragen/test-plugin` or `afragen/test-plugin`

**Comment by lmoffereins** [comment]
Unrelated to installating from repos, but I found an error showing in Settings > Bitbucket Private Settings in the input field for Bitbucket Username:

```<br /><b>Notice</b>:  Undefined index: bitbucket_username in <b>/<xxx>/wp-content/plugins/github-updater/classes/GitHub_Updater/Settings.php</b> on line <b>351</b><br />```

and Bitbucket Password:

```<br /><b>Notice</b>:  Undefined index: bitbucket_password in <b>/<xxx>/wp-content/plugins/github-updater/classes/GitHub_Updater/Settings.php</b> on line <b>351</b><br />```

I do not have any Bitbucket related plugins/themes in my installation.

Btw, would you mind giving password input fields the `type="password"` attribute?

**Comment by lmoffereins** [comment]
A suggestion for Installing Plugins/Themes: remove the 'Private Repo' checkbox and assume it's private when the 'GitHub Access Token' contains a value.

**Comment by lmoffereins** [comment]
Are you familiar with the `Download failed. Forbidden` install message? Happens on both updating and installing with GHU.

**Comment by afragen** [comment]
@lmoffereins I think I know how to fix the PHP notice.

What does giving a `type=password` do? I'll look it up too and it shouldn't be a problem.

The Private Repository checkbox is really only for Bitbucket repos, no effect for GitHub repos. I'll see what I can do but a better label will help. If someone can figure out some simple JavaScript to show that setting when the drop down is 'Bitbucket' that would be great.

The `Download failed. Forbidden` happens when you've been pounding the GitHub API :wink:  What happens is that you have reached GitHub's 60 unauthenticated check sper hour against the API. There's nothing to do but wait an hour.

**Comment by lmoffereins** [comment]
Ever attempted to have GHU return a dedicated feedback message when the the API limit is reached, instead of WP's? Don't know if it is at all possible, but that would be much more valuable when using GHU :)

Concerning JS, unfortunately WP's Settings API does not identify the setting's `<tr>` wrapper, but here is a little script that might work, when you either add the `github-setting` or `bitbucket-setting` class to the `<input>` elements (to identify the targeted settings):

```js
<script>jQuery(document).ready( function($) {
   $( 'select[name="github_updater_api"]' ).on( 'change', function() {
      // Show/hide all settings that have the selected api's class. 
      // this.value equals either 'github' or 'bitbucket'
      $( '.form-table tr' ).hide().find( 'input.' + this.value + '-setting' ).parents('tr').show();
   });
});</script>
```

**Comment by afragen** [comment]
@lmoffereins I've created a new branch `js-settings` to work this out. I've added the js and all I succeed in doing is permanently hiding the checkbox for private Bitbucket repos. Can you take a look?

> Ever attempted to have GHU return a dedicated feedback message when the the API limit is reached, instead of WP's? Don't know if it is at all possible, but that would be much more valuable when using GHU :)

I'm not sure there's a callback to hook into but if there is I'll gladly create some sort of error message.

> Btw, would you mind giving password input fields the type="password" attribute?

Done. https://github.com/afragen/github-updater/commit/c2ec47fc845cbbbae0003bababee0d197db3a22b

**Comment by afragen** [comment]
Feature complete in v4.1.0

@lmoffereins I'm leaving this open if you have any further thoughts on the `js-settings` branch, or we can move to a new issue.
