### ISSUE TITLE
Refresh time lag even after clicking 'Check Again'

### ISSUE THREAD

**Issue by gyrus** [afragen/github-updater#154]
Searching on this issue - an apparent time delay between a new version being tagged on GitHub and the update being ready to go in a WP install - it always seems to be answered with 'Press the Check Again button'.

However, in my experience, Check Again is no guarantee. Generally this doesn't bother me too much - I usually update my sites via InfiniteWP every few days, and any GitHub-hosted plugins come round eventually.

But one of my main reasons for using this plugin is I have a bunch of my own plugins here on GitHub. And when I'm working on one of those, I invariably have to fire up FileZilla to get updates on staging or production. I press Check Again a few times, give up, open FileZilla.

Is there any way of debugging this? Or anything else that might be holding the check up?

**Comment by afragen** [comment]
We cache transients for 12 hours. Clicking 'Check Again' deletes the transients so GitHub's API will be polled again. If you have to use FileZilla then I am failing you. Do your repos not update or just not quick enough for your liking? I will say that GitHub has a 60 check per hour hard limit against its API for non authenticated checks. If you keep choosing Check Again you may be hitting this limit as well.

If there's a particular repo I can check against I'll be happy to troubleshoot. Other than my cache, which is cleared with Check Again and GitHub's 60 check per hour on its API, there shouldn't be anything holding it up. I have found that I might need to refresh the core-update.php page once or twice to have updates show. I don't know why but occasionally this works.

**Comment by gyrus** [comment]
Many thanks for the quick response. I think I missed a trick here - the updates are *silent*?

I just created a really simple test (https://github.com/gyrus/test/ - it just outputs its version to the Twenty Fifteen footer). I changed the version in the code, committed, tagged, pushed, and when I went to Updates in WP and pressed Check Again, the plugin wasn't listed in the updates list - but when I looked at the main plugins list, it'd been updated.

Actually, I pushed another version increment, then refreshing the front-end page saw an increment to the version in the footer. It seems to be updating whenever it can, even on a page refresh.

I've gone from one end to the other - concerned that I'm not getting updates quick enough to concerned I'm getting them too quickly! :-D  Is this the intended behaviour? Sorry if I've misunderstood...

**Comment by gyrus** [comment]
If this is the intended behaviour, I was simply looking for the plugin in the 'update available' list, and assuming it wasn't being picked up.

**Comment by afragen** [comment]
I'll have some time tomorrow to take a closer look.

**Comment by afragen** [comment]
@gyrus sometimes the updates show right away and sometimes they will show if you simply refresh the page a time or two. If you have already clicked 'Check Again' don't continue to do so as it will likely exacerbate the problem.

Updates to the plugin will still only happen if you manually select to update. If you have a setting in `wp-config.php` that sets automatic updating of plugins, that may be what you're seeing.

**Comment by gyrus** [comment]
Thanks Andy. Unselected automatic updates aren't as much of an issue as delayed updates for me, but it still seems to be an issue. The only constants I've added to `wp-config.php` are:

    define( 'FS_METHOD', 'direct' );
    define( 'WP_LOCAL_DEV', true );

Which setting is supposed to force automatic updating of plugins? None of the wordpress.org plugins are updating automatically.

**Comment by afragen** [comment]
Nothing in the plugin should cause automatic updating. It will only show that an update is available.

**Comment by afragen** [comment]
@gyrus I tested locally using your test plugin and updates occurred as expected. Is the issue that you're not seeing the actions of the plugin? That's a different issue. Let me know if there are any other problems.

**Comment by afragen** [comment]
I think this should be fixed in https://github.com/afragen/github-updater/commit/bb2a1617782685a6c7c6fc270c0143e92b899fac

**Comment by gyrus** [comment]
Seems to be working well now, many thanks.

**Comment by afragen** [comment]
Great. Thanks for the follow up.

**Comment by JulianKingman** [comment]
Sorry for commenting on a super-old issue, but I seem to have this problem. Sometimes the updates aren't available for an hour or more, I can't figure out exactly what is causing the delay, but I have a pretty bare-bones system and I get the same results with or without additional plugins or non-default themes. Other times, the updates are available instantly. If things are updated on Github correctly, what could be causing such a delay?

**Comment by afragen** [comment]
The plugin stores transients for 12 hours but can be refreshed using the _Refresh Cache_ button in Settings.

**Comment by JulianKingman** [comment]
Yes. Sorry if I wasn't clear, I'm aware of the transients and cache-clearing. My issue is that there is still sometimes a delay, is there anything else that could contribute to a delay? Does the API call generally go through instantly or...?

**Comment by afragen** [comment]
An API call can sometimes take a 1 second at most. There are anywhere between 1 and 6 API calls per plugin. If you don't have a personal access token set, you can be subject to GitHub's API rate limit of 60 API calls per hour.

**Comment by JulianKingman** [comment]
I have an access token set. Oh, I have an idea, what actually triggers the plugin to check for the update? If it uses `wp_cron`, it might be because of that. If I remember right, `wp_cron` isn't a real cron function, and has to be triggered by a wordpress action, such as a pageview. Could that be it?

**Comment by afragen** [comment]
If you don't use the _Refresh Cache_ button then yes, the same wp-cron job that updates plugins normally is piggybacked.
