### ISSUE TITLE
Renaming folders

### ISSUE THREAD

**Issue by unetics** [afragen/github-updater#155]
Similar to #18 have been using GHU for a wile now working great (thank you) but since the last update it is rename theme folders i.e. "ECHO" from my Github account becomes "unetics-ECHO-0cb12ab" causing havoc with parent child theme relationships.

**Comment by afragen** [comment]
The renaming function should be handling this. Are you using GitHun Updater through a service it directly in the admin dashboard?

Can you share the repo URI? In testing this still functions but it is one one the functions I add code to. Can you make sure the latest develop branch is being used.

**Comment by afragen** [comment]
Shoot, I see this on a live site but it didn't appear in local install. Sorry, I broke, I'll fix.

**Comment by afragen** [comment]
@unetics please update latest `develop` branch v4.0.0.5 and let me know if it's fixed. Thanks and sorry.

**Comment by unetics** [comment]
thanks yeah seems to be woking with new version (only tested 1 update so far)i will let you know if i run  into any problems updating the others

**Comment by afragen** [comment]
Thanks for letting me know about it. Reopen this if there's another problem.
