### ISSUE TITLE
Cannot activate - Fatal Error

### ISSUE THREAD

**Issue by chris-agims** [afragen/github-updater#157]
I've installed this plugin on multiple sites, but as I tried to activate it on one site, I got this:

> Plugin could not be activated because it triggered a fatal error.
> 
> Parse error: syntax error, unexpected T_STRING in [directory tree here]/wp-content/plugins/github-updater-develop/github-updater.php on line 47

I don't know if this makes any difference but the WP install is located in a subdirectory vs. in the root while we work on development.

**Comment by afragen** [comment]
Hey @chris-agims you do realize you've installed the `develop` branch and it now **requires PHP 5.3**.

Can you confirm that you're on PHP 5.3 or greater?

**Comment by zanetaylor** [comment]
I ran into the same problem after updating to 4.0.0 from WP. To clarify, as of 4.0.0, the master branch requires PHP 5.3 as well, correct? My site was on 5.2.

**Comment by chris-agims** [comment]
@afragen I was thinking I was running 5.3.x but apparently I'm on 5.2.x

**Comment by chris-agims** [comment]
@afragen That was it - updated to 5.4.x and had no problems!  Thank you sir!

**Comment by afragen** [comment]
@zanetaylor you are correct. As of v4.0.0, PHP 5.3 or better is required.
