### ISSUE TITLE
Bitbucket private repo plugin installs fail

### ISSUE THREAD

**Issue by jr00ck** [afragen/github-updater#158]
Steps to reproduce:

1. Go to "Settings" tab of plugin
2. Enter your Bitbucket login credentials (I used a login that has readonly access to the plugin)
3. Click "Save Changes"
4. Go to "Install Plugin" tab
5. Enter plugin URI of private repo plugin
6. Switch "Remote Repository Host" to "Bitbucket"
7. Check the box for "Private Bitbucket Repository"
8. Leave other fields alone/blank
9. Click "Install Plugin"

Error comes back:
The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature

**Comment by afragen** [comment]
It sounds like you're doing everything correctly.

Can you re-enter and save your password and make sure you have `read` access to the repo.

If yo give me your Bitbucket user I can give you read access to my `afragen/test-bitbucket-private-plugin`

**Comment by jr00ck** [comment]
I re-entered and saved the password and I do have read access to the repo.

The username for this readonly account I'm using is freeup_readonly

**Comment by afragen** [comment]
Very strange. I have given that user `read` access to the above private repo. Could you show some screenshots of the settings tab and the install tab before you press e button to install?

**Comment by afragen** [comment]
I think I see the problem. A quick workaround is to manually install https://bitbucket.org/afragen/test-bitbucket-plugin/branch/master its an empty plugin. You don't need to activate it. I found what I need to do is to instantiate the Bitbucket_API class.

After install that plugin you should be able to remote install.

**Comment by jr00ck** [comment]
Awesome! It works when your test plugin is installed (not activated). But doesn't work when it's not installed.

**Comment by afragen** [comment]
I just pushed `develop` v4.0.1.1

Remove the test-bitbucket-plugin. All should now be working.

Tricky bug. As I have multiple test plugins and themes from Bitbucket, in my site `class Bitbucket_API` was always loaded. If the class wasn't loaded GitHub Updater couldn't get to the `maybe_authenticate_http()` and so the password wasn't being passed for the remote install.

I now create a new instance of `Bitbucket_API` before the remote install and now it works.

Thanks for alerting me to the bug.

**Comment by jr00ck** [comment]
Bam! Working like a charm after the latest 4.0.1.1 update. Thanks for all the hard work. Love this plugin.

**Comment by afragen** [comment]
Fabulous! Tell all your friends. :smile:
