### ISSUE TITLE
ERROR: options page not found.

### ISSUE THREAD

**Issue by mattradford** [afragen/github-updater#159]
I've installed 4.0.1.1 and I'm getting "ERROR: options page not found." after I enter my Bitbucket username and password.

The user credentials are saved, and I've installed a theme from a private BB repo (which is cool, thanks!). So it works but something's not quite right. Running WP 4.1.

**Comment by afragen** [comment]
Not sure what to make of that. Is this a consistent error? Can you upload an image of th error?

Are you running in a single site or multisite? I test on both and on current release and latest alpha.

Is the error reproducible?

**Comment by afragen** [comment]
It seems the answer is here, http://codex.wordpress.org/Function_Reference/register_setting

I'll see what I can do for a fix, especially if it persists.

**Comment by w33zy** [comment]
@afragen I am getting the same error too...
This a new (first) install of the plugin and new install of WP, it is a reoccurring error that appears after I enter my BitBucket account details and click "save changes".

Here is a screenshot http://imgur.com/ymzdHAp

I can provide with any additional details you may need

**Comment by afragen** [comment]
So this occurs every time you save from the settings tab?

**Comment by w33zy** [comment]
Yeah, I am going to try it in a local WAMP install...

**Comment by afragen** [comment]
I think I see how to fix this. Definitely tomorrow as I'm on call tonight.

**Comment by afragen** [comment]
@mattradford @w33zy I just made a change in where `register_settings` is called. Hopefully that will remove this error. Update to v4.0.1.2 and please let me know as this seems to be the last/only blocker to release.

Thanks.

**Comment by w33zy** [comment]
@afragen I just updated and everything is good now. It works.

**Comment by afragen** [comment]
Thanks. I think it's time to tag.
