### ISSUE TITLE
GitHub Updater logo

### ISSUE THREAD

**Issue by afragen** [afragen/github-updater#160]
Sorry, I can't really draw to save my life. If someone/anyone wants to create a logo it would be much appreciated.

**Comment by vladimirlukyanov** [comment]
![logo](https://cloud.githubusercontent.com/assets/2518266/6222748/b302406c-b66a-11e4-90cc-02d999f1fb44.png)

**Comment by afragen** [comment]
Thanks but I'm sure there would be copyright issues. :stuck_out_tongue_winking_eye:

**Comment by afragen** [comment]
Closing as I've contacted a couple of designers.
