### ISSUE TITLE
403 forbidden requests by GHU

### ISSUE THREAD

**Issue by scarstens** [afragen/github-updater#161]
GET
https://api.github.com/repos/afragen/github-updater/contents/github-updater.php
?ref=master

gives me an error, there are several errors like this on my install, but this one is directly related to GHU.

**Comment by scarstens** [comment]
looking closer, I feel like there is a space in the URL between php and ?ref=master causing the issue.

**Comment by afragen** [comment]
Seth,

The 403 error is usually when the GitHub API is hit more that 60x/hour. If the endpoint were bad you should get a 404. I usually encounter this when testing.

Let me know if this persists.

Andy

**Comment by scarstens** [comment]
ah your right. apparently this is happening when the transient is failing to be set, trying to find out why now

**Comment by afragen** [comment]
I don't set a transient for a 403 error. If I did updates would take 12 hours instead of one.

**Comment by scarstens** [comment]
sorry I didn't mean that it was an error on your end. marking as "complete". Do take note that if the config for the site is setup in a way that "transient cache is broken" it will fail the transient call and blow the api limit every 20 seconds.

**Comment by afragen** [comment]
How can a site be setup with a broken transient cache? The Transient API just stores values in the database that auto expire.

**Comment by scarstens** [comment]
no, hosting companies that run fast wordpress sites use memcache... but thats a whole other conversation!
