### ISSUE TITLE
Plugin folder not renamed after update

### ISSUE THREAD

**Issue by EusebiuOprinoiu** [afragen/github-updater#162]
Hello! I found a bug with the plugin update.
When the update is triggered from the plugin details modal, the folder is not renamed. The new plugin folder remains GitHubUsername-PluginName-AccessToken.
If the update is triggered by selecting the plugin and using the update function from the Bulk Actions dropdown, everything works as it should.

I also noticed the update notification appears only on the Plugins page when Jetpack is active. (No updates appear on the Updates page)

**Comment by afragen** [comment]
Thanks for the report. Update to follow.

**Comment by afragen** [comment]
Can you test latest develop branch? New changes should rename correctly under all circumstances.

**Comment by EusebiuOprinoiu** [comment]
Thank you, Andy! The version from development works as it should!

**Comment by afragen** [comment]
Great. This has been tagged and released too.
