### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by apysais** [afragen/github-updater#164]
Hi, I use your plugin, however in the bitbucket i get a 403 forbidden error, any help?

thanks and regards

allan

**Comment by afragen** [comment]
You must be trying to update a private Butbucket repo. You will need to make sure you have a user and password in the Settings page for a user with `read` access to the repo and you will need to check the box next to the plugin's name indicating the repo is a  private repo.

**Comment by apysais** [comment]
yes its a private repo, and I provide my username and password, and im the owner of the said repo

**Comment by apysais** [comment]
i try to add a user and give read only access, and i give it a try, still its 403

**Comment by afragen** [comment]
Can you post an image of the settings screen?

**Comment by afragen** [comment]
It should be a 401 error

**Comment by afragen** [comment]
Can you give me temporary read access. My username is afragen on Bitbucket.

**Comment by apysais** [comment]
here is the settings 
http://i.imgur.com/XllubRi.png

the plugin tab
http://i.imgur.com/XTgZZzw.png

the forbidden page
http://i.imgur.com/8ZGHnHd.png

**Comment by apysais** [comment]
ok ill give you read access, hold on

**Comment by apysais** [comment]
I have added 'afragen' please let me know if you receive the invitation

thanks

**Comment by afragen** [comment]
Your Bitbucket username is `allan_paul_casilum`
You should enter that and not your email as the username.

**Comment by apysais** [comment]
ah i see, thank you, i will try

**Comment by afragen** [comment]
If that works you can remove the read access for me.

**Comment by apysais** [comment]
it didn't work, i still get forbidden :(
http://i.imgur.com/jzVWX2j.png

does it work on your end?

**Comment by afragen** [comment]
![screenshot_01](https://cloud.githubusercontent.com/assets/1296790/6343913/8112be70-bba5-11e4-9497-8063328b1a8d.png)

**Comment by apysais** [comment]
wow that didn't happened to me :( i mean, what is the problem in my end? after install plugin there is this FTP then after putting FTP credentials it redirects to bitbucket but 403

**Comment by apysais** [comment]
is this correct data ? http://i.imgur.com/XTgZZzw.png

**Comment by afragen** [comment]
yes that data is correct. Make sure your password is entered correctly.

**Comment by afragen** [comment]
I don't see FTP credentials on my end, they are probably FTP credentials to your web site. Make sure those are entered correctly as well.

**Comment by apysais** [comment]
i entered both credentials correctly, in fact I try to update my WP and FTP prompt me, and it works as I believe I put correct credentials both bitbucket and FTP

my WP is MU will that works?

**Comment by afragen** [comment]
My WP is MU too.

**Comment by apysais** [comment]
:( i really don't know what cause this problem, anyway thanks for the time , I really appreciate it

**Comment by afragen** [comment]
No problem. Is it possible you have a permissions issue for the plugins directory? Have you had this issue when adding a plugin from the .org repo?

**Comment by apysais** [comment]
hmm seems legit question, let me change the permission of 'plugins' but if its coming from 'FTP' php it should update..

it seems I have no problem installing plugin coming from .org repo

still I will try that

**Comment by apysais** [comment]
the folder 'plugins' is set to 777

**Comment by afragen** [comment]
If you have no issues installing from .org it shouldn't be that

**Comment by apysais** [comment]
yeah weird, i dont know the problem

**Comment by afragen** [comment]
Can you post a pic of the screen asking for FTP creds?

**Comment by apysais** [comment]
after clicking the 'Install Plugin' here is what I get, prompted by FTP
http://i.imgur.com/3GVD99e.png

**Comment by apysais** [comment]
the forbidden page stops here http://i.imgur.com/8ZGHnHd.png

**Comment by afragen** [comment]
Sorry, I've just never encountered a FTP page asking for credentials. Do you have `define('FS_METHOD', 'direct');` in your `wp-config.php`?

**Comment by apysais** [comment]
I will check that

**Comment by apysais** [comment]
No i dont have that 'FS_METHOD' defined

**Comment by afragen** [comment]
http://codex.wordpress.org/Editing_wp-config.php

**Comment by apysais** [comment]
wow this did the trick

define('FS_METHOD', 'direct'); 

thank you a lot!

**Comment by afragen** [comment]
Excellent! Glad it's working. Have a great evening. Well, it's evening here. :wink:

**Comment by apysais** [comment]
thanks, good night doc ;)

**Comment by afragen** [comment]
Good night Allan
