### ISSUE TITLE
how to update / pull

### ISSUE THREAD

**Issue by apysais** [afragen/github-updater#165]
How do I update the plugin, I have push codes in bitbucket, now how do I update or pull them in the plugin? thank you again :)

**Comment by afragen** [comment]
Make sure you have the `Bitbucket Plugin URI:` correctly in your plugin's header. A version number bump should triggers an update notice. Transients are set for 12 hours. You can test the update by decreasing the version number of the plugin in your site,

**Comment by apysais** [comment]
in my case 'https://bitbucket.org/allan_paul_casilum/masterdigm' correct right? thanks again

**Comment by afragen** [comment]
I find it better if your main plugin is named exactly as your repo like, `github-updater/github-updater.php`

**Comment by afragen** [comment]
So main plugin file named `masterdigm.php`

**Comment by apysais** [comment]
hmm so i should have a repo of 'allan_paul_casilum/masterdigm-api/masterdigm-api' as my main plugin file name is 'masterdigm-api.php'

**Comment by afragen** [comment]
Or just change the plugin name

**Comment by apysais** [comment]
thanks again, i did rename the main php into masterdigm.php, ill just observe if pass 12 hrs I get update

again thank you

**Comment by afragen** [comment]
You don't have to wait 12 hours. You can use the 'Check Again' button from the main update page to clear the transients.
