### ISSUE TITLE
Hitting GitHub API request maximum - multiple sites on same server

### ISSUE THREAD

**Issue by mlteal** [afragen/github-updater#166]
Wondering if anyone else has run into this issue: we've got multiple sites on the same server checking for updates and this seems to be maxing out the 60 API requests each hour, so I end up getting access denied errors by the time I go in to actually update the plugin. The plugin accessing a private repo (using an API key) doesn't have this issue. 

@afragen can we add an option to enter an API key for the plugin to use? Happy to work on this/do a pull request.

**Comment by afragen** [comment]
I hit this all the time in testing and as I have multiple sites on same server ( shared host ). One of the reasons I just put in a warning message to see in the dashboard so you can tell.

I'd love to work with you on a PR for an API key for GitHub. At least that would bring the number up to 5000 requests per hour.

**Comment by afragen** [comment]
The problem is that Deploy Keys are ssh keys and not access tokens. As far as I can tell you cannot create an access token for a public repo. That's our problem.

**Comment by mlteal** [comment]
Ah, that makes sense. I was looking through the plugin code earlier today so I'll see if I can come up with something to actually take action with. At least I know we're not the only ones running into this, though!

**Comment by afragen** [comment]
At least now on the develop branch you get a warning. Before I woukd have to snoop the code in Query Monitor to see the 403s.

**Comment by afragen** [comment]
Maura, how do you like the new error message. Update `develop` to see.

**Comment by mlteal** [comment]
That's looking really nice! When I uploaded the plugin to one of my staging sites I actually briefly saw an API key field for GitHub Updater in the settings page there... must have been a weird caching thing. I dropped one of my keys in there and the 403 error for the plugin went away (but so did the field). 

Not going to be able to test more tonight but I'll get the development branch running on a few more dev sites tomorrow and see if I can replicate :)

**Comment by afragen** [comment]
That field is for the access token. It will be visible for private repos only, but can be visible if the repo's meta data hasn't been retrieved.

This is because the default is to think the repo is private and downloading and caching the repo meta will show the real value.

**Comment by afragen** [comment]
> That's looking really nice! When I uploaded the plugin to one of my staging sites I actually briefly saw an API key field for GitHub Updater in the settings page there... must have been a weird caching thing. I dropped one of my keys in there and the 403 error for the plugin went away (but so did the field).

That may cause problems. I'll have to add a function to clear "tokens" from public repos if this does cause issues. I'll have to test.

**Comment by afragen** [comment]
Hey Maura, the latest develop branch now includes the time until the rate limit is reset. I think it will be more useful.

**Comment by afragen** [comment]
A special branch named just for you.

**Comment by afragen** [comment]
Now merged into `develop`
