### ISSUE TITLE
Parse error:

### ISSUE THREAD

**Issue by ashraf-ali-ca** [afragen/github-updater#173]
Parse error: syntax error, unexpected T_STRING in/public_html/wp-content/plugins/github-updater-4.1.3/github-updater.php on line 47

**Comment by afragen** [comment]
Please check your version of PHP and report back please.

**Comment by bradmkjr** [comment]
Experienced same issue, was related to Cpanel being set for 5.2, changed to 5.3 plugin issue resolved. May need to consider adding a version check with an alert to prevent this error?

**Comment by afragen** [comment]
New PHP version check should fix this.
