### ISSUE TITLE
Plugin won't work in situations where super admins do not have update_plugins or update_themes.

### ISSUE THREAD

**Issue by scofennell** [afragen/github-updater#174]
I'm really intrigued by this plugin -- looks like fantastic work for a common problem.  However, I have an issue with it on my environment because we have some restrictive settings around roles & caps, even for super admins.  I had to change Base.php to this, near line 92, to get it to work:

	/**
	 * Instantiate GitHub_Updater__Plugin and GitHub_Updater__Theme
	 * for proper user capabilities.
	 */
	public static function init() {
		if ( current_user_can( 'manage_network' ) ) {
			new Plugin;
		}
		if ( current_user_can( 'manage_network' ) ) {
			new Theme;
		}
		if ( is_admin() && ( current_user_can( 'manage_network' ) || current_user_can( 'manage_network' ) ) ) {
			new Settings;
		}
	}

Whereas before, that block was:

	/**
	 * Instantiate GitHub_Updater__Plugin and GitHub_Updater__Theme
	 * for proper user capabilities.
	 */
	public static function init() {
		if ( current_user_can( 'update_plugins' ) ) {
			new Plugin;
		}
		if ( current_user_can( 'update_themes' ) ) {
			new Theme;
		}
		if ( is_admin() && ( current_user_can( 'update_plugins' ) || current_user_can( 'update_themes' ) ) ) {
			new Settings;
		}
	}

I think a good solution for you might be to check for is_super_admin().  If so, you get the keys to the castle.

**Comment by afragen** [comment]
I don't understand. A super admin has `update_plugins` and `update_themes` capabilities.

**Comment by scofennell** [comment]
Hi!

Normally they do, but Wp Engine is different ... I think.  Or maybe just our environment is different because we have a lot of super admins and we have some restrictions in place at the wp-config.php level.

So, I guess what I'm hoping for is one of two things:

1) Take pity on me and others like me, and give super admins access by default.
2)  Rewrite that function such that the result of current_user_can() passes through a filter, and so therefore I will be able to write a plugin of my own to filter that.

**Comment by afragen** [comment]
Are you certain that WP Engine is different? Is there any way to ask? I've had WP Engine users in the past and it think there might have been a caching issue.

**Comment by scofennell** [comment]
That's a good point -- I will ask their support staff to help be sure about what's going on.

WPE can be very cachy, but I don't think this is a cache issue.  As soon as I changed those caps, I was able to use the plugin.

**Comment by scofennell** [comment]
Okay, here is a pull request that seems to be working well.  I am able to handle permissions from a child theme or other plugin, which is what we need:

https://github.com/afragen/github-updater/pull/176

**Comment by afragen** [comment]
So question? Is this a WP Engine thing or something set up in your `wp-config.php`?

If in `wp-config.php` it might be simpler just to check `is_super_admin()`

**Comment by scofennell** [comment]
Sorry for jumping to the conclusion that this was a WPE thing.  It's not, it's because of our wp-config and probably not at all common.

Just checking for is_super_admin() in wp-config might not suit us, because we have a lot of super admin's who might not have a grasp on all the buttons they have access to.  All that said, I'm happy to close this and just work out any details on the pull request thread.
