### ISSUE TITLE
Variable named class

### ISSUE THREAD

**Issue by szepeviktor** [afragen/github-updater#182]
```php
new $class_loader( $root, $extra_classes );
```

A variable named function/class looks like malware. `$a='ev'; $b='al'; $c=$a.$b; $c('php code');`

**Comment by afragen** [comment]
Even when that variable is defined in the line preceding line? I get the point. :wink:

**Comment by szepeviktor** [comment]
https://github.com/btoplak/Joomla-Anti-Malware-Scan-Script--JAMSS-/issues/8

**Comment by szepeviktor** [comment]
**off:**
@afragen This is a new frontend debugger:
https://wordpress.org/plugins/frontend-debugger/
Maybe it proves useful.

**Comment by szepeviktor** [comment]
Isn't it item #3 here https://github.com/afragen/github-updater/blob/develop/CHANGES.md#430?

**Comment by szepeviktor** [comment]
Yes, it is. https://github.com/afragen/github-updater/commit/eb2a8877dfb16335faddfb6f1fd3363405e07e23
Somehow reverted.

**Comment by szepeviktor** [comment]
Reverted here https://github.com/afragen/github-updater/commit/04c5b01f0041484139259da1e9ae0e8c95f06632

**Comment by szepeviktor** [comment]
Please consider developing Travis CI. Only a basic unit testing...

**Comment by afragen** [comment]
I just saw that. I've done some refactoring and will push a fix with that soon.

I'm very open to unit testing. I just don't really know how to go about it. PRs welcome.

**Comment by szepeviktor** [comment]
Simply call your own functions and test the returned values.
https://phpunit.de/getting-started.html
