### ISSUE TITLE
off: Option debugging

### ISSUE THREAD

**Issue by szepeviktor** [afragen/github-updater#191]
https://github.com/szepeviktor/option-inspector
Go to Settings / Options and click on a serialized option.

@afragen I hope it'll be very useful.

**Comment by afragen** [comment]
Thanks. I'm using PHPStorm so debugging is much easier.

**Comment by szepeviktor** [comment]
Phpstorm can see into wp-options?

-- 
+36204242498
Ezen a készüléken nehéz gépelni. 
Elnézést!

**Comment by afragen** [comment]
It can after you use `get_option` :wink: 

Since that's in the code already…

I think I can also see those results in Query Monitor

**Comment by szepeviktor** [comment]
Anyway please give it a try.

**Comment by afragen** [comment]
Ok, will do

**Comment by szepeviktor** [comment]
Any comments on it?

**Comment by afragen** [comment]
It doesn't scroll vertically and some data just doesn't display. But looks promising.

**Comment by szepeviktor** [comment]
It is a fixed height Thichbox. Maybe you have a low display.

**Comment by szepeviktor** [comment]
Could you share a screenshot?

**Comment by afragen** [comment]
I'm using 11" MBA and window not full screen

**Comment by szepeviktor** [comment]
The cause is it was designed to my 1600×1200 display.

**Comment by szepeviktor** [comment]
Thickbox needs the height in pixels.

**Comment by afragen** [comment]
![screenshot_01](https://cloud.githubusercontent.com/assets/1296790/6678556/40731e1e-cbf9-11e4-8122-ec5f6594b0bb.png)

**Comment by szepeviktor** [comment]
Maybe I measure the viewport height before opening Thickbox.

**Comment by szepeviktor** [comment]
Thank you for reporting this.
https://github.com/szepeviktor/option-inspector/commit/2314f588e1d5fbf8c3c278ad8584ddad6a27d554
Yo may use GHU to update as this is not yet published to WP.org.

**Comment by szepeviktor** [comment]
Does GHU need a new tag to update?

**Comment by afragen** [comment]
It just needs a version bump unless you've already used tags, then it will need a tag.
