### ISSUE TITLE
Can't get plugin to update my plugin

### ISSUE THREAD

**Issue by chris-agims** [afragen/github-updater#197]
I can't for the life of me figure out what I'm doing wrong here.  I've got everything set up as it's supposed to be in the plugin header but I must be missing something because it's still not working.  This is what I have right now:

Plugin Name:		AGI Modal
Plugin URI:		https://github.com/chris-agims/AGI-Modal
Description:		Add a modal window that pops up when a certain point is reached.  Version 1.2.3 - Balmorhea
Version:			1.2.3
Author:			Chris G. Clapp
Author URI:		http://www.chrisclapp.com
Text Domain:		agi-modal
GitHub Plugin URI:	https://github.com/chris-agims/AGI-Modal
GitHub Branch:	master

What am I missing?

**Comment by afragen** [comment]
Try to ensure that you have at least one space after the colon in the header to aid in parsing the header data.

**Comment by chris-agims** [comment]
This is how it's set up...

On Tue, Mar 17, 2015 at 1:02 PM, Andy Fragen <notifications@github.com>
wrote:

> Try to ensure that you have at least one space after the colon in the
> header to aid in parsing the header data.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afragen/github-updater/issues/197#issuecomment-82532180>
> .
>



-- 


Chris G. Clapp
Web Developer
Join us: <https://www.facebook.com/agimarketing>
<https://twitter.com/agimarketingsol>
<http://www.agims.com/>
1370 Pullman Dr. Suite G
El Paso, TX 79936

Office: 915.590.7420
Web: www.agims.com

Confidentiality Notice: This email and any files attached or transmitted
with it may be confidential and is intended solely for the use of the
individual or entity to whom they are addressed. If you have received this
email in error please notify the sender and/or your system administrator.

**Comment by afragen** [comment]
Try decreasing you version number locally to test instead of bumping on the repo. I'll check when I get back to my computer unless it's fixed before then.

**Comment by chris-agims** [comment]
Much appreciated!

On Tue, Mar 17, 2015 at 2:12 PM, Andy Fragen <notifications@github.com>
wrote:

> Try decreasing you version number locally to test instead of bumping on
> the repo. I'll check when I get back to my computer unless it's fixed
> before then.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afragen/github-updater/issues/197#issuecomment-82577501>
> .
>



-- 


Chris G. Clapp
Web Developer
Join us: <https://www.facebook.com/agimarketing>
<https://twitter.com/agimarketingsol>
<http://www.agims.com/>
1370 Pullman Dr. Suite G
El Paso, TX 79936

Office: 915.590.7420
Web: www.agims.com

Confidentiality Notice: This email and any files attached or transmitted
with it may be confidential and is intended solely for the use of the
individual or entity to whom they are addressed. If you have received this
email in error please notify the sender and/or your system administrator.

**Comment by chris-agims** [comment]
After I tried lowering the number on my local version, nothing happened.  How soon should it be showing up?

**Comment by afragen** [comment]
It should shown if away.

**Comment by afragen** [comment]
Here's what I did.

I installed your plugin via the 'Install Plugin' under GitHub Updater Settings.
I reduced the version number locally.
I see an immediate update notification.

![screenshot_01](https://cloud.githubusercontent.com/assets/1296790/6698989/0417824e-ccbb-11e4-8f49-bac6e22851ab.png)

Here's the View details

![screenshot_04](https://cloud.githubusercontent.com/assets/1296790/6699002/1514ff7c-ccbb-11e4-8576-d1f74cb20bd3.png)

I then checked update and the plugin updated with the following message.

![screenshot_05](https://cloud.githubusercontent.com/assets/1296790/6699013/278fede2-ccbb-11e4-8920-8d0b135cc16e.png)

Did I do something different than you have done? It seems to be working.

**Comment by chris-agims** [comment]
I will try it again but I haven't gotten any update notifications.....

**Comment by afragen** [comment]
Can you show the plugin's local headers?

**Comment by chris-agims** [comment]
Where would I find those / what am I looking for?

**Comment by afragen** [comment]
The headers for the installed plugin you are trying to update.

**Comment by chris-agims** [comment]
...and all of a sudden it's working perfectly.  Don't know what changed but it works now.  :)

**Comment by chris-agims** [comment]
At this point, how long after I update the version on github will the plugin catch that there is a new version?  Right now it's catching it the next day after I've looked at the plugins page at least once.

**Comment by afragen** [comment]
The transient cache is for 12 hours. You can delete all transients by using the "Check Again" button on the core update page. Please take a glance at the README for more details, if needed.
