### ISSUE TITLE
Plugin on both GH and WP

### ISSUE THREAD

**Issue by szepeviktor** [afragen/github-updater#198]
Is there a way to switch between WP.org updates and GHU?

I have a plugin with GHU header
https://wordpress.org/plugins/plugin-installer-speedup/
and I would like to update it through WP.org.

Ofcourse besides removing the GHU header.

**Comment by afragen** [comment]
If the plugin is on wp.org and it's branch is `master` then all updates will come from wp.org :wink:

**Comment by szepeviktor** [comment]
Thank you.
Now I remember!

**Comment by pedro-mendonca** [comment]
Still related to this, is it possible that a plugin/theme that was installed with WordPress to be connected to it's github repo by github updater without haviing to uninstall it first?

**Comment by pedro-mendonca** [comment]
When a plugin have new versions both in WordPress and git repo, how can we choose wich one to load?
Themes can be reverted to older versions and choose branch, could we do the same with plugins?

**Comment by szepeviktor** [comment]
> If the plugin is on wp.org and it's branch is master then all updates will come from wp.org

**Comment by afragen** [comment]
@pedro-mendonca if the plugin installed from wp.org has both the `GitHub Plugin URI` and a `GitHub Branch` headers you can update to a branch on GitHub by changing the branch header.

**Comment by pedro-mendonca** [comment]
Thanks for your anwser. Unfortunately that would only be possible for personal forks, as no plugin use those headers.

**Comment by afragen** [comment]
Not sure I completely understand what you're wanting to accomplish.

As an example, I have https://wordpress.org/plugins/the-events-calendar-category-colors which has both headers. On normal sites I run the code from wp.org which has the branch master and updates from wp.org. On testing sites the branch is set to develop and updates from GitHub.

There is no mechanism to restore to a previous plugin version as updates are usually for a reason and previous tagged versions can be reinstalled by other mechanisms.

**Comment by pedro-mendonca** [comment]
You're right, there is no much sense in rollback a plugin, even when developing, but might be interesting to change between branches.
About connecting github to an existing plugin/theme, is t necessary to uninstall first? Might be usefull to create this connection, as some kind of Add GitHub Source to existing theme/plugin.

**Comment by afragen** [comment]
Not necessary to uninstall first. Just necessary to have a higher version number. That's why for my develop branches I use `<major>.<miner>.<patch>.<development>` as a versioning pattern.

**Comment by pedro-mendonca** [comment]
Great, just added the GitHub Plugin URI and branch, worked fine :+1:
