### ISSUE TITLE
Warning: stristr(): Empty needle in GitHub_Updater/Base.php

### ISSUE THREAD

**Issue by szepeviktor** [afragen/github-updater#200]
Please prepare for source change:
https://github.com/afragen/github-updater/blob/develop/src/GitHub_Updater/Base.php#L376

See: https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/class-wp-upgrader.php#L377-L394

My brand new plugin [does it](https://github.com/szepeviktor/plugin-installer-speedup/blob/master/plugin-installer-speedup.php#L54-L57). (when removing `-master` from GitHub zip-s)

**Comment by szepeviktor** [comment]
Count me as competition: my plugin does upload from URL, and handles GitHub `-master` in folder name. An it **is** on WP.org.

**Comment by szepeviktor** [comment]
https://wordpress.org/plugins/plugin-installer-speedup/

**Comment by afragen** [comment]
Be careful. If the .org plugin maintainers think that your plugin can install plugins that aren't histed on long they may remove it. That's why this plugin isn't there.

**Comment by afragen** [comment]
I've never seen an error  here before. What was the complete error message and how can I reproduce it?

**Comment by szepeviktor** [comment]
I've got it already.

> The short version is here: We don't permit plugins to install from NON wordpress.org sources. The "Install plugin from a URL" feature has to be removed.
> 
> You can have it check when someone uploads the zip (that is, you can have it look for -master and rename), but you cannot have it auto-install from a url at this time.
> 
> We do not permit plugins to phone home to other servers for updates, as we are providing that service for you with WordPress.org hosting. One of our guidelines is that you actually use our hosting, so we need you to remove that code.

**Comment by szepeviktor** [comment]
1. install the [violation branch](https://github.com/szepeviktor/plugin-installer-speedup/tree/violation)
2. upload a plugin zip from a GitHub repo/master branch
3. see `Warning: stristr(): Empty needle in GitHub_Updater/Base.php`

**Comment by afragen** [comment]
I'm on a run of every other day/night call but I will get to this. Just not sure when.

**Comment by szepeviktor** [comment]
After removing the violating feature, it is available as an MU plugin.
https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/mu-plugin-upload-from-url/plugin-upload-from-url.php
I suggest you to use it for testing this issue.

**Comment by afragen** [comment]
I installed as above.

First test using `https://github.com/afragen/test-plugin2/archive/master.zip`

![screenshot_01](https://cloud.githubusercontent.com/assets/1296790/6745842/8cf2a6a0-ce7a-11e4-9983-388aadf0d721.png)

Rename error due to similar plugin names.

With plugin that has no similar name works great.

![screenshot_02](https://cloud.githubusercontent.com/assets/1296790/6745861/04a77482-ce7b-11e4-8af5-2ee9f64bcb3f.png)

BTW, doesn't work under multisite installation.

**Comment by szepeviktor** [comment]
I do not know that `Renaming`. Where does it come from? WP core?

**Comment by szepeviktor** [comment]
Now I've corrected the UI.
When installing the above test plugin:
`Warning: stristr(): Empty needle in /var/www/subdirwp/server/static/plugins/github-updater/src/GitHub_Updater/Base.php on line 434`
But I have no renaming....

**Comment by szepeviktor** [comment]
Oh! Renaming is in [GHU](https://github.com/afragen/github-updater/blob/1faaf2773497ed29c9fc014794ef1de4a87fa8a2/src/GitHub_Updater/Base.php#L418)
Please do not use GHU for installing.
The problem occurs when using my MU plugin to install a zip URL.
https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/mu-plugin-upload-from-url/plugin-upload-from-url.php

**Comment by afragen** [comment]
I used your plugin for installing. The problem is corrected in GHU renaming code, not in your renaming code. I found this in my code by accident when I was installing very similarly named plugins. Example `test-plugin` installed and `test-plugin2` trying to be installed.

**Comment by szepeviktor** [comment]
I do now understand. You've just found the problem causing the above warning on `stristr`?
Please explain it to me.
My MU plugin (upload from URL) does source modification and directory renaming during plugin installation.

**Comment by szepeviktor** [comment]
I do not see your commit.

**Comment by szepeviktor** [comment]
I think both of us do source modification
https://github.com/afragen/github-updater/blob/1faaf2773497ed29c9fc014794ef1de4a87fa8a2/src/GitHub_Updater/Base.php#L348
and you do it unconditionally.

**Comment by szepeviktor** [comment]
I do it only on my admin page:
https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/mu-plugin-upload-from-url/plugin-upload-from-url.php#L28

**Comment by afragen** [comment]
I never got the stristr error

**Comment by szepeviktor** [comment]
I've just deleted all DB tables,
installed GHU from develop.zip, renamed plugin folder to `github-updater`,
installed my MU plugin,
used my MU plugin to install https://github.com/afragen/test-plugin2/archive/master.zip
Plugins / Upload from URL

You've got mail.

**Comment by szepeviktor** [comment]
This is a free preview from http://labs.online.net/

**Comment by Ipstenu** [comment]
I got this error uploading a third-party theme:

```
Installing Theme from uploaded file: author-pro.zip
Unpacking the package…

Installing the theme…

Warning: stristr(): Empty needle in /home/ipstenu/public_html/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 386

This theme requires a parent theme. Checking if it is installed…

The parent theme, Genesis 2.1.2, is currently installed.

Theme installed successfully.
```

At a guess, it's trying to rename the folder even if it doesn't have to?

**Comment by szepeviktor** [comment]
@afragen Could you take your time?

**Comment by afragen** [comment]
Thanks for the report @Ipstenu I think I understand the circumstances. During a file upload. I'll see if I can reproduce and fix.

@szepeviktor not sure I understand.

**Comment by szepeviktor** [comment]
I was talking about you finding time to invertigate this.

**Comment by afragen** [comment]
Fixed https://github.com/afragen/github-updater/commit/b8fec6974a15cc80998505cecbef66383cffc529
