### ISSUE TITLE
Any interest in GitHub Enterprise?

### ISSUE THREAD

**Issue by mdwheele** [afragen/github-updater#202]
We've forked the project to get it working on our instance of GHE and with a little more polish, that work could be contributed back upstream. The only difference between GH.com and GHE, in the case of this plugin, is the API endpoints and hostname.

We simply did a string replace and all seems to continue working for the short-term, but because of how the plugin is updating itself, I'm pretty sure it's orphaned. My next steps are going to be some small refactors to allow GHU to speak with GH.com to maintain its own updates as well as a new adapter for GitHub Enterprise and associated user interface changes, e.g. "When I select GitHub Enterprise, I can also specify a hostname to be used when constructing URIs for API requests."

If there's no interest, I'll stop short. Let me know!

Thanks

**Comment by afragen** [comment]
Yes, I'd be interested in supported GitHub Enterprise. Can you provide the endpoints?

**Comment by mdwheele** [comment]
The differences are documented here: https://developer.github.com/v3/enterprise/#endpoint-urls

It's important to allow per-user specification of hostname as this will vary case-by-case.

**Comment by afragen** [comment]
I'll probably put in a filter to adjust. Are both endpoints different in enterprise and not in regular?

**Comment by afragen** [comment]
@mdwheele try `enterprise` branch.

You will need to use the following filter.

`add_filter( 'github_enterprise', 'https://github.ncsu.edu/api/v3' );` in the `functions.php` of your theme.

If this works for you, I'll add a small GitHub Enterprise Updater plugin to use along side.

**Comment by mdwheele** [comment]
Thanks for the work @afragen! I'll poke the folks that we're interested in this and bring their feedback here. I was at a hack-a-thon of sorts and that's what spurred the request after we hacked together something that worked. 

The work on `enterprise` would suffice for a user that was writing a custom theme and wanted to override the host as you've specified. However, consider the case where I just want to install this plugin specifically to update a set of 6-7 custom plugins behind Enterprise. With this implementation, I would probably need to write a separate plugin to filter the host.  

What if when I'm installing a plugin theme; in addition to GitHub and Bitbucket, I should see an option for GitHub Enterprise. When I select GitHub Enterprise, an additional textfield is presented that is the host-name of the Enterprise installation. You are able to validate this by one or more of the following (in increasing runtime complexity):

1. Valid Hostname
2. Valid TLD (top-level domain)
3. HTTP/1.1 200 OK on ping to root
4. OK response from enterprise API root endpoint

If this were implemented, you would be able to install your plugin, have it use GitHub.com to keep itself up-to-date and in addition to all of that be able to install plugins/themes no matter if they were on GH.com, GHE or Bitbucket.

Thoughts?

Like I said, I'll send `enterprise` along to the folks that are interested in this and point them back here.

**Comment by afragen** [comment]
@mdwheele I came up with a much better solution. One that will work together with GitHub.com plugins and themes too.

Check out `enterprise-header` branch. 

All you have to do is add a header to the plugins or themes that are hosted on your GitHub Enterprise.

Ex. `GitHub Enterprise: https://github.ncsu.edu`

If you want to install a plugin from your GitHub Enterprise simply enter the URI as `https://github.ncsu.edu/owner/repo`

I think this will cover all bases. Kick the tires and let me know how it works for you guys.

**Comment by afragen** [comment]
@mdwheele have you had a chance to see if https://github.com/afragen/github-updater/tree/enterprise-header works for you?

**Comment by afragen** [comment]
@mdwheele, GitHub Enterprise support is now in the `develop` branch.

**Comment by afragen** [comment]
To maintain consistency with GitLab the new header will change from `GitHub Enterprise` to `GitHub Self-Hosted`

**Comment by afragen** [comment]
@mdwheele can you test this please and let me know. Thanks.

**Comment by mdwheele** [comment]
Seems to work for me. I've asked the consumer of this feature to check it out multiple times and they're working off the patch I made. I'll ping them again, but consider this issue closed.

**Comment by afragen** [comment]
Thanks for testing.
