### ISSUE TITLE
_site_transient_ghu-* contains the whole response

### ISSUE THREAD

**Issue by szepeviktor** [afragen/github-updater#203]
Please consider storing only the body part of the response.

**Comment by afragen** [comment]
Specifically which content are your referring to. We store only the headers for the main file but we store the whole changelog.

**Comment by szepeviktor** [comment]
![GHU transient](http://i.snag.gy/Ut4Zq.jpg)

**Comment by szepeviktor** [comment]
It seems like a WP.org plugin API response. I may be wrong.

**Comment by afragen** [comment]
Ok. I'll see what's necessary to save for that call.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by afragen** [comment]
A quick look tells me that's the API call to make sure the WP.org updates continue to work as expected. I'll take a closer look later.

**Comment by szepeviktor** [comment]
Is it resolved? Could you point out the commit?

**Comment by afragen** [comment]
It's grabbing data from wp.org and needs it to correctly populate the View Details.

No change.
