### ISSUE TITLE
Can't update theme from Bitbucket private repo

### ISSUE THREAD

**Issue by lmartins** [afragen/github-updater#205]
Hi, this is most likely due to something wrong on my part but still I can't figure it out what im doing wrong.
I have a private repo setup at Bitbucket that I've successfully installed on my site. The issue is I once I install it I can't get it to update to new changes. When I open the theme details it shows me a previous older version available to update, and once I click update it then says the theme is already at the latest version:
```
Disclosure Version: 0.2.9
By Intangible Life

Theme description	
There is a new version of Disclosure available now.  View version 0.2.9 details or update now.
```

My style.css at this point is at version 0.3.1 despite what says above.

I've tried changing both the `Version` info on `style.css` and using tags on the repo, both gave me the same result. Am I missing something here?

**Comment by afragen** [comment]
@lmartins is it possible to give me read acces so I can take a look?

**Comment by lmartins** [comment]
Hi Andy, sure, i've just sent the invitation.
Thanks.

**Comment by afragen** [comment]
@lmartins I've gotten access and installed the theme locally. I can update and rollback without issue, though the 0.3.0 tag has a version number of 0.2.9.

Can you provide more details about what in particular isn't working?

I'm using the latest develop branch.

**Comment by lmartins** [comment]
Hey Andy, thank you so much for the feedback.
Yesterday I've manage to update my theme by deactivating it, then update and reactivating it. If I try to update while the theme is enabled is just keeps saying is already up to date.

I'll have a look into the mismatch you mention and make sure to have that correct in the next attempt. I'll report back here once I have more details.

Thanks again.

**Comment by afragen** [comment]
You should be able to use the rollback link from the themes page and that tagged version will install. It should then also show you an update is available.

Can you send some pics of the themes page and GHU settings?

**Comment by lmartins** [comment]
Sorry for the delay.
I've just tried again, having the style.css and repo tag both set to 0.3.3
Still on theme details it still says that the latest version is 0.3.1.

Here are the screenshots:
![screen shot 2015-04-05 at 16 30 31](https://cloud.githubusercontent.com/assets/151981/6997380/23774fca-dbb1-11e4-9914-8b99799b2ac9.png)
![screen shot 2015-04-05 at 16 30 14](https://cloud.githubusercontent.com/assets/151981/6997381/239f32ce-dbb1-11e4-9137-2933fb41cb8f.png)

**Comment by afragen** [comment]
It also says to update now. I've seen the view detail show the wrong info even for wp.org plugins. If you click update does it update?

It's possible if you go to the core update page and click the 'Check Again' button the view details will update.

**Comment by lmartins** [comment]
It does say update available, but not only it says the new version is 0.3.1 (which is already installed), but also when I run "update now" it just says the theme was already updated.

After updating Github Updater itself, It now detects the proper version available, but when I run install I get the following error message:
```
Downloading update from https://bitbucket.org/luistmartins/disclosure/get/0.3.3.zip…

Unpacking the update…

The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature
```
This probably a different issue so let me know if you prefer I close this one.
Thanks.

**Comment by afragen** [comment]
@lmartins make sure your Bitbucket user/pass is entered and correct.

Here's what I got and it works.
![screenshot_02](https://cloud.githubusercontent.com/assets/1296790/6999312/33bd3b7a-dbba-11e4-8a79-6242d7301f7e.png)
![screenshot_03](https://cloud.githubusercontent.com/assets/1296790/6999313/3888c07a-dbba-11e4-8032-30283ff0b65c.png)

**Comment by lmartins** [comment]
@afragen I was testing this again today, this time avoiding repo tags entirely. 
I've created a repo with a theme, passing the following info info in `style.css`:

```
/*  Theme Name: Webipack Roots
	Description: Starter Theme to use with Webipack Designs
	Author: We are Multiweb
	Version: 0.1.4
	Bitbucket Theme URI: https://bitbucket.org/luistmartins/wip-roots/
	Bitbucket Branch:    master
*/
```
In the themes section, the updater seems to get confused about this:
![screen shot 2015-04-18 at 20 10 40](https://cloud.githubusercontent.com/assets/151981/7216887/42e971de-e607-11e4-8985-e968e359aa01.png)

After this I bumped the theme version to `Version: 0.1.5` and did a force updates check, now it shows:
![screen shot 2015-04-18 at 20 15 08](https://cloud.githubusercontent.com/assets/151981/7216897/a3e807a2-e607-11e4-970f-057e3c36c4b0.png)

By any means Im excluding the possibility of errors on my part, but the behaviour im getting does seem weird.

Thanks.

**Comment by afragen** [comment]
Every once in a while and I cannot explain why, after doing a force check you must load the page without the force check. I can't explain why it's just that sometimes the plugins update cache (not related to this plugin) gets purged and needs to rebuild.

**Comment by afragen** [comment]
@lmartins is this working for you now?

**Comment by lmartins** [comment]
Im not sure Andy, but i’ll give it another try and let you know.


-- 
Luis Martins
Sent with Airmail

On 29 Apr 2015 at 15:02:57, Andy Fragen (notifications@github.com) wrote:

@lmartins is this working for you now?

**Comment by zachflauaus** [comment]
I'm having the same issue with regards to private repos for plugins and themes on Bitbucket. Even after force checking, it doesn't give a notification for an update. It will install from the plugin without an issue, however.

**Comment by afragen** [comment]
Can you post the plugin's headers?

**Comment by zachflauaus** [comment]
Sure thing:

```
Plugin Name: Directory for Chambers
Plugin URI: http://www.prophecy1.com/
Description: This plugin is a directory plugin designed for Chamber of Commerce.
Author: Prophecy1, LLC
Version: 1.1.1
Author URI: http://www.prophecy1.com/
Bitbucket Plugin URI: https://bitbucket.org/prophecy1/listings-plugin
Bitbucket Branch: master 
```

**Comment by afragen** [comment]
Headers look fine. Are you creating tags? If so what's the latest tag?

**Comment by zachflauaus** [comment]
Nope, no tags here.

**Comment by afragen** [comment]
Can you give `afragen` `read` access so I can test? First try deleting all the transients by using the check again button on the Update page.

**Comment by zachflauaus** [comment]
Done. I tried the check again button but didn't work. Once I deleted transients through WP Optimize, it did come up though a bit spotty (doing just small version increments).

**Comment by afragen** [comment]
Using the Check Again will delete all the transients associated with GHU. Let me know if you're still having issues.

**Comment by afragen** [comment]
It seems to work for me locally. Transients are saved for 12 hours. If you're looking to see an update before then you will have to use Check Again.

**Comment by zachflauaus** [comment]
I think it was the 12 hours that was giving me an issue as things look to be working now.

**Comment by afragen** [comment]
Excellent, you can remove the access. Thanks for allowing it as it greatly helps me to ensure the code runs as expected in your given situation.

**Comment by bobbybouwmann** [comment]
So the solution is waiting 12 hours? I have the same issues with private Bitbucket repositories. Currently version 0.4.0 is installed while my master branch holds version 0.5.0

This is my information in style.css:
```
 * Version: 0.5.0
 * 
 * Bitbucket Theme URI: https://bitbucket.org/blackbird-development/neldi
 * Bitbucket Branch: master
```
Screenshot of version: (This should give me an update message since 0.5.0 exists)
[Imgur](http://i.imgur.com/UenFhV5.png)

**Comment by afragen** [comment]
Can we please make separate issues as it drowns out the OP.

The solution is to go the the `core-update.php` page and select the Check Again button. Then refresh the page without the `?force-check=1` in the URL.

**Comment by bobbybouwmann** [comment]
Thank you, I will create a new issue the next time ;)

**Comment by afragen** [comment]
I'm going to close this issue. If anyone is having similar issues please create a new issue. Thanks.
