### ISSUE TITLE
No updates when branch specified is other than master

### ISSUE THREAD

**Issue by SurekhaRane** [afragen/github-updater#208]
I have a network site on wp-engine, in which each theme is a repository.We use Github updater plugin to get updates from the repository.The plugin was working fine when the branch specified in styles.css was master.
But now we have done some new changes on a new(for ex develop)  branch and we want wp-engine to get updates from the new branch.So i specified this new branch in styles.css and created a tag for it.
But after doing this.I haven't received any updates on wp-engine.
Guess I am not doing it properly.

Can you please help me with the above problem?

**Comment by afragen** [comment]
Tags will only be used for the `master` branch. After changing the branch header locally you will have to clear the transients by using the 'Check Again' button.

Can you give the URI and branch you are using?

**Comment by SurekhaRane** [comment]
Repository link  - https://github.com/ajency/Homes

Branch - apt-sel-live

**Comment by franceimage** [comment]
Hi, 
This is a strange choice to limit tags to master branch. I think you should be able to follow either commits on a given branch or tags on the repository.

You can check out what I'm doing here https://github.com/franceimage/wp-alt-repositories

**Comment by afragen** [comment]
@SurekhaRane I see an issue with your how you have named your tags. You really should follow semantic versioning. The consequences are that from the `master` branch. GHU "sees" the newest tag as `push` and the remote version is 4.4.

Additionally all those tags, `v1.5.0`, `v1.4.0`, etc sort higher than `4.4`, `4.5`, etc. I'm sure this will/does cause issues.

I was able to install `apt-sel-live`, lower to version number locally, clear the transients, and then successfully update to version 4.4

**Comment by afragen** [comment]
> This is a strange choice to limit tags to master branch. I think you should be able to follow either commits on a given branch or tags on the repository.

@franceimage for most developers, `master` is the release version. Similarly, the most current tag is the release version. That is why `master` is the _only_ branch that is capable of updating to tags.

As far as I know there is no way to describe which branch is associated with a particular tag. For this reason, one of the assumptions I make is that every developer has a `master` branch and that this is the most current, stable branch. As such, it should correlate to the most current tag (if tags are used). I essentially assume a [git-flow](http://nvie.com/posts/a-successful-git-branching-model/) style of development.

If a developer doesn't want to use tags, they don't have to and this issue won't occur. The README actually attempts to make this very clear.

**Comment by afragen** [comment]
> You can check out what I'm doing here https://github.com/franceimage/wp-alt-repositories

It looks great. It took me a little while to figure out how and where to start, so I think some instructions for first time users should be in the README.

There's a great opportunity to make it work in multisite, unfortunately I don't think it will -- yet :wink:

Others will appreciate the work that goes into your project as I do. The fundamental difference between our project seems to be that yours has a more upfront, though one time, need to specifically opt in plugins or themes. Whereas this project necessitates that the developer opt their plugins or themes in allowing for less work by the user.

Keep up the great work and remember the hardest thing to tell open source contributors is _no_. Remember your vision for the project and stick to it. Of course, if your vision changes, go with it.

Take a look at my `enterprise-header` branch to see how to make GitHub Enterprise working. :+1:

**Comment by franceimage** [comment]
Thanks for your kind words. 

I took notice of your comments and implemented support for multisite

**Comment by afragen** [comment]
@SurekhaRane did you get this working properly?

**Comment by SurekhaRane** [comment]
Hello,

No.I understood that tags work only with master branch.

I tried deleting the transients but did not see anything happening.

**Comment by afragen** [comment]
@SurekhaRane can you share the URI for the repo?

**Comment by afragen** [comment]
@SurekhaRane the problem is the inconsistent naming of your tags. To avoid any problems you should use semantic versioning. Your `push` tag is sorting as the most recent and all the `V1.x.x` tags also sort differently that just `4.7`, though I don't think that will cause you an issue. To fix this you will need to delete the `push` tag.
