### ISSUE TITLE
"View details" is missing from GHU

### ISSUE THREAD

**Issue by szepeviktor** [afragen/github-updater#210]
Please add `View details` to GHU on the Plugins page.

**Comment by afragen** [comment]
Isn't it already there?

**Comment by afragen** [comment]
You mean when there isn't an update. What's the hook?

**Comment by afragen** [comment]
Watch this. Add an empty `readme.txt` file to the plugin and this will be visible. :+1:

**Comment by szepeviktor** [comment]
I do not really know what it behind `View details`, it has to do something with plugin data.

**Comment by afragen** [comment]
We already get the plugin dats, I'll have to dig into it.

**Comment by afragen** [comment]
I've spent a couple of hours digging into this and as near as I can tell, the data required to display this is added from a check to the wp.org repo when checking plugins. Simply adding the necessary data to the `update_plugins` transient doesn't work :person_frowning: 

If you can find a way to make it work I'm happy to include it but short of a filter added to core, I'm not sure this is feasible or worthwhile.

**Comment by afragen** [comment]
I think I just figured this out. But it will only work if your `Plugin URI` header points to your GitHub/Bitbucket repo. In other words 
```php
`Plugin URI` === `GitHub Plugin URI` || `Bitbucket Plugin URI`
```

https://github.com/afragen/github-updater/commit/2d020f902c113e0fe9f13e659be3e315317a20ea

**Comment by szepeviktor** [comment]
It works.
