### ISSUE TITLE
Checking "Personal GitHub Access Token"

### ISSUE THREAD

**Issue by szepeviktor** [afragen/github-updater#211]
Is "Personal GitHub Access Token" validated when updated?

**Comment by szepeviktor** [comment]
Let's say with a test request.

**Comment by afragen** [comment]
Nope. If the token is incorrect you will see a GitHub Updater error code, likely a 401.

**Comment by szepeviktor** [comment]
Yes. But not immediately after saving it.

**Comment by afragen** [comment]
But it's not used when it is saved unless it's being used during a remote install. How and more correctly, why, would or could we check the validity of an access token without it being used?

If someone mistyped an entry the error code should clue them to the problem.

**Comment by szepeviktor** [comment]
- length and character check by a regexp
- test API call: list public repos

**Comment by afragen** [comment]
If you would like to create a method that would validate an access token, I'd be happy to take a look at it.
