### ISSUE TITLE
Branch switching support problem.

### ISSUE THREAD

**Issue by pedro-mendonca** [afragen/github-updater#214]
Hi,

I've found two situations where Branch switching isn't working:

**a) repo name is case sensitive**

I've added the headers to the main php file of a plugin.
The branch switcher won't work unless I the repo name is exactly the same as the main file/textdomain.
As this plugin I'm testing have some capital letters it won´t show the new branch switcher.
Example:
https://github.com/Designmodocom/WP-Maintenance-Mode
The file is wp-maintenance-mode, if I change the `GitHub Plugin URI: https://github.com/Designmodocom/WP-Maintenance-Mode` to `GitHub Plugin URI: https://github.com/Designmodocom/wp-maintenance-mode` it works, but renaming this repo is not possible for me.

Can you make this not case sensitive?

**b) repo name must be equal to install folder**

Example:
https://github.com/elliotcondon/acf
The plugin also don't show branch support, it's because the `acf` plugin repo name is different from plugin install folder `advanced-custom-fields`.

Both cases can happen and github-updater should be able to rely on something else to work correctly.

**Comment by pedro-mendonca** [comment]
I've read in this GHU Description (https://github.com/afragen/github-updater#description) that you've described both these situations.

Are you sure it's not possible work this out even for plugins that don't follow these rules?

**Comment by afragen** [comment]
It might be that in your plugin file you don't specify the branch in a `GitHub Branch` header. Each of these should be specific to the branch. As you don't include this header all branches may appear as master.

Can you add the correct branch header to each branch and retest?

**Comment by afragen** [comment]
I'm not sure I can or want to make this case insensitive, you can install 2 plugins in WP whose directory names differ only by case. Eg it is possible to install EDD from the wp.org repo and from GitHub. All .org repo slugs are lowercase.

In your second example, that repo doesn't have any headers to make it work with GHU.

**Comment by afragen** [comment]
@pedro-mendonca I just took a closer look at your first example and the header lists as follows,
`GitHub URI: https://github.com/Designmodocom/WP-Maintenance-Mode`

That's not correct. It needs to be `GitHub Plugin URI`

**Comment by pedro-mendonca** [comment]
Yes, I know, I'm testing with `GitHub Plugin URI` customized header.

**Comment by pedro-mendonca** [comment]
About the case or even the whole slug of the plugin, some developers use a completely different names (as in acf) and others just the case (as in wp-maintenance-mode).
Could we get it to work even in those cases?

**Comment by afragen** [comment]
This feature actually came about for pods-framework/pods. They have the correct headers in the 2.x branch. If you install that branch you can switch to any other branch, but none off the other branches have correct headers so you may not be able to switch back.

The correct headers **must** be in the upstream plugin.

**Comment by afragen** [comment]
ACF installed from GitHub is different from ACF installed from .org. If installed from GitHub it will be in a directory `acf/acf.php`

**Comment by afragen** [comment]
I think my readme is overly cautious and that updating does not require the main plugin file to be named similarly to the repo name.

**Comment by pedro-mendonca** [comment]
> The correct headers must be in the upstream plugin.
Of course, I know, I've made a PR for wp-maintenance-mode just in case this gets solved. I know that as soon as I change branch I delete my custom header, but for testing purposes I can see that the problem is that the branch switcher don't even show up.

**Comment by afragen** [comment]
> Yes, I know, I'm testing with GitHub Plugin URI customized header.

But that's your local file and the upstream file doesn't have the correct header. If you want to test you can use my `test-plugin`

**Comment by pedro-mendonca** [comment]
The header that is being read is the from the installed plugin, where the `GitHub Plugin URI` must be. That one is customized by myself to simulate it being include in a future update. If somehow I update or change branch I'll loose this of course.
The main problem is that the branch switcher don't even shows up, even with the correct repo/branch headers.

**Comment by pedro-mendonca** [comment]
While the branch switcher gives this problems, the updater works fine.

**Comment by afragen** [comment]
I assume the branch switching option is checked in the settings. Can you provide some screenshots?

**Comment by pedro-mendonca** [comment]
I've customized the headers so that an update notice is shown.
```
Version: 2.0.2
GitHub Plugin URI: https://github.com/Designmodocom/WP-Maintenance-Mode
GitHub Branch: master
```

![captura de tela 2015-04-07 15 53 42](https://cloud.githubusercontent.com/assets/7371591/7025948/c21a2d4e-dd3e-11e4-9b1e-5c1d62cf1946.png)




If I change the headers to this:

`Version: 2.0.2`
`GitHub Plugin URI: https://github.com/Designmodocom/wp-maintenance-mode` (notice the case)
`GitHub Branch: master`

It will show up the branch switcher:

![captura de tela 2015-04-07 16 01 45](https://cloud.githubusercontent.com/assets/7371591/7026079/906c4b5a-dd3f-11e4-951e-76ebca46ce94.png)

**Comment by pedro-mendonca** [comment]
The same happens with **advanced custom fields**, it's loads the github icon and `master* branch link, but the branch switcher only shows up if I rename the plugin folder from the original `advanced-custom-fields` to `acf`.

**Comment by afragen** [comment]
You may have to clear the transients by using 'Check Again' after you change the headers.

I'll have a chance to test later today, but where are you installing ACF from?

**Comment by pedro-mendonca** [comment]
I've installed it from main WordPress.org repo and then customized the headers according your guidelines. The same as the example above on WP-Maintenance-Mode.

`Version: 4.4.0` (lowered the version number to check that update notices are working)
`GitHub Plugin URI: https://github.com/elliotcondon/acf`
`GitHub Branch: master`

I do always check again, the update notices and the branch switcher only appear after a couple refreshes.

**Comment by pedro-mendonca** [comment]
In this **acf** there is only one branch in the repo, but it's a valid example because as I've seen in other plugins the branch switch shows fine even with only one branch.

**Comment by afragen** [comment]
I installed https://github.com/pedro-mendonca/WP-Maintenance-Mode from the remote install on my test site. With branch switching checked, I was able to switch branches, though I am not able to switch a second time as the new branch does not have the requisite headers.

In your above example with ACF, you will likely get 2 installations of the plugin, one in the wp.org directory of `advanced-custom-fields` and one in `acf`. I haven't tested this but that's what should happen.

You should try to test with `afragen/wp-theme-tweaks` it has many branches all set up properly so you should be able to switch back an forth among them.

**Comment by pedro-mendonca** [comment]
Installing the plugins directly from the GitHub repo partially solves the problem, but I think it's better think of a solution for the original method of installing from wp.org in the first place.

Probably, if a new version is released in the wp.org official repo it would create a problem with the folder name.

**Comment by afragen** [comment]
Perhaps I'm not understanding the problem. Are you trying to have updating and branch switching work for wp.org plugins when those plugins don't have the appropriate headers already?

**Comment by afragen** [comment]
@pedro-mendonca is this now working or is there still an issue?

**Comment by afragen** [comment]
Please re-open if this is still an issue.
