### ISSUE TITLE
Bitbucket Password Stored in Plain Text

### ISSUE THREAD

**Issue by d4mation-** [afragen/github-updater#215]
Issue title says it all. The password is stored in plain text in wp_options table in the github_updater row. When you go to Settings->GitHub Updater menu page in the Dashboard you can easily Inspect Element and see the password in the "value" attribute of the text field. 

Even if the plugin is Symlinked into a mu-plugin you are still exposing your password to anyone with the capabilities in their user role to view that page as well as anyone with access to the database/can throw get_option( 'github_updater' ) into functions.php.

**Comment by franceimage** [comment]
To perform what this kind of plugin is doing, you need to keep the password unencrypted in the database; that's a fact.

A good precaution you can take is to create another Bitbucket user and give that user read access to the private repositories you want to use.
That way you never compromise your own Bitbucket account.

**Comment by d4mation-** [comment]
That's what I figured. I just looked at where the Submenu was being added to find the capability it needed and it is by default only given to Administrators (manage_options) which makes me feel better. I'm going to implement a dummy user like you mentioned.

Perhaps the password could be salted with a randomly generated salt per-install? That would make the password less easy to get a hold of.

**Comment by afragen** [comment]
@d4mation- as @franceimage pointed out the password has to be used in plain text. At some point, somewhere, it will be visible. However, it will only be visible to an admin user. 

Even if the password could be stored encrypted in the database, it must still be decrypted and sent in the HTTP authentication headers in plaintext so Bitbucket can authenticate. All anyone would have to do is set an action hook to display the HTTP headers. Much simpler than trying to snoop the database.
