### ISSUE TITLE
Plugin says theme up to date when it isn't

### ISSUE THREAD

**Issue by magiclantern** [afragen/github-updater#219]
Hooked up to a GitHub private repository, not using tags. When I bump the version number in style.css, GitHub Updater doesn't see the changes. I have to decrement the version number on the local copy for the plugin to see that an update is available. Any clues?

**Comment by afragen** [comment]
Try clearing the transients using the 'Check Again' button. The transients exist for 12 hours.

**Comment by magiclantern** [comment]
Nope, still says "Theme is up-to-date! No previous tags to rollback to."

**Comment by afragen** [comment]
Try refreshing theme page.

**Comment by magiclantern** [comment]
Thanks for your help. That didn't work but eventually some combination of clicking "Check Again" and refreshing the theme page did work. Appreciate your help and your plugin.
