### ISSUE TITLE
Encourage GitHub Personal Access Token for public repositories

### ISSUE THREAD

**Issue by pengwynn** [afragen/github-updater#220]
Since the default unauthenticated rate limit for the GitHub API is 60 req/hr, this plugin results in a substantial number of rate-limited requests from shared hosts. This means that the updater won't work for many users on those hosts.

Could you change the "GitHub Private Settings" section to "GitHub Settings", and encourage users to always use a [Personal Access Token][pat]? For public repositories, a scopeless token is sufficient and preferred. For private repositories, the token will need `repo` scope.

[pat]: https://help.github.com/articles/creating-an-access-token-for-command-line-use/

**Comment by afragen** [comment]
I'm not sure I understand. There is a setting for 'GitHub Personal Access Token' and it displays above any settings for private GitHub repositories. The access token section also explains why it's a good idea to use one and the README explains why it's a good idea as well as giving a link to get one.

Maybe I'm misunderstanding but what problem is there here that needs solving?

**Comment by pengwynn** [comment]
> There is a setting for 'GitHub Personal Access Token' and it displays above any settings for private GitHub repositories. 

@afragen right. From what I found in the README, personal access tokens are always mentioned in the context of private repositories. The [`401` section][401] makes it sound like you'll get a `401` if you use an access token for a public repo:

> - using a GitHub Access Token for a public repo
> - an incorrect Access Token for a private GitHub repo.

It would be great to encourage using a token _all the time_ to avoid running into rate limiting. The section on [`403` errors][403] makes it seem like these errors are transient and temporal:

> usually this means that you have reached GitHub API's rate limit of 60 hits per hour. This is informative and will go away in less than an hour.

For self-hosted installs, this is usually the case. For large WordPress hosts where many end users share a single IP, users without a token may never get around the problem.

We're seeing a substantial number of `403` errors to the GitHub API from unauthenticated WordPress clients and we'd like to reduce those while helping end users avoid problems while updating. Encouraging users to _always_ use a personal access token, or even requiring it, would help a great deal.

Does that help explain the issue?

[401]: https://github.com/afragen/github-updater#github-1
[403]: https://github.com/afragen/github-updater#403---unauthorized-access

**Comment by afragen** [comment]
So what I really need to do is update the README and make it more clear that using a personal access token is the preferred method.

**Comment by franceimage** [comment]
@pengwynn I also like the idea of pulling Wordpress plugins and themes directly from GitHub. Considering the success for Wordpress, there could be a fairly high traffic (API and downloads) to GitHub if, suddenly, all Wordpress users (not only a few developers) were using GitHub as a primary source of update for their plugins and themes.

My question is: would you welcome or throttle this ? 

Thanks

**Comment by pengwynn** [comment]
> So what I really need to do is update the README and make it more clear that using a personal access token is the preferred method.

@afragen That would be awesome. :sparkles: 

@franceimage The GitHub API is better suited for collaboration workflows than providing a CDN.

**Comment by afragen** [comment]
@pengwynn I guess there are a couple of things I can do.

1. Use personal access token for remote install.
2. Revise README.
3. Through up an admin notice if personal access token not set.

Re: 3 -  I'll need to make this dismissible for a defined time period as we don't want it to be THAT annoying.

**Comment by afragen** [comment]
@pengwynn I've done the first 2 above. Can you check the README and see if you think it's now sufficient. I'm not sure a nag is the best way to go.

**Comment by pengwynn** [comment]
@afragen I think the updated README is great and will go a long way toward resolving the problem. Thank you! :sparkling_heart:

**Comment by afragen** [comment]
@pengwynn out of curiosity are you referring to seeing lots of rate limits being hit for clients or on GitHub's side?

**Comment by pengwynn** [comment]
@afragen On the GitHub side. Trying to connect the dots via User Agent and paths requested led me here. Adding a custom User Agent header to `wp_remote_get` on your end would help us confirm that and let you know how the situation improves over time.

Feel free to close this issue out, and thanks for the quick response. :+1:

**Comment by afragen** [comment]
I'll look and see how to add the custom user agent.

I'm playing with a nag notice. Is there some wording that you think would work best?

**Comment by pengwynn** [comment]
For the nag, do you have the ability to check https://api.github.com/rate_limit and only show the message if the limit is 60 (instead of 5000)?

**Comment by afragen** [comment]
OK, custom user agent added. It will add `GitHub Updater - https://github.com/afragen/github-updater` to the user agent.

**Comment by afragen** [comment]
> For the nag, do you have the ability to check https://api.github.com/rate_limit and only show the message if the limit is 60 (instead of 5000)?

I think I can set the nag to show if the rate limit message shows.

**Comment by afragen** [comment]
Any specific language to that nag?

**Comment by pengwynn** [comment]
I think you could keep it friendly:

> It looks like you're running into GitHub API rate limits. Be sure and configure a [Personal Access Token](https://help.github.com/articles/creating-an-access-token-for-command-line-use/) to avoid this issue.

Does that work?

**Comment by afragen** [comment]
Looks great.

**Comment by afragen** [comment]
So I've added the nag into the same error message that displays the time remaining in the until the rate-limit is reset.

Please let me know if the custom user agent is working to identify the issue. I'm also curious as to approximately how many API requests GitHub gets from this plugin. I do cache the response for 200 and 404 and each plugin will make 4-5 calls per plugin/theme.

I'll push this update today.

**Comment by afragen** [comment]
@pengwynn please let me know when you start seeing the custom user agent addition.
