### ISSUE TITLE
Wrong Updates

### ISSUE THREAD

**Issue by JoeHana** [afragen/github-updater#221]
Hi,

lately I had the case where I had 3 plugins of a set, custom developed for my client. All those 3 had similar names - to be straight it was:

* Fabios
* Fabios Menu
* Fabios Infoscreen

The latter 2 require the first one as some kind of "core".

Lately I was pushing an update to bitbucket of the Fabios Infoscreen Plugin. On the other side (the client's website) it didn't took long to show up as an update. But after the update has been done I've got various issues and found out that the wrong plugin has been updated. Instead of the Fabios Infoscreen plugin the Fabios Plugin has been updated. I'm not quite sure nor did I had a closer look at the code for that case but it seems like the GitHub Updater might look only for a specific pattern within a plugin name but doesn't compare them completely?

More Info:
* All plugins have their respective folders (eg. fabios, fabios-menu, fabios-infoscreen)
* All plugins contain a plugin.php file instead of a fabios.php, fabios-menu.php,...)
* The update process itself went smooth, altough I found it quite too quick which also made me suspecting there must be an issue. I was not sure if all files have been changed or only a bunch of them. The whole process was around a second.

Would love to get any more insights, cause I would love to use this solution also in the future.

Thanks in advance

**Comment by afragen** [comment]
Can you give me access to the plugins? My Bitbucket username is `afragen`. I would also need a URI.

It will help me figure out what the problem might be.

**Comment by JoeHana** [comment]
I gave you access now. Hopefully read access is enough?

**Comment by afragen** [comment]
There is an issue with 'Fabios - Infoscreens'. The repo is actually named `fabios-infoscreen` not `fabios-infoscreens`. Because of this the repo is showing as nonexistent.

But thanks for showing me a bug in my renaming code. It should now be fixed.

**Comment by afragen** [comment]
BTW, I would reinstall those plugins on your clients site as I think what happened was the Fabios - Menu plugin was updated and renamed Fabios. This possible caused the Fabios plugin to be overwritten. To be safe I would delete the plugins via FTP and reinstall via GitHub Updater's remote install feature. The reason for deleting via FTP and not via the WP interface is so that any data associated with those plugins isn't deleted.

**Comment by JoeHana** [comment]
Well, thanks a ton. I will do that for sure and will get back if there is anything else in that regards. 

Thanks again.

**Comment by afragen** [comment]
@JoeHana what I meant regarding the naming of Fabios - Infoscreens is that either the repo name must be changed to match the GitHub Plugin URI or the GitHub Plugin URI must be changed to match the repo.

**Comment by afragen** [comment]
Let me know if it's working correctly for you now.

**Comment by afragen** [comment]
Please re-open if this is still an issue.
