### ISSUE TITLE
Update by Release Assets

### ISSUE THREAD

**Issue by geminorum** [afragen/github-updater#224]
Since Github would not include git sub-modules in tarball/zipball,
and I can not commit Composer's vendor directory in my plugin git repo,

I'm strongly suggesting:
Before updating from tags, the updater checks for the tagged release assets and install them instead.

This way we can include packaged version of each release and automatic updates at the same time!

tnx for the plugin, btw.

**Comment by afragen** [comment]
What exactly is a "tagged release asset" and how would I check for it?

**Comment by geminorum** [comment]
- on Github UI they call it binary attachments, when I try to make a tag/release.
- but on GitHub API, they call it assets, see: [Get a release by tag name](https://developer.github.com/v3/repos/releases/#get-a-release-by-tag-name)
- there's a name and mime prop for each asset if each release.
- the main challenge seems to be how to select from more than one assets. something like `pluginname-tagversion.zip`

**Comment by afragen** [comment]
Can you explain how this is used?

**Comment by geminorum** [comment]
- since Github does not commit git-submodules source files in the repo, and therefore automatically generated tarballs are incomplete.  So practically We can not use this functionality. for example see my theme library directory [here](https://github.com/geminorum/gtheme_03/tree/master/libs). I'm using Bootstrap and Genericons as submodules. the generated zip will not contain this folders, since they are only a reference to another repo and when the updater pulls the zipball, the source code is incomplete.

- another case is when I'm trying to use [Composer](http://getcomposer.org). since we cannot properly using it for plugins in WordPress, I have to update composer packages manually on my local dev and then upload the generated files and source packages as a single file. Again each package maybe contain a git repo and I can not commit them as regular source code in my plugin.

in this cases the updater plugin simply wont work.

**Comment by afragen** [comment]
Unfortunately there are several issues. The biggest is that there is no real way to download a submodule within the repo as an intact part of the repo. Since a submodule is really just a reference to another repo all that gets copied is a reference (an empty file) and that doesn't work.

Unfortunately the easiest solution is to put an actual copy of the submodule into your repo. Obviously it would no longer be a submodule, but it would download correctly with the existing endpoints.

If you can figure out a way to do this I'm more than happy to review a PR. Unfortunately, it's just too much for me to undertake for such a small use case. I say that because in 2 years this is the first time anyone has asked and I haven't used submodules myself.

Sorry.

**Comment by geminorum** [comment]
- let me be clear, I'm suggesting updates from release packages and not just the source code in the repo. 
- this will help my cases, but mainly a feature for the updater.
- I'll be happy to help figuring a way to help implementing this and trying to make a pull request.

thanks again.

**Comment by afragen** [comment]
@geminorum I think I understand and it would add a nice feature to the plugin. I'm happy to work through a PR with you.

**Comment by afragen** [comment]
I think I understand now. Is there a naming convention that GitHub provides or can you name it whatever you want?

Should we always seek to use `https://github.com/<owner>/<repo>/archive/<tag>.zip` where `<tag>` is the latest numeric tag?

**Comment by geminorum** [comment]
- Seems to me there are no limits on naming the assets, see [atom releases](https://github.com/atom/atom/releases) for exampe. downloads for each platform with it's own name.

- `https://github.com/<owner>/<repo>/archive/<tag>.zip` won't work, it's just a zip mirror of the repo. but we need assets attached to each release/tag, like the example [here](https://developer.github.com/v3/repos/releases/#get-a-release-by-tag-name).

- I think we have two options for naming: `wordpress-pluginslug-vtag.zip` or `github-reposlug-vtag.zip` which in many cases are the same, like [this](https://github.com/geminorum/gpersiandate/releases/tag/0.2.34).

- so if there's an asset to the latest release/tag with name of `wordpress-pluginslug-vtag.zip` the updater must install it instead of the zip mirror of the repo.

- and this is my old testing of the updater

**Comment by afragen** [comment]
If we hit the API at `https://api.github.com/repos/geminorum/gpersiandate/releases/latest` it looks like there JSON returns something with `browser_download_url` which looks like it has the correct endpoint.
I don't think we should assume a consistent naming convention if the user is actually doing the naming.

Is it safe enough to to assume that `latest` is really the asset we need?

I think I can pull the data and verify against the version number and if matching see if `browser_download_url` exists and use it if if does.

**Comment by geminorum** [comment]
> If you tag releases the version number of the tag must be the same as in the file inside of the tag.

said on the [readme](https://github.com/afragen/github-updater/blob/develop/README.md). so why we have to check WordPress header tags on Github repo? 

> View the latest published release for the repository.

said on [API docs](https://developer.github.com/v3/repos/releases/#get-the-latest-release)

but what if the release has more than one asset?

**Comment by afragen** [comment]
>> If you tag releases the version number of the tag must be the same as in the file inside of the tag.

> said on the readme. so why we have to check WordPress header tags on Github repo?

Because some people don't always do it correctly. :wink: 


> but what if the release has more than one asset?

We can only use a single download link for updating. I've not used published assets or releases, only tags. If the project is on a release with multiple assets and therefore multiple download links I'm not certain that updating via this method is possible.

Since the dev is creating the file for the asset, we could require them to create a single file. Just to confirm this single file would have to be able to be installed just like a .zip on the Add Plugin or Add Theme page by upload.

**Comment by grappler** [comment]
@afragen The idea is good to use `browser_download_url`. I find if the plugin author wants to add support like this then they should be able to set it up correctly.

**Comment by afragen** [comment]
@grappler how should we account for an author creating multiple assets per release? Or should we assume only one will be present and use the first one we get?

I'm on call today. When I get some free time I'll code something up and publish the branch here.

**Comment by grappler** [comment]
@afragen I can't think of a situation when multiple assets are needed per release. We should just assume only one and take the first one.

**Comment by afragen** [comment]
Hey guys! If you want to test, use the branch switcher and switch to `assets` branch. Let me know what you think.

**Comment by afragen** [comment]
This seems to work in my testing and I've merged it into the develop branch.

**Comment by afragen** [comment]
@geminorum is the latest `develop` branch working for you as a solution to this issue?

**Comment by geminorum** [comment]
`develop` `v4.4.0.8`  works fine with my one asset [release](https://github.com/geminorum/gpersiandate/releases/tag/0.2.34). but the installer on settings page still using the source in repo.

sorry I'm still on a rather long trip. I will trying to do more testing in home. thanks.

**Comment by afragen** [comment]
> but the installer on settings page still using the source in repo.

I think I forgot about this one.

**Comment by afragen** [comment]
The installer isn't going to be able to get the asset as the installer doesn't check anything upstream so it doesn't know about the existence or non-existence of the asset.

**Comment by afragen** [comment]
@geminorum I've added a check to the remote install so if an asset's URI is entered it should be installed. I've made the assumption that the asset's URI contains the string `releases/download`, I hope that's consistent.

**Comment by afragen** [comment]
Included in latest release v4.5.0. Please let me know if there are any issues.

**Comment by afragen** [comment]
Please re-open if there are any issues.
