### ISSUE TITLE
Updating Bitbucket repo, installs to folder with name that includes commit hash

### ISSUE THREAD

**Issue by plaidpowered** [afragen/github-updater#225]
So my plugin is in a bitbucket repo. The plugin folder is identical to the repo name. But when GHU updates it, it deletes the old plugin folder, downloads the most recent tag (which creates a zip named [my_username]-[my_repo]-[commit].zip) and installs to a folder matching the zip file. It wouldn't be a big deal, except that now the plugin has to be reactivated. 

Example:
Repo is *bitbucket.org/myusername/myrepo*
Plugin folder is named *myrepo*
On update, *myrepo* gets deleted and replaced with *myusername-myrepo-123456abcd*

**Comment by afragen** [comment]
How did you install the plugin originally? Did you rename it? Can you share the URI?

**Comment by plaidpowered** [comment]
I added an example to my original post. I installed it by cloning the bitbucket repo, which gave me the correct foldername. The update process seems to rename my folder

**Comment by plaidpowered** [comment]
I just confirmed that the same thing happens when I turn off updating by tag (I deleted my tags). Unfortunately I can't share the URI

**Comment by plaidpowered** [comment]
Is there a hook I can use to rename the zip file after it's been downloaded? Seems like that would fix the problem.

**Comment by afragen** [comment]
Can you show a screenshot of the settings page?

**Comment by plaidpowered** [comment]
It's just the default settings - nothing filled in, as if I've just freshly installed the Github Updater plugin.
![screen shot 2015-04-23 at 2 11 26 pm](https://cloud.githubusercontent.com/assets/4389847/7304090/f0aa16de-e9c2-11e4-8928-fb3e4748d98b.png)

**Comment by afragen** [comment]
So this is not a private repo.

Unfortunately, without testing the actual repo I'm not sure what more I can do.

Can you email me the URI if you don't wish to share it publicly?

**Comment by plaidpowered** [comment]
Yep. Doing so

**Comment by afragen** [comment]
Try removing the `.git` from the Bitbucket Plugin URI and let me know if that works.

**Comment by plaidpowered** [comment]
Bizarrely, that worked! Intended behavior?

**Comment by afragen** [comment]
The header is not supposed to have the `.git` extension. It really is just the `<owner>/<repo>`.

It's very likely the renaming code breaks if the extension is present.

Glad it's working.

**Comment by plaidpowered** [comment]
You might want to mention that in the documentation if you haven't already. Pulled my hair out for an hour trying to debug this before I even posted an issue. :) Many thanks for your assistance.
