### ISSUE TITLE
GHU adds Bitbucket username and commit number to plugin folder name

### ISSUE THREAD

**Issue by gantsta** [afragen/github-updater#226]
When I install a plugin from a (private) Bitbucket repo using GHU's Install Plugin feature the resulting folder that gets added to wp-content/plugins is: bitbucketusername-bitbucketreponame-repocommitnumber

So, for my plugin called ajg-messages, the resulting folder is called:

gantsta-ajg-messages-16e3de387735

Then, once I update the plugin it renames the folder to the new commit number and, in so doing deactivates the plugin because it can't find the original version of the plugin.

Any idea why this may be. I am developing on a localhost web server (MAMP Pro).

**Comment by gantsta** [comment]
FYI, I just tried the same operation on a live web server with the same result so it doesn't look as if the local server environment is the cause of this issue.

**Comment by franceimage** [comment]
Can you share a link to your repo ?

**Comment by afragen** [comment]
Can you add `afragen` with `read` privileges to the repo?

**Comment by gantsta** [comment]
Thanks Andy. I have added your user `afragen` to the repo and granted `read` privs. The repo URL is:
https://gantsta@bitbucket.org/gantsta/ajg-messages.git
Appreciate your help.

**Comment by afragen** [comment]
@gantsta you need to change the header URI to `Bitbucket Plugin URI: https://bitbucket.org/gangsta/ajg-messages`

**Comment by franceimage** [comment]
@afragen Why is there a need for this URI ?  

I don't see what functionality I miss in my [own implementation](https://github.com/franceimage/wp-alt-repositories).

The only thing I think of is that (with your plugin) you cannot install a plugin without the consent of the developer. Is it what it's about ?

Thanks

**Comment by afragen** [comment]
@franceimage GitHub Updater is definitely opt in. Isn't it wonderful that people have a choice for this primary functionality. I won't go into the differences in our projects, but fundamentally they both allow a user to have automatic update function for plugins and themes. I have tried to put the onus for updating on the developer, not on the user. From a user's perspective all they need to do to have a plugin or theme update is to install and activate this plugin and install any other plugin that supports it. They don't have to create a connector, a plugin/theme setting, or make choices on how they want to receive updates.

If you wish to suggest your own project to users here, I won't stop you but the OP is asking a question and I'm trying to answer it.

My advice would be to write about your project. Describe it's feature, uses, etc. Ask others to evaluate your code and provide feedback, some will some won't. I wish you great success with your plugin as I think it offers another alternative via a different method.

Cheers,
Andy

**Comment by gantsta** [comment]
Thanks Andy. The change to the `Bitbucket Plugin URI` that you mentioned has resolved the issue.
Really grateful for your assistance with this and for creating such a useful plugin.

**Comment by afragen** [comment]
You're very welcome. Be sure to make the same changes upstream in the repo too.
