### ISSUE TITLE
How to move github updater to includes folder within theme?

### ISSUE THREAD

**Issue by jaycbrf4** [afragen/github-updater#230]
I love this plugin and would like to include it as part of my theme instead of a plugin. I have moved it to my theme's includes folder and have called it into my theme's functions using "require_once('includes/github-updater/github-updater.php');"

I now see that a lot of the required files inside github updater are coded to pull from the plugin directory.

How do I change these paths to go to the includes folder?

**Comment by afragen** [comment]
The design of this plugin is such that it is an add on to whatever you wish to update. This has been a design choice from the beginning to eliminate the inclusion of "irrelevant" code from your project and only add a header or so to allow for updating.

While I'm quite certain it's possible you would need to include most of the plugin and it's structure. Even then I won't guarantee that problems won't arise.
