### ISSUE TITLE
Bitbucket Issues

### ISSUE THREAD

**Issue by lupetalo** [afragen/github-updater#232]
On install i always get: Download failed. Too many redirects. error, no matter what i do. I can download manualy and install but i cant do it with updater:

Downloading install package from https://bitbucket.org/xxx/xxx/get/master.zip…

Download failed. Too many redirects.

Return to Plugins page

**Comment by lupetalo** [comment]
When i change repo to public, its working. I did checked private and fill credentials....

**Comment by afragen** [comment]
Is that from a remote install using the GHU or on an update?
Can you give read access to `afragen` and share the URI?

**Comment by lupetalo** [comment]
Initial install, and only when repo set to private. Added access.

**Comment by afragen** [comment]
You shouldn't add the `.git` to the end of the URI. Does that make a difference?

**Comment by lupetalo** [comment]
Nope. same.... :(

**Comment by afragen** [comment]
FWIW, I was able to remote install and update the repo without issues. The multiple redirect issue is usually a server thing.

**Comment by lupetalo** [comment]
Thanks. Can you tell me how plugim communicate with bitbucket so i can track down issue?

**Comment by franceimage** [comment]
I think at the stage your problem occurs, it has nothing to do with the plugin (am I right @afragen  ?)

Some people have the same problem just trying to update their plugin. Check that https://wordpress.org/support/topic/automatic-updates-of-core-and-plugins-failing-too-many-redirects

Is your server hosted or do you run it yourself ? In the first case, you could ask some support from them.

**Comment by lupetalo** [comment]
I own small hosting buisness, that server has more than 50 wp sites and none of them have issues with regular wp update, some of them are on https, some not. I am sure that this update has difference. Also public repos work and private does not...

**Comment by franceimage** [comment]
weird ... can you give read access too ? (fi_read)

**Comment by lupetalo** [comment]
Added, as i have root to server i can try many things, bit i must say that this should work on any hosting, same as WP and its update... And it is not that it happen sometimes as mentioned in readme.md, ita always :(

**Comment by afragen** [comment]
> I think at the stage your problem occurs, it has nothing to do with the github-updater plugin (am I right @afragen ?)

I think this is correct.

There shouldn't be any issue regarding http vs https.

The plugin communicates via the Bitbucket API. There is a standard endpoint for downloading, as you have outlined above. It's also possible that there are issues with Bitbucket's site.

This plugin should work regardless of hosting.

**Comment by franceimage** [comment]
@lupetalo 

This works for me without trouble too

This is how you fill up the form, right ?

![lupetalo](https://cloud.githubusercontent.com/assets/3442039/7457947/81c32bf8-f290-11e4-8ce8-34e512270359.png)

**Comment by lupetalo** [comment]
Only difference is that i put full url including protocol. (Https://).

**Comment by franceimage** [comment]
Please try as shown

**Comment by afragen** [comment]
> same problem just trying to update their plugin. Check that https://wordpress.org/support/topic/automatic-updates-of-core-and-plugins-failing-too-many-redirects

This was interesting.

You might try commenting out the following line.

https://github.com/afragen/github-updater/blob/develop/src/GitHub_Updater/API.php#L35

> Only difference is that i put full url including protocol. (Https://).

This shouldn't matter as the URI is stripped down to only it's owner/repo. Adding, the `.git` can cause issues and it's come up enough that I'll probably sanitize it out as well.

**Comment by lupetalo** [comment]
@franceimage Nope, same... 
@afragen That may be the case, at some point it it shows correct download url, no matter what i enter in Plugin URI above
![image](https://cloud.githubusercontent.com/assets/2978358/7458084/d33e480e-f291-11e4-85b5-78150905d47b.png)

**Comment by afragen** [comment]
Try commenting out the line mentioned above.

**Comment by lupetalo** [comment]
Tried, same error as in picture above...

**Comment by lupetalo** [comment]
I think that problem is in difference in private and public repo API handling, and some setting on server side.

**Comment by franceimage** [comment]
Normally, it is just adding basic authentication headers .... 

Can you try with https://github.com/franceimage/wp-alt-repositories ?

**Comment by lupetalo** [comment]
Working:
![image](https://cloud.githubusercontent.com/assets/2978358/7458474/f4e12bfe-f294-11e4-9657-265ffca09be3.png)

**Comment by lupetalo** [comment]
same thing with this plugin...
![image](https://cloud.githubusercontent.com/assets/2978358/7458589/cdb58d3a-f295-11e4-911d-211a7fac02b9.png)

**Comment by afragen** [comment]
@lupetalo I think what @franceimage meant was to try using that plugin for updating.

Can try installing `afragen/test-bitbucket-plugin` I'll also add you to my private test plugin, `afragen/test-bitbucket-private`

**Comment by lupetalo** [comment]
First:
![image](https://cloud.githubusercontent.com/assets/2978358/7458615/116084ea-f296-11e4-9e91-8f684f99297f.png)
first without Private Bitbucket Repository checked
![image](https://cloud.githubusercontent.com/assets/2978358/7458643/453ff35e-f296-11e4-8e2f-6473c0d6573b.png)
second:
![image](https://cloud.githubusercontent.com/assets/2978358/7458628/2a1d1d36-f296-11e4-8bbd-65184b5735e2.png)

**Comment by afragen** [comment]
The only difference in a public and a private repo is the addition of the appropriate Basic Authentication HTTP headers.

Do you happen to have a WP install that's on a different server? It would be nice to see if this is somehow isolated to is particular server setup.

**Comment by franceimage** [comment]
@afragen I think @lupetalo has installed my plugin using yours, and then tried to install his plugin (private repo on bitbucket) using my plugin.

It gave the same error and that's reassuring. So the problem is definitely related to downloading a resource using basic authentication on @lupetalo 's server

**Comment by franceimage** [comment]
@lupetalo you could try downloading the master.zip using curl and see what's happening

**Comment by lupetalo** [comment]
Ok, this is really stupid, i found the reason.... It looks like Chrome-s password remember is problem.
![image](https://cloud.githubusercontent.com/assets/2978358/7458866/324e3894-f298-11e4-9114-2049493285fb.png)
Looks like values from these fields are being sent somehow, and in this case instead of password is blank field (chrome bug). When i delete stored pw and enter it manually it works.
So problem is that on this pahe saveing blank password is allowed and/or when you click update plugin use that value instead of saved one.

**Comment by lupetalo** [comment]
Try saveing blank pw and you will get redirect error.

**Comment by lupetalo** [comment]
also try storing credentials in chrome and you will se  that field like filled but it is acctualy blank.

**Comment by afragen** [comment]
Does this mean that Chrome is the issue and now everything works as expected?

**Comment by lupetalo** [comment]
Yes, if you save login credentials using Chrome password manager, you get blank field where password should be. But there is still bug with updater. When you click update, it should not care for value of 'Bitbucket Password',certanly not on update tab.

**Comment by lupetalo** [comment]
Thing with Chrome happens when use same username login to bitbucket and on wp login page

**Comment by afragen** [comment]
Once you have saved the user/pass it's stored in the options table. That's where it's picked up when doing a remote install of a private repo.

Can you try using a different browser or turning off the password manager in Chrome? You might want to re-enter and save your Bitbucket credentials in a different browser.

**Comment by lupetalo** [comment]
Well the bug may happen on save, looks like at point when you click Install plugin it also executes store to options table. Yes if pass manager turned off and resave of pw it works like a charm.

**Comment by afragen** [comment]
> Well the bug may happen on save, looks like at point when you click Install plugin it also executes store to options table. Yes if pass manager turned off and resave of pw it works like a charm.

It does but that information isn't what's being stored. The only info being stored is the check for being a private repo or the access token. To even attempt a download of a Bitbucket private repo the user/pass must already be entered.

**Comment by afragen** [comment]
If this is still an issue please re-open.

**Comment by Dnncha** [comment]
I'm having this issue now on Google Compute Engine, but it has worked before in other similar set ups.

**Comment by afragen** [comment]
@Dnncha can you create a new issue, this has been closed for over a year.
