### ISSUE TITLE
undefined property PHP notice when attempting to update theme

### ISSUE THREAD

**Issue by gantsta** [afragen/github-updater#235]
Hi. I have updated GHU to version 4.4.0.6 and installed a theme from a private repo hosted in our Bitbucket account. Once I push an update to the repo and then try and check for updates in Wordpress, I get the following PHP notice and warnings:

```
Notice: Undefined property: stdClass::$data in /Users/alexgant/Sites/freightlineraustralia/public_html/wp-content/plugins/github-updater/src/GitHub_Updater/Bitbucket_API.php on line 57

Warning: Cannot modify header information - headers already sent by (output started at /Users/alexgant/Sites/freightlineraustralia/public_html/wp-content/plugins/github-updater/src/GitHub_Updater/Bitbucket_API.php:57) in /Users/alexgant/Sites/freightlineraustralia/public_html/wp-includes/option.php on line 772

Warning: Cannot modify header information - headers already sent by (output started at /Users/alexgant/Sites/freightlineraustralia/public_html/wp-content/plugins/github-updater/src/GitHub_Updater/Bitbucket_API.php:57) in /Users/alexgant/Sites/freightlineraustralia/public_html/wp-includes/option.php on line 773
```

Also, the update to the theme is not picked up so I can't update it.

**Comment by afragen** [comment]
If you clear the transients by using the Check Again button from the core update page, does the error persist?

**Comment by gantsta** [comment]
I have reinstalled the theme which cleared the Notice and Warnings but it still won't update. I have granted your user access to the repo if you want to take a look.
Thanks.

**Comment by afragen** [comment]
I will check it out. But moving my son out of college dorms today so it might be a bit later.

**Comment by afragen** [comment]
I was able to install, turn down version number and update all without issue or PHP notices.

**Comment by franceimage** [comment]
@gantsta

What level of the plugin do you use ?
In other words, what is the content of line 57 (github-updater/src/GitHub_Updater/Bitbucket_API.php) ?

**Comment by gantsta** [comment]
Thanks @afragen. I have just updated the theme to 1.0.0.4
@franceimage, line 57 of the file you mention is `$contents = $response->data;`
Thanks.

**Comment by afragen** [comment]
@gantsta I just checked and see the update for 1.0.0.4 and update occurs correctly.

**Comment by afragen** [comment]
The PHP notice was likely due to something stale in the transient. I have no way to test in specific user circumstances and if clearing the transients solves the issue then I'm not sure there's anything I can do.
