### ISSUE TITLE
Option to set folder name

### ISSUE THREAD

**Issue by reinink** [afragen/github-updater#239]
Hello! I'm very new to GitHub Updater, and it's perfect for my particular use-case. Thanks for your work on this.

I've got a question about folder names. Right now it appears that the plugin/theme folder names are resolved from the repo name. This makes sense, but in some situations you may want a more complicated folder names in order to avoid plugin conflicts. However, that means you'd also need a more complicated repo name, which isn't necessarily ideal.

Would it makes sense, and if yes, would it be possible to add an additional option to specify the folder? Something like this:

```php
/*
Plugin Name:       GitHub Updater
Plugin URI:        https://github.com/afragen/github-updater
Plugin Folder:     afragen-github-updater
/*
```

Does this make sense, or am I missing something here that makes this not necessary? Thanks!

**Comment by afragen** [comment]
You're understanding is correct, however, is this really a problem? If 2 plugin/theme names are identical, it might be that an overwrite of an existing plugin/theme occurs. Obviously that would be bad.

While it probably wouldn't be difficult to add, it would result is more settings that certainly could result in more confusion as these setting would also be exposed in the install panels as well.

If there's enough interest in this feature I'm happy to work on it. So everyone let me know your thoughts. @reinink votes yes.

**Comment by reinink** [comment]
Well, the reason I think it's worth considering is because right now these sort of name conflicts are managed by the WordPress theme and plugin repositories. However, because this tool works independent of that, there's a greater chance of collision.

**Comment by afragen** [comment]
There's actually a way to do this without an extra header. I could just make the renaming code rename the directory to `github-<owner>-<repo>`, where `github` would change for Bitbucket or GitLab hosted plugins or themes. This would absolutely eliminate the possibly of a conflict, though it it might cause any update from the previous code to require a re-activation of the plugin or theme.

Thoughts?

**Comment by reinink** [comment]
That sounds brilliant! Great idea, not sure why I didn't think of that.

**Comment by afragen** [comment]
When I get it done I'll post the branch here and you can see how it functions for you.

**Comment by reinink** [comment]
Great, thanks so much!

**Comment by afragen** [comment]
Using this long rename style doesn't work for themes. I was making progress until a change managed to erase everything. Waiting to restore from backups, go Backblaze.

**Comment by reinink** [comment]
Really? :(

**Comment by afragen** [comment]
That's what can happen when messing around with renaming code and returning `false` in the wrong place. Not to worry, Backblaze is amazing and I was back up in 30 min. :+1:

**Comment by reinink** [comment]
Okay man. Well, if this feature is creating pain for you...don't stress it. Hopefully it doesn't become an issue ever. :)

Worst case a plugin/theme is overwritten. Not terrible.

**Comment by afragen** [comment]
I've gotten it mostly written with an exemption for themes. I just need to test a bit more. I may just push it out as a branch and not roll into main plugin though, still deciding.

**Comment by afragen** [comment]
Nothing should get overwritten. If you try to install a plugin or theme in a directory that currently exists you will get a failure to install notice.

**Comment by reinink** [comment]
Oh, perfect. That's even better.

**Comment by afragen** [comment]
I just finished a simplification of the renaming code. I'll see if I can adjust it to rename plugins, but there are many little problems that may arise and it certainly doesn't work for themes.

**Comment by reinink** [comment]
:+1:

**Comment by afragen** [comment]
@reinink if you'd like to test something, use the branch switcher and switch to branch `long-rename2`.

I haven't fixed the long rename for remote installation and this is only for plugins as something screwy happens with themes.

Only caveat is if you rename an active plugin it will need to be reactivated.

Let me know what you think. I was thinking of just adding another preference to toggle.

**Comment by afragen** [comment]
@reinink I believe I've gotten most all the issues with extended renaming worked out. Give the `long-rename2` branch a spin. The extended renaming checkbox lives in the settings page. See if you can find bugs or break it.

**Comment by reinink** [comment]
Will do!

**Comment by afragen** [comment]
@reinink Latest update to this branch should be completely functional. If it works for you let me know and I'll merge into `develop`.

**Comment by afragen** [comment]
@reinink I've decided to make this a bit more obscure. There is now a constant. All info is in the Settings page. In the `long-rename2` branch the constant is defined at the end of the main plugin file. You can test by changing the setting as appropriate.

**Comment by reinink** [comment]
Okay sweet, sorry I've been out of the project that uses GitHub Updater for the last little bit, but I'll be getting back into it soon! :+1:

**Comment by afragen** [comment]
I've done a bunch of testing and rewrote the renaming code again to provide for more precise matching of what's being updated. Both `long-rename2` and `develop` branches have these changes. `long-rename2` also has the define in the main plugin file.
