### ISSUE TITLE
"Page not Found" upon submitting "install plugin"

### ISSUE THREAD

**Issue by nadworks** [afragen/github-updater#240]
I am consistently getting "Page Not Found" upon submitting "install plugin" - no error, just a refresh to Page Not Found within my theme.

Happens consistently on latest WP version as of today and a fresh install of 4.5.1 of Github Updater.

**Comment by afragen** [comment]
What's the URL in the browser when this occurs?  You can omit the server part.

**Comment by afragen** [comment]
Is this repeatable. I've never seen it.

**Comment by afragen** [comment]
Does this problem still exist?
