### ISSUE TITLE
Force update/reinstall

### ISSUE THREAD

**Issue by cramdesign** [afragen/github-updater#244]
I would love for there to be an option to force update/force reinstall.

**Comment by afragen** [comment]
How do you mean? A force reinstall of a plugin or a force check of the APIs again? Or is it something different?

**Comment by cramdesign** [comment]
A force reinstall of a plugin or theme much like you can choose to "Re-Install Now" for the current version of wp on the updates page.

**Comment by afragen** [comment]
If you go to settings and check branch switcher then go to plugins page and switch to the same branch, a reinstall of the plugin should occur.

**Comment by cramdesign** [comment]
Ok. Great. That does work. Thank you. I would prefer a more direct method however. 

Thank you for your reply and help not to mention this extremely useful plugin. Cheers!
