### ISSUE TITLE
Filter to disable updates and change update message

### ISSUE THREAD

**Issue by darknailblue** [afragen/github-updater#247]
Hi!

I'm looking for a way to disable the checking and offering of updates.  Is there a filter I could use that would do this aside from altering the code in the github-updater.php file?  What aiming to accomplish is to use this plugin to update a theme from a PRIVATE github repo using license keys.

Any help in advance would be appreciated!

**Comment by afragen** [comment]
Not sure how to accomplish that. EDD is a wonderful platform that has modules for updating and licensing.

The only real alternative would be to closely monitor who you give `read` access to a particular private repository then just use the plugin as is.

While I assume it is possible, this project wasn't designed to be parsed and included in another repo as a method of updating.
