### ISSUE TITLE
GitLab Issue

### ISSUE THREAD

**Issue by JosefJezek** [afragen/github-updater#249]
I have issue with GitLab.com private repo.

`Hello Dolly was not checked. GitHub Updater Error Code: 400`
`You must set a GitLab.com, GitLab CE, or GitLab Enterprise Private Token.`

I set plugin header to
`GitLab Plugin URI: https://gitlab.com/test/hello`

I have saved `GitLab.com Private Token`

```
[Thu Jun 18 15:03:45 2015] [hphp] [5698:7f94d83ff700:1412:000001] [] \nNotice: Undefined property: stdClass::$last_activity_at in /htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/GitLab_API.php on line 319
[Thu Jun 18 15:03:45 2015] [hphp] [5698:7f94d83ff700:1412:000002] [] \nNotice: Undefined property: stdClass::$public in /htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/GitLab_API.php on line 321
```

GitHub repo is ok on my wp instance.

**Comment by afragen** [comment]
Can you please check an ensure your GitLab Private Token has been entered correctly?

The PHP notices are because the API didn't return a response, likely due to an incorrect token.

I'll look deeper on my end as well.

**Comment by JosefJezek** [comment]
I can remote install this plugin with same private token.

**Comment by afragen** [comment]
If you clear the transients by using the Check Again button, do the errors persist?

**Comment by JosefJezek** [comment]
Yes

**Comment by afragen** [comment]
I should have some time tomorrow to dig deeper into this.

**Comment by JosefJezek** [comment]
Thank you

**Comment by afragen** [comment]
@JosefJezek I think I just fixed this GitLab issue in all latest branches. Please confirm. Thanks.

**Comment by JosefJezek** [comment]
Thank you :+1: :star:
