### ISSUE TITLE
Switching branches - branch name

### ISSUE THREAD

**Issue by chris-agims** [afragen/github-updater#250]
First of all, LOVE this plugin!  Really appreciate the work you've put into it as it saves me a lot of work.

The one issue I'm having is that when I am looking at switching branches, no matter which branch I'm actually using, it always says the current branch is 'master'.

I've attached a screen shot.  The branch it's actually on is 'master-bootstrap-24-col', but it shows up as 'master'.

![screen shot 2015-06-19 at 10 51 22 am](https://cloud.githubusercontent.com/assets/9965623/8258319/2fc8937e-1671-11e5-8a92-0b54bd1dc56f.png)

**Comment by afragen** [comment]
The branch designation is taken from the `GitHub Branch:` header. My guess is that the header in your branch repository still says `master` when it should say `master-bootstrap-24-col`.

**Comment by chris-agims** [comment]
So to be clear, each branch needs to have a different text in the "GitHub Branch:" line?

**Comment by afragen** [comment]
If you wish to update against that branch, then yes. The branch switching takes the branch name from this header so that's why when you switched to your other branch, it still displayed as master.
