### ISSUE TITLE
BitBucket Creates New Directory when updating

### ISSUE THREAD

**Issue by darknailblue** [afragen/github-updater#251]
Hey man,

Sorry to keep buggering you especially when you have lives to save!  Either way, I'm getting a strange issue when using this plugin with BitBucket.  The repository setup is private.  The plugin will correctly identify that there is an update available but will come through like this.

![image](https://cloud.githubusercontent.com/assets/1395517/8308597/b854a74e-1993-11e5-9f41-165c874ba482.png)

Furthermore the plugin will also INSTALL the update but will create it in some OTHER directory like...

newleafwebsolutions-anfoundation-0ded27464476

Any idea what could be causing this?  Thanks in advance!

**Comment by afragen** [comment]
No problem. Can you grant `read` privileges to user `afragen` so that I can test locally?

**Comment by afragen** [comment]
I've tested updating using your Freightliner theme using my `long-rename2` branch and it seems to work correctly both locally and on my test server.

**Comment by afragen** [comment]
Testing now.

**Comment by darknailblue** [comment]
Of course.  Thanks so much!

**Comment by afragen** [comment]
I believe the problem is your in your header.

`Bitbucket Theme URI: https://newxxxxxxxxxxxns@bitbucket.org/newxxxxxxxxxxtions/anfoundation.git`

First, don't include your username in the header. Second, don't include the `.git` in the header.

My guess is that changing these will fix everything. Please let me know.

**Comment by afragen** [comment]
FWIW, GHU isn't really designed to be included in a project. You really should ask your users to simply install the plugin separately to take advantage of theme updates. It will also make installing the theme simpler. :smile:

**Comment by darknailblue** [comment]
Your suggestion worked perfectly.

And yes I see that.  The theme I'm working on is for our internal clients ONLY.  At the moment it is not intended to be consumed by the general public.  That being the case, asking any of our clients to do ANYTHING more than make simple text or image changes proves to be almost impossible.

**Comment by afragen** [comment]
Excellent.

I understand re: clients. Whatever works best for you.
