### ISSUE TITLE
You have 1.0.3 installed, please update to 1.0.3

### ISSUE THREAD

**Issue by devonhg** [afragen/github-updater#252]
I'm struggling with this issue where it updates the theme, and I can clearly see that the theme files are up to date, but the dashboard persists on updating it. I'm only updating the version in the header in the style.css file for the theme.

This is my header. 
```
Theme Name: Paradise Body Works Theme
...
GitHub Theme URI: https://github.com/devonhg/pbw-theme
GitHub Branch: master
```

Otherwise, everything is updating perfectly with exception it updates endlessly.

**Comment by afragen** [comment]
I was able to install and update successfully on my test server. Are you still having issues? I see that there have been a couple of version bumps recently.

**Comment by devonhg** [comment]
Still doing it, it's not stopping my site because it still updates properly, but the problem is that it insists on updating even though it's up to date. 

I could be missing something so let me elaborate my process. 

1. Slap headers into style.css ( as shown above )
2. Commit and push changes with "version" in style.css updated to new version ( example: 1.0.4 )
3. Force check update on site, update to 1.0.4. ( This is NOT a local server, but a live site )
4. Still requests update to 1.0.4, but it is 1.0.4. Showing a similar message ( You have 1.0.4 installed, please update to 1.0.4 ). 

Hopefully this helps further figure out the issue.

**Comment by afragen** [comment]
Currently the theme's version is 1.0.5. I tested on a live server, installed the theme via remote install from GHU then decreased the version number to see update. Updated fine and no other updates show.

**Comment by afragen** [comment]
I now see that version at 1.0.6

I did a Check Again to clear transients, an update shows and updated.

**Comment by devonhg** [comment]
Still having the issue.

However, like you said you installed it using the GHU, I forgot that things can be installed in this way and I downloaded a zip of the repo and uploaded it manually. Can this affect it?

**Comment by afragen** [comment]
It possible that you've ended up with 2 distinct installations of the theme. That could certainly cause an issue.

**Comment by afragen** [comment]
Theme directory names are very sensitive. They must be named exactly as the theme slug or they will not display correctly in all areas and they may not update correctly.

**Comment by devonhg** [comment]
Wonderful bits of information. So rules of thumb for the future...

1. Make sure directory matches theme slug perfectly
2. Install the plugin through GHU, not download zip and install, otherwise make sure zip matches slug ( The zips name is theme-name-master )

Makes sense, I think we can get it from here.

**Comment by afragen** [comment]
I think you have a good understanding. Let me know if there are any other issues.
