### ISSUE TITLE
Update theme on private repo gitlab.com issue

### ISSUE THREAD

**Issue by JosefJezek** [afragen/github-updater#254]
New update of theme is not show on update page. :-(

**Comment by afragen** [comment]
![screenshot_02](https://cloud.githubusercontent.com/assets/1296790/8367599/c45a194e-1b54-11e5-9a38-9cb804ac6320.png)

I realize it's plugins v. themes but it shouldn't matter. How did you test for the update?

1. Decrement the local theme version?
2. Increment the gitlab theme version?

**Comment by JosefJezek** [comment]
Increment from 1.0.0 to 1.0.1 is ok, but 1.0.0 to 1.0.0.1 is not ok.

Plugins are ok. Themes are not ok.

**Comment by afragen** [comment]
I will test this too.

**Comment by afragen** [comment]
![screenshot_01](https://cloud.githubusercontent.com/assets/1296790/8393718/fe812e46-1cd0-11e5-9e33-13717aee2bb7.png)

This seems to work as expected here. Just need to use the Check Again to clear transients or wait 12 hours :wink: 

This is a private Gitlab theme.

**Comment by afragen** [comment]
Another question: what is the directory name for the theme in `wp_content/themes/`? Is it identical to the GitLab repo?

**Comment by JosefJezek** [comment]
I resolve it. When I have test-theme and test-theme.git so updater don't update. ;-)

**Comment by afragen** [comment]
I'm starting to see that a lot. I'll have to trim that from the repo name and possibly through up an error message.
