### ISSUE TITLE
SVN support

### ISSUE THREAD

**Issue by szepeviktor** [afragen/github-updater#255]
Do have an advise on how to update a WP.org plugin to its `trunk` version?
Ofcourse without downloading it in a ZIP or using `svn`.

**Comment by szepeviktor** [comment]
B) Using a git repo *without* the GHU header in the plugin.

**Comment by afragen** [comment]
If your plugin is also on .org repo and the GitHub Branch === 'master', it will update from .org even with the GHU header in the plugin.

But the master branch should theoretically also be the same as what is in .org

**Comment by szepeviktor** [comment]
But I have no header. This is not my plugin.
It seem I have to write an **SVN Plugin Updater**.

**Comment by afragen** [comment]
Try the WP Rollback plugin. It in the repo.

**Comment by szepeviktor** [comment]
Thank you!
It lists only released versions:
![screenshot-2](https://cloud.githubusercontent.com/assets/952007/8366858/0c540dd8-1b99-11e5-8301-d6d8e74dca91.png)

**Comment by joshuadavidnelson** [comment]
https://github.com/WordImpress/WP-Rollback/wiki

**Comment by szepeviktor** [comment]
@joshuadavidnelson What would you like to point out?

**Comment by szepeviktor** [comment]
@afragen How about extending GHU with SVN support?

**Comment by joshuadavidnelson** [comment]
Apologies on the brevity, my intent was to point out that WP Rollback questions are probably best suited for those developers. I'm pretty sure WP Rollback only pulls from versions that have been tagged, as shown here: https://plugins.trac.wordpress.org/browser/google-maps-builder/tags. 

This sounds like an odd use case - are you not able to use FTP?

**Comment by szepeviktor** [comment]
Yes, I am.
I just prefer to have a 1-click solution.
BTW I work on console all day long.

**Comment by szepeviktor** [comment]
Like: https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/mu-plugin-upload-from-url/plugin-upload-from-url.php

**Comment by afragen** [comment]
I'm really quite certain that  GHU is unlikely to ever support svn.

All .org plugins are tagged and I think the latest tag is also in trunk.

**Comment by szepeviktor** [comment]
I am sorry to report: tags are *beside* trunk, not in it.

**Comment by szepeviktor** [comment]
> I'm really quite certain that GHU is unlikely to ever support svn.

That is pretty staight-forward.

**Comment by szepeviktor** [comment]
HEre it is
https://github.com/szepeviktor/svn-updater/blob/master/svn-updater.php

**Comment by szepeviktor** [comment]
*I'm really quite certain that GHU is unlikely to ever support svn.* was my inspiration.

**Comment by afragen** [comment]
I'm very glad for the results of your inspiration. While I understand the need for other plugins, I believe this is best served as a separate plugin. Congrats.
