### ISSUE TITLE
WP Repo and Git Repo together

### ISSUE THREAD

**Issue by JosefJezek** [afragen/github-updater#256]
How solve two repos of plugin? Checking both repos?

Could you add list of all plugins and themes with any git repo?

```
Plugin Name: Dynamic Featured Image
 Plugin URI: http://wordpress.org/plugins/dynamic-featured-image/
 Description: Dynamically adds multiple featured image or post thumbnail functionality to your posts, pages and custom post types.
 Version: 3.5.0
 GitHub Plugin URI: https://github.com/ankitpokhrel/Dynamic-Featured-Image
```

**Comment by afragen** [comment]
From the README

Hosting Plugin in WP.org Repository

If you develop your plugin on GitHub and it also resides in the WP.org repo, the plugin will preferentially pull updates from WP.org if GitHub Branch: master. If GitHub Branch is anything other than master then the update will pull from GitHub. Make sure that the version of your plugin uploaded to WP.org has GitHub Branch: master.

The same applies for Bitbucket or GitLab hosted plugins.

**Comment by afragen** [comment]
If I'm not correctly understanding the question please clarify for me. Thanks.

**Comment by JosefJezek** [comment]
Thank you
