### ISSUE TITLE
Doesn't rename folder after install of plugin

### ISSUE THREAD

**Issue by PthPndr** [afragen/github-updater#257]
I just started using your plugin (which appears to work perfectly) on a few servers. But on one of my servers it is doing the download, unpacking, and installing but not renaming. Any idea what could be causing this?

![github updater - bad](https://cloud.githubusercontent.com/assets/11739012/8406789/0879db06-1e2e-11e5-87c4-7dde54aebc56.png)

Any help would be greatly appreciated. Thank you.

**Comment by afragen** [comment]
What branch and what version of the plugin are you using

**Comment by PthPndr** [comment]
Master branch, version 4.5.7

**Comment by afragen** [comment]
Is there anything different about this server it's not working on? Is it localhost?

Can you post the plugin's headers?

**Comment by adenicboy** [comment]
I am having the same issue. It installs the update side by side and naming it name_of_user + name_of_repo + commit_id. (i.e. 'adenicboy-adenicboy-alpha-a618033')

**Comment by adenicboy** [comment]
Should be named adenicboy-alpha-master

**Comment by afragen** [comment]
@adenicboy actually it should be named `adenicboy-alpha`. BTW, you really should remove the GHU plugin from the contents of your theme. It's not meant to be run that way and you possible won't see any updates to this code.

**Comment by PthPndr** [comment]
I found the culprit. In my case it appears to be a conflict with Gravity Perks (http://gravitywiz.com/) an add-on for Gravity Forms.

**Comment by adenicboy** [comment]
For me it just doesn't work correctly in MAMP. Works fine when hosted.

**Comment by afragen** [comment]
Can you both test the `develop` branch and see if the renaming issue persists. I've made a bunch of changes to make renaming match more precisely. Use the branch switcher to change to the `develop` branch.

Let me know how it goes.

**Comment by PthPndr** [comment]
No luck for me, it still doesn't rename.

**Comment by afragen** [comment]
@PthPndr I'm not sure what I can do about that plugin conflict. You should notify the developers of that plugin. Hopefully they will contact me and we can find a solution.


@adenicboy what version of PHP is running on your MAMP? I use XAAMP/DesktopServer, locally, but MAMP shouldn't be the issue. Did you try the updated branch?

**Comment by aariacarterweir** [comment]
Same issue - not working on live env, PHP 5.3. Have tested develop branch. :(

**Comment by afragen** [comment]
@aariacarterweir does it work for you locally? Can you put a screenshot of the Settings page up?

**Comment by aariacarterweir** [comment]
Nope doesn't work locally - but I am using MAMP. Which settings page ? :D

**Comment by aariacarterweir** [comment]
Unable to test locally right now :/ keeps timing out - I will return!

**Comment by afragen** [comment]
The GitHub Updater Settings page

**Comment by adenicboy** [comment]
Sorry for the late responce. I just updated the app on my site and it seems to be working better. I haven't tried it in MAMP because I changed my set up to not use the plugin and I'd rather not change it back. But the live site seems to be renaming the file fine now.

**Comment by afragen** [comment]
Thanks @adenicboy

**Comment by PthPndr** [comment]
Just wanted to let you know I contacted the other developer and he fixed the problem with his plugin. Thank you for your help with this.

**Comment by afragen** [comment]
Thanks for the followup @PthPndr
