### ISSUE TITLE
GitLab Private Token Security

### ISSUE THREAD

**Issue by eyedarts** [afragen/github-updater#260]
Thanks for the great software!

I'm using GitHub Updater on multiple client sites with GitLab private repositories. In order to do this, I need to put my GitLab Private Token in the GitHub Updater settings for all of those sites. In essence, my clients now have my GitLab Private Token. If those sites were hacked, they'd have the token too.

Is there any other way for the GitHub Updater plugin to interact with GitLab that doesn't require putting my private token in plain text on every website I work on?

GitLab has an "Applications" feature. Would this work and be a better alternative?

Am I missing something in terms of using GitHub Updater with GitLab on multiple sites (not WP Multisite, totally separate WP installs on different servers)?

**Comment by afragen** [comment]
Unless you can give `read` access to individual users per repo, like you can with Bitbucket, I don't know what to tell you.

I'm open to ideas.

**Comment by afragen** [comment]
You might have your clients create users on your GitLab instance and then add them as team members to your project with the Reporter level access.

Not sure if this will work but certainly worth a try.

**Comment by eyedarts** [comment]
Thanks for the suggestions. I added a reporter level access user and using that private token will be secure enough. I appreciate the help with this and again, thank you for putting this plugin together!

**Comment by afragen** [comment]
@eyedarts I'm glad your got this worked out in a more secure manner. I hope it works out great for you clients.

You are very welcome, I glad you like the plugin.
