### ISSUE TITLE
Plugin folders not renaming

### ISSUE THREAD

**Issue by mlteal** [afragen/github-updater#261]
The plugin folder names are no longer renaming, and the info that's output when the update is done no longer mentions that the folder successfully renamed (though it indicated that the update was completed successfully). I've only tested with private repos. 

I'm unfortunately not sure which version that this stopped working in, but it's definitely happening on GitHub Updater v4.5.7 - tested on both WPEngine and Pagely.

Ref: https://github.com/afragen/github-updater/blob/master/src/GitHub_Updater/Base.php#L465 

<img width="815" alt="screen shot 2015-07-07 at 1 19 54 pm" src="https://cloud.githubusercontent.com/assets/3302175/8556510/47b0ac4e-24ac-11e5-8728-9acb1e565ca6.png">

**Comment by afragen** [comment]
Maura, can you switch to the `develop` branch and let me know if the problem persists? You might have to clear the transients and do a branch switch to the same/current branch of your plugin to get it to rename correctly.

**Comment by mlteal** [comment]
Ok, switched to the develop branch of GitHub Updater and the renaming's working there :) Thanks!

**Comment by afragen** [comment]
Thanks Maura. Renaming code change in that branch. :wink:

Hopefully the last time I'll be doing this.
