### ISSUE TITLE
BitBucket update failing

### ISSUE THREAD

**Issue by ethanclevenger91** [afragen/github-updater#263]
Hey, great plugin, but I'm currently having an issue.

Correct me if I'm wrong, but the plugin folder, core `.php` file and repo name should all be the same, right? So I've got that much going with some plugins hosted on a private BitBucket repository. However, when I update, the original plugin folder is deleted and replaced with `<team>-<repo-name>-<shasum>` and then the WordPress ajax updater spins forever. I put team because our repository actually belongs to a BitBucket team rather than a single user, which could be causing the issue I suppose. I did check to make sure that the new extended naming feature is disabled.

Let me know if you have any thoughts.

**Comment by afragen** [comment]
Can you tell me what branch and version of the plugin you are using?

**Comment by ethanclevenger91** [comment]
Master branch, version 4.6.

**Comment by afragen** [comment]
Sorry I was updating my comment above.

**Comment by afragen** [comment]
How did you do the plugin update? From the core update page, plugins page, or in one of the details popups?

**Comment by ethanclevenger91** [comment]
Plugins page using the AJAX updater. Let me go ahead and do one more controlled test following your suggestion above to make sure I can replicate this and if the problem persists I'll give you access.

**Comment by afragen** [comment]
Sounds fine. I test locally and on live server with public and private repos of GitHub, Bitbucket, and GitLab; but I can't get all the combinations of user's naming conventions.

**Comment by PthPndr** [comment]
I just had the same issue on Master branch version 4.6 (which I just installed). I also did an update from the plugins page (AJAX Updater) from a private BitBucket repository and it deleted the original plugin folder and named the new directory <team>-<repo-name>-<shasum>.

**Comment by afragen** [comment]
I can now reproduce this and will look into it today. I will update here. Thanks

**Comment by afragen** [comment]
Please use the updating from the core update page in the meanwhile.

**Comment by afragen** [comment]
I have a fix I'm testing.

**Comment by afragen** [comment]
Can you both switch to the `develop` branch and test the fix? It seems to be working for me.

**Comment by PthPndr** [comment]
It appears to be working for me.

**Comment by afragen** [comment]
Excellent, I'll push to master

**Comment by ethanclevenger91** [comment]
I'm still having the issue with 4.6.1 (sorry for just now getting to this) when updating via Infinite WP, so could be related to #262 ?

**Comment by afragen** [comment]
Ive never had users give me consistent results with any of the remote update services. I use iThemes Sync and I know it works. If I can easily get a test account in InfiniteWP I'll see if I can fix it. Right now ManageWP doesn't work.

@ethanclevenger91 does updating from the WP dashboard work?

**Comment by ethanclevenger91** [comment]
Yep, looks great. Thanks for looking into this. Let me know if there's anything I can do to help.

**Comment by afragen** [comment]
Will do. I'll see if I can set up InfiniteWP when I get a chance.

**Comment by afragen** [comment]
@ethanclevenger91 latest `develop` branch has a Settings > GitHub Updater > Remote Management tab. You must use the beta version of InfiniteWP Admin Panel and plugin for his to work.

Can you let me know if it's working for you?

**Comment by ethanclevenger91** [comment]
I didn't get a chance to try the `develop` branch, but I saw it got merged into master. Updated, set the Remote Management and was able to update from IWP. I'll follow up if I run into more issues, but seems to be fixed.

**Comment by afragen** [comment]
Thanks for confirming.
