### ISSUE TITLE
403 Forbidden Error (options-general.php permissions)

### ISSUE THREAD

**Issue by bradonomics** [afragen/github-updater#264]
I'm trying to add a private BitBucket repo, but I'm getting a 403 error. I've added my username and password on the settings tab, then the repo name on the Install Theme tab ([see here](http://www.awesomescreenshot.com/image/412149/e30d2391be4bacacd9fa0b4d2cb9ba0f)). Once I click on Install Theme button I get the following:

```
Forbidden

You don't have permission to access /wp-admin/options-general.php on this server.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.
```

I tried bumping the permissions on options-general.php to 777, but that did nothing. I tried adding `define('FS_METHOD', 'direct');` in my `wp-config.php` file which was suggested in another support issue, but that did nothing. I tried adding the below to my .htaccess file per [a thread on WordPress.org's Forums](https://wordpress.org/support/topic/you-dont-have-permission-to-access-blogwp-adminoptionsphp), but that did nothing.

```
<IfModule mod_security.c>
SecFilterEngine Off
SecFilterScanPOST Off
</IfModule>
```

Any ideas?

**Comment by afragen** [comment]
Strange, that clearly is a WordPress or server permissions issue and doesn't really have anything to do with the plugin.

You might try reinstalling that particular file or re-installing all of the WordPress core files. I wish I had a better answer.

**Comment by bradonomics** [comment]
No errors occur when saving other settings. I tried switching to a different theme, but got more of the same.

Here's what I've tried so far:
* I switched the Bitbucket repo to public---error persists.
* Added the repository to GitHub to see if it was a problem with Bitbucket---error persists.

Since I couldn't think of anything else under my control, I contact my hosting support. The tech I chatted with couldn't identify the problem and submitted a support ticket. Once a solution is found I'll post it here.

**Comment by afragen** [comment]
TIA, this seems very odd.

**Comment by bradonomics** [comment]
Yeah, in my local dev environment it's working fine. Didn't think to check that first. So, definitely a server problem.

**Comment by afragen** [comment]
Yeah, sorry about that but from my perspective it's nice to know this particular issue isn't my fault :stuck_out_tongue_winking_eye:

**Comment by bradonomics** [comment]
I'm still testing and I've got a few notes ...and need some guidance.

I setup a development environment on different servers. This time MediaTemple. I setup a private GitLab repo, made some changes and pushed. My local environment took the updates fine, but the MediaTemple servers did not. I contacted their support and was told that since WordPress installed and was working it shows that the server is setup correctly.

MediaTemple is acting slightly different than the previous servers I was trying (midPhase) in that the theme downloaded and installed fine; no 403 error. But then it won't take the updates. I've turned on debugging in WordPress, but so far there are no errors. Any idea what I can tell these support guys?

**Comment by afragen** [comment]
So MediaTemple is, at least, not throwing any 403 errors as originally described?

Have you tried using the **Check Again** button from the `core-update.php` page?

Can you give `afragen` `read` privileges for your private test repo? I can test it on DreamHost, which I use, but clearly that may have different implications than using MediaTemple. It may likely work when I test it but I'm not sure how that would relate to your issue, other than saying "something strange is happening at the server."

I'm hopeful that as there is now no longer the original error that it's simply a matter of the transients needing to be refreshed.

**Comment by bradonomics** [comment]
I heard back from midPhase support and they have updated my mod security rules so the 403 is now gone and I can install themes.

Now both midPhase and MediaTemple will install themes, but are not updating. The themes are installed, the plugin recognizes them, but new updates to the repo never get pushed to WordPress.

I tried the check again button this morning but it didn't change anything.

I've given you access to the [BitBucket repo](https://bitbucket.org/bradonomics/world-traveler-theme) as requested.

**Comment by afragen** [comment]
I'll test in the morning and let you know.

**Comment by bradonomics** [comment]
I finally got an error related to this plugin in my debug.log file.

```
[21-Jul-2015 01:53:19 UTC] PHP Warning:  Invalid argument supplied for foreach() in /path/html/wp-content/plugins/github-updater-4.6.1/src/GitHub_Updater/GitLab_API.php on line 212
```

Not sure that this is helpful, but it's the only message the server has given so far.

**Comment by afragen** [comment]
That shouldn't cause a fatal error, besides its fixed in the develop branch.

You must have some GitLab hosted repos if you are saw this.

**Comment by afragen** [comment]
Hey Brad, I was able to correctly install your theme using the remote install feature of the plugin both locally and on my test site.

I then decreased the version number in the `style.css` file and an update was identified. The update proceeded normally.

I usually test for updates by just decrementing the local/remote version number. This avoids the need to constantly push version number updates.

I did see that you've made a number of up and down version number changes in the repo. I had a single issue where I needed to clear the transients at least twice on my test site as I installed the theme last night but didn't have Genesis on the site. I now have Genesis on the site. It gave me an update message for v0.1.1 but you've since downgraded the version number. Clearing the transients a couple of times seems to have resolved this and now updates show and update correctly.

If you want to bump the version number back to 0.1.1 or something I'll let you know when I see an update.

**Comment by bradonomics** [comment]
The midPhase server pulling data from the Bitbucket repo did finally get a notification that v0.1.1 was available. I did the upgrade via the dashboard and everything worked fine.

But I'm a little confused about having to use the WordPress dashboard to do the update. When I'm working in my local environment the updates happen with no input from me; no notification in the dashboard, no button clicking, the files just change. Why is this different on a live server?

**Comment by afragen** [comment]
Do you have something set to do automatic plugin/theme updates on your local environment?

There's nothing in this plugin that would result in an automatic update. I use WP core update functions.

**Comment by bradonomics** [comment]
Nope ... I'm just an idiot. "Testing" it this morning I realized, it's not getting the update from the server, the updates are happening because the files are on my computer.

Thanks for your help with all this Andy. I really appreciate it.

For those jumping to the bottom for a solution to the original issue:

**Solution:**
If you're on shared hosting and getting 403 Forbidden errors, contact your support techs and have them update your mod security rules.

**Comment by afragen** [comment]
Excellent Brad. Glad everything's working as it should be.
