### ISSUE TITLE
Can this be included with a theme, so the end user does not need to edit any settings?

### ISSUE THREAD

**Issue by oncecoupled** [afragen/github-updater#266]
I'd like to use this as part of a theme, where the plugin does not have to be installed separately, does not have a settings page, but instead has the relevant information defined within the code/theme. Is this possible/advisable? If so, could you point me in the right direction?

**Comment by afragen** [comment]
The answer is 'it depends', but it's not designed that way.

It might be possible to load the whole plugin within your theme and activate it, however, the plugin was designed to be installed and activated by the user. That leaves much less _extra code_ distributed with your theme and additionally allows the user the benefit of keeping the updating code (this plugin) up to date too.

The settings page is only viewable for admin level users, `update_plugins` and `update_themes` capabilities. If you're theme is in a private repo then your users will need access to the settings page.

If you could describe the ultimate goal perhaps there's another solution like a hook that disables the Settings page?

**Comment by oncecoupled** [comment]
Thanks Andy, I appreciate the feedback. 

Ideally, I'll distribute a .zip to theme purchasers, and once installed have the capability to push updates from my private GitHub repo. My end users aren't tech savvy though, so I need to make this process as simple as possible.

My most recent thought is to use https://github.com/TGMPA/TGM-Plugin-Activation to install this plugin, manually pass in the relevant api access token, and then disable the settings page as 99% of my users won't need access to it.

Best,
Lauren

**Comment by afragen** [comment]
Hey Lauren,

How about this workflow. Have your customer install and activate GitHub Updater. Install the theme from the GitHub Updater's remote install page.

All they would need is URI and access token. No need to had out zip files.

Try it yourself and let me know what you think. I think I made it pretty easy. :wink: 

What settings page are you referring to? GitHub Updater, TGM Plugin Activation, or your own?

Locally I've added a filter hook to disable GHU's settings page, but they might need it for something else. Just testing that idea.

**Comment by oncecoupled** [comment]
I did consider that, but I'm not yet sold on it for two reasons:

1. I want to make it a mildly more challenging for people to share my
theme(s). I think they'd be less likely to send a zip to a friend than to
share the api token.

2. I want to keep the process as simple and familiar as possible, i.e. zip
upload. I'm targeting food bloggers and as simple as your plugin is, in my
experience it will seem daunting.

As for disabling the settings page, I'm referring to GitHub Updater. It's
something most of my users won't understand, so I don't want them worried
about it. If someone does need access, they'll find it easy to edit the
theme and remove the lines where I unhook it.

Best,
Lauren

On Sunday, July 26, 2015, Andy Fragen <notifications@github.com> wrote:

> Hey Lauren,
>
> How about this workflow. Have your customer install and activate GitHub
> Updater. Install the theme from the GitHub Updater's remote install page.
>
> All they would need is URI and access token. No need to had out zip files.
>
> Try it yourself and let me know what you think. I think I made it pretty
> easy. [image: :wink:]
>
> What settings page are you referring to? GitHub Updater, TGM Plugin
> Activation, or your own?
>
> Locally I've added a filter hook to disable GHU's settings page, but they
> might need it for something else. Just testing that idea.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afragen/github-updater/issues/266#issuecomment-125027118>
> .
>


-- 

<http://oncecoupled.com>
Lauren Gray / Owner, Lauren Gray Designs
Visit us online at: http://oncecoupled.com
Schedule a 30 minute, no fee <https://oncecoupled.youcanbook.me/>
consultation!

Please be aware that due to high workload, I check my email twice daily,
scheduling all replies for 8am the next morning. Thank you for
understanding this move to more efficiency and effectiveness. It helps me
accomplish more to serve you better.

**Comment by afragen** [comment]
So I've got a working solution to remove the settings page, but the user will need to put in the access token in the settings page in order to receive updates. Catch-22

People will always find a way around if motivated. Simplest idea is usually easiest to maintain.

Eventually any paid user will have access to the theme's URI and its access token. Might be easier to trust your users to be good net citizens. Certainly would make installation simpler.

Easiest way to ensure that the theme is installed correctly and will receive updates is to use GHU remote theme install feature. With the disable settings page hook active in your theme, the end user would never see that page again, unless they switch themes.

If going this route distribute GHU zip with instructions. Make sure you pre-download the zip, expand and rename, then re-zip, otherwise renaming with update will cause plugin to become disabled.

**Comment by oncecoupled** [comment]
Hm, so no way to manually assign the access token via theme?

I agree, there's a certain amount of trust that has to be given, and no solution presented here is going to lock down this theme. The perceived value of a .zip file is greater than that of a single-line access code, however. Plus, while *I* certainly think your installation is simple, I know that many basic users will not -- so installing by zip is still the ideal solution, being sure that folder/repo are named appropriately.

All that said, I'll definitely keep this solution in mind, as you're right - it may be the best solution at this time.

Either way, I appreciate you taking the time to discuss possible solutions with me.

**Comment by afragen** [comment]
Originally, I had the access token as an additional header item but deemed it much less secure as every copy of the theme would then include this data. It was changed around version 3 or so when I created the settings page. No plans to reintroduce it. Sorry.

I do understand your feeling of the value between a zip file and a couple of lines of information. Though from a practical standpoint there is none, except possibly adding some perceived complexity of installing the theme via GHU might be more protective than posting a zip file online to share.

Another thought, have you considered using a private Bitbucket repo? They're free. The workflow would be to have your user create a Bitbucket account and then you would give `read` access to each user. In this way you would precisely control who can access your theme. The only way for someone to share your theme would be for them to not only share the URI but to share their Bitbucket credentials.

Practically speaking your could control access on a per user basis. The user would still have to enter their credentials into GHU from the settings page and remote install the theme. At that point, not token is required, just a checkbox indicating a private repo.

If you want to try is option and need help testing and/or setting this up let me know

**Comment by oncecoupled** [comment]
Andy,

I appreciate this intellectual discussion and see where you're coming from.

I understand that there is no real difference in value between a zip file vs a couple lines of code, because in the end the receipt is an installed theme. However, I think the perceived value comes from the viewpoint of sharing. I'm either giving someone the theme by uploading it for them, or I'm sharing a couple lines of code with them and they're taking the theme themselves, making me less accountable for their actions. Is it fundamentally the same? Yes. I think that it will make a difference in accountability, however.

More importantly, I think we're at an impasse regarding my clientele. I by no means think that food bloggers are incapable of installing a theme via the methods you've suggested, and see how they are certainly more ideal. Having worked with many one-on-one, however, I know they spend a lot of time discovering things that, as a programmer and millennial, seem easy for me. I want them to be able to install a theme via the instructions that they are most accustomed to and are most easily found on Google: zip install. I don't mind doing some more complicated code in my theme (assuming it doesn't impact performance) to make the install and update process easier on them.

That said, I'd certainly give up both the zip install and hiding the settings page if it were to make a huge impact on my theme or audience. However, right now it seems like neither will have negative effects that outweigh the benefits: ease of use for even the most basic WordPress user -- skipping the plugin install and settings in favor of the more familiar zip upload that installs the plugin and assigns the settings for them.

I did go ahead and access the site options and manually assign the access token for my theme if the option exists. It checks whenever my theme's settings page is loaded, and outputs some text to let the site owner know if their theme is currently set up to handle updates through your plugin. I understand this is less secure, but I'm using a private GitHub repo and have set the access token with no write capabilities. I'm also speaking with Gary Jones next week, and will get his opinion on the code as it's currently written -- perhaps it is a pipe dream that I'll have to scrap!

Again, I really appreciate this discussion and value your feedback. I don't see it as an end-all be-all yet, but perhaps that's my own lack of understanding. Whether or not this solution works out for me, I'll certainly contribute to the project just to express how much I respect the time you've spent assisting me with your plugin and its functionality. :)

Best,
Lauren

**Comment by afragen** [comment]
Thanks Lauren, I appreciate the kind words. @GaryJones is a brilliant developer and helped tremendously with is plugin early on. Perhaps he might be able to come up with another solution.

Using TGM Plugin Activation will likely be a great way to include GHU in your theme. Perhaps I can come up with a class you could add to your theme that would add that access token to the Settings automatically. Then all you would have to do is add that class file and some config data to your theme.

If that sounds plausible let me know and I'll see what I can com up with.

**Comment by oncecoupled** [comment]
Sure Andy, I'll speak with Gary and see what he recommends I do to improve the functionality on my end first.

**Comment by afragen** [comment]
So I've been playing around and I've gotten it so a simple hook returning an array of the repo and token in a key/value pair will set the token from the theme's functions.php file. It would be something like the following.

```php
add_filter( 'github_updater_token_distribution', 'my_set_token' );
function my_set_token() {
	return array( 'foodie_theme' => 'kjasdp984298asdvhaljsg984aljhgosrpfiu' );
}
add_filter( 'github_updater_show_settings', __return_false() );
```

That in combination with the following hook to hide the Settings page should work to your specs. The user would just need to somehow install GitHub Updater. Via TGM Plugin Activation would probably be best.

**Comment by afragen** [comment]
If you want to try it out switch to the `token-distribution` branch. Use 'check again' and new branches will be visible to the branch switcher.

**Comment by yafred** [comment]
@oncecoupled 
In your case (you are speaking to customers), you could also explore end to end solutions (with license management) like [EDD Software Licensing](https://easydigitaldownloads.com/downloads/software-licensing/) or [WP Updates](http://wp-updates.com/) + [Sellwire](http://sellwire.net/).

You should use [Git Updater](https://github.com/afragen/github-updater) to keep your beta testers aware of all your changes.

my 2 cts

**Comment by afragen** [comment]
Hey Lauren,

Anything more we need to do here or did you find an alternate solution? Is so, please let me know I'm curious. 

Thanks,
Andy

**Comment by oncecoupled** [comment]
Sorry Andy,

I spent last week moving and am still settling in. I'm meeting with Gary on
Thursday, and haven't had a chance to look at your new solution yet. I did
have some working code, but it certainly wasn't elegant. I'll definitely
let you know this weekend what gets implemented!

Cheers,
Lauren

On Tue, Aug 4, 2015 at 8:08 PM, Andy Fragen <notifications@github.com>
wrote:

> Hey Lauren,
>
> Anything more we need to do here or did you find an alternate solution? Is
> so, please let me know I'm curious.
>
> Thanks,
> Andy
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afragen/github-updater/issues/266#issuecomment-127809924>
> .
>



-- 

<http://oncecoupled.com>
Lauren Gray / Owner, Lauren Gray Designs
Visit us online at: http://oncecoupled.com
Schedule a 30 minute, no fee <https://oncecoupled.youcanbook.me/>
consultation!

Please be aware that due to high workload, I check my email twice daily,
scheduling all replies for 8am the next morning. Thank you for
understanding this move to more efficiency and effectiveness. It helps me
accomplish more to serve you better.

**Comment by afragen** [comment]
No hurry Lauren. Just wondered if you had any further questions.

Andy

**Comment by oncecoupled** [comment]
Thanks Andy, you've saved me from the horrendous block of code below. :+1: 
When do you expect to add this to the main branch?
```
<?php
/**
 * Update Notification Metabox
 * @since 1.0.0
 */
function update_metabox() {

	// get the current site options
	$options = get_site_option( 'github_updater', Array() );
	$name = isset( $options[ 'tasty-theme' ] ) ? esc_attr( $options[ 'tasty-theme' ] ) : '';
	$expectedAccess = 'abc';
	// no plugin
	if ( is_plugin_inactive( 'github-updater/github-updater.php' ) ) {
		?>
		<div class="section-title">No update plugin detected.</div>
		<div>It looks like you do not have the GitHub updater plugin installed and activated. You will not be able to receive automatic updates without this plugin. Please contact support@oncecoupled.com for more information.</div>
		<?php
	}
	// plugin installed
	else {
		// if the access code isn't as expected, try to reset.
		if ( $name != $expectedAccess ) { 
			echo 'Not currently supported... Trying to reset...<br>';
			$options[ 'tasty-theme' ] = $expectedAccess;
			// re-get the current site options
			update_site_option( 'github_updater', $options );
			$options = get_site_option( 'github_updater', Array() );
			$name = isset( $options[ 'tasty-theme' ] ) ? esc_attr( $options[ 'tasty-theme' ] ) : '';
		}
		// success
		if ( $name == $expectedAccess ) {
			?>
			<div class="section-title">Updates enabled!</div>
			<div>Your theme will receive automatic notifications when an update is available!</div>
			<?php
		}
		// access code not reset
		else {
			?>
			<div class="section-title">Something is wrong...</div>
			<div>It looks like you have the updater activated, but we're unable to set you up with the proper access code to receive updates. Please contact support@oncecoupled.com for further assistance.</div>
			<?php
		}
	}

}
```

**Comment by afragen** [comment]
Lauren, https://github.com/afragen/github-updater/commit/439ee1124fecddcb225ca74e0ff357e6b6dc4bff just pushed to `develop` branch. Please take a look at README as instructions above changed a bit. I hope to have it pushed to `master` by the end of the week.

Essentially now,

```php
add_filter( 'github_updater_token_distribution',
	function () {
		return array( 'my-private-theme' => 'kjasdp984298asdvhaljsg984aljhgosrpfiu' );
	} );
add_filter( 'github_updater_hide_settings', '__return_true' );
```

Anonymous function may have only one key/value pair.

Thanks for the donation. Believe it or not your's is the first. :+1: 

BTW, curious what @GaryJones said, can you share?

**Comment by GaryJones** [comment]
In regards, to this, @oncecoupled said that you'd added a filter, but wasn't sure if it would be available in the released version of GHU by the time she wanted to release her theme. I said to ask you what your expected timeline would be, and that there's a strong chance you could release sooner (~few weeks) rather than later (~few months), because you're a nice guy like that :-)

**Comment by afragen** [comment]
Thanks for the kind words Gary. Releasing sooner was always in my plans.

**Comment by oncecoupled** [comment]
Andy, I honestly could not believe I was the first to donate. Your plugin is integral to accomplishing one of my goals for this project and your support for it has been amazing. If nothing else, the time you put into responding to questions (not updating your code, but just thinking through goals and pointing us in the right direction) is worth the donation. This is only a small token of appreciation. I had already planned on contributing more in the future, but in the mean time I hope others also express their thanks for the time you've shared with us!

**Comment by afragen** [comment]
Thanks Lauren. I do appreciate it.

I greatly respect those that code for a living and I'm glad don't have to rely on my coding for a living. I am fortunate that I am able to code as a hobby, distraction, and mental exercise.

I look at GHU as one of the ways that I can give back to the WordPress community and in particular to the developers and designers that enable the rest of us to look so good online.

If there's anything else you need, please let me know.

Andy
