### ISSUE TITLE
Breaks Gravity Forms Add-Ons downloads page and may install incorrect plugins

### ISSUE THREAD

**Issue by webspecnick** [afragen/github-updater#267]
When this plugin is activated along with Gravity Forms and a user goes to Forms->Add-Ons all of the install buttons no longer download the correct plugins. Some fail entirely, but some __download a different plugin__ from the official WordPress repo. This can cause a security issue as the user may unknowingly download and activate unwanted plugins on their site, thinking it came from the Gravity Forms plugin.

Steps to Reproduce
1. Install a fresh copy of WordPress, 2015 Theme
2. Install and activate Gravity Forms plugin and activate a pro license
3. Install and activate the GitHub Updater plugin
4. Go to Forms->Add-Ons in the backend
5. Click on the Install button for the Coupons Add-On to see the installation fail
6. Click on the install button for MailChimp and see it download MailChimp by MailChimp and Crowd Favorite (https://wordpress.org/plugins/mailchimp/) <- This is an unwanted plugin from w.org
7. Deactivate GitHub Updater
8. Go back to Forms->Add-Ons
9. Install Coupons Add-On to watch it succeed
10. Install MailChimp addon to watch it download Gravity Forms MailChimp Add-On, the correct plugin,  from not w.org.
11. Verify that the two different MailChimp plugins are present in the plugins screen of the site.

The behavior also happens in other addons such as ActiveCampaign Add-On

**Comment by afragen** [comment]
I'm reaching out to @rocketgenius to see if I can get some assistance here.

**Comment by stevehenty** [comment]
Gravity Forms uses the core WordPress functionality for installing/updating so I'm not sure there's anything we'll be able to do to help I'm afraid.

**Comment by afragen** [comment]
This plugin also uses core WordPress functions for updating. 

Without the benefit of the above mentioned plugins to test with, I'm afraid I can't help much.

**Comment by afragen** [comment]
It would be helpful it reach out in the Gravity Forms forums to see if others can replicate this issue.

**Comment by stevehenty** [comment]
This is the first report we've received. Could I ask you to get in touch and ask for the ticket to be assigned to me? I'll sort you out with everything you need and follow up with you. https://www.gravityhelp.com/contact-us/

**Comment by afragen** [comment]
@webspecnick see @stevehenty's comment above. It should help us identify and hopefully duplicate the issue so it can be fixed.

**Comment by webspecnick** [comment]
Hope I did that right, I sent in a priority support ticket with the details to this issue.

**Comment by stevehenty** [comment]
You did, but my message was intended for @afragen - Andy would you like to get in touch?

**Comment by afragen** [comment]
Sure Steve, email is easiest. andy (at) thefragens (dot) com

**Comment by afragen** [comment]
I have a solution, I've email'd @stevehenty as there are 2 ways to implement it. Neither, unfortunately seems to be without certain consequences to GHU. :-1:

**Comment by afragen** [comment]
@webspecnick @stevehenty can you check to see if latest `develop` branch with https://github.com/afragen/github-updater/commit/d35842dd015e0bdb97f570a3159c47aa443de1b7 fixes this issue? Thanks.

**Comment by webspecnick** [comment]
Updating to the develop branch fixed the issue. I checked with the MailChimp addon and a few others and they downloaded the correct plugins.

**Comment by afragen** [comment]
Great! Also waiting for confirmation from @stevehenty

**Comment by afragen** [comment]
Corfirmed by @stevehenty too. Plan it push this to master soon.

@webspecnick thanks for the detailed bug report.
