### ISSUE TITLE
There is no option to update the plugin installed via github updater?

### ISSUE THREAD

**Issue by viral810** [afragen/github-updater#268]

**Comment by afragen** [comment]
GitHub Updater requires the addition of at least one header line to the plugin or theme for updating to work. The developer of the plugin must provide this. Most devs are amenable to PRs for this as it's only a header line.

GitHub Updater is, however, capable of installing any plugin or theme.

**Comment by viral810** [comment]
I can only update the plugin is by "Enable Branch Switching" option in the settings. and click on try another branch in plugin options page and choose "master" to update it. Is it right way to do it?

**Comment by afragen** [comment]
Can you post the URI of the plugin, or post it's headers?

Branch switching is a useful method to either switch branches or to re-install the same branch. If a version bump is noted then the regular update process should proceed. It will take some time for the transients to clear or you could clear them using the _Check Again_ button.

**Comment by afragen** [comment]
> I can only update the plugin is by "Enable Branch Switching" option in the settings. and click on try another branch in plugin options page and choose "master" to update it. Is it right way to do it?

No, if the plugin is properly setup to use GitHub Updater, then any commit that updates the version number will result in an update message in the dashboard, just like with .org plugins. It may take 12 hours for the transients to expire and show the update. If you are impatient, you can go to the `update-core.php` page and use the 'Check Again' button to clear/refresh the transients.

**Comment by viral810** [comment]
Hey Andy, I changed the header of the plugin properly and it is working perfect for now. Thank you so much for following up with me. Great work with plugin!! Thanks again.

**Comment by afragen** [comment]
Excellent and you're welcome.
