### ISSUE TITLE
Remote install

### ISSUE THREAD

**Issue by szepeviktor** [afragen/github-updater#269]
My plugin is also banned on WP.org:
https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/mu-plugin-upload-from-url/plugin-upload-from-url.php

Are you interested in adding this functionality?

**Comment by szepeviktor** [comment]
Oh! I see you've developed *Settings / Install Plugin*. Is it possible to upload a non-git zip there?

**Comment by afragen** [comment]
No, the URI there is the same as one might put in the header line.

**Comment by szepeviktor** [comment]
OK. It is up to you to add this. But it has not much in common with GitHub updating.

**Comment by afragen** [comment]
> OK. It is up to you to add this functionality. But it has not much in common with GitHub updating: it removes -master from the directory name in GitHub ZIP-s.

Not quite sure I understand. Renaming of downloads from GitHub, Bitbucket, and GitLab should be finally fixed in latest `develop` branch. I switched to using `upgrader_post_install` hook and renaming got a lot simpler.

**Comment by szepeviktor** [comment]
> it removes -master from the directory name in GitHub ZIP-s.

This is the only common point of GHU and my plugin-upload-from-url MU plugin. That why mentioned this similarity.

**Comment by afragen** [comment]
I found I had to re-write the directory using `upgrader_source_selection` and when using `upgrader_post_install` the $extra_hook parameter contains the slug. It makes for easier renaming.

If you are referring to adding the ability to upload a zip file, this is already in core. No need to repeat it here. :wink:

**Comment by szepeviktor** [comment]
> ability to upload a zip file

Actually my plugin:

1. downloads a ZIP file from a URL
1. installs the plugin in it

This feature was rejected from WP.org, only other parts could be hosted there:
https://wordpress.org/plugins/plugin-installer-speedup/
I've made it into a separate MU plugin.

**Comment by afragen** [comment]
Otto has a real thing about installing plugins from outside repos. That's why this isn't in the repo either. :-1:

**Comment by szepeviktor** [comment]
I understand them. They are there to host plugins, not to host plugins elsewhere.

**Comment by szepeviktor** [comment]
You could also upload your plugin as *GitHub update notification*.
Ofcourse without the part doing the actual update.

**Comment by afragen** [comment]
That's a very interesting idea.

**Comment by szepeviktor** [comment]
I will contribute by handling support questions.

**Comment by szepeviktor** [comment]
Please consider adding a new item on the admin bar beside WP update notification.

**Comment by afragen** [comment]
Do you mean like, https://github.com/szepeviktor/github-link ?

**Comment by szepeviktor** [comment]
Github-link displays icons beside plugin actions. I am thinking about adding an item to the admin bar.

**Comment by szepeviktor** [comment]
I man the purpose of the plugin would be to show GitHub updates in the admin bar. (or elsewhere but not where WP core displays it)

**Comment by afragen** [comment]
My intent with GitHub Updater is to provide a seamless integrated update process. I don't really want to show how the plugin distinguishes itself from the normal core processes.
