### ISSUE TITLE
Plugin file does not exist after updating

### ISSUE THREAD

**Issue by mrterryh** [afragen/github-updater#271]
Hi guys,

Loving your plugin – it works like a charm (almost)! I just have one quick query.

After updating a plugin and reloading the plugins page, I get this error:

> The plugin mrterryh-mytestplugin-72460a089d82/plugin.php has been deactivated due to an error: Plugin file does not exist.

It looks like GitHub Updater is renaming my plugin directory.

I have GitHub Updater installed as a Must Use plugin.

Has anyone else encountered this issue? How do I fix it?

**Comment by afragen** [comment]
What version and branch are you using? 

Also, I'm converting the renaming code to use a different filter so this no longer happens. Try out the `upgrader-post-install` branch and see if this still happens.

To fix this you will need to rename the folder using FTP, or you might try refreshing the transients and use the branch switch to reinstall the same branch of your plugin. Try switching to the above GHU branch first.

**Comment by mrterryh** [comment]
@afragen I've tracked down the issue.

When installing the plugin remotely through GitHub Updater, it creates the plugin with the directory name `plugin-72460a089d82`

When I update the plugin, it renames the directory to `plugin`

So it looks like the hash needs to be removed from the plugin dir name on remote install.

**Comment by afragen** [comment]
Yes, there's a change in the hook used to rename in latest develop branch. Try using that and LMK if any further issues or if it works. TIA

**Comment by afragen** [comment]
> When installing the plugin remotely through GitHub Updater, it creates the plugin with the directory name plugin-72460a089d82

I shouldn't ever do that on a remote install.

**Comment by mrterryh** [comment]
I did use that branch but it didn't make a difference. Still getting the same error.

**Comment by mrterryh** [comment]
I've fixed this temporarily by adding this block of code to the top of the `Base::upgrader_post_install()` method:

    // Remove hash from plugin directory name
	$destination = $result['destination'];

	$basename = basename($destination);
	$basename = explode('-', $basename);
	$remove = '-' . end($basename);
	$newDestination = str_replace($remove, '', $destination);

	rename($destination, $newDestination);
	// End remove hash from plugin directory name

**Comment by afragen** [comment]
Can you share the URI, the above code shouldn't be needed.

**Comment by afragen** [comment]
I can confirm this and will fix it. Thanks. I'll post back here when it's fixed so you can test.

**Comment by mrterryh** [comment]
Hi Andy,

Any news on this? I'd love to start using this plugin in production.

**Comment by afragen** [comment]
I've gotten it fixed in the `wp-cron` branch. If you want to test this let me know if it's working for you. Next step will be pushing that to the `develop` branch and finally to `master`. At least that's the plan. I hope to have that all done within the next week or so.

**Comment by afragen** [comment]
I've push the latest stuff to the `develop` branch. If I don't have any issues or don't hear about any from those testing. I'll push to `master` by the end of the week.

**Comment by mrterryh** [comment]
Awesome, thanks. Will give it a go today.

**Comment by mrterryh** [comment]
I can confirm that this issue is fixed on the current `develop` branch.

**Comment by afragen** [comment]
Excellent. Thanks.

**Comment by cferdinandi** [comment]
Hi there. This is happening to me on just one of my plugins. I've tried deleting it completely and reinstalling it, including manually removing the file via an FTP client on the server, but it continues to happen.

Any insights on how to resolve this? I'm on version 6.0.0 of GitHub Updater.

**Comment by afragen** [comment]
@cferdinandi can you please create a new issue. Adding this on to an issue that was closed over a year ago is not optimal.
