### ISSUE TITLE
Only updating to penultimate commit

### ISSUE THREAD

**Issue by fredbradley** [afragen/github-updater#273]
Hello, 

I have installed successfully, and tested it. 

The updater is triggered and tells me that my plugin (on repo) is v1.3. So I update. 

But it download the version/commit previous to that (in my case v1.2.1) - which is essentially what is on my wordpress installation already! 

Is this a known bug? 

Am I doing something wrong?

**Comment by afragen** [comment]
If you are tagging releases, when a new update is discovered the most recent tagged release will be downloaded, if branch is master. 

I'm guessing you started tagging and missed the last one.

**Comment by afragen** [comment]
@fredbradley is this still an issue?
