### ISSUE TITLE
Notices when installing a plugin from wordpress repo

### ISSUE THREAD

**Issue by EJOweb** [afragen/github-updater#276]
Hi, I'm getting the following notices when I'm installing a plugin from WP-repo the normal way. 

Notice: Undefined index: repo in /[...]/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 602

Notice: Undefined index: extended_repo in /[...]/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 602

Notice: Undefined property: Plugin_Installer_Skin::$plugin in /[...]/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 490

Notice: Undefined property: Plugin_Installer_Skin::$plugin_info in /[...]/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 495

Notice: Undefined offset: 1 in /[...]/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 758

Notice: Undefined property: Plugin_Installer_Skin::$plugin_info in /[...]/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 495

Notice: Undefined offset: 1 in /[...]/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 758

Notice: Undefined property: Plugin_Installer_Skin::$plugin_info in /[...]/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 495

Notice: Undefined offset: 1 in /[...]/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 758

**Comment by afragen** [comment]
Is this during the actual installation? Is this repeatable for you? What plugin are you installing? 

Currently I can't reproduce this.

**Comment by EJOweb** [comment]
I'm using the master branch v4.6.2. I downloaded the zip from github and uploaded it via FTP to my plugins. I'm using Wordpress 4.2.4 and have WP_debug turned on. 

It happened while installing multiple plugins.

**Comment by afragen** [comment]
Can you switch to the develop branch and see if this persists?

**Comment by EJOweb** [comment]
With the develop branch the notices don't occur.

**Comment by afragen** [comment]
Great! Looks like this is fixed and should be pushed to `master` this week.
