### ISSUE TITLE
Consider changing your title

### ISSUE THREAD

**Issue by dosire** [afragen/github-updater#278]
Thanks for adding GitLab support, consider updating your project description:
This WP plugin will update GitHub and Bitbucket hosted plugins and themes
=>
This WP plugin will update GitHub, GitLab and Bitbucket hosted plugins and themes

**Comment by afragen** [comment]
Oops, forgot about that. Done. Thanks for pointing it out.

**Comment by dosire** [comment]
Thanks for updating @afragen
