### ISSUE TITLE
Parsedown error with php7

### ISSUE THREAD

**Issue by markc** [afragen/github-updater#280]
I'm not sure which Parsedown.php script you are using otherwise I'd try an upstream pull request. However, there is a [Uniform Variable Syntax] error when using php7 in the included Parsedown.php script on line 894 with a `PHP Fatal error:  Uncaught Error: Function name must be a string...`.

This line...

    $markup .= $this->$Element['handler']($Element['text']);

needs to be changed to this to enable the correct left-to-right precedence in php7...

    $markup .= $this->{$Element['handler']}($Element['text']);

and remain compatible with current versions of PHP (but untested by me).

[Uniform Variable Syntax]: https://github.com/tpunt/PHP7-Reference#uniform-variable-syntax

**Comment by afragen** [comment]
The Parsedown.php script used is referenced in the README. Does the suggested change work for PHP7?

**Comment by markc** [comment]
Yes, adding the {} brackets works with php7. According to the docs I've read it should be a safe change and backwards compatible with earlier versions but I haven't actually tested that yet.

**Comment by afragen** [comment]
Can you swap out the current version of Parsedown.php into GHU and see if that works?

**Comment by afragen** [comment]
Current version from https://github.com/erusev/parsedown

**Comment by markc** [comment]
That's odd, I did a `mv vendor/Parsedown.php vendor/Parsedown.php.fixed` and clicked around a few pages and did not get an error... without any vendor/Parsedown.php at all! Anyway I grabbed the new 
Parsedown.php and still no error so I guess they have fixed it.

    wget https://raw.githubusercontent.com/erusev/parsedown/master/Parsedown.php

**Comment by markc** [comment]
Yep, here we go, there is quite a few of these `$this->{something}()` constructs so it looks like someone has made sure it runs under PHP 7s new uniform syntax rules...

https://github.com/erusev/parsedown/blob/master/Parsedown.php#L168

**Comment by afragen** [comment]
Good, then updating Parsedown,php should fix these errors. I'll push out an update soon.

**Comment by afragen** [comment]
Update to `develop` pushed. Please let me know if any errors persist.
