### ISSUE TITLE
Conflict with The Event Calendar

### ISSUE THREAD

**Issue by darknailblue** [afragen/github-updater#282]
There seems to be some sort of conflict with using The Events Calendar plugin from Modern Tribe.  Basically what happens is that if the plugin is installed then GitHub Updater becomes unaware of the headers in themes (not sure about plugins) and therefore will not update.

No clue as to why or how to diagnose.

**Comment by afragen** [comment]
I'm going to need a lot more info on this. I've been using The Events Calendar, Events Calendar PRO, and many of my own Events Calendar plugins with GHU for a long time and I've never noticed any issues.

Can you share the theme URI?

**Comment by afragen** [comment]
Closed for lack of activity.
