### ISSUE TITLE
Cannot update theme to another version

### ISSUE THREAD

**Issue by milesimarco** [afragen/github-updater#283]
Hi,
in the last update 5.0.1 i can't change theme version to other branches / releases. The dropdown appears but there isn't the "Install" button.

Thank you

**Comment by afragen** [comment]
Try using the 'Check Again' button from the core update page. Transients likely need to be refreshed.

**Comment by milesimarco** [comment]
Hi,
I tried many times and with more websites. I include your package in a wp theme for Italian schools/municipalities and many others noticed this. At the moment I have rolled back to 4.6.2, released a new version of the theme and everything is fine.
Also, 2 of 3 websites where I tested it weren't able to update to the new version of the theme because after the update the default theme got activated. My theme needed to be manually reactivated.

**Comment by afragen** [comment]
This plugin is not designed to be included inside a plugin or theme. It's designed to be installed and activated on its own. That might be part of the problem.

**Comment by afragen** [comment]
Themes might need to be reactivated after rollback or branch switch.

**Comment by afragen** [comment]
@milesimarco are you still having a problem?
