### ISSUE TITLE
Problems with private gitlab installations

### ISSUE THREAD

**Issue by zelle7** [afragen/github-updater#284]
I stumbled over some problems with a private gitlab repo. 
I have a child theme with following header in the style.css file:
```
/*
Theme Name:           xy child
Theme URI:            https://mygitlab.org/wordpress/childtheme
Version:              0.1.1
Description:          Child theme
Author:              author
Template:             parentheme
Text Domain:          xychild
GitLab CE:          https://mygitlab.org
GitLab Theme URI:     https://mygitlab.org/wordpress/childtheme
GitLab Branch:        master
*/
```

The installation works fine, although it would be nice if i could already enter a private token for the gitlab repo before I install the first plugin/theme from there.

The problematic part comes when I want to update my theme. 
![error_loading](https://cloud.githubusercontent.com/assets/2727205/9490440/39d9739a-4be8-11e5-9c6b-33aded78f842.png)

The plugin tries to fetch the zip file from the api/v3 url which I think is not correct at this point. 
I fixed it for our purpose that we changed the gitlab.com urls in the code with our private gitlab url. With this way everything seems to work fine.

**Comment by afragen** [comment]
If you use the Install Theme from the Settings page, you should be able to add the private token there.

Is your private token set when you try to do the update? If there is an incorrect download URI can you show me more precisely what the correct URI is and what the plugin is using?

**Comment by zelle7** [comment]
If I first install the theme from my private gitlab I have no way to enter a key for the private gitlab and only can enter my token in the gitlab.com field ( I noticed that this key was used then also for my private gitlab ). 
![selection_001](https://cloud.githubusercontent.com/assets/2727205/9513782/0d6f440e-4c94-11e5-95cb-834761da4a9d.png)
![selection_003](https://cloud.githubusercontent.com/assets/2727205/9513793/29f1d61e-4c94-11e5-84ec-f5f2fc68540a.png)

After  I have installed the theme the private repo token field appears
![selection_005](https://cloud.githubusercontent.com/assets/2727205/9513799/428cd3f4-4c94-11e5-890a-602c7a7f0b74.png)

It seems that in the updating process the plugin again tries to go to the "https://mygitlab.org/api/v3/?ref=..." url. Shouldn't it be going against the same url as it was at the installing? (last screenshot) Also the private token seems not to be added to the url.
![selection_004](https://cloud.githubusercontent.com/assets/2727205/9513802/4ba9cae6-4c94-11e5-8b67-3fab654ba380.png)
![selection_002](https://cloud.githubusercontent.com/assets/2727205/9513871/175b392c-4c95-11e5-9d3b-fde34c8f61df.png)

**Comment by afragen** [comment]
I don't have a GitLab CE/Enterprise installation to test with, but when I created the option to use GitLab CE/Enterprise.

If a GitLab.com private token is set the Install tab will not show a space for setting a GitLab CE private token. As such the normal installation may not work properly.

Do you have both GitLab.com and GitLab CE themes installed?
Do you have both areas for private tokens set correctly?
After you have all private tokens set correctly, does updating work?

If the download endpoint is incorrect, can you show me what the correct endpoint is? I was trying to figure it out using GitLab's documentation.

**Comment by afragen** [comment]
Can you switch branches to `fix-gitlab-ce` and see if that resolves the issues? You will need to reactivate GitHub Updater after the branch switch.

**Comment by zelle7** [comment]
The installation works fine with your branch. But the updates still not work (I there are no udpate notificatons)

 - To your questions above:
 - There is only a gitlab ce theme installed.
 - Both private tokens should be set correctly (in my case only the CE token was set, as I have not gitlab.com theme installed.)

I am currently try to debug the process. If I find something I will update my findings here.

Thanks for your great support and quick responses :-)

**Comment by zelle7** [comment]
Ok I forgot to add the CE Url again after I have tried some things out in the plugin. The theme installation and updating seems to work now. I will do further testing on another system.

But the plugin updating still seems not to work.

**Comment by afragen** [comment]
Screenshots are helpful, just don't block out too much.

**Comment by afragen** [comment]
Can you update to latest `fix-gitlab-ce` branch using the branch switcher. You will have to reactivate the plugin.

**Comment by afragen** [comment]
I'm going to merge these into `develop`. Please test and let me know if this issue is fixed. Thanks.

**Comment by afragen** [comment]
@zelle7 does this problems persist in the `develop` branch?

**Comment by zelle7** [comment]
I'm still testing, as sometimes it seems to work and other times the update mechanism again won't work (won't see any updates although the version on gitlab is clearly higher). I  have no idea what the problem could be.

**Comment by afragen** [comment]
Remote data is cached for 12 hours. You can clear this cache using the 'Check Again' button from the update-core.php page.

**Comment by afragen** [comment]
@zelle7 is there still an issue or is it fixed. Thanks.

**Comment by afragen** [comment]
Please re-open if this persists.
