### ISSUE TITLE
Unable to update my plugin

### ISSUE THREAD

**Issue by TheMackCod** [afragen/github-updater#285]
Hello all,

I have tried to install and update my plugin through Github-Updater. I did managed to install it and activate it. But when i make changes to my Bitbucket repo, i don't see the changes on my site.
Here's my plugin's header : 

/*
Plugin Name:       	       Arc
Plugin URI:        	       https://bitbucket.org/Ivan-Lopes/arc
Description:       	       Yet another admin theme for Wordpress...
Version:           	               1.0.6
Author:            	                Ivan
License:           	        None
Text Domain:       	        Ivan-Lopes/arc
Bitbucket Plugin URI: 	https://bitbucket.org/Ivan-Lopes/arc
GitHub Branch:     	        master
*/

**Comment by afragen** [comment]
First, you should fix the `GitHub Branch` to be `Bitbucket Branch`. ;)
Are you tagging releases? Are you updating the version number?

How long are you waiting to check for the updates? Transients are set for 12 hours, so it may take that long to see an update. If you use the 'Check Again' button on the core update page the transients will be deleted and fresh data retrieved.

**Comment by TheMackCod** [comment]
Thank you very much for the quick response.
I have indeed made a mistake in header. Silly me !
The file has been updated and pushed to Bitbucked.
After using "Check Again" i get the file update message.

Another thing though, i have this popu message saying :
"GitHub Updater was not checked. GitHub Updater Error Code: 403
GitHub API's rate limit will reset in 28 minutes.
It looks like you are running into GitHub API rate limits. Be sure and configure a Personal Access Token to avoid this issue. " Is this important ?

Thank you again for the answer, and for the much enjoyed plugin !

**Comment by afragen** [comment]
It is important if you as you have GitHub sourced plugins and themes. GitHub's API has a rate-limit for non authenticated calls. It's really simple to create your own personal access token and eliminate this as an error. I've also heard from the GitHub folks and they would appreciate it too. :wink: 

Please refer to https://github.com/afragen/github-updater#personal-github-access-token
