### ISSUE TITLE
After updating, plugin directory name changes and breaks the site

### ISSUE THREAD

**Issue by cyprienclerc** [afragen/github-updater#286]
Hi,
Thanks for your plugin it's great work ;)
I've just tried this operation 3 times on 2 different wordpress installations.
I click "update now" on my plugin and the result is: the new version successfully downloads but the plugin's folder name changes from 'test' to 'cyprienclerc-test-ec0a6fac1fef' ('cyprienclerc' being my bitbucket account). As a result, the plugin is deactivated and i have to manually re-activate it.
I have tried changing the directory's permission to 775 just in case but that wasn't the issue.

Thanks in advance for your support.

**Comment by afragen** [comment]
What branch and version of the plugin are you using?

Can you share the URI for the plugin so I can test?

**Comment by cyprienclerc** [comment]
I downloaded the latest version of github-updater on https://github.com/afragen/github-updater.
Bitbucket Plugin URI: https://bitbucket.org/cyprienclerc/test
Bitbucket Branch: master

**Comment by afragen** [comment]
I actually just tested by installing from the Install Plugin tab, then decreasing the version number in the plugin and getting an update message and updating. Every worked as expected.

How did you initially install the plugin? 

If you download directly from Bitbucket and install the folder name will not be correct.

**Comment by cyprienclerc** [comment]
Hey. Thanks for your reply.
I tried getting the 'test' plugin with and by ZIP file. Same result. Good to know it's working on other configs. What do you mean by "If you download directly from Bitbucket and install the folder name will not be correct." ?

**Comment by afragen** [comment]
Unzip the download from Bitbucket and see how it is named.

If you don't correct that before you upload it the folder will be named that on installation.

![screenshot_01](https://cloud.githubusercontent.com/assets/1296790/9538993/c6293bb0-4cff-11e5-9bd2-aa73a807536b.png)

**Comment by afragen** [comment]
If you use the Install Plugin tab from GitHub Updater's Settings, the renaming will be correct. This plugin uses that structure so any initial naming will effect any subsequent naming.

**Comment by cyprienclerc** [comment]
Thanks a lot for all your answers, i made it work now.
And thanks for this plugin, it's very handful!
Cheers ;)

**Comment by afragen** [comment]
Excellent. Enjoy and tell your friends.

**Comment by cyprienclerc** [comment]
Actually, didnt really solve the problem.
It's true that when i download the ZIP file from the bitbucket i get a
folder with a "versioned" name. And that doesn't cause any problems. BUT i
tried using the INSTALL A PLUGIN functionality from the github-updater
plugin and as soon as i updated the plugin the same problem happened again:
the new version had a different folder name and as a consequence it
deactivated the plugin.

**Comment by afragen** [comment]
It seems your original `test` plugin is missing.

As I tried to explain above, if the folder name is versioned, it will stay versioned on the update.

Can you provide screenshots so I can have a better understanding of what's happening?

**Comment by afragen** [comment]
I found where you relocated the file and can replicate the issue. I'll look into a fix.

**Comment by afragen** [comment]
Can you use the branch switcher to reload the `fix-gitlab-ce` branch. It contains a fix for the renaming.

**Comment by cyprienclerc** [comment]
That fix worked. Thanks a lot!

**Comment by afragen** [comment]
Thanks for the follow up.

**Comment by afragen** [comment]
@cyprienclerc just an FYI. I just pushed some code to `develop` that should handle the renaming of an update to the correct name. It will require a reactivation of the plugin.
