### ISSUE TITLE
update offered for unreleased version

### ISSUE THREAD

**Issue by gyrus** [afragen/github-updater#289]
I have a parent WP theme on GitHub for which the latest release tag is 2.1.3. I'm working on 2.2, and the style.css etc. have been changed to 2.2 - but I've not added a release tag for it yet.

However, I'm seeing 2.2 being offered as an update on WP installations. See attached screenshots.

![github-releases](https://cloud.githubusercontent.com/assets/609161/9606101/4e166fe0-50b9-11e5-98e8-5671c163b5cd.png)
![wp-updates](https://cloud.githubusercontent.com/assets/609161/9606102/4e1b2b34-50b9-11e5-9f56-56389f984da6.png)

**Comment by afragen** [comment]
The version number in the repo is listed as 2.2, though the latest tag is 2.1.3. As such, you will see an update but will download the tagged version.

To avoid this only update the version number in the master branch when you tag a release.

**Comment by gyrus** [comment]
What do you mean by "the version number in the repo"? I always go by the latest tagged release.

**Comment by afragen** [comment]
The version number in your master branch of this in GitHub is 2.2, whereas the latest tag is 2.1.3.

What happens is that GHU checks for the new version from the style.css in GitHub. If the version is greater on GitHub an update will show. Per the README, if tags are used the download link will reflect the latest tag.

If, as in your current case, the tag is lower than the version in the repo, a cycle of showing an update an installing the tag will result.

**Comment by gyrus** [comment]
OK, didn't realise it checked style.css, I thought it checked for the highest release tag. I'll have to change how I manage things. For me when I'm developing locally and I've got my installations symlinking themes and plugins to my development versions, I like to see the actual (upcoming) version in WP, but I don't tag a release until I'm actually releasing.

**Comment by afragen** [comment]
That's why I personally use a `develop` branch and a semver like x.x.x.x, where the last place is a development bump. GHU is smart enough to update your develop branch based upon the develop version number and not use the tags for anything other than the master branch.
