### ISSUE TITLE
Does github-updater work with Gogs?

### ISSUE THREAD

**Issue by tiptronic** [afragen/github-updater#292]
Hi there,

has - by any chance - someone tested already, if the github-updater works with Gogs (http://gogs.io)?

thx

andy

**Comment by afragen** [comment]
I'll leave this open, but I've never used Gogs and this is the first request I can remember for it. If it is a GitHub fork written in Go, it should be relatively easy to integrate. However, I'm not going to install a Gogs instance, so I have no method of testing and I don't see a API reference anywhere.

**Comment by tiptronic** [comment]
Thx for the feedback... 
Fwiw, I have a running test-repo on my Synology, so if you need something to test that shouldn't be the problem. (As soon as I'm back, I'm going to try it myself, but that may take a bit more than a week from now.)
OTOH installing Gogs (or running Gogs with Docker) is a snap.
Thx anyway for your reply.

(Btw. - I'm running Gogs, because it's ideal for private projects, as the server only needs a fraction of resources (e.g. CPU) than a common git-server.)

**Comment by ck-ws** [comment]
@tiptronic Any news on this? I currently have to decide between GitLab CE and Gogs, but I would opt for Gogs, if we could get it working with GitHub Updater.

**Comment by afragen** [comment]
I don't have Gogs installed. If someone does and can give me an account maybe I/we can figure this out.

**Comment by afragen** [comment]
What I don't see anywhere is documentation of an API for getting file/repo information.

**Comment by ck-ws** [comment]
I have an installation of Gogs running now.

All I found atm is this: https://github.com/gogits/go-gogs-client/wiki

> Aim to be format similar to GitHub v3 APIs.

See the subsites for detailed information, especially:
* https://github.com/gogits/go-gogs-client/wiki/Repositories
* https://github.com/gogits/go-gogs-client/wiki/Repositories-Contents

Disclaimer: Up to now I haven't checked which endpoints GitHub Updater actually uses for the other services.

**Comment by afragen** [comment]
I think I've just gotten GitHub Updater working with Gitea, which I believe is a Gogs fork. Is there still interest in using Gogs?

**Comment by afragen** [comment]
I'm going to close this in favor of using Gitea, a more actively supported fork of Gogs.
