### ISSUE TITLE
Possible to use non GUI wordpress settings page?

### ISSUE THREAD

**Issue by kodeine** [afragen/github-updater#295]
Hello,
I develop plugins for commercial use and i dont want to install github-updater plugin interface to organization websites. Is it possible to use non-gui version of updater? so github-updater can silently update and i can define the github user/pass in a php file. Goal is the plugins are obfuscated and encrypted so i want to hide the github credentials in php rather than displaying them on clients websites.

**Comment by afragen** [comment]
Short answer, yes.

Read the section on Developer Hooks. There are 2 filters available. One to add a GitHub access token and one to turn off the settings entirely.

Your users will have to install GHU.

**Comment by kodeine** [comment]
@afragen alright, sounds good. thanks for the quick response.
