### ISSUE TITLE
PHP Notice Errors

### ISSUE THREAD

**Issue by Frumph** [afragen/github-updater#296]
Settings -> GitHub Updater -> Remote Management [tab]

Notice: Undefined index: ithemes_sync in /home/frumph/public_html/dev/wp-content/plugins/github-updater-develop/src/GitHub_Updater/Settings.php on line 597

Notice: Undefined index: infinitewp in /home/frumph/public_html/dev/wp-content/plugins/github-updater-develop/src/GitHub_Updater/Settings.php on line 597

**Comment by afragen** [comment]
Thanks for the report.

**Comment by afragen** [comment]
This should now be fixed in develop branch.
