### ISSUE TITLE
Renaming on Theme Update still broken

### ISSUE THREAD

**Issue by aariacarterweir** [afragen/github-updater#297]
Hi @afragen. This is a continuation of #253. For a while there, the update feature seemed to work. Lately when I update a theme on PHP 5.3, the front-end of the site goes down and the current theme is set to the temporary folder name. Clicking into appearance/themes and marking the proper theme active seems to resolve the problem.

So it looks like the folder is actually getting renamed properly, but it switches the active theme to the temp folder name instead of just keeping it the same.

thanks again for all the fab work and let me know if i can help debug this.

**Comment by afragen** [comment]
Unfortunately this is also a continuation of #293 too.

I have tried many methods to get the current, active theme to correctly update and re-activate but it seems there is a host folder that retains the active state. As you've discovered you will see an update. Thus far th per only "solution" that I could do was to add a notice and link to re-activate the theme.

If you or anyone else can figure out how to reactivate the current, active theme after an update, please let me know. Unfortunately using `switch_theme()` doesn't seem to work.

**Comment by Frumph** [comment]
Question: https://github.com/afragen/github-updater/blob/develop/src/GitHub_Updater/Base.php#L394

I don't see a $filesystem->move if theme currently exists, (nor) it moving into it's proper namespace name if it doesn't ... I know WordPress will not worry about activating / deactivating if the theme is in it's proper location.. could just fool it by doing a rename of current to $active_theme->name.'-'.$activate_theme->version and then moving the new to the active theme name? (you get the jist ya?)

Just thinking out load really

**Comment by afragen** [comment]
I agree that this is where I need to look. WP_Filesystem->move should be a copy/rename but something about it isn't picking up on re-activating the renamed directory. 

Curious that it's not a plugin issue.

**Comment by Frumph** [comment]
think there's a logic problem... the renamed directory should be the original name of the directory, otherwise child themes and the options that store the theme get messed up (or do you mean something else)

say my theme themes/comicpress/ gets updated  it needs to stay the name themes/comicpress/ not themes/frumph-comicpress-0e342f3/

my suggestion would be to move the current theme to comicpress-4.2 (version num) and the new downloaded be renamed to the original folder name themes/comicpress/  then nothing will break

**Comment by afragen** [comment]
If you look at what's happening. The theme is getting updated and renamed correctly. The problem seems to be that the active theme picks up the downloaded theme name as the new update and activates it. After the copy/rename the downloaded name no longer exists and the "active" selection doesn't switch to the then renamed theme.

Does that make sense? I still don't know how to fix it. :stuck_out_tongue_closed_eyes:

**Comment by yafred** [comment]
In your code (the link quoted by @Frumph), the renaming is done during the upgrader_post_install filter.

It should be done in the upgrader_source_selection filter.

It was right in an earlier version of your code ...

**Comment by afragen** [comment]
@petersuhm are you seeing a similar problem with WP Pusher? If not, what hook are you using to rename the downloaded theme.

**Comment by afragen** [comment]
@yafred thanks. I've re-added a stripped down version of my `upgrader_source_selection` filter to only rename the current, active theme. https://github.com/afragen/github-updater/commit/e2423d76fa3d9c84b9d89850ab7c8d6a4659a871

This should fix #293 too.

Please let me know if this is now fixed everyone.

**Comment by petersuhm** [comment]
@afragen, I'm not sure I fully understand, but I don't think I've had this issue. Happy to help, though, if you're still having the issue!

**Comment by yafred** [comment]
@afragen you're welcome

Your fix should work. 
Here is how I understand the initial bug ...
WordPress core has 2 interesting hooks:
1. *upgrader_source_selection* after the name of the installation folder has been computed but before the installation is actually performed 
2. *upgrader_post_install* after installation is complete

It seems that WordPress core sets the current theme active between the 2 hooks, but you rename the folder afterwards and WordPress core gets lost.
In the case of a plugin or an inactive theme, it does not seem to matter ...

My gut feeling is that all the renaming work should be done in *upgrader_source_selection* hook.
Do you remember what made you decide to push the renaming from *upgrader_source_selection* to *upgrader_post_install* between version 4.6.2 and 5.0.0 of your plugin ?

**Comment by afragen** [comment]
It seems that I've solved this thanks to direction from @yafred 

@petersuhm I was curious to which hook you use to rename themes/plugins. What I've done with my fix is to only use `upgrader_source_selection` only when I'm updating the active theme.

@yafred I think you are correct in your assessment about when active theme renaming occurs. In every other instance (updating plugins or inactive themes) using `upgrader_post_install` works.

I decided to switch from `upgrader_source_selection` to `upgrader_post_install` to make the check for the slug simpler. There is cleaner information about the plugin or theme that's being updated passed in the second hook.

**Comment by petersuhm** [comment]
I use `upgrader_source_selection ` and don't recall having any issues...

**Comment by afragen** [comment]
@petersuhm I don't think you should have any issues using that hook.
