### ISSUE TITLE
Remote Management - MainWP

### ISSUE THREAD

**Issue by JosefJezek** [afragen/github-updater#299]
Please add support for MainWP to Remote Management.

https://wordpress.org/plugins/mainwp/

**Comment by afragen** [comment]
@JosefJezek I don't have MainWP installed? According to this forum issue hooking into WP update mechanisms should be all that's needed and that's what GitHub Updater does. https://mainwp.com/forum/showthread.php?9900-Custom-Plugin-Upgrade-Impossible

Other users have reported the MainWP does work #89 so I'm not sure if something changed or when.

Out of curiosity, have you checked either of the other Remote Management checkboxes to see if it works. If it does, that's a simple addition.

**Comment by GermaineMills** [comment]
i would love an update on this

**Comment by afragen** [comment]
Does it currently not work? If not, what steps have you gone through to see if it will work?

**Comment by GermaineMills** [comment]
i told mainwp to update it fails works manually

**Comment by afragen** [comment]
Can you be more specific about how it fails?

**Comment by GermaineMills** [comment]
it just says fail have you ever used mainwp?

**Comment by GermaineMills** [comment]
theres nothing in the log ill screencast the next try

**Comment by afragen** [comment]
I don't have or use MainWP. Without more information I can't really do anything.

Do you have anything checked in the Remote Management tab?

Can you share the URI of the plugin you're trying to update?

Does updating work outside of MainWP?

Is there any way for me to test with MainWP?

**Comment by GermaineMills** [comment]
Do you have anything checked in the Remote Management tab?
-- no, i guess you want me to test those?
Can you share the URI of the plugin you're trying to update?
-- https://github.com/AffiliateWP/AffiliateWP
Does updating work outside of MainWP?
-- yes
Is there any way for me to test with MainWP?
-- https://wordpress.org/plugins/mainwp/

**Comment by afragen** [comment]
AfflitiateWP does not use GitHub Updater for updates.

**Comment by GermaineMills** [comment]
doesn't the plugin enable github updates if i set the github url and branch? i thought that was the point of this plugin. Maybe i'm confused.

**Comment by afragen** [comment]
The plugin uses an opt-in philosophy. The developer must add the appropriate headers in the upstream file too.

You can try adding the plugin via https://github.com/afragen/github-updater-additions

**Comment by afragen** [comment]
I'm quite certain AffilitateWP has it's own updating mechanism.

**Comment by afragen** [comment]
Thanks to @ruben- MainWP support is now in the develop branch and will be functional with the next update to MainWP child plugin.
