### ISSUE TITLE
Update Cron / On-Off Switch

### ISSUE THREAD

**Issue by scarstens** [afragen/github-updater#303]
I use Github updater on local dev for manual branch updates and development. In this case I often don't want to insert my token for github, in fact, I don't really want it "auto checking" for updates at all. How hard would it be to build an on/off switch to turn off autoupdate checking? Maybe you could do manual update checks (refresh button next to version number as a UIX) for testing GHU too.

**Comment by afragen** [comment]
I'll look into this. Under what circumstances, with the switch on, should checking be done? If never, that's easier, but wouldn't you get the same effect by deactivating the plugin?

**Comment by scarstens** [comment]
Maybe it would check with the manual wordpress core update check function? We are already doing that anyways right?

No, its not quite the same. With the plugin active you can "install" plugins and themes using URL's in the interface and you can "rollback" and forward using the rollback function to move between versions. I think you can also use branch switching to move to dev branch... though I'm not sure GHU gives us a way to "manually pull a new update from the dev branch"... but that would be awesome for development as well.

**Comment by afragen** [comment]
The data for rollback and branch switch is gotten from those update checks. So bypassing them would stop these functions. It might be simpler to change the values of `parent::$hours` in `GitHub_API.php` as this determines how frequently the checks are made. Similar settings are in each API class.

**Comment by scarstens** [comment]
I guess going back to the original idea, allowing manual requests to be made, would solve that issue. We could allow changing of "hours" but something will have to clear the old crons every time that option is saved.i suppose on dev I could just set the hours to 1,000,000 and then it wouldn't update.

**Comment by afragen** [comment]
But we don't really add crons per se, we add transients. We just do the update on `wp_update_plugins` and `wp_update_themes` crons as an action hook. Otherwise update are done on after transient timeouts. A "manual" check can be done from the **Check Update** button on the update core page which clears all the transients.

Getting back to the original question, you don't have to add your GitHub Access Token, but depending upon how many plugins/themes you are checking you might bump into that API rate limit. We also don't go to GitHub but twice a day.

**Comment by scarstens** [comment]
I only have 2 github themes and 2 github plugins but somehow capped my API calls within the first hour of development. I was prepping for my Advanced WordPress Developer presentation, and it crapped out on API calls really fast.

**Comment by afragen** [comment]
Come on Seth just create and add a personal Access Token. @mlteal can show you. :wink:

**Comment by afragen** [comment]
Each repo has 5-6 API calls so refreshing often, as during testing, can do that. I used to hit it all the time.

**Comment by scarstens** [comment]
I have an access token, but I'm using this during a recorded presentation, I don't want my token on the dev site that published to the world... thats like putting your car keys on your car when you leave it parked at the airport.

**Comment by afragen** [comment]
You can make another token. :stuck_out_tongue_winking_eye:

**Comment by afragen** [comment]
Try changing the following line, https://github.com/afragen/github-updater/blob/develop/src/GitHub_Updater/Settings.php#L220 
To
`array( 'id' => 'github_access_token_password' )`

And let me know if that works.

**Comment by afragen** [comment]
Did this work for you Seth? It should have replaced the token with dots. Similar to how the Bitbucket password is displayed.

**Comment by scarstens** [comment]
When I click "save" on that page, nothing stays in the access token field, so I'm assuming that doesn't work, that or its saving and its just not smart enough to pull in the old token from the DB or at least pretend that it knows I have a token in the DB. Lastly, obfuscation is hardly security... but it would certainly solve the issue of my presentation being recorded.

**Comment by afragen** [comment]
Sorry Seth, I was shooting from the hip on that one. I was hoping it would be a quick fix for your presentation. It might be simpler to just create a temp personal access token and delete it after.

**Comment by scarstens** [comment]
I appreciate the attempt, lets go back to the original request, which is the ability to turn off update checking, with the possibility of manual checking.
