### ISSUE TITLE
Access Tokens

### ISSUE THREAD

**Issue by Frumph** [afragen/github-updater#304]
Bear with me, kinda new to this access tokens thing.

Each user of the plugin gets their own account and creates their own token, or using my token will work?

I can't add the token to the code cause github says "no, not allowed son. /twap" .. Whats the proper methodology?  I'm guessing they create accounts and get their own token but I want to make sure-sure, know what I mean?

**Comment by afragen** [comment]
Each user would create their own GitHub Account and personal access token. There is a link in the README.

If you're distributing a plugin or theme from a private repo, you can use the hooks to include an access token. Please refer to the README.

**Comment by afragen** [comment]
There are 2 reasons to have tokens.

1. so you can check public repos and not bump into the API rate limit.
2. To get data from private repos.

Having each user create their on account and create a personal access token works for 1.
Using the developer hooks to add an access token for a private repos works for 2.
