### ISSUE TITLE
Conflicts with wp-notification-center

### ISSUE THREAD

**Issue by 2nickpick** [afragen/github-updater#306]
It seems you have a conflict with wp-notification-center over conflicting versions of wp-update-php. 

It's difficult for me to tell which of your versions is more recent. 

On installation of github-updater with wp-notification-center already installed I get the error : `set_plugin_name is undefined`. 

I've notified `wp-notification-center` and `wp-update-php` as well in hopes that this problem doesn't cause similar problems in the future.

**Comment by afragen** [comment]
I'm using the 'release-1-1-0' branch which is a more advanced version of the plugin. Obviously 'wp-notification-center' uses the master branch.

**Comment by 2nickpick** [comment]
Thanks, @afragen. It's clear now that `github-updater` requires no action.

**Comment by afragen** [comment]
However, I have just pushed a commit to `develop` to avoid the error.

**Comment by 2nickpick** [comment]
Fantastic! :+1:

**Comment by afragen** [comment]
Please let me know if this fixes the conflict you see,

**Comment by 2nickpick** [comment]
Received the following warning: `The plugin generated 2302 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.`.

**Comment by 2nickpick** [comment]
The unexpected output was: 
`Warning: Missing argument 1 for WPUpdatePhp::does_it_meet_required_php_version(), called in github-updater.php on line 44 and defined in \wp-notification-center\vendor\wpupdatephp\wp-update-php\src\WPUpdatePhp.php on line 19`

**Comment by 2nickpick** [comment]
I don't think `github-updater` really needs to anticipate handling all the differences between the branches of `wp-update-php` .

**Comment by afragen** [comment]
I think you're right. Sorry, you might be better off convincing the other plugin author to update branches or get wp-update-php to update the master branch.

**Comment by afragen** [comment]
I'll do a better job fixing this.

**Comment by afragen** [comment]
@2nickpick try the latest `develop` version and let me know if there are any errors. I installed `wp-notification-center` and don't see any locally.
