### ISSUE TITLE
Force an update

### ISSUE THREAD

**Issue by 2nickpick** [afragen/github-updater#308]
Is there any way we could force an update without checking if the remote is a higher version?

For example, if a theme/plugin has been corrupted, pull a new copy with the same version number and overwrite .

I'll consider building it, either as part of github-updater or an "add-on" plugin.

**Comment by afragen** [comment]
From the Settings, enable branch switching.

Select the current branch of the plugin or theme and it should reinstall from the source. You will likely have to reactivate after reinstalling.
