### ISSUE TITLE
Enterprise issues

### ISSUE THREAD

**Issue by flashadvocate** [afragen/github-updater#309]
Any particular reason why this would throw a 403 error (all other things being correct) for github enterprise -> github.ncsu.edu

Necessary header information is included in the plugin, which installs fine through the updater, but refuses to update afterward

```php
/**
 * GitHub Plugin URI: https://github.ncsu.edu/oitdesign/test_updater
 * GitHub Enterprise: https://github.ncsu.edu
 */
```

**Comment by afragen** [comment]
Have you set a personal access token for your GitHub installation?

**Comment by flashadvocate** [comment]
Yes

**Comment by afragen** [comment]
Can you install the Query Monitor plugin? It should be able to show exactly what the HTTP request error is. That would be help.

**Comment by flashadvocate** [comment]
Thanks, that helps out quite a bit. Apparently it's not able to authenticate, even though I'm including an access token that should have all the necessary permissions

**Comment by afragen** [comment]
@flashadvocate it would be much more helpful for me to se the entire URI as it exists in the first column in Query Monitor. Obfuscating the token is fine but seeing the rest of the URI is important. You can email screenshot to me if you don't want it posted.

**Comment by afragen** [comment]
I think this problem is somewhere in the following commit, https://github.com/afragen/github-updater/commit/d4aaa79a1eb4e564668f1f5ae6ff92eaa71d3faf

The above commit solved a similar issue with GitLab CE.
I'll be dig into this and have a solution soon.

**Comment by afragen** [comment]
Chris and I were able to figure this out offline. I really appreciate the Chris' help as I don't run GitHub Enterprise so I'm not really able to test. The bottom line is that I had a slightly malformed endpoint, which is now fixed and working.

Thanks Chris.
