### ISSUE TITLE
avoid deleting of theme-generated file (custom css)

### ISSUE THREAD

**Issue by commwork** [afragen/github-updater#310]
this is more of a question. my theme has an options field (it is a custom field) that generates a CSS file ("custom.css") so the customer can make visual changes on the theme from within the wordpress backend. i git ingored this file because i do not want to overwrite the customers "custom.css" with the one from my developer machine for sure. 

the problem is now: everytime the customer gets an update per wordpress updater this file will be deleted (while it's on the git ignore list it is not beeing transmitted from my local machine to github), so the wordpress updater deletes this file everytime he installs the theme update. any idea how i can avoid this? or is this more a github question (sorry i am very new to github ...).

**Comment by Frumph** [comment]
..i have one as well and I have it update and created in the /wp-content/uploads/custom-css  area to keep things exactly like this from occurring.

**Comment by commwork** [comment]
sounds genius :) any idea how to get this working?

    function generate_options_css() {
    	$upload_dir = wp_upload_dir();
	    $ss_dir = get_stylesheet_directory();
	    ob_start(); // Capture all output into buffer
	    require($ss_dir . '/custom-styles.php'); // Grab the custom-style.php file
	    $css = ob_get_clean(); // Store output in a variable, then flush the buffer
	    file_put_contents($upload_dir . '/custom-styles.css', $css, LOCK_EX); // Save it as a css file
	}
	    add_action( 'acf/save_post', 'generate_options_css' ); //Parse the output and write the CSS file on post save

**Comment by Frumph** [comment]
```
function generate_options_css() {
    $wp_uploads = $wp_upload_dir();
    $custom_css_path = $wp_uploads['basedir'].'/css';
    $ss_dir = get_stylesheet_directory();
    ob_start(); // Capture all output into buffer
    require($upload_dir.'/custom-styles.php'); // Grab the custom-style.php file
    $css = ob_get_clean(); // Store output in a variable, then flush the buffer
    file_put_contents($upload_dir . '/custom-styles.css', $css, LOCK_EX); // Save it as a css file
}
add_action( 'acf/save_post', 'generate_options_css' );
```

Then, for the part where it links it in, it's

```
$wp_uploads = $wp_upload_dir();
$custom_css_url = $wp_uploads['baseurl'].'/css/custom-styles.css'
```

can also use:
```
if (!file_exists('$custom_css_path.'\custom-styles.css'))  {}
```
to verify the file exists before even doing the link in the header/wp_head can even:

```
if (!file_exists('$custom_css_path.'\custom-styles.css')) wp_mkdir_p(dirname($custom_css_path));
```
And it will create the directory if it doesn't exist when you write the file

Reference:  https://github.com/Frumph/theme-companion/blob/master/companion_core.php#L113

**Comment by commwork** [comment]
Hello, when i use the first part i get an error message:
"Fatal error: Function name must be a string in C:\xampp\htdocs\ ... \functions.php on line 997"

shouldn't it be
`$wp_uploads = wp_upload_dir();`
without the dollar? but when i do this i get nothing (but no error).

**Comment by commwork** [comment]
Okay this works:

getting the file:
```
function enqueue_css() {
    $upload_dir = wp_upload_dir();
    wp_enqueue_style('custom_style', $upload_dir['baseurl'] . '/custom-styles.css', 'style');
}
```
And the function for adding the file to the uploads folder:

```
function generate_options_css() {
    $wp_uploads = wp_upload_dir();
    $custom_css_path = $wp_uploads['basedir'].'/';
    $ss_dir = get_stylesheet_directory();
    ob_start(); // Capture all output into buffer
    require($ss_dir.'/custom-styles.php'); // Grab the custom-style.php file
    $css = ob_get_clean(); // Store output in a variable, then flush the buffer
    file_put_contents($custom_css_path . '/custom-styles.css', $css, LOCK_EX); // Save it as a css file
}
add_action( 'acf/save_post', 'generate_options_css' );
```
... next step is to establish a "Frumph" fanclub :) - THX a lot, mmd!

**Comment by Frumph** [comment]
^ your require($ss_dir) is getting the file from the stylesheet directory still btw // in code example

and if you have a / at the end of $wp_uploads['basedir'].'/';   then you add /custom-styles.css it'll have double slashes in the string you can use trailingshlashit() (sp?)  to make sure the first has a slash always then don't need to add the extra /

**Comment by commwork** [comment]
"^ your require($ss_dir) is getting the file from the stylesheet directory still btw // in code example"

yes, the "custom-styles.php" is (and has to be) in the theme folder and the generated "custom-styles.css" will be created in the "upload" folder, this works as it should (?).

**Comment by afragen** [comment]
I'm really excited when 2 users are able to help each other, thanks to both of you.

Another thought regarding the saving of a generated CSS file. You could save it to a transient set for say 30 days or actually save it to an option. This way you might avoid the file writing and loading issues.

For the curious, I do something like this here. https://github.com/afragen/the-events-calendar-category-colors/blob/develop/src/Category_Colors/Frontend.php

**Comment by fahimku** [comment]
i want to save Customizing Additional CSS into upload folder dynamically.
And render the custom CSS from the file. (that was just generated dynamically in 1st step above.)
 Remove it from the HTML head section. Otherwise, the custom CSS will be rendered twice.

anyone help me to functions.php code?

**Comment by afragen** [comment]
This particular issue was closed 3 years ago. You’re not likely to get an answer. 

Additionally you’re question doesn’t seem to be related to this plugin. If it does, please create a new issue. If it doesn’t I would suggest using the WordPress.org forums.
