### ISSUE TITLE
Not reciving updates

### ISSUE THREAD

**Issue by indie-rok** [afragen/github-updater#312]
hi, thanks for this plugin.

How ever I can't make it work on my theme.

This is an existing theme wich I am adding the git and the auto update feature.

This are the steps that I am doing:

1) Download via FTP the theme to my computer.
2) create repository in github and git init in my computer.
3) edit styles.css to add the header with the github URL
3) push changes
4) Install theme via Settings/GitHub update/Install theme

Until this point, theme is installed correctly.

but then:

6)Change the theme version of styles.css
7) Do a random change in theme
8) Push again the changes.

But then I go to Apparence/Themes, hoping to see that notificacion of theme updates, but I can see it.

Am i doing something wrong?

This are the commits of my theme (including the theme version change)

https://github.com/indie-rok/yo/commits/master

Thanks

**Comment by flashadvocate** [comment]
Are you running "check again" to force WP to check for updates?

**Comment by afragen** [comment]
@indie-rok are able to receive updates yet?

**Comment by indie-rok** [comment]
@flashadvocate  @afragen  Thanks guys. The "Check again" solved the problem. Maybe adding it to the Readme to avoid this threads? Thanks!

**Comment by afragen** [comment]
It is in the README under "Deleting Transients"
