### ISSUE TITLE
After GHU deactivation available plugin update is still visible

### ISSUE THREAD

**Issue by szepeviktor** [afragen/github-updater#313]
I could still see a GitHub plugin's update availability after GHU deactivation.
Please clean up the updater transient on deactivation.

**Comment by scarstens** [comment]
I wouldn't delete days on disable, that's a bad practice.

**Comment by afragen** [comment]
Per standard practice, the saved options are removed upon uninstall. Transients will automatically deprecate over a short period of time. I'm not aware of clearing transients on a deactivation. 

Especially as the branch switcher deactivates the plugin. `is_plugin_active` is inaccurately false during this action.
