### ISSUE TITLE
Theme Branch Switching?

### ISSUE THREAD

**Issue by flashadvocate** [afragen/github-updater#315]
Noticed that it is possible to determine which branch to pull from, allowing us to determine on an installation basis which branch we want to check. I was in the process of setting up a staging environment to take advantage of this, but then I realized it's only for plugins.

Any plans to expand this ability to allow themes to do the same? :+1:

**Comment by afragen** [comment]
This should work for themes too.

**Comment by flashadvocate** [comment]
Strange, I'm not seeing a way to do this when I'm looking at the themes page (with branch switching enabled).

**Comment by afragen** [comment]
Screenshot?

**Comment by afragen** [comment]
Here's what I see in a single site install.
![modified](https://cloud.githubusercontent.com/assets/1296790/10529967/7a61d6f0-7357-11e5-825c-a56308989a54.png)

Here's what I see in multisite.
![screenshot_02](https://cloud.githubusercontent.com/assets/1296790/10529973/8a1b4040-7357-11e5-8539-000a9d69d32b.png)

If you see something different, can you point to the theme's URI?

**Comment by afragen** [comment]
@flashadvocate are you still having a problem?

**Comment by flashadvocate** [comment]
Nope. Consider this resolved. :)

**Comment by afragen** [comment]
Great!
