### ISSUE TITLE
Access Token Twice?

### ISSUE THREAD

**Issue by andrewatduckpin** [afragen/github-updater#316]
I used the "Install Theme" feature to do an initial install of a theme. I entered a "Theme URI" and a "GitHub Access Token". 

After that install, if I go back to settings, the Token is automatically shown under "GitHub Private Settings".

Do I also need to add the token to the "Personal GitHub Access Token" section or am I fine (not going to get hit with the 60 API limit) by just leaving the token in the private settings, next to the newly installed theme?

**Comment by afragen** [comment]
If the token is a personal access token and not a repo specific token, you should copy it to the appropriate area. If theme is a private repo and the token is specific to that repo you can leave it in place. 

You shouldn't ever need the same token in both places.
