### ISSUE TITLE
Not seeing updates

### ISSUE THREAD

**Issue by PthPndr** [afragen/github-updater#318]
I am seeing unusual behavior starting with version 5.0 of the plugin, I no longer see plugins that requires updates. However, version 4.6.2 appears to work correctly.

With 4.6.2 the console reports the correct number of updates and the remote management console reports the correct number of updates needed.

With 5.0 and above, I only see the updates after doing a "force check" of the updates. The problem is that after a few minutes those updates disappear and you won't see them until you do a force update again.

Just wondering if you had any thoughts?

Thanks

**Comment by afragen** [comment]
Do you have any caching plugins installed?

**Comment by PthPndr** [comment]
No, I sure don't.

And just to be safe I setup a server from scratch and only installed a handful of plugins, It's also exhibiting the same behavior.

**Comment by afragen** [comment]
Can you share the specs of your server and WP install?

**Comment by PthPndr** [comment]
Is there anything in particular you are looking for? 
Both instances are single-site and hosted at A2Hosting.

WP Version: 4.3.1
WP Memory Limit: 256MB
PHP Version: 5.5.30

**Comment by afragen** [comment]
I'm looking for whether or not your host is caching for you. I've seen something similar with W3-Total cache and turning off the object cache solved it. Something in there caching deleted the transient cache at most page loads.

**Comment by PthPndr** [comment]
I did double-check. We have no caching from the hosting provider and I don't have any caching plugins installed.

**Comment by afragen** [comment]
Can you check on a localhost installation?

**Comment by PthPndr** [comment]
It appears to work correctly on a localhost install. The only difference between the two is the ManageWP plugin. We just started testing a remote management tool.

From what it looks like, github-updater version 4.6.2 works everywhere. For version 5.0 and above it appears to work with ManageWP plugin 4.1.10. If I update the ManageWP plugin to the latest (4.1.17) that's where the problem starts. 

If I force a refresh on the ManageWP console all github-updater plugins that need an update disappear.

**Comment by afragen** [comment]
Odd, thanks for narrowing it down. I'll see if I can figure out where the issue with the 2 plugins is, but I haven't been able to use ManageWP for a while. Never was able to figure it out but never seemed to have an issue with GHU.

**Comment by afragen** [comment]
Unfortunately I've never really been able to get ManageWP to work with GHU. I would recommend iThemes Sync or InfiniteWP.

**Comment by PthPndr** [comment]
OK, thanks.
