### ISSUE TITLE
Symlink for MU Plugin

### ISSUE THREAD

**Issue by jonny2k9** [afragen/github-updater#319]
Hi,

I have been trying to setup the github plugin as an MU plugin on Ubuntu (hosted by AWS).

At first I tried to follow the method you supplied in your docs (readme.md) but that didn't work.

So, I specified the full path to both the file and the symlink:

ln -sv /var/www/website/wp-content/plugins/github-updater/mu/ghu-loader.php /var/www/website/wp-content/mu-plugins/ghu-loader.php

This approach worked for me. 

Thanks for creating this plugin. I know the pain of just trying to integrate with one hosted repo (bitbucket), but not three!

**Comment by afragen** [comment]
Thanks. I'll update the readme to specifically require full paths.
