### ISSUE TITLE
Automatic background updates not supported

### ISSUE THREAD

**Issue by jancbeck** [afragen/github-updater#320]
I would like to improve my workflow so that whenever I push a change to my Git repository, this will trigger an update of the plugin or theme without user interaction at all. After I got the manual updates working, my idea was that I could use the [automatic background updater](https://codex.wordpress.org/Configuring_Automatic_Background_Updates) that WP provides since 3.7. 

However, I tried this briefly without success. I'm wondering if this is actually supported by GitHub Updater?

**Comment by afragen** [comment]
It may be that automatic plugin updates are only supported for plugins on the dot org repo. I'm not sure how to confirm this.

**Comment by afragen** [comment]
This from the Codex.

> By default, automatic background updates only happen for plugins and themes in special cases, as determined by the WordPress.org API response, which is controlled by the WordPress security team for patching critical vulnerabilities. To enable or disable updates in all cases, you can leverage the auto_update_$type filter, where $type would be replaced with "plugin" or "theme".

This implies only w.org hosted plugin are eligible for automatic updates.

**Comment by jancbeck** [comment]
Correct, however, non-.org plugins can still support automatic updates by filtering 'pre_set_site_transient_update_plugins'. This is how for example ACF and EDD are doing it:
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/f2f1f7db7322f5abe2d5900be0c40895978aed21/includes/EDD_SL_Plugin_Updater.php#L58

What's confusing to me is that github-updater already has the same approach here:
https://github.com/afragen/github-updater/blob/develop/src/GitHub_Updater/Plugin.php#L278

However, this filter is only enabled when the ´wp_update_plugins´ action runs, which itself is a confusing hook, because it isn't called anywhere in WordPress via `do_action`. At least when I tried to test background updates, `wp_update_plugins` wouldn't run, so I was stuck with this problem.

Eventually what I did was this:

```
add_action( 'update_option_auto_updater.lock', function( ){
	\Fragen\GitHub_Updater\Base::forced_meta_update_plugins();
});
```

This manually calls the necessary functions whenever the auto updater lock is written. Perhaps it is helpful for anyone who had the same problem and reads this.

**Comment by afragen** [comment]
Is this written differently for themes?

How about a PR?

**Comment by afragen** [comment]
https://github.com/afragen/github-updater/commit/283695b478c248350b7e73a94343eee6fb8d3af5
https://github.com/afragen/github-updater/commit/40d9c72d405a8f71a779c3a2922df72c7b764b95

**Comment by nicomollet** [comment]
@jancbeck @BjornW do automatic background updates still work for you?

**Comment by BjornW** [comment]
It work for our own plugins last time I checked.
