### ISSUE TITLE
Plugin not remembering check box

### ISSUE THREAD

**Issue by kpry** [afragen/github-updater#324]
I have used GitHub Updater successfully before, but on new WordPress install, the Bitbucket private repo checkbox (on settings page) will not stay checked on save.

Procedure:
'Check box if private repository. Leave unchecked for public repositories.'   =   Checked
Click save.
The check box is unchecked on page reload.

Error 401 being show.

<img width="540" alt="screen shot 2015-10-26 at 14 10 23" src="https://cloud.githubusercontent.com/assets/4054334/10741068/62104590-7beb-11e5-8830-79b6e25dfd05.png">

**Comment by kpry** [comment]
More information:

I am experiencing these symptoms on 5.2.0.2, however, when I downgrade to Github Updater 5.1.2.3, everything seems fine again, although I do have to re-connect to Bitbucket.  

Another note: On 5.2.0.2, my theme update does not show on WordPress updates screen.  When using 5.1.2.3, the updates shows.  Seems like a Bitbucket auth issue.

**Comment by afragen** [comment]
I've made some changes to the Settings saving. Please update to 5.2.0.3 and let me know if the problem persists. 

Thanks.

**Comment by kpry** [comment]
Updating has fixed this issue.  Check box now saves  state.

**Comment by kpry** [comment]
This issue is happening again. running 5.2.0.4.

The check box will not save in a checked state.

**Comment by afragen** [comment]
I am unable to duplicate this error and that makes it real difficult to try and fix.

Can you use the branch switch feature to reinstall the plugin. You will need to reactivate it afterwards.

**Comment by afragen** [comment]
Can you turn on WP_DEBUG and see if there are any errors?

**Comment by afragen** [comment]
We were able to figure this out. Bottom line is that it's best to only use dashes or underscores in repo names. In this case a name with 2 periods was changed in sanitization to from `xxx.xx.xx` to `xxx.xx_.xx` and that caused the settings to be removed.
