### ISSUE TITLE
Installing a theme "missing style.css"

### ISSUE THREAD

**Issue by flashadvocate** [afragen/github-updater#325]
On 0fb1e542eaee5345bdd503849b8ceb19f2a626c0, when attempting to install a fresh theme via updater, the following occurs (erroneously) 

![screenshot_1](https://cloud.githubusercontent.com/assets/7848492/11538773/66b42cd8-98f1-11e5-83bd-0251143439fe.png)

**Comment by allurco** [comment]
Same thing here!

**Comment by afragen** [comment]
Sorry, I too see this error. I'll have it fixed soon. Sorry for the inconvenience.

**Comment by flashadvocate** [comment]
No worries sir. :)

**Comment by afragen** [comment]
I think it's now fixed https://github.com/afragen/github-updater/commit/9fbd958b4003706ade0154fe3dfb5267675928fd

I forgot to add a trailing slash when I switched back to using the `upgrader_source_selection` filter.

Please let me know if this is now working. Thanks and sorry.

**Comment by flashadvocate** [comment]
@afragen seems to be working now. Thanks for the quick fix :)

**Comment by afragen** [comment]
:smiley:

**Comment by chestozo** [comment]
:+1: thank you )
