### ISSUE TITLE
Theme install from bitbucket private repository fails

### ISSUE THREAD

**Issue by chestozo** [afragen/github-updater#327]
With a message:

    The package could not be installed. The theme is missing the style.css stylesheet.

But it is not true - `style.css` is present.

**Comment by chestozo** [comment]
The same archive downloaded manually and manually uploaded to WP is installed successfully.

**Comment by chestozo** [comment]
It looks like inside downloaded archive (from bitbucket) files are inside a directory (in my case `chestozo-mtv-theme-test-93da8a62d787`) and this is probably the cause of not finding `style.css`. So bitbucket is bad? )

**Comment by chestozo** [comment]
Maybe the problem is that download url is `https://bitbucket.org/chestozo/mtv-theme-test/get/master.zip` but what you get is an archive named `chestozo-mtv-theme-test-93da8a62d787.zip`.

**Comment by flashadvocate** [comment]
Dup of https://github.com/afragen/github-updater/issues/325

**Comment by chestozo** [comment]
Thank you )
