### ISSUE TITLE
Update to 5.3.1 breaks plugin

### ISSUE THREAD

**Issue by glueckpress** [afragen/github-updater#328]
When updating to 5.3.1 from the WordPress back-end, the update breaks the plugin:

> The plugin `afragen-github-updater/github-updater.php` has been deactivated due to an error: Plugin file does not exist.

That’s because after the update that path looks like this: `afragen-github-updater-469ce78/github-updater.php`.

**Comment by afragen** [comment]
Simply reactivate the plugin. What version were you updating from and how did you perform the update?

**Comment by glueckpress** [comment]
I was updating from 5.3.0 and I updated on 2 sites, one via Dashboard->Updates, and the other one via Plugins page.

**Comment by afragen** [comment]
Strange as I update the GHU plugin to my test server and it didn't have any issues.

From your description it seems the renaming didn't happen.

**Comment by glueckpress** [comment]
I had the very same issue locally, and on a shared web hosting. If I’m the only one, never mind. :)

**Comment by afragen** [comment]
If it persists re-open this issue and please let me know. I really don't want this to be an issue for anyone.
