### ISSUE TITLE
[WISHLIST] Force branch switch regardless of version

### ISSUE THREAD

**Issue by flashadvocate** [afragen/github-updater#334]
It would be nice to be able to pull the latest state of a repo via branch switching > "try another branch" regardless of whether or not the local version equals the remote version. I find myself filling up my commit history with "bump version", and being able to pull an update this way would eliminate the need for constantly version increments that break [semantic versioning rules](http://semver.org/)

**Comment by afragen** [comment]
That's how this works. If you use the branch switching to switch to the same branch it will reload that branch. Occasionally it will say the plugin is up to date, but trying the branch switch again usually works.

**Comment by afragen** [comment]
I break semantic versioning with development branches by using a fourth position.
major.minor.patch.development

**Comment by flashadvocate** [comment]
Oh, in that case disregard. I was making the assumption that it pulled regardless, but I did run into that "same version" error. If that's an exception rather than the rule, then great :)
