### ISSUE TITLE
Don't update symlinked directories

### ISSUE THREAD

**Issue by afragen** [afragen/github-updater#335]
Does anyone else use symlinked directories for plugin or themes? I use them in my local development environment and it's irritating if I accidentally overwrite my local git repo because I've inadvertently hit the update.

This usually happens when I'm testing a local version of another repo I'm contributing to and they've pushed an update.

I've created a branch to stop this from happening by replacing the download link with some warning text.

My questions:

1. Would anyone else find this useful?
2. Does anyone use symlinked plugins or themes outside of a development environment?

**Comment by scarstens** [comment]
negetive, symlinking plugin into wordpress doesn't always produce the the results as having the actual files in wordpress so I've avoided doing this

**Comment by afragen** [comment]
My problem was I would occasionally update the symlinked directory thereby deleting the file files. I was trying to think of a way to  not have that happen. I think I'll just creat an add-on plugin that passes an array of slugs to GHU so I can display an update message so hopefully I won't do that.

**Comment by bobbingwide** [comment]
+1 - same requirement https://github.com/bobbingwide/oik/issues/11

**Comment by afragen** [comment]
What I've created in an add on plugin is something to warn me that the plugin/theme is symlinked. It does not prevent updating.

**Comment by afragen** [comment]
BTW, symlinked plugins/themes work just fine in a local environment.

**Comment by afragen** [comment]
I've pulled out the filters I added to this plugin just created another plugin.

https://github.com/afragen/local-development-upgrade-warning
