### ISSUE TITLE
Travis-CI and Unit Tests

### ISSUE THREAD

**Issue by afragen** [afragen/github-updater#339]
Well, I think I've gotten Travis-CI working and now all I need are some unit tests to make this work.

This is a great opportunity to contribute. Thanks!

**Comment by szepeviktor** [comment]
Please add the Travis badge.

[![Build Status](https://travis-ci.org/afragen/github-updater.svg?branch=develop)](https://travis-ci.org/afragen/github-updater)

**Comment by afragen** [comment]
https://github.com/afragen/github-updater/commit/b9cde96c3ff320871122ddbe5adef8a7b9057872

**Comment by afragen** [comment]
Switching over to GitHub Actions for the CI.
