### ISSUE TITLE
 Can't switch theme version to another branch. 

### ISSUE THREAD

**Issue by joeyred** [afragen/github-updater#340]
I saw a closed issue with this problem, but I think mine may be happening a bit differently.

When I go to change the version/branch the theme is using, I'm able to click `try another version`, get the dropdown, make my selection, and hit install. After this is done I'm taken to a page that says "The theme is at the latest version." However, when I check for the differences from the master branch and the new branch I selected, they aren't there. The theme still remains on its original branch. 

I've tried using "check again" but it doesnt work.

**Comment by joeyred** [comment]
The only way I was able to accomplish this was to delete the theme and install it with GitHub Updater with the branch I wanted selected.

**Comment by afragen** [comment]
The core update code wasn't designed with reinstalling over a current version in mind. Occasionally this message appears. Just try again. I've seen it take 2-3 times before.

**Comment by joeyred** [comment]
Maybe it has to do with how I installed everything in the first place?

First of all this is on a local installation. I used a bash script filled with WP-CLI commands to install all the plugins and themes I needed for it. This includes plugins that have the GitHub Updater declaration in the appropriate location. 

My assumption was that as long as the plugins and theme had the correct declaration, then it would be fine. So I didn't actually install anything through GitHub Updater the first time around. 

I did, though, make sure that GitHub Updater was the first thing installed, and it's options were updated with the correct bitbucket info for use of private repositories.

I have no idea if that kind of an installation process affects how GitHub Updater works or not, but I figured I should at least mention it, just in case.

**Comment by afragen** [comment]
How you installed the plugins/themes initially may or may not have an issue during updates and keeping the plugins or themes active. This is because installing from GitHub or Bitbucket will not name the directory correctly where installing them via GHU will rename them correctly.

I still think the issue is likely just an intermittent problem I've encountered that I'm not sure has any real solution. Just have to keep trying and it will eventually work.

**Comment by joeyred** [comment]
Okay, that makes sense.
 
Thanks for the explanation!
