### ISSUE TITLE
Connect GItLab

### ISSUE THREAD

**Issue by Zagur** [afragen/github-updater#341]
How can connect plugin with Gitlab? I can install theme, but not can't update.

Thanks,
Zagur.

**Comment by flashadvocate** [comment]
Are you adding the necessary headers to the stylesheet?

https://github.com/afragen/github-updater#gitlab-ceenterprise-support

**Comment by Zagur** [comment]
In my stylesheet I added:

GitLab Enterprise: https://gitlab.com
GitLab Branch: master

This is correct? Or I have to add:

GitLab Enterprise: https://gitlab.com/zagur/AlpheratzTheme
GitLab Branch: master

Thanks,
Zagur.

**Comment by flashadvocate** [comment]
Sorry, I thought you were using a self hosted gitlab instance. Since you're using gitlab.com, see https://github.com/afragen/github-updater#themes

You should have the following in your stylesheet
```GitLab Theme URI: https://gitlab.com/zagur/AlpheratzTheme```

**Comment by Zagur** [comment]
Nice! Works.

Thank you for your attention to this matter.
Zagur,

**Comment by afragen** [comment]
@Zagur it looks like your headers are set correctly now. Is it working for you?

Thanks @flashadvocate :smiley:

**Comment by Zagur** [comment]
@afragen Yes, I leave my header example:

GitLab Theme URI: https://gitlab.com/zagur/AlpheratzTheme
GitLab Branch: master

More: https://gitlab.com/zagur/AlpheratzTheme/blob/master/style.css

Thanks.
