### ISSUE TITLE
Auto / Manual Update; perhaps using webhooks?

### ISSUE THREAD

**Issue by sujaypawar** [afragen/github-updater#342]
GREAT WORK!

Would it be possible to auto (or manually) update plugins & theme for every push, perhaps using webhooks?

**Comment by afragen** [comment]
While it's possible to use webhooks it's not the method employed in this plugin. @petersuhm's WP_Pusher uses this method. While it might be a more efficient method and require less to no user involvement in updating, I opted to more closely mirror the method used in core or plugins/themes in the repo.

That being said, I'm not opposed to another option, say update on every commit which would certainly be better accomplished via webhooks. Any PRs for this would certainly be considered.

**Comment by limikael** [comment]
This should solve it I believe: https://github.com/afragen/github-updater/pull/366 :)

**Comment by afragen** [comment]
@sujaypawar I can confirm that after finishing up @limikael's PR it is possible to update specific repos from a webhook. You will find a RESTful endpoint in the Remote Management tab. In combination with the appropriate attributes should do the trick. Take a look at the README for more information.

**Comment by limikael** [comment]
I'm also planning to write a separate tutorial/article on how to do exactly this using the RESTful endpoint. If I get around to it I will post the link here as well...
