### ISSUE TITLE
Branch switching for disabled themes / plugins

### ISSUE THREAD

**Issue by flashadvocate** [afragen/github-updater#344]
Is it intended behavior or am I the only one experiencing this "problem"? I'd like to be able to update themes and plugins via branch switching regardless of their active / inactive status

**Comment by afragen** [comment]
You should be able to us branch switching on disabled plugins/themes. Every once in a while you will get a message stating the plugin/theme is up to date. Just keep trying. Eventually it will reinstall. 

It's an odd bug I have to see if there's any way around. Odd in that it didn't happen all the time.

**Comment by flashadvocate** [comment]
Well, my problem is that I don't even see the context for the branch switch. On an enabled theme, I do see "Choose another version", but under a disabled theme, no such options appear. I'll try to get a screenshot if/when I run into it again.

Hopefully it's just me :)

**Comment by flashadvocate** [comment]
Yep, it was just me.

**Comment by afragen** [comment]
:smile:

**Comment by afragen** [comment]
Thanks for showing me that I need to fix the logic here. It seems in a single install for themes branches are always displayed and if there are no tags I need to put in something stay so.

**Comment by flashadvocate** [comment]
Glad to help. It's somewhat annoying that it's not reliable. IE I have gone through "at latest version" sometimes 6 or 7 times before I get it to pull.

**Comment by flashadvocate** [comment]
Actually, let me reiterate. It's extremely frustrating. If I want to pull a branch, it should completely ignore the version and just pull the branch.

**Comment by afragen** [comment]
I'll have to figure out a way to "trick" the system so maybe this won't happen.

**Comment by flashadvocate** [comment]
You're the man Andy!

**Comment by afragen** [comment]
@flashadvocate PRs ar a great way to "donate". There is a donate link listed in the README for the other way. :smile:

**Comment by afragen** [comment]
I think I may have the 'at latest version' problem fixed. Update to latest develop branch to see if this is fixed and let me know.

**Comment by afragen** [comment]
> Thanks for showing me that I need to fix the logic here. It seems in a single install for themes branches are always displayed and if there are no tags I need to put in something stay so.

https://github.com/afragen/github-updater/commit/b4b60f7f39d0345ce720ed428b5246de5c6d7319
