### ISSUE TITLE
Branch Switching for private repo on Bitbucket

### ISSUE THREAD

**Issue by benoitchantre** [afragen/github-updater#345]
I have installed plugin from a private repository on Bitbucket. This was done with the Install Plugin tab.
The repository has 2 branches: master and develop.

When I enable Branch Switching option, the link to try another branch doesn't show anything.
When I click on the same link under the GitHub Updater Plugin, it shows develop and master branches.

Does this function work with private repos hosted on Bitbucket?

**Comment by afragen** [comment]
Can you go to the core update page and click the Check Again button. It might be that GHU simply hasn't downloaded the data for that plugin yet.

**Comment by benoitchantre** [comment]
I have now tested that again and pressed as before the Check Again button, but the branches are not showing.

Now, I have removed the plugin and I have reinstalled it. I have chosen to install the develop branch.
The download path is correct, but when I look at the plugin in the plugins list, the info says the current branch is master.

**Comment by flashadvocate** [comment]
I can confirm the misnamed branch issue as well. I thought it might have been coming from the branch specification header in the plugin file but removing it seemed to have no bearing

**Comment by afragen** [comment]
I don't see a misnamed branch. Can someone give `afragen` `read` privileges to plugin that this occurs with?

**Comment by benoitchantre** [comment]
@afragen You have now `read`privilege to a private repo named Team Post Type

**Comment by afragen** [comment]
Thanks, I'll test when I can and let you know what I find.

**Comment by afragen** [comment]
Thanks for the read access. What I found was an inconsistency in how Bitbucket returned an API response for getting branch information. I was able to adjust the code to work more consistently. https://github.com/afragen/github-updater/commit/3245a931764a67b0178208bdf109a821ac2207bb

You can remove me from the repo.

Please confirm that this is now working. You may have to reset the transients after updating to the latest develop branch to see the changes.

Also, as you don't specify a `Bitbucket Branch: master` and `Bitbucket Branch: develop` in the respective branches the display on the plugins page will always say `master` as that is the default if no header is specified.

**Comment by benoitchantre** [comment]
Thanks. I have added `Bitbucket Branch; master` and `Bitbucket Branch: develop` to the respective branches and now (after having updated GiHub Updater) the name of the branch is correct.

However, when I click on the link "another branch" it doesn't display anything.
All transients have been cleaned with the Transient Cleaner plugin.

Is it not possible to get / extract de branch name from the repository or the API?
I think this value can be easily replaced by mistake when you merge branches.

**Comment by afragen** [comment]
@benoitchantre have you updated to the latest develop branch of GHU? In my testing it worked with your plugin.

**Comment by afragen** [comment]
Current version is GHU 5.3.3.4

**Comment by benoitchantre** [comment]
@afragen I did my tests with GitHub Updater 5.3.3.4 (develop branch).

**Comment by afragen** [comment]
@benoitchantre instead of using another plugin to clear transients, all you should need to do is to use the Check Again button, then go back to the plugins page.

**Comment by benoitchantre** [comment]
@afragen now it is working as expected. The branches are displayed and I can switch branches :-)
I have done nothing done since yesterday.

Thanks for the patch and for your support.

One question regarding branches:
Is it not possible to get / extract de branch name from the repository or the API?
I think this value can be easily replaced by mistake when you merge branches.

**Comment by afragen** [comment]
The transients expire after 12 hours so that's probably why it now works.

In the branch switching, the branch and the link are extracted from the API. It will switch to the correct branch and you can currently confirm by looking at th the URI being downloaded.

@flashadvocate is it now working for you as well?

**Comment by benoitchantre** [comment]
> In the branch switching, the branch and the link are extracted from the API. It will switch to the correct branch and you can currently confirm by looking at th the URI being downloaded.

I don't understand why we need to add the branch header if they are extracted from the API.
From the readme, I understand it is used to select the branch where updates are pulled from.
Why doesn't we use the name of the active branch to select the corresponding remote branch?

**Comment by afragen** [comment]
You need to have the branch header to differentiate the two branches. The API returns the branches in the repository. It does not specifically identify which branch you're working with.

**Comment by benoitchantre** [comment]
Thanks again for the explanations.

I let the issue open because it seems your are you waiting for a second confirmation from @flashadvocate.

**Comment by flashadvocate** [comment]
@afragen let me see if I can run into the problem again. I'll let you know
