### ISSUE TITLE
Support of submodules

### ISSUE THREAD

**Issue by benoitchantre** [afragen/github-updater#346]
If you have a plugin that has a submodule, the content of the submodule is not downloaded when you install the plugin.

**Comment by afragen** [comment]
This is a general problem with GitHub and submodules. If you download the repo normally submodules are not downloaded. The only work around is to create a release asset that includes the submodules and is appropriately tagged with the latest tagged release. That or just not use submodules.

**Comment by benoitchantre** [comment]
Thanks for the explanation.
