### ISSUE TITLE
You must set a GitLab.com, GitLab CE, or GitLab Enterprise Private Token.

### ISSUE THREAD

**Issue by charli-polo** [afragen/github-updater#347]
Hi there,

Since a few days, I have this message in different WP backoffice:
"You must set a GitLab.com, GitLab CE, or GitLab Enterprise Private Token."

I checked, and in GitLab Private Settings, I have my private token, so this is strange.

I can still install a plugin, but the updates never appears.
So I have to delete and re install plugin in order to have them up to date.

This has been seen on 3 different website and 2 different servers.
Tell me if I can help in any way.

And thx for this great plugin.

**Comment by roadsidedevteam** [comment]
I am experiencing the same issue and would like to find a solution.

**Comment by afragen** [comment]
Are these plugins on GitLab.com or private GitLab installations?

Can you post the plugins headers and provide a screenshot of the Settings?

**Comment by roadsidedevteam** [comment]
This happened with the latest WP update for me. It s a private Gitlab.

**Comment by roadsidedevteam** [comment]
@afragen They are on GitLab.com as a private repo,
![capture](https://cloud.githubusercontent.com/assets/15658932/12276480/96801dae-b93b-11e5-9981-1133ac7742c9.PNG)

**Comment by afragen** [comment]
@roadsidedevteam this seems to be a different issue. What is it you are expecting to see?

What I see is a theme that isn't showing an update and has no tags. Is there supposed to be an update?

**Comment by charli-polo** [comment]
Well the issue has disappeared...
I am not sure why. Maybe gitlab had some issues (I am on gitlab.com)

I'll keep an eye on it, sorry for the trouble.

**Comment by charli-polo** [comment]
@roadsidedevteam I closed the issue, I hope it's ok for you too ?
