### ISSUE TITLE
Lite / embeddable version?

### ISSUE THREAD

**Issue by mgibbs189** [afragen/github-updater#348]
Hey Andy,

Just wondering if you've considered adding an embeddable version of this plugin?

I'm currently using GHU for quite a few plugins hosted on public GitHub repos. I recommend that users install GHU to get automatic updates, but most users don't actually install it. It'd be awesome to be able to bundle this with any plugin so that updating happens automatically. Pseudocode below.

```php
if ( ! function_exists( 'GHU' ) ) {
    include( PATH_TO_GITHUB_UPDATER_EMBED_FILE );
}

GHU()->register_plugin( array(
    'Plugin Path' => 'github_updater/github_updater.php',
    'GitHub Plugin URI' => 'https://github.com/afragen/github-updater',
    'GitHub Branch' => 'master',
) );
```

**Comment by afragen** [comment]
Hey Matt,

@royboy789 has asked about this too.

My biggest issue is having that embedded code be updated when it changes. 

It begs the question of what do you think would be better? 

A lite embeddable version or something that automatically downloads and installs GHU if it's not already installed something like TGMPA https://github.com/TGMPA/TGM-Plugin-Activation
Bear in mind I think TGMPA is moving towards a plugin too.

Thoughts?

**Comment by afragen** [comment]
We could create a drop-in class that would check to see if GHU is present and active. If not it would install and activate.

**Comment by mgibbs189** [comment]
@afragen A notifier / updater class (like TGMPA) would be an awesome solution too.

**Comment by afragen** [comment]
I've been playing around this evening and I have a small class that should be able to install and activate GHU if it's not present. Once I get it working better I'll put it up. Should be tomorrow.

TGMPA is moving towards being a plugin and looking at the discussion regarding TGMPA as a feature plugin, it was mentioned that dependencies should be added and activated without user interaction. We probably should add a notification that the plugin is being installed as a dependency for the other plugin.

**Comment by afragen** [comment]
Hey Matt, a question. 

Do you think something more universal to install one or more plugin dependencies or just stick to GHU?

I think we could make something reasonably simple that could use a json encoded file as input.

**Comment by mgibbs189** [comment]
I'd love to see a small lib that works like TGMPA, but only for the GitHub updater plugin. E.g. it notifies users to install it, via an admin notice.

**Comment by mgibbs189** [comment]
I don't even think it would necessarily need to install GHU for them.

It would check if GHU is active. If not active, it'd show an admin notice containing either (A) an "Install plugin" link, or (B) a link to download the GHU zip.

This admin notice would presumably be dismissed temporarily (e.g. for a week), but not permanently.

**Comment by afragen** [comment]
So here's what I've done. https://github.com/afragen/wp-install-dependencies

There's an example plugin and a drop-in folder with a class and json package file for config. I make several assumptions, among them that the dependencies are needed and must be active.

There's still an issue with some install info but I'm not sure how to get rid of it.

There is essentially no user interaction except to activate your plugin. Currently the class only works on plugin pages.

It's been a fun morning. :+1:

**Comment by mgibbs189** [comment]
Andy, this looks great! A few suggestions:

1. Some users might not want plugins to be installed automatically. In each item's JSON settings, what are your thoughts on supporting an (optional) `confirmation` setting? If it exists and is set to TRUE, the user will need to confirm installation (by clicking an "Install" link within an admin notice).

2. If this gets used by multiple plugins, there will need to be a way for each plugin to modify `$config`. Maybe something like:

```php
$config = apply_filters( 'wpid_register_dependencies', $config );
```

**Comment by afragen** [comment]
Matt,

Let's take the discussion over to the other repo and reference back here.

**Comment by deviodigital** [comment]
Not sure if all discussion about this is at the new repo, but I wanted to give a :+1: to this idea. Would be happy to help in any way I can.

**Comment by afragen** [comment]
Take look over there. The `master` branch basically will install and activate any plugins passed in the included json config. The `js-install` branch is an effort to have optional install plugins and have them install and activate using JS like how Matt did in his single purpose installer.

I could really use some help getting this to work. Currently, I think we've gotten it located under the plugin requiring the dependencies.

All help is welcome.

**Comment by deviodigital** [comment]
Cool. I'll check it out soon and see if there's anything I can offer to help. I'll be using this for all WordPress theme projects going forward, so this idea definitely interests me.

**Comment by afragen** [comment]
https://github.com/afragen/wp-dependency-installer/
