### ISSUE TITLE
Clone submodules

### ISSUE THREAD

**Issue by limikael** [afragen/github-updater#349]
It would be great if plugins installed using github-updater would also cloe submodules of the installed plugins. When using git from the command line, submodules are included be using `git clone --recursive`. Not sure if github-updater uses the command line version of git internally or if it uses some other magic way. More info on submodules: http://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules

This is mainly to start a discussion. If you like the idea, _maybe_ I can submit a PR...

**Comment by afragen** [comment]
GHU uses the WordPress core methods for updating. It doesn't use `git clone`. It acts just like when you would download a repository from GitHub and unfortunately that doesn't sync and download submodules.

Most users would not have git running on their shared hosts anyway.

There is a way. For each tagged release you could create a release asset that includes the submodules. GHU will use a release asset if it sees one.

**Comment by limikael** [comment]
Ok makes sense... Thanks for the quick reply, closing this for now...

**Comment by unfresco** [comment]
> There is a way. For each tagged release you could create a release asset that includes the submodules. GHU will use a release asset if it sees one.

I have not been able to get it working at [wherever-content plugin](https://github.com/unfresco/wherever-content/releases/tag/2.1.12). I think the attached asset has the correct spelling but It still only pulls from the repo without the submodules, not the .zip file where I have them included. Thanks for any hint!

**Comment by afragen** [comment]
You must include the header `Release Asset: true` in the plugin.

**Comment by unfresco** [comment]
First try with a [theme](https://github.com/unfresco/last2-theme/releases) didn’t work out… I understand that magic happens [here](https://github.com/afragen/github-updater/blob/162d693ee2020475793f6b8d3f6f8b64f91cbed0/src/GitHub_Updater/API/GitHub_API.php#L140)? And that an alternative to retrieving from a release asset would be through the _github_updater_post_construct_download_link_ filter?

**Comment by unfresco** [comment]
Looking into the received $headers at https://github.com/afragen/github-updater/blob/1550833b6f5084ca2d9f4fa90a331baf10378adc/src/GitHub_Updater/Base.php#L896 the “Release Asset” key is empty so probably the error is on my side but what is wrong about https://github.com/unfresco/last2-theme/blob/6234837be70d960dbcfeddd1feb63bbc405baf93/style.css#L5 ?

**Comment by afragen** [comment]
@unfresco so firstly it’s very difficult to follow when you have added new problems to an issue that has been closed for over 3 1/2 years. Please create a new issue or hit me up on Slack.

Second, I was able to install and update your theme successfully. To test I simply decreased the local version number to _trigger_ an update notice.
