### ISSUE TITLE
New versions not detected

### ISSUE THREAD

**Issue by limikael** [afragen/github-updater#350]
Thanks for a great plugin!

I have the problem, however, that the github-updater does not detect updates to my plugins. What I did was the following:

1. Installed github-updater
2. Made sure I had a "Version:" and a "GitHub Plugin URI:" field in my .php file. The plugin php file is here: https://github.com/tunapanda/wp-remote-sync/blob/master/wp-remote-sync.php
3. Installed the plugin using the UI of github-updater. This worked fine.
4. I not tried to update the version and push the change to github. I would expect that the next time i logged in to my wordpress site, github-updater would detect the update and prompt me to update. This did not happen... I thought that maybe there was some button in github-updater I needed to press in order to have it update, but I didn't find such a button either...

Is my installation working correctly, or have I done something wrong when installing? Is there something else I don't understand?

**Comment by afragen** [comment]
@limikael you will have to wait until the cache expires, 12 hours, or use the Check Again button from the core update page which will clear the transients.

**Comment by afragen** [comment]
@limikael is it now working?

**Comment by limikael** [comment]
yep it worked fine! thanks!
