### ISSUE TITLE
Deprecated notice

### ISSUE THREAD

**Issue by mgibbs189** [afragen/github-updater#352]
Hey Andy, I'm occasionally seeing this PHP notice:

`Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Automattic_Readme has a deprecated constructor in [path]/wp-content/plugins/github-updater/vendor/parse-readme.php on line 3`

E.g. change:

```php
function Automattic_Readme() {
```

to

```php
function __construct() {
```

**Comment by afragen** [comment]
You are correct. I'll fix.

**Comment by afragen** [comment]
And the method's empty to boot.

**Comment by mgibbs189** [comment]
:+1:

**Comment by afragen** [comment]
https://github.com/afragen/github-updater/commit/9ced9f2a6848425216406fb7920578a4e6223945
