### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by jhcorsair** [afragen/github-updater#353]
Ok, my GitHub stylesheet header is like so:

Theme Name: 	   Used Car Lot Theme
Theme URI:	   http://jehtech.com/wp.plugin
Description: 	   Child theme of the twentyten theme 
Author: 	   Jim Haney Jr
License:           GNU General Public License v2
License URI:       http://www.gnu.org/licenses/gpl-2.0.html
Template:          twentyten
Theme Version:     1.0.1
GitHub Theme URI:  https://github.com/jhcorsair/Used-Car-Lot-Theme
GitHub Branch:     master

and my header from the theme installed on my site is like so:

Theme Name: Used Car Lot Theme
Theme URI: http://jehtech.com/wp.plugin
Description: Child theme for the twentyten theme 
Author: Jim Haney Jr
License:           GNU General Public License v2
License URI:       http://www.gnu.org/licenses/gpl-2.0.html
Template: twentyten
Version: 1.0.0
GitHub Theme URI: https://github.com/jhcorsair/Used-Car-Lot-Theme
GitHub Branch: master

I have your plugin installed and activated but I've received no update notice. I've hit the check again button, waiting for an hour or so and zip ...... nada.

Did I miss something perhaps?

**Comment by afragen** [comment]
I should be able to look into this tomorrow. Stay tuned

**Comment by afragen** [comment]
@jhcorsair you have a very small problem with your style.css headers.

You have `Theme Version: 1.0.1` and it should be `Version: 1.0.1`. Fix that and all should work. :+1:

**Comment by jhcorsair** [comment]
Works perfect. Thanks and sorry to trouble you for such a minor thing!
Sometimes the answer is right in front of you.

**Comment by afragen** [comment]
Fresh eyes help a lot at times. :smiley:
