### ISSUE TITLE
Adding functions to "Add Theme" and "Add Plugin" tabs

### ISSUE THREAD

**Issue by deviodigital** [afragen/github-updater#357]
I've been working on some edits to the plugin and was curious to know what you thought about putting in a custom function for theme and plugin authors to use. It would allow for featured themes from the author to be displayed, similar to the image below.

![github-updater](https://cloud.githubusercontent.com/assets/9917957/12795101/8766d4a0-ca86-11e5-9844-8b40aa55a938.jpg)

I've got code examples if you'd like me to push them. A quick and dirty example can be seen in [this gist](https://gist.github.com/deviodigital/5aedfeccd49c87246cd9), which has the "Add Theme" link that, when clicked will scroll the user down to the input box where the theme's URL gets added automatically

**Comment by afragen** [comment]
The Install Plugin/Theme page is really just to install a known entity. It's not designed as a search service and I would like to keep it simple.

It sounds like it could be a great idea for another plugin though.

**Comment by deviodigital** [comment]
Totally understandable. I wasn't thinking a full on search service, though. I was thinking more of a place for a theme or plugin author to add a piece of code in their theme or plugin hooking into the space above the form.

This way, if I, as a theme author, wanted a way for people who use my theme to have the easy option to install another one of my themes, I could.

If the theme or plugin author doesn't hook into it, it wouldn't show anything, as it currently does.

Also, a bit off-topic but it's in the [gist](https://gist.github.com/deviodigital/5aedfeccd49c87246cd9), I added a link for the Github Updater logo to your github repo, so people in the future when adding the plugin have a quick way of finding info about it. I can submit that in a separate PR if you'd like

**Comment by afragen** [comment]
Linking the logo to the repo seems like a good idea. PR away

**Comment by deviodigital** [comment]
Further explanation and code examples for what I was referring to for the function.

In the Github Updater plugin in `src/GitHub_Updater/Settings.php` file [here](https://github.com/afragen/github-updater/blob/develop/src/GitHub_Updater/Settings.php#L156) there would be the following code

	echo githubupdater_featured_plugins();

Then, the following could would be in the same file, a couple lines down [here](https://github.com/afragen/github-updater/blob/develop/src/GitHub_Updater/Settings.php#L159)

	echo githubupdater_featured_themes();

Now, as a theme author, I have the Clean Blog theme for download, and I would then be able to showcase other themes I've built when a user is using one of my themes.

To do this, I could hook into the above `githubupdater_features_themes()` code and output my own themes, similar to the original image in this issue. You can [view this gist](https://gist.github.com/deviodigital/8850fe0f1444a2ea1883) for the example code I used to hook into it.

*the image url's starting on line 49 can be changed to pull from the theme or plugin author's folder*

Let me know what you think.

**Comment by afragen** [comment]
What do you think about `feature/dev-showcase-hooks` branch?

My only fear is that someone could use this as a security vector. I'm not sure how to escape the output and still allow it to be useful. Currently output is not escaped but it will need to be.

**Comment by deviodigital** [comment]
Thanks for putting this together. I'll look it over later today and see if there's anything to do that can help with security.

**Comment by afragen** [comment]
We would have to pass the filter through `esc_html()`or something and any html would not survive.
