### ISSUE TITLE
Obscured Access Token

### ISSUE THREAD

**Issue by damanic** [afragen/github-updater#358]
Thanks for the useful plugin,

Is it possible to make the access token fields hidden on entry by using password fields and not have the key shown again on the settings page once stored. Storing the keys as encrypted in the database would be further improvement.

I have an install where I have entered my github access token for private repository access but I do not want to make that token visible to other admins. Unfortunately the github access token gives access to all private repos and cannot be limited to one. Perhaps there could be a way to assign a deploy key or alternative auth method assigned to each plugin where read access can be granted to the required repo only?

**Comment by afragen** [comment]
Unfortunately those wouldn't remain private as they would be visible in the upgrade URI. Someone with admin access to your site could alway find the token.

There is another solution. If you don't need/want other admins to access the GHU settings you can block it out entirely using the following hook.

`add_filter( 'github_updater_hide_settings', '__return_true' );`
