### ISSUE TITLE
Gitlab private repos (theme and plugin) stopped working

### ISSUE THREAD

**Issue by JiveDig** [afragen/github-updater#360]
I have a private theme that was showing updates fine for a few weeks, and now the update never shows up in WP dashboard. Same thing with a different private plugin on a totally different server.

Theme header (stopped working):
```
/*
	Theme Name: Holistic Squid
	Description: Holistic Squid is a custom child theme for The Genesis Framework.
	Author: Mike Hemberger
	Author URI: http://thestizmedia.com/
	Version: 2.0.2
	Template: genesis
	Template Version: 2.0.2
	License: GPL-2.0+
	License URI: http://www.opensource.org/licenses/gpl-license.php
	GitLab Theme URI: https://gitlab.com/jivedig/holisticsquid
*/
```

My access token is still showing in GU settings.

**Comment by afragen** [comment]
Can you give `read` privileges to user `afragen` so I can test?

**Comment by JiveDig** [comment]
I made you a reporter. That should do it right?

**Comment by afragen** [comment]
That works.

I was able to use GHU to install the theme and then I decreased the version number in style.css locally. An update notice registered and I was able to update.

Can you try that?

**Comment by JiveDig** [comment]
Interesting. Thanks for taking the time to test btw, very cool of you.
I re-installed the theme via GU this time, then bumped down the version number on the server, then force checked for update, still nothing. Maybe it's a server configuration thing?
The website is holisticsquid.com and it's hosted with Web Synthesis.

FWIW, i'm seeing this error as well, with Query Monitor running.
<img width="1201" alt="screen shot 2016-02-11 at 10 45 45 am" src="https://cloud.githubusercontent.com/assets/540990/12981001/dc11f260-d0ac-11e5-9c5e-fb3cc2f727a5.png">

**Comment by afragen** [comment]
I'll do a bit more checking. The error you see denotes a problem with getting the data from GitLab.

**Comment by afragen** [comment]
@JiveDig the problem you seem to be having has to do with updating `Template Version:` and not `Version:`

According to the Codex, https://codex.wordpress.org/File_Header#Theme_File_Header_Example , the `Template Version` header is not required. I believe that header refers to the version number of your parent theme, Genesis.

It might be less confusing to remove the `Template Version` header, but the bottom line is you must change the `Version` header, nothing else will matter. Sometimes this is much more confusing than it needs to be. :wink: 

Please let me know if that solves your problem.

**Comment by JiveDig** [comment]
OMG, that is extremely embarrassing.  The template version is def referring to Genesis. Sometimes i use that to keep track of when i actually put together a starter/custom child theme. What a waste of your time. Thanks for sticking with me here. I'll test when i get a min and confirm we're all good. Thanks!

**Comment by afragen** [comment]
Not a waste of time. Sometimes we stare at something so long we miss the obvious and a fresh pair of eyes provides a quick solution.

**Comment by JiveDig** [comment]
I forgot to update. I tested this. It works, but seems to take waayyyy longer to show updates from GitLab vs Github. I actually moved some of my repos to Github cause I couldn't handle waiting for updates to show Also notice Bitbucket delay compared to GH as well. It may be on their end, idk... but definitely noticed it on a few different repos.

**Comment by afragen** [comment]
The actual update time shouldn't be terribly different. It's possible that the transients could be on different cycles. The develop branch also has a new feature where repos that have not had a version bump aren't being hit remotely except for 1 or 2 API calls, in this case one API call for GitHub or Bitbucket and 2 APIs calls for GitLab. Is only for repos not updated.

Have you tested with something like Query Monitor to see the actual http requests and how long they take?

**Comment by JiveDig** [comment]
I'm running Query Monitor on some sites. I see requests but the update doesn't show immediately. Sometimes hours. Is there a process I can follow to debug or confirm things on my end?

**Comment by afragen** [comment]
I follow the processes locally in PHPStorm using XDebug
