### ISSUE TITLE
Bitbucket private repo updating

### ISSUE THREAD

**Issue by fxguillois** [afragen/github-updater#361]
Hi,

I'm very excited by your work, since i'm discovering Infinite WP as well. 
I develop a private theme for my company, on a Bitbucket private repository. i was thinking to transfer the repo to Github, then i've discovered your plugin !

I manage to install my theme by the bitbucket URI. But i've no clue on how updating works. i'm keeping raising my version number, but there's no update message anywhere. In my theme details windows, i get a dropdown menu with version numbers, but never the last one. 
`/*
Theme Name:     C set ID
Theme URI:      https://www.csetid.com/
Description:    Thème pour les sites C set ID
Author:         François-Xavier Guillois <fx@csetid.com>
Version:        0.7.9
Bitbucket Theme URI:    https://bitbucket.org/csetid/csetid
*/`

![capture du 2016-02-09 16 36 06](https://cloud.githubusercontent.com/assets/933914/12920976/57823abc-cf4b-11e5-8ab9-1eae57b9b390.png)
![capture du 2016-02-09 16 36 33](https://cloud.githubusercontent.com/assets/933914/12920975/5781bcb8-cf4b-11e5-86a7-e3d751a1531f.png)

What i'm doing wrong ?

Many thanks,

**Comment by afragen** [comment]
It may be that the transient is still cached. You can clear the transients by going to the update-core.php page and using the 'Check Again' button, or just wait 12 hours.

You can also decrease the version number locally and an update notice should trigger.

**Comment by fxguillois** [comment]
this button ?

![mises a jour de wordpress c set id wordpress 2016-02-09 20-41-46](https://cloud.githubusercontent.com/assets/933914/12928420/9e08cd08-cf6d-11e5-9c8d-8700d461221d.png)

no result.

i'm not sure to understand what do you mean by decreasing the version locally, but i've commited style.css with a new version number and a new tag number, and wordpress backoffice hasn't reacted. 

so if the check again button won't fix the thing, i assume i should have made a mistake somewhere...

**Comment by afragen** [comment]
That's the button. Can you give `read` privileges to user `afragen` so I can test?

**Comment by fxguillois** [comment]
This morning, i could update my theme in two Wordpress, great !
So i've upgraded my version number again (0.8 now), and the check button doesn't make this update appear. 

the 12 hours solution work, afaik.

thanks !

**Comment by afragen** [comment]
Only click the Check Again button once, then go to the Plugins page or reload the core update page from the link in the sidebar. Otherwise the transients will continually be deleted.

**Comment by afragen** [comment]
@fxguillois I've received credentials for your site, but I would prefer to install the theme locally and test. Can you give user `afragen` `read` access to https://bitbucket.org/csetid/csetid ?

**Comment by fxguillois** [comment]
Sorry for the delay its done.

**Comment by afragen** [comment]
Sorry for the delay. What I see is that your latest tag is `0.8.1.1` and your current version is listed as `0.8.0.1`. I'm certain this is the issue. While you don't have to tag releases, once you start you must continue to do so.

Your version number and your tag must match.

**Comment by fxguillois** [comment]
So here i am again :)

push the 0.8.1.2 in repo
https://bitbucket.org/csetid/csetid/raw/034e33f3106a0ec67a23a3d6f637f3038e550317/style.css

go to the update page :
http://new.fromageriebouchet.com/wp-admin/update-core.php

no clue about a new version, so i've clicked once on the Update Now button. no update appeared. 

Then i go to my themes
http://www.csetid-team.com/wp-admin/themes.php?theme=csetid
and then look at the "older versions" : no tag available, it says...

but i'm just remembering i'm using the develop branch of your plugin, maybe it's where i'm falling. 

Thanks for your time.

**Comment by fxguillois** [comment]
I found what blocked the update : bitbucket password. 
I tested on several wordpress with github updater installed. when i'm going in the back office, no alert, theme shows no tag list. when i tape my password again, update appears instantaneous....

Maybe it's a password error (but i've dozen of wordpress with gitub updater now, so i'll be surprised), or maybe when i submit the form something manages to connect. 

Maybe you could develop an indicator for knowing if bitbucket manages to connect ?

Thanks for your time.

**Comment by afragen** [comment]
Strange as there is an error message that should be generated if the the authentication fails. In any event, glad you got it sorted out and it's working.

**Comment by squarecandy** [comment]
Thanks for the great plugin. In case it's helpful for anyone else, I found the "refresh cache" button on the GitHub Updater Settings page to help with getting fresh info from Bitbucket, where the "Check Again" button on the WP updates page was not helpful.
