### ISSUE TITLE
Better API error rate handling

### ISSUE THREAD

**Issue by mgibbs189** [afragen/github-updater#362]
Hey @afragen,

Let's make API rate limit errors more graceful.

<img src="http://i.imgur.com/uXlHJsS.png" width="680" height="276" />

- [x] Show 1 error message total (instead of 1 per plugin)
- [x] Allow the error message to be dismissed (for like a week by default)
- [ ] Store the "time until rate limit reset" value. Prevent further update checks until the rate limit has reset, or an API key has been entered
- [x] Bonus: force update check limits -- maximum of 1 check per plugin per hour

P.S. do you know offhand how many API calls are made, per plugin? It's pretty darn easy nowadays to hit GitHub's 60-per-hour limit for anonymous API calls.

**Comment by afragen** [comment]
Hey Matt. 

Lots of very interesting suggestions.

I don't think dismissing an error message for a week when that will go away in an hour really needs to be done. 

I was trying to be more descriptive by having each plugin display the error message. Is there less value in that approach? I know, asking for a value judgment. :wink: 

I do like the idea of skipping updates until after the rate limit expires or an API key entered. But once API key entered the user will never see the error message so it won't matter. 

There are about 6 API calls per plugin. Some are overkill, like checking for an asset. This is probably used by less than 1% and I could probably eliminate it but it's only a single call. Yes, it's very easy to hit the rate limit for anonymous API calls. :stuck_out_tongue_closed_eyes: 

Calls for remote info, remote meta, tags, branches, changelog, and asset.

**Comment by mgibbs189** [comment]
Hey Andy, I hope you're enjoying your weekend :smile: 

My local dev site has a dozen GHU-enabled plugins, so I see a dozen of those error messages. Each one says the same thing... API limit exceeded. This **is** valuable information, but not necessarily for every single plugin... once is enough IMO.

I'm thinking about this process from my customers' perspective (hence why I haven't entered an API key). A good chunk of them have no idea what GitHub is, let alone how to get an API key. They've installed GHU, and expect it to be a "set it and forget it" kind of thing.

60 anonymous API requests / hour is really low, but it's workable if we built some throttling. E.g. do a round-robin approach, check a maximum of 10 plugins per hour. This would help eliminate the "rate limit" errors too.

Thanks for the API call info, very helpful.

**Comment by afragen** [comment]
I'm actually working the weekend. 

Once I received a notice from someone working for GitHub. They had traced a site with large numbers of API calls to my plugin. They wanted to encourage users to enter and use an access token.

@petersuhm is using Laravel/Socialite to create an oAuth token from a single click. It looks like a great solution but would require setting up a new site instance for this. Not a huge entry barrier but I still haven't figured it out. Take a look at http://wp-pusher.com to see it working.

If we could figure out some similar method of creating and collecting an oAuth token that would be huge and would be great for Bitbucket too.

As for round robin of plugin checking, interesting thought. Perhaps store the plugin slugs needing updating in a one hour transient, only checking those plugins and only adding 8-10 to the transient at a time, stop checking once the transient is full and while it is exists. Just brainstorming.

**Comment by afragen** [comment]
I just had another thought. What if after getting the remote file info, which gets the plugin/theme headers, we check to see if an update is available and if yes then do the additional remote API calls?

That could save us 5 API calls for every repo not needing an update and could be simpler.

**Comment by flashadvocate** [comment]
Would certainly detract from the heavy load times on wp-admin that I'm
almost positive are coming from extended usage of the updater (we have
about 15-20 connected repos)

**Comment by petersuhm** [comment]
@afragen just a heads up on Bitbucket: Tokens expire after an hour 😩 Working on a long term solution for this, but this can potentially be a lot of traffic on your server, since tokens would have to be refreshed all the time... Wasn't aware of this when I started!

**Comment by afragen** [comment]
Thanks for the insight @petersuhm, that sucks!

When I have some time I'll work on a branch to pull the readme, changes, etc, locally if there's no update available. That should significantly improve speed.

**Comment by afragen** [comment]
If anyone wants to test branch `feature/skip-remote-no-update` and let me know what you think. You will likely have to wait for 12 hours to pass to see results. Everything will update if the 'Check Again' button is used, as expected.

In my testing I can eliminate 5 of 6 API calls for plugins not requiring updates. We should be loading the other info from the local files.

Kick the tires for a few days and let me know what you think.

**Comment by afragen** [comment]
Please reinstall this branch as I've made a few updates for better handling of checking when branch switching is enabled.

So far I've seen a 60% decrease in number of remote API calls. :+1:

**Comment by mgibbs189** [comment]
:clap: looking good!

**Comment by afragen** [comment]
Anyone notice any show stoppers? If not, I'll probably merge into `develop` tomorrow.

**Comment by mgibbs189** [comment]
@afragen Looks pretty good from what I can tell

**Comment by afragen** [comment]
Thanks Matt. I know we seem to have hijacked this issue, are there any points you wish to continue discussing?

**Comment by mgibbs189** [comment]
It's mostly my fault for lack of availability, but I think the error message issue is going to be a really important one.

Your changes have mostly addressed the 4th bullet point (from the first thread), but getting the first 3 addressed (eventually) would be awesome too.

**Comment by afragen** [comment]
Do you think not listing the specific plugin that is having a problem is the way to go or should we just add all the plugin names in an array and dump the array in the error message?

**Comment by mgibbs189** [comment]
For API rate limit errors, I don't think it's important to list each affected plugin... as long as the user knows that they've hit the limit and will need to either wait for the limit to reset, or add their API key.

**Comment by afragen** [comment]
@mgibbs189 with the current changes in `skip-remote-no-update` are you still seeing these error notices? Just curious, I'm still planning on combining the notices.

**Comment by afragen** [comment]
`skip-remote-no-update` now merged to `develop`

**Comment by afragen** [comment]
@mgibbs189 https://github.com/afragen/github-updater/commit/72510e0eae609d4074dd63a0a3a00814c14f07ed should fix first bullet.

**Comment by afragen** [comment]
Hey Matt.

I've been using this branch on my test site without an access token and I've yet to see a warning that wasn't associated with a Check Again clearing of the transients.

Are you seeing the warning? Is it bothersome enough to try an fix the last 2 points on your list?

**Comment by mgibbs189** [comment]
Hey Andy,

No worries, those aren't a big deal. While it'd be nice to see eventually, they're really not that important. Getting those other 2 fixed have been a huge deal! :+1:

**Comment by afragen** [comment]
Hey Matt,

I'm looking at my fork of https://github.com/afragen/persist-admin-notices-dismissal as  framework for dismissing notices. It looks really good, but I haven't tested it.

I can see including it and then being able to set some dismissal times. 👍

**Comment by mgibbs189** [comment]
@afragen That lib looks good to me 😃

**Comment by afragen** [comment]
I just made a PR for my changes. In testing it seems to work well.

I don't think a week dismissal is needed, perhaps only a day as the notice would go away automatically after an hour.

I can foresee user problems if we set the dismissal for too long. Any thoughts as to dismissal time per message? How long should we dismiss the notices for adding Enterprise/GitLab/Bitbucket user/pass errors?

**Comment by afragen** [comment]
@mgibbs189 I'm having issues making it work on test server. Works great locally. 😝

**Comment by afragen** [comment]
I figured out the problem. Apparently `admin_enqueue_script` is called before `admin_notices`. This means I had to load the admin notice dismissal class outside of where the autoloader will load the class in the function setting up the notice.

I'll move into `develop` in the next commit and you can see how it works for you.

**Comment by afragen** [comment]
@mgibbs189 now live in `develop`, I think we can close this 3 or 4 not bad. 😉 
https://github.com/afragen/github-updater/commit/205009967749e687e898c0e8bb7dec2b0f9de95b
