### ISSUE TITLE
Update GitHub Updater from WordPress?

### ISSUE THREAD

**Issue by reinink** [afragen/github-updater#364]
Hello,

I'm wondering if it would be possible to also update the GitHub Updater plugin from WordPress somehow? Seems to me this plugin is in active development, and it would be nice to have the option to update it easily as well.

Or maybe this is already possible?

**Comment by flashadvocate** [comment]
Yes, this is already possible. When you "check for updates" through the dashboard, the updater will show updates if there are any

**Comment by reinink** [comment]
Of course it is. Thanks!

**Comment by afragen** [comment]
@reinink that made me laugh. :laughing:

**Comment by reinink** [comment]
:grinning:

**Comment by afragen** [comment]
I hope you enjoy it. If you have any questions not answered in the README, let me know.
