### ISSUE TITLE
Use project releases

### ISSUE THREAD

**Issue by ohmanger** [afragen/github-updater#367]
I have a problem with one of my plugins needing to be 'built' before I can release it (composer, grunt to compile LESS).

One way to get round this could be to use the github/bitbucket release system that allows you to upload zip files containing the compiled code.

For bitbucket we end up with the following URL structure:

https://bitbucket.org/account/project/downloads/1.0.0.zip

Which I'd obviously like to priorities over what is in the actual repo.

I think the two ways of handling this would be to:
* add use another meta field to say look for the download in the releases
* and/or add a filter in `construct_download_link()` for the download URL itself. The plugin or theme could then handle the logic to say "don't use that URL, try this one".

I might have missed something so suggestions welcome.

**Comment by afragen** [comment]
Crud, I just removed this feature from GitHub (using a release asset) as I made it for one person and later found they stopped using it. 

I removed it because it created an additional API call for every plugin/theme and figured more users would prefer the speed improvement over the API call.

I guess I should try adding it back. :stuck_out_tongue_closed_eyes:

**Comment by afragen** [comment]
Maybe a filter would be better. I'll investigate.

**Comment by afragen** [comment]
@ohmanger I'm really close. Can you provide an actual link to a release asset?

**Comment by ohmanger** [comment]
@afragen I have set up an example here:

https://bitbucket.org/lighthouseuk/issuu-publication-feed/downloads

Not really sure on the folder structure inside the .zip (e.g. should it be /plugin-name/files or just straight to /files)

**Comment by afragen** [comment]
@ohmanger the structure should be identical to the structure if you downloaded the branch. That is to say `/plugin-slug/files`.

As this is a _release asset_ it should be associated with an actual tagged release. The logic I'm building requires that the release asset and a corresponding tagged release both exist as the logic checks the version number against the newest tag.

The format is as follows.

```php
add_filter( 'github_updater_release_asset', 	function () { 
		$asset     = array( 'test-plugin' => array( '0.7.3' => 'asset_name_0.7.3.zip' ) ); 
		$additions = Fragen\GitHub_Updater\Additions::instance(); 
		$additions->add_release_asset( $asset );  

		return $additions->release_assets; 	} );
```

Where the `$asset` format would be as follows.

`$asset = array( $slug => array( $tag => $filename.zip ) );`

It is essential to include the `.zip` file extension as I haven't included the logic to add it.

In your case you would need to create a release tag for version 1.0.0 and your `$asset` would look like
`$asset = array( 'issue-publication-feed' => array( '1.0.0' => '1.0.0.zip' ) );`

If you would switch branches to `feature/assets` and test that would be great.

**Comment by afragen** [comment]
FWIW, release assets are usually in place when submodules are being referenced in the project as they won't download under normal circumstances with the project download.

**Comment by ohmanger** [comment]
Thanks for the example code! I'll give it a go now.

I might be missing something but the local plugin wont know what the newest `$asset` is (e.g. if I released 1.0.1 to the repo, the local version would still be passing 1.0.0 in the filter). Maybe if the filter could pass the newest version number or release tag.

**Comment by afragen** [comment]
> I might be missing something but the local plugin wont know what the newest $asset is (e.g. if I released 1.0.1 to the repo, the local version would still be passing 1.0.0 in the filter). Maybe if the filter could pass the newest version number or release tag.

Oops, you're right. I may have to make constraints on the filename so that the filename must be in a certain format `slug-version.zip` and then the filter would just pass true to use the release asset when an update is available. This could be more error prone but might work. What do you think?

**Comment by ohmanger** [comment]
Yes I like the sound of that!

I take it errors you mention will happen if there is a new version but no matching asset? I guess this wouldn't be an issue if I always compiled and uploaded the asset before tagging the release.

**Comment by afragen** [comment]
OK, reload the `feature/assets` branch by switching to it again.

Hook now should be as follows.

```php
add_filter( 'github_updater_release_asset',
	function () {
		$asset     = array( 'test-plugin' => true );
		$additions = Fragen\GitHub_Updater\Additions::instance();
		$additions->add_release_asset( $asset );

		return $additions->release_assets;
	} );
```

And release asset **must** be named per the following protocol. `slug-tag.zip` as an example `test-plugin-0.7.3.zip`.

The release asset download URI is created based upon this formula and downloads will obviously fail for incorrect naming.

If the management of tagging and release assets is not correct, the user will have problems.

**Comment by afragen** [comment]
> I take it errors you mention will happen if there is a new version but no matching asset? I guess this wouldn't be an issue if I always compiled and uploaded the asset before tagging the release.

Yes. I don't think the order will be important as long as both are set prior to the user attempting an upload.

**Comment by ohmanger** [comment]
It works! But for some reason caching the old 1.0.0 version and not showing 1.0.1?

A small suggestion would be to just pass an asset array to the filter then call `$additions->add_release_asset( $assets );` in the updater plugin.

It'll simplify the filter down to just:

```
add_filter( 'github_updater_release_asset',
function ( $assets ) {
    $assets['issuu-publication-feed'] = true;

    return $assets;
} );
```

The _API code could then just look something like:

```
$release_assets = apply_filters( 'github_updater_release_asset', array() );

$additions = Additions::instance();
$additions->add_release_asset( $release_assets );

if ( array_key_exists( $this->type->repo, $release_assets ) ) {
	$asset[ $this->type->repo ] = $release_assets[ $this->type->repo ];
	if ( $asset[ $this->type->repo ] && '0.0.0' !== $this->type->newest_tag ) {
		return $this->make_release_asset_download_link( $asset );
	}
}
```

To me just feels a bit more 'filter-y'

**Comment by afragen** [comment]
You will likely have to clear the transients by using the Check Again button.

The above won't work if there are multiple plugin's using release assets. Only the last filter call will see the correct data. That's why I had to use a singleton and save the filter hook to a class variable.

Unless there's another way?

**Comment by ohmanger** [comment]
The filter variable gets passed to other plugins hooking into the filter! [`the_content`](http://codex.wordpress.org/Plugin_API/Filter_Reference/the_content) is a good example as it goes through lots of functions (wptexturize, wpautop, do_shortcode)

**Comment by afragen** [comment]
Thanks for putting me on the correct path. When I initially did this I was overwriting the current contents of the filter by using `$asset = array( $slug => true )` and not `$asset[ $slug ] = true`

I've made the proper adjustments and now I don't need to mess with creating a singleton or the class variable. Much simpler. Thanks.

Let me know if it's working for you and I'll merge into `develop`

**Comment by afragen** [comment]
@ohmanger as I've been testing I think it would be best to place this hook into a must-use plugin so that even when the plugin requiring the release asset is inactive it will be able to use the proper download link. Otherwise, when the plugin is inactive the hook will not fire and the normal download link will be generated.

**Comment by ohmanger** [comment]
Yeah good point, I didn't realise the updater worked on inactive pluggins..
Bit of a backwards step but maybe setting this in the plug in meta would be
more reliable?

**Comment by afragen** [comment]
Do you mean adding another header to the main plugin file?

**Comment by ohmanger** [comment]
Yeah, presumably it is parsed even if the plugin is deactivated

**Comment by afragen** [comment]
It is parsed regardless of the plugin's activity state.

I can work on adding something like `GitHub Updater Release Asset: true`

It would certainly be more consistent.

Thoughts?

**Comment by ohmanger** [comment]
Yes that seems more in line with the other headers!

And thanks for looking into this

**Comment by afragen** [comment]
@ohmanger Switch to `feature/asset-header` branch.

You will need to have a header `Release Asset: true` in the upstream repository. The same requirements for the release asset filename exist.

Let me know how this works for you.

**Comment by ohmanger** [comment]
Works great for me in BitBucket. :+1:

**Comment by ohmanger** [comment]
I have done some more testing and it seems that it doesn't work with private BitBucket repos - I get a 'Download failed. Bad Request' error. Removing the `Release Asset: true` header goes back to downloading the uncompiled zip so I know the credentials are correct.

**Comment by afragen** [comment]
Very strange as the credentials are added elsewhere. I'll look closer.

**Comment by afragen** [comment]
Can you give `afragen` `read` access to the repository so I may check?

**Comment by ohmanger** [comment]
You should have access to the private repo now!

I'm thinking that maybe it is just a limitation of BitBucket not allowing basic authentication on manually uploaded files. I'll query their support to see if they know.

**Comment by afragen** [comment]
Below is are the HTTP request and response args. It appears as though Bitbucket is using Amazon S3 for storage of it's uploaded assets and we have a failure to communicate between Bitbucket's Basic Auth and Amazon S3 auth.

I'm not sure how to go about fixing this. I have zero experience with S3.

```
string '
<br />Request URL: 'https://bbuseruploads.s3.amazonaws.com/99fb5ebf-6e4c-4fd8-b5d7-1ea3177ef012/downloads/7747e57d-b865-4e01-a0e9-f08fd8548d38/bandce-ask-api-1.0.1.zip?Signature=iOmQvGrC5h3VUTkn9Kw5C2uV2n8%3D&Expires=1457374259&AWSAccessKeyId=xxxxxxxxxx&versionId=xxxxxxxxxx_ws&response-content-disposition=attachment%3B%20filename%3D%22bandce-ask-api-1.0.1.zip%22'' (length=395)
string '
<br />Request Args: array (
  'method' => 'GET',
  'timeout' => 300,
  'redirection' => 4,
  'httpversion' => '1.0',
  'user-agent' => 'WordPress/4.5-beta2-36871; http://test.dev; GitHub Updater - https://github.com/afragen/github-updater',
  'reject_unsafe_urls' => true,
  'blocking' => true,
  'headers' => 
  array (
    'Authorization' => 'Basic xxxxxxxxxxxxx',
  ),
  'cookies' => 
  array (
  ),
  'body' => NULL,
  'compress' => false,
  'decompress' => true,
  'sslverify' => true,
 '... (length=1367)
string '
<br />Request Response : array (
  'headers' => 
  array (
    'x-amz-request-id' => 'xxxxxxxx',
    'x-amz-id-2' => 'xxxxxxxxxx',
    'content-type' => 'application/xml',
    'date' => 'Mon, 07 Mar 2016 17:44:27 GMT',
    'connection' => 'close',
    'server' => 'AmazonS3',
  ),
  'body' => '',
  'response' => 
  array (
    'code' => 400,
    'message' => 'Bad Request',
  ),
  'cookies' => 
  array (
  ),
  'filename' => '/var/fold'... (length=587)
string '
<br />Request URL: 'https://bitbucket.org/lighthouseuk/bandce-ask-api/downloads/bandce-ask-api-1.0.1.zip'' (length=106)
string '
<br />Request Args: array (
  'method' => 'GET',
  'timeout' => 300,
  'redirection' => 5,
  'httpversion' => '1.0',
  'user-agent' => 'WordPress/4.5-beta2-36871; http://test.dev; GitHub Updater - https://github.com/afragen/github-updater',
  'reject_unsafe_urls' => true,
  'blocking' => true,
  'headers' => 
  array (
    'Authorization' => 'Basic xxxxxxxxx',
  ),
  'cookies' => 
  array (
  ),
  'body' => NULL,
  'compress' => false,
  'decompress' => true,
  'sslverify' => true,
 '... (length=951)
string '
<br />Request Response : array (
  'headers' => 
  array (
    'x-amz-request-id' => 'xxxxxxxx',
    'x-amz-id-2' => 'xxxxxxxxx',
    'content-type' => 'application/xml',
    'date' => 'Mon, 07 Mar 2016 17:44:27 GMT',
    'connection' => 'close',
    'server' => 'AmazonS3',
  ),
  'body' => '',
  'response' => 
  array (
    'code' => 400,
    'message' => 'Bad Request',
  ),
  'cookies' => 
  array (
  ),
  'filename' => '/var/fold'... (length=587)
```

**Comment by afragen** [comment]
@ohmanger I've got this working, now to just clean it up a bit. I'll let you know when it's testable. :+1:

**Comment by afragen** [comment]
OK, do another switch to `feature/asset-header` to reload and let me know if you break it. :smirk:

**Comment by ohmanger** [comment]
I have used it in a couple of other plugins, all seems to be working now! :star2:

**Comment by afragen** [comment]
Merged into `develop`. You shouldn't have to do anything as the next update to the `develop` branch will have all this.

Thanks for testing with me.

**Comment by GaryJones** [comment]
Just came here to ask about adding this feature, and you've already solved this. Great work!

**Comment by afragen** [comment]
Thanks Gary. It's already pushed to master. It does require a specific format for the naming convention of the release. Let me know if you have any issues.

**Comment by GaryJones** [comment]
Our use case here, is that we want to be able to use some Composer packages.

By default, one wouldn't normally add the `vendor/` directory to the repo. So our plan is to keep it out, but when we tag, we can create a local .zip file, named appropriately, that already has the `vendor/` directory populated, and then add that to the GitHub Release.

**Comment by afragen** [comment]
That should work. Just need to name the release as `$slug-$tag.zip`
