### ISSUE TITLE
How make it work

### ISSUE THREAD

**Issue by adrianwaler** [afragen/github-updater#369]
Hello,

I have few questions about this plugin because I can't make it work.

1. I have created public repository on github, you can see it here: https://github.com/adrianwaler/ApiKey (it's only draft). Instalation by plugin works great but I haven't any notification about update. https://github.com/szepeviktor/github-link installed also and now after swtich branch from master to master plugin is updated.

2. I think it's related but in infiniteWP I haven't any notification too. It will work like normal update and I will be able to update all plugins and don't matter from what source they are?

I don't have if it's my fault in the code, I will be thankfully for any clue.

**Comment by afragen** [comment]
Transients are set for 12 hours so any update may take that long to be recognized. You can clear the transients by using the Check Again button on the update-core.php page.

**Comment by adrianwaler** [comment]
Thanks :) After that I can update plugin from wordpress but infinitewp still cannot see it.

**Comment by BjornW** [comment]
@adrienwater, just some things you might want to checkout: 
- is there somekind of error message you can see in your logs or in infinitewp's?
- can you fake the connection, for instance with cURL to see if you are able to make a connection at all (making sure there's not a firewall preventing this)

**Comment by adrianwaler** [comment]
For now sometimes infinitewp see plugin and sometimes not. In managewp I can always see update, but neither can see update theme. (In wordpress I can see it). Do I forgot about something or it's issue from infinitewp/managewp?
