### ISSUE TITLE
Using Github Updater as a update mechanism on a private Github Repo.

### ISSUE THREAD

**Issue by nextgenthemes** [afragen/github-updater#371]
To me its not obvious how this should be used and the docs are not really there.

My idea is to use a private repository to push out beta updates to testers of my commercial pro addon. The think is I want the repo not to be public accessible.

So should I generate a Github access Token and give then same token out to everyone who wants to test. I am not sure If I am supposed to do this but I guess this if I restrict the token to just the rights needed to update.

Also side question: The readme speaks of "Github enterprise and Self Hosted" the self hosted refers to github enterprise alone or can it be used with self hosted git repo.

**Comment by afragen** [comment]
If you give your beta testers `read` access to the repository all they would need to do is create and enter their own access token. You could then add or delete individual users as you choose.

Make sure the to set the `GitHub Plugin URI` and `GitHub Branch` correctly and those users will have updates. It will also be simpler to have them install the beta test from the Install Plugins tab.

### Enterprise vs. Self Hosted
This refers to a self hosted installation of GitHub Enterprise. You can also self host instances of GitLab and Bitbucket Stash, though I'm still working out the details of supporting Bitbucket Stash.

There are other self hosted git servers but these are not supported at this time.

**Comment by nextgenthemes** [comment]
Thanks for your reply.

I was thinking about giving them **my** access token as I do not want to bother them to make a github account and request a token. I just want them, as you say, install the plugin through the settings page of this plugin and then forget about it and get auto updates while at the same time having the repo private.

Would that be a security concern or will Github choke on it if lets say 50 WP installs use the same token to check for updates?

As for self hosted, thats what I thought. Just wanted to make sure, don't count me in as interested in that feature.

**Comment by afragen** [comment]
I have no idea what GitHub would do with 50 of the same tokens authenticating around the same time. I suspect that would be ok. 

If you plan on distributing a token I suggest you create an app specific token and add it using the hook provided. That way no user will have to enter the token. It's in the README under developer hooks and token distribution.

**Comment by afragen** [comment]
https://github.com/afragen/github-updater/raw/develop/#developer-hooks

**Comment by nextgenthemes** [comment]
Ah thats perfect for what I want to do app token and the hook. I will do that, thanks

**Comment by afragen** [comment]
Let me know if you have issues getting it to work.

**Comment by afragen** [comment]
As an FYI, it would be a personal access token that is needed.
