### ISSUE TITLE
Tags with lower version are being downloaded

### ISSUE THREAD

**Issue by mrtorbert** [afragen/github-updater#373]
When I bump the version in master (github), an update will show available and download it from the latest tag, even if the tag is an older version.

Obviously I can work around this, but it may be worth looking into. :)

**Comment by flashadvocate** [comment]
Are you using releases?

**Comment by afragen** [comment]
The expected behavior is that if you start using tags you must continue using tags. 

If you begin using tags and then simply bump the version number, GHU will identify an update but will pull the update from the newest tag.

**Comment by mrtorbert** [comment]
Hey @afragen 
From looking at the other github issues I figured it was the expected behavior.
I wonder if it would be worth looking into changing the behavior a bit. If you bump the version in master, it probably shouldn't pull from a lower tag.
Either way, you've made an awesome plugin. Thank you, I've sent a donation. :)

**Comment by flashadvocate** [comment]
@mrtorbert actually there is a fairly necessary use case for ignoring commits beyond a tag. The most prominent that comes to mind is releasing software to clients. By using tags, you control what version becomes available to those clients who pull updates from your repo. If you don't create a matching tag, that release doesn't become visible. So instead of forcing clients to update a plugin or theme every time a commit is made, you can explicitly define what is pushed.

Of course, this can be avoided by never using tags in the first place. If you find yourself initially using tags, and then want to stop using them, [you'll need to delete them](https://gist.github.com/matthewmccullough/898798).

**Comment by mrtorbert** [comment]
@flashadvocate What I meant was that it could use tags, but only pull from the tag if the version is higher in that release. It just seems odd that it's using the version from master to determine whether to get an update, but then is getting the actual update from the tag, even if the version in the tag is lower.

So if using tags...

Currently: check to see if master has a higher version than local... if so, pull from the latest tag, ignoring the actual version of the tag

My suggestion: check to see if master has a higher version than local.... if so, pull form the latest tag, but only if the latest tag also has a higher version than what's installed, otherwise don't show an available update.

**Comment by flashadvocate** [comment]
That's true, it would be a good idea to only display an "update available" message if there is indeed a *new* matching tag and version

**Comment by afragen** [comment]
@mrtorbert - first, thanks for the donation!

`master` is expected to be a copy of the latest release. As such it should be identical to the current release. 

Might I suggest using another branch like `develop` and bump the version number to a fourth digit in semver as I have described in the README. 

This is how I work. All development in the develop branch or in other branches based off develop which would later be merged back into develop. I increment the version number in the fourth place so others on the develop branch receive updates. Once ready, I merge into master, tag, and push. 

If you develop in the master branch I would encourage you to not tag releases as this is the problem you will encounter.

**Comment by afragen** [comment]
> That's true, it would be a good idea to only display an "update available" message if there is indeed a new matching tag and version

Troubleshooting this would be much more difficult as updates just won't show when expected vs. showing and updating to a different download link.

**Comment by mrtorbert** [comment]
@afragen No problem, it's only a suggestion to think about. :)

You're very welcome, and thanks again for the great work.
