### ISSUE TITLE
Does not receive GitLab Updates

### ISSUE THREAD

**Issue by marbetschar** [afragen/github-updater#374]
I've configured the GitLab API Token, and set up the GitLab Plugin URI in my plugin.
Additionally I've created the following tags at GitLab: 0.0.5, 0.0.7

Now I installed 0.0.5 on the WordPress page and tried to check via force-check for an update.
But WordPress outputs the following message and no update:

( ! ) Notice: Undefined property: stdClass::$content in /var/www/mandelkind.help/htdocs/wp-content/plugins/github-updater-5.4.0/src/GitHub_Updater/GitLab_API.php on line 86

What's wrong?

**Comment by afragen** [comment]
Can you share the plugin headers or URI for the plugin?

This PHP notice is fixed in the develop branch. You might want to switch to that branch and see if there's a problem.

**Comment by marbetschar** [comment]
Sure, this is the plugin header (it's a private repo right now):

```
<?php
/*
Plugin Name: 		Helpdesk
Plugin URI:  		https://mandelkind.swiss
Description: 		The MANDELKIND Helpdesk, based on Piklist.
Version:     		0.0.8
Author:     		MANDELKIND
Author URI: 		https://mandelkind.swiss
Plugin Type:		Piklist
License:    		GPL2
License URI: 		https://www.gnu.org/licenses/gpl-2.0.html
Text Domain: 		helpdesk
GitLab Plugin URI:	https://gitlab.com/mandelkind/helpdesk
*/
```

**Comment by afragen** [comment]
Can you give `read` access to `afragen`?

**Comment by marbetschar** [comment]
Sure. You should now be able to read & download the project.

**Comment by marbetschar** [comment]
I just did some repo reorganizing. You got still access and you'll find the plugin now here:
https://gitlab.com/happydesk/wordpress

**Comment by afragen** [comment]
Thanks. I found the issue and fixed in latest develop commit. You will have issues however as your tags do no match your release version. What will happen is an update may show but the newest tag will be used for updating. 

Once you begin using tags you must continue. That or remove all tags.

**Comment by marbetschar** [comment]
Cool! Great News!!

Yeah, you're right. Due to the fact the updates not showed up I had to change plans ;)

**Comment by marbetschar** [comment]
Just updated to the development branch and the update was successfully recognized. BUT: After installing the update, the plugin was deactivated.

This was due to the fact, the base plug directory changed from "wp-content/plugins/happydesk/happydesk.php" to "wp-content/plugins/wordpress/happydesk.php"

I suspect this is somehow related to the GitLab Plugin URI and the resulting zip file...? Shouldn't the plugin be installed in a subdirectory named equally as it's main file? If not, how could this be corrected - since "wordpress" is definately wrong somehow ;)

**Comment by afragen** [comment]
Let me know if everything's working and we can close this issue.

**Comment by afragen** [comment]
> This was due to the fact, the base plug directory changed from "wp-content/plugins/happydesk/happydesk.php" to "wp-content/plugins/wordpress/happydesk.php"

> I suspect this is somehow related to the GitLab Plugin URI and the resulting zip file...? Shouldn't the plugin be installed in a subdirectory named equally as it's main file? If not, how could this be corrected - since "wordpress" is definately wrong somehow ;)

But you have renamed the repository to https://gitlab.com/happydesk/wordpress 
The owner is `happydesk` and the repository name is `wordpress`.

The plugin is installed in a directory named for the repository name.

**Comment by marbetschar** [comment]
I see .... mhm works out to be a logical problem.
Is it somehow possible to grab the name of the main plugin file as reference instead of the repo name?

Here's why I've changed the repo name and why I feel like in this case the behaviour of the GitHub Updater is wrong (even though function wise fully understandable):

GitLab has the possibility to "Group" projects under one namespace. This way, several subprojects can be logically bundled together and managed by using such a group. (And I think GitHub has a similar feature too).

The concrete use case is our Happydesk. The project group structure is as follows:

- gitlab.com/happydesk
 - /wordpress
 - /app
 - /web

Nevertheless, the WordPress plugin is still named "happydesk". Any Idea how to solve this?

**Comment by afragen** [comment]
This is how WordPress core works. If you wish to somehow brand your app folders you should probably do something like the following.

* github.com/happydesk (this is the owner of the GitLab repo, the equivalent in the WordPress repo would be wordpress.org/plugins
  * happydesk-wordpress 
  * happydesk-app
  * happydesk-web

This is your plugin slug, all translations and many other things are dependent upon its uniqueness.
