### ISSUE TITLE
folder names dependent on branch switching?

### ISSUE THREAD

**Issue by flashadvocate** [afragen/github-updater#375]
This isn't necessarily an issue, but I have a particular use case that I'm trying to work through and I'm having trouble with it.

We have a single repository with separate branches each housing a separate child theme (so we don't have dozens of individual repos for each child theme). My idea was to leverage the updater to be able to pull a child theme in from a specific branch and have it be able to update.

The problem comes when I need to change the folder the child theme is in when it gets installed (because there could possible be multiple installations of child themes all from the same repo). When I do this, I lose the ability to use branch switching, or to pull from the repo. The option simply goes away.

Is there a flaw in my process? What about being able to specify the folder name when we install a plugin or theme, or is this too finite?

**Comment by afragen** [comment]
The folder matches the slug. As you've discovered changing it breaks things. The code depends upon this relationship. Sorry. 

If you need to install multiple child themes/branches like for a multisite install this won't work. You'll need to make each child theme it's own repo. For a single site install al you would need to do is switch branches. It would always pull in the most recent code.

**Comment by flashadvocate** [comment]
Fair enough. I thought I was on to something but I guess we'll have to
scrap that idea. Oh well. :)

Thanks

**Comment by afragen** [comment]
Sorry :frowning:

**Comment by flashadvocate** [comment]
It's cool. WordPress problem, not an updater problem. :)
