### ISSUE TITLE
update loop

### ISSUE THREAD

**Issue by arniebradfo** [afragen/github-updater#376]
On the themes page when i open my-custom-theme modal:

The theme is being listed as the latest version, 2.1.2, but it still gives me the option to update the theme to 2.1.2.

When I try to update it tells me I've already got the right version(which is true).

I want to be able to use that modal to return to earlier versions of the theme, but that option is now gone.

Not really a showstopping issue but I'd like to be able to roll back the version if i need too.

Thanks,
-James

**Comment by afragen** [comment]
Can you provide a URL for me to look at the repository?

**Comment by afragen** [comment]
Actually, this may have been already fixed in the develop branch. Can you switch and see if the issues persists?

**Comment by arniebradfo** [comment]
Yup. Its fixed in the dev branch. That branch switching setting is very helpful.

The version switching in the theme modal only allows me to switch between branches? I'm only seeing my branches in the dropdown there. I thought I would see the tagged versions.

**Comment by afragen** [comment]
If you have tagged versions you should see them too.

**Comment by arniebradfo** [comment]
They are there now.

Thanks for all your help!
