### ISSUE TITLE
BitBucket deployment keys (feature request)

### ISSUE THREAD

**Issue by robertphipps** [afragen/github-updater#377]
Hi,

I was just looking into setting up your plugin, but in the access management section of my private BitBucket repo for the theme I found an option for Deployment keys - https://confluence.atlassian.com/bitbucket/use-deployment-keys-294486051.html

I couldn't see any reference to these in the readme of the plugin, and using a key rather than making a new account just for the installation probably makes more sense.

Would it be possible to log support for this type of authentication as a feature request?

Cheers.
Rob

**Comment by afragen** [comment]
Unfortunately a Bitbucket deployment key is an SSH key and it isn't the same as an application specific key or an access token like GitHub uses.

As an SSH key it's not usable in this manner.
