### ISSUE TITLE
Unable to get update from GitLab 

### ISSUE THREAD

**Issue by Rowin** [afragen/github-updater#378]
Hello,

I've configured my theme with GitLab headers : 
`GitLab Theme URI: https://git.framasoft.org/Rowin/parade-riposte
GitLab CE: https://git.framasoft.org`

Also add a GitLab CE Private Token. But it doesn't seem to work. When I push new commit with bigger version number (like 0.0.3 instead of 0.0.2), even with a force check, the system still detect my theme as up-to-date. Sometimes, when I manually downgrade my style.css it seems to work, but not every time. 

Additionally, I've got a warning message "You must set a GitLab.com, GitLab CE, or GitLab Enterprise Private Token" even with a private token configured.

Best,

**Comment by afragen** [comment]
Your headers look correct. Can you try re-entering you access token?

Can you go to the themes page after doing a Check Again? I'm not sure why but sometimes after a force recheck it takes an additional page load to show results. Don't continually do a Check Again for this reason.

**Comment by alexjose** [comment]
I am also having the same issue. No Updates are showing for my theme even if the version is incremented. All the headers are correct and no error messages are displayed.

@Rowin The issue with the warning message can be removed by setting the private key in both the 
GitLab.com Private Token and GitLab CE or GitLab Enterprise Private Token fields. I have checked the source and found that the warning will be displayed if any of those two fields are null. This might a  new bug.

**Comment by alexjose** [comment]
@Rowin Please see #380, Opened a new issue for the warning message.

**Comment by afragen** [comment]
I don't have a GitLab CE install to test. Is it possible to post a screenshot of the settings tab. Black out the tokens naturally.

**Comment by Rowin** [comment]
I re-entered my private key several times, but it doesn't seem to work anyway. I even tried to generate a new private key. In fact, update works sometime but it's quite uncertain...
![capture](https://cloud.githubusercontent.com/assets/1727478/14290302/c6798f62-fb5e-11e5-8749-cc89124ccfd4.PNG)

I couldn't try your suggestion, because I've already update my theme to the last version and I'm not on my usual computer, so I cannot push a little modification , just to see.

@alexjose Adding both GitLab CE and GitLab Entreprise Private key do work. Thank you !

**Comment by afragen** [comment]
@Rowin @alexjose there are 2 different private tokens. One for GitLab.com and one for a GitLab CE/Enterprise installation. These tokens are not interchangeable. I think there may be some confusion as the fields to enter these data will only be present if there is a plugin/theme with the correct headers. If there is no GitLab CE header then only the `GitLab.com Private Token` field will be displayed. The same and reverse is true for `GitLab CE or GitLab Enterprise Private Token` field. If you have both types of repositories present then both fields will be displayed and both **need** to be filled in.

Does that make sense?

**Comment by Rowin** [comment]
I understand. However, I have both `GitLab.com Private Token` and `GitLab CE [...] Token` fields displayed, even with only a `GitLab CE` header (I only have one theme/extension using github-updater).

**Comment by alexjose** [comment]
Is there any idea why the updates are not working from GitLab CE?

**Comment by afragen** [comment]
.@Rowin seems to indicate that updates did work after tokens were filled in.

**Comment by alexjose** [comment]
@afragen  the updates are not working for me even after filling the tokens. That will just hide the warning message.

**Comment by afragen** [comment]
@alexjose can you test again with latest develop branch and let me know what any errors are or what isn't working?

**Comment by Rowin** [comment]
>  the updates are not working for me even after filling the tokens. That will just hide the warning message. 

The same for me, sorry for misunderstanding. I'll give a try with the latest branch.

**Comment by afragen** [comment]
Is there any way for someone to let me create an account on their GitLab CE installation so I can test?

**Comment by Rowin** [comment]
You can create an account on the same installation as me : https://git.framasoft.org/public/projects It's a free installation by a french non-profit association.

**Comment by afragen** [comment]
@Rowin thanks.

I was able to create an account and create a test plugin repo.

Using the latest develop branch. I was able to successfully, update, reinstall by switching branches, and install the plugin.

@Rowin and @alexjose - can you try starting over and installing the GitLab CE plugins/themes using the install tab in GitHub Updater?

@Rowin can you give `afragen` `read` access to your theme?

**Comment by alexjose** [comment]
@afragen All good dude. Update works very well. Thank you.

**Comment by Rowin** [comment]
@afragen Updated to latest development version, re-installing the theme using the install tab in GitHub Updater but still not work. I push a little commit with a new version number (0.0.4 instead of 0.0.3), perform a force-check and then load the theme page, but the new version is still not detected.

Additionally, I always had this warning message [#380](https://github.com/afragen/github-updater/issues/380), but now there is just one field (the GitLab CE field) and I filled it.

You now have a read access to my theme.

Thanks ;)

**Comment by afragen** [comment]
@Rowin I was able to install and update your theme without any issues. Can you now do the same?

**Comment by Rowin** [comment]
I try to reinstall my theme an other time via the installation tab of github-updater. It seems to work, but it takes several minutes before the update is detected. Maybe some cache issues !

Thank you for your help !

**Comment by afragen** [comment]
Glad it's working and thanks for pointing me to the error notice issues.
