### ISSUE TITLE
Updates not shown in plugins list, is this normal?

### ISSUE THREAD

**Issue by pingram3541** [afragen/github-updater#379]
First, let me say I love being able to install straight from a repo!  Thank you for this.

Once I have installed one of my plugins which contains the proper header of it's git repo, is it supposed to indicate when there is a new version for update?

The only way I have found to update is by enabling the option to see other branches in this plugin's settings, then I can go back to the plugins list and click on the "try another branch" option, from there I simply click on master and the uninstall then update process executes.

**Comment by afragen** [comment]
Transients are stored for 12 hours. Once an update is detected it will show up in WordPress admin like any other update. Switching between branches won't trigger an update notice. If you want to test, push a version bump then use the Check Again button and check the plugins page. Alternatively you can just decrease the local version number.

**Comment by pingram3541** [comment]
Thanks for the explanation and now know how to push manually without waiting on a cron task,
