### ISSUE TITLE
Showing GitLab private token warning even if it is set.

### ISSUE THREAD

**Issue by alexjose** [afragen/github-updater#380]
I am getting a warning message _"You must set a GitLab.com, GitLab CE, or GitLab Enterprise Private Token"_ even with a private token configured.

**Comment by afragen** [comment]
Do you have both GitLab.com and GitLab CE plugins/themes installed? Can you post a screenshot of the settings tab? Blur the tokens.

**Comment by alexjose** [comment]
![github-issue](https://cloud.githubusercontent.com/assets/194099/14305838/39f48b98-fbde-11e5-9063-4df90b95f4b9.png)

I am only having GitLab CE theme installed. But I am getting both the fields for GitLab.com and GitLab CE keys.

**Comment by afragen** [comment]
That shouldn't happen. I'll test locally and have a fix out soon. 

The error message is generic, but the token field should only show if appropriate.

**Comment by alexjose** [comment]
But the error message is displayed if any of the GitLab key field is empty. I think that too is a mistake.

**Comment by afragen** [comment]
The error message should only show if the appropriate token field is empty or the token is incorrect.

**Comment by afragen** [comment]
I just pushed an update to `develop` that should resolve this issue.

**Comment by alexjose** [comment]
Now only GitLab CE key field is displaying, but still the error message shows up even if the field is filled.

**Comment by afragen** [comment]
Can you try resaving. Then post a pic of the setting tab and the error notice. This shouldn't be happening any more and I can't reproduce it.

**Comment by Rowin** [comment]
Here it is : 
![screenshot from 2016-04-07 23 51 34](https://cloud.githubusercontent.com/assets/1727478/14364884/30a21514-fd0b-11e5-89bc-708601bd7368.png)

**Comment by afragen** [comment]
Can you reinstall GitHub Updater via the branch switch and let me know if anything 'so different?

**Comment by afragen** [comment]
I was able to reproduce locally and just pushed an update to fix. Please let me know if this finally fixes this issue.

**Comment by Rowin** [comment]
It works ! Thank you very much !

**Comment by afragen** [comment]
@alexjose is this now fixed for you too? If so, can you close? Thanks.

**Comment by alexjose** [comment]
This working fine.
