### ISSUE TITLE
Upgrade failed: Plugin update failed. (https://bitbucket.org)

### ISSUE THREAD

**Issue by andruwa13** [afragen/github-updater#382]
Hello, thank you for a job, I have an update error. Previously everything worked (GitHub Updater 5.4.0.6)
[error](https://farm2.staticflickr.com/1626/26221823081_56d734100b_o.png)

**Comment by afragen** [comment]
Can you translate error that into English?

**Comment by andruwa13** [comment]
- Upgrade failed: Plugin update failed
- Yes but we have a private repository
I send your e-mail login and password link ok?

**Comment by afragen** [comment]
Can you just give `read` access to `afragen`?

**Comment by afragen** [comment]
If you try updating from the update-core.php page you might get a more descriptive error message.

**Comment by andruwa13** [comment]
ok, https://webakcent_pro@bitbucket.org/webakcent/rwp-role.git

**Comment by afragen** [comment]
Try changing you header to
`Bitbucket Plugin URI: https://bitbucket.org/webakcent/rwp-role`

**Comment by andruwa13** [comment]
Not work. Download failed. Too many redirects. :(

**Comment by afragen** [comment]
I was just able to install and update your plugin. Have you fixed the local plugin's headers as above?

**Comment by andruwa13** [comment]
- yes, update fixed local and repo. not work.

- I tried to install the plugin, the same error [1](https://farm2.staticflickr.com/1492/26200895502_8497a5f9ee_o.png) [2](https://farm2.staticflickr.com/1459/26200896272_01a3749d60_o.png)

**Comment by afragen** [comment]
Can you re-save your Bitbucket username/password in the Settings tab and try again.

Here's what happened for me.
![screenshot_01](https://cloud.githubusercontent.com/assets/1296790/14361673/db112734-fcb0-11e5-85d3-a65f61c2516f.png)
![screenshot_02](https://cloud.githubusercontent.com/assets/1296790/14361678/e06b6172-fcb0-11e5-932b-8c37def45c83.png)

**Comment by andruwa13** [comment]
I understand where the error is, you now need to enter your login (e-mail) and before I entered username. Previously worked with the username. thank you very much

**Comment by afragen** [comment]
It should work with your username.

**Comment by andruwa13** [comment]
I set for e-mail, updates

**Comment by rjksn** [comment]
I'll second that the username does not work with Bitbucket, not sure why. 

(I shared the plugin with an extra update specific user, so not sure if that changes things)

**Comment by afragen** [comment]
Does this happen in all cases? I cannot reproduce as username works for me.

Are you sure the email and username aren't the same?

**Comment by rjksn** [comment]
This is the first time I've used this so I can't say more than I got a too many redirects on trying to install a plugin for the first time (using a new BitBucket user, who's not the repo owner). Until I changed the username to the email and it worked right away. 

The username is rjksn-updater, and the email address is ryan+updater@example.com, so the username and the email address definitely are not the same (account was created today for this).

On the bitbucket.org website, trying to log in as the new user, by "username", I receive an error on the site, while for my older account I can still log in via the username (rjksn).

> You must use your email address when authenticating with your Atlassian account.

The email works in all my accounts, so maybe just changing it to the email address, as opposed to the username would be sufficient in solving problems like mine. :)

**Comment by rjksn** [comment]
PS: While I haven't done much with this plugin, I just want to thank you for creating it.

**Comment by afragen** [comment]
> On the bitbucket.org website, trying to log in as the new user, by "username", I receive an error on the site, while for my older account I can still log in via the username (rjksn).

That's very odd. But I guess I would expect the plugin's Basic Auth to fail if you can't log in to bitbucket.org with the username. I wonder if it has anything to do with newer accounts?

I'll close because it seems like a Bitbucket issue.

And you're welcome.
