### ISSUE TITLE
Does the Github Updater use WordPress's HTTP API for the auto-updates?

### ISSUE THREAD

**Issue by ArchitectforBusiness** [afragen/github-updater#383]
Just checking so I can see if it should be compatible with MainWP's WordPress site management plugin.

**Comment by afragen** [comment]
It is entirely hooked into WordPress core update functions. You might need to check one of the other options under the Remote Management tab. 

If it works with MainWP please let me know and let me know what settings you used so I may officially support it.

**Comment by ArchitectforBusiness** [comment]
Hi Andy,

I reached out to MainWP and got this response:

The issue that we are running into is that the Github Updater is the plugin detecting the updates on your premium. MainWP can not read the update from Github Updater.  

More then likely a specific Extension will need to be made for Github Updater.

Does this sound accurate? Thanks for your help.

Steven Walsh
Architect for Business





architectforbusiness.com
steve@architectforbusiness.com
(860) 510-9328

**Comment by afragen** [comment]
GitHub Updater detects its updates and adds them into the appropriate WordPress option. This is exactly how WordPress itself works. 

InfiniteWP, iThemes Sync, and ManageWP are all able to pick up the updates. The only exception is ManageWP doesn't "see" updates to child themes. 

I haven't looked at MainWP but they must pick up the site_update_transient before GitHub Updater has a chance to run. I don't really know.

**Comment by afragen** [comment]
MainWP support now working but needs next update to MainWP child plugin.
