### ISSUE TITLE
Fatal error: Cannot use object of type stdClass as array in /github-updater/src/GitHub_Updater/Base.php on line 824

### ISSUE THREAD

**Issue by charli-polo** [afragen/github-updater#385]
I get this error on a regular basis since the update to 5.4.0 (when accessing the backoffice). The error is not triggerred immediately and seems somehow related to the readme.txt files of the plugins installed with github updated.

**Comment by afragen** [comment]
This is likely because the readme.txt file is not valid. Do you have an example that I can use to test with?

**Comment by afragen** [comment]
@charli-polo can you change the following line, https://github.com/afragen/github-updater/blob/master/src/GitHub_Updater/Readme_Parser.php#L38

to 
```php
return (array) $this->parse_readme_contents( $file_contents );
```

and let me know if the error is fixed?

**Comment by charli-polo** [comment]
It seems indeed to have solved the problem.
I'll check if the error is not triggered in the coming days.

**Comment by afragen** [comment]
I'll add that fix to the develop branch, it should be released next week. Thanks for confirming.
