### ISSUE TITLE
Standalone version in a single file?

### ISSUE THREAD

**Issue by hrsetyono** [afragen/github-updater#386]
Hi, I was wondering whether I can implement just the core functionality (notify, show changelog, and download update) in one single file?

I would love to use this, but I don't want to add one more plugin.

I found some code here https://github.com/radishconcepts/WordPress-GitHub-Plugin-Updater but it doesn't use Github Tag to check version and no changelog.

Thanks

**Comment by afragen** [comment]
There's no way to convert this plugin into a single file framework.

I'm not quite certain of your reticence to add a plugin, especially one whose code you can review here before installing.

**Comment by hrsetyono** [comment]
Thanks for the reply.

The main reason why I don't want to add more plugin is because when I distribute it, I must include this updater plugin too. Which is fine but will be much better if it's just one plugin.

**Comment by afragen** [comment]
I do have a framework for installation of plugin dependencies. 

https://github.com/afragen/wp-dependency-installer

With it your user will get a notice and a single click installation/activation of any plugin.
