### ISSUE TITLE
Not a issue, search help to create a install plugin from Github

### ISSUE THREAD

**Issue by onigetoc** [afragen/github-updater#390]
I did a Wordpress plugin to search Wordpress plugins, Themes and Widget on Github.
[WPGIT](https://github.com/onigetoc/wpgit)
Visit [wpgit.org](http://wpgit.org/) to see a front end demo similar to the backend WPGIT plugin.

I need help to create a simple remote install from the Github zip file.
Any idea?
![wpgit](https://cloud.githubusercontent.com/assets/47570/13083379/bfc15c00-d4a2-11e5-9f93-54897015bc40.gif)

**Comment by afragen** [comment]
You should take a look the Install class, but for a simpler model you should take a look at https://github.com/afragen/wp-dependency-installer

It should give you a simpler look at installing something from GitHub.

**Comment by onigetoc** [comment]
Thank you, it's a good start, i will investigate.
