### ISSUE TITLE
Plugin updates to old version

### ISSUE THREAD

**Issue by richardblythe** [afragen/github-updater#391]
First off, let me say that I absolutely love this plugin!  I'd give it 10 stars if I could.

However, I am having difficulty updating my Github based plugin to the new version.  Github-Updater correctly identifies that there is a newer version.  But when I run the update, it rolls my plugin back to version 1.8.0. (see attachments)  Is this a bug or am I doing something wrong here?

![update-plugins-1](https://cloud.githubusercontent.com/assets/18535927/14864146/a0016182-0c86-11e6-9484-481e20d698b6.jpg)

![update-plugins-2](https://cloud.githubusercontent.com/assets/18535927/14864156/a8d986f4-0c86-11e6-941f-09a2b78df1d2.jpg)

![update-plugins-3](https://cloud.githubusercontent.com/assets/18535927/14864222/f8b09636-0c86-11e6-99d0-81a52a1108d3.jpg)

**Comment by afragen** [comment]
Looks like you've forgotten to tag the release. I just did that myself with 5.4.1.

Once you start tagging releases you must continue. If you've ever tagged a release updating the master branch will always use the latest tag regardless of the version number. Tagging releases is optional, but if you start you can't stop.

And thanks.

**Comment by richardblythe** [comment]
> ...Tagging releases is optional, but if you start you can't stop

That stinks!  Although I understand why GitHub enforces this rule.  Thanks for your contribution to the WordPress community!

**Comment by afragen** [comment]
You can always just delete all the tags for the repo on GitHub.
http://thefragens.com/2014/04/delete-tag-github/

**Comment by richardblythe** [comment]
That's good to know!  I'm new to the Github community but I'm blown away by
the possibilities of git.  Still undecided on doing version control for my
client themes.

My next goal is to learn about composer.

**Comment by afragen** [comment]
Version control everything, no harm, great rewards. :100:
