### ISSUE TITLE
SSL certificate problem: self signed certificate in Gitlab

### ISSUE THREAD

**Issue by mostafasoufi** [afragen/github-updater#392]
@afragen I get this error in the dashboard. How can disable ssl in the plugin?

Regards

**Comment by afragen** [comment]
Can you provide a screenshot? I can't reproduce this.

**Comment by mostafasoufi** [comment]
![434343](https://cloud.githubusercontent.com/assets/701520/15096533/4544e2ca-1512-11e6-9f82-43f0253c4375.png)
Showing in the: /wp-admin/plugins.php

Regards

**Comment by afragen** [comment]
Sorry, I just introduced the notice to display any WP_Error code that might show during the wp_remote_get process. This error comes from the server that GHU is attempting to download information. This is really a safety thing as we should encourage use of SSL certs, especially as Let's Encypt offers them for free. I assume this must be from a plugin/theme in a self hosted git server.

You should be able to override this by changing the code in `class API` on line 54.

A better way would be to add something like the following to functions.php

```php
add_action( 'http_request_args', function( $args ) {
$args['sslverify'] = false;
return $args;
});
```
You might have to fiddle with the priority a bit.

All of the above considered, you should seek to find which server is using a self-signed certificate and try to fix that.

**Comment by mostafasoufi** [comment]
Thanks for it, i'll check it :)

**Comment by mostafasoufi** [comment]
**It's work!**
thanks @afragen.
