### ISSUE TITLE
Specify plugin path, ignore files?

### ISSUE THREAD

**Issue by pingram3541** [afragen/github-updater#393]
Often a project may contain multiple compile sources not needed in the installed plugin.  Is it possible to specify a git ignore set or point the updater to a specific path within a branch?

If not, is this a viable feature request to add path and ignore headers?

For example: gituser/myproject/
(we don't want any of this)
/compile.abc
/other.src
/README.MD
/some-other-sub-folder/
...
(we want this however)
gituser/myproject/mypluginfolder <--- this is the where plugin we want to install resides
/mypluginfolder/myplugin.php
/mypluginfolder/uninstall.php
/mypluginfolder/readme.txt
...

**Comment by afragen** [comment]
This is what a `gitattributes` file is for. As an example, see the one included with this project.

**Comment by pingram3541** [comment]
Ok but but the actual plugin needs to remain in the root of the repo?

**Comment by afragen** [comment]
That shouldn't be a problem. Just specify which files you don't want included. All you have to do is download the repo to see if your settings are correct.

If you share the repo URI I could make more specific recommendations.

**Comment by afragen** [comment]
Yes, main plugin file must be at root level of the repo.

**Comment by pingram3541** [comment]
Got it, so curious if this is still something to consider for a feature request, for those of us that have projects that may be larger than just the wp plugin...where different plugins for different platforms may be located within sub-folders of our repo?  Is this considered bad practice and each plugin should be its own repo even though they are for the same product, for example, take the ever popular Revolution Slider where there is a js only version, a wp version, possibly even a joomla version.

I also noticed that the plugin folder uses the repo name.  If we had a "path" header maybe that final "path" folder would be used for the name which would allow us to have a more customized repo name.

**Comment by afragen** [comment]
I'm really just modeling how the .org repo functions. One plugin per repo. It does make organization simpler. 

If you have several plugins in one repo, how would you update only one of them. How do you activate a plugin in subfolders?

If you're having dependency issues you could take a look at `afragen/wp-dependency-installer`. It's a single class that loads plugin dependencies from a JSON config file. 

Overall the paradigm is one plugin, one repo.

**Comment by pingram3541** [comment]
Good points.  Seems I may need to submit to using a more simpler approach by using individual repo's for each module.

> If you have several plugins in one repo, how would you update only one of them.

Essentially all of them are updated even though some may reflect no actual difference within a specific module, no harm no foul if it gets updated - it's just a version change, but so far haven't run into this in the early stages of my project and it keeps all versions the same for simplicity.

> How do you activate a plugin in subfolders?

The wp plugin exists in a sub folder that could be referenced via a root file with the appropriate path rule (similar to .gitattributes).  The plugin would install on the wp site just like any other, /wp-plugin-url/my-plugin-folder/my-root-plugin-file.php.  The Git Updater plugin would know the version and repo url via the headers just the same as any other, but recognize the special path rule of where to install/update from.
