### ISSUE TITLE
Develop branch renamed master after an hotfix (git-flow)

### ISSUE THREAD

**Issue by benoitchantre** [afragen/github-updater#394]
If you have 2 branches (e.g. *master* and *develop*) and you add the branch name in the banner, you will have a misnamed branch after an [hotfix](http://danielkummer.github.io/git-flow-cheatsheet/#hotfixes).

The develop branch will have `GitHub Branch: master` instead of `GitHub Branch: develop`

Is there a way to prevent that?

**Comment by afragen** [comment]
You just need to ensure that in your merge you don't merge the line changing the branch designation. Been there, done that. Many times. Most of the time I catch it but sometimes I need another commit to switch it back.

**Comment by benoitchantre** [comment]
Ok, thanks

**Comment by afragen** [comment]
You're welcome. Unfortunately it's just something to consciously remember.
