### ISSUE TITLE
Version number recognition 1.1.2 vs 1.2.0

### ISSUE THREAD

**Issue by vc27** [afragen/github-updater#395]
The system only seems to want to recognize there is an update when a minor version number increments. I'm positive I'm not using tagging in my commits. Any ideas? btw, this plugin is awesome! and your code is supper clean, way to go!

##### My env:
- WordPress 4.5.2
- Twenty Fifteen theme
- Active plugins: GitHub Updater, All My Web Needs - Branding
- https://github.com/kizinko/all-my-web-needs-admin-branding

**Comment by afragen** [comment]
Thanks. I think you might be running into the fact that transients are stored for 12 hours. You can delete the transients by using the 'Check Again' button in the core update page. Alternatively you can simply decrease the version number locally. 

I commonly use a 4th place for development testing, major.minor.patch.dev

Try the above and let me know if that works.

**Comment by vc27** [comment]
Oh! The 12hr transient is exactly what I was inadvertently looking for! I ended up using the "Check Again" button to get it to recognize the version change. This is good news, I was on track!

I probably wont be able to look at this again today, but I will definitly check back! Thanks!

**Comment by afragen** [comment]
Glad you're on track. Let me know if there's anything else I can help with, if not just close out his issue. Thanks.
