### ISSUE TITLE
Renamed plugin directory after update

### ISSUE THREAD

**Issue by mostafasoufi** [afragen/github-updater#396]
Hello @afragen,

After update with github updater, the directory of plugin is renamed.

for example:
`test` to `gitlab-m.soufi-test`

Regards

**Comment by afragen** [comment]
Can you share the URI of the repo so that I may test?

**Comment by afragen** [comment]
Do you have `define( GITHUB_UPDATER_EXTENDED_NAMING, true );` in your wp-config.php?

**Comment by mostafasoufi** [comment]
Oh! Yes. i enabled this define.
Resolve after disable `Extended Naming`

Thanks @afragen
