### ISSUE TITLE
Fatal error: Cannot use object of type stdClass as array in /src/GitHub_Updater/Base.php on line 863

### ISSUE THREAD

**Issue by charli-polo** [afragen/github-updater#398]
Same kind of error than last time. (https://github.com/afragen/github-updater/issues/385)
Sorry my check wasn't complete.

**Comment by afragen** [comment]
What version number are you currently using?

**Comment by charli-polo** [comment]
5.4.1

It might be an issue with some information previously written to the
database... I tried deleting and re installing github updater and deleting
some transients, but it didn't helped...

Charlie

2016-05-24 14:44 GMT+02:00 Andy Fragen <notifications@github.com>:

**Comment by afragen** [comment]
This is likely due to a malformed readme.txt file. If you know what plugin it's associated with can you send me the URI so I can test?

**Comment by afragen** [comment]
Can you use the branch switching and switch to the `develop` branch and see if the error persists? If it does, can you send a list of the plugins you are using GitHub Updater with? Perhaps we can narrow the plugin down so that I may use it to test locally.

**Comment by charli-polo** [comment]
Hi @afragen 
Thx for your quick answer and sorry I could not follow up immediately.

I enabled branch switching, but for some reason I cannot switch branch for github updater (I can for other plugins in the extension page). So I downloaded the branch and re-installed the plugin.

I get this error:
Fatal error: Cannot use object of type stdClass as array in wp-content/plugins/github-updater-develop/src/GitHub_Updater/Base.php on line 901

I know what plugin readme file is causing the error. It's a private plugin I made, hosted on gitlab.
PLease find attached the readme.text. I also have a README.md and CHANGES.md but I don't think they matter.
[md files.zip](https://github.com/afragen/github-updater/files/283741/md.files.zip)
[readme.txt](https://github.com/afragen/github-updater/files/283740/readme.txt)

Please tell me if I can help you further, I'll be happy to.

**Comment by afragen** [comment]
This should be fixed now, https://github.com/afragen/github-updater/commit/40dfff88389781881d1f8b4a0b6a9cadf021c43f

Thanks. It will be in next release.

**Comment by charli-polo** [comment]
You rock !
