### ISSUE TITLE
GitHub Updater Error Code: 401 There is probably an access token or password error on the GitHub Updater Settings page

### ISSUE THREAD

**Issue by BjornW** [afragen/github-updater#399]
This message causes confusion if someone is using the plugin solely with other version control platforms such as Bitbucket or Gitlab. Perhaps this message should be explained in a bit more detail, something along the line of: 

"GitHub Updater Error Code 401: You have probably a plugin installed which needs a connection to Github, but at the moment it is probably lacking an access token or password. Keep in mind that github-updater is a plugin in itself and needs a connection to Github in order to check for new updates"

**Comment by afragen** [comment]
401 error isn't the same as the 403 for hitting the GitHub API limit.

401 is when a Bitbucket user/pass isn't entered or is incorrect, or a when a Bitbucket private repo doesn't have a checked box.

401 is when an access token isn't present for a GitHub private repo, any GitLab repo, or most enterprise installs.

**Comment by afragen** [comment]
The README has more detail :wink:

**Comment by timothyjensen** [comment]
>when a Bitbucket private repo doesn't have a checked box.

This is what was causing the error notice for me.  Thanks for pointing that out, Andy.

**Comment by afragen** [comment]
Wiki now contains all this info. 

https://github.com/afragen/github-updater/wiki/Messages
