### ISSUE TITLE
RESTful updates

### ISSUE THREAD

**Issue by afragen** [afragen/github-updater#402]
@limikael I did some simplification of the checks, there's really no need for 
`isset( $_REQUEST['some_value'] ) && $_REQUEST['some_value']` 
the initial `isset` does the work. 😉 

I added an endpoint, **updates**. This will show the available updates.

```
$ curl "http://test.dev/wp-admin/admin-ajax.php?action=github-updater-update&key=4e361c406e1903a49d2f05e93fc622fe&updates"
{
    "messages": "Available Updates",
    "plugins": [
        {
            "plugin": "easy-digital-downloads",
            "new_version": "2.5.17"
        },
        {
            "plugin": "plugin-noheader",
            "new_version": "1.0"
        },
        {
            "plugin": "test-bitbucket-plugin",
            "new_version": "0.3.3"
        },
        {
            "plugin": "test-plugin-gitlab-ce",
            "new_version": "0.1.0"
        }
    ],
    "themes": [
        {
            "theme": "theme-noheader",
            "new_version": "1.0"
        }
    ],
    "success": true
```

Might as well stay in CLI and give updated information. 👍 

I also updated the README, etc as I was in error previously by saying this was using the REST API. It's really using RESTful endpoints.

Let me know what you think. It's in latest `develop`

**Comment by afragen** [comment]
I also add a button to reset the RESTful API key. 👍

**Comment by limikael** [comment]
Hi @afragen, I think this is awesome!

**Comment by limikael** [comment]
Hm, maybe there could be a way of listing all managed plugin and themes, with a status code if they need updating or not. Not sure why it would be needed, it doesn't exactly solve a concrete problem that exists, but it's more a feeling that it would be nice to have for the sake of consistency. Maybe something like:

(This is not something implemented, I hand edited your response to illustrate)

```
$ curl "http://test.dev/wp-admin/admin-ajax.php?action=github-updater-update&key=4e361c406e1903a49d2f05e93fc622fe&list"
{
    "messages": "Available Updates",
    "plugins": [
        {
            "plugin": "easy-digital-downloads",
            "current_version": "2.5.17",
            "new_version": "2.5.17",
            "status": "up_to_date"
        },
        {
            "plugin": "plugin-noheader",
            "current_version": "1.0",
            "new_version": "1.0",
            "status": "up_to_date"
        },
        {
            "plugin": "test-bitbucket-plugin",
            "current_version": "0.3.2",
            "new_version": "0.3.3",
            "status": "update_available"
        },
        {
            "plugin": "test-plugin-gitlab-ce",
            "current_version": "0.0.9",
            "new_version": "0.1.0",
            "status": "update_available"
        }
    ],
    "themes": [
        {
            "theme": "theme-noheader",
            "new_version": "1.0",
            "current_version": "1.0",
            "status": "up_to_date"
        }
    ],
    "success": true

**Comment by limikael** [comment]
Is there some functionality that should be added for this to be considered to be implemented? Just wondering since the issue is still open...

**Comment by afragen** [comment]
I haven't decided yet whether I'm even going to take the `&updates` out. It's only useful for someone sitting in front of the CLI. Not exactly what this feature was designed for.

**Comment by limikael** [comment]
No it is also useful for creating an external system that can check which updates are available or so. Don't know what kind of external system exactly, but this is something one cannot predict, people are creative you know... :) I think it should be there.

**Comment by afragen** [comment]
Just added `branch` which will show the current installed branch and `branches` which will show an array of all available branches.

I don't think listing every installed plugin/theme is a good idea. I think there's currently enough data passed in `&updates` for a developer to create all kinds of things. If there's a specific need we can revisit this.
