### ISSUE TITLE
Undefined properties: stdClass::$pushed_at, stdClass::$watchers, stdClass::$private

### ISSUE THREAD

**Issue by noahkuhn** [afragen/github-updater#403]
After a recent update, I'm getting some PHP errors on local websites. This happens on several sites. I have WP_DEBUG set as true. I have also placed my github.com access token in the settings.

WordPress 4.5.2, Github Updater 5.4.1.13

Any thoughts?

Notice: Undefined property: stdClass::$pushed_at in /Users/xxx/Sites/xxxxx.com/wp-content/plugins/github-updater/src/GitHub_Updater/GitHub_API.php on line 417

Notice: Undefined property: stdClass::$watchers in /Users/xxx/Sites/xxxxx.com/wp-content/plugins/github-updater/src/GitHub_Updater/GitHub_API.php on line 418

Notice: Undefined property: stdClass::$private in /Users/xxx/Sites/xxxxx.com/wp-content/plugins/github-updater/src/GitHub_Updater/GitHub_API.php on line 419

**Comment by afragen** [comment]
I've seen this but only intermittently and can't reproduce reliably. I do have a couple of checks in place so it shouldn't really happen, but I'd like to know how the code gets there. 

If you can give steps to reproduce, I'm sure I can squish it.

**Comment by afragen** [comment]
I think I've been able to reproduce this and it's a bit crazy as it would only show until the transients are cleared the first time.

Here's the breakdown. I changed how I stored the repo meta from 5.4.1 to develop. Consequently if you switch from master to develop you will encounter this error, but only for a 12 hours or so.

I think I've gotten this solved. Please let me know if the next update to develop doesn't fix the issue.

https://github.com/afragen/github-updater/commit/cd0f0dd969fb894ac1510227435fffba01cfd3ec

**Comment by noahkuhn** [comment]
I was only using the develop branch, but it does appear to go away after 12 hours (plus or minus), so it must be the same issue. Thanks for running this down!
