### ISSUE TITLE
500 Error on /wp-admin/themes.php

### ISSUE THREAD

**Issue by miguelgaton** [afragen/github-updater#404]
Hello,

After updating github updater I get this 500 error on /wp-admin/themes.php

PHP Fatal error:  Call to undefined method Fragen\\GitHub_Updater\\Theme::get_theme_update_url() in /website/wp-content/plugins/github-updater/src/GitHub_Updater/Theme.php on line 566

Could you check and fix it?

Regards,

**Comment by afragen** [comment]
Absolutely, sorry.

**Comment by afragen** [comment]
fixed, https://github.com/afragen/github-updater/commit/1b0a8300859283e18a079c77236e0d49b3906c98
