### ISSUE TITLE
Github Updater's master branch on version 5.4.1.16, but latest release is 5.4.1, causing update loop.

### ISSUE THREAD

**Issue by curtisbelt** [afragen/github-updater#406]
I had this same problem with a private plugin of mine. If the version of branch is higher than the latest release, it causes an update loop.

This is due to conflicting logic between the "when is update available" logic and the "what to download" logic. If download logic will only use latest release, the update available logic should be checking latest release to compare.

**Comment by afragen** [comment]
The master branch is at 5.4.1, the develop branch is at 5.4.1.16.

**Comment by curtisbelt** [comment]
Ah my mistake. Apparently the bug he was in branch switching. I can't seem to reproduce it now, but the plugin was set to master branch, and was giving me an update alert "You have version 5.4.1 installed. Update to 5.4.1.16". So I assumed master was 5.4.1.16 since I know it was on master.

Switching branch to dev then back to master made it go away.
