### ISSUE TITLE
Incorrect branch name displaying

### ISSUE THREAD

**Issue by curtisbelt** [afragen/github-updater#408]
github-updater dev branch, 5.4.1.16.
Branch switching: On
Private GitHub API keys are entered

On the plugins page, under **My Plugin A** it says:

> Current branch is `master`, try another branch.

I'll click "another branch" and select dev.

It successfully updates, and it downloads the dev branch correctly.

Return to plugins page, still says

> Current branch is `master`, try another branch.

So functionally it's working but the branch name could cause problems if I forget what branch I really had it on.

I noticed this bug does not occur on the Github Updater plugin.

Let me know if you want to see anything from the plugin. I'm not specifying a branch in the plugin headers.

**Comment by afragen** [comment]
This data is pulled from the `GitHub Branch` header. Sometimes when we create new branches we are guilty of not correctly updating this for the new branch. I know I've done this on more than one occasion.

Please check and let me know. If it's still an issue can you point be to the repo with the issue?
Thanks.

**Comment by curtisbelt** [comment]
I do not have Github Branch specified at all, is it a required field? Keep it updated accordingly in the branches?

**Comment by afragen** [comment]
If not specified it defaults to `master`. It's not required for the master branch but if you want to update against another branch it is required. It's also required to show the correct _current branch_ for the branch switch.

As you've noticed branch switching will work regardless, but that bit of info is incorrect.

**Comment by curtisbelt** [comment]
Ah I see. Thank you! And thank you for your work on the plugin in general.
