### ISSUE TITLE
Internal server error with private Bitbucket Accounts

### ISSUE THREAD

**Issue by adowdle** [afragen/github-updater#410]
Some time this week, all of my private Bitbucket repos stopped working; I am able to install from public repos. Here is the error message I get: 

Downloading install package from https://bitbucket.org/adowdle/as-calendar/get/master.zip…

Download failed. INTERNAL SERVER ERROR

**Comment by afragen** [comment]
Hmm, nothing's changed recently in that code and the error is on Bitbucket's side. I've checked and I can still install a private repo from Bitbucket.

Are you certain your Bitbucket user has `read` access to the repo?

**Comment by adowdle** [comment]
I had been using a read-only account for installing plugins/themes; looks like Atlassian had temporarily locked it until I went through the account migration process that rolled out recently.

**Comment by afragen** [comment]
Glad it's now working.
