### ISSUE TITLE
Always Display The Branch Switcher

### ISSUE THREAD

**Issue by ahmadawais** [afragen/github-updater#411]
Thanks for this amazing plugin. I face a lot of issues with updates and mostly I rely on updating plugins by just reinstalling the same version via branch switching. It works perfect but for themes the branch switching is not always displayed even if I have enabled branch switching. 

Can you look into it?

**Comment by afragen** [comment]
I'm going to need more information. I've never seen this. 

Does this happen all the time or just with specific themes?

**Comment by ahmadawais** [comment]
@afragen It happens all the time. There's a pattern. 

Let's say I installed `XYZ Theme` and then went to `Appearance > Themes > XYZ THEME` and in the branch switcher, I just applied the master branch and installed it again (Since many times the features do not warrant a version change). The new master branch was applied, all good. Now after this update when I go to apply the master branch again there is no `select` element for selecting a branch. And the plugin somehow considers that there is an update while there is none.

![](https://i.imgur.com/srZgm4R.png)

Installed and update version both are `1.0.0` How is that possible? And where is the branch selector now? It's gone.

Here's what I'd love to have. A settings page with all the themes and plugins that can be updated by GitHub Updater. That page should have option buttons like <kbd>UPDATE</kbd>(In case I know there is an update) <kbd>ReInstall</kbd> (If everything fails, this button will delete the old code and will replace it with the new one from the specified branch)

This would dramatically improve my workflow. Instead of updating versions, checking for them, and waiting for them to be available, I will just click a new <kbd>ReInstall </kbd> button and voila! 

Looking forward!

**Comment by afragen** [comment]
Can you provide a URL for me to test against?  

If it's a private repo can you give `read` access to `afragen`?

**Comment by ahmadawais** [comment]
@afragen I am not at liberty to share this repo, it's a client project. But did you read the last part? If only there can be a reinstall button it would do great. Just like the roll back plugin just not rolling back but installing the same version over and over again.

**Comment by afragen** [comment]
Reinstall is exactly what branch switch to same branch does. My problem is that I can't replicate your issue. 

Branch switch won't be present if update is showing, otherwise it should. 

How many different branches are present in repo?

Occasionally I've seen where branch switch fails with message if "theme is up to date". Same thing occasionally happens with plugins but I don't know how to fix it. Perseverance usually pays off. 

Have you tried the `develop` branch? It has a new feature under Remote Management for a RESTful endpoint to update. This might work better for you.

**Comment by ahmadawais** [comment]
There!!!
`Branch switch won't be present if update is showing, otherwise it should.`
Can you remove this functionality? I want the branch switching to be present all the time. Coz, for some reason this plugin is not reading the version right. I tried the latest `develop` version and it sometimes says that an update is present with version `0.0.0` wonder how that happens. 

Only if I can have branch switching available all the time irrespective of any condition.

**Comment by afragen** [comment]
Without access to your theme I'm not sure I can do any additional debugging.

**Comment by ahmadawais** [comment]
@afragen I am using my [WPGulp](https://github.com/ahmadawais/WPGulp) workflow. You can test it with this [dummy theme](https://github.com/ahmadawais/WPGulpTheme).

But besides that, can you build a settings page where all themes and plugins could be listed and reinstalled by a single click?

**Comment by afragen** [comment]
I was able to install WPGulpTheme and switch branches successfully. Is it possible for you to show me the headers for the theme you're working on?

As branch switching will perform a re-install I'm not going to create a new single click page.

You might try looking at the `develop` branch and see if the RESTful updates (which does a reinstall) suits your needs. Look in the README and under the Remote Management tab.

**Comment by ahmadawais** [comment]
@afragen Thanks a lot for caring about solving this problem.

Here's the child theme's header

```
/**
 * Theme Name:   Writable Child
 * Theme URI:    http://ahmadawais.com/
 * Description:  Writable Child Theme
 * Author:       Ahmad Awais
 * Author URI:   http://ahmadawais.com/
 * Template:     writablewp
 * Version:      1.0.0
 */
````
And here is the theme's header

```
/*!
Theme Name: Writable
Theme URI: http://WPTie.com/
Author: WPTie, mrahmadawais
Author URI: http://WPTie.com/
Description: Writable is a personal blogging theme.
Version: 1.0.0
License: GPLv2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html
Tags:  grid, personal
Bitbucket Theme URI: https://bitbucket.org/company/repo

*/

```

I will take a look at the RESTful endpoints.

**Comment by afragen** [comment]
I think you'll like this, https://github.com/afragen/github-updater/commit/88016116747a9119672222b4c960350abfea045d

If you are using GHU for both parent and child theme, both will need appropriate headers.

If you are developing on a branch, will need the `Bitbucket Branch` or `GitHub Branch` header.
If you are developing on `master` the branch header is not needed but tagging and developing will get confusing.

**Comment by ahmadawais** [comment]
@afragen Thanks for the update! It fixed the problem. Now I can easily update and see the branch switching panel even after the update. 

I am just updating the Parent theme not the child one which is why there is nothing inside the child theme's header. Also I am using master branch that's why I ignored the branch tag. I hope it is the right way to go about it.

**Comment by afragen** [comment]
@ahmadawais I'm glad it's working for you. You can/should use it however it works best.

Just for fun you could try creating a  webhook that sends to the appropriate RESTful endpoint and perhaps you can have automatic updates with to the client. I haven't tested but it seems possible.

**Comment by ahmadawais** [comment]
@afragen Thanks.

>Just for fun you could try creating a webhook that sends to the appropriate RESTful endpoint and perhaps you can have automatic updates with to the client. I haven't tested but it seems possible.

Was thinking along the same lines. I will try it after completing the current project, way too jammed up!

**Comment by afragen** [comment]
Let me know how it goes.

**Comment by ahmadawais** [comment]
Sure!
