### ISSUE TITLE
Update theme by REST from Bitbucket create new folder

### ISSUE THREAD

**Issue by shvlv** [afragen/github-updater#412]
When I change theme version and update from Worpress dashboard it's work perfectly but when I use Bitbucket's webhook and REST, theme install in new folder with name `user-repository-hash`. Maybe it related with [this issue](https://bitbucket.org/site/master/issues/3486/file-name-when-downloading-a-tag). But standart update work normal.

Thank for your plugin. Very helpful for developer!

**Comment by afragen** [comment]
Can you describe precisely how you updated using the Bitbucket webhook? Can you give an example to the webhook URL?

**Comment by shvlv** [comment]
In Bitbucket Settings->INTEGRATIONS->Webhooks I create Webhook that triggered after repository push. Example URL: `http://xxxx.xx/wp-admin/admin-ajax.php?action=github-updater-update&key=xxx&theme=xxx`.

I get normal response:
`{
  "messages": [
    "Downloading update from <span class=\"code\">https://bitbucket.org/shvlv/xxx/get/master.zip</span>&#8230;",
    "Unpacking the update&#8230;",
    "Installing the latest version&#8230;",
    "Enabling Maintenance mode&#8230;",
    "Removing the old version of the theme&#8230;",
    "Disabling Maintenance mode&#8230;",
    "Theme updated successfully."
  ],
  "success": true
}`

This behavior almost feature :), and I can active theme with recent commit but annoy when reset theme_mod: menus, widgets etc.

**Comment by afragen** [comment]
If you use the RESTful update from the CLI without going through a webhook is the renaming correct?

`curl "http://xxxx.xx/wp-admin/admin-ajax.php?action=github-updater-update&key=xxx&theme=xxx"`

**Comment by afragen** [comment]
I have not tried using the RESTful update in this manner. That's very clever.

Renaming should work correctly and I wonder if something about calling the update URL is skipping something.

**Comment by shvlv** [comment]
Sorry for delay.

I try using CLI in proposed way, but result not changed. First time original theme is replaced new folder, after other update plugin create new folder and activate new theme (folder name and theme slug `user-repository-hash`).

**Comment by afragen** [comment]
Unfortunately I can't replicate this. What version number are you using?

**Comment by afragen** [comment]
I was able to set up a webhook from A Bitbucket repo and use the RESTful endpoint to update. It didn't seem to work all the time, even though the payload result indicated it was successful.

I will say that when it did work the renaming was successful so I can't replicate your issue.

**Comment by shvlv** [comment]
I update plugin to latest version 5.5.0.7 from 5.4.1.19 and it work well.
Thank.
