### ISSUE TITLE
Continual 403 Error

### ISSUE THREAD

**Issue by psasser** [afragen/github-updater#413]
I keep seeing a 403 error in the header of my admin...

GitHub Updater Error Code: 403	
GitHub API's rate limit will reset in 29 minutes.
It looks like you are running into GitHub API rate limits. Be sure and configure a Personal Access Token to avoid this issue.

I'm not using GitHub only BitBucket.  So is this error related to BitBucket?  Is there something I need to do to get the error message removed?  At the bottom I see that I'm successfully connect to a BitBucket private repository... http://puu.sh/pKO5Q/492d290acc.png. 

Thanks much

**Comment by afragen** [comment]
You really are using GitHub too as this plugin uses it. It's still easiest to create a personal access token. Otherwise you can ignore it.

Have you been using the Check Again button on update-core.php a lot?

**Comment by afragen** [comment]
You can safely ignore this message if you don't wish to add a personal access token. No harm, no foul.

**Comment by psasser** [comment]
I haven't been using the check again button the message starts to show up immediately when I install the plugin.  If I were to create a personal access token would I have to create a new one each time I used this plugin (for each site its on) or would the same one suffice?  When I create the token what scopes should I give it?

Thanks.

**Comment by afragen** [comment]
Are you using iThemes Security on a multisite install? Just curious.

The personal access token only need `read` scope, nothing else. You can use the same access token on multiple sites. The access token allows for 5000 authenticated API calls per hour. You won't likely come close unless you're using it on several hundred sites. 😉

**Comment by psasser** [comment]
Not using iThemes Security, but Wordfence on a single site install.  Would that make a difference??

**Comment by afragen** [comment]
If there are settings to hide update messages it may be an issue. I do a lot of caching in the Transients API as the `wp_remote_get` calls are time expensive. I found under the circumstances above the transients wouldn't save causing many calls.

You can save yourself at least one API call per plugin by turning off branch switching. If you use Query Monitor you can see what HTTP Requests are being made.

**Comment by afragen** [comment]
@psasser are you still having issues? If you want to see what HTTP calls your site is making you can install the Query Monitor plugin. It will show you what HTTP requests are being made and which ones are failing.

**Comment by afragen** [comment]
I'm going to close this issue for lack of activity. Please reopen if there's anything further.
