### ISSUE TITLE
Prevent to accidentally remove a Git repository

### ISSUE THREAD

**Issue by benoitchantre** [afragen/github-updater#414]
It would be great if GitHub Updater could check for the existence of a Git repository, for itself or installed plugins / themes.

In the case there's a Git repository for a theme / plugin, it should not manage it (updates and branch switching). If the user accidentally does an action with GitHub Updater (update, branch switching), the Git repository will be removed.

You can easily be in a situation like this when you have a local installation which database is synced periodically with the live website. If you forget to disable GitHub Updater, you can perform a dangerous action for your Git repository.

**Comment by afragen** [comment]
@benoitchantre I can't tell you how many times I've done this. So many that I released a plugin on the dot org repo to solve it.

https://wordpress.org/plugins/local-development/

Let me know if you like it.

**Comment by benoitchantre** [comment]
@afragen Thanks for this plugin. I have tested it quickly and it does the job. I think you should mention this plugin in README.md

I have also completed the french translation on GlotPress.
