### ISSUE TITLE
Theme is showing as up-to-date, when it is not.

### ISSUE THREAD

**Issue by joshfoskett** [afragen/github-updater#415]
### Issue

Theme appears as up-to-date, even when you try to force update (by checking it and using the dropdown and selecting "Update"). The theme in question is in a private repo, and should have the correct information in the `style.css`:

    Version: 1.0.4
    GitHub Theme URI: Foo/Bar

It has worked flawlessly in the past on the same plugin version (`5.4.1`), I also tried it on the latest release (`5.5.0`).

I made sure it wasn't a caching issue, as I pushed the `1.0.3` release to master and also tagged it. But after two hours, it still said `1.0.2` was the latest version, regardless with the amount of times I tried refreshing, or force updating.

### Workaround

If you enable branch switching and simply select master, it'll update the theme to the latest version as expected.

**Comment by afragen** [comment]
When you say force updating, what do you mean?

It's likely that the transients just need to be refreshed. If so, the update should show within 12 hours.

**Comment by joshfoskett** [comment]
By "force updating" ([example](http://i.imgur.com/pzwzu19.png)) I simply mean trying to run an update on a theme that appears to be up-to-date. Not sure if doing that triggers anything, or overrides any sort of cache locally? If not, is there anyway to bypass the "transient" cache, instead of waiting up to 12 hours for it to appear (without the branch switching workaround)?

**Comment by afragen** [comment]
I don't think your example of "forcing" an update really works as you think it does. If the plugin shows no update available I don't think it does anything.

But, in the latest `develop` branch there's a button in the _GitHub Updater Settings_ to _Refresh Transients_. In the version you have you can just use the 'Check Again' button in the update-core.php page.

**Comment by afragen** [comment]
Is this still an issue?
