### ISSUE TITLE
After 5.5, can't update private BitBucket repos

### ISSUE THREAD

**Issue by ethanclevenger91** [afragen/github-updater#418]
Steps to reproduce: 

1. Update plugin version from 5.4.1 to 5.5 on site with plugins sourced at BitBucket private that had previously been working

2. Attempt to update a plugin sourced at BitBucket private

3. Receive "Download failed, INTERNAL_SERVER_ERROR"

Checked w/ 2 plugins. Let me know if you need anything else.

**Comment by ethanclevenger91** [comment]
Actually, I just got this on a site w/ 5.4.1, too. Makes me think it could be something on BB's end that updated, then.

**Comment by afragen** [comment]
I just tested with a private BB repo and it all worked. Perhaps it is something on there end. Let me know if this persists.

Internal Server Error is usually an htaccess problem. Anything change recently?

**Comment by ethanclevenger91** [comment]
So I'm getting a WP_Error when it tries to do `download_package` in `class-wp-upgrader.php`, line 673ish:

```
WP_Error Object
(
    [errors] => Array
        (
            [download_failed] => Array
                (
                    [0] => Download failed.
                )

        )

    [error_data] => Array
        (
            [download_failed] => Too many redirects.
        )

)
```
So sounds like I'm being redirected around on BitBucket's end. This sound like anything you've encountered before?

**Comment by ethanclevenger91** [comment]
But if I throw open an incog window and navigate to the zip's URL, I get a login screen.

**Comment by ethanclevenger91** [comment]
Okay, `account/signin` is redirecting to `account/signin` indefinitely - here are the last URL it hits:

```https://bitbucket.org/account/signin/?next=/account/signin/%3Fnext%3D/account/signin/%253Fnext%253D/account/signin/%25253Fnext%25253D/account/signin/%2525253Fnext%2525253D/webspec/all-in-one-seo-populate-keywords/get/1.6.1.zip```

**Comment by ethanclevenger91** [comment]
And the authorization header is both intact and accurate.

**Comment by ethanclevenger91** [comment]
Welp sorry for all of that.

BitBucket is upgrading accounts to Atlassian accounts if they aren't already. The account used in our settings was a catch-all that no one ever _actually_ logs into, so we weren't aware this update was pending. BitBucket, rather than return some sort of unauthorized status code, simply returned 302s. After logging into the account and going through the upgrade process, things have returned to normal.

If anyone else runs into this, well, here's the solution.

**Comment by afragen** [comment]
Thanks for documenting this @ethanclevenger91
