### ISSUE TITLE
php error 

### ISSUE THREAD

**Issue by simbalion** [afragen/github-updater#419]
FastCGI sent in stderr: "PHP message: PHP Warning:  array_merge(): Argument #1 is not an array in /wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 263"

I am using some custom functions that you helped me with, to hide GHU, set up the gitlab token, and auto-configure some of the options, could these be contributing to the error?:

// Github Updater Settings
function ptd_ghu_remote_options() {
	$enable_iwp = array(
	'itemes_sync'	=> 'N',
	'infinitewp'	=> '1',
	'managewp'		=> 'N',
	'mainwp'		=> 'N'
	);
	activate_plugin( 'github-updater/github-updater.php' );
	update_option( 'github_updater_remote_management', $enable_iwp );
}
add_action('adminmenu', 'ptd_ghu_remote_options');
add_filter( 'github_updater_token_distribution',
   function () {
      return array( 'gitlab_enterprise_token' => 'token-goes-here' );
   } );
add_filter( 'github_updater_hide_settings', '__return_true' );

**Comment by afragen** [comment]
@simbalion I'm not sure where you have all of the above but the error certainly is related. line 263 argument 1 is `get_site_option( 'github_updater' )` and argument 2 is the return value of `add_filter( 'github_updater_token_distribution', ... );`

I would need a clearer understanding of where you're calling your custom code from  to be able to duplicate this. Is it possible you have an `update_option( 'github_updater', ...);` somewhere that isn't an array?

**Comment by simbalion** [comment]
I copied that verbatim from functions.php All of the github-updater
related code is in that block of code.

I just updated to 5.5 and I apologize but I'm uncertain if this issue
existed before I updated or after.

**Comment by afragen** [comment]
Was this error on an first run of the plugin on a new site?
Does this error persist?

**Comment by afragen** [comment]
I think I may know what's happening. The filter was designed to accept GitHub access tokens. I'll have to test to see if/where the issue is.

**Comment by afragen** [comment]
Was this issue related to your other issue with ports?

**Comment by simbalion** [comment]
I don't believe so but it may have been. I will need time to test it again but I am preparing for court tomorrow so it won't be before the weekend.

**Comment by afragen** [comment]
@simbalion are you still having an issue?

**Comment by simbalion** [comment]
I haven't had opportunity to test, but I will be able to in the next
couple of weeks I suspect.

Simba Lion - https://tailpuff.net
https://keybase.io/simbalion

"Why is a raven like a writing desk?"

**Comment by simbalion** [comment]
With the latest version of your plugin I do not seem to be having this issue any longer.
