### ISSUE TITLE
"Download failed, a valid URL was not provided"

### ISSUE THREAD

**Issue by simbalion** [afragen/github-updater#421]
Downloading update from https://*******:4433/pridetechdesign/memorialReam/repository/archive.zip?ref=master&private_token=*******************

Download failed. A valid URL was not provided.

That URL is valid, I copied it and pasted it into firefox and it downloaded the archive.

**Comment by afragen** [comment]
@simbalion what type of git server is that? None of the usual ones use a port other than 80? Is this a GitLab Enterprise installation?

In order to troubleshoot further I really need to look at the repo, is that possible?

**Comment by simbalion** [comment]
It's gitlab-ce, it's running on a residential ISP which blocks ports 80 and 443.

I thought the custom port was probably the issue, I can give you reporter access will that be enough?

**Comment by afragen** [comment]
Reporter access is enough.

**Comment by afragen** [comment]
I think the issue is the non-standard port. I know the code creating the download link doesn't support it -- yet.

**Comment by afragen** [comment]
I was incorrect. The non-standard port does make it into the download link. I'm testing and with a  constructed download link given the information provided in email in a browser and the server times out.

**Comment by simbalion** [comment]
I apologize, but if you're testing on my server I changed it back to the standard port 443, as I was able to ask my ISP to unblock it. I sent you an email about that but perhaps you didn't receive it.

**Comment by afragen** [comment]
I just adjusted the port to 443 and if I put the download link in the browser I get a 404.

**Comment by simbalion** [comment]
I sent an email just now with the correct repo name

**Comment by afragen** [comment]
OK, for followup. I was able to install the theme locally and the download link did include a port number. I'm unclear what the previous issue was but it seems to be sorted out now. 👍

**Comment by wordpress-updater** [comment]
the question i met, too .and don't known where is wrong, maybe it's WP_Error caused?
