### ISSUE TITLE
Tags are missing on Packagist

### ISSUE THREAD

**Issue by ethanclevenger91** [afragen/github-updater#425]
Maybe this has always been the case, but I noticed that none of your tags are listed on Packagist ATM, and so composer installs are failing. Also saw [this](https://github.com/borisrepl/boris/issues/121), so wonder if it's something intermittent on Packagist's end?

**Comment by afragen** [comment]
Hey Ethan, I went to Packagist and updated. Tags are now listed there. Not sure if this is something that must be done from time to time. Thanks for letting me know.
