### ISSUE TITLE
Branch switcher is changed on plugin update

### ISSUE THREAD

**Issue by joelworsham** [afragen/github-updater#427]
When updating directly from the plugins page, WordPress seems to grab both the WordPress update line as well as the branch switcher line, and change them to the updating text. It never changes back either, probably because WP's JS only accounts for the first line.

https://i.imgur.com/x6ENuOq.png

**Comment by afragen** [comment]
This has to do with the classes I need to add for the branch switcher row. On WP 4.6 the spinner is not present in the branch switcher row.

**Comment by joelworsham** [comment]
Ahhh gotcha, great!
