### ISSUE TITLE
Pull latest commit

### ISSUE THREAD

**Issue by joelworsham** [afragen/github-updater#428]
Sorry to flood you with issues here, I'm loving the plugin. Just things I notice :)

## Scenario:

I've got a plugin, and I'm working on a branch. I switch to that branch from within WP. All is well. I push a commit up to that branch and want to test it on the site.

## Problem:

It seems there is no way to A) know if the site's plugin is behind the latest commit on the GitHub repository, and B) pull down the latest changes to the site.

## Current Solution:

In order to get the latest changes, without manually SFTP the changes up, I can switch to a different branch and then back.

## Possible Fixes:

A) Have GH Updater somehow know or check to see if it's at the latest commit. I don't believe this is possible, because I _think_ it only checks tags/branches. This is fine.
B) Have a button somewhere that says something like "Try for latest changes". This button would simply re-download that branch from GitHub, potentially grabbing new files, if there are changes present, otherwise simply re-downloading what exists.

Perhaps this issue is due to my naivety and there is indeed a way to bring down the latest changes?

Thanks again for all your hard work on this plugin.

**Comment by joelworsham** [comment]
Ya know, after further looking into this, it does seem that possible fix B) does technically exist. You can "try another branch", but click on the current branch, and it downloads.

Perhaps then this is simply a case of UX? Maybe there's a way to make this more clear. I'm not saying it's necessary, so feel free to brush this off. Maybe I'll figure out a way and PR it sometime :)

**Comment by afragen** [comment]
Actually this is pretty easy using the RESTful endpoint and a webhook on GitHub. The code is already in GitHub Updater.

Here's what I do for testing GitHub Updater on my test site. 

In the GitHub settings for the repo I create a webhook that has the URL `https://thefragens.net/wp-admin/admin-ajax.php?action=github-updater-update&key=xxxxxxxxxxxxxxxxxxxxxxxxx&plugin=github-updater&tag=develop`. Every time I push a commit GitHub sends that webhook. That webhook is seen by GitHub Updater and will essentially result in a _reinstall_ of the `develop` branch of the plugin whose repo name is `github-updater`. The RESTful endpoint starting point is displayed in the Remote Management tab.

Take a look at the README for more details. Naturally, I'd have to remove the webhook if I ever want to stay on a different branch.

**Comment by joelworsham** [comment]
Ohhh I like the sound of that webhook. I'll check it out. Thanks so much for the advice.

**Comment by joelworsham** [comment]
> Naturally, I'd have to remove the webhook if I ever want to stay on a different branch.

I wonder if there's a way to have this be automatic and dependent on the branch. So that, the webhook is sent for every branch, and if the current branch on the site matches the branch updated, **then** it's updated.

**Comment by afragen** [comment]
>> Naturally, I'd have to remove the webhook if I ever want to stay on a different branch.

> I wonder if there's a way to have this be automatic and dependent on the branch. So that, the webhook is sent for every branch, and if the current branch on the site matches the branch updated, then it's updated.

I don't think that's possible as you have to set the webhook in GitHub. You could create a shell script to run the RESTful endpoint though.

`$ curl "https://thefragens.net/wp-admin/admin-ajax.php?action=github-updater-update&key=xxxxxxxxxxxxxxxxxxxxxxxxx&plugin=my-super-awesome-plugin&tag=develop"`

But you would have to know which branch you want to update with. You might be able to build your own plugin to do this. Use the code to read in the local plugin meta so you know it's updatable from GitHub Updater and you'll also have the branch specified.

Once you have that data you just need to send a GET to the local RESTful URI. I think it should work, never done it. 😉 Not sure if that might rip the space/time continuum.

**Comment by joelworsham** [comment]
> Not sure if that might rip the space/time continuum.

That's a risk I'm willing to take for the sake of convenience!

I really am liking the sound of this. Perhaps I will build it in a different plugin. Is this a feature you would consider ever merging into GitHub Updater?

**Comment by afragen** [comment]
I'm not sure it needs to be in GitHub Updater but would make a nice add-on that we can mention in the README. Sorta like I did with GitHub Updater Additions. 

https://github.com/afragen/github-updater-additions
