### ISSUE TITLE
Extended Naming not working with branch switching

### ISSUE THREAD

**Issue by joelworsham** [afragen/github-updater#429]
I have `define( 'GITHUB_UPDATER_EXTENDED_NAMING', true );` in `wp-config.php` and it does work when installing and such, but when branch switching, it goes back to the repository name without the extended naming. Just watched it live via SFTP to confirm.

**Comment by joelworsham** [comment]
Just to be thorough, here's a screencast. Note that the plugin *is* remaining active properly, despite the dirname change.

https://www.dropbox.com/s/woltinv2xz9hoys/github-updater-issue-429.mov?dl=0

**Comment by afragen** [comment]
I'll take a look. It seems as though it's not catching the renaming part of `Base->upgrader_source_selection()`.

**Comment by afragen** [comment]
This should solve the issue. Please let me know.

**Comment by joelworsham** [comment]
I've been using the release tag 5.5.0. Is the develop branch safe for production use?

**Comment by afragen** [comment]
I think so, but you should be able to use branch switching to switch, test, and switch back. If you want to continue using develop until next release change the branch in develop to master and when the version bump happens it will update to the master branch.

**Comment by joelworsham** [comment]
Switched to develop, changed branches on a plugin, successfully renamed to extended naming.

Thank you!
