### ISSUE TITLE
"GitHub Updater Error Code: 401" with Bitbucket

### ISSUE THREAD

**Issue by RadGH** [afragen/github-updater#431]
I am using one plugin in a private bitbucket repo.

I have added the following to the plugin's main file on line 9, just below the author uri:

> Bitbucket Plugin URI: https://bitbucket.org/limelightdept/article-arrow-navigation.git

I have created a bitbucket user that has read access of the repo. I am able to log in as that user, go to the repo, and download the files.

After saving the username and password for Bitbucket on the Github Updater plugin settings page, I get the error:

> GitHub Updater Error Code: 401	
> There is probably an access token or password error on the GitHub Updater Settings page.

Issue #1) It doesn't mention bitbucket at all. I have no idea if this is a bitbucket or github error.

Issue #2) If it is a bitbucket error, why am I getting that? I don't want to use bitbucket for updating any of my plugins, and I purposefully left the bitbucket fields blank.

Issue #3) The plugins screen does not show any update available for my plugin, which has the comment mentioned above. Even after manually attempting to update the plugin, it remains at version 1.0.0. The current version is 1.0.1. Both versions have the bitbucket plugin URL line.

What should I do? Just seems like this plugin is broken.

**Comment by RadGH** [comment]
Issue #4) The plugin settings screen asks for Bitbucket Username. But you do not log into bitbucket with your username, you log in with your email. I tried both, but this seems confusing.

**Comment by RadGH** [comment]
Ah, seems to work if I uninstall the plugin then install it through Github Updater. Still, the issues I experienced were quite confusing.

**Comment by afragen** [comment]
Bitbucket used to have usernames. I think older accounts still do. Saying `username` if fairly common, even if the username is an email address. 

The problem with labeling the field `email address` is that someone will put in an email address not associated with their Bitbucket account.

**Comment by afragen** [comment]
FYI, you don't need the `.git` on the URI but the code strips it off if it's present.

**Comment by afragen** [comment]
#2 is the cause of your issue as you discerned. Sorry.

**Comment by RadGH** [comment]
Ah that makes sense about the usernames. The main concern was it didn't ask for a username when signing up, and I was trying my email and it wasn't working for the issue I figured out later. ;)

**Comment by afragen** [comment]
At some point you'll have to make your way to the Settings page. 😉

**Comment by afragen** [comment]
I see there's another related issue I'm working on related to WP 4.6. I hope to have a fix to the develop branch later today.

**Comment by afragen** [comment]
See if develop v5.5.0.20 fixes this for you.

**Comment by RadGH** [comment]
Thanks! I updated the plugin files manually, it reported 5.5.0.20 in the plugins screen of the dashboard. I still had the error initially: https://goo.gl/TcTB4M

I saved changes on the settings page, and then refreshed, and now the error is gone. Looks like it is fixed. Thank you!

Also, a minor issue. I'm using private bitbucket repos for my plugins. When I add them through the plugin there's a checkbox to mark them as private. Afterwards though, they get listed under "Bitbucket Private Repositories" and the checkbox is NOT checked. Could you make it remember if it was a private repo during the install? That would make this plugin perfect!

**Comment by afragen** [comment]
@RadGH the image you posted wasn't the develop branch as it should show the _Refresh Transients_ button on the Settings page. 

 The 'minor' issue is fixed in this branch. 

Glad everything's working again. I'm getting closer to releasing all these fixes in next release.
