### ISSUE TITLE
Plugin suddenly stopped detecting changes in BitBucket private repo

### ISSUE THREAD

**Issue by yaronguez** [afragen/github-updater#432]
Hi there. I love this plugin and use it all the time for client development. Today it stopped detecting changes in a private Bitbucket repo.  The version number of the plugin in WP is 1.6 and the version number on the repo is 1.7 but it won't detect a new update available. I've tried clearing transients, clearing the cache (WP Engine) and clicking "Check Again" in the WordPress Update dashboard a dozen times. I've also confirmed that it's checked off as a private repo in GitHub Updater Settings. What else can I try? Thanks for all your help!

**Comment by afragen** [comment]
Can you post the headers for both local and upstream main plugin files?

Are you getting any errors notices?

What version are you using?

**Comment by yaronguez** [comment]
Thanks for the prompt reply, Andy! Here is the local plugin header:
```php
/**
 *
 * @link              http://trestian.com
 * @since             1.0.0
 * @package           Gcwar
 *
 * @wordpress-plugin
 * Plugin Name:       Global Car Wash and Repair
 * Plugin URI:        https://bitbucket.org/goerdan09/gcwar.plugin
 * Description:       Custom functionality plugin for Global Car Wash and Repair
 * Version:           1.6.1
 * Author:            Yaron Guez
 * Author URI:        http://trestian.com
 * License:           GPL-2.0+
 * License URI:       http://www.gnu.org/licenses/gpl-2.0.txt
 * Text Domain:       gcwar
 * Domain Path:       /languages
 * Bitbucket Plugin URI: https://bitbucket.org/goerdan09/gcwar.plugin
 */
```

Here is the header of the plugin in the BitBucket repo:
```php
/**
 *
 * @link              http://trestian.com
 * @since             1.0.0
 * @package           Gcwar
 *
 * @wordpress-plugin
 * Plugin Name:       Global Car Wash and Repair
 * Plugin URI:        https://bitbucket.org/goerdan09/gcwar.plugin
 * Description:       Custom functionality plugin for Global Car Wash and Repair
 * Version:           1.7
 * Author:            Yaron Guez
 * Author URI:        http://trestian.com
 * License:           GPL-2.0+
 * License URI:       http://www.gnu.org/licenses/gpl-2.0.txt
 * Text Domain:       gcwar
 * Domain Path:       /languages
 * Bitbucket Plugin URI: https://bitbucket.org/goerdan09/gcwar.plugin
 */
```

I do not receive any error notices. I am using version 5.5.0.19 of the GitHub Updater Plugin. I tried manually reducing the local version to 1.6 (from 1.6.1) to see if that would force an update detection but it did not. I needed to deploy this so I finally used the "Install Plugin" tab feature to reinstall the plugin from the repo. This resulted in me having two copies of the plugin installed with different version numbers so I manually removed the old version.

I just tried pushing a new change to the plugin as a 1.7.1 feature and, after clicking "Refresh Transients" in the plugin settings and clicking "Check Again" in WP Updates, the update came through. Hopefully reinstalling the plugin has resolved the issue, but if it comes back, is there anything else you recommend? Also, do I need to click "Refresh Transients" in the plugin settings and click "Check Again" in WP Updates every time in order for new updates to come through?

Thanks again for your help!

**Comment by afragen** [comment]
Can you give temporary `read` access to `afragen`?

**Comment by afragen** [comment]
It could be that GHU doesn't like repo names with `.`

**Comment by yaronguez** [comment]
Done.

Yaron Guez
Software Architect
(781) 249-4709

**Comment by afragen** [comment]
I'm having the same issues you are. I'm guessing updating has never worked with this plugin.

I think the issue is deeper inside of WP core as the update fails at unpacking. I think the problem is how the repo is named. 

Can you change the repo name from `gcwar.plugin` to `gcwar-plugin`?

So far this is the first time I've come across this particular naming convention.

**Comment by yaronguez** [comment]
We recently renamed the repo, adding a period, when we moved the plugin
from one account to another. Before the rename it worked every time though
you'd sometimes have to click "check again" a few times. After the rename
it works *sometimes *but sometimes not at all. It's unpredictable.

I just renamed the repo to gcwar-plugin and had to refresh transients and
click check again 4 times before it showed up as an available upgrade. Does
it work on your end?

Yaron Guez
Software Architect
(781) 249-4709

**Comment by afragen** [comment]
I see the problem and I think it's unrelated.

When shiny updates hit I must not have tested the Bitbucket authentication. I need to readjust how I send the Basic Auth header when using AJAX.

Stay tuned.

**Comment by afragen** [comment]
Latest commits to `develop` v5.5.0.20 should sorta fix this issue. Still only can update one private Bitbucket repo per page load. Not very AJAXy 😝 

Let me know.

**Comment by yaronguez** [comment]
I'm unable to update the plugin from the plugins screen:
https://www.dropbox.com/s/o1nctzhdpg01ksv/Screenshot%202016-08-24%2015.29.32.png?dl=0

I did just update it from the WP Updates page though.

Pushing a new gcwar-plugin update didn't show up in plugins on its own.
Clicking Check Again under WP Updates didn't show the update either.
Clicking Refresh Transients and then Check Again DID show the gcwar-plugin update and the update went through

**Comment by afragen** [comment]
The Check Again button no longer refreshes transients. This must be done from the *Refresh Transients* button on the Settings page. 

Seems like it's working then. No sure why you got the initial update failed. Better messages are written to the browser console.

**Comment by yaronguez** [comment]
Thanks for all your help, Andy! And thanks for creating such a useful
plugin.
Yaron

Yaron Guez
Software Architect
(781) 249-4709

**Comment by afragen** [comment]
No problem Yoran
