### ISSUE TITLE
How to Sync

### ISSUE THREAD

**Issue by kutec** [afragen/github-updater#434]
I have changed the file in local clone and pushed to Bitbucket. But now how to sync with self hosted WP? I am bit confused! Please suggest.

**Comment by afragen** [comment]
What particularly is the issue? Is this a private Bitbucket repo?

**Comment by andreasupftw** [comment]
@afragen I have the same issue. Private repo. Changed version number in style.css and pushed to master...

**Comment by kutec** [comment]
Yes @afragen thatt's private Bitbucket repo.

**Comment by kutec** [comment]
Hey issue fixed. It requires version to be changes every time we pushed :).

Thanks @andreasupftw and @afragen.

**Comment by afragen** [comment]
> Hey issue fixed. It requires version to be changes every time we pushed :).

Well, that's not entirely accurate. :wink: 

Take a look at the README about using RESTful endpoints and webhooks. If you set a webhook in you repo's settings an update will be pushed at every commit. It's under the Remote Management tab.
