### ISSUE TITLE
Error on plugin activation after update

### ISSUE THREAD

**Issue by ryanfurtner** [afragen/github-updater#439]
Hey there! 

I just updated to the latest version (through the wordpress dashboard) and after the update, wordpress deactivates the plugin due to an error. If I try to re-activate the plugin I get this:

`Fatal error: Allowed memory size of 41943040 bytes exhausted (tried to allocate 72 bytes) in /home/________/public_html/wp-includes/compat.php on line 181`

At one point I got this too but im not sure how to recreate it:
`Call to undefined function mb_strrpos() in /home/_________/public_html/wp-content/plugins/github-updater/vendor/class-parser.php`

Im not sure if this is caused by my wordpress installation or not, thought it was worth mentioning though!

**Comment by afragen** [comment]
Wow, not sure how to explain that second error. `mb_strrpos` is part of PHP. 

Which plugin was updated, GitHub Updater?

Can't say I've ever seen that. It seems like you may need to increase the amount of memory allocated to PHP. 

Try adding the following to your wp-config.php

`define('WP_MEMORY_LIMIT', '256M');`

**Comment by ryanfurtner** [comment]
Yep it was the memory limit! I upped it to 256M like you suggested, downloaded the latest from git and uploaded/installed without any issues.
