### ISSUE TITLE
401 Error on Multisite with current theme that installed by Github Updater

### ISSUE THREAD

**Issue by calvintam236** [afragen/github-updater#444]
I have installed Github Updater on a WordPress 4.6.1 Multisite Network. I notice the theme & plugins installed from Bitbucket Private Repo doesn't saved its private repo status at settings. It results in 401 status, and requires network admin to check all repos as private repos.

**Comment by afragen** [comment]
This has been fixed in the `develop` branch. I will likely be pushing this by week's end.

**Comment by calvintam236** [comment]
Awesome. There is another problem. ```Theme is up-to-date! No previous tags to rollback to.``` remains at theme list page, and it doesn't go away after refreshing the page. Is it supposed to show all the time?

**Comment by afragen** [comment]
There is a theme rollback feature where, if you tag your releases, the last 3 tagged versions will be available for rollback. If you don't tag your releases, this is the display. It is expected.

**Comment by calvintam236** [comment]
Is there a setting to disable this message? I have no planning to use the tags yet, and it shows up at sub-sites too.

**Comment by afragen** [comment]
It only shows up for user roles that can update themes. So only the Administrator can see, not others. There isn't a setting to hide it.

**Comment by afragen** [comment]
> requires network admin to check all repos as private repos

Only check the private repos

**Comment by calvintam236** [comment]
sorry for confusion.. I mean when I install the theme/plugin using the plugin, and they are bitbucket private repos, the plugin does not mark these plugins as bitbucket private repos. I (network admin) have to manually check the checkboxes at the updater plugin settings and save them as private repos.

**Comment by afragen** [comment]
I understand. This bug is fixed in the develop branch. 

What I meant was only check the boxes of private repos, not public repos. 😉

**Comment by calvintam236** [comment]
I aware what you are saying. From a user experience, when you install a plugin/theme, and you have selected it is a private repo at installation, you would expected the plugins know it is private repo until I delete it. User shouldn't need to check the checkboxes again as most people would probably assume the plugin knows about it.

**Comment by afragen** [comment]
It really did retain the selection initially. I clearly introduced a bug somewhere and only realized it when another user posted an issue.

**Comment by afragen** [comment]
BTW, just released 5.6.0, the fix is there. 👍
