### ISSUE TITLE
Notice: Undefined index: tested

### ISSUE THREAD

**Issue by nextgenthemes** [afragen/github-updater#445]
in .../wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 922

got this after updating to Version 5.6.0

also:

( ! ) Notice: Undefined index: requires in .../wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 923

**Comment by afragen** [comment]
This is the section of code that parses a `readme.txt` file. What's happening is a `readme.txt` file is missing some data that I am trying to parse.

Fixed https://github.com/afragen/github-updater/commit/aabf4c2407f7d508ac4417c0bc4b62e6059d70ce
