### ISSUE TITLE
 5.6.0 Parse error: syntax error, unexpected '[' in /nas/content/staging/zephyrre/wp-content/plugins/github-updater/vendor/class-parser.php on line 289

### ISSUE THREAD

**Issue by CurtisBelt** [afragen/github-updater#447]
Was on Github Updater 5.5.0
Used Wordpress Dashboard to update to 5.6.0

For example `[...]/wp-admin/network/settings.php` will result in

`Parse error: syntax error, unexpected '[' in /nas/content/staging/zephyrre/wp-content/plugins/github-updater/vendor/class-parser.php on line 289`

Does not occur on all pages, only some:
`/wp-admin/network/settings.php`
`/wp-admin/options-general.php`

I can give you a temporary admin user on the staging site if you would like, let me know.

**Comment by curtisbelt** [comment]
Server (where the error occurs) is on PHP 5.3.10.
Error does NOT occur on localhost, which is on PHP 5.5.36

**Comment by afragen** [comment]
I will look at this to make sure there is no php 5.4 style array declared.

**Comment by afragen** [comment]
@CurtisBelt you really should have that server updated.

**Comment by CurtisBelt** [comment]
@afragen I just checked into it with WPEngine. Have a ticket setup to migrate our installs to PHP 5.5. May not be done for a few days.

**Comment by afragen** [comment]
@CurtisBelt can you install the develop branch?

I pushed a commit to fix these issues and I'd like you to test.

**Comment by afragen** [comment]
PHP 5.5 isn't current. You should ask for at minimum PHP 5.6

**Comment by CurtisBelt** [comment]
@afragen Tried the develop branch like you asked - that fixed it! And yeah I know :( 5.5 is the highest they offer until they release 7.0 in a few months.

Are you going to hotfix to master by chance? I have a lot of individual sites that are running on Github Updater master branch.

**Comment by afragen** [comment]
Yes, hotfix for master on the way. Just waiting for confirmation of fix for #446

**Comment by CurtisBelt** [comment]
Thank you! I'll close this out.
