### ISSUE TITLE
5.6 Updates no longer working

### ISSUE THREAD

**Issue by scarstens** [afragen/github-updater#448]
After upgrading to 5.6 it no longer gets updates in a reasonable amount of time, and reset transients does not solve the problem. As far as I can tell its not doing a remote call to the github API and properly updating the available tags.

![nogithubupdater](https://cloud.githubusercontent.com/assets/1483300/18568130/644530c2-7b50-11e6-9de6-693054281df3.gif)

**Comment by afragen** [comment]
Seth, in Query Monitor, what's causing the red notification of error? Anything in HTTP Requests?

**Comment by scarstens** [comment]
It makes 52 HTTP requests, 3 of theme fail (woothemes updater helper fails) which is why its red. Of note, I did't see it actually reaching out to the github repo in those updates let me see if I can get a screenshot that captures all that.

**Comment by scarstens** [comment]
Actually, looks like I did find the request for tags for GHU - more screenshots coming

![image](https://cloud.githubusercontent.com/assets/1483300/18570816/faafd06a-7b61-11e6-83bd-5dda2199198a.png)

**Comment by scarstens** [comment]
Oh wow oops, just realized I released my access token 😵

**Comment by afragen** [comment]
You can delete screenshots. Also you can make temp token and just delete after.

**Comment by afragen** [comment]
Any update registered?

**Comment by scarstens** [comment]
Its fine I just deleted that token I'll leave it up. Still not updates. Its not registering any of my theme updates either, which I processed in a tag yesterday.

**Comment by scarstens** [comment]
also I'm on slack/google if chats easier. or I can give you access to the site

**Comment by afragen** [comment]
Hit me up on slack

**Comment by afragen** [comment]
Hey Seth, I think https://github.com/afragen/github-updater/commit/78ecdd91bc0173a5e1361af505b55188507804b4 may fix this issue.

It ties a reset of the _update\_plugins_ and _update\_themes_ transients when the _Refresh Transients_ button is used.
