### ISSUE TITLE
Too many redirects when installing theme from Bitbucket

### ISSUE THREAD

**Issue by Dnncha** [afragen/github-updater#452]
Hi.

I'm getting a Too many redirects error when I try to install a theme from Bitbucket. The site runs on Google Compute Engine. The strange thing is, I've run sites with this set-up before, and haven't encountered this problem. 

Any ideas? 

Thanks for the great plugin. 
Donncha

**Comment by Dnncha** [comment]
Newbie mistake, I was using an incorrect password. It might be helpful if the plugin could display that error coming back from Bitbucket. 

Thanks again.

**Comment by afragen** [comment]
Not sure how we could check for a user/password error. If I ever get oAuth working that may solve the problem, but it's a way off.
