### ISSUE TITLE
Notification should not in separate row

### ISSUE THREAD

**Issue by calvintam236** [afragen/github-updater#454]
I finally notice why the notification from GitHub updater looks different. It seems it is inserted into separate row instead of below the same row.. It should be an easy fix though.

![screen shot 2016-09-24 at 5 25 08 pm](https://cloud.githubusercontent.com/assets/6436149/18812040/f1bec0a8-827b-11e6-8d56-662a971b05d7.png)

**Comment by afragen** [comment]
Believe me I've tried. Unfortunately I can't seem to make it look like the branch switcher row is part of the plugin row.

If you can make it work I'm game for a PR.

**Comment by calvintam236** [comment]
I googled it, and it seems there is a solution according [http://wordpress.stackexchange.com/questions/87051/how-to-display-a-message-about-updates-in-the-plugin-list/90899#90899](http://wordpress.stackexchange.com/questions/87051/how-to-display-a-message-about-updates-in-the-plugin-list/90899#90899). I can work on it if I have time.

**Comment by afragen** [comment]
Thanks @calvintam236. I guess I missed that hook.

I'll have to rewrite some of the code to conform to the hook but it gives me a good starting point.

**Comment by afragen** [comment]
Well there's a problem. This hook is only for plugins showing updates. Even then it seems the message row looks similar though since this hook doesn't work on every plugin row it's a non-starter.

**Comment by calvintam236** [comment]
If there is an update, the hook fires.
https://developer.wordpress.org/reference/hooks/in_plugin_update_message-file/

I think changing the ```$plugin_data['update'] = true``` can force WP to fires the hook?

**Comment by afragen** [comment]
It doesn't seem to work that way. 😝

**Comment by calvintam236** [comment]
I think I found a better solution: http://wordpress.stackexchange.com/questions/137644/how-to-add-custom-content-under-plugin-row-in-wordpress-admin-plugin-list

**Comment by afragen** [comment]
Your better solution is exactly what I use. 😄 
https://github.com/afragen/github-updater/blob/develop/src/GitHub_Updater/Plugin.php#L253

**Comment by afragen** [comment]
I think what we would really need is a hook `before_plugin_row_end_{$plugin_file}` somewhere around here https://core.trac.wordpress.org/browser/tags/4.6/src/wp-admin/includes/class-wp-plugins-list-table.php#L838

**Comment by calvintam236** [comment]
I was inspecting the plugin list page source code.

I found a workaround using JS. To remove the bottom border, the ```tr``` for the plugin row needs ```update``` class. Maybe adding similar to ```$('tr[data-plugin=' + plugin path + ']:first').addClass('update')``` on ```onload``` method.

Plugin status should be added into the update row class same as WP, e.g. ```active``` when plugin is active. Otherwise, the update row does not match the plugin style.

**Comment by afragen** [comment]
But adding the `update` class changes the CSS for the row. I've looked at this. That is why the update notification that I add appears inside the row but the additional branch switcher row does not.

I really don't think this is fixable. Sorry, but by all means if you find something that works let me know.

**Comment by calvintam236** [comment]
I used the inspector to add the classes.
1. Add ```update``` on the plugin row.
2. Add ```active``` on the update row to indicate the plugin status.

I don't see layout broken because of these new classes.
![screen shot 2016-09-29 at 6 05 40 pm](https://cloud.githubusercontent.com/assets/6436149/18977488/87d86354-866f-11e6-84ab-ce5666e0c150.png)

**Comment by afragen** [comment]
What happens when the plugin isn't active?

**Comment by calvintam236** [comment]
```active``` class should only be added when the plugin/theme is active.

For plugin, use [is_plugin_active](https://codex.wordpress.org/Function_Reference/is_plugin_active).
For theme, use [wp_get_theme](https://developer.wordpress.org/reference/functions/wp_get_theme/#comment-673).

**Comment by afragen** [comment]
I know when the plugin is active, my point is that when the plugin is not active, using this does not create the desired effect.

You would need to test active/inactive plugin and those with updates too. Having both the update and the branch switch row doe really mess with things.
