### ISSUE TITLE
Error notices when debuggin

### ISSUE THREAD

**Issue by joje47** [afragen/github-updater#456]
A small issue, but still it's a bit annoying when debugging other problems.
If WP-debug is on you get these warnings;

Notice: Undefined index: owner_repo in ...wp-content/plugins/github-updater/src/GitHub_Updater/Plugin.php on line 175

Notice: Undefined index: owner_repo in ...wp-content/plugins/github-updater/src/GitHub_Updater/Theme.php on line 170

They repeat a couple of times making the page crowded. I removed a portion of the path.
Should be simple to fix this by checking the index before using it.

**Comment by afragen** [comment]
Can you let me know how many plugins are using GitHub Updater and if possible URI's for them? 

I've never seen this error but I suspect it has to do with a `GitHub Plugin URI` and/or a `GitHub Theme URI` that is malformed.

I never turn WP_DEBUG off in my local environment.

**Comment by joje47** [comment]
It's 2 plugins and 6 child themes that you can find on https://github.com/ngo-portal that I use with github updater. (It's all of them that is there)
The plugins that I have on wordpress are at https://github.com/joje47/NGO-portal
In fact I have another problem and that is that the plugins don't show updates, but the child themes do.
 
Vänligen /George 

    Den tisdag, 27 september 2016 15:47 skrev Andy Fragen <notifications@github.com>:
 

 Can you let me know how many plugins are using GitHub Updater and if possible URI's for them? I've never seen this error but I suspect it has to do with a GitHub Plugin URI and/or a GitHub Theme URI that is malformed.I never turn WP_DEBUG off in my local environment.—

**Comment by afragen** [comment]
I was able to install and update both plugins.

![screenshot_01](https://cloud.githubusercontent.com/assets/1296790/18886094/5bb17d2e-84a3-11e6-8f5b-cc35579674f9.png)

I was also able to install and update most of the child themes. I couldn't seem to install the 'wally' parent theme.

But I didn't get any PHP notices. Only error was trying to read one of the theme's 'Readme.txt' file when it expected 'readme.txt'. Just gave a 404, expected.

**Comment by joje47** [comment]
Yeah,
The wally theme requires a wally-plugin + of course the wally-mother theme to work. It works perfectly here. You can find it on wally-wp.se but it's all in Swedish. It's a high availability theme.
I will try the plugins again.
Any news on those error notices?Attached a screendump. I tweaked wp-config to show error messages in read. 
It complain about 
Notice: Undefined index: owner_repo in /home/datagar1/domains/ngo-dev/wp-content/plugins/github-updater/src/GitHub_Updater/Plugin.php on line 175
4 times (twice per plugin?) and 
Notice: Undefined index: owner_repo in /home/datagar1/domains/ngo-dev/wp-content/plugins/github-updater/src/GitHub_Updater/Theme.php on line 170
6 timesI guess once per child theme
Vänligen /George 

    Den tisdag, 27 september 2016 20:15 skrev Andy Fragen <notifications@github.com>:
 

 I was able to install and update both plugins.I was also able to install and update most of the child themes. I couldn't seem to install the 'wally' parent theme.But I didn't get any PHP notices. Only error was trying to read one of the theme's 'Readme.txt' file when it expected 'readme.txt'. Just gave a 404, expected.—

**Comment by afragen** [comment]
> Notice: Undefined index: owner_repo in /home/datagar1/domains/ngo-dev/wp-content/plugins/github-updater/src/GitHub_Updater/Plugin.php on line 175
> 4 times (twice per plugin?) and 
> Notice: Undefined index: owner_repo in /home/datagar1/domains/ngo-dev/wp-content/plugins/github-updater/src/GitHub_Updater/Theme.php on line 170
> 6 timesI guess once per child theme

Unfortunately I cannot replicate this error. Perhaps it might be worthwhile adding just one plugin or theme at a time as see if the error is present. If it is can you copy/paste the main file's headers here?

**Comment by joje47** [comment]
Strange... since it's saying an index it's not defined. I will try, but I might not make it this evening. I'm fixing som bugs on my plugins ;)
Thanks for your effort though. It's worth a lot. Vänligen /George 

    Den tisdag, 27 september 2016 20:38 skrev Andy Fragen <notifications@github.com>:
 

 
Notice: Undefined index: owner_repo in /home/datagar1/domains/ngo-dev/wp-content/plugins/github-updater/src/GitHub_Updater/Plugin.php on line 175
4 times (twice per plugin?) and 
Notice: Undefined index: owner_repo in /home/datagar1/domains/ngo-dev/wp-content/plugins/github-updater/src/GitHub_Updater/Theme.php on line 170
6 timesI guess once per child theme
Unfortunately I cannot replicate this error. Perhaps it might be worthwhile adding just one plugin or theme at a time as see if the error is present. If it is can you copy/paste the main file's headers here?—

**Comment by afragen** [comment]
Just so you know where that index should come from, it should be from the parsed URI in `GitHub Plugin URI` or `GitHub Theme URI`

**Comment by joje47** [comment]
You mean likeGitHub Plugin URI: https://github.com/NGO-portal/adrotate-ngo
in theme or plugin header?
But if that one does not work, would it update then?
In your code (for plugins on line 175)I find$git_plugin['uri']   = $repo_parts['base_uri'] . $header['owner_repo'];

But where is $repo_parts['base_uri'] and $header['owner_repo'] defined? 
It seems any of those ends up empty somehow? It's just a notice, and obviously the plugin works but the output is a bit in the way.
Vänligen /George 

    Den tisdag, 27 september 2016 21:25 skrev Andy Fragen <notifications@github.com>:
 

 Just so you know where that index should come from, it should be from the parsed URI in GitHub Plugin URI or GitHub Theme URI—

**Comment by afragen** [comment]
> You mean likeGitHub Plugin URI: https://github.com/NGO-portal/adrotate-ngo
> in theme or plugin header?
> But if that one does not work, would it update then?
> In your code (for plugins on line 175)I find$git_plugin['uri']   = $repo_parts['base_uri'] . $header['owner_repo'];
> 
> But where is $repo_parts['base_uri'] and $header['owner_repo'] defined? 
> It seems any of those ends up empty somehow? It's just a notice, and obviously the plugin works but the output is a bit in the way.

Like I said, it's confusing. Your headers seem to all be correct but somewhere along the way in either `Base->parse_header_uri()` or `Base->get_repo_parts()` something is not populating for the Plugin or Theme.

If you can step through using xDebug maybe you can see the issue. It all seems to work on my end.

**Comment by afragen** [comment]
Please reopen if this is still an issue.
