### ISSUE TITLE
Feature request: change plugin directory

### ISSUE THREAD

**Issue by nigrosimone** [afragen/github-updater#460]
Hi guy! i'm come from https://github.com/szepeviktor/fix-w3tc with a request.

So many users asked me for a github-updater integration on fix-w3tc.

Fix-w3tc need to work in `\wp-content\plugins\w3-total-cache\` directory but when github-updater download it from github place it in `\wp-content\plugins\fix-w3tc\`.

The idea is add another header for choise the directory, eg.:

    GitHub Plugin URI: https://github.com/szepeviktor/fix-w3tc
    GitHub Plugin Directory: w3-total-cache

thanks for your great work!

**Comment by afragen** [comment]
Is there some issue with installing into `wp-content/plugins/fix-w3tc`?

You could change your instructions to just deactivate the original plugin and activate yours. No renaming needed.

**Comment by afragen** [comment]
Additionally by using your own slug your users wouldn't update back to the original by mistake.

**Comment by nigrosimone** [comment]
thank you! but `fix-w3tc` for work needs to be installed in `w3-total-cache` folder

**Comment by afragen** [comment]
Why?

**Comment by afragen** [comment]
Forget it. I see why. Plugin defines the directory instead of getting the directory. Bad coding IMHO.
