### ISSUE TITLE
Can't get Bitbucket repo branch's hash

### ISSUE THREAD

**Issue by websanya** [afragen/github-updater#462]
When GitHub Updater tries to get a branch from Bitbucket repo it throws an error:
`PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature`. It happens because it can't get proper url with hash. How to fix it?

Thanks.

**Comment by afragen** [comment]
This is usually an authorization issue. Is this a private repo and is the checkbox checked in Settings?

**Comment by afragen** [comment]
Can you share the URI?

**Comment by websanya** [comment]
Sure thing, I check the box when installing the theme. I don't have the theme in the list of private repositories in the plugin settings. 

![bitbucket-theme-screen](https://cloud.githubusercontent.com/assets/3403777/19259618/c3de12b4-8f9c-11e6-86e4-5c97ce39842a.jpg)

**Comment by afragen** [comment]
Can you check the Settings page? I fixed a bug that creeped in that didn't save the checkbox setting. Make sure it's currently checked.

**Comment by websanya** [comment]
Everything works like a charm now!
