### ISSUE TITLE
GitLab Updates not shown

### ISSUE THREAD

**Issue by marbetschar** [afragen/github-updater#464]
I've added my GitLab Access Token to GitHub Updater `v5.6.2` and also included the `GitLab Theme URI` to the themes header file. I'm also able to install the theme by providing the necessary information to the GitHub Updater Theme Install tab.

But for some reason, new updates never show up in WordPress. What's wrong?

Please note that I've tested this on sites running the actual theme in version `0.0.6` and in the GitLab repository there are the following tags existant right now: `0.0.4`,`0.0.5`,`0.0.6` and `0.1.0`.

The full header of the theme looks like:

```
/*
Theme Name: MANDELKIND
Description: A <a href='http://codex.wordpress.org/Child_Themes'>Child Theme</a> for the Enfold Wordpress Theme. If you plan to do a lot of file modifications we recommend to use this Theme instead of the original Theme. Updating wil be much easier then.
Version: 0.1.0
Author: MANDELKIND
Author URI: http://mandelkind.swiss
Template: enfold
GitLab Theme URI: https://gitlab.com/mandelkind/enfold-mandelkind
*/
```

**Comment by afragen** [comment]
What timeframe were you checking for updates? Transients are stored for 12 hours.

**Comment by marbetschar** [comment]
I've checked yesterday evening and tomorrow evening - nothing changed. That said, no new updates are showing. I've even used the "Delete Transients", again no success.

**Comment by afragen** [comment]
It seems to be working for me. Could you test using the `develop` branch? Use the branch switcher to change branches.

**Comment by marbetschar** [comment]
Sure! Do I need to add a GitHub token in order for this to work?

**Comment by afragen** [comment]
GitHub token helps as this plugin is still checking GitHub API for itself. Not needed for branch switch.

**Comment by afragen** [comment]
GitHub token allows for 5000 API calls/hour vs 60 API calls/hour
