### ISSUE TITLE
hook filter to disable transients

### ISSUE THREAD

**Issue by scarstens** [afragen/github-updater#466]
we don't use transients to cache REST calls, we use a more advanced method stemming from WP_Rest_Cache plugin. the hooks will allow other cache plugins to disable native GHU caching so they can replace it with something smarter / different.

**Comment by afragen** [comment]
Thanks for the PR, the hook call is as follows. It's in `class API`

~~~php
add_filter( 'ghu_use_remote_call_transients', '__return_false' );
~~~
