### ISSUE TITLE
Workflow problem with too many API calls

### ISSUE THREAD

**Issue by scarstens** [afragen/github-updater#468]
If you install 10-20 plugins with GHU headers, and then install GHU, the activation of the plugin does all 100+ api calls. As an admin, you should be given the option to enable a personal access token before the first set of API call fetches.

**Comment by afragen** [comment]
There's sort of a way to do this.

Create a plugin, Config GitHub Updater or something.

Pass the access token in a hook as follows.

~~~php
add_filter( 'github_updater_token_distribution', array(
    'github_access_token' => '230[ihewqvpfuqbwejglqwefdj'
) );
~~~

This will save the information into the correct option. Once this is saved you can remove this plugin as the data will now be saved in the options table.

**Comment by afragen** [comment]
If you install GHU first you get the benefit of being able to install your plugins and themes via the Install tab and have correct renaming. 😉
