### ISSUE TITLE
Force check not working

### ISSUE THREAD

**Issue by yeomann** [afragen/github-updater#474]
Great plugin guys,

Sorry, but i'm not seeing notification for update after clicking on check again under updates. Until, I refresh transients and go back to click again check again and come to plugin tab and refresh it multiple times or click on check again multiple times.

I thought it'll be easy like:

1. Push on Github.
2. come to admin panel under Updates click on check again. 
3. and It'll show you update notification.

ps: Selecting master branch for github-updater made my plugin file not exists, after some digging i realize through ftp that It changes folder name and even added "github-" prefix in start of folder name. Therefore, I changed my repo name in git to start with github prefix follow by the name github-updater created in plugin directory. and also selected develop branch. Now, it updates fine without file not exists error. Is it a normal behavior?

**Comment by afragen** [comment]
I believe much of this behavior has been fixed in the `develop` branch. I'll likely be releasing it within the next few days. If you want to switch to it and see if those issues still exist, please let me know.

**Comment by afragen** [comment]
That last part is not expected behavior and I think has been corrected in the develop branch.

**Comment by cferdinandi** [comment]
Not sure if you pushed an update recently, but I was having this same issue, and it seems to have resolved itself today. I'm on v5.6.2, and the `Refresh Transients` makes updates show up instantly.

**Comment by afragen** [comment]
I'm about to push an update that should make it much better.

**Comment by afragen** [comment]
@yeomann can you upgrade to v6.0.0 and let me know if this is still an issue?

**Comment by yeomann** [comment]
Okay, i have switched to Bitbucket for now. After upgrading, i'm trying to update and have been receiving this error
`Update Failed: The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature`
I'm not sure, what is causing this now. Though after upgrading to v6.0.0, The update notification of plugin come after one refresh, So, it was instant and good. But can you help me with above error. upon google it says that format of plugin which is being download or installed is not zip.

**Comment by afragen** [comment]
This error is an authentication error. If you're now using Bitbucket please confirm that your Bitbucket username and password are correctly set in the Bitbucket Settings tab.

**Comment by yeomann** [comment]
No, i'm using correct password and username but plugin is under `Teams` repo in bitbucket. and also because of that, I can't login in bitbucket using my username, only through my email. Moreover, i don't have any 401 authentication error from your plugin poping up. I remember it shows up if i wrote wrong bit bucket password.

**Comment by afragen** [comment]
@yeomann you must enter a username not an email address in the Bitbucket username field. Go to your Bitbucket settings and see what your username is.

**Comment by yeomann** [comment]
@afragen No! i'm already having username in my plugin bitbucket settings page. After pushing commit to bitbucket, WordPress successfully detects that there is a update. but after clicking on update now, it ends up miserably with this message, 
`Update Failed: The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature
`
I don't know, what is wrong? Can you help me with this? Is there something i'm missing? I have even moved repo from Teams to under my account in bitbucket.

![errorupdate](https://cloud.githubusercontent.com/assets/5970751/19796840/c3698d9e-9cef-11e6-9175-d647a5884620.jpg)

**Comment by yeomann** [comment]
sorry for closing and reopening, was thinking to close this issue and start new with Bit bucket title and issue.
