### ISSUE TITLE
500 Error on Plugin Activation

### ISSUE THREAD

**Issue by icryptix** [afragen/github-updater#476]
I have kind of an odd issue here.

I Activated the github-updater plugin on two WP Multisite's fine. I added the plugin manual to `/wp-content/plugins/github-updater` as described in the directions. They activated and the plugin works fine.

Now I have a 3rd WP Multisite I did the same thing, but the second I hit Network Activate I get a 500 error on the plugins page `(https://example.com/wp-admin/network/plugins.php)` and on the plugin settings page `(https://example.com/wp-admin/network/settings.php?page=github-updater)`

What drives me nuts is on the first 2 networks I did not get that error. So I spent several hours deactivating all my plugins, removing htaccess file, etc. I don't even see an entry in the error log.

So finally I was close to giving up, and I uploaded the plugin again, but this time without renaming it and uploaded it as `/wp-content/plugins/github-updater-master` and sure enough it Activated fine and I can now access the plugins area and the plugin settings menu. The plugin worked and updated my own plugin with it.

My first though was maybe the zip was somehow corrupted, So I tried all over again after downloading a fresh zip from githib and tried this `/wp-content/plugins/github-updater` and sure enough I get the 500 error again. 

So I went ahead, again... and re-uploaded the plugin and activated as `/wp-content/plugins/github-updater-master` and it works again.

Any idea how to resolve this? The plugin works when renamed to **github-updater-master** but now I am assuming I wont get updates for the updater plugin now unless I rename it to **github-updater**

**Comment by afragen** [comment]
500 errors are "Internal Server Errors" usually these resolve over time. What you describe is indeed strange. I'm about to make a new release. So we can see whether or not this persists.

**Comment by icryptix** [comment]
Okay. Thanks for the quick response.

**Comment by icryptix** [comment]
The update to 6.0 solved this. Thanks
