### ISSUE TITLE
MainWP Update installed, but still shown

### ISSUE THREAD

**Issue by marbetschar** [afragen/github-updater#477]
I've noticed one more thing. If I update the Theme by using MainWP it actually updates the theme and the newest version is installed. But: the WordPress instance in question still shows there's an update available and under Dashboard / Updates you can see the following line: "Version installed v0.1.5, newest version available v0.1.5".

**Comment by afragen** [comment]
I'll take a look but I suspect the update just hasn't registered and it should clear with the next cache refresh.

**Comment by afragen** [comment]
I just tested with MainWP and I cannot confirm this. For me the update happens in MainWP and when I go to the site the plugin is updated. I do find MainWP's a little flaky (new update) in seeing updates. Not sure what that's about.

**Comment by afragen** [comment]
Does this still persist?

**Comment by marbetschar** [comment]
Unfortunately yes. I can see the following on my MainWP Dashboard:

<img width="594" alt="bildschirmfoto 2016-10-31 um 15 08 00" src="https://cloud.githubusercontent.com/assets/392542/19857005/3ae47404-9f7c-11e6-98db-daf62cf6befe.png">

But I've also noticed there are new versions of MainWP and MainWP Child available. I'll test those and come back with the results.

**Comment by afragen** [comment]
This seems to be more of an issue with MainWP having issues with its caching and update checking than with GHU. Does this persist if you have MainWP recheck with the child?

**Comment by afragen** [comment]
I've seen this on MainWP recently. A refresh from the child sites fixes it. Seems like a MainWP issue.
