### ISSUE TITLE
Where are the Bitbucket Settings?

### ISSUE THREAD

**Issue by vestaxpdx** [afragen/github-updater#478]
Hi

In the new version I now do not see any bitbucket settings? In 5.6.2 I saw them fine.

Can I confirm that we do not have to install a theme with your plugin? We can simply add the headers to our existing theme styles.css that you mention in the docs and it should still work.

I only say this because I never seemed to get an update message for my theme with 5.6.2. (waited 24 hours) I updated to version 6 thinking maybe this might fix some issues. But now I see no settings for bitbucket at all.

_*Note when I just added headers to my styles.css file I did see my theme listed as installed on the github updater settings page on version 5.6.2 In version 6 I see nothing as I believe the bitbucket settings tab is missing. I only see Github Updater and Github tabs._

Hope you can shed some light.

**Comment by afragen** [comment]
The Bitbucket tab will show dynamically if there's a repo with Bitbucket headers. It sounds like you might have an issue with that. Could you give `afragen` `read` access to the repo so I can take a look?

**Comment by vestaxpdx** [comment]
Just to note, if I go to the 'Install Theme' tab and install a theme that way the bit bucket tab settings appear and lists my theme, however it installs it to a 'projectnamedir/' which is not ideal in my situation. I prefer using a much sorted url of 'v3/'

I have given you Read access.

**Comment by vestaxpdx** [comment]
Ah I may of spotted my own error. Should the Bitbucket Theme URI only be the following as you prepend the user@ when connecting. 

https://bitbucket.org/user/nextelementwptheme.git

**Comment by afragen** [comment]
You can leave off the `.git` too but I strip it regardless.

**Comment by afragen** [comment]
Is it now working?

**Comment by vestaxpdx** [comment]
Hi, 

No sadly no matter what I made the URI the bitbucket settings would never show.

The only way they would is if I used your install theme method, which is not ideal for me as it creates a theme folder name which I have no control over.

I have since decided to go down the bitbucket pipelines route to deploy my code. So I do not mind if you close this or if you suddenly know why I can't get them to show I would be interested to know.

Many thanks for a great plugin though!

**Comment by afragen** [comment]
A theme's directory and slug must match for any updates to show.

**Comment by vestaxpdx** [comment]
Ah this was probably it I did not see that mentioned in the docs so figured it would be fine if I used a shorter theme directory.

Thanks for the help.

**Comment by afragen** [comment]
Glad it's working.
