### ISSUE TITLE
Refresh transients happens again on screen refresh

### ISSUE THREAD

**Issue by scarstens** [afragen/github-updater#479]
After clicking refresh transients, if you refresh the next screen it continues to delete transients again.

I'd suggest either doing a redirect so the query is no longer in the URL after it clears OR switch to POST.

**Comment by afragen** [comment]
I think this should solve that problem once and for all. :fingers_crossed:
https://github.com/afragen/github-updater/commit/8addec5b4aadb989f88c470be1b9fe05f5a05a71

**Comment by afragen** [comment]
I switch the refresh over to POST so this shouldn't happen, even with a screen refresh.
