### ISSUE TITLE
Settings: sentence used as title instead of paragraph

### ISSUE THREAD

**Issue by benoitchantre** [afragen/github-updater#480]
I think there's a small markup issue in the settings.

_Private repositories are not installed, are cached, or are using your personal access token._ is an `<h2>` and _Installed Plugins and Themes_ is an `<h4>` (see screenshot below).

![settings](https://cloud.githubusercontent.com/assets/1521015/19796783/065335aa-9ce7-11e6-8b3c-dfe3a43dd3be.png)

It would be better if _Installed Plugins and Themes_ would be an `<h2>` and _Private repositories are not installed, are cached, or are using your personal access token._ a `<p>` (see screenshot below)..

![settings-suggestion](https://cloud.githubusercontent.com/assets/1521015/19796812/38d9fd2e-9ce7-11e6-8fdf-a44c07466a29.png)

**Comment by afragen** [comment]
This text _Private repositories are installed..._ is added in `add_settings_section()` and picks up it's html tags from there. I can change the tag for _Installed Plugins and Themes_. Do you still think h2 is appropriate?

**Comment by benoitchantre** [comment]
Yes, I think h2 is appropriate: I think it has to be the same level as _GibHub Personal Access Token_.

I have also noticed that the GiHuber Updater logo should be surrounded by an h1, not an h2. 

The text _Private repositories are installed..._ is a bit confusing. I clearly understand the first part, but not the rest. Is it necessary to inform the user when there are no private repositories installed?

**Comment by afragen** [comment]
> I have also noticed that the GiHuber Updater logo should be surrounded by an h1, not an h2.

fixed

> The text Private repositories are installed... is a bit confusing. I clearly understand the first part, but not the rest. Is it necessary to inform the user when there are no private repositories installed?

That text was present before I began listing the installed repositories. I guess at this point it really isn't needed.

**Comment by afragen** [comment]
Besides, I just thought of adding a lock dashicon to the end of the repo name if it's a private repo. 👍

**Comment by afragen** [comment]
![screenshot_01](https://cloud.githubusercontent.com/assets/1296790/19833639/e29b9040-9dfd-11e6-89ee-a81206e087fb.png)

**Comment by benoitchantre** [comment]
I think a label at the end of the plugin  name would be more appropriate. It could also be used to display more informations (private, branch name if different than master, local development, ...).
What do you think?

**Comment by afragen** [comment]
That's actually how I originally did it. Which one do you think looks better?
![screenshot_01](https://cloud.githubusercontent.com/assets/1296790/19837308/b428d7f0-9e74-11e6-9584-6e9b49c88fe9.png)

Putting the branch would be inconsistent as it's only accurate if it's designated in the branch header. You can see the current branch listed in the plugins page when branch switch is checked.

https://wordpress.org/plugins/local-development/

**Comment by benoitchantre** [comment]
Icons before the name are better, but only one icon would be the best: either one icon to mean private plugin / private theme or the actual plugin / theme icon and a label (or text) after the name.

Here's an example of what it could look with a label.

![b428d7f0-9e74-11e6-9584-6e9b49c88fe9](https://cloud.githubusercontent.com/assets/1521015/19840010/246c53ca-9eed-11e6-897f-ae519883d2b7.png)

**Comment by afragen** [comment]
I think I like one icon in front of the name better. But I'm not convinced a text label after is better. I like the lock icon. Everyone understands its meaning and no extra strings.

**Comment by benoitchantre** [comment]
Ok, thanks for the discussion.

**Comment by afragen** [comment]
I reverted back to putting the lock icon behind the name. I agree, I think it looks better.
