### ISSUE TITLE
update failed

### ISSUE THREAD

**Issue by yeomann** [afragen/github-updater#481]
i tried to update to new version 6.0.2 from 6.0.0 and got this error. See picture as well for what happen afterwards. 

`Update Failed: Rename successful using extended name to github-afragen-github-updater&#8230;`

![screenshot from 2016-10-28 12 52 10](https://cloud.githubusercontent.com/assets/5970751/19802701/9cd13bc8-9d0d-11e6-988e-840bee68e6c1.png)

edit: i can't enable github-updater plugin now. i tried to rename from ftp and then tried to enable it from wp admin. but it pops the same error like above picture.  i'm going to download now 6.0.0 release from GitHub and hope everything will be fine. 

edit: so yeah github-updater 6.0.0 is working fine.

**Comment by afragen** [comment]
This may be related to #482

**Comment by afragen** [comment]
Is there some reason you're using the extended naming? It's really there only to avoid slug conflicts with the .org repo.

**Comment by afragen** [comment]
The above error is due to the new optimize transients. Using the branch switch to jump between branches should automatically refresh the cache. This is the error you see.

How were you changing from master to develop?

**Comment by afragen** [comment]
If this or similar error returns I wrote a _one off_ plugin to fix it. 

https://github.com/afragen/clear-github-updater-cache

**Comment by yeomann** [comment]
> Is there some reason you're using the extended naming?

_i was just testing with it._

>changing from master to develop?

_Can't see still this option, even downloaded new repo from github. After unzipping downloaded zip, Folder name was github-updater-develop. With that no switch branch option came up. Even i renamed to   github-updater and same no branch switch option._

So, Here's what happened. I downloaded new github-updater from repo with version 6.0.0.4. upon first activation it throws error and made my plugin panel inaccessible. See picture for that below.
![onactivateerror](https://cloud.githubusercontent.com/assets/5970751/19847654/193b7044-9f51-11e6-8a36-25ff6fa65de6.png)

After using your clear Transients above [mentioned plugin](https://github.com/afragen/clear-github-updater-cache). It did the trick and i was able to activate github-updater plugin successfully. It also detected update changes for my private bitbucket repo and did Update only from update-core not from plugin panel but after updating, It disabled my plugin. I will close this issue so we can follow up at issue #482
