### ISSUE TITLE
Fatal error in WP Updates after upgrade to 6.0.0.3

### ISSUE THREAD

**Issue by yaronguez** [afragen/github-updater#483]
After upgrading to 6.0.0.3, I receive a fatal error whenever I visit the WordPress Updates page:
`( ! ) Fatal error: Cannot use object of type stdClass as array in /public_html/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 1046`

**Comment by yaronguez** [comment]
Sorry, I don't understand. All I did was click update plugin. What do I
need to do to fix it?

Yaron Guez
Software Architect
(781) 249-4709

**Comment by DuckDivers** [comment]
I also had the current branch set as DEVELOP and got this error after updating:

Fatal error: Cannot use object of type stdClass as array in /plugins/github-updater/src/GitHub_Updater/GitHub_API.php on line 147

**Comment by afragen** [comment]
I'm sorry guys. The quick solution is to clear out all the transients from the database. I made a quick plugin to do that.

Install and activate. The plugin will automatically deactivate. GitHub Updater should automatically rebuild the transients and hopefully the issue will be resolved.

https://github.com/afragen/clear-github-updater-cache

Please let me know.

**Comment by DuckDivers** [comment]
That worked for me.  Thanks!

**Comment by afragen** [comment]
Great! Sorry it was necessary.

**Comment by yaronguez** [comment]
Thanks for the quick fix!
