### ISSUE TITLE
Feature: GHU Plugin Marketplace

### ISSUE THREAD

**Issue by scarstens** [afragen/github-updater#484]
After surfing .org plugins over the weekend, it made me think we could give ourselves a way to provide "github.com hosted plugins marketplace" where you can search for plugins outside of the .org marketplace, but with the same easy 1 click install process available inside WordPress.

The idea would be to host a repo / file that can be contributed to that lists all official "plugins". Alternative / more advanced would be to allow people to paste in custom URL's that allow remote fetching and indexing of these plugins. The idea is... borrowed from another project, screenshots attached:
![image](https://cloud.githubusercontent.com/assets/1483300/19912261/62d43bcc-a056-11e6-9993-1a75364b2875.png)
![image](https://cloud.githubusercontent.com/assets/1483300/19912354/14c52210-a057-11e6-9855-0eb1b9e2aee4.png)

**Comment by afragen** [comment]
Take a look at https://github.com/pdclark/github-plugin-search

**Comment by backamblock** [comment]
the last update in this repo is from 2014. 
what is the current recommended way to find github plugins? is there any site or search filter available?

**Comment by afragen** [comment]
@backamblock there isn't one.

**Comment by backamblock** [comment]
@afragen thank you. how do you find them personally?

**Comment by afragen** [comment]
I follow lots of developers on GitHub.

**Comment by chesio** [comment]
@backamblock One way to discover some WordPress plugins hosted on GitHub is to have a look at https://github.com/topics/wordpress-plugin.
