### ISSUE TITLE
"Plugin file does not exist" error when updating plugins

### ISSUE THREAD

**Issue by cferdinandi** [afragen/github-updater#485]
Whenever I update my plugins with GitHub Updater, I get an error message similar to this one:

> The plugin `cferdinandi-gmt-wordpress-for-web-apps-3c79373/wordpress-for-web-apps.php` has been deactivated due to an error: Plugin file does not exist.

I'm on version 6.0.0.

**Comment by afragen** [comment]
That is likely because the initial directory was not renamed correctly and _hopefully_ now it is. You can check this by looking at the activation link or using FTP.

**Comment by cferdinandi** [comment]
How might I look at the activation link? I actually tried uninstalling the plugin altogether, deleting the directory via FTP, and reinstalling fresh via GitHub Updater a day or two ago (still with v6.0.0). The problem persists.

Yesterday I pushed about 5 or 6 smaller plugin revisions, updating each time, and each time, the problem reoccured, so I'm not sure the naming problem is fixed.

**Comment by afragen** [comment]
Can you share a link so I can test?

Installing via GHU should result in a correctly directory.

**Comment by cferdinandi** [comment]
That is how I installed, actually. Link to one of the plugins for which I'm experiencing issues?

https://github.com/cferdinandi/gmt-wordpress-for-web-apps

**Comment by afragen** [comment]
I can replicate this. I'll test more when I get back to a computer.

**Comment by cferdinandi** [comment]
(thumbsup) Thanks!

**Comment by afragen** [comment]
So here's the problem. Your plugin repo is `gmt-wordpress-for-web-apps` and your plugin slug is `wordpress-for-web-apps`. You are probably doing some forwarding that's causing the issue.

**Comment by afragen** [comment]
Just change the header to `GitHub Plugin URI: https://github.com/cferdinandi/gmt-wordpress-for-web-apps` and it should work.

**Comment by cferdinandi** [comment]
Ohhhh... I updated the names of a bunch of these in GitHub and must have forgotten to update the plugin headers.

GitHub seems to autoforward, so I didn't even notice. Thank you for catching my own stupidity!

**Comment by denishowe** [comment]
I was getting this error after installing a plugin because my URL was mapped to a load balanced server farm.  This is a Bad Idea.  You need to be always hitting the same web server, otherwise you'll be installing/uploading stuff on one server then wondering why you can't see it when your request goes to another server.

**Comment by marcusquinn** [comment]
might help others fixing this issue, or similar: https://github.com/wpallstars/wp-fix-plugin-does-not-exist-notices
