### ISSUE TITLE
Version 6.0.0.5

### ISSUE THREAD

**Issue by pftaylor61** [afragen/github-updater#486]
Version 6.0.0.5 caused me to lose all dashboard items in the first two of my sites, in which I updated Github Updater. I stopped updating, and checked plugins - it was only the Github Updater which caused the dashboard items to disappear. So I deleted it, and returned both sites to version 5.6.2.9. Both sites worked again.

I have not got around to investigating the source code in the plugin.

**Comment by afragen** [comment]
What do you mean dashboard items?

**Comment by zandergrin** [comment]
its broken my site - I get a 501 error on my plugins page. Can't use it now.

**Comment by afragen** [comment]
@zandergrin HTTP 5xx error codes are usually server related issues. Please create a new issue and provide background information.

**Comment by zandergrin** [comment]
Well - its a server related issue that only occurs on the latest version of the plugin. We normally get 5xx pages for php errors if debugging isn't on.

Will start a thread when I get a chance - for now I rolled back.

**Comment by moseley** [comment]
I too am have been struggling with the update as well. I get the following error message...
`Fatal error: Cannot use object of type stdClass as array in /var/www/html/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 1053`

**Comment by afragen** [comment]
Depending upon how you updated to 6.0.0.5 you will get this error if the transients haven't cleared. To clear the transients install and activate https://github.com/afragen/clear-github-updater-cache then reactivate GHU.

**Comment by moseley** [comment]
Thank you @afragen it worked! And thank you for the great plugin.

**Comment by afragen** [comment]
@pftaylor61 are you still having problems? It would be best to update from 5.6.2.x to master and then to the current develop.

**Comment by afragen** [comment]
@pftaylor61 I've fixed the latest develop branch so that you should be able to update to it directly.

**Comment by pftaylor61** [comment]
Version 6.0.0.8 works perfectly. Thanks!
