### ISSUE TITLE
Hooking in to auto update after a version is pulled from a repo

### ISSUE THREAD

**Issue by WhereBeTheDan** [afragen/github-updater#487]
Is there any way to configure this? The ability to push out the code is amazing, but to then go hit 'Update' across a large number of sites could be problematic. I know there are 3rd party solutions to this like ManageWP, but is there any way to just run the update off of a built in hook?

**Comment by afragen** [comment]
You could probably set a filter as referenced in the Codex, https://codex.wordpress.org/Configuring_Automatic_Background_Updates

**Comment by WhereBeTheDan** [comment]
Yeah, I had tried that but I guess I had a misunderstanding of how that hook operates. Looks like it also runs off of transients on a 12 hours schedule. I'll look into it further, thanks for the advice and great plugin.
