### ISSUE TITLE
Broken changelog links with InfiniteWP

### ISSUE THREAD

**Issue by Zodiac1978** [afragen/github-updater#488]
![bildschirmfoto 2016-11-10 um 12 28 42](https://cloud.githubusercontent.com/assets/870475/20175061/41e803c0-a741-11e6-9b70-41b1a85206fe.png)

These changelog links are 404s for non-wp.org plugins:
https://wordpress.org/plugins/github-updater/changelog/

As there is no standard, maybe this can be fixed with an additional config line to configure an individual link?

**Comment by afragen** [comment]
As this is a function of InfiniteWP I don't have the ability to fix it. It does work within the wp-admin dashboard.

**Comment by Zodiac1978** [comment]
Of course it is :)
I have opened a ticket there too (#57624) and I think together we will find a better UX than a broken link for every non-wop.org plugin.

**Comment by afragen** [comment]
But how do you think it could/should work? It works on the admin dashboard because the data is in your install. In InfiniteWP the _data_ is retrieved from .org. This data only exists in the proper format in your database.

**Comment by scarstens** [comment]
I agree, the fix cannot be done in this plugin. This is a function of infiniteWP where it falsely assumes all plugins are from WordPress.org. Nothing to be done here.

**Comment by Zodiac1978** [comment]
If InfiniteWP is willing to provide a fix for this, the question is: Which link is used here? And maybe you can help to make this link/data available per extra config line:

> As there is no standard, maybe this can be fixed with an additional config line to configure an individual link?

I'm just trying to start a conversation here. Hopefully the InfiniteWP team will join it. I send them the link to this issue in my support ticket.

**Comment by afragen** [comment]
I appreciate your efforts, truly, but internally, GHU creates and adds a plugin update row containing a local link to the view details. The data from this link is generated by GHU and hooks into the local WP install via plugins_api filter hook. There is no way to send this data to a remote WP installation.

**Comment by afragen** [comment]
The link generated by GHU is like the following.

`http://single-test.dev/wp-admin/plugin-install.php?tab=plugin-information&plugin=github-updater-tester&section=changelog&TB_iframe=true&width=600&height=800`

**Comment by Zodiac1978** [comment]
Got an email from the support of InfiniteWP:
> Thanks for bringing this issue to our notice. I have noted this issue as a bug. This will be fixed in the upcoming update releases of IWP admin panel. 

I don't know how this will be fixed, but it seems there is a way. :)

**Comment by afragen** [comment]
Please let us know.

**Comment by Zodiac1978** [comment]
I will report here when the update arrives.

**Comment by devbabuind** [comment]
Hi @Zodiac1978 @afragen
I have confirmed this as a bug in our product . We are working on a fix . Next release should have this fix. Thanks for the reporting 
Regards
Babu M
Developer - InfiniteWP
