### ISSUE TITLE
Add GHU settings page to admin bar navigation

### ISSUE THREAD

**Issue by scarstens** [afragen/github-updater#489]
Would like a quick shortcut to GHU settings page in the network navigation in the admin bar.

![image](https://cloud.githubusercontent.com/assets/1483300/20201328/5777172a-a774-11e6-8c77-25f209896a5b.png)

**Comment by afragen** [comment]
The normal _My Sites_ menu only has a single level to its menus. You're running another plugin that is giving you what you currently see. The question should be, in the plugin that gives the added menu level why doesn't it pickup **all** the Settings submenus?
