### ISSUE TITLE
Question: With Github Updater 6.0 is folder name now tied to repo name

### ISSUE THREAD

**Issue by garrett-eclipse** [afragen/github-updater#490]
Hello,

I was previously using 5.6.2 and updated to 6.0 before I was going to do the theme update that is handled through Github Updater. After updating to 6.0 I was unable to get the theme update to show.

Rolling back to 5.6.2 the theme update was available again but installed into a new folder with the repo name as folder name.

Going back up to 6.0 and changing the folder name of my theme to match the repo name the updates became available again.

So my question is with 6.0 is the theme folder name now tied in with the repo name?

If that's the case can we update the readme to indicate this relationship, please. There's some text about it for plugins but wasn't blatant especially concerning themes. The text about plugins;
> When first downloading and installing a plugin from GitHub you might have to do the following, otherwise the next update may not be able to cleanup after itself and re-activate the updated plugin or theme. Or you can just use the remote install feature and this will be done for you. 😉
> 
> Unzip the archive.
> Fix the folder name to remove to extra stuff GitHub adds to the download, like -master.
> Copy the folder to your plugins directory or re-zip folder and add from plugins page.

Thank you

**Comment by afragen** [comment]
Hey Garrett, this is actually in the wiki and has been in the README before. https://github.com/afragen/github-updater/wiki/Usage

> Themes

> There must be a GitHub Theme URI, Bitbucket Theme URI, or GitLab Theme URI declaration in the style.css file. When initially adding a theme, the directory must be identical to the repo name.

Is there some other phrasing that I can put in to make it better?

**Comment by afragen** [comment]
I added some new language to https://github.com/afragen/github-updater/wiki/Usage

I hope it makes things clearer.

**Comment by nightbook** [comment]
Thanks @afragen, sorry I completely overlooked that. 

I appreciate you pointing that out. Can definitely close this up and attribute it to a long day.
