### ISSUE TITLE
Feature Request - Provide option for supporting non-standard ports or unsafe urls

### ISSUE THREAD

**Issue by garrett-eclipse** [afragen/github-updater#491]
Hello,

I noticed this previously and through alot of digging found a workaround and potential solution.

Issue - With Gitlab installed over a non-standard port 8181 Wordpress blocks the download and displays an error (Update Failed: Download failed. A valid URL was not provided.)
![screen shot 2016-11-10 at 9 30 11 pm](https://cloud.githubusercontent.com/assets/8726005/20205389/39188912-a78d-11e6-8f1e-4083ae93b51f.png)

This error led me to a few threads/articles online;
http://www.emanueletessore.com/wordpress-download-failed-valid-url-provided/
http://wordpress.stackexchange.com/a/123313
https://core.trac.wordpress.org/ticket/24646

Through these threads I discovered that it was Wordpress blocking the call through download_url as it was running the wp_http_validate_url that checks ports (https://github.com/WordPress/WordPress/blob/93f7f904ec32a12531d25b3a76f6fdb974507d43/wp-includes/http.php#L575);
`if ( 80 === $port || 443 === $port || 8080 === $port )`
*So Wordpress only supports the ports 80, 433 and 8080 and my Gitlab is through 8181

To work around this issue for our theme I added the following;
```
function allow_unsafe_urls ( $args ) {
	$args['reject_unsafe_urls'] = false;
	return $args;
}
add_filter( 'http_request_args', 'allow_unsafe_urls' );
```

As Github Updater supports hosted installs of Gitlab it might be an idea to provide an option to support a specific port or simply just allow unsafe urls. Probably not the most secure to just allow any url so I'll leave the logistics but am happy to discuss.

If an option is added it would be great if it can also be handled programmatically like the github_updater_token_distibution;
function setup_gitlab_token() {
    return array( 'gitlab_enterprise_token' => 'XXXXX' );
}
add_filter( 'github_updater_token_distribution', 'setup_gitlab_token' );
*That way it can be part of the theme and not an admin step.

Thoughts?
Thanks
Sitenote - This may be the core issue behind #421.

**Comment by afragen** [comment]
It seems like a great little plugin. You should package the code and put it in the .org repo as something like _Allow Non-Standard Update URLs_.

Great detective work and finding a solution.

**Comment by garrett-eclipse** [comment]
Good call, thanks @afragen
