### ISSUE TITLE
Feature Request - Enable Support for direct inclusion in Themes/Plugins

### ISSUE THREAD

**Issue by garrett-eclipse** [afragen/github-updater#492]
Hello,

This plugin has been a godsend, so firstly thank you.

I would like to request that the Github Updater plugin support direct inclusion in themes/plugins similar to ACF;
https://www.advancedcustomfields.com/resources/including-acf-in-a-plugin-theme/

I realize the plugin already supports being a Must Use Plugin, but that requires some set-up and linking.
https://github.com/afragen/github-updater/tree/6.0.0#install-github-updater-as-a-must-use-plugin-optional

What I'm seeking is to remove additional set-up steps upon install. Currently, I run a bash script to install Wordpress, our theme and the Github Updater. But on existing sites I manually install our theme and the Github Updater. By providing a way to include Github Updater directly into our theme it would streamline our set-up.

Just an idea I wanted to share.

Thank you

**Comment by afragen** [comment]
I've written a light framework to install optional and required plugin dependencies. You should take a look at it. 

https://github.com/afragen/wp-dependency-installer

**Comment by garrett-eclipse** [comment]
Thanks @afragen, that's exactly what I need for Github Updater among other plugins. I'll check it out

**Comment by afragen** [comment]
If you setup many sites similarly you could create a _site setup plugin_ to run once, have it install everything, and then remove it.

**Comment by garrett-eclipse** [comment]
Good call, been using wp-cli with our bash install script. It'd be fun to figure out how to trigger the setup plugin to run wp functions. Thanks for the idea

**Comment by afragen** [comment]
FYI, I just finished making https://github.com/afragen/wp-dependency-installer a composer package. Refer to README, `wp-dependencies.json` now at plugin/theme root.

**Comment by garrett-eclipse** [comment]
Thanks @afragen
