### ISSUE TITLE
Readme Update - Add info about programatically setting branch_switch

### ISSUE THREAD

**Issue by garrett-eclipse** [afragen/github-updater#493]
Hello,

I love that Branch Switching has become an option;
https://github.com/afragen/github-updater/tree/6.0.0#branch-support

But can a programmatic example be provided as I only found the solution via trial and error.

It seems you can use the github_updater_token_distribution filter to enable branch_switch as follows;
function enable_branch_switch() {
    return array( 'branch_switch' => '1' );
}
add_filter( 'github_updater_token_distribution', 'enable_branch_switch' );

Appreciated,
Cheers

**Comment by afragen** [comment]
You could do exactly as you've outlined, but it you go to the Settings you should see where the option is set. BTW, branch switch just got an overhaul with 6.0.0 but it's been in the plugin for a while.

https://github.com/afragen/github-updater/wiki/Versions-and-Branches

BTW, I recently moved most of the README to the Wiki as the README was becoming more difficult to navigate. The new, much abbreviated README has a link to the wiki.

**Comment by nightbook** [comment]
Thanks @afragen, good call with the wiki it looks great. Is there a full list of options that can be set via php?

**Comment by afragen** [comment]
There isn't a full list but anything that is stored in `github_updater` option can be set.

**Comment by garrett-eclipse** [comment]
Thanks @afragen 
And a minor thought, as any option can be set in that method would it make sense to deprecate the 'github_updater_token_distribution' filter and replace it with something more generic 'github_updater_options' or something?
Cheers

**Comment by afragen** [comment]
That's certainly doable.

**Comment by afragen** [comment]
Take a look at branch `deprecate-token-hook`, replaces with 'github_updater_set_options' filter.

**Comment by garrett-eclipse** [comment]
Thanks @afragen 
Should $config be piped into the deprecated filter in the very off chance that someone uses both filters or maybe has a plugin using the older filter and their theme uses the newer. As is right now if someone has the new filter in use and the old then anything set via the new filter will be overwritten by the old filter.
Cheers

**Comment by afragen** [comment]
Good point

**Comment by afragen** [comment]
https://github.com/afragen/github-updater/commit/d97018acd1da3dcd1609698254a2a51e2440028e should take care of this until we require WP 4.6 for using this plugin, which we can do.

**Comment by afragen** [comment]
> As is right now if someone has the new filter in use and the old then anything set via the new filter will be overwritten by the old filter.

They would have to use both filters in the same plugin/theme for this to happen.

**Comment by garrett-eclipse** [comment]
Thanks @afragen

**Comment by afragen** [comment]
Merged. https://github.com/afragen/github-updater/commit/f64cef6051a7f9f2b248035fd3bda29028e7c3fc
