### ISSUE TITLE
Error on plugin install

### ISSUE THREAD

**Issue by JayHoltslander** [afragen/github-updater#494]
Using 6.0.0 I'm getting the following error when trying to add a plugin from GitLab through the "Install plugin" tab.

> Downloading install package from http://[domain.com]/[User]/[Plugin]/repository/archive.zip?ref=master&private_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx…
>
>Unpacking the package…
>
>The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature

**Comment by afragen** [comment]
That's usually an authorization issue. Can you recheck your GitLab Access Token?

**Comment by JayHoltslander** [comment]
That was indeed the issue. I hadn't created the correct token. (First time in GitLab.)
Thanks for your help.
