### ISSUE TITLE
Can't see plugin's available update.

### ISSUE THREAD

**Issue by JayHoltslander** [afragen/github-updater#495]
I've read through the Wiki and I believe I've done everything correctly here.

My plugin header has:
```
GitLab CE: https://gitlab.myhost.com
GitLab Plugin URI: https://gitlab.myhost.com/[user]/[plugin-repo]
```
The repo contains a newer version of my plugin than what I successfully remote installed, but my test Wordpress site doesn't see the available update.

Am I missing something?

**Comment by afragen** [comment]
Have you tried refreshing the cache? Under normal circumstances transients aren't saved for 12 hours.

**Comment by JayHoltslander** [comment]
I did try that, yes. Tried again just now just to be sure. Still no update visible.

**Comment by afragen** [comment]
Can you show the headers of the local file and the headers of the remote file?

**Comment by JayHoltslander** [comment]
[![](http://cdn.skunkworks.ca.s3.amazonaws.com/temp-screenshots/skunk-logout.php_2016-11-16_10-14-00.jpg)]
(http://cdn.skunkworks.ca.s3.amazonaws.com/temp-screenshots/skunk-logout.php_2016-11-16_10-14-00.jpg)

**Comment by afragen** [comment]
I wonder whether or not you have an issue with SSL? GitLab CE visible at `http://git.skunk.ws` but not at `https://git.skunk.ws`

**Comment by afragen** [comment]
Any further debugging and I'll likely need a temp account.

**Comment by fatjester** [comment]
Just an FYI for other having these issues:
I was having issues with updates not being seen, and the cache refresh not seeming to work as well.

It turned out that the installation was using redis object cache, and it seems that was interfering with items updating.

**Comment by afragen** [comment]
@JayHoltslander I'd really like to make sure this is working for you. I may need an account on your GitLab CE installation to test though.

**Comment by JayHoltslander** [comment]
@afragen Sorry about the delay. Been super busy. Just created an account for you. Check your email.

**Comment by afragen** [comment]
Jay, I was able to install the plugin manually. After installation I did have to rename the directory because the initial download and install was in the format `<slug>-<branch>-<hash>`. I then made sure I had a proper token from git.skunk.ws User Settings > Access Tokens

 I renamed the repo to just `<slug>` in this case `skunkworks-plugin-logout-destination`. Everything seems to work now.
