### ISSUE TITLE
Need some clarification on updater when plugin is hosted on wp.org and Github.

### ISSUE THREAD

**Issue by nextgenthemes** [afragen/github-updater#496]
https://github.com/afragen/github-updater/wiki/WordPress.org-Directory

I just read this but I am not sure how this will actually work.

So if my plugin is on wordpress.org and I have a newer version on github in master, will it update or not? Or does preference mean it just will download the newest version from wp.org or the latest tag on master is the same as the wp.org version?

Its this plugin included in themes other plugins? I just had a user who never heard of the github updater who gets my beta versions without intention.

Can I disable the Github Updater for my plugin only with a hook? I am thinking of a "Use github updater for beta updates" option. I would like to have the github updater data in the plugin header even for the wp.org version but not simply force it on everyone who has it installed, but that seems to be the case even with master branch.

**Comment by afragen** [comment]
> So if my plugin is on wordpress.org and I have a newer version on github in master, will it update or not? Or does preference mean it just will download the newest version from wp.org or the latest tag on master is the same as the wp.org version?

I think it will download from .org, but if you've pushed to `master` shouldn't you also update .org?

> Its this plugin included in themes other plugins? I just had a user who never heard of the github updater who gets my beta versions without intention.

I've had other users include parts or all of GHU in their projects. I don't know if this is the case with your user. Are you sure it's not installed?

> Can I disable the Github Updater for my plugin only with a hook? I am thinking of a "Use github updater for beta updates" option. I would like to have the github updater data in the plugin header even for the wp.org version but not simply force it on everyone who has it installed, but that seems to be the case even with master branch.

If you designate a branch for the beta and the user has installed that beta version, and the `GitHub Branch` header designates that branch. Then the only updates that user will see is those to that branch.

I have GHU data in many plugins on .org. I do keep my `master` branch and my .org release in sync, so updates occur from .org.

GHU gets version info from GitHub, but if same plugin is on .org you shouldn't see update until .org is updated. GHU update process should be bypassed.

**Comment by afragen** [comment]
If you're referring to this beta, https://github.com/nextgenthemes/advanced-responsive-video-embedder/blob/revert-23-beta/advanced-responsive-video-embedder.php#L27

I'm not sure how updates are being done at all. You need to have the branch name as the actual branch name. In this case `revert-23-beta` or create another branch `beta`.

**Comment by nextgenthemes** [comment]
Short version:

I can now definitely state that the GHU is in fact updating my plugin clean installed from wordpress.org that is currently version `7.9.8`. (It has the `master` branch defined in the header) As soon install the GHU I get a notice about the latest `7.9.16-beta` that is tagged on the `master` branch (and updated on 2nd try, wrong zip format issue I have reported b4)

No I do not use the `revert-23-beta` and no I do not want to have wp.org with github master in sync. In fact I want to do the opposite.

I think this behavior is actually great if you can introduce a filter to skip plugin checks for specific plugins. Could be helpful for others uses as well.

And no I am using one branch and push versions with -beta prefix there and only push some versions to wp.org that I feel are ready for release, and no I do not want a beta/dev/anything branch. Its to much of a burden to me to branch switch all the time, yeah I know I am not using git properly ... I am just alone working on this and I am fine with just tags on master.

> If you designate a branch for the beta and the user has installed that beta version, and the GitHub Branch header designates that branch. Then the only updates that user will see is those to that branch.

I know that, did that, hated that, it would also require the user to install the plugin again after installing the GHU right? Again, I would prefer a simple switch but not force it on people just because they have the updater installed or a theme plugin code from it without even knowing about it. This seems to be the case for the guy I talked to.

> Are you sure it's not installed?

I choose to trust the guy who told me that he never heard of it has it not installed, I do not have access to his site so I cant be sure.

**Comment by afragen** [comment]
Let me test.

**Comment by afragen** [comment]
So here's what I found. Initially, the plugin would show an update. But upon reloading the plugin page or the update core page the plugin will no longer show an update. I think this is because on the initial pass just after the plugin is installed, it doesn't yet set the variable for `dot_org = true`. On subsequent passes this is set as it will be if the cache is refreshed.

Use git the way you want. It shouldn't make a difference here.

Not sure about what to tell you about your friend's site without looking at his plugins and themes.

**Comment by afragen** [comment]
![screenshot_01](https://cloud.githubusercontent.com/assets/1296790/20325317/fc9bc2e2-ab38-11e6-9b0c-fb0702a9237f.png)

**Comment by nextgenthemes** [comment]
Are you dodging?

Can we now agree its a bug in your plugin? What you thought is not true is actually not really. I just tried to try it again with refresh to check of the message then disappears by deleting my plugin, deactivating GHU. Reinstalling the wp.org version and then activated the GHU but I am getting no notice now, may be due to caching or that this `dot_org = true` is set now. I don't know how your plug-in works.

Its not really about my "friends site" in that sense. Its actually a customer of my pro addon if that matters. I could ask him for access to his site but do not see any reason to. I found a bug in your plugin that caused him pain. It does not matter where the actually code sits because I could reproduce this without him. He maintains a lot of sites and was referring to this as some "magic" shows him beta updates, he thought they were from wp.org. And it looks like you never intended this. So its a bug that should be fixed or not?

**Comment by nextgenthemes** [comment]
Maybe just a simple workaround like `on first run assume wp_org = true`

**Comment by afragen** [comment]
Please test `develop` branch 6.0.0.10 https://github.com/afragen/github-updater/commit/05aede8de2850d1d380aa6381d6ce26d680f9910

**Comment by afragen** [comment]
> I know that, did that, hated that, it would also require the user to install the plugin again after installing the GHU right? Again, I would prefer a simple switch but not force it on people just because they have the updater installed...

BTW, this is exactly what the branch switch feature is for.

**Comment by scarstens** [comment]
I'm a little confused @nextgenthemes . Why are you putting a github updater meta line in a plugin where you want version control to be handled on .org via SVN? To me, it seems like you need to decide where you want your updates to come from, instead of trying to force this plugin to cherry pick for you. You have some special use case?

**Comment by nextgenthemes** [comment]
@scarstens let me clarify.

1. My intention was to "force it on people" who have the updater installed. My assumption was that the GHU does exactly that, and it in fact did at least after its first activation as we worked out here, even with master branch. The users who install it are likely the ones who install or for the reason I tell them to so they get beta updates. And to be honest I thought those  who install it for others plugins will get my betas and I have a few more beta testers that way (evil me) I guessed that number was super low but I have no real clue on how many of my 50000 installs have the GHU installed for other reasons.
2. Then I pushed out betas with fatal errors in it a customer who maintained many sites thought I pushed a new beta to wp.org almost every day and then one version crashed his sites ...
3. Then I thought about my decision and wanted to find out about filters in the GHU to prevent then, this lead me the the wiki page that tells me that this forced Github Updates should actually *not* happen on master and figured its a bug.
4. I filed this issue, tested it properly and I was right it was a bug.

I tried to use the plugin like its supposed to be work according to the wiki, it has **extra code to specifically prevent updated from Github when there is any wp.org version** so you talking about that I am supposedly trying to force to plugin to do something strange I should not. The plugin has actually "cherry picking code" in it! wp.org is the cherry, it picks it over any Github version when on master. (now)

I assume @afragen did implement it so people can work on the plugin on github and use the master branch as release/stable branch but use wp.org for distribution, disabling Github to test if they wp.org works, get those wp.org stats counting ... and maybe other reasons.

Maybe cherry picking is the right term.

So with it now fixed we can have forced Github versions upon install of GHU simply by setting the branch to anything but master (in wp.org version) and not forced by setting it to master.

Well read on ...

@afragen 

Tested 6.0.0.10 and it worked thanks you very much. I hope this I prevents a headache for someone in the future because I think I will not even make use of this fix code now.

So lets say I rename my master branch to beta, omit the the branch header (or leave it set to master) even if that branch will not exists but leave the Github URL header.
Can I then tell people (with wp.org version) to install the GHU and "switch" the branch to the one and only beta branch? If true then there would be a easy way to give my users a opt in beta. But with no master branch there would be no easy way to downgrade back to wp.org version (they would essentially be Github master version and not wp.org right?). Thats why it actually does matter is they are in sync or not right?

So that is what I mean with "I use git wrong"

> Use git the way you want. It shouldn't make a difference here.

At the time you told be that it mattered a lot obviously. I thought about it and even now with this fixed it matters I guess because lets assume the the wp.org API is not reachable (DNS problems, Maintenance, ...) then updates will come from Github, meaning that unintended upgrades are still possible, even if unlikely to actually happen. So if my assumptions are right I now think master and wp.org should actually really in sync and it should be mentioned on the wiki that doing other things may have unforeseen consequences. 

So I think I will now do:

* Maintain master+beta branches and merge the versions I release on wp.org b4 that into master. Can I tag on another branch and then merge? I am still a Git noob.
* Or I just tell people to delete and reinstall from wp.org to downgrade. Assuming the "switch" works if I just have one beta branch I will work on.

Thanks again should have went with branch switching

**Comment by afragen** [comment]
It was always my intent for w.org to override GHU as a download source if the repo's branch was set to `master`. If this is the case GHU will *never* update. At least, originally that was the intent. Your example showed an edge case that I had not anticipated. Now fixed.

The only advantage your users will have is from GHU is by using the branch switching they would be able to re-install or switch between branches without difficulty. 

Any repo without a specified branch header will assume `master` and would only then receive and update if an update is pushed to w.org. Your w.org hosted plugin will never receive an update from GitHub unless it is on a branch other than `master`.

**Comment by afragen** [comment]
I still need to do a bit more testing.

**Comment by afragen** [comment]
I basically just overhauled how I check for wp.org plugin info. It's much more deliberate. 

Everything seems to work as expected but since your now matching version numbers in dot org and on GitHub I can't test our previous problem. I think it should still work.
