### ISSUE TITLE
Brach swiching fails on Firefox 49.0.2 Ubuntu 16.04

### ISSUE THREAD

**Issue by nextgenthemes** [afragen/github-updater#497]
This is what I get when I click the 'try another version' link.

![bildschirmfoto vom 2016-11-17 13-10-37](https://cloud.githubusercontent.com/assets/1780826/20388998/b89c9ed2-acc7-11e6-8a79-4ec9ff7c113a.png)

tried versions 6.0.0 and 6.0.0.11, new clean Firefox profile, works on chromium.

This JS on href or on onlick is outdated practice AFAIK but it should work anyway I guess. No idea why this happens.

**Comment by afragen** [comment]
I've tested this on Firefox 50.0 (current release) on macOS. And it works fine. Can you update Firefox and try?

**Comment by robertvidrine** [comment]
I am getting this same error message on a Win 8.1 system with Firefox 50.0. This feature definitely worked previously, though I haven't yet downgraded my copy of GHU to see in which recent version it still worked. This function works fine in Chrome 56.0.2922.0 canary (bleeding edge build).
I love this plugin by the way! It is a great help in developing new themes and plugins. Thank you!

**Comment by afragen** [comment]
Sorry I initially looked in the wrong area. I can confirm Firefox not working 😩

reverted https://github.com/afragen/github-updater/commit/05b89ce48f97c9394b941d040af415ed1d99ab58
