### ISSUE TITLE
Dynamically set Bitbucket username, password and private repo checkbox

### ISSUE THREAD

**Issue by teolaz1990** [afragen/github-updater#498]
Hi @afragen , just a question...
I'm developing a custom wp theme, i installed my required plugins (included github-updater) via the tgm-plugin-activator, and i can see my theme under GitHub settings --> Bitbucket page.

As my theme needs to be installed on client WP installations, they need the possibility of updating the theme without knowing where the theme came from. 
So, i need a way to automatically compile bitbucket fields on backend as soon as i activate your plugin (the fields below).

![image](https://cloud.githubusercontent.com/assets/19909323/20479903/5b3132f0-afe0-11e6-8381-b59def9c398c.png)

I'm wondering if there's a way to do it, maybe setting up a file on the plugin/theme base directory, a json containing all the stuff i need to declare.

Inspecting your code, it seems i can force update_site_option on theme loading to automatically set bitbucket credentials and set the checkbox, but i believe something more destructive is better (i cannot decide if you in a year or 2 will change options saved name on database or what)....

Maybe a filter on those values should be a great thing...

**Comment by afragen** [comment]
It would be much simpler for you to set this up on GItHub or GitLab. I say this as these will allow you to set up a `read-only` access token. Please review the wiki. You can use a filter hook to set the  access token. I'm not sure Bitbucket has the best method of implementing this process. But you could use the same hook to set the Bitbucket user/pass and set the theme slug to `'1'`.

https://github.com/afragen/github-updater/wiki/Developer-Hooks

**Comment by teolaz1990** [comment]
I'm using the free version of Bitbucket, i don't want to install self-hosted repos (gitlab) or pay for private one (github) for now... 
Anyway, i've done a pull request (wrong, branch tough....). Please delete it, as i need to request it on develop branch..

**Comment by afragen** [comment]
GitLab.com has free accounts and private repos. You don't have to have a self-hosted solution.

**Comment by afragen** [comment]
The functionality of your PR is already in the plugin. See filter hook `github_updater_token_distribution`.

**Comment by teolaz1990** [comment]
Please refer to #501 for a better code format.

**Comment by afragen** [comment]
Not sure what you mean regarding _theme and plugin options_.

**Comment by teolaz1990** [comment]
![image](https://cloud.githubusercontent.com/assets/19909323/20489314/6c81d864-b00a-11e6-897a-09e37d88177d.png)

this is a var dump and die of self::$options inside Base.php ... i don't think "complete-theme" must stay there... you'd need a support array for themes and a support array for plugins

**Comment by afragen** [comment]
There is a tremendous amount of code that relies on this plugin and theme data being available where it is. A change such as this would require re-writing many functions.

**Comment by afragen** [comment]
Sticking to the subject. 

If your user is using this plugin outside of your theme and they are using Bitbucket, this plan will change their credentials. This is the problem of using Bitbucket in this use case as opposed to GitHub or GitLab. 

Both GitHub and GitLab provide for the ability to create individual access tokens that would in no way over-write any other user data.

**Comment by teolaz1990** [comment]
Yup, no problem there... i created a dedicated read only account on bitbucket and i will use it on every project i need... clients doesn't have to touch any parameter of your plugin and my installation logic, as their only job is to correct content and write new one :)

You can close this topic after new documentation is well formatted.
Thanks
T

**Comment by teolaz1990** [comment]
I think you shoul fix wiki before closing this...
