### ISSUE TITLE
Why to not only use tag version instead of both tag version and headers version?

### ISSUE THREAD

**Issue by teolaz1990** [afragen/github-updater#499]
@afragen as described here https://github.com/afragen/github-updater/wiki/Versions-and-Branches, why not just use Tag version of VCS instead of checking both Tag and CSS Headers?
Isnt' enough a sequential control on tag or header version? Why both? With this method we need to enter any time we update both tags and versions on css headers...

**Comment by teolaz1990** [comment]
Auto-answer: How can i check current theme/plugin version without adding a version on headers?
Short answer: use a serialized option for all detected plugins which remember the system last downloaded tag version for each one :)

**Comment by afragen** [comment]
WordPress **requires** a version number set in the theme's `style.css` file. GitHub Updater uses this version number then checks to see if a tag is set and uses it for the download link. The developer must ensure the release version and tag match.

This is by design and won't change.
