### ISSUE TITLE
Update documentation for Developer Hooks

### ISSUE THREAD

**Issue by Santana1053** [afragen/github-updater#502]
I found this code in the Developer Hooks wiki, however this filter no longer seems to exist inside of the function.
```
add_filter( 'github_updater_set_options',
    function () {
        return array( 
            'my-private-theme'    => 'kjasdp984298asdvhaljsg984aljhgosrpfiu',
            'github_access_token' => 'iorgoaihrg[89930ews8dchujnasgp',
        );
    } );
```

**Comment by afragen** [comment]
This hook is in the develop branch and will be merged within the week.

**Comment by afragen** [comment]
https://github.com/afragen/github-updater/commit/f64cef6051a7f9f2b248035fd3bda29028e7c3fc
