### ISSUE TITLE
Is it possible to use it for a ceratin theme foleder under the root of the repository?

### ISSUE THREAD

**Issue by RyosukeTakahashi** [afragen/github-updater#504]
I have a private repo like below.

![screenshot-github com-2016-11-27-14-32-07](https://cloud.githubusercontent.com/assets/12992519/20645873/bbdc4d60-b4ae-11e6-9877-41fce029f0e2.png)

This repo has a theme folder named "aikstheme" ("aiks" is the name of our client) and it has a bunch of files needed for the theme like index.php, contents.php and all that.

I was wondering if there is a way to automatically update the theme in a production server when I pushed something to this repository.

Is it possible to do it with this plugin? I am sure that you can if the files and contents of the theme folder are in the root directory of the repo, but this is not the case so I asked.

**Comment by afragen** [comment]
The model for how GitHub Updater works is for each individual plugin or theme be in a repository by itself and named after the plugin or theme slug.

In your example, if your theme is at `https://github.com/RyosukeTakahashi/aikstheme`. You **must** have a `style.css` at the root level of the repository. If there is post-processing needed you can create a release asset an update against that, but the requirements remain the same.

There is no ability to update based upon a specific subdirectory of a repository. It must be in the root. Sorry.

**Comment by RyosukeTakahashi** [comment]
OK, fine with that. Thank you very much for your quick reply.
