### ISSUE TITLE
Network Plugin page results in Error 500 after update to 6.1.0

### ISSUE THREAD

**Issue by tribusrandy** [afragen/github-updater#505]
Error 500 prevented access to Network Plugins once GitHub-Updater was updated to 6.1.0. Host cited the following from error logs:

PHP Fatal error: Cannot use object of type stdClass as array in /nas/content/live/randyqa/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 1051

**Comment by afragen** [comment]
Something didn't finish in the update process as that error should be mitigated. 

Download, install, and activate https://github.com/afragen/clear-github-updater-cache

**Comment by tribusrandy** [comment]
It took a couple tries, but we're back in business. Thank you for all the great work!
