### ISSUE TITLE
Internal server error after upgrading to 6.1.0

### ISSUE THREAD

**Issue by sachittandukar** [afragen/github-updater#506]
Hi,

Whenever I tried to upgrade from v6.0.0 to v6.1.0, I am getting internal server error.
Website is hosted on WP Engine.

I have also tried refreshing cache before updating plugin but it doesn't work

**Comment by afragen** [comment]
Install and activate https://github.com/afragen/clear-github-updater-cache

GitHub Updater should be clearing the cache on installation. It appears something isn't finishing with the upgrade.

**Comment by sachittandukar** [comment]
@afragen 
thanks. It worked. :)
Since WPEngine keeps transient cache, I need to purge that one too after running clear GitHub updater cache plugin to make it work.

Thank you for your help .

**Comment by afragen** [comment]
I was thinking the same thing re: WP Engine's cache.
