### ISSUE TITLE
 Call to undefined function WordPressdotorg\Plugin_Directory\Readme\mb_strrpos()

### ISSUE THREAD

**Issue by nelsonc24** [afragen/github-updater#507]
Hi,

After get installed and activated plugin, once trying to access again to plugin area, I am getting following error:

Fatal error: Call to undefined function WordPressdotorg\Plugin_Directory\Readme\mb_strrpos() in /home/xxxxx/public_html/xxxxxx.com/wp-content/plugins/github-updater/vendor/class-parser.php on line 403

Best Regards

**Comment by afragen** [comment]
https://secure.php.net/manual/en/function.mb-strrpos.php Has been part of PHP for a long time. You may need to contact your service provider to make sure they have compiled this in their version of PHP.

**Comment by afragen** [comment]
That being said, I'll see about replacing this function with the non-multibyte function.
