### ISSUE TITLE
Updating to 6.1.1.2 breaks plugin updates

### ISSUE THREAD

**Issue by yaronguez** [afragen/github-updater#510]
I just updated to 6.1.1.2 and it's not seeing my plugin updates anymore. Anything I can do to help debug?

**Comment by afragen** [comment]
What version did you update from?

**Comment by yaronguez** [comment]
I didn't note the original version prior to upgrading. The version in my
local dev environment is 6.1.1 so it may have been that.

Yaron Guez
Software Architect
(781) 249-4709

**Comment by afragen** [comment]
Only thing added from 6.1.1 to 6.1.1.2 was wp-cli stuff and last commit for some PHP notice fixes.

**Comment by afragen** [comment]
Have you tried Refreshing the cache?

**Comment by yaronguez** [comment]
Yep, many times. Also tried pushing another update through. Finally removed
plugin outright and reinstalled using Github Updater. That seems to have
fixed it. New update I pushed just went through.  Strange. Thanks for the
prompt reply!

Yaron Guez
Software Architect
(781) 249-4709

**Comment by afragen** [comment]
Weird. I guess it's too late to ask if the plugin directory was misnamed.

Anyway, glad it's all working again.

**Comment by yaronguez** [comment]
I checked that as well. It wasn't. I've had this happen before where
reinstalling worked but I had forgot to try that before filing an issue
here.

Yaron Guez
Software Architect
(781) 249-4709

**Comment by afragen** [comment]
Still very strange. Only thing deleting and re-installing would do is remove the plugin's setting in the option.
