### ISSUE TITLE
Child theme doesn't show update available.

### ISSUE THREAD

**Issue by Cskyleryoung** [afragen/github-updater#511]
Hi afragen,

I've culled through past issues for a while, but haven't been able to solve this issue yet. I'm attempting to get updates for a child theme. The remote headers are:
`/*
Theme Name: Beaver Builder Child Theme
Theme URI: http://www.wpbeaverbuilder.com
Version: 1.1.2
Description: The default customized child theme for Site Savvy created websites.
Author: The Site Savvy Team
Author URI: https://sitesavvy.systems
Template: bb-theme
GitHub Theme URI: Cskyleryoung/bb-theme-child
GitHub Branch: master
*/`

Local headers are:
`/*
Theme Name: Beaver Builder Child Theme
Theme URI: http://www.wpbeaverbuilder.com
Version: 1.1.1
Description: The default customized child theme for Site Savvy created websites.
Author: The Site Savvy Team
Author URI: https://sitesavvy.systems
Template: bb-theme
GitHub Theme URI: Cskyleryoung/bb-theme-child
GitHub Branch: master
*/`

This is pulling from a public repo: https://github.com/Cskyleryoung/bb-theme-child.

GitHub Updater appears to see the child theme:
<img width="663" alt="screen shot 2016-12-15 at 7 57 47 pm" src="https://cloud.githubusercontent.com/assets/3250365/21251211/d05511b8-c300-11e6-96d5-c6f026058e5f.png">

However, it still doesn't show any updates available. I have cleared the cache many times. Have I missed something obvious? If not, what should be my next step troubleshooting this?

**Comment by afragen** [comment]
I was able to install your theme, rollback the version number, refresh the cache, and show an update. I was then able to update. Do you see anything on the themes.php page?

It's possible, since you don't have a personal access token set that you bumped up against the GitHub API rate limit. You would see a notice about it.

**Comment by Cskyleryoung** [comment]
You are right, it's showing an update available this morning. I'm not sure why it took so long to register after I cleared the cache, but in any case, it's working.

Thanks for your time, and I'm sorry to have troubled you. And thanks for the plugin! It's perfect :)
