### ISSUE TITLE
PHP Notice: Trying to get property of non-object in GitHub_API.php on line 221

### ISSUE THREAD

**Issue by egifford** [afragen/github-updater#512]
Great plugin!  It has changed my workflow for the better.

I've been running into the PHP Notice in the title of this issue.  I think I've tracked it down.  It only happens when we're pulling in forked GitHub repositories.

It looks like the /search/repositories endpoint on the GitHub API doesn't return forked repos by design.  See this link for more information:
https://help.github.com/articles/searching-repositories/#search-based-on-the-number-of-forks-the-parent-repository-has

I think tweaking the API query in get_repo_meta() in GitHub_API.php to include forks will do the trick (I'll put together a pull request).

For example, this altered query works for me:
https://api.github.com/search/repositories?q=github-updater+user:blueblazeassociates+fork:true

Running the query without the fork:true modifier returns 0 repositories and freaks out the get_repo_meta() function.

Thanks!

**Comment by afragen** [comment]
Interesting. Can you explain why we want to get the forks too? What's the use case?

I ask because it's never come up before.

**Comment by afragen** [comment]
I think I understand, let me test something.

**Comment by afragen** [comment]
I see. Merging now. Thanks.

**Comment by afragen** [comment]
@egifford I found a better solution with a more direct API call that gets forks. https://developer.github.com/v3/repos/#get

This simplifies the method and gets all the data I'm looking for. https://github.com/afragen/github-updater/commit/369c4433ddc9e6334e497c026bf8dd4d023cf00d

**Comment by egifford** [comment]
@afragen Nice find on that API call.  Your change is nice and clean.  Thanks for keeping me in the loop.
