### ISSUE TITLE
Incorrect update message for branches

### ISSUE THREAD

**Issue by fatjester** [afragen/github-updater#515]
I have GitHub Updater (master branch) 6.1.1 installed on Wordpress 4.7, and the plugin is telling me there is an update for available to version 6.1.1.8, which as of now is the develop branch.

Clicking the update button doesn't update the plugin (which is good because I'm on master), but the message to update persists.

It should be giving me an update notification if I'm on the latest in my specified branch (or the default of master).

**Comment by afragen** [comment]
Can you show a screenshot?

**Comment by fatjester** [comment]
Sorry, after a reboot of the server, it seems to be working correctly now :/
Thanks again for such a great plugin!

**Comment by fatjester** [comment]
Just a followup - I believe the incorrect update message turned out to be caused by redis object cache.  I had initially had the develop branch installed, and when I switched, certain transients were being cached.
