### ISSUE TITLE
Fails to include private submodules

### ISSUE THREAD

**Issue by IzaacJ** [afragen/github-updater#516]
I have a theme I'm working on, which is hosted on bitbucket in a private repo.
That theme is using another project, also a private repo on bitbucket, and has that as a submodule.
Installing the theme fine, but the submodules directory is empty. Both repositories are owned by the bitbucket account I entered.
Any ideas on how I can get this to work?

**Comment by afragen** [comment]
Submodules will not install. This is a longstanding issue and one that cannot be worked around. 

You can create a release asset that separately contains the entire project. Please see wiki.
