### ISSUE TITLE
Naming convention would ideally be softer

### ISSUE THREAD

**Issue by fwolfst** [afragen/github-updater#517]
Hi and sorry that I updated https://github.com/afragen/github-updater/wiki/Usage (with example directory structure for plugin git-repositories) without prior communication.

I would like to see Github Updater being confident with **git-repositories of any name**, where the plugin code (and metadata) sits in a **subdirectory with the given plugin name**.

An example can be seen in https://github.com/ecovillage/ev7l-events/tree/9d6ca752f17a9a138d556bc8f434ef46276c9d40 (where actually the git repository name equals the plugin name, imagine it would be named differently).

As a developer this allows me to put additonal assets (wiki images, documentation, developer readme, testing tools and data etcpp) in the same repository, while avoiding fiddling with `.gitattributes` and have all relevant plugin code in a single directory (no need to exclude extra readmes, .gitignores, whatevers).

I understand that the structure "as if cloning the repository in wp-content/plugins" has its benefits, too. In my dream world, github-updater would first look for a file "./myplugin.php" (for a plugin called "myplugin") then "./myplugin/myplugin.php". This assumes that the plugin name is known prior to initial installation via github updater or the initial installation is done manually.

Same arguments count for themes, obviously.

I see GitHub Updater working really fine as-is and the conventions are all fine, I just stumbled upon this "issue" and would find it a great addition/feature. Unfortunately my php skills and free time will not allow me to create a PR for this.

**Comment by afragen** [comment]
Not to worry about editing the wiki, any clarity to documentation is appreciated.

Under normal circumstances plugins/themes are not is subfolders and the main plugin file or theme's `style.css` file **must** be at the root of the directory structure. This is a WordPress standard. As you can see from the file structure of GitHub Updater, using an appropriately configured `.gitattributes` file solves the issue of which files are downloaded during an update.

Though I prefer the naming convention `/myplugin/myplugin.php` you actually can use something like `/myplugin.php/plugin.php` as long as the plugin's headers are in that file. Theme structure is more restrictive.

Fundamentally I've designed GitHub Updater to function as a drop-in to provide updating to git-hosted plugins and themes just as core does for dot org hosted files. Yes, there are some additional features but expanding the definitions of where the main plugin file or `style.css` file will likely serve only to create larger support issues for me.

**Comment by fwolfst** [comment]
> Though I prefer the naming convention `/myplugin/myplugin.php`

Well, this did not work for me (maybe I made a silly mistake though - maybe you refer to the repository name with the first `/myplugin/` component). I mean like in the link I had a repository "ev7l-events", with contents `ev7l-events/ev7l-events.php` . The `ev7l-events.php/plugin.php` "trick" sounds good, but actually I am also fine with the convention as-is and I totally understand your concerns. Thanks for responding, will close this issue now.

**Comment by afragen** [comment]
Sorry, my reference is to the plugin directory structure where `/myplugin/myplugin.php` refers to a plugin directory named `myplugin` with a main plugin file in its root of `myplugin.php`. 

This would correspond to a GitHub URI along the lines of `https://github.com/owner/myplugin/myplugin.php`.
