### ISSUE TITLE
Can no longer update current branch of plugin

### ISSUE THREAD

**Issue by joelworsham** [afragen/github-updater#520]
It used to be that I could re-pull a branch to update it to the latest code from the repository. So, the workflow would be:

1. Push new code to `branch-a`.
2. Go to website and go to plugin in question, which is already on `branch-a`.
3. Click "try another branch", but click again on `branch-a` option.
4. Website would download latest code from `branch-a`.

Now when I try this, I get the message: "The plugin is at the latest version." and can longer update the code this way.

This is related to #428, where I talked about needing to pull the latest commit. I landed on the manual solution of just pulling the same branch again. I can no longer do this. I would need to pull another branch, say `branch-b`, and then go back and pull `branch-a` back. This isn't ideal for me.

Is there now a different way to pull the latest code from within the same branch?

**Comment by joelworsham** [comment]
UPDATE: This is actually deeper than I thought. I can't switch branches at all. No matter what I the "Plugin at latest version" message.

![](http://d.pr/i/HrMP+)

**Comment by afragen** [comment]
On the server are the directory names the same as the slug?

**Comment by joelworsham** [comment]
They've been renamed using the extended naming feature. So the current dirnames were set by the plugin.

**Comment by afragen** [comment]
OK, I think that extended naming breaks the branch switch. Trade-offs 😝

**Comment by joelworsham** [comment]
Haha okay gotcha. So is this something you think you can fix? Or should I consider extended naming unusable for this situation?

**Comment by afragen** [comment]
I think it means extended naming has some trade-offs that I can't circumvent. 

Really the only reason to use extended naming is if you have a slug conflict with a dot org plugin.

**Comment by joelworsham** [comment]
Well, this was working in version 6.0.0. I roll'd back to confirm, and branch switching *does* work even with extended naming. Perhaps something changed that broke that functionality?

**Comment by afragen** [comment]
Wow, I'll have to check back. If I can fix it I will.

**Comment by afragen** [comment]
I can confirm this worked in v6.0.0. I should be able to fix. Stay tuned.

**Comment by joelworsham** [comment]
You rock.

**Comment by afragen** [comment]
Now I rock. 🙄 https://github.com/afragen/github-updater/commit/dc501e8863b7c17784c2f55bac9ebe1c177d6411
