### ISSUE TITLE
cURL Error

### ISSUE THREAD

**Issue by geoffreyrose** [afragen/github-updater#521]
Im getting this error:
GitHub Updater Error Code: cURL error 56: SSL read: error:00000000:lib(0):func(0):reason(0), errno 104

Any ideas?

**Comment by afragen** [comment]
What's your server stack?

**Comment by geoffreyrose** [comment]
It is Laravel's Homestead, running on VirtualBox
- Ubuntu 16.04.1
- PHP 7.1
- Nginx

https://laravel.com/docs/5.3/homestead

**Comment by afragen** [comment]
I found this error when running certain versions of VirtualBox. I think 5.1.10 works.

**Comment by geoffreyrose** [comment]
That fixed it, thanks!

**Comment by afragen** [comment]
It was a very odd bug to track down and I still don't know the cause. Fortunately I know a solution 😉

**Comment by afragen** [comment]
BTW what version caused you the problem?

**Comment by geoffreyrose** [comment]
I was using 5.1.8 and updated to 5.1.14

**Comment by afragen** [comment]
Thanks. I think 5.1.8 was the original version I saw the issue with.
