### ISSUE TITLE
Generate error if GitHub Plugin URI tag is missing

### ISSUE THREAD

**Issue by limikael** [afragen/github-updater#523]
If the `GitHub Plugin URI` is missing from the plugin header, this will cause all sort of problems. One of the problems is that the RESTapi will not work, it will just say that the plugin is incompatible. This is fine, since adding that header is a requirement.

However...

It is actually possible to install plugins that doesn't have that header. IMO this shouldn't be possible, and github-updater should refuse to install such a plugin and generate a hard error. What do you think about this @afragen? If you want it to be more tolerant on installation, that's ok, but then at least there should be a strong warning when installing a plugin without `GitHub Plugin URI` in the header.

What would you prefer? An error or a warning?

In any case... please assign this issue to me, will work on a PR within a week or so...

**Comment by afragen** [comment]
There is really no way to test the repository being installed and I'm not sure I would want to limit GHU's usage by imposing that limit. If a developer knowingly wants to use GHU with their plugin they will add the header. Something like this can potentiallly throw exceptions for dot org plugins.

Besides, you can always use the [GitHub Updater Additions](https://github.com/afragen/github-updater-additions) plugin.

**Comment by limikael** [comment]
Well, I thought the test could be done after the installation.

Ok, I understand that this could be a limitation to how people might want to use github-updater, so let's not generate an error then.

But how about a warning?

Let me explain why I think this would be a good thing. In my experience as a teacher I have noticed that several people find it quite challenging to set this up. This is especially true for those new to programming. As recent as this morning I was approached by someone who was trying to set up continuous integration, and she was clueless why it didn't work. It turned out that it was the `GitHub Plugin URI` header that was missing. So if we would show a warning after a plugin has been installed it would probably be helpful.

**Comment by afragen** [comment]
I believe this is more of a learning issue for the developer. They have to go deep to GitHub Settings to create a webhook, remembering to add the header to their project seems like a minor issue. 

That and there already is an error thrown if the plugin isn't compatible with GHU when using continuous integration. How would this idea be different?

They just need to know where to look for the response.

If the goal is to throw an exception or notice whenever someone installs a repo via GHU that doesn't have the proper header, it's my opinion that it will result in more confusion and problems than it solves. The Install tab installs plugins or themes from git servers, it doesn't make update guarantees after that. This is a user education issue not a software issue.

**Comment by limikael** [comment]
Ok.

Well it would be different in the way that the error would be more informative. If you try to set up the webhook with the header missing is just "plugin not found".

But anyway, actually the best would be if it would be possible to get it to work even if the header is not there. What do you feel about this? Do you think there would be any way of getting this to work?

**Comment by afragen** [comment]
The actual error is "plugin not found or not updatable with GitHub Updater" https://github.com/afragen/github-updater/blob/develop/src/GitHub_Updater/Rest_Update.php#L68

Other than using GitHub Updater Additions, there's no way to make GHU work with a repo that doesn't have the appropriate header.

**Comment by limikael** [comment]
Ok.
