### ISSUE TITLE
Notice:  Undefined property: Class::$data in /wp-content/plugins/github-updater/src/GitHub_Updater/Bitbucket_API.php on line 81

### ISSUE THREAD

**Issue by calvintam236** [afragen/github-updater#525]
It keeps showing at my plugins page.. GitHub Updater v6.2.1.

**Comment by afragen** [comment]
Thanks. My guess is the API didn't get the complete response it expected. I can tighten up the code a bit to eliminate the notice.

**Comment by afragen** [comment]
Should be fixed here. https://github.com/afragen/github-updater/commit/86bbd92e94e1f2e53c900cc65e4ed4fc0059390f
