### ISSUE TITLE
Child Theme Not Saved or Updated

### ISSUE THREAD

**Issue by INA2N** [afragen/github-updater#526]
I've been using your plugin to update one of my own plugins, and that works fine, but I can't get it to save a custom child theme.  I'm not getting any errors, it just doesn't add the child theme to the Settings --> Github tab.  Since it won't save it, it's not showing the child theme to have an update when it is updated with a new version.

**Comment by afragen** [comment]
Have you added the appropriate header to the child theme? Can you show the child theme's headers?

**Comment by INA2N** [comment]
Thank you.  That did it.  I think it had something to do with the spacing as well.  I had the GitHub Theme URI: already in place but it was more than just that.  I think the header spacing has to be correct.

/*
Not this
*/

/*
 But this
*/

**Comment by afragen** [comment]
Not sure I can see the difference without a code block, but glad it's working.
