### ISSUE TITLE
empty white pages after activation

### ISSUE THREAD

**Issue by TheodorHof** [afragen/github-updater#527]
Hello,

I have a problem with "GitHub Updater". After activating the plugin, an empty white page appears. The "Update" and "Settings" page are also affected:

wp-admin/plugins.php
wp-admin/update-core.php
wp-admin/options-general.php

This problem only occurs if the folder for "GitHub Updater" is named "github-updater" in the plugin directory:
.../wordpress/wp-content/plugins/github-updater  --> problem 

If you rename the folder, the problem does not exist, the plugin can be activated:
.../wordpress/wp-content/plugins/github_updater  --> No problem, activation ok
.../wordpress/wp-content/plugins/githubupdater   --> No problem, activation ok

If it was activated because the folder was renamed, then the links [Deactivate | Edit] will show up on the plugin page but not [Deactivate | Edit | Settings] as one would expect. The settings page is nevertheless accessible via Settings> GitHub Updater.

If you update "GitHub Updater" itself, the error message "Update Failed: Internal Server Error" appears, but the update still seems to have been carried out. However, the folder is automatically renamed to:

.../wordpress/wp-content/plugins/afragen-github-updater-9b203d4

A problem with permissions can not be actually - for test reasons I have done chmod -R 777 for .../wordpress/...

The above described problem occurs with the following machine:
Config Mashin A)
--------------------------------------------
Ubuntu 16.04.1 LTS
Apache/2.4.18
PHP 7.0.13
mysql  Ver 15.1 Distrib 10.0.29-MariaDB

On the following machine the described problem occurs NOT:
Config Mashin B)
--------------------------------------------
SUSE Linux Enterprise Server 11 Patchlevel 2
Apache/2.2.12 
PHP 5.3.17
mysql  Ver 14.12 Distrib 5.0.96

any suggestions?

**Comment by afragen** [comment]
Thanks for the detailed report. Can you try deactivating all plugins except GHU and see if the error persists? If it doesn't can you reactivate plugins until you find the conflicts? Thanks.

**Comment by TheodorHof** [comment]
Hi,
it happens with a brand new installation of wordpress with no plugins enabled, no extra themes and no other plugins then default.
best regards

**Comment by afragen** [comment]
I can't explain it. Are there are PHP errors or anything from WP_DEBUG?

**Comment by TheodorHof** [comment]
at the moment when activating the plugin:
[Wed Feb 08 17:25:23.054721 2017] [:error] [pid 6675] [client 192.168.5.5:61636] PHP Fatal error:  Uncaught Error: Call to undefined function WordPressdotorg\\Plugin_Directory\\Readme\\mb_strrpos() in /home/user_name/wordpress/wp-content/plugins/github-updater/vendor/class-parser.php:402\nStack trace:\n#0 /home/user_name/wordpress/wp-content/plugins/github-updater/vendor/class-parser.php(324): WordPressdotorg\\Plugin_Directory\\Readme\\Parser->trim_length('This plugin was...', 150)\n#1 /home/user_name/wordpress/wp-content/plugins/github-updater/src/GitHub_Updater/Readme_Parser.php(38): WordPressdotorg\\Plugin_Directory\\Readme\\Parser->parse_readme('# GitHub Update...')\n#2 /home/user_name/wordpress/wp-content/plugins/github-updater/src/GitHub_Updater/GitHub_API.php(183): Fragen\\GitHub_Updater\\Readme_Parser->__construct('# GitHub Update...')\n#3 /home/user_name/wordpress/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php(476): Fragen\\GitHub_Updater\\GitHub_API->get_remote_readme()\n#4 /home/user_name/wordpress/wp-content/plugins/github-updater/src/GitHub_Updater/Plugin.php(228): Fragen\\G in /home/user_name/wordpress/wp-content/plugins/github-updater/vendor/class-parser.php on line 402, referer: http://testweb.somewhat.somewhere.com/folderX/folderY/user_name/wp-admin/plugins.php

**Comment by afragen** [comment]
It seems you server stack doesn't have `mb_strrpos` compiled in it's PHP. http://php.net/manual/en/function.mb-strrpos.php

It would appear this is a built-in function. Thoughts?

**Comment by afragen** [comment]
I'll see what I can do about replacing this function if `mb_strrpos()` doesn't exist.

**Comment by afragen** [comment]
Update  to latest `develop` branch and let me know if the error persists.

**Comment by TheodorHof** [comment]
that it! "mbstring is a non-default extension. This means it is not enabled by default. You must explicitly enable the module with the configure option." (http://us.php.net/manual/en/mbstring.installation.php)

solution 1)
using latest develop branch as suggested by you - it's working without errors!
thank you very much for this very fast update!

solution 2)
install "php7.0-mbstring"
on ubuntu:
sudo apt-get install php7.0-mbstring
sudo service apache2 restart
using latest master branch is now also possible and works without errors!

thank's a lot for your help and for github-updater

best regards

**Comment by afragen** [comment]
Thanks for confirming. I think I'll leave the fix in place as this isn't the first time it's been an issue.
