### ISSUE TITLE
WP-CLI PHP Notice about wp_enqueue_style

### ISSUE THREAD

**Issue by egifford** [afragen/github-updater#528]
I'm seeing the following notice after updating to 6.2 (currently running 6.2.2):

`Notice: wp_enqueue_style was called <strong>incorrectly</strong>. Scripts and styles should not be registered or enqueued until the <code>wp_enqueue_scripts</code>, <code>admin_enqueue_scripts</code>, or <code>login_enqueue_scripts</code> hooks. Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 3.3.0.) in W:\_bbwebsites\DeLL.WP\wp-includes\functions.php on line 4136`

It may be that my WordPress setup is causing it, but I wanted to check with y'all.

I run the plugin as a mu-plugin.  I think that is a factor.

Assuming that this isn't local to my setup...

When configured as an mu-plugin, I think the new WP-CLI code in the plugin is unintentionally loading the plugin's `github-updater.css` file via `wp_enqueue_style()` in `Theme::load_pre_filters()` before WordPress is ready for it.

My dirty way to fix this would be to set a sentinel value somewhere inside `CLI_Integration.php` indicating that admin theme resources don't need to loaded.  `Theme::load_pre_filters()` would check this sentinel before loading resources.

For me, the PHP notice is a really minor issue, but I didn't want to ignore it for too long in case it could be fixed or indicates a bigger problem.

If my solution sounds agreeable, I could put together an initial fix as a pull request.

I attached a stack trace.

[php-stack-trace.txt](https://github.com/afragen/github-updater/files/778150/php-stack-trace.txt)

**Comment by egifford** [comment]
Looking at the code, there is already a check for running as WP-CLI: Base::is_wp_cli(). Nice!

**Comment by afragen** [comment]
Thanks for the stack trace. I'll take a look but this should be simple enough to fix.

**Comment by afragen** [comment]
Let me know if https://github.com/afragen/github-updater/commit/7723de311d19eb9125d864041e631119b45d522e doesn't fix it.

**Comment by egifford** [comment]
https://github.com/afragen/github-updater/commit/7723de311d19eb9125d864041e631119b45d522e worked perfectly!
