### ISSUE TITLE
some unexpected messages by using it via wp_cli

### ISSUE THREAD

**Issue by steffenster** [afragen/github-updater#530]
Thanks for your plugin, I like it.
I used it with `wp plugin install-git uri --bitbucket-private=` and got some unexpected messages for language updates.

```
<p>Einige Übersetzungen benötigen eine Aktualisierung. Warte noch ein paar Sekunden ab, während wir diese ebenfalls aktualisieren.</p>
<div class="update-messages lp-show-latest"><h2>Aktualisiere Übersetzungen für Akismet (de_DE)&#160;&hellip;</h2><p>Herunterladen der Übersetzung von <span class="code">https://downloads.wordpress.org/translation/plugin/akismet/3.2/de_DE.zip</span>&#160;&hellip;</p>
<p>Entpacken der aktualisierten Version&#160;&hellip;</p>
…
<p>Die Übersetzung wurde erfolgreich aktualisiert.</p>
</div><script type="text/javascript">
					(function( wp ) {
						if ( wp && wp.updates.decrementCount ) {
							wp.updates.decrementCount( "translation" );
						}
					})( window.wp );
				</script>
```
At the end I got a message, `Success: Theme '…' installed.` and it was.
Not really a bug, but I didn't start an update for languages. I expected to install my theme and nothing more.

**Comment by afragen** [comment]
I have found that triggering any update when there are language updates available will also trigger a language update. Not sure it's related but you can test by removing the language update from `wp-content/languages` and try installing any other plugin say `hello-dolly` and see if the language update happens too.
