### ISSUE TITLE
Duplicate/Multiple installs?

### ISSUE THREAD

**Issue by wormeyman** [afragen/github-updater#531]
![screenshot from 2017-02-19 16-39-49](https://cloud.githubusercontent.com/assets/1795016/23108430/239723a8-f6c2-11e6-8b4b-65cf2089db2a.png)

As you can see from the screenshot I have GitHub Updater listed twice!

I installed 6.2.2 from the zip and this is what i got.

**Comment by afragen** [comment]
I've seen this personally but can't consistently replicate it.
Does this persist between page loads? Local or on a remote server? Caching?
I need to replicate this to fix it.

Please make sure the directory is correctly named `github-updater`.

**Comment by afragen** [comment]
I think I may have fixed this in the `develop` branch.

**Comment by wormeyman** [comment]
I did not rename it to `github-updater` but when I did I still get it doubled.

**Comment by afragen** [comment]
Can you install/switch to the `develop` branch and see if persists?

**Comment by wormeyman** [comment]
That appears to have fixed it 👍
