### ISSUE TITLE
Extended Naming active or not active

### ISSUE THREAD

**Issue by VanDerPrygel** [afragen/github-updater#533]
Hi,

I have just started using GitHub Updater for WordPress and I have a question before using it on several websites.

Is it necessary to set Extended Naming to active or not? Will it mess something up not set to active?

Kind regards
René

**Comment by afragen** [comment]
The **only** reason to use extended naming is if your plugin slug is identical to the plugin slug of a plugin on wp.org. I personally don't use it.
