### ISSUE TITLE
Installing/Updating a private repo theme and a private repo child theme via bitbucket

### ISSUE THREAD

**Issue by konceptas** [afragen/github-updater#534]
First off thanks for a great plugin which almost seems to do what I need it to do! :)

However I am having trouble updating a child theme from a private repo when i have the parent theme installed form private repo from bitbucket.

Only the parent theme appears as the one installed in the github updater plugin list, and when I try to install the child theme again, it says it of course already exists.

I have already bumped the child theme version number and nothing happens also cleared the cache in the plugin, yet the child theme does not appear in the updates list.

I am also using manage wp for remote management but accessing from wp-admin only still doesn't work :(

If you need additional details, i'll be happy to help!

**Comment by afragen** [comment]
Can you post the headers of both the parent and child themes?

**Comment by konceptas** [comment]
Hi Afragen! I just found my error and i'm so sorry! It's not only the parent theme that needs the repo path but the child theme aswell. Sorry to waste your time! Thanks again for a great plugin! :)
