### ISSUE TITLE
not menu gitlab

### ISSUE THREAD

**Issue by andruwa13** [afragen/github-updater#535]
Hi, hi, there is no menu gitlab
![github_updater_nastroiki__plategonline__wordpress_2017-03-02_22-14-27](https://cloud.githubusercontent.com/assets/5846351/23525027/b886a89a-ff95-11e6-8cfe-796414daebbe.png)
GitHub Updater v **6.2.2.13**

**Comment by afragen** [comment]
The submenus are dynamic and only present if a plugin/theme with the appropriate header is preset. 

Do you have a repo hosted on GitLab installed?

**Comment by andruwa13** [comment]
yes privat repo/ Install theme, not menu gitlab
![style css volumes hdd webakcent theme default 2017-03-02 22-23-27](https://cloud.githubusercontent.com/assets/5846351/23525381/fa6e306a-ff96-11e6-872a-1517f1904df4.png)

**Comment by afragen** [comment]
You are missing the colon from the header `GitLab Theme URI:`
