### ISSUE TITLE
Feature Request - Tie the Refresh Cache functionality into the Check Again button on Updates page

### ISSUE THREAD

**Issue by garrett-eclipse** [afragen/github-updater#536]
Hi @afragen 

I had a minor feature request which will make our workflow a bit nicer. Currently in my theme I disable the Github Updater settings, as such the Refresh Cache button isn't available unless I enable that settings page again. I don't really want users to even be aware of the updater though so would like to keep disabled.

What I'm hoping is feasible is to tie the refresh cache functionality in with the 'Check Again' functionality on the standard Wordpress updates page. That way if the cache needs a refresh can be done via Check Again without needing to temporarily expose the settings page or have someone wait for cache expiry.

Hope that makes sense,
Thanks

**Comment by afragen** [comment]
Makes sense and that was formerly the behavior. During the Shiny Updates dev process there was a hint that the 'Check Again' button might go away so I create the current alternative.

Fortunately I've already got you covered. Download and install, https://github.com/afragen/clear-github-updater-cache

Anytime you want to clear the cache just activate the plugin, it will clear the cache and deactivate.

**Comment by garrett-eclipse** [comment]
Thanks @afragen,

Would it work to install via zip as well since I disable the Github Updater settings? Handy little plugin.

I think I'll stick with temporarily enabling settings for now until you can tie in the button.

Appreciate the quick response.

**Comment by afragen** [comment]
I suggest installing via the Install tab to ensure the renaming is correct. If you correctly rename the zip you can install that way.

I don't really intend to add back the cache empty to the check again button, but it could make for an interesting new plugin.

**Comment by afragen** [comment]
Stay tuned.

**Comment by afragen** [comment]
@garrett-eclipse just for you. Install the `force-check` branch of the above plugin. It will cause the _Check Again_ button to function similarly to the _Refresh Cache_ button.

**Comment by garrett-eclipse** [comment]
OMG THANK YOU @afragen, greatly appreciated. I'll test it out here.
Will that branch be merged into the plugin if all is successful? I'm just wondering if I'll be able to keep users on master will all you amazing updates or if I'll have to bundle the branched plugin and indicate they should replace?
Appreciated

**Comment by afragen** [comment]
I'm not planning on incorporating this back into the main plugin. It's actually a pretty simple plugin. I would just install it and activate it for your users. I'll have to put in a sanity check to ensure that it doesn't error if GitHub Updater is not active.

**Comment by garrett-eclipse** [comment]
Thanks @afragen sounds good, I will play with it here and see how we want to handle within our theme. We might either add to our dependency or install script along with the updater, or maybe just extract some of the code to bake into the theme itself for when the updater is installed.

**Comment by afragen** [comment]
I pushed an update to the `force-check` branch so it won't fatal if GHU is not active.
