### ISSUE TITLE
Plugin Updates delete git ignore files.

### ISSUE THREAD

**Issue by gnnpls** [afragen/github-updater#537]
Hi.

We face a problem (or we have done something totally wrong).

We have a .gitignore file with some files inside:
booking/sbp.json
sftp-config.json

These files are being edited by the user of wordpress.

But every time we update the plugin these files are being deleted from each wp wordpress.

Is somehting we are missing out?

**Comment by afragen** [comment]
Files or folders listed in .gitignore don't show up on the git server. They will be present locally only.

Why did you put these files in .gitignore ?

**Comment by afragen** [comment]
Answered in Slack

**Comment by gregoriopellegrino** [comment]
Hi,
I'm in the same use case, what is the correct way to manage user files? (without deleting them)?

Thanks!

**Comment by afragen** [comment]
Use a .gitattributes file. You can see an example in this repository.
