### ISSUE TITLE
Can't see Bitbucket settings screen

### ISSUE THREAD

**Issue by wolffe** [afragen/github-updater#538]
I have a theme called "Moon UI Theme", the theme folder is "moon-ui-theme" and the Bitbucket repository is https://bitbucket.org/xxxxxxxxxx/moon-ui-theme (private). Why can't I see the Bitbucket settings page? I have flushed the cache countless times. I have the latest version of GHU and WP. I have added a Bitbucket tag and the version there is higher than the local one, so it should trigger an update.

**Comment by afragen** [comment]
Can you copy/poster the theme's headers here's?

**Comment by wolffe** [comment]
```
/*
Theme Name: Moon UI Theme
Theme URI: https://posterspy.com/
Author: Ciprian Popescu
Author URI: https://getbutterfly.com/
Description: Moon UI is a dark theme, built on top of CSS3 UI Kit framework. Custom modifications added for PosterSpy.com.
Version: 2.2.6
Bitbucket Theme URI: https://bitbucket.org/getbutterfly/moon-ui-theme
Bitbucket Branch: master
License: GNU General Public License v3 or later
License URI: https://www.gnu.org/licenses/gpl.html
Tags: black, custom-menu, featured-images, microformats, threaded-comments
*/

```

**Comment by afragen** [comment]
That looks correct. How did you install the theme?

**Comment by wolffe** [comment]
The theme was already there, I have added the headers and installed GHU. I have also tried to install the theme from the Bitbucket repository, it installed successfully, but it didn't keep the settings.

**Comment by afragen** [comment]
Can you give `afragen` `read` access so I can test?

**Comment by wolffe** [comment]
Access to my Bitbucket?

**Comment by afragen** [comment]
Can you try installing the theme from GHU?

**Comment by wolffe** [comment]
Done, access granted. I will try again, let me commit the latest changes.

**Comment by afragen** [comment]
Just `read` access to the repo.

**Comment by afragen** [comment]
I was able to install from GHU and see the theme in the Bitbucket Settings tab.

**Comment by wolffe** [comment]
Let me do it now. I have just committed the latest changes.

**Comment by afragen** [comment]
It depends a great deal on how the theme or plugin is named on the server. GHU automatically renames everything correctly.

**Comment by wolffe** [comment]
Done. Installed. What about updates? I tried to tag the new version but I didn't get anything.

**Comment by wolffe** [comment]
Just pushed v2.3.3 and created a new tag. No update is visible. I used your plugin before and it worked properly with another Bitbucket theme and a plugin.

**Comment by afragen** [comment]
Stick to standard semantic versioning for tags. `2.3.3` not `v2.3.3`.

**Comment by afragen** [comment]
`version_compare()` can be fickle.

**Comment by wolffe** [comment]
Done. Now I keep force checking the update page in WordPress.

**Comment by wolffe** [comment]
Any thoughts?

**Comment by afragen** [comment]
Sorry. Got caught up in the morning duties. I'll get back after I finish rounding on my hospital patients.

**Comment by wolffe** [comment]
Oh, sure, no problem. Thanks for your help.

**Comment by afragen** [comment]
I think you'll have to delete the `v2.3.3` tag as it sorts higher than the others.

**Comment by wolffe** [comment]
I have removed it, do you still see it?

**Comment by afragen** [comment]
I saw it on Bitbucket under tags.

**Comment by wolffe** [comment]
I'll check later but I removed it 3 hours ago. Thank you.

**Comment by afragen** [comment]
I still see it on Bitbucket.org

What can happen is you'll see an update but the update will come from the highest sorted tag. If this is an older version the headers may not be correct an you could cease seeing updates.

**Comment by wolffe** [comment]
I see. Thanks, Andy.

**Comment by afragen** [comment]
LMK if you've got it working or if we still have an issue.

**Comment by afragen** [comment]
Seems to be working for me both locally and on test server.

**Comment by wolffe** [comment]
I managed to delete the `v2.3.3` tag and push another version. I'll wait for the update. If not, I'll just clean the repository and start again from scratch.

**Comment by afragen** [comment]
I now see an update notification for version 2.3.6 on my test server.
