### ISSUE TITLE
How to check if updates are avaivable?

### ISSUE THREAD

**Issue by lionas89** [afragen/github-updater#539]
Good day, earlier there was RESTful updates tag to check available updates. Now there is not, how can i check for available updates?

**Comment by afragen** [comment]
Are referring to updating via restful endpoint? https://github.com/afragen/github-updater/wiki/Remote-Management

There is integration with WP-CLI. https://github.com/afragen/github-updater/wiki/WP-CLI

I did remove the update check via RESTful endpoint when I added WP-CLI integration.
