### ISSUE TITLE
Beanstalk?

### ISSUE THREAD

**Issue by wpcrankphilip** [afragen/github-updater#540]
Hello,

I'm new to Git and workflows and settled on Beanstalkapp for my repository and deployment, code reviews, etc.  I found it much more straightforward for an average user than Github, Bitbucket or GitLab (eek).

Is it possible to use GitHub Updater somehow with Beanstalk?  Something that could be built in relatively easily if not?

Thanks much!

Philip

**Comment by afragen** [comment]
I've never used Beanstalk but if they have an API that allows; it should be possible. I'll see what I can do but it won't likely happen soon. 😢

**Comment by wpcrankphilip** [comment]
Alrighty, thanks much for letting me know.  I think I can just setup a dummy Bitbucket repository for use with Github Updater and push my master branch to it to deploy out to the sites using these plugins/themes.

**Comment by afragen** [comment]
FYI, Currently there seems to be an issue with authorization and private Bitbucket repos. I have a ticket in.

**Comment by afragen** [comment]
I will consider re-opening if there is any interest.
