### ISSUE TITLE
What happened to bitbucket and gitlab?

### ISSUE THREAD

**Issue by pingram3541** [afragen/github-updater#542]
I only have 2 tabs under settings, github updater and github.  Used to have all four.

**Comment by afragen** [comment]
You will always have the GitHub Updater and GitHub tabs. The GitHub, Bitbucket, and GitLab tabs only show up if you have plugins or themes that have the appropriate `GitHub Plugin URI`, `Bitbucket Plugin URI`, `GitLab Plugin URI`, etc.

**Comment by pingram3541** [comment]
I see now under the upload plugin/theme tabs there is an option to provide remote repo host: GitLab along with an access token.

I also just changed one of my theme's headers from GitHub to GitLab and saw the appropriate tab show up so I could provide my tokens.

Where I got confused was seeing these other tabs previoulsy when I wasn't using those other services and they are also still shown in the documentation in places that don't actually spell out the dynamic nature of these settings.

Thanks for the explanation!

**Comment by afragen** [comment]
Sorry, about the confusion. I thought it would be nicer to dynamically create the tabs only when needed.

**Comment by pingram3541** [comment]
No worries!  Maybe just add a quick note about the dynamic nature of these settings in the wiki under self hosted / enterprise =)

**Comment by afragen** [comment]
Will do.

**Comment by afragen** [comment]
Settings seemed more appropriate.

https://github.com/afragen/github-updater/wiki/Settings
