### ISSUE TITLE
Handling of enqueue_style within init

### ISSUE THREAD

**Issue by garrett-eclipse** [afragen/github-updater#543]
Hi @afragen 

Noticed this message starts logging during my bash install script once github updater has been installed and activated;
> Notice: wp_enqueue_style was called incorrectly. Scripts and styles should not be registered or enqueued until the wp_enqueue_scripts, admin_enqueue_scripts, or login_enqueue_scripts hooks. Please see Debugging in WordPress for more information. (This message was added in version 3.3.0.) in /home/dev/public_html/cdhf/wp-includes/functions.php on line 4137  

From the looks of it, it's caused by the code within init();
https://github.com/afragen/github-updater/blob/d39c84bf150ff1960b60c3ce265dd7cfa3d7c49e/src/GitHub_Updater/Base.php#L245

Can that stuff be moved into a admin_enqueue_scripts hook to avoid the warning?

Thanks

**Comment by afragen** [comment]
I should be able to do that. I'll report back here.

**Comment by afragen** [comment]
Hopefully https://github.com/afragen/github-updater/commit/8cf28c5cc4372f89c8ba963cb409bb4c747f998d fixes the issue. Let me know.

**Comment by garrett-eclipse** [comment]
You rock @afragen thank you, I'll update you once I've tested today

**Comment by garrett-eclipse** [comment]
Hey @afragen we're good to go with that change, no more warnings during install.

**Comment by afragen** [comment]
Great! Thanks for the bug report. It should hopefully be pushed to master next week.
