### ISSUE TITLE
Plugin throwing internal 404 error

### ISSUE THREAD

**Issue by pnoeric** [afragen/github-updater#545]
Hi Andy, I've set up your excellent plugin and I have it working for a GitHub theme... it all seems to be doing ok. However, it's throwing a 404 error (that I can see in Query Monitor).

Here's what I see (removed the access token):

`GET https://api.github.com/repos///contents/plugin.php?ref=master&access_token=5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`

Error: `404 Not Found`

Call stack:
```
WP_Http->get()
wp-includes/class-http.php:593
wp_remote_get()
wp-includes/http.php:170
Fragen\GitHub_Updater\API->api()
wp-content/plugins/github-updater/src/GitHub_Updater/API.php:131
Fragen\GitHub_Updater\GitHub_API->get_remote_info()
wp-content/plugins/github-updater/src/GitHub_Updater/GitHub_API.php:59
Fragen\GitHub_Updater\Base->get_remote_repo_meta()
wp-content/plugins/github-updater/src/GitHub_Updater/Base.php:482
Fragen\GitHub_Updater\Plugin->get_remote_plugin_meta()
wp-content/plugins/github-updater/src/GitHub_Updater/Plugin.php:196
Fragen\GitHub_Updater\Base->forced_meta_update_plugins()
wp-content/plugins/github-updater/src/GitHub_Updater/Base.php:312
Fragen\GitHub_Updater\Base->init()
wp-content/plugins/github-updater/src/GitHub_Updater/Base.php:271
do_action('init')
wp-includes/plugin.php:453
```
Again, this isn't stopping the plugin from doing its job and keeping my theme updated from the repo, but I would love to get rid of this big error message. Any ideas?

Thanks--

best
Eric

**Comment by afragen** [comment]
Can you share the whole URI minus the access token? Usually that happens if there isn't a `readme.txt` or some sort of `CHANGES.md` file. It shouldn't happen on a main plugin file though.

**Comment by pnoeric** [comment]
Hmm that is the whole URI -- with the 3 `/` characters in a row. If you think this might be plugin-related, I can try disabling and enabling plugins here to see if that might indicate what's going on.

**Comment by afragen** [comment]
What plugins have the `GitHub Updater URI` header

**Comment by pnoeric** [comment]
Hmm none of them that I can see. I tried disabling plugins but I see that doesn't really matter to the code. Let me try deleting plugins and see if that makes a difference.

Also: side question, is there a debug log anywhere? I'm having an issue where the plugin isn't seeing my updated version in the GitHub repo, but I wouldn't be surprised if I've overlooked something. I've double-checked everything and haven't spotted a problem yet, but it would help so much if the plugin had some kind of internal log I can spy on, to see where it's not matching.

**Comment by pnoeric** [comment]
AHA - found the problem. Sure enough, another plugin had a malformed `GitHub Updater` URI header. Fixed it and all is good now. Thank you for your help and support!

**Comment by afragen** [comment]
There is no internal log. I step through the code in XDebug. 

It won't matter if the plugin is disabled. Look for a plugin with an empty `GitHub Plugin URI ` header. 

If you share the URI for your theme I can look at it and let you know if there's an issue.

**Comment by afragen** [comment]
Excellent. I guess we were responding at the same time.

**Comment by pnoeric** [comment]
I think so :-) Thanks again.

**Comment by afragen** [comment]
I just add a red warning dashicon to the Settings submenus to more easily identify which plugin/theme is causing the issue. https://github.com/afragen/github-updater/commit/70a773b2fdf459bf2dc154feb0e56aa2562fd666

**Comment by pnoeric** [comment]
Awesome, I think that is a good improvement.
