### ISSUE TITLE
Theme Update left the update notice until a second update

### ISSUE THREAD

**Issue by garrett-eclipse** [afragen/github-updater#546]
Hello,

With the latest Git-Updater I had to update my theme twice to get the update message to go away. The first update was successful but in the update page shows that there’s an update. To get it to go away I had to update it again.
![screen shot 2017-04-27 at 9 16 47 pm](https://cloud.githubusercontent.com/assets/8726005/25514262/719c4db4-2b90-11e7-9e8d-e6d919ccf434.png)

Sadly I don't have much more information as yet, if I can reproduce consistently or with any errors then will update this ticket.

Cheers

**Comment by afragen** [comment]
I wonder if the cache just didn't clear and a refresh might have made it go away.

**Comment by garrett-eclipse** [comment]
I'll give that a shot if I can reproduce. Is there any DB tables (transients) I should check to see if they just didn't clear properly if this comes up again? Thanks

**Comment by afragen** [comment]
All the DB rows in wp-options table begin with `ghu-`.

**Comment by garrett-eclipse** [comment]
Hi @afragen, came across it again here.
So after the theme update was complete I clicked the Return to Updates link that appears after the install text and the theme update was available and executable. Reloading the Updates page removes the theme.
And in my DB I have two ghu options I'm sending via slack incase there's any sensitive data.
Cheers

**Comment by afragen** [comment]
In the next site you update, refresh the cache before you attempt to update any themes. If that works then I'll have to clear the cache with every update.

BTW, there's no sensitive data in the option, unless you consider the URI, etc. sensitive. 😉

**Comment by garrett-eclipse** [comment]
Thanks @afragen, are you speaking on my browser cache? Comet Cache? or is there a Gitupdater Cache? Will be doing updates next week so will get you an update then when I've gotten around to it. Cheers

**Comment by afragen** [comment]
I was referring to the _cache_ as the data in wp-options as `ghu-`. So after updating GHU use the _Refresh Cache_ button.

**Comment by garrett-eclipse** [comment]
Thanks that's what I was assuming but just wanted to be sure we're on the same page.

**Comment by pixeltherapy** [comment]
I've bumped into the same issue but never found a way to reproduce it. I've avoided it over the past many months by simply refreshing the GHU cache before I attempt any updates. This becomes annoying when deploying multiple patches to a theme in one day.

Maybe exposing some options on cache behaviour is a quick fix. Such as the cache timeout, which seems to be ```self::$hours = 6 + rand( 0, 12 );``` as found on line 439 of ```Base.php```.

Here I am back talking about timeouts again... I'm not obsessed, promise! 😺

**Comment by afragen** [comment]
@pixeltherapy I think this issue had more to do with me not flushing the cache after an update to GHU. 

You certainly shouldn't need to refresh the cache before attempting an update, unless you are pushing out multiple updates within 6-18 hours. I would encourage you to take a look at using a webhook and then any time you push an update your site would automatically reflect those changes. If you want to try that and have issues, hit me up in Slack.
