### ISSUE TITLE
Push to deploy broken with 6.3.0

### ISSUE THREAD

**Issue by benoitchantre** [afragen/github-updater#547]
With the latest version of GitHub Updater (6.3), push to deploy doesn't work anymore.
I haven't touched the settings.

After I restored GitHub Updater 6.2.2, push to deploy worked again.

Note: tested with Bitbucket and a private repository

**Comment by afragen** [comment]
Are you referring to using a webhook?

**Comment by benoitchantre** [comment]
Yes

**Comment by afragen** [comment]
Did your API key change or did you change how the webhook was setup? Does the Webhook section in Bitbucket display the reponse?

**Comment by afragen** [comment]
I personally use the feature to update GHU on my test site with each commit to develop. So I know it's working here. I did find that a couple of other webhooks I had set up previously were failing because of a bad API key.

**Comment by benoitchantre** [comment]
I need to make more tests, but I can't do them today. What I remember is that there was an error during the upgrade of GitHub Updater, but the version number was 6.3.0 after the upgrade.
I'll reinstall all the files manually, test again and keep you informed.

**Comment by benoitchantre** [comment]
The API key wasn't changed. Once I reinstalled version 6.2.2, it worked as before.

**Comment by benoitchantre** [comment]
I just did a new test on another project. The upgrade of GitHub Updater was successful, but when I pushed a commit, it wasn't deployed.

Here's the response body:
```
{
  "messages": [
    "Downloading update from <span class=\"code\">-- URL REMOVED --</span>&#8230;",
    "Unpacking the update&#8230;",
    "The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature"
  ],
  "response": {
    "hash": "c5e022d4e60470b7d50585e484e25a264caa2afa",
    "branch": "develop",
    "json_error": "No error"
  },
  "error": true
}
```

**Comment by afragen** [comment]
That error is an authentication error. You might want to re-enter your password and test to see if it's correct. 

The only thing I haven't tested is using your email as a username.

**Comment by afragen** [comment]
It think I know what it is. I changed the addition of the Basic Auth header to a new class and I'm guessing something isn't adding it during the REST update. 

I'll look into and have a fix soon. Thanks for the report.

**Comment by afragen** [comment]
Can you switch to the develop branch of GitHub Updater and test again? I think I found the issue https://github.com/afragen/github-updater/commit/a96e004eb3dc6a45cac553650116d376bf06708d

**Comment by benoitchantre** [comment]
I get the same error after having switch to the develop branch.

**Comment by afragen** [comment]
Yeah, I just tried locally. Stay tuned.

**Comment by afragen** [comment]
I believe it's now fixed. I had to account for a different `$_REQUEST` format in `class Basic_Auth_Loader`. https://github.com/afragen/github-updater/commit/542ac4bd4ddc7e29707c330b091de4dafc6ab9c4

And still works elsewhere 💯 

Reload the develop branch to test.

**Comment by benoitchantre** [comment]
Tested with version 6.3.0.3: it works.
Thank you for the fix.

I'll let you close the issue once you push the hot fix.

**Comment by benoitchantre** [comment]
I have noticed it doesn't work again with 6.3.3
A bug was introduced between 6.3.2 and 6.3.3

**Comment by afragen** [comment]
Can you try testing the develop branch?

**Comment by rolandinsh** [comment]
in development branch still not working.

**Comment by rolandinsh** [comment]
Some updates from `master` branch: (testing with bitbucket)

1. BitBucket's webhooks do not work. As it's stated in this issue
2. However, in plugin screen, clicking `update` triger (link) plugin from bitbucket is updated as should

I hope this help more

**Comment by afragen** [comment]
Can you tell me what the response from the webhook is?

**Comment by rolandinsh** [comment]
HTTP status: 500

Body
`
{
  "messages": [
    "Tiek lejupielādēts jauninājums no <span class=\"code\">https://bitbucket.org/simplemediacode/********/get/*******02d*******.zip</span>&#8230;",
    "Tiek izpakots jauninājums&#8230;",
    "Pakotni nevarēja instalēt. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature"
  ],
  "response": {
    "hash": "XXXXXY*******",
    "branch": "master",
    "json_error": "No error"
  },
  "error": true
}
`

**Comment by rolandinsh** [comment]
serverside everything works as should.

**Comment by afragen** [comment]
Please test with `develop` branch. I think I've fixed it.

**Comment by rolandinsh** [comment]
Look like update work, **but**
in BitBucket I receice `Request status: TIMEOUT` bu by visiting webhook's URI for plugin update (in my case), header response status is 200;

No errors in logfile of server.

**Comment by afragen** [comment]
The timeout sounds like an intermittent issue with Bitbucket.

**Comment by benoitchantre** [comment]
I works again with `develop` branch.

**Comment by afragen** [comment]
Thanks for your help. Releasing fix now.
