### ISSUE TITLE
Generic css should be more specific

### ISSUE THREAD

**Issue by pingram3541** [afragen/github-updater#548]
This line is effecting one of my themes and should have a more unique identifier/selector please. TY =)

/github-updater/css/github-updater.css:
`.form-table th[scope='row']:empty{display:none;}`

**Comment by afragen** [comment]
What page is it affecting? It only loads on the admin?

**Comment by pingram3541** [comment]
It was a premium theme called BeTheme sold on ThemeForest.  I have a few clients using this theme and it causes any empty th element to lose it's width properties and the resulting td slides behind the left admin bar making the links difficult to click.  I've fixed it by loading my own conditional admin css specific to that page and query string with:

```
#mfn-wrapper .form-table th[scope='row']:empty {
    display: inherit;
}
```

And loading it conditionally via:

```
add_action( 'admin_enqueue_scripts', 'mfnch_admin_enqueue', 101 );
function mfnch_admin_enqueue(){

    global $pagenow;
    if (
        $pagenow == 'themes.php' && ($_GET['page'] == 'muffin_options') )
    {
        $field_upload_path = CHILD_THEME_URI .'/css/custom-admin.css';
        wp_enqueue_style( 'custom-admin'.$hook_suffix, $field_upload_path, array(), time(), 'all' );
    }
}
```

**Comment by afragen** [comment]
I think I might be able to split the CSS into 2 files and load the segment causing this particular issue only on the GitHub Updater Settings page. I'll work on it.

**Comment by pingram3541** [comment]
Or if there is a unique id parent element just add that to the css

**Comment by afragen** [comment]
This should fix the issue. https://github.com/afragen/github-updater/commit/0a9275dc877f50b8463b4f04398751acecdc8454
