### ISSUE TITLE
Misc. issues on activation / deactivation of plugins

### ISSUE THREAD

**Issue by benoitchantre** [afragen/github-updater#549]
Some notices are triggered on activation / deactivation of plugins since GitHub Updater 6.3.0

- Undefined index in Basic_Auth_Loader.php on line 148
- Trying to get property of non-object in Basic_Auth_Loader.php on line 148

**Comment by afragen** [comment]
Hmm, activation/deactivation of plugins shouldn't really matter to GHU. Perhaps something like the following would fix that.
```php
$type  = isset( $_REQUEST ) && $slug ? $repos[ $slug ]->type : $type;
```

**Comment by afragen** [comment]
In latest develop branch, does https://github.com/afragen/github-updater/commit/0eb1687780f49ebdac2f76235eca165bd4964ae6 fix the issue?

**Comment by benoitchantre** [comment]
Unfortunately, it doesn't.

**Comment by afragen** [comment]
I made a change from that commit. https://github.com/afragen/github-updater/commit/db894a23cecad6b0bb2de01f92df712ac1082c34 Does that work?

**Comment by afragen** [comment]
How do you trigger the error?

**Comment by benoitchantre** [comment]
To trigger the error, I activate / deactivate any installed plugin.
The latest commit fixes the issue.

**Comment by afragen** [comment]
Odd but glad it's fixed.
