### ISSUE TITLE
[v6.3.1] PHP Notices

### ISSUE THREAD

**Issue by calvintam236** [afragen/github-updater#550]
```
PHP Notice:  Trying to get property of non-object in /wp-content/plugins/github-updater/src/GitHub_Updater/Basic_Auth_Loader.php on line 148

PHP Notice:  Undefined index: wordpress-beta-tester in /wp-content/plugins/github-updater/src/GitHub_Updater/Basic_Auth_Loader.php on line 148
```

I dont know is the error occur when I install the plugin inside WP.

**Comment by afragen** [comment]
Can you test the current develop branch. I think is the same as #549

**Comment by calvintam236** [comment]
Updated to 6.3.3, and got another (similar) error.
```
PHP Notice:  Undefined index: . in /wp-content/plugins/github-updater/src/GitHub_Updater/Basic_Auth_Loader.php on line 148
PHP Notice:  Trying to get property of non-object in /wp-content/plugins/github-updater/src/GitHub_Updater/Basic_Auth_Loader.php on line 148
```

Have you pushed the fix to master yet?

**Comment by afragen** [comment]
Does this persist? When do you see it? 
ab202c2e5b0ab2d4f81fc29b9dc47c5c3a413baa Should have fixed it.

**Comment by calvintam236** [comment]
I think possible by checking/ installing plugin updates. I see this error on loading `/wp-admin/network/update-core.php` on v6.3.3.

I can't tell if one of the plugins triggered it.. I can give you login info for the testing site, so you can debug yourself?

**Comment by afragen** [comment]
That would be great. You can DM me the credentials on Slack.

**Comment by afragen** [comment]
Actually, can you switch to the `develop` branch and see if the error persists?

**Comment by calvintam236** [comment]
I think the develop branch works so far after updating the page, updating the plugin using Github Updater.

**Comment by afragen** [comment]
Let me know if the error comes back. Next week I'll push a  release if I don't hear back.
