### ISSUE TITLE
Feature: Look for theme's style.css from subfolder

### ISSUE THREAD

**Issue by jloproductions** [afragen/github-updater#551]
Hey,

Is it possible to get this plugin to search style.css from theme's subfolder?

[Sage starter theme](https://github.com/roots/sage) has updated it's folder structure and style.css is inside the resources folder. And right now while github-updater doesn't search files from sub folder there isn't a way to get updates for themes with this folder structure.

**Comment by afragen** [comment]
GitHub Updater is designed to look for the main plugin/theme files in the root directory, exactly as dot org requires. At this point there are no plans to support plugin or theme placement in subfolders.

**Comment by nboliver** [comment]
@eljass Did you find a way around this issue?

**Comment by afragen** [comment]
GitLab Groups is something similar which does work with GitHub Updater

**Comment by nboliver** [comment]
@afragen Thanks for the reply. How does GitLab Groups help with a style.css file that's located in a subdirectory?

**Comment by afragen** [comment]
It allows for grouping repositories so you would have something like `owner/group/repo1`, `owner/group/repo2` instead of simply `owner/repo1` and `owner/repo2`

I guess it’s not quite the same but is an interesting concept from GitLab. Unfortunately WP defines a theme by having the style.css file at the root level. 

Sage must have some pre-processing that brings the `resources` folder to the root level.

There might be a way by replicating the style.css file at the root level and create a post-processed release asset that GHU can utilize. https://github.com/afragen/github-updater/wiki/Settings#release-assets

**Comment by SamirJoza** [comment]
Well, there is no problem putting the style.css into the root level (Sage 9), however, next step is, that the updater expects an index.php file in the root level as well, and here is where everything break, once I put a blank index.php file into the root, github updater dies (too many redirects and the theme is no longer working. -- Is there not a way to disable the file checking (if files required by WP are present) ?

**Comment by afragen** [comment]
GHU only expects the `style.css` at the root level. If you’re using a build process you will need to create a release asset and also set the appropriate header.

Do you have a repo I can look at?

**Comment by SamirJoza** [comment]
Well, as you know, I am sure, Sage requires composer, but in my instance, for this project the host does not allow composer so I save a bit more into the repo, than what I need to save. But here it is: 
https://bitbucket.org/samirjozateam/order_theme/
Right now I am just playing around with GHU and try to incorporate that into my workflow.

**Comment by afragen** [comment]
@SamirJoza first your header is incorrect. It should be `Bitbucket Theme URI`. Also, do not put your username in the URI. 

I use composer for my projects and I understand if you don’t wish to put the vendor directory under version control. You will need to create and list a release asset to each tag per Bitbucket requirements. 

You will also need to add the appropriate header for release asset. 

If you want to play around I would suggest something a little simpler. Try using https://bitbucket.org/afragen/test-bitbucket-child

**Comment by SamirJoza** [comment]
@afragen thank you very much for getting back to me that quickly. GHU works fine for all my other "projects" (plugins/simple themes), I just had an issue with Bitbucket, and the Sage theme (sage is a new experience for me) :)
