### ISSUE TITLE
Request: Add method to set Bitbucket Basic Auth credentials via WP-CLI

### ISSUE THREAD

**Issue by fatjester** [afragen/github-updater#552]
I'm hoping to use WP-CLI to automate the install/setup process for creating Wordpress sites.
We use private Bitbucket repos, and would like to install custom plugins and themes from there.

Without having method to set up basic auth in github-updater from wp-cli, I can't fully automate the setup through wp-cli as I'd like.

Thanks for looking into it!

**Comment by fatjester** [comment]
Your suggestion on the slack channel works for this, thanks for the help!
For anyone else looking, this can be done through the wp-cli option update.
Here's the wp-cli code I used to install from a bitbucket private repo:

#install & activate the github-updater plugin
wp plugin install https://github.com/afragen/github-updater/archive/master.zip --activate
#set the username and password options for the bitbucket account
wp option update github_updater '{"bitbucket_username":"my-username","bitbucket_password":"my-password"}'  --format=json
#install and activate them from bitbucker private repo
wp theme install-git https://bitbucket.org/my-username/my-theme --bitbucket-private

**Comment by afragen** [comment]
Thanks for writing this up. I added it to the WP-CLI page on the wiki. 

https://github.com/afragen/github-updater/wiki/WP-CLI#adding-credentials-to-github-updater
