### ISSUE TITLE
arguably incorrect usage of sanitize_file_name() in Settings::sanitize()

### ISSUE THREAD

**Issue by pbiron** [afragen/github-updater#553]
In `Settings::sanitize()` you have the following code:

```PHP
foreach ( array_keys( (array) $input ) as $id ) {
	$new_input[ sanitize_file_name( $id ) ] = sanitize_text_field( $input[ $id ] );
}
```

and I think it would be safer to replace that by:

```PHP
foreach ( array_keys( (array) $input ) as $id ) {
	$new_input[ sanitize_key( $id ) ] = sanitize_text_field( $input[ $id ] );
}
```

After all, `$id` is an array key and **not** a filename.

I'm trying to use GitHub Updater on a site that uses another plugin which hooks into the [santize_file_name](https://developer.wordpress.org/reference/hooks/sanitize_file_name/) filter to [md5()](http://php.net/manual/en/function.md5.php) hash filenames (in a weird attempt to change the filenames of uploaded media to "random" strings...don't ask, I have to use that other plugin, despite this weirdness :-(.

Arguably, that other plugin is incorrectly using the `santize_file_name` filter.  I have also filed a bug report with its author, suggesting they hook into the [wp_handle_upload_prefilter](https://developer.wordpress.org/reference/hooks/wp_handle_upload_prefilter/) filter instead to accomplish their goal.

Because of that other plugin's arguably incorrect use of the `santize_file_name` filter and GitHub Updater's arguably incorrect use of `santize_file_name()`, it's not possible to save changes to GitHub Updater's settings when both plugins are active.

Granted, there is nothing preventing yet some **other** plugin from hooking into the [santize_key](https://developer.wordpress.org/reference/hooks/sanitize_key/) filter and doing weird things to your option keys, but I think the chances of that are less.

**Comment by afragen** [comment]
Both `sanitize_file_name()` and `sanitize_key()` have filters. Your other plugin, or you, can use the `remove_filter()` to remove that specific instance of the other hook. Just make sure you do it after it runs and before GitHub Updater runs.

You might be able to hook into the `github_updater_set_options` filter to run the `remove_filter()` hook. Just remember to `return array()` with that hook.

**Comment by afragen** [comment]
I use `santize_file_name()` because not every key is of my creation. Many are the slugs of plugins/themes and `sanitize_key` was too restrictive.

**Comment by pbiron** [comment]
OK.  I'll push back harder on the developer of that other plugin since their misuse of `sanitize_file_name` is worse (and has a viable alternative).  I'll also look into your suggestion of temporarily removing their hook until they change.

**Comment by afragen** [comment]
What I described for using the `remove_filter` is what the other developer should be doing after it runs. 

If you add it correctly it will work for the other plugin and be removed when GHU runs. Ideally that's how it should work.
