### ISSUE TITLE
Programmatically reset cache

### ISSUE THREAD

**Issue by pnoeric** [afragen/github-updater#555]
(feature request)

Hi Andy, we're using your excellent plugin to deploy new versions of our clients' sites. I edit the site, check in changes to GitHub, bump the version number, then manually go to the site, click "Clear Cache" in your plugin, and then I can click "Update Theme" to load in the updated theme.

Could there be a way to send a message to the plugin (something I could do in my `gulp` process, ideally) to reset the cache? This would save me a step in deployment.

Perhaps if I just access a hashed enpoint inside the plugin, i.e. something like:

`http://mysite.com/wp-admin/options-general.php?page=github-updater-clearcache&tab=reset-cache&hash=14b3aa7a0b7df7070e4092fc7d7449f1`

This would just reset the cache on the server.

What do you think? (And of course, if there is a more elegant way for me to do this, that's cool!)

Thanks and best wishes from Zürich--
Eric

**Comment by afragen** [comment]
If your looking for a programmatic way to clear the cache it's in WP-CLI.

`wp github-updater cache delete` should do it. Please refer to the Wiki for other commands.

The other thing you could do is set up a webhook for those specific repos to automatically push updates to specific sites when you commit/tag. Again, take a look at the wiki for more info. 🤓

**Comment by pnoeric** [comment]
Brilliant, thanks. I'll look at both of those options.

**Comment by pnoeric** [comment]
Quick followup, looks like WP CLI route will be the easiest. I found this [Gulp module](https://www.npmjs.com/package/wp-cli) that I think will do the job... will try wiring it all up later today. Thanks again for the prompt response.

**Comment by afragen** [comment]
Installing WP-CLI will open up all sorts of possibilities.

**Comment by afragen** [comment]
Of course you could just wait until the cache expires automatically in 6-18 hours 😉

**Comment by pnoeric** [comment]
Yeah, but after we rev a client site, we want to push that change live right away. I can see other circumstance where waiting would be a good idea... but not for this particular way we're using the tool. 👍

**Comment by afragen** [comment]
Using a webhook really is cool in this use case.
