### ISSUE TITLE
Wordpress admin pages load slow upon plugin activation

### ISSUE THREAD

**Issue by majiix** [afragen/github-updater#558]
Hi,
When github updater is active almost all pages of admin panel, specially those that are related to WP settings or other plugins settings page works and loads so slow that you have to wait about 5 minutes to load.
And when the plugin is not active everything works fine and so fast.
I should mention that my WP is on a SSD VPS and i have checked every possible issue and it was just because of github updater.
It would be great if you could fix it.
Thank you

**Comment by afragen** [comment]
How many plugins and themes do you have that work with GitHub Updater?

GHU is only active on certain admin pages and when it's not making API calls doesn't tune much time. Try installing the Query Monitor plugin too.

**Comment by majiix** [comment]
Currently 1 theme and 10 plugins are installed via GHU and they're all on gitlab.

**Comment by majiix** [comment]
OK, i installed Query Monitor  and activated GHU. Now there is 40 HTTP request which 39 of them is for GHU. 


HTTP Request
`GET https://gitlab.com/api/v3/projects?per_page=100&private_token=xxxxxxxxxx`

Response
`cURL error 28: Operation timed out after 5001 milliseconds with 0 bytes received`

Call Stack

`WP_Http->get()
wp-includes/class-http.php:612
wp_remote_get()
wp-includes/http.php:170
Fragen\GitHub_Updater\API->api()
wp-content/plugins/github-updater/src/GitHub_Updater/API.php:133
Fragen\GitHub_Updater\GitLab_API->get_gitlab_id()
wp-content/plugins/github-updater/src/GitHub_Updater/GitLab_API.php:407
Fragen\GitHub_Updater\GitLab_API->get_remote_info()
wp-content/plugins/github-updater/src/GitHub_Updater/GitLab_API.php:72
Fragen\GitHub_Updater\Base->get_remote_repo_meta()
wp-content/plugins/github-updater/src/GitHub_Updater/Base.php:483
Fragen\GitHub_Updater\Plugin->get_remote_plugin_meta()
wp-content/plugins/github-updater/src/GitHub_Updater/Plugin.php:197
Fragen\GitHub_Updater\Base->forced_meta_update_plugins()
wp-content/plugins/github-updater/src/GitHub_Updater/Base.php:313
Fragen\GitHub_Updater\Base->init()
wp-content/plugins/github-updater/src/GitHub_Updater/Base.php:272
do_action('init')
wp-includes/plugin.php:453`


Component
`Plugin: github-updater`


And the other 39 error are the same as above.

**Comment by afragen** [comment]
Only API calls take time. There are about 6 calls per plugin/theme. All values are cached between 6-18 hours randomly. Turning off branch switching decreases one API call per repo. Using the filter to _scale_ eliminates most API calls but does limit some functionality. Please refer to the wiki. 

Also, API calls only occur for privileged users.

**Comment by majiix** [comment]
I think the problem was with limiting the HTTP request methods. only GET, POST and HEAD was allowed and when i commented the command on the server things work much better even when GHU is active. Except GET, POST and HEAD which other methods should be enabled?

**Comment by afragen** [comment]
I've gotten hit with the `cURL timeout` errors on GitLab too. The only way I've dealt with it was to increase the HTTP timeout. I think using the `http_request_args` filter.

**Comment by afragen** [comment]
```php
add_filter( 'http_request_args', function( $args, $url ) {
	$args['timeout'] = 8;
	return $args;
} );
```
Should do the trick, I think.

**Comment by afragen** [comment]
You might need to change to a longer timeout.

**Comment by majiix** [comment]
I moved everything to github and its now awesome. gitlab has serious issues.

**Comment by afragen** [comment]
Not sure why gitlab is slow but using the above filter would help. Maybe they're just having scaling issues. I haven't found that it's consistent.

Glad it's all working out. I've also seen an occasional timeout with Bitbucket.com too.
