### ISSUE TITLE
Branch list API limit

### ISSUE THREAD

**Issue by joelworsham** [afragen/github-updater#559]
If there's too many branches, they won't all show up in the branch switcher. The GitHub API has a limit on how many returned branches it shows. I verified because the newest branch I wanted to switch to didn't show up so I:

1. Used the GH API tester and verified the branch didn't show.
2. Set the query param `page` to `2` on the API call and then it _did_ show up.

I cannot figure out what (or if there even is) the query parameter for upping how many branches are returned... I would say either this plugin should figure that out and up the limit or anticipate a possibly paginated result and try looping through each `page` until no more are found.

**Comment by afragen** [comment]
Can you tell me the URL for the repo? How many branches are there?

**Comment by afragen** [comment]
I may be able to use the `per_page` query arg. https://developer.github.com/v3/#pagination

Any thoughts on how high to set it?

**Comment by afragen** [comment]
Can you test latest `develop` branch. https://github.com/afragen/github-updater/commit/3da3cbf6c74db0c4ed982df8411701cdab268f08

Not sure I can do much better.

**Comment by joelworsham** [comment]
Thanks! I can't test now actually because the temporary solution was pruning stale branches, so I don't have access to a repo with that many branches anymore, but I will keep an eye out for it! Thanks, as always, for your quick response.

**Comment by afragen** [comment]
Not to worry Joel. It should be fixed in any event.
