### ISSUE TITLE
Password Fields

### ISSUE THREAD

**Issue by jcwrightson** [afragen/github-updater#560]
Password fields appear to be plain text? And installing theme from bitbucket gives me this error: PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature

**Comment by afragen** [comment]
When you say plaintext, yes passwords are stored in the database in plaintext. For Bitbucket Basic Auth they are then converted to the appropriate HTTP header.

The error you're seeing is because the user/pass is incorrect.

**Comment by jcwrightson** [comment]
OK thanks for your clarification. Is there any plans to just hash the password first? I don't like the idea of putting my github / bitbucket credentials on client sites available to anyone who knows how to work phpmyadmin, but then i guess this would rule out basic auth?. Aside from this, the password field is not of type "password" while in the install theme UI, this is actually what I meant by "plain text" sorry. Anyway, keep up the good work! :)

**Comment by afragen** [comment]
If they have access to the database it really doesn't matter. The best I could do is store the base64 auth string and it's still easy to decode that. Anything I do to hash the password would still have to be un-hashed to create the HTTP Basic Auth header.

Type _password_ allows users to copy the screen and not worry as dots replace characters.

**Comment by afragen** [comment]
1. You can remove the GitHub Updater Settings page with a filter.
2. You can pass credentials in a filter.
3. You can make your clients create Bitbucket/GitHub/GitLab accounts and just add them as `read-only` user to specific repos.

**Comment by jcwrightson** [comment]
Great, thanks! I thought md5 passwords cannot be unhashed without rainbow
tables? I just created a default user with read-only rights instead. I did
however get another error msg: "Too many redirects"

**Comment by afragen** [comment]
> Great, thanks! I thought md5 passwords cannot be unhashed without rainbow
> tables? I just created a default user with read-only rights instead.

md5 hash can't be used as I need to pass base64 hash of actual _"user:pass"_

> I did however get another error msg: "Too many redirects"

Not sure about where that's coming from.

**Comment by jcwrightson** [comment]
Ok, is there a way to register the theme with the plugin? Say, because i've
had to use git to clone the theme, now i want the plugin to track the
theme. On my local machine, manually cloning the theme, then installing the
plugin resulted in the plugin recognising the theme. But on production
sites, this is not the case...

**Comment by afragen** [comment]
Is that because production sites didn't have he user:pass set?

Take a look at the wiki here, https://github.com/afragen/github-updater/wiki/Developer-Hooks

There are hooks you can use to set variables or to complete hide the customer's GitHub Settings.

**Comment by talymo** [comment]
If someone were to gain access to the Wordpress Admin panel, they could go into the Github Updater Settings > Bitbucket tab and change the input type from 'password' to 'text' using the front end inspector on any web browser and see your password for your entire Bitbucket account. This seems a little dangerous. Perhaps storing this in the backend and not displaying it in the admin panel is a good security call. If they want to change the username and password, then they have to install the theme again. Seems dangerous to have your entire BitBucket login credentials just sitting there on the off-chance that someone wants to change their password (which should be rare).

**Comment by afragen** [comment]
Only admin privileged users will even see the GitHub Updater Settings. https://github.com/afragen/github-updater/blob/develop/src/GitHub_Updater/Base.php#L244-L246
https://github.com/afragen/github-updater/blob/develop/src/GitHub_Updater/Base.php#L301

If anyone wants to help with a PR for oAuth support I would be extremely grateful. Otherwise, how else would someone change a Bitbucket login? Once stored there is no login field for a new repo install. oAuth is the real answer but I just don’t know how to accomplish that.

#323
