### ISSUE TITLE
Plugin Localization for Traditional Chinese is complete

### ISSUE THREAD

**Issue by alexclassroom** [afragen/github-updater#561]
Hi Developer,

I have completed plugin localization for Traditional Chinese, please get the latest PO and MO file from the following Box sharing link.

https://app.box.com/s/6qc9djub5plkg3oj660dvfus19qvumu5

Please put them to your plugin, thanks.

Regards,

Alex Lion

**Comment by afragen** [comment]
Hey Alex,

Can you make the PR against, https://github.com/afragen/github-updater-translations in the future. I've separated the translations from the actual plugin file for simplicity.

Thanks for the files. You should see an update soon.

Thanks.
