### ISSUE TITLE
Version 6.3.5?

### ISSUE THREAD

**Issue by DuckDivers** [afragen/github-updater#565]
Is there a version 6.3.5?  I keep getting notifications of update but it doesn't seem to find this version, and its not in the Repo.

Additionally, I've been getting this error (on multiple sites):

Invalid argument supplied for foreach() in / ... /wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 701

Thanks.
Howard

**Comment by afragen** [comment]
Mea culpa. I thought I pushed the tag but evidently did not. Give me until tomorrow otherwise it's Groundhog Day. 🤦🏻‍♂️

**Comment by DuckDivers** [comment]
lol... no problem.  We've all been there.

**Comment by afragen** [comment]
Now tagged.
