### ISSUE TITLE
Missing BitBucket Update Button

### ISSUE THREAD

**Issue by cbratschi** [afragen/github-updater#567]
After upgrading the plugin to 6.3.5.4 there is a new option in the select branch dropdown. However, after selecting the branch the UI no longer offers an install button. The previous version was working fine.

**Comment by afragen** [comment]
Can you show me a screenshot of this? Perhaps I'm not fully understanding the issue.

This is what I see.
![screenshot_01](https://user-images.githubusercontent.com/1296790/27929967-d0ec7c04-6249-11e7-8708-0672607d1af7.png)

**Comment by cbratschi** [comment]
Well, it is in German:

1) main branch selected

<img width="341" alt="bildschirmfoto 2017-07-06 um 22 57 46" src="https://user-images.githubusercontent.com/3909121/27932636-c61fee82-629e-11e7-9028-3408b60a95cc.png">

2) open dropdown

<img width="340" alt="bildschirmfoto 2017-07-06 um 22 57 58" src="https://user-images.githubusercontent.com/3909121/27932650-d15b7014-629e-11e7-969c-2b1d700d3317.png">

I also checked the HTML code and there is no button there. After #ghu_versions there is an empty p element. Also tried to reset all caches but did not help.

**Comment by afragen** [comment]
Can you send me a URL to the theme?

**Comment by cbratschi** [comment]
It is a private project, I cannot share the URL.

**Comment by afragen** [comment]
Try using the branch switcher to reinstall the `develop` branch and see if it works.

Unfortunately I cannot replicate this.

**Comment by afragen** [comment]
Can you install my test child theme, https://github.com/afragen/test-child and see if the branch switcher workshop?

**Comment by cbratschi** [comment]
I was already on develop. Switched to master where it works again.

I will try your child theme next.

**Comment by cbratschi** [comment]
It works with your test-child theme from GitHub. My theme from a private BitBucket repository does not work. I hope this helps to track it down.

I am switching now back to the master version which works fine, until this issue is fixed.

**Comment by afragen** [comment]
Install Query Monitor and you should be able to see what the HTTP request error is. Does your theme show up in the Bitbucket tab of Settings?

**Comment by afragen** [comment]
@cbratschi you haven't really given me enough information to see what may be causing _your_ particular issue. What you have demonstrated is that my test repository works. It's possible there's an issue with your repository, but I can't tell from the info provided.

I tested with a private Bitbucket repo that I have access to and it works as expected.

If you give `afragen` `read` access to the repository I might be able to help more.

**Comment by afragen** [comment]
This should be fixed in `develop` branch. https://github.com/afragen/github-updater/commit/6a864fefeea9e73dbe173cb7f2179a4147081df3

**Comment by cbratschi** [comment]
Thanks a lot, it works again.
