### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by StaggerLeee** [afragen/github-updater#568]
Your plugin freeze servers, and I have to restart them. I believe it is your plugin, judging by this Apache error log:

`Thu Jul 06 18:53:43.181967 2017] [:error] [pid 6492:tid 1724] [client ::1:1172] PHP Fatal error:  Uncaught Error: Call to undefined method Fragen\\GitHub_Updater\\GitHub_API::local_file_exists() in D:\\Neard\\www\\classifieds_wp\\wp-content\\plugins\\github-updater\\src\\GitHub_Updater\\GitHub_API.php:166\nStack trace:\n#0 D:\\Neard\\www\\classifieds_wp\\wp-content\\plugins\\github-updater\\src\\GitHub_Updater\\Base.php(491): Fragen\\GitHub_Updater\\GitHub_API->get_remote_readme()\n#1 D:\\Neard\\www\\classifieds_wp\\wp-content\\plugins\\github-updater\\src\\GitHub_Updater\\Plugin.php(197): Fragen\\GitHub_Updater\\Base->get_remote_repo_meta(Object(stdClass))\n#2 D:\\Neard\\www\\classifieds_wp\\wp-content\\plugins\\github-updater\\src\\GitHub_Updater\\Base.php(313): Fragen\\GitHub_Updater\\Plugin->get_remote_plugin_meta()\n#3 D:\\Neard\\www\\classifieds_wp\\wp-content\\plugins\\github-updater\\src\\GitHub_Updater\\Base.php(1378): Fragen\\GitHub_Updater\\Base->forced_meta_update_plugins(true)\n#4 D:\\Neard\\www\\classifieds_wp\\wp-content\\plugins\\github-updater\\src\\GitHub_Updater\\API.php(76): Fragen\\GitHub_Updater\\Base->make_update_transient_current('update_plugins')\n#5 D in D:\\Neard\\www\\classifieds_wp\\wp-content\\plugins\\github-updater\\src\\GitHub_Updater\\GitHub_API.php on line 166, referer: http://localhost/classifieds_wp/wp-admin/plugins.php?plugin_status=all&paged=1&s`

**Comment by afragen** [comment]
That method `API->local_file_exists()` is in `class API` which `class GitHub_API` extends. As such it is available from the call `$this->local_file_exists( $filename )` from within `class GitHub_API`.

Is there more in the error log?

**Comment by StaggerLeee** [comment]
Hi afragen. No, nothing more, just some notices as usual. Cannot see PHP error log, something is not configured right on servers. Have to see what.
I believe just some glitch with overwriting files when plugin is updated. Maybe my server got limit of 512 MB when plugin was updating, I work on several websites at once. Cannot know now, impossible.

**Comment by afragen** [comment]
Does that mean it's working again?

**Comment by StaggerLeee** [comment]
I did not test yet. You can close issue, believe something just happened under update process. I noticed my Windows in last time lock some WP plugin folders for no so obvious reason. No file is in use, and even when servers disabled.

Cannot test it now, as it needs update process.
