### ISSUE TITLE
PHP Notices again

### ISSUE THREAD

**Issue by calvintam236** [afragen/github-updater#572]
Just updated to v6.3.5.7. Got these notices at my dashboard, plugin page, etc.

```
Notice: Undefined index: callback_method in /wp-content/plugins/github-updater/src/GitHub_Updater/Settings.php on line 486

Notice: Undefined index: callback_method in /wp-content/plugins/github-updater/src/GitHub_Updater/Settings.php on line 490

Notice: Undefined index: page in /wp-content/plugins/github-updater/src/GitHub_Updater/Settings.php on line 491

Notice: Undefined index: section in /wp-content/plugins/github-updater/src/GitHub_Updater/Settings.php on line 492
```

**Comment by afragen** [comment]
Is there a specific repo you’re seeing this on? I’ve not seen any of these previously.

**Comment by afragen** [comment]
Can you show a screenshot of your Bitbucket Settings tab?

**Comment by calvintam236** [comment]
I think it is happening on all repos (4 sets of the above errors)

scrolled down to take the screenshot.
![screen shot 2017-07-09 at 9 36 52 pm](https://user-images.githubusercontent.com/6436149/28003003-c9760164-64ee-11e7-87a7-76c2edbe18a9.png)

**Comment by afragen** [comment]
I think this should fix it. https://github.com/afragen/github-updater/commit/3909705ba8d71143880af3d94ddeaf5dadc52493

Re-install the `develop` branch to get the update.

**Comment by afragen** [comment]
How is it that there's no Username or Password field?

**Comment by afragen** [comment]
The error seems as if `Settings->load_apis()` fails.

**Comment by calvintam236** [comment]
It seems those fields are gone after upgrading the updater. (It used to have..)

After refreshed to latest `develop` branch, those notices are gone.
I rolled back to `master` branch, and the fields are back. Some codes are broken in `develop` branch for bitbucket.

**Comment by afragen** [comment]
The problem stems from `Settings->load_apis()` not running or not running properly for you. The question is why? Removing the error notices doesn't seem to be the correct thing to do.

**Comment by calvintam236** [comment]
It seems that is another notice in the debug.log.
```
PHP Notice:  Undefined index: sections in /wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 1031
```

For the investigation, do you have an option in the UI to generate debug log? Alternatively, I can send you the username and password to log in?

**Comment by afragen** [comment]
Is that last notice in the `develop` branch?

Can you try recreating the initial issue using a clean WP install and only the `develop` branch of GHU and one of your plugins?

Add the remaining plugins to see if any one in particular might be at issue.

**Comment by calvintam236** [comment]
I think the notice is on `develop` branch because of the time logged.

That would take a while to make a clean install.. My setup is multisite with 10+ plugins. 

I know v6.3.4.x has those missing fields. Can you see what is changed from that version to the latest `develop`?

**Comment by afragen** [comment]
> I think the notice is on develop branch because of the time logged.

That's line is inside a comment block at this time. 

> That would take a while to make a clean install.. My setup is multisite with 10+ plugins.

> I know v6.3.4.x has those missing fields. Can you see what is changed from that version to the latest develop?

I made the changes to make the code a bit more modular so if a user doesn't have classes for Bitbucket or GitLab APIs installed they shouldn't get errors. I test in both single and multisite and I don't see this error. 

You see this error because there seems to be an issue for you with `load->apis()`. If you can step through it and see why it doesn't seem to be functioning.

**Comment by afragen** [comment]
I think I've fixed this. https://github.com/afragen/github-updater/commit/c535d1344dd78f73b9c3bf2446f823980ffa951d

**Comment by afragen** [comment]
@calvintam236 can you test the latest update and let me know if the errors persist? Thanks

**Comment by afragen** [comment]
Now I really think it's fixed. Testing appreciated.

**Comment by calvintam236** [comment]
@afragen it seems working fine now on `develop` branch! thank you! :)

**Comment by afragen** [comment]
Thanks for the feedback. Glad we figured it out.
