### ISSUE TITLE
GHU uses site language instead of user language

### ISSUE THREAD

**Issue by pnoeric** [afragen/github-updater#573]
Hi Andy, I have a site that is in German, but as an admin user I keep the interface for myself in English (a setting under my user profile). Everything's in English except GHU. ;-)

![image](https://user-images.githubusercontent.com/447652/28268447-9a1eeb04-6afe-11e7-98fc-8b9ad9322177.png)

**Comment by afragen** [comment]
That’s very odd Eric. I know that the translation files for German will be present as the site locale is set for German. I don’t have any idea about how the new individual user admin preference works. Translation files are handled by WordPress core and are stored in the `wp-content/languages/plugins` folder just as if they were loaded from dot org.

**Comment by afragen** [comment]
I think I may see the reason and have a potential fix. I’ll report back here.

**Comment by afragen** [comment]
I think this might have something to do with fixing the issue. https://core.trac.wordpress.org/ticket/26511#comment:93 https://github.com/afragen/github-updater/blob/develop/src/GitHub_Updater/Language_Pack.php

The really curious part is all I do with languages inside of the plugin is to load language packs depending upon site locale. I don’t do anything regarding displaying translations. 

Is any other plugin whose translations are from dot org giving problems, like Akismet or Jetpack? You can check using Query Monitor where translation files are loaded from.

**Comment by afragen** [comment]
Is this a single site or multisite. I'm currently testing locally and setting the default site language to German and my user's language to English works on my end. This for both single and multisite, locally and on server.

I can't replicate.

![screenshot_01](https://user-images.githubusercontent.com/1296790/28493749-b322e936-6ed0-11e7-9eee-957b52d1becb.png)
![screenshot_02](https://user-images.githubusercontent.com/1296790/28493751-b5b3d7fa-6ed0-11e7-8678-e641e77fad71.png)
![screenshot_03](https://user-images.githubusercontent.com/1296790/28493752-b8742198-6ed0-11e7-8b68-7b30fe56bcee.png)

**Comment by afragen** [comment]
@pnoeric is there any further information you have? I can’t reproduce this.
