### ISSUE TITLE
Can no longer update theme

### ISSUE THREAD

**Issue by pnoeric** [afragen/github-updater#574]
The latest revision has broken my ability to update my theme. I think I figured out what's going on:

- My theme in github has 2 branches, 'master' and 'deploy'... ONLY deploy has a `style.css` file
- Previously this was no problem, I had `GitHub Branch: deploy` in the `style.css` header and all was well
- But now I'm using the latest GHU and since I originally installed the theme "by hand," it thinks the main branch is `master`
- But it can't find a `style.css` file on github under `master` (I see the 404 error in Query Monitor)
- So I can't switch to `deploy`!
- So I'm stuck.

For now I'm deleting the entire theme and manually installing it via GHU so I can install it from `deploy`... but this breaks all my other sites where I've already installed a theme (from `master`, originally, way back) and now just want it to always update from the deploy.

(And I can't keep a style.css file on the master branch... too many people work on this site and we get collisions in git all the time that are a pain to fix. It's much easier to let everyone work in `master`, compile their own SCSS locally but never commit `style.css`. When it's time to deploy, the `deploy` branch is built out properly.)

**Comment by afragen** [comment]
Yes, the new branch setting code takes the branch from the branch switch or install actions. Can you use the branch switching to reinstall the branch you want to update against. I do realize this new method is a breaking change for all branches but master.

I’m really confused about the statement above that _only deploy has a style.css file_. A theme requires a style.css file for the theme headers to make it a theme.

**Comment by pnoeric** [comment]
I think I can use the branch switching option? The problem is that all my themes in github have two branches: `master` which has no style.css file, and `deploy`, which does.

I think the problem I'm having now is that even when I turn on the option to choose a different branch, it appears to fail during the process of locating other branches because `master` doesn't have a style.css file. So I never get the option to switch to `deploy`.

**Comment by afragen** [comment]
I’m actually not sure how it ever worked without a style.css file. Can you add a style.css file with just the headers? GitHub Updater finds all the branches based upon the API. Can you grant me read access or create a read-only token so I can try locally?

**Comment by pnoeric** [comment]
Hmm weird. Let me try adding that style.css file now. I'm nervous about completely removing the theme (deleting it) and then reinstalling from GitHub-- I'm afraid I'll lose content entered in widgets and menus.

**Comment by pnoeric** [comment]
I have a style.css file in there now; it's the "stub" style.css file I use to keep things updated. It looks like this (sorry for all the redaction):

```
@charset "UTF-8";
/*
Theme Name: xxx-org
Description: xxx-org
GitHub Theme URI: https://github.com/switchplus/xxx-org
GitHub Branch: deploy
Author: switchplus
Version: 1.0.45
Text Domain: xxx-org
Domain Path: /languages
*/

```

The problem is, the GHU plugin thinks it's working with the `master` branch since that's where I originally installed it from (I probably just FTP'd it in place back then). When I try to use the branch switcher popup, it doesn't give me any choices, and I see that 404 error because it's trying to find a `style.css` file out there on the `master` branch at GitHub.

Soooo... I think I'm still stuck. Is there any way to trick GHU into working with the `deploy` branch for this site, now?

I could completely uninstall (delete) the theme, and then do a fresh install from GitHub (using the GHU Theme Install option, from `deploy` of course). The problem with that is I'm nervous about losing any data in widgets/menus that I've already entered... for example, when a theme's widget areas go away, does WP keep that info around, and then restore the data if that theme comes back online? Etc. I think you see my dilemma. This would be much easier if I could just get GHU to look at the `deploy` branch like it had been doing... hopefully there's a way to do that.

**Comment by pnoeric** [comment]
Hmm I could temporarily check in a `style.css` file to GH in the `master` branch. I'll try that for now.

**Comment by afragen** [comment]
Branch headers are no longer being utilized, they are ignored. In order to _set_ the branch, you must use the _branch switching_ to switch or reinstall a branch or you must _install_  using GHU Install.

The act of updating a repo does not create a new branch value that is saved in the options table.

Branches are discovered via the GitHub (or Bitbucket, etc) API as the cache refreshes. This is not new.
