### ISSUE TITLE
Occasional 502 errors

### ISSUE THREAD

**Issue by pnoeric** [afragen/github-updater#575]
I assume this is a GitHub issue, but FWIW I'm getting these a lot today when I update my theme--

![image](https://user-images.githubusercontent.com/447652/28269682-354f7f86-6b03-11e7-9546-a4f98d90b7d9.png)

No other errors, no issues in Query Monitor, and despite the errors everything _appears_ to be working with the update. Is there any further logging done by GHU, maybe we can dig deeper in to see what's going on when this happens?

**Comment by afragen** [comment]
Googling turn up this, https://www.odoo.com/forum/help-1/question/timeout-error-with-nginx-88687

Seems to be some sort of nginx timeout issue.
