### ISSUE TITLE
How can I hide my Bitbucket Credentials in the Admin

### ISSUE THREAD

**Issue by talymo** [afragen/github-updater#576]
I am planning on installing this on a client's Wordpress install and I do not want them having access to my Bitbucket account. I can simply right click the password input field in any web browser, click inspect and change the type of the input from password to text and it will display my password. This gives them complete access to my entire Bitbucket repository and that is not good for me.

There is no reason they would need to change this information so those fields are arbitrary.

I've tried searching through the Bitbucket_API.php file as well as the Settings.php file for where you are outputting this and I've found the input form for the initial creation, but not the form-table for the display.

Please advise.

**Comment by talymo** [comment]
Ok, I've found out how to hide the entire settings, but the problem with that is I need to hit refresh cache every time I push to the Github repo, and hiding the settings takes away my ability to do that. I haven't had a theme update come through without hitting the refresh cache button.

**Comment by afragen** [comment]
The cache can be anywhere between 6-18 hours per repo that changes with each cache expiration. You should only need to refresh the cache if you need something sooner.

If you do need something sooner you can look into using webhooks for an automatic update. Please see the wiki for more detailed instructions. LMK if you have questions.

**Comment by afragen** [comment]
Additionally, if you don’t want to rely on your client for updating you should be able to update using several of the remote management services, like iThemes Sync, MainWP, etc.
