### ISSUE TITLE
Missing BitBucket tab

### ISSUE THREAD

**Issue by grudda** [afragen/github-updater#578]
After installing Version 6.3.5 for the first time ever the BitBucket tab on settings page is missing.

![image](https://user-images.githubusercontent.com/18442458/28567159-b3b672f6-7131-11e7-98ea-a76bb379b188.png)

Wordpress Version: 4.7.3
PHP: 5.6

**Comment by afragen** [comment]
Can you share the headers for any Bitbucket sourced repo you have installed in that site?

**Comment by grudda** [comment]
Ah, I'm very sorry. I probably misunderstood the docs, because I expected this tab even before installed the very first plugin from BitBucket repo. Now everything is working with that. Sorry for bothering.

**Comment by afragen** [comment]
Not a problem.
