### ISSUE TITLE
question: update from github fork instead of wordpress

### ISSUE THREAD

**Issue by Hube2** [afragen/github-updater#579]
So I have this plugin forked from another plugin on github. The original plugin is in on WP. I have made some changes to my version of the plugin, but I also keep it updated with any changes made to the original plugin.

So here's my question. Is it possible to force the plugin to update from my own repo rather than from the original plugin on WP?

I probably already know the answer to this, I just want to confirm. 

I'm guessing that I'm going to have to create another repo here and alter the plugin name to make it update the way I want. Just want to check to see if there is another or any suggestions other than creating another repo that I need to keep up.

**Comment by afragen** [comment]
By default, any plugin that is both on the dot org repo and is on branch `master` will only be updated from dot org. If it is on a branch other than `master` updates will happen from the source and branch designated in the `GitHub Plugin URI` header.

Be aware a breaking change regarding branches is coming. The next update, currently in `develop` will ignore any `GitHub Branch` headers and set the branch from an _install_ or _branch switch_ action.

What you would need to do to ensure your fork is updating from your source would be to ensure it’s deploying from a branch other than `master` and when the next GHU version comes out, **set** the branch by using the _branch switch_ to re-install the specific non-master branch.

Did that make sense?

**Comment by Hube2** [comment]
Umm, not 100%, but I'm sure I'll figure it out when I dig into it. I'll probably wait till that change is made.

But thanks for letting me know that it's possible.  If I have any more questions I'll yell.

**Comment by afragen** [comment]
You can always hit me up on the group Slack, https://github-updater.herokuapp.com/ to join.
