### ISSUE TITLE
Unable to change theme branch

### ISSUE THREAD

**Issue by yaronguez** [afragen/github-updater#582]
Hi there, one of our themes is stuck on the master branch. I tried clicking "select another branch" and then choosing the correct branch from a dropdown menu but there's no save button and nothing happens on select.

**Comment by yaronguez** [comment]
I inspected the selector code and saw a JavaScript onchange event looking to modify the ahref attribute of a non-existent anchor element. I manually navigated to the link it was trying to set and was able to change the branch. Issue still remains without this work around. Also, no values were set on any of the drop down elements.

**Comment by afragen** [comment]
If you switch to the `develop` branch of GitHub Updater this issue should be fixed.

**Comment by yaronguez** [comment]
I actually had tried to switch to the develop branch but, after doing so, the plugin deactivated itself. All of my attempts to re-activate it didn't work. The page would reload but the plugin would remain inactive. I finally had to reinstall the 7.0.0 release to get the plugin working again but still without the branch select.

**Comment by afragen** [comment]
The fix for this particular issue is currently in the develop branch. I don’t understand why it wouldn’t reactivate but try moving away from the plugins page and/or reloading the page.

**Comment by afragen** [comment]
You need to make sure the directory in wp-content/plug-ins is named correctly for the branch naming to work.

**Comment by afragen** [comment]
I just updated to v7.1.0 which contains this fix.

**Comment by yaronguez** [comment]
Thanks, Andy!
