### ISSUE TITLE
Performance: should plugin run outside admin panel

### ISSUE THREAD

**Issue by giedrius** [afragen/github-updater#583]
Hi. I have noticed that github-updater slows my site somewhat (0.15 seconds or like 1/3-1/2 of total, majority of time not db queries) while outside wp-admin. While I can solve it with caching, I wonder if it would be possible to check for updates of repos from wp-cron or for users in wp-admin only implemented? At least as optional setting.
<img width="520" alt="screenshot 2017-08-10 18 32 58" src="https://user-images.githubusercontent.com/65549/29178554-91c3d0be-7dfa-11e7-8787-2a18a80e6d00.png">
Here profiling with/without with wp-cli. The generation times with query monitor show time difference as well.

**Comment by afragen** [comment]
GHU is not active outside of specific pages on wp-admin, except if one of the Remote Management options is selected. If one of these options is selected then GHU is also active on index.php. 

I'm not sure where you are pointing to as evidence of GHU as the culprit. I cache everything already and certainly any server level caching only helps. 

GHU loads on init not plugins_loaded. 

GHU caches individual repository data randomly between 6-18 hours. This so everything doesn't expire at once.

**Comment by giedrius** [comment]
I debugged a bit further with wp-cli/wp-profile .There first slowing down was caused by cycling through plugins and checking their filedata on the outside site: 
<img width="1898" alt="screenshot 2017-08-14 11 00 01" src="https://user-images.githubusercontent.com/65549/29263141-4ad041e0-80e0-11e7-9702-4cc27f42e1fe.png">
The second was caused by some sort of request that failed in my debugging case and not listed under wp-requests, but request library was loaded and some request was tried. 
All remote management options are off, and there is measurable change between leaving github updater on and off both in wp-cli and in normal uncached site visit.

**Comment by afragen** [comment]
Can you provide the commands you are running?

How many plugins/themes do you have being checked with GHU?

**Comment by giedrius** [comment]
I believe 1 plugin and one theme. I might guess that it loops through all
plugins and checks their files, not only github-hosted.
This output is from debug with wp-cli, using wp-profile  (
https://github.com/wp-cli/profile-command ).

wp profile hook plugins_loaded:before --url=http://<yoururl.com>
 (debugable from php<7 only due to wp-cli or php limitations),

wp profile stage --all --url=http://<yoururl.com>  other cases, provides
less info.

running from wordpress install dir.

**Comment by afragen** [comment]
Thanks, I’ll test locally and see what I find. GHU does cycle through all plugins and themes but only runs when it finds an appropriate header. I only hook into init, not plugins_loaded.

**Comment by giedrius** [comment]
This code was executed before plugin_loaded, not during. As far as I
understand, it all part of overall init. Overall, launching plugin-check
from wp-cron (which is loaded separately and does not slow showing content
to user) might work better from end-user perspective, like it is done for
wordpress -hosted plugins.

**Comment by giedrius** [comment]
That is, the naming of stages in wp-cli might mis-match with ones used in
wordpress docs.

**Comment by afragen** [comment]
Launching plugin check from wp-cron is not a simple undertaking. Each plugin/theme not hosted on dot org must be checked up to 6 times for different pieces of data. Once checked that data is cached until the timeout expires.

GitHub Updater is a complex plugin. When I look at load times using Query Monitor there doesn't seem to be the same impact as under `wp profile`.

If you can figure out how to group all the `wp_remote_get()` calls for a specific repo into a wp-cron job I would happily help test a PR.

**Comment by afragen** [comment]
Also, GHU only loads on specific pages checking against $pagenow. As `wp profile` doesn't actually load pages I'm not exactly certain when GitHub Updater loads. Additionally, GitHub Updater only loads for privileged users.

**Comment by giedrius** [comment]
Sure, wp-cli loads everything slower and has some additional code that
works differently as far as I know.
You can pass --url= parameter the 'desired' page to load.  Anyway, I see
load time difference with query monitor as well with plugins and without
even with non-logged in user for main blog page.

Giedrius

**Comment by afragen** [comment]
When not under wp-cli GitHub Updater only loads for admin level users and only in plugin page, theme page, GHU Settings, and core update page. 

Non-admin users will not see and impact on the site at all.
