### ISSUE TITLE
PHP Notices during theme update

### ISSUE THREAD

**Issue by calvintam236** [afragen/github-updater#584]
```
Notice: Undefined property: stdClass::$extended_repo in /wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 733
```
Verson: v7.1.0

**Comment by afragen** [comment]
Eventually this will go away with the rest if the extended naming stuff. I hate to add more code I'm just going to remove later but let me see if I can find an easy fix.

**Comment by afragen** [comment]
Should be fixed with https://github.com/afragen/github-updater/commit/4c2f236d53b1a3fcfcb365f828a2efe9587e1265
