### ISSUE TITLE
No longer seeing theme updates with 7.1.0

### ISSUE THREAD

**Issue by PthPndr** [afragen/github-updater#585]
I updated to 7.1.0 from 6.3.5 for the "Dot Org Override". But with it enabled, I'm not seeing any theme updates available. If I disable the override, the theme updates return. The plugins appear to be fine.

My plugins and themes are located in BitBucket private repos.

**Comment by afragen** [comment]
Are you themes also in the dot org repo? Have you tried refreshing the cache?

**Comment by PthPndr** [comment]
Yes, I tried refreshing the cache (multiple times).  And no, my themes are not in the dot org repo (just a couple of the plugins are)

**Comment by afragen** [comment]
Please test latest `develop` branch and let me know if this is fixed. Thanks.

**Comment by PthPndr** [comment]
Yes, that looks like it fixed it. Thanks.
