### ISSUE TITLE
Bitbucket Private Repo Themes + Active Theme Issue

### ISSUE THREAD

**Issue by bradmkjr** [afragen/github-updater#586]
I apologize for not providing more details, but have just lost multiple hours to this issue and want to just document it and get back to work.

If you delete the folder via FTP for the active WP theme, then attempt to install that theme using the GHU plugin, specifically I was trying to install a private Bitbucket Repo, it will never appear in the list of installed bitbucket themes on the GHU bitbucket tab (very likely the bitbucket tab itself will never appear).

Once I switched to a different theme, and installed the private repo theme worked fine.

**Comment by afragen** [comment]
It may be an issue with not having an active theme. Completely removing the active theme will usually result in a default theme being activated if it is available. You should've been able to reinstall the active theme using  the branch switching to the current branch. 

I realize this is in the backend of the site but WP still needs to know what the active theme is. 

Sorry for your time loss. If there's anything else please let me know.

**Comment by bradmkjr** [comment]
After a very long debugging session, I have discovered it is directly related to wp_get_themes() being called by a hosting installed mu-plugin, prior to GHU being able to hook into the action to add extra headers, so the Bitbucket Theme URI header is missing and therefor not shown on the bitbucket tab.

Recommend fix in process, need to take a short break and clear my head.

**Comment by afragen** [comment]
Thanks for all your efforts. Maybe playing with the filter priority for `add_headers` will help.

**Comment by afragen** [comment]
This is next on my list Brad.

**Comment by afragen** [comment]
I think this should fix it. https://github.com/afragen/github-updater/commit/31ed7061d8667263f010877cb5554b7ea752f3af It seems to work locally for me.

LMK if it solves your issue.

**Comment by afragen** [comment]
This should be fixed in latest develop branch in v7.3.0. Please reopen this issue if not.
