### ISSUE TITLE
Can no longer "View Details" for plugins

### ISSUE THREAD

**Issue by PthPndr** [afragen/github-updater#589]
Starting with version 7.0.0, I can no longer click the "View Details" or "View Update Details". It will only display the Description and none of the other tabs or changelog.

All my plugins are BitBucket private repo plugins.

**Comment by afragen** [comment]
It pulls this info from the readme.txt and CHANGES.md files. Do you have these files?

**Comment by PthPndr** [comment]
I've only used/had a readme.txt. Up to and including 6.3.5 it looked like this:
[https://farm5.staticflickr.com/4430/35844500603_bbe8060c76_b.jpg](url)

Now with 7.0 and above I get this:
[https://farm5.staticflickr.com/4342/35844500723_7caff0b82c_b.jpg](url)

**Comment by afragen** [comment]
Let me take a look at this over the weekend. It would really help if I could use he same plugin you are having issues with.

**Comment by PthPndr** [comment]
Sure, no problem. I added you to the repository. Let me know if you have any problems.
https://bitbucket.org/mystudioengine/mse-test-plugin

**Comment by afragen** [comment]
Thanks Robert. I’ll figure it out and have fixes forthcoming.

**Comment by afragen** [comment]
I think this should fix everything. https://github.com/afragen/github-updater/commit/ecadf6d2903ca0ff30ce4c827d068d936736b327

I bumped the `develop` branch.

**Comment by PthPndr** [comment]
Thanks Andy, it looks good.
