### ISSUE TITLE
Bitbucket private repos

### ISSUE THREAD

**Issue by afragen** [afragen/github-updater#59]
@jazzsequence I think I've finally gotten this figured out. Please test latest `develop` branch.

**Comment by abrudtkuhl** [comment]
I was able to add a private Bitbucket repo owned by our organization. However when I push an update to Bitbucket and go to check the plugin - it never sees the updated version is available.

Another issue (and probably should be opened as another issue) is that it is not remembering I selected "private repository" on installation. I am having to go back in and re-check that after the authentication fails when re-loading the plugin page. 

I am running version 4.2.0

**Comment by afragen** [comment]
Remote installation and updating occur through different mechanisms. The Settings page must be updated after a remote install of a private repo.

Did that solve your issue?

**Comment by abrudtkuhl** [comment]
no not solved. The main issue im having is that when i update a plugin, i
dont see the update available in the plugins page on WP.

i just thought it was weird i had to check "private repository" twice when
the second one should know i've already checked the first one.

Andy Brudtkuhl
@abrudtkuhl <http://twitter.com/abrudtkuhl>

**Comment by afragen** [comment]
> no not solved. The main issue im having is that when i update a plugin, i
> dont see the update available in the plugins page on WP.

Is your Settings page correct?

> i just thought it was weird i had to check "private repository" twice when
> the second one should know i've already checked the first one.

The issue is that the private repo won't be listed in the Settings page until it is installed. There's no place to put the setting for a private repo because it didn't exist prior to installing the app.

I'll consider it a feature request. Maybe I can figure something out.

**Comment by afragen** [comment]
>> i just thought it was weird i had to check "private repository" twice when
> >the second one should know i've already checked the first one.

> The issue is that the private repo won't be listed in the Settings page until it is installed. There's no place to put the setting for a private repo because it didn't exist prior to installing the app.
> 
> I'll consider it a feature request. Maybe I can figure something out.

https://github.com/afragen/github-updater/commit/86ac601ea24bf8cc037a9dee22b283adba119b60

**Comment by afragen** [comment]
> no not solved. The main issue im having is that when i update a plugin, i
> dont see the update available in the plugins page on WP.

You might have to clear the transients by clicking `Check Again` on the `update-core.php` page.
