### ISSUE TITLE
PHP Notice in debug mode.

### ISSUE THREAD

**Issue by asumranphan** [afragen/github-updater#591]
Notice: Undefined index: branch_switch in .../plugins/github-updater-develop/src/GitHub_Updater/Theme.php on line 521

**Comment by afragen** [comment]
If you save any settings does it persist?

**Comment by picasso** [comment]
I have the same PHP Notice.

```Undefined index: branch_switch
wp-content/plugins/github-updater/src/GitHub_Updater/Theme.php:520
```
Call Stack
```
Fragen\GitHub_Updater\Theme->single_install_switcher()
          wp-content/plugins/github-updater/src/GitHub_Updater/Theme.php:434
Fragen\GitHub_Updater\Theme->customize_theme_update_html()
          Unknown location
apply_filters('wp_prepare_themes_for_js')
          wp-admin/includes/theme.php:623
wp_prepare_themes_for_js()
          wp-admin/themes.php:123
```

this only happens on page Appearance > Themes and **ONLY** if `Enable Branch Switching` is switched off.

**Comment by afragen** [comment]
Does this occur in the develop branches?

**Comment by picasso** [comment]
yes, the same notice in the develop branch as well

**Comment by afragen** [comment]
I’ll take a look at it today. Stay tuned.

**Comment by afragen** [comment]
I just pushed a commit to develop. Can you test and see if there are any other notices?

**Comment by picasso** [comment]
tested. Now there are no notices. Thanks!

**Comment by afragen** [comment]
I should be tagging this soon. Just waiting for confirmation on a couple other but fixes.

**Comment by picasso** [comment]
on page `Appearance > Themes` I see again: **Undefined index: branch_switch**

call stack:
```
wp_prepare_themes_for_js()
   wp-admin/themes.php:123
apply_filters('wp_prepare_themes_for_js')
   wp-admin/includes/theme.php:623
Fragen\GitHub_Updater\Theme->customize_theme_update_html()
   Unknown location
Fragen\GitHub_Updater\Theme->single_install_switcher()
   wp-content/plugins/github-updater/src/GitHub_Updater/Theme.php:456
```

**Comment by afragen** [comment]
@picasso update to latest `develop` branch and let me know if this persists.

**Comment by afragen** [comment]
Closing again as I think this is fixed in develop.
