### ISSUE TITLE
filter files and folders from GitHub

### ISSUE THREAD

**Issue by picasso** [afragen/github-updater#593]
Thanks for wonderful plugin!

I did not find an answer in the Wiki and therefore decided to write here.
Is there a way (filter? hook?) to filter the files and folders that will be installed during the update?
What if I do not want some folders to be installed on the client's server? But I need them for development and I cannot just exclude them through .gitignore.

**Comment by afragen** [comment]
You need a .gitattributes file. Look at the one in this repo as an example.

**Comment by picasso** [comment]
Thanks!
