### ISSUE TITLE
Fatal error using PHP 5.4 (Centos 7)

### ISSUE THREAD

**Issue by galaxiusmons** [afragen/github-updater#596]
Getting the following error:

PHP Fatal error:  Can't use method return value in write context in /wp-content/plugins/github-updater/src/GitHub_Updater/Basic_Auth_Loader.php on line 283

I think the issue is that empty() cannot accept a function as input in php 5.4.

Aaron

**Comment by afragen** [comment]
Sorry Aaron. I've fixed this. 

There will come a time when I move the PHP requirements up to PHP 7.0 so start looking in that direction.
