### ISSUE TITLE
GitLab is missing

### ISSUE THREAD

**Issue by marbetschar** [afragen/github-updater#597]
GitHub Updater does not show the settings tab for GitLab as in previous versions. If it's conditionally hidden, then it seems to ignore the fact we have a theme installed which relies on GitLab updates.

See screenshot of our admin view for GitHub Updater v7.2.0

<img width="840" alt="bildschirmfoto 2017-09-06 um 17 26 54" src="https://user-images.githubusercontent.com/392542/30120336-d1e92ca0-9328-11e7-9b92-4295d939b0a3.png">

**Comment by afragen** [comment]
Can you try switching to the `develop` branch to see if this issue persists. I think it's related to #580 and #586

**Comment by afragen** [comment]
Can you share URL for GitLab repo or post theme's headers?

**Comment by marbetschar** [comment]
Theme Header:

/*
Theme Name: MANDELKIND
Description: A <a href='http://codex.wordpress.org/Child_Themes'>Child Theme</a> for the Enfold Wordpress Theme. If you plan to do a lot of file modifications we recommend to use this Theme instead of the original Theme. Updating wil be much easier then.
Version: 0.5.13
Author: MANDELKIND
Author URI: http://mandelkind.swiss
Template: enfold
GitLab Theme URI: https://gitlab.com/mandelkind/enfold-mandelkind
*/

**Comment by marbetschar** [comment]
I can also provide you an admin access to the instance if needed to debug the issue; via pm in the GitHub Updater Slack. Just ping me there.

**Comment by afragen** [comment]
Everything looks OK. If you deactivate the theme does the issue persist?

Can you share list of plugins active?

**Comment by afragen** [comment]
I only need read access, thanks.

**Comment by afragen** [comment]
Offline, we have been unable to find any consistent bug. This seems to work both locally and on other installs. Closing unless there becomes something more specific.
