### ISSUE TITLE
When theme is not from 'master'

### ISSUE THREAD

**Issue by picasso** [afragen/github-updater#598]
There are several issues related to the theme if it was installed not from the 'master' branch

- installed a new theme from **non** 'master' branch via GitHub-Updater (from private repo). So far - ok.
- on GitHub branch (call it `develop`) the theme was updated to a higher version
- there is no sign of update in themes in wordpress (tried several times to refresh cache)

... ok, I see reason now... in details I see that : `Current branch is master`... But I have not switched the branch!

- now I try to switch it back to `develop`... and get the following: `The theme is at the latest version.`
It's not true. `master` is 1.1.4 and develop is 1.1.5

**Comment by afragen** [comment]
This was a _breaking_ change from v7.0.0. Branch headers are no longer needed and not used. You will need to use the branch switcher to _reinstall_ the non-master branch so that the option can be set and the branch switch row will correctly identify the current branch.

Please make sure you're using the GHU develop branch as there's a bug fix for the _The theme is at the lastest version._ issue.

**Comment by afragen** [comment]
If you installed using the GHU's remote install, the specified branch should be set automatically as of v7.0.0

**Comment by picasso** [comment]
I cannot reinstall with the branch switcher - when I try I got the same message `The theme is at the latest version.`
I'm using the `develop` branch of GHU.

I installed with the tab `GitHub Updater Install Theme`... not sure if it's remote install or not...

**Comment by afragen** [comment]
Installing from inside GHU is a remote install. What's the URL of the theme so I can test. Also, I've just pushed a commit for a problem I found with accidentally deleting the current branch.

**Comment by picasso** [comment]
sent with email.

**Comment by picasso** [comment]
I have some tests and found the following:

1. if the current theme is 'Twenty Seventeen', then I can  switch branch for my theme (inactive) without problems. Everything works.

2. If my theme is active then nothing works. When I try to switch branch I get `The theme is at the latest version.`

Maybe it helps...

**Comment by afragen** [comment]
I’ll take a look at it this weekend. I should have time.

**Comment by afragen** [comment]
@picasso I think I've gotten this fixed in https://github.com/afragen/github-updater/commit/f0c1c258233ec031ee42511f5bbe974b4286b9d2

Please test and let me know.

**Comment by picasso** [comment]
Thanks Andy!
now works as expected.
