### ISSUE TITLE
Theme updates fail and very old theme is installed instead

### ISSUE THREAD

**Issue by joshsmith01** [afragen/github-updater#599]
The last few updates to the theme have returned a 502 error. The theme has not been updated, but the original theme in the GitHub Repo will now be in its place. If I want to update, I end up having to scramble to actually reinstall the theme completely, not just update it.

Originally, the theme was named Dice.org. Now the theme name is Dicenews2015. I've kept the changes in the same repo, but only the name of the theme has changed.

I've installed and updated this theme many times in the last few months via GHU. I've also installed and updated plugins for this site and others as well as installed and updated themes for other sites. This is the first issue I've encountered. 

I'm on WP Engine, but I'm not sure where the breakdown is happening; WP Engine or GHU. 

Possibly related, but I don't see version details anymore when I push updates. 

Can anyone guide me on what's happening and where?

![manage_themes_ _dice_insights_ _wordpress](https://user-images.githubusercontent.com/1550745/30188087-794fb94c-93e1-11e7-9ac8-f06e93d6ce8f.png)

**Comment by afragen** [comment]
I've been getting cc'd on the WPE ticket, thanks.
That error seems to be related to nginx. Can you try using the latest develop branch of GHU and see if it persists? Also, what error, if any, do you see if trying to update from the update-core.php page?

**Comment by afragen** [comment]
Josh,
GHU will only _see_ the plugin in the header URI. I gets no info from a .git folder.

**Comment by afragen** [comment]
I think I may know what’s going on. WP installs a theme to a folder based upon it’s directory name. GHU translates this a the repo name. You described above that you changed the theme’s name. What is the theme’s URI?

**Comment by joshsmith01** [comment]
I changed the name of the repo and the name of the theme months ago. I have been using this repo in this configuration for a few months with several updates. 

I created a new repo named dicenews2015 and renamed the old repo to dicenews2015-old. I reinstalled the theme from the new repo. I've also successfully updated with the new repo where the old repo failed. I, too, think this is a renaming issue, but I think somehow GHU was reaching deeper into the repo history and finding somewhere that names of theme and repo didn't match. 

Repo name:
https://github.com/DiceHoldingsInc/dicenews2015
Theme name:
dicenews2015

Theme header in style.css:
`/**
* Theme Name: Dicenews 2015
* Theme URI: https://confluence.dice.com/display/WP/dicenews2015
* Author: Josh Smith
* Author URI: http://www.efficiencyofmovement.com
* Version: 1.0.24
* Description: Base theme for WordPress
* License: GNU General Public License v2 or later
* License URI: http://www.gnu.org/licenses/gpl-2.0.html
* Text Domain: dicenews2015
* Domain Path: /languages
* Tags: News, publish
* GitHub Theme URI: https://github.com/DiceHoldingsInc/dicenews2015
*/`

**Comment by afragen** [comment]
There's no way for GHU to did deeper than the URI provided. The most likely culprit is from GitHub's redirects with the name change. 

If all works now with the new repo let me know. 

I was able to install, switch branches, update, and install the `safari` branch directly.

**Comment by afragen** [comment]
GHU can only check the URI provided. I think the issue came about from renaming the repo and GitHub's redirects.

**Comment by joshsmith01** [comment]
Ah. Yes, all is well now.
