### ISSUE TITLE
Gitlab implementation

### ISSUE THREAD

**Issue by aristath** [afragen/github-updater#60]
[Gitlab](http://gitlab.org/) is the most widespread open-source alternative to github and it can be self-hosted.
Integrating Gutlab support for both private and open repositories would mean that we'll be able to use our own servers for updates instead of relying to 3rd party services.

Gitlab has a pretty open API http://api.gitlab.org/repositories.html and it tries to emulate the way github works in many ways.

If you install gitlab to use on your own organization you'll see that in many ways it is better and more versatile than github, so it only makes sense to use it for our private repos (hosting gitlab on a VPS is way cheaper than a github premium account).

**Comment by afragen** [comment]
Branch `gitlab` is starting point for integration.

**Comment by tubiz** [comment]
@afragen thanks for creating the gitlab branch. 
Have started working on the gitlab integration

**Comment by afragen** [comment]
Hey everyone! GitLab integration is now in the `develop` branch. If you want to test, just use the branch switcher. :+1: 

It should also work with self-hosted GitLab by adding a `GitLab Enterprise` header to those plugins/themes hosted there.

**Comment by lmartins** [comment]
Cool. Is it supposed to work with private Gitlab repos at this point.
Asking because i've tried and got "Download failed. Unauthorized" Not sure if because my repos server or the plugin.

**Comment by afragen** [comment]
@lmartins you must have a GitLab private token in the settings. It seems all interaction via the GitLab API needs to be authenticated.

**Comment by lmartins** [comment]
@afragen Im on the develop branch but the settings don't have any input for the Gitlab credentials.

**Comment by afragen** [comment]
Do you have any GitLab hosted plugin's installed? 

The setting is not displayed unless there are any. Installing GitLab repos doesn't require a private token, but updating does.

**Comment by lmartins** [comment]
Not sure im following, should I put the complete URL into the "Plugin URI" field?
I mean since this is a private Gitlab install Im guessing this is the only way to tell the plugin where to look at.

Still, when I insert `http://git.multiweb.pt/multiweb/social-icons-widget` into that field, I get as response:

```
Downloading install package from https://gitlab.com/multiweb/social-icons-widget/repository/archive.zip?ref=master…

Download failed. Unauthorized
```
The plugin seems to be translating the URL to something under the gitlab.com domain, which isn't the case here.

**Comment by afragen** [comment]
Darn I thought I had this worked out. Can you make sure you're on the latest develop by using the branch switch feature and reinstalling the develop branch. After doing this please try again and let me know.

**Comment by afragen** [comment]
Sorry, I thought I put this in. I forgot. I'll have it fixed later tonight as I'm on the road right now.

**Comment by lmartins** [comment]
No stress Andy, and many thanks for all the help.

**Comment by afragen** [comment]
Try now. I tried to test using the URI above but kept getting timeout errors.

**Comment by lmartins** [comment]
Hi Andy, the timeouts you're getting are normal, this server doesn't accept external connections.
I've tried again and I can now install plugins. Once I do that, im now getting two error messages:
```
Social Icons (Webipack) was not checked. GitHub Updater Error Code: 401	
There is probably an error on the GitHub Updater Settings page.
```
and
```
You must set a GitLab Private Token.
```
Saving the private token in the plugin settings seems to make no difference.

**Comment by afragen** [comment]
If you go to the settings page you should see a space for setting the GitLab Enterprise Private Token. You will need to fill that in.

**Comment by lmartins** [comment]
I should have been clearer about that, those error messages persist after I fill that field with my account token.

**Comment by afragen** [comment]
The error is an authentication error. Can you post a screenshot of the settings page with blurred out tokens?

**Comment by afragen** [comment]
Unfortunately I don't have access to a GitLab Enterprise installation. It makes debugging difficult. 

If anyone can give me an account to test with that would be great.

**Comment by lmartins** [comment]
Heres the screenshot:
http://snpy.link/p2M39V

**Comment by afragen** [comment]
Can you show the headers for the plugin? It should have the `GitLab Enterprise` header that has the base URI for your git server. In this case, `GitLab Enterprise: http://git.multiweb.pt`

If this header is missing you won't see the setting to put in your GitLab Enterprise Private Token.

**Comment by lmartins** [comment]
This is what I have on the plugin headers:
```
Gitlab Plugin URI: http://git.multiweb.pt/multiweb/social-icons-widget
Gitlab Branch:     master
```
Github Updater it is indeed asking for the private token, as you can see on the screenshot: http://snpy.link/p2M39V

But upon save that setting the error notification stays present.

**Comment by franceimage** [comment]
Could the problem be similar to issue #232 ?

**Comment by lmartins** [comment]
Not really sure, although id doesn't sound like that.

**Comment by afragen** [comment]
@lmartins that's not the correct private token for a GitLab Enterprise hosted plugin/theme. 

If the plugin/theme doesn't have the `GitLab Enterprise` header you won't see that setting section. 

Can you post your plugin headers here for confirmation?

**Comment by afragen** [comment]
The following headers:
```
GitLab Plugin URI: https://gitlab.com/afragen/test-gitlab-plugin2/
GitLab Branch:     master
GitLab Enterprise: http://gitlab.example.com
```
makes this show up in the Settings.

![modified](https://cloud.githubusercontent.com/assets/1296790/7541331/68b9d8ce-f569-11e4-8b19-f0b80680cbbd.png)

**Comment by lmartins** [comment]
Ouch, I missed that info and seeing the field "GitLab Private Token" I though that was it. Was unaware of the another value for Enterprise. 

I don't think that what I have is an Enterprise service. We have a CE edition Gitlab self hosted which I believe is a bit different. I'll try get it working and let you know what I find.

**Comment by afragen** [comment]
I think the Enterprise refers to self hosted.

**Comment by afragen** [comment]
Because of this confusion I've decide to rename the header. For self-hosted git servers the header will end in `Self-Hosted` so @lmartins the header you should add is
`GitLab Self-Hosted: http://git.multiweb.pt`

**Comment by lmartins** [comment]
Not really, the enterprise is the paid version of their service:
https://about.gitlab.com/features/

**Comment by afragen** [comment]
Is the base URI for GtiLab Enterprise different than `https://gitlab.com` ?

**Comment by lmartins** [comment]
To anyone using a self-hosted Gitlab CE and Github Updater, have you managed to find the "GitLab CE or GitLab Enterprise Private Token" info?

Github updater asks for two values, "GitLab Private Token" (which is available in the user account) and the one I mention above that I can't find anywhere.

**Comment by afragen** [comment]
@lmartins are you referring to the setting in GHU or a private token listed in GitLab CE/Enterprise?

**Comment by afragen** [comment]
Did you add `GitLab Self-Hosted: http://git.multiweb.pt` header to your plugin?

**Comment by afragen** [comment]
Is it more or less confusing to use the header `GitLab Enterprise` or `GitLab Self-Hosted` for both GitLab CE and GitLab Enterprise?

**Comment by lmartins** [comment]
@afragen 
Im referring to the second of the two inputs after GHU installs a plugin from Gitlab. 
The plugin has now the header as you mention, removed and reinstalled just to be sure.

Regarding the last question, I thing self-hosted would be adequate to both version CE and Enterprise. Im just wondering if there's really two tokens for the Gitlab's CE, as I've failed to find one on our install. That was the confirmation I was looking for. 

Also considering that the user token gives him rights to use Gitlab's API, im not sure what would be the use of the "generic" token, but this is just me trying to understand what im failing to grasp.

**Comment by afragen** [comment]
The first token is for GitLab.com. The second token would be for any self-hosted GitLab.

**Comment by afragen** [comment]
If you aren't using a plugin from GitLab.com then you shouldn't get an error asking for that token. If I can figure out a way to hide it I will as that should avoid confusion.

**Comment by afragen** [comment]
I've also been thinking about it and perhaps using the term Enterprise might be better. 2 of the self hosted solutions use this term, GitLab CE being the third.

**Comment by afragen** [comment]
OK, accepted headers are `GitLab CE` and `GitLab Enterprise`. The Settings are more explicit and report a **GitLab.com** Private Token or a **GitLab CE** or **GitLab Enterprise** Private Token.

Please test and let me know how it works. Thanks.

**Comment by afragen** [comment]
I've deleted a number of my posts here that referred to different headers so as to not be confusing.

**Comment by afragen** [comment]
Closing as this should now be feature-complete and in `develop`.
