### ISSUE TITLE
Not clear on what I need to do for Wordpress updates for github plugins

### ISSUE THREAD

**Issue by jamminjames** [afragen/github-updater#600]
I have the Contact Form DB plugin on a Wordpress site which requires this Github Updater to stay updated. I installed this Updater on the site, seems to be working fine. However, I'm not sure if I need to do more. The Wiki is kind of confusing on this.

In the Github plugin, it lists the Contact Form DB as one of the "Installed Plugins and Themes", so does that mean it'll take care of updates without further action on my part?

I also created a GitHub.com Access Token and put it in the appropriate spot in the plugin, although I was unclear if I really needed that or not, and how I should configure it. I just left all the Scopes blank -- should I check any of those boxes?

Thanks for any help.

**Comment by afragen** [comment]
James, you're done. Any updates to either the GitHub Updater plugin or any plugins or themes that utilize GitHub Updater will be seen by you in your dashboard. When they show up just update as usual.

I think the Access Token is configured correctly. All it really needs is public read access, which I believe is the default.

BTW, you should see an update to this plugin show up by tomorrow. 😉

**Comment by jamminjames** [comment]
Great! Thanks! I think Wiki should be updated with something that tells people in my situation that this simple setup is all we need.

**Comment by afragen** [comment]
I'll see about adding something for those just looking to use GHU's functionality.

**Comment by afragen** [comment]
How’s this? Feel free to edit. https://github.com/afragen/github-updater/wiki/General-Usage

**Comment by jamminjames** [comment]
Does this line have to be added to your wp-config.php file as well? I added it:
`define( 'GITHUB_UPDATER_OVERRIDE_DOT_ORG', true );`

**Comment by afragen** [comment]
That option is only for the unusual circumstances. Personally I don't use it. It's for edge cases.

**Comment by jamminjames** [comment]
It seems like it's for the case where the plugin updates are also available via the normal WP updates, correct? So, you'd only need it if updates are also available in two places, via Wordpress' regular update system AND on github? Since it's right there in the Wordpress Github Updater plugin when you activate it, it looks like it's telling you you should do it -- so maybe that should be clarified as well.

**Comment by afragen** [comment]
If the plugin is on both dot org and on GitHub and using GHU, updates will be preferentially from dot org unless a branch other than master is running.

The use case is if there is a plugin on dot org that has the same slug but is a different plugin.

**Comment by jamminjames** [comment]
Ok, thanks a lot for all your help!
