### ISSUE TITLE
Errors after update to latest version (20170919)

### ISSUE THREAD

**Issue by fwolfst** [afragen/github-updater#602]
Hi there
On my staging environment which sits in a local only domain (assume it is http://stage.mydomain.org.8l -> probably important, the TLD of "8L"), an update of github updater leads to unusable backend with "error" messages like 

```
Warning: Missing argument 1 for Fragen\GitHub_Updater\API::api(), called in /var/www/wordpress/stage.mydomain.org/wp-content/plugins/github-updater/src/GitHub_Updater/Branch.php on line 43 and defined in /var/www/wordpress/stage.mydomain.org/wp-content/plugins/github-updater/src/GitHub_Updater/API.php on line 134
Notice: Undefined property: Fragen\GitHub_Updater\Branch::$type in /var/www/wordpress/stage.mydomain.org/wp-content/plugins/github-updater/src/GitHub_Updater/API.php on line 93 Notice: Trying to get property of non-object in /var/www/wordpress/stage.mydomain.org/wp-content/plugins/github-updater/src/GitHub_Updater/API.php on line 93
Notice: Undefined offset: 1 in /var/www/wordpress/stage.mydomain.org/wp-content/plugins/github-updater/src/GitHub_Updater/API.php on line 95
Notice: Undefined variable: url in /var/www/wordpress/stage.mydomain.org/wp-content/plugins/github-updater/src/GitHub_Updater/API.php on line 139
Notice: Undefined property: Fragen\GitHub_Updater\Branch::$type in /var/www/wordpress/stage.mydomain.org/wp-content/plugins/github-updater/src/GitHub_Updater/API.php on line 93 Notice: Trying to get property of non-object in /var/www/wordpress/stage.mydomain.org/wp-content/plugins/github-updater/src/GitHub_Updater/API.php on line 93 Notice: Undefined offset: 1 in /var/www/wordpress/stage.mydomain.org/wp-content/plugins/github-updater/src/GitHub_Updater/API.php on line 95
Notice: Undefined property: Fragen\GitHub_Updater\Branch::$type in /var/www/wordpress/stage.mydomain.org/wp-content/plugins/github-updater/src/GitHub_Updater/API.php on line 191
Notice: Trying to get property of non-object in /var/www/wordpress/stage.mydomain.org/wp-content/plugins/github-updater/src/GitHub_Updater/API.php on line 191
Notice: Undefined property: Fragen\GitHub_Updater\Branch::$type in /var/www/wordpress/stage.mydomain.org/wp-content/plugins/github-updater/src/GitHub_Updater/API.php on line 192
...
```

And the rendered message:
`
 GitHub Updater Fehlercode: A valid URL was not provided. 
`
("Fehlercode" is German for error code/return status). I mentioned to TLD of "8L" because I remember that I had problems with it once in a different project which did heavy URL checking and the error message sounds a bit as if this might be the problem.

Can you give me any pointers? Can I help debugging? Thanks (and thanks to myself that I have a staging environment ... :) )

**Comment by fwolfst** [comment]
btw this was an update of WP itself to latest version + update of a handful of plugins.

**Comment by afragen** [comment]
Is this a local staging environment? I’m not aware that `8L` is a TLD and may not work. All the code checking URL validation would be in WP core.

**Comment by afragen** [comment]
Can you post the plugin’s headers?

**Comment by fwolfst** [comment]
Yes, its a local staging environment.
With plugin headers you meant this, I guess:
'''
<?php
/**
 * GitHub Updater
 *
 * @package   GitHub_Updater
 * @author    Andy Fragen
 * @license   GPL-2.0+
 * @link      https://github.com/afragen/github-updater
 */

/**
 * Plugin Name:       GitHub Updater
 * Plugin URI:        https://github.com/afragen/github-updater
 * Description:       A plugin to automatically update GitHub, Bitbucket,
or GitLab hosted plugins, themes, and language packs. It also allows for
remote installation of plugins or themes into WordPress.
 * Version:           7.3.0
 * Author:            Andy Fragen
 * License:           GNU General Public License v2
 * License URI:       http://www.gnu.org/licenses/gpl-2.0.html
 * Domain Path:       /languages
 * Text Domain:       github-updater
 * Network:           true
 * GitHub Plugin URI: https://github.com/afragen/github-updater
 * GitHub Languages:  https://github.com/afragen/github-updater-translations
 * Requires WP:       4.6
 * Requires PHP:      5.3
 */
'''

**Comment by afragen** [comment]
Sorry, I meant the headers if your plugin, not GHU’s.

**Comment by fwolfst** [comment]
Ah sure.
its https://github.com/ecovillage/ev7l-events (plugin)
and https://github.com/ecovillage/hueman-7l-child (theme)

'''
[...]
* Ecovillage 7 Linden Event System
*
* @package EV7L_Events
* @license AGPL-3.0+
*
* @wordpress-plugin
* Plugin Name: 7L Events
* Plugin URI: https://github.com/ecovillage/ev7l-events
* Description: Enables post types 'Event', 'Event Category' and 'Referee',
* provides functionality like widgets to be used in views.
* Version: 0.3.1
* Author: Felix Wolfsteller
* Author URI: https://econya.de
* Text Domain: ev7l-events
* License: AGPL-3.0+
* License URI: http://www.gnu.org/licenses/agpl-3.0.txt
* Domain Path: /languages
* GitHub Plugin URI: https://github.com/ecovillage/ev7l-events
'''

and

'''
/*
Theme Name: siebenlinden.org hueman child theme
Version: 0.7.7
Description: A child theme of Hueman for siebenlinden.org
Template: hueman
Author: Felix Wolfsteller
GitHub Theme URI: https://github.com/ecovillage/hueman-7l-child
*/
'''

**Comment by afragen** [comment]
Does this error exist when only GHU is present and active and no other plugins and only default themes?

Can you try creating a new local install of WP with only GHU present and active? Does the error persist?

**Comment by afragen** [comment]
Do you happen to have a plugin or theme with an empty `GitHub Plugin URI` IR empty `GitHub Theme URI`?

That’s really where the error begins.

**Comment by afragen** [comment]
I may have another idea if the above is not the case. I’ll test and get back to you.

**Comment by fwolfst** [comment]
* About the vanilla installation: I cannot test right now.
* rgrep 'GitHub Theme' and rgrep 'GitHub Plug' shows me only the relevant
file(s) as I directed to above (and obviously code and readmes of GHU).

**Comment by afragen** [comment]
Can you try commenting out class Branch line 43 so it is the following `//parent::__construct()`?

**Comment by fwolfst** [comment]
Did that, re-activated GHU and no error messages showed up. So, I guess you
found it!

**Comment by afragen** [comment]
I hate when I add bugs. I should have a fix out soon.

**Comment by afragen** [comment]
And thanks
