### ISSUE TITLE
Bitbucket - Plugin installation fails (updates or branch switching works fine)

### ISSUE THREAD

**Issue by Liarco** [afragen/github-updater#605]
Since one of the latest updates I'm not able to install anything from the GHU panel. The installation fails with the same "zip error" as if the login data was invalid, but using the same user/pass to update a manually installed plugin works fine. (Anything works the same with both "master" and "app password" credentials)

I'm having this issue under the following conditions:
* installing a plugin from the GHU panel
* the repository is private

I can't test other cases at the moment, including:
* installing themes
* installing from a public repository

Thanks for your time.

**Comment by afragen** [comment]
If you retry the install does it work? Does this only happen the first time or every time?

**Comment by Liarco** [comment]
# It won't work even retrying, but not when updating/switching branch
# I'm going to try this as soon as I reach my workspace!

**Comment by Liarco** [comment]
Here is what I did:
* disabled my custom plugin
* deleted it
* switched GHU branch to develop (using GHU itself)
* installed my custom plugin

Everything seems to work fine now... does it help?

**Comment by afragen** [comment]
So everything is working in GHU develop branch? If yes, that means I think I fixed the problem. https://github.com/afragen/github-updater/commit/fba004577e3d65a0c4dec5371123bd9a899871fc

**Comment by Liarco** [comment]
Yes, thank you for your help!
