### ISSUE TITLE
Unable to update private Bitbucket repo with WP-CLI

### ISSUE THREAD

**Issue by afragen** [afragen/github-updater#607]
I think it's an issue passing the Basic Auth header. I have to dig deeper.

**Comment by maremmano** [comment]
Hello,

I get the following error when trying to update a theme from private bitbucket repo using wp-cli:
PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature

No problem updating from wp admin.

Thank you very much for the work done.

**Comment by afragen** [comment]
That is the error I’m describing.
