### ISSUE TITLE
Performance impact with get_plugins()

### ISSUE THREAD

**Issue by f4bsch** [afragen/github-updater#608]
These are actually 2 issues, but somehow related:

1. Issue:
github-updater does a meta update of all plugins on the admin screens:
```
			'plugins.php',
			'plugin-install.php',
			'themes.php',
			'theme-install.php',
			'update-core.php',
			'update.php',
			'options-general.php',
			'settings.php',
```

This meta update calls `get_plugins()`, which does a whole scan of the Plugin directory, and can be very slow (I measured up to 600ms).

I think it's not necessary to update on all theses screens, making them slow. There should be at least an interval limit, like `_maybe_update_plugins()` has 12 hours.

2. Issue
Because `get_plugins()` is slow, I changed the object cache group `plugins` to be persistent. (I know that this is non-WordPress-standard, but I got bored by this slow function)
This will cause github-updater to trigger some warnings:
The plugin expects the filter `extra_plugin_headers` to be triggered, and there it collects `Fragen\GitHub_Updater\Base::$extra_headers`. But if `get_plugin()` uses the cache value it will never trigger `extra_plugin_headers` and `Fragen\GitHub_Updater\Base::$extra_headers` stays empty.
This causes `Fragen\GitHub_Updater\Plugin::get_plugin_meta()` to fail with just empty `$git_plugin`.
So `get_plugin_meta()` should return an empty Array if `self::$extra_headers` is empty. Here I'm not sure if the updater will still capture and show updates. Maybe `self::$extra_headers` should be cached once set.

**Comment by afragen** [comment]
> This meta update calls get_plugins(), which does a whole scan of the Plugin directory, and can be very slow (I measured up to 600ms).

This was less than 200ms on my local testing environment. Clearly the more plugins you have the longer it will be.

I adhere to WP core and utilize it as often as I can. This prevents potential breakage with WP updates. By your own admission, changing the behavior of `get_plugin_meta()` cascades to other errors.

GHU only fires on admin pages where plugins, themes, settings, or updating is present. It will not fire on the frontend unless you are using a remote updating service.

If you try the `develop` branch you will notice a significant speed increase in page load time as API calls are now via WP-Cron.
