### ISSUE TITLE
No tag 7.3.1.11 ?

### ISSUE THREAD

**Issue by fadupla** [afragen/github-updater#610]
Hello @afragen 

Isn't there a missing tag for the last version 7.3.1.11 you made ?

I encounter issues with "remote_version" for any bitbucket plugins, and 7.3.1.11 seems in the way to resolve them...

Thanks :)

**Comment by afragen** [comment]
I only tag releases which come from the `master` branch. I should be merging soon. I’m just seeing something odd on my test site that I can’t replicate locally. 

I’m glad that fixes an issue you saw.
