### ISSUE TITLE
Versions numbers don't match, updater works, but semantic error?

### ISSUE THREAD

**Issue by MCOAugusta** [afragen/github-updater#611]
See attached screenshots. Brackets and GitHub version of style.css is 0.0.3, however wordpress is seeing version 4.0.0. The theme updates to the correct files, I just don't understand why its saying the new version is 4.0.0.

![screen shot 2017-10-12 at 2 32 45 pm](https://user-images.githubusercontent.com/32741136/31512837-4fcbfd30-af5a-11e7-847c-a8e1b8c17ca7.png)
![screen shot 2017-10-12 at 2 32 57 pm](https://user-images.githubusercontent.com/32741136/31512838-4fd93554-af5a-11e7-9ab6-0b775d62bb85.png)
![screen shot 2017-10-12 at 2 33 03 pm](https://user-images.githubusercontent.com/32741136/31512839-4feb38c6-af5a-11e7-8f32-47747fe13ea3.png)

**Comment by MCOAugusta** [comment]
WP editor version is also correct

![screen shot 2017-10-12 at 2 37 34 pm](https://user-images.githubusercontent.com/32741136/31513036-f4b25dc6-af5a-11e7-98d6-61256ca92036.png)

**Comment by afragen** [comment]
Strange. I’ll take a look.

**Comment by MCOAugusta** [comment]
Also shows that an update (to 4.0.0) is available when there isn't one, theme is updated to current version in GitHub. 

I previously had a 4.0.0 version of the theme in a repo that I deleted. Repo had the same name. Perhaps the files are cached?

**Comment by afragen** [comment]
That is likely the issue. Is the theme in the repo really deleted? There are 2 options.

1. Set the version number higher than the previous repo theme.
2. Use the `define( 'GITHUB_UPDATER_OVERRIDE_DOT_ORG', true );` hook.

**Comment by afragen** [comment]
You must still be cached somewhere as I don't see any update to v4.0.0
