### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by f4bsch** [afragen/github-updater#612]
@afragen closed https://github.com/afragen/github-updater/issues/608, let me reformulate it:

github-updater triggers the WP API function `get_plugins()` on a lot of admin screens. This function scans the complete plugin directory, which can take a long time (I measured 600ms with 50 plugins in that directory).

github-updater should cache the `get_plugins()` result and defer an update to a cron.

I know that 50 plugins are a lot, but consider that that github-updater is an updater, and it should do it's job well. This means that it should be able to handle a lot of plugins, without clogging the admin screens.

**Comment by afragen** [comment]
Have you tried the `develop` branch?

**Comment by afragen** [comment]
Thanks for opening this ticket, https://core.trac.wordpress.org/ticket/42217

I think it’s the better way to handle the issue rather than force plugin developers to create their own solution.

**Comment by afragen** [comment]
@f4bsch I've been looking into this and I've got it working such that on my local dev with caching the lookup is 1-2 ms vs 300ms without caching.

My question to you is, how long is long enough to cache? Currently I have it set to 5 minutes.

https://github.com/afragen/github-updater/commit/597ca9541e3f75a6ffaab3fe6fbdf2a327e0c09e

**Comment by afragen** [comment]
Timeout increased to 30 minutes. https://github.com/afragen/github-updater/commit/845e9a6cca56b12951ce94772edd426c9944ba3c

**Comment by afragen** [comment]
@f4bsch I’m curious to see what kind of improvements you see with the develop v7.3.1.23

**Comment by afragen** [comment]
I have to revert this as I think it's causing #662 and possibly #637 https://github.com/afragen/github-updater/commit/6a787f97c07e9b1cdfe6d8051ad3400cf437090c
