### ISSUE TITLE
Clear Cache After Install Failure

### ISSUE THREAD

**Issue by bradmkjr** [afragen/github-updater#614]
When installing a plugin from Bitbucket, and accidentally enter the incorrect password GU caches the results from Bitbucket, which can either be a redirect or 1k corrupt zip file. Going back, entering the correct password results in same error. Clearing cache allowed me to install the repo without issue. I suggest that on any install error to clear the cache to ensure that future attempts to install same repo are not impacted by previous attempts.

Thanks

**Comment by afragen** [comment]
Which cache are you wanting to clear? Specifically which data?

Install is designed to store any new user/pass or access tokens. These can be corrected on the individual settings tabs.

**Comment by afragen** [comment]
I think I may have solved this in https://github.com/afragen/github-updater/commit/69ab45e7ade548d6f6ef49ff81334f10f2fa1dbf

**Comment by bradmkjr** [comment]
Thank you, I know it wasn’t a major issue but it was something that could
cause a 1st time user a major headache if they entered incorrect
information.

P.S. I think Bitbucket has changed from using usernames to login to email
addresses. I’m not 100% sure, but it someone else could confirm and then we
could update the field label.

**Comment by afragen** [comment]
I still use a username, not an email address. Can you confirm that an email works? If so, I'll change the string.

**Comment by afragen** [comment]
I just tested locally and while logging into the website requires an email address, using Basic Auth seems to require a username and app password.

**Comment by bradmkjr** [comment]
I guess I jumped the gun, documentation says to use username:

https://confluence.atlassian.com/bitbucket/use-the-bitbucket-cloud-rest-apis-222724129.html#UsetheBitbucketCloudRESTAPIs-Authentication

**Comment by afragen** [comment]
It would be nice if they would accept either. Please close if your issue is fixed, if not let me know what else we can try.

**Comment by afragen** [comment]
Brad, make sure you update to develop 7.3.1.20 before you attempt a remote install otherwise your stored options will vanish. 😣
