### ISSUE TITLE
can't switch branches for themes

### ISSUE THREAD

**Issue by le-mon** [afragen/github-updater#618]
I have the same issue as https://github.com/afragen/github-updater/issues/315
But there was no solution, just solved. 

I see no option to switch branches for themes. Under "Theme Details" there is only one version and no option to switch. 

The theme gets updated from github. 

What can i do?

Worpdress is v4.8.2

**Comment by afragen** [comment]
Can you provide a screenshot and the theme’s headers?

**Comment by le-mon** [comment]
Sure :)

`/*
Theme Name: hanflager
Theme URI: http://hanflager.de
Author: Andreas
Author URI: http://hanflager.de
Description: just a fancy theme
Version: 1.0.0
License: GNU General Public License v2
License URI: http://www.gnu.org/licenses/gpl-2.0.html
Tags: jquery animation responsive
Text Domain: hanflager
*/
`
![screenhsot_ghu](https://user-images.githubusercontent.com/6536450/32003139-8f4c501a-b99e-11e7-9d21-eeb5dbefa74b.png)

**Comment by le-mon** [comment]
Oh, i forgot to add "GitHub Theme URI: " to the header. 
I did now. 

I had to reinstall the theme over ghu plugin and it works now. 
Thanks for the hint ;)
