### ISSUE TITLE
Cannot set both tokens for Github and Gitlab

### ISSUE THREAD

**Issue by geminorum** [afragen/github-updater#619]
saving each type token will result in empty others.

saved db options, after setting gitlab token:
![chrome_2017-10-26_07-08-46](https://user-images.githubusercontent.com/150718/32034146-a91fbc3c-ba1d-11e7-9a3f-886d29bf79e2.png)

saved db options, after setting github token:
![chrome_2017-10-26_07-13-42](https://user-images.githubusercontent.com/150718/32034161-c2a793aa-ba1d-11e7-9d52-d4754c058566.png)

- I think the simple use of core's settings api (e.g. `register_setting()`) is not a good idea for a complex system like github-updater.
- It's better to keep the type tokens and plugin/theme tokens on separate objects and both away from general options.
- tokens are not passwords and cannot be revealed by a glance. so form inputs are better to be type `text` instead of `password`.
- and it's really confusing to have two primary buttons after a form on the both sides:

![chrome_2017-10-26_07-26-53](https://user-images.githubusercontent.com/150718/32034484-b970a4e6-ba1f-11e7-8d2a-86def85c7a02.png)

**Comment by geminorum** [comment]
probably I have to point out that the core's settings api is messing with dashes and underscores.

`db_version` > `db-version`
`github_access_token` > `github-access-token`

**Comment by afragen** [comment]
My guess is that you have a plugin that hooks into `sanitize_file_name()` and/or `sanitize_text_field()` and that is why you are seeing the results you have.

**Comment by geminorum** [comment]
- actually I have ([here](https://github.com/geminorum/gnetwork/blob/f77daa2fa720cca4e071945283e0649d6fa33255/includes/modules/media.php#L1341-L1357)). but using `seems_utf8()` and for un-escaped *file names*. 
- related core [ticket](https://core.trac.wordpress.org/ticket/22363). 
- github-updater works fine after disabling, though. 😩 
- why using this for sanitization of keys?

**Comment by afragen** [comment]
Can you remove your filter after it’s used? That way it shouldn’t interfere with anyone else using the same function.

**Comment by afragen** [comment]
Does this have anything to do with your other issue?

**Comment by geminorum** [comment]
> Can you remove your filter after it’s used? That way it shouldn’t interfere with anyone else using the same function.

this is a general filter for media upload filenames. there are several plugins that [do the same](https://wordpress.org/plugins/search/filename+sanitizer/). not to mention the two core tickets [here](https://core.trac.wordpress.org/ticket/22363) and [here](https://core.trac.wordpress.org/ticket/24661)

> Does this have anything to do with your other issue?
currently testing.

**Comment by geminorum** [comment]
> Does this have anything to do with your other issue?

still the same after disabling (no asset release)
![chrome_2017-10-26_09-27-36](https://user-images.githubusercontent.com/150718/32037051-26f00c36-ba30-11e7-8f3e-2a93b6733b23.png)

**Comment by geminorum** [comment]
test it again after disabling all plugins: same issue.

**Comment by afragen** [comment]
Can you test from a local install with only the current develop branch of GHU and one of your plugins or themes at a time. When one works add another and continue until the problem presents.

**Comment by afragen** [comment]
Can you zip up your wp-content folder and send me a download link so that I can test with all of your content?

**Comment by geminorum** [comment]
posted on #615

**Comment by geminorum** [comment]
please consider using proper sanitization. the problem still exists. 😩

**Comment by afragen** [comment]
With all due respect I’m using core sanitization functions for there intended purposes.

**Comment by geminorum** [comment]
code sanitization for filenames not for option keys.

thanks anyway.

**Comment by afragen** [comment]
So what’s a better core function to use and my option keys are very similar to filenames.

**Comment by afragen** [comment]
The intent is to sanitize repo names.

**Comment by geminorum** [comment]
- the similar is not the same.
- the file name of plugin in core is `plugin-slug/plugin-slug.php'
- if repo names are slugs like  `plugin-slug` or textdomain then the proper function is [sanitize_title()](https://developer.wordpress.org/reference/functions/sanitize_title/)
- even the for option keys with restrict chars core have [sanitize_key()](https://developer.wordpress.org/reference/functions/sanitize_key/)

**Comment by geminorum** [comment]
by the way, I comment out the filter hook and currently have not any problem with this issue. but it's not the correct approach.

**Comment by afragen** [comment]
The issue is all of the sanitize functions have filter hooks and any plugin can hook into. Making changes to these hooks without removing those hooks after use had unintended consequences. 

I use the this sanitize function as it provides more variability for repo names.
