### ISSUE TITLE
How long does cache exist before the system refreshes it automatically?

### ISSUE THREAD

**Issue by themightymo** [afragen/github-updater#621]
I'm really loving this plugin - thank you!

I know I can manually refresh the cache (https://github.com/afragen/github-updater/wiki/Settings).  

But if I do not manually refresh the cache, how long until the system checks for a plugin update on its own?

Thanks,
Toby

**Comment by afragen** [comment]
The cache expires after 12 hours. Once WP-Cron runs after that the new checks should occur.

**Comment by themightymo** [comment]
Awesome.  Thanks!
