### ISSUE TITLE
Add real background processing instead of WP-Cron

### ISSUE THREAD

**Issue by afragen** [afragen/github-updater#622]
Create a real background processing implementation as WP-Cron seems problematic.

https://github.com/A5hleyRich/wp-background-processing

It would seem using a background process for `API::api()` is the process to background, however, need to ensure returned result correctly flows to cache.

**Comment by afragen** [comment]
Unfortunately the above wp-background-processing also uses WP-Cron so it wouldn't be any better.

I'll keep looking, possibly https://github.com/techcrunch/wp-async-task

**Comment by afragen** [comment]
Possibly hook into Heartbeat API as polling to run update tasks.

**Comment by wp-networks** [comment]
...not sure what you're looking for, wanted to be sure you were aware of [Cavalcade](https://hmn.md/2017/05/29/cavalcade-scaling-wordpress-jobs/)

**Comment by afragen** [comment]
I’ve seen Cavalcade before and just read the post again. It seems they require WP-CLI and not everyone has access to it. 

But thanks for the idea. I’ll keep looking.

**Comment by afragen** [comment]
It would seem that without lots of server control there are 2 automatic action triggers, WP-Cron and the Heartbeat API.

We currently use WP-Cron and I’m not sure there’s a particular benefit of one over the other.

**Comment by afragen** [comment]
Unless there is some simpler method, using WP-Cron seems like the _WordPress Way_. If anyone finds a better solution please re-open this issue.

I have added a new [wiki page for Background Processing](https://github.com/afragen/github-updater/wiki/Background-Processing).
