### ISSUE TITLE
Programmatically set up plugin for private Bitbucket repos

### ISSUE THREAD

**Issue by dohnutt** [afragen/github-updater#623]
I didn't see this anywhere, so I figured I'd suggest it. I've looked through the documentation and some of the code but couldn't find a way to do this, so I assume it doesn't exist already. If it does... even better 👍 

I am using this plugin alongside some custom plugins that are in private bitbucket repos. Right now, I've got it set up using the `github_updater_set_options` filter, providing a bitbucket username and app password with read-only access to those two repos. I've still got to go into the GU options page and check off the private repos.

Ideally, I could install my plugins alongside GU and GU would already be set up because I've defined the options through my plugins. Thoughts?

P.S. Great plugin!

**Comment by afragen** [comment]
Add the following element to the array you’re passing to the filter.

`'my-private-plugin-slug' => '1'`

For every private Bitbucket repo you are installing.

**Comment by dohnutt** [comment]
Ooops. That _was_ in the documentation. Thanks so much.
