### ISSUE TITLE
Plugin File not found

### ISSUE THREAD

**Issue by rizkirmani** [afragen/github-updater#624]
While installing dokan-lite I am facing following error on my website "The plugin dokan-lite/dokan.php has been deactivated due to an error: Plugin file does not exist" 
Two days ago it was working fine and pro version is also working fine but I am not able to activate dokan lite due to this error.I have deleted all files of this plugin from file manager again and again error remain same.How this error will be removed?

**Comment by afragen** [comment]
@rizkirmani I'm having a bit of trouble following your problem.

Can you share the URL for dolan-lite?

- How did you install dokan-lite?
- When did the problem first occur?
- What does your `wp-content/plugins` directory contain? What are the individual plugins directories actually named?
- Can you share actual screenshots of the errors?

**Comment by rizkirmani** [comment]
@afragen Thank you very much for your response. The issue was resolved.That was due to a plugin conflict.

**Comment by afragen** [comment]
Not GitHub Updater I hope.
