### ISSUE TITLE
Can't change Github API token for theme

### ISSUE THREAD

**Issue by giedrius** [afragen/github-updater#625]
It looks like GitHub API token for theme does not work in Github updater settings page  (it looks it works for general Github API Tokens and probably for plugins too). There is no error, but setting left unchanged and remains the same in DB. 
Temporary workaround - changed manually in wp-options table.

**Comment by afragen** [comment]
If you set s specific access token when using the remote install then that token will be associated with that repo. 

If the repo is public it really doesn’t matter and only an GitHub.com token is needed to avoid hitting the API rate limit.
