### ISSUE TITLE
PHP errors after updating to version 7.4.2

### ISSUE THREAD

**Issue by webmandesign** [afragen/github-updater#626]
Hi,

I just updated the plugin to version 7.4.2 and I get these PHP errors:

![](http://easycaptures.com/fs/uploaded/1219/0258425012.png)

Please fix those.

Thanks and regards,

Oliver

**Comment by afragen** [comment]
The current version is 7.4.3. Are those PHP warnings and notices still present?

**Comment by webmandesign** [comment]
Oh, OK, I see. Probably it was cache or something, as just now I was prompted to update to 7.4.3.

The errors are not occurring in 7.4.3. Thanks for help!
