### ISSUE TITLE
What happens when I enable remote management for ManageWP?

### ISSUE THREAD

**Issue by petemolinero** [afragen/github-updater#627]
I have ManageWP connected to my site, and Github Updater is configured with my active theme.

I'm just wondering what this plugin offers as far as remote management? I mean, when I enable remote management for ManageWP, nothing seems to happen. I don't notice any new options in my ManageWP dashboard or on my WordPress site. What should I be looking for?

Thanks,

Pete

**Comment by afragen** [comment]
Technically, most remote management services, like ManageWP, access your site via their plugins and APIs. These usually act on the base URL of the site, `https://example.com`. GitHub Updater is designed to not affect the front end of the site. It does this by not running expect on specific admin dashboard pages. The Remote Management setting also adds `index.php` to the list of pages that GitHub Updater runs on.

Once selected and after GitHub Updater runs it's checks, this means that updates should also be visible in the ManageWP dashboard.

I can test and document that this works for all listed Remote Management services, but it should work with any of them. Unfortunately as ManageWP has evolved, I haven't had the opportunity to test but I still believe it should work.

If it doesn't work, make sure you can see updates normally in the dashboard.

**Comment by petemolinero** [comment]
Great, thanks!
