### ISSUE TITLE
Release with dependencies

### ISSUE THREAD

**Issue by Lewiscowles1986** [afragen/github-updater#628]
So I have a plugin with an external composer dependency.

I created a release (matching readme version), and then created "{$repo}-{$headtag}.zip" as-per https://github.com/afragen/github-updater/issues/407#issuecomment-226255967

For some reason it downloads master branch, not the release. Do I need to use a token? Do I need to release with the `Release Asset: true` prior to changing the format for pulling updates?

I have `Release Asset: true` in this release and the release is tagged with "{$repo}-{$headtag}.zip" I'm just not sure what is going wrong.

**Comment by afragen** [comment]
Can you share the URL? It will make it easier for me to look at the repository to answer questions.

**Comment by afragen** [comment]
I looked in your repos and saw WordPressSVGPlugin. I assume that’s the plugin you’re referring to.

I was able to install it. Decrease the version number locally and update using the release asset. To test I usually just decrease the version number of the installed plugin.

How did you install the plugin? If you installed via GHU’s remote install, you would need to to the above as it would install the non-functional master branch.

**Comment by Lewiscowles1986** [comment]
Sure. Also checked https://github.com/afragen/github-updater/wiki/Settings#release-assets

https://github.com/Lewiscowles1986/WordPressSVGPlugin/releases/tag/1.8.2

**Comment by afragen** [comment]
It seems to be working as expected for me, as above. If it’s not working on your end can you provide some information. What is current installed version? Have you tried refreshing the cache?

**Comment by Lewiscowles1986** [comment]
:blush: Fixed. It was a release referencing an orphaned commit for 1.8.2. Thank you and sorry

**Comment by afragen** [comment]
Not a problem. Glad it’s working.
