### ISSUE TITLE
Connection to private BitBucket repository no longer works

### ISSUE THREAD

**Issue by petemolinero** [afragen/github-updater#629]
Hi,

Lately, I've had multiple sites that no longer can connect to their associated Bitbucket repository (at least, I'm assuming what the red warning icon means). In all cases, the repository was private. I've checked and double-checked that my account credentials were correct (including trying both my Bitbucket username and email as the username). Nothing seems to fix it. Any ideas?

![updatesfromprivatebitbucket](https://user-images.githubusercontent.com/1924752/33153295-03d6214c-cf96-11e7-9301-656fb8f17c79.png)

**Comment by afragen** [comment]
This is somewhat a byproduct of using WP-Cron. When the cache expires or is refreshed, GHU must wait until WP-Cron runs and the API calls run in the background. You can load `http://mysite.com/wp-cron.php`. If you don’t want to use the background processing you can revert to the original method with the following hook, `add_filter( 'github_updater_disable_wpcron', '__return_true' );`

**Comment by afragen** [comment]
BTW, you must use the Bitbucket username, using the email will fail.

**Comment by afragen** [comment]
https://github.com/afragen/github-updater/wiki/Background-Processing

**Comment by petemolinero** [comment]
Thanks for the quick reply! That makes sense since my server has WP_CRON disabled and instead uses a server-side cron to ping it every 15 minutes. That would mean, of course, that if I click 'Refresh Cache' I'd have to wait for the next 15-min-interval execution of WP Cron before I'd see the cache refresh go into action.

It looks like the foreground processing is what I'll need. Are there any negative side-effects of disabling it using the filter you've shown?

**Comment by afragen** [comment]
Only side effect is that it runs all the API requests. Depending upon the number of plugins/themes you have that can take a while. I found I could actually timeout my server, take more than 30 seconds to run all requests. You could just increase you server-side cron interval to 5 minutes. 

Really whichever works best for you. The trade off is delay for cache refreshes with more responsiveness or somewhat less responsiveness and no delay in cache refresh.

**Comment by petemolinero** [comment]
Okay, sweet. So...just to be sure, what API requests are we talking about? Is it correct that the only API request in question is the one that communicates with Github/BitBucket to see if there's an update—which would amount to one request for each plugin/theme that uses Github Updater?

**Comment by afragen** [comment]
It’s the API requests between GitHub Updater and both GitHub/Bitbucket/GitLab, but it’s really about 6 requests per repository. Everyone has API requests to GitHub for GHU.

**Comment by afragen** [comment]
There’s another filter to bypass several of these requests but it limits the user experience. Also turning off branch switching stops a request.

**Comment by petemolinero** [comment]
Awesome, thanks for the quick and thorough replies!

**Comment by petemolinero** [comment]
It might be cool to have a `title` attribute explanation on that red alert icon that sits next to the installed plugins and themes.
