### ISSUE TITLE
First plugin installation with private Bitbucket repository always fail

### ISSUE THREAD

**Issue by netplansrl** [afragen/github-updater#630]
If I try to install first plugin from a Bitbucket repository and I always received this error message:

> Scaricamento del pacchetto di installazione da https://bitbucket.org/xxxxx/xxxxxx/get/master.zip…
> Scompattamento del pacchetto…
> Il pacchetto non può essere installato. **PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature**
> 

![1](https://user-images.githubusercontent.com/33959702/33213864-bbeee9aa-d129-11e7-9dea-fb4edb28ce5b.jpg)

If I try to install it manually and then insert the username and the password, after I saved I loose the Bitbucket Button:

![2](https://user-images.githubusercontent.com/33959702/33213869-bfd75700-d129-11e7-9cf6-9f6da5abc507.jpg)

To fix this problem I need to use the 6.3.5 version, add the first plugin (or the credential) and then I can upgrade the github-updater to the last version (7.4.3)

**Comment by afragen** [comment]
I will try to reproduce this.

**Comment by afragen** [comment]
Can you update to latest develop branch? I think I've fixed this. Please let me know if it's fixed. Thanks.

**Comment by netplansrl** [comment]
Just tried. I saw the following error is fixed:
> [Mon Nov 27 10:19:48.638925 2017] [:error] [pid 8971] [client xxx.xxx.xxx.xxx:21014] PHP Warning:  array_filter() expects parameter 1 to be array, null given in /var/www/xxxxxxx/wp-content/plugins/github-updater-7.4.3/src/GitHub_Updater/Base.php on line 494, referer: http://xxxxxxxx/wp-admin/plugins.php
but the problem stills: If I try to add the bitbucket credentials and save it
![1](https://user-images.githubusercontent.com/33959702/33260003-e7404e5a-d35e-11e7-9b46-936275bfda50.jpg)
I always receive this:
![2](https://user-images.githubusercontent.com/33959702/33260021-f5dad57a-d35e-11e7-9d9d-4373e29931e5.jpg)

If I downgrade the github-updater plugin to the 6.3.5 version and retry the same operation everything works smoothly
![3](https://user-images.githubusercontent.com/33959702/33260322-bf530954-d35f-11e7-91fe-d90f2ad205ce.jpg)
![4](https://user-images.githubusercontent.com/33959702/33260323-c38ba666-d35f-11e7-926a-ca010eea0eae.jpg)

**Comment by afragen** [comment]
Let’s not confuse the issue, I don’t need screenshots from v6.3.5. Let’s stick to using the most current develop branch.

1. Is there still an error when first installing a private Bitbucket plugin? 
2. Do the Bitbucket credentials save correctly?

Screenshots of errors are helpful. Please tell me what you were doing when the error occurred.

**Comment by netplansrl** [comment]
I removed all plugins, installed the github-updater 7.4.3.1 (develop branch) and i tried to install the first plugin from bitbucket. I was able to install and enable it but, if i go in the Bitbucket sub tab the second and third sub-tabs disappear and no plugins are listed.

![0](https://user-images.githubusercontent.com/33959702/33273060-703fc172-d38c-11e7-91a4-3b91549aa108.PNG)


If I push the "Refresh Cache" button I always receive an error: ERR_EMPTY_RESPONSE
![1](https://user-images.githubusercontent.com/33959702/33272896-ed32871a-d38b-11e7-95b3-35d0a8f9c391.jpg)

**Comment by afragen** [comment]
Can you try replicating this on a new local install? Something is definitely going wrong in this install and I can’t reproduce it.

Can you set WP_DEBUG to true and let me know if there are any error messages?

**Comment by ivan133** [comment]
@afragen 
I confirm it works on development branch and does not work on master

**Comment by ivan133** [comment]
But I don't see bitbucket tab under Settings after successful install

**Comment by afragen** [comment]
@ivan133 is that last comment, re:not seeing Bitbucket tab, on the develop branch? 

If yes, any errors from WP_DEBUG?

**Comment by ivan133** [comment]
@afragen  I'm so sorry
The tab works.
I didn't setup Bitbucket Plugin URI.
And I confirm that bitbucket plugin installation works on development branch and does not work on master

**Comment by afragen** [comment]
@ivan133 thanks. I’ll push out an update soon.

**Comment by netplansrl** [comment]
I've activate the WP_DEBUG, fix all PHP Notice made from other plugins, retry to push the "refresh cache" button and the three tabs appear again. The only strange thing is if I check all plugins (I double checked the credential) and I press "Save changes" button all plugins still with the the red exclamation point, but after a while, changing the page and going back to the bitbucket tab everything is ok. Maybe a little delay, I don't know.
BTW I confirm that fixing the PHP Notice generated by the other plugins everything is ok now.

Thank you for your precious support!
Matteo

**Comment by afragen** [comment]
@netplansrl what you see after the refresh cache is normal with the background processing.
https://github.com/afragen/github-updater/wiki/Background-Processing

Thanks for reporting this and working with me to fix it.
