### ISSUE TITLE
GitHub Updater Error Code: There may be a problem with WP-Cron. A GitHub Updater WP-Cron event is overdue

### ISSUE THREAD

**Issue by henrywright** [afragen/github-updater#631]
Hey

We're seeing the below error message lately. I couldn't find anything in the documentation. What does this mean and how can we fix it?

> GitHub Updater Error Code: There may be a problem with WP-Cron. A GitHub Updater WP-Cron event is overdue

**Comment by billybigpotatoes** [comment]
I think it is due to cron not running - as a result it is not refreshing the updates

**Comment by billybigpotatoes** [comment]
run wp-cron.php - see if it goes away

**Comment by afragen** [comment]
That warning displays if it has been more than 24 hours since WP-Cron has run. In a low traffic site this can happen. Take a look at the following wiki page too.

https://github.com/afragen/github-updater/wiki/Background-Processing 

Thanks @billybigpotatoes you are correct.

**Comment by henrywright** [comment]
Thanks @afragen for the link to the Background Processing article. That's super useful
