### ISSUE TITLE
Does github-updater work with mu-plugins?

### ISSUE THREAD

**Issue by mihdan** [afragen/github-updater#633]

**Comment by afragen** [comment]
The only way to update a mu-plugin is for the mu-plugin to be a symlink to a plugin in the plugin directory. 

You can see what I mean in the actual GitHub Updater plugin and the instructions for installing as an mu-plugin. 

https://github.com/afragen/github-updater/wiki/Installation

**Comment by mihdan** [comment]
ок

**Comment by afragen** [comment]
This is a limitation of WordPress.
