### ISSUE TITLE
cron error

### ISSUE THREAD

**Issue by peter-mumford** [afragen/github-updater#634]
I get this error on multiple sites I manage:
GitHub Updater Error Code: There may be a problem with WP-Cron. A GitHub Updater WP-Cron event is overdue.

I realize that's not very specific. I looked in the logs and there is nothing related to cron.

**Comment by afragen** [comment]
It can happen on low traffic sites. It’s really just a notification that WP-Cron hasn’t run and your caches will be outdated. 

https://github.com/afragen/github-updater/wiki/Background-Processing

**Comment by jamminjames** [comment]
We have a cron set up on our server, which triggers WP cron, among other things, and so we turn off the automatic cron in Wordpress. Please consider a setting that will allow for this, and suppress warnings. Thank you.

**Comment by jamminjames** [comment]
It is set up to trigger WP's cron every few minutes, but I'm still getting this warning.

**Comment by afragen** [comment]
Can you install the WPCrontrol plugin and see if you have any WP-cron events that are due and should have been run?

**Comment by jamminjames** [comment]
Okay, figured it out. We just changed to a secure site recently (https) and neglected to change the wp-cron url in the server's cron job. I'm glad we had a github plugin, or we may have not noticed this for quite a bit longer! Thanks for your help.

**Comment by afragen** [comment]
If you have WP-CLI available I think that method is better, but as long as it’s working.
