### ISSUE TITLE
Private GitLab causing download fails

### ISSUE THREAD

**Issue by timwsuqld** [afragen/github-updater#635]
We have a private Gitlab instance (only accessible from internal servers) which we are trying to use.

Initially I tried the "Install Theme" option, which failed.
```
Downloading installation package from https://INTERNAL_SERVER.suqld.org.au/wordpress-themes/suqld-org-au/repository/archive.zip?ref=master&private_token=*********…

Download failed. A valid URL was not provided.
```

I then manually installed the package (a curl on the URL works fine, and downloads the correct zip), and refreshed the cache, which had the Github updater plugin now detecting the theme. After pushing an update to the theme and refreshing the cache, wordpress detects the new version, but attempts to update it also fail with `Update Failed: Download failed. A valid URL was not provided.`

The server running the wordpress install, correctly resolves the internal DNS name, and has no problem accessing it. (As said above, Curl works fine, and we currently have our own solution that does git to that server to pull our plugins/themes).

As it's impossible to give you access to the GitLab install, can you point us in the right direction to debug why it can't download these urls.

The SSL certificate being served is a *.suqld.org.au wildcard that validates correctly.

**Comment by timwsuqld** [comment]
The only errors in the webserver logs are:
```
[11-Dec-2017 03:17:36 UTC] PHP Notice:  Undefined index: branch_switch in /var/www/html/wp-content/plugins/github-updater/src/GitHub_Updater/Theme.php on line 568
```

**Comment by afragen** [comment]
The PHP Notice shouldn't be causing an issue.

Can you post your theme's headers?

**Comment by afragen** [comment]
What is the user and the repository?

**Comment by afragen** [comment]
Is `https://INTERNAL_SERVER.suqld.org.au` an internal server? It seems to have an FQDN?

**Comment by afragen** [comment]
It's possible that some WP core function doesn't like your internal domain.

**Comment by timwsuqld** [comment]
Hi @afragen 

Headers are:
```
/**
 * Theme Name: SU QLD
 * Theme URI: https://www.suqld.org.au/
 * Author: Flagship Digital
 * Author URI: https://flagshipdigital.com.au/
 * Description: Template developed for SU QLD.
 * Version: 1.0.1
 * Text Domain: su
 * GitLab Theme URI: https://INTERNAL_SERVER.suqld.org.au/wordpress-themes/suqld-org-au
*/
```

https://INTERNAL_SERVER.suqld.org.au is an internal server. Due to our split DNS, it is a FQDN for servers inside the network. It resolves to an internal IP which is accessible to those servers.

Looking through the servers logs, it's clear that the requests to the GitLab server aren't using the displayed url, but are instead using the API. 

A refresh of the cache produces the following URLs
```
10.1.X.X - - [11/Dec/2017:14:18:46 +1000] "GET /api/v3/projects?per_page=100&private_token=XXXX HTTP/1.1" 200 53129 
10.1.X.X - - [11/Dec/2017:14:18:46 +1000] "GET /api/v3/projects/335/repository/files?file_path=style.css&ref=master&private_token=XXXX HTTP/1.1" 200 700 
10.1.X.X - - [11/Dec/2017:14:18:46 +1000] "GET /api/v3/projects/335/repository/tags?private_token=XXXX HTTP/1.1" 200 2 
```

However, an attempt to update a theme, or install a theme, produces no log lines.

I'm not sure why the WP Core functions wouldn't like the domain, unless it overrides the DNS server?

**Comment by timwsuqld** [comment]
Hmmm. https://www.emanueletessore.com/wordpress-download-failed-valid-url-provided/ seems to hold the answers.

How annoying. Might be worth adding something in the Wiki about local IP's for GitLab.

**Comment by timwsuqld** [comment]
https://wordpress.org/plugins/wp-allow-hosts/ is a plugin that makes this easy

**Comment by afragen** [comment]
Does that mean you've gotten it to work?

**Comment by timwsuqld** [comment]
@afragen yes, once I put wp-allow-hosts in, it works. It seems the internal code looks at the IP, see's it's an "internal" IP and then rejects the url completely.
