### ISSUE TITLE
GitHubupdater keeps overwriting his own settings

### ISSUE THREAD

**Issue by ivan133** [afragen/github-updater#637]
Hi!
Recently I installed github updater on my new site (version was 7.4.4).
WP version 4.9.1.
I'm using github updater with several private bitbucket repos.

But when I encountered several issues.
If I go read settings of github-updater normally I got:

`wp option get github_updater --format=json`
`{"db_version":7400,"bitbucket_username":"user","bitbucket_password":"pass","wppizza":"1","wppizza-add-ingredients":"1","wppizza-delivery-by-postcode":"1","growapp-restaurant":"1","github_access_token":"","github-updater":""}`

But when I clear github updater cache or if I reinstall one on above plugins the settings are rewritten and I can't update plugins

`{"db_version":7400,"bitbucket_username":"user","bitbucket_password":"pass","github_access_token":"","wppizza-add-ingredients":"1","current_branch_wppizza-add-ingredients":"master","branch_switch":"","wp-english-wp-admin":"","github-updater":"","wppizza":"","wppizza-delivery-by-postcode":""}
`
For example wppizza-add-ingredients is missing here.

To fix it I have to set them manually with:

`wp option update github_updater '{"db_version":7400,"bitbucket_username":"user","bitbucket_password":"pass","wppizza":"1","wppizza-add-ingredients":"1","wppizza-delivery-by-postcode":"1","growapp-restaurant":"1","github_access_token":"","github-updater":""}' --format=json`

I rolled back to 7.4.3  but it didn't help.

It works ok on other sites but all of them are using no more than one plugin, while this site uses 3 plugins and custom theme.

**Comment by afragen** [comment]
Can you provide a screenshot of your Bitbucket Settings tab both before and after using Refresh cache?

The refresh cache does not hit the API immediately, it runs under WP-cron.

**Comment by ivan133** [comment]
Before "Refresh Cache"
![github updater settings sandbox wordpress 1](https://user-images.githubusercontent.com/4018236/35425324-14a0803c-026b-11e8-97b4-f1c67e10c599.png)

After

![github updater settings sandbox wordpress 2](https://user-images.githubusercontent.com/4018236/35425331-288e192e-026b-11e8-8eb5-6e8b4b1ef0c1.png)

if I go to bitbucket tab I see all my plugins, but they are marked as publuc
![github updater settings sandbox wordpress 3](https://user-images.githubusercontent.com/4018236/35425365-5d4513ac-026b-11e8-9c20-5319879ade76.png)

Sometimes marking them as private helps, sometimes not

**Comment by afragen** [comment]
What you are seeing is that checking the APIs now runs in wp-cron. As such it doesn't run immediately but does return your browser to a useable state very quickly. Browse around and check back, then everything should be loaded.

https://github.com/afragen/github-updater/wiki/Background-Processing

**Comment by ivan133** [comment]
Great advice, but sadly I'm still stuck
![268170e10693180db6b9f2f83deb4235 1](https://user-images.githubusercontent.com/4018236/35425852-65eb6a84-026f-11e8-9f04-ef7883d3d547.png)

I still can't update  got "message": "Plugin not found or not updatable with GitHub Updater: new_salon", message

And after some time github_updater option reverts to credentials only data:

{"db_version":7400,"bitbucket_username":"login","bitbucket_password":"****"}

**Comment by ivan133** [comment]
Can I somehow make githubupdater to "scan" plugins?

**Comment by afragen** [comment]
GHU is opt-in by the developer as they must include a proper header, eg `GitHub Plugin URI`, for GHU to _see_ it.

All that being said, take a look at https://github.com/afragen/github-updater-additions

**Comment by afragen** [comment]
At the end of the above wiki page there’s a reference to a filter to bypass the wp-cron updating. Using this in combination with Query Monitor can help with troubleshooting.

**Comment by afragen** [comment]
What you’re seeing regarding _disappearing_ settings is the internal cleanup when GHU discovers a plugin is no longer present. It determines this if it doesn’t _see_ it any more.

**Comment by afragen** [comment]
@ivan133 is this still an issue or has it been solved?

**Comment by afragen** [comment]
What version are you using?

**Comment by afragen** [comment]
You can add the following filter to bypass background processing. It may help while we’re trying to solve the issue.

`add_filter( 'github_updater_disable_wpcron', '__return_true' );`

Can you replicate in a local environment?
Can you give `afragen` `read-only` privileges to those repos so I can test locally?

**Comment by afragen** [comment]
Can you test with the latest `develop` branch and see if this still exists?

**Comment by mediaformat** [comment]
I'm on a local environment, and my plugin I'm trying to update is on bitbucket (private repo).

Similar to above, going directly to settings page `settings.php?page=github-updater` shows no Github or Bitbucket tabs.

I have tested with the lastest dev (branch switched).
After `Refresh Cache`, my plugin is recognized, but has Waiting for WP-Cron to finish icon.
Browsing `localhost/wp-cron.php`  has no effect.

Adding `add_filter( 'github_updater_disable_wpcron', '__return_true' );` changes the status to the red icon (This repository has not connected to the API or was unable to connect).

**Comment by afragen** [comment]
Latest release should also work.
