### ISSUE TITLE
impossible to check version

### ISSUE THREAD

**Issue by CaporalJuju** [afragen/github-updater#638]
I can install theme with the plugin. But i dont view version or theme in setting after install.

Also i don't view bitbucket tabs.
![fireshot capture 155 - reglages de github updater synaps _ - http___synaps-theme devnuvo com_wp](https://user-images.githubusercontent.com/34747138/34266424-03775212-e647-11e7-8ce3-576e30979fdf.png)

my theme header : 
/*
Theme Name: Synaps
Author: the Synaps team
Author URI: http://ardecom.com/
Version: 1.2.3
Bitbucket Theme URI: https://bitbucket.org:netnuvo/synaps
Bitbucket Branch:    master

do you have a solution ?
thanks

**Comment by afragen** [comment]
Just looking at the headers the URI for the Bitbucket Theme URI is incorrect. You have a colon separating the host and owner. It should be as follows:

`Bitbucket Theme URI: https://bitbucket.org/netnuvo/synaps`
