### ISSUE TITLE
How do I get my theme to update? - Documentation is unclear

### ISSUE THREAD

**Issue by olafghanizadeh** [afragen/github-updater#639]
Hello. I have a Wordpress-theme in a private bitbucket repo. I would like this to update and reflect on my production site whenever I commit and push to remote master. How do I do this? I'm able to install my theme through the menu in Wordpress, but it does not pull from the repo when there is a commit.

**Comment by afragen** [comment]
Can you provide the theme’s headers?

**Comment by olafghanizadeh** [comment]
Headers as in style.css?

```
/*
 Theme Name:   Best i Test
 Theme URI:    N/A
 Description:  Best i test custom theme - Generatepress Child Theme
 Author:       Olaf Ghanizadeh
 Author URI:   N/A
 Template:     generatepress
 Version:      0.1
 Bitbucket Theme URI: https://bitbucket.org/olafghanizadeh/best-i-test-theme
*/
```

style.css is in the root yes.

**Comment by afragen** [comment]
It all looks ok. Can you give `afragen` `read` access to the repo so I can test?

**Comment by olafghanizadeh** [comment]
I tested some more and it seems like I have to update the version number for it to catch it as an update? Does it only check against the version number and not recent commits?

**Comment by afragen** [comment]
If you use a webhook as described in the wiki you can set to update against every new commit, by default the version number must increment.
