### ISSUE TITLE
Bitbucket theme update option not found

### ISSUE THREAD

**Issue by blbwd** [afragen/github-updater#641]
I have a theme hosted in Bitbucket private repository. I want to send update notification on my WordPress website once I push commit on my master branch on Bitbucket repository. In this plugin settings I can not see any option for 'Bitbucket'. I am using latest version of the plugin (7.4.4). 
In your wiki you showed option to put bitbucket username and password but in latest version there is nothing. Please suggest.

**Comment by afragen** [comment]
Can you provide a list of you theme’s headers? Have you included a `Bitbucket Theme URI` header?

**Comment by blbwd** [comment]
In my style.css file I have included this. 

/*
Theme Name: MPG Travels 2018
Theme URI: https://bitbucket.org/wdrtyz/mpgtrvel
Description:  MPG Travels 2018 WordPress Theme
Version: 1.0.1
Author: Wavesdream
Author URI: http://www.wavesdream.com/
Tags: white, black, custom header, fixed width, two columns, widgets, fully responsive
*/

**Comment by afragen** [comment]
Please refer to the wiki. https://github.com/afragen/github-updater/wiki/Usage

The reason nothing is happening is because you don't have the required header. You must include a `Bitbucket Theme URI` header.
