### ISSUE TITLE
Github plugin tag not seen (change in api.wordpress.org ?)

### ISSUE THREAD

**Issue by comptoirdesappli** [afragen/github-updater#643]
Hi, I released a tag for my plugin (https://github.com/comptoirdesappli/amapress) on github yesterday and I don't see any update notification on a website it is installed in. 
My plugin is not in `Wordpress.org`. Also, I see that my plugin is seen as if it was on wordpress.org.

After investigating it seems that `api.wordpress.org` return `{"error":"Plugin not found."}` with `200 ` status instead of an `empty result` or `404`.

You can see it for example : [https://api.wordpress.org/plugins/info/1.1/?action=plugin_information&request[slug]=amapress](https://api.wordpress.org/plugins/info/1.1/?action=plugin_information&request[slug]=amapress)

I modified get_dot_org_data in `API.php` :

`$response = ! empty( $response ) && empty( $response->error ) ? 'in dot org' : 'not in dot org';`

And now, I can see my plugin update.

Probably, it may be needed to also check that response is an object.

Thanks,

Guillaume Legrand

**Comment by afragen** [comment]
Let me take a look at this and I’ll report back. I wonder if the API response changed.

**Comment by afragen** [comment]
@comptoirdesappli thanks for the heads up! Fixed in https://github.com/afragen/github-updater/commit/27c9ef1308ae1be670321ec1cbb8d16796324415
