### ISSUE TITLE
Bitbucket Password field is plain text

### ISSUE THREAD

**Issue by henrywright** [afragen/github-updater#646]
When I type my password in the Bitbucket Password field under Settings > GitHub Updater > Install Plugin, everyone in the room can see it.

Note Remote Repository Host has to be set to "Bitbucket" so that you can see the field.

**Comment by afragen** [comment]
If you can’t see what you’re typing how do you know if you’ve entered the correct password?

After entering the username/password, it is saved and not asked for again.

Additionally, you can create a read-only password in Bitbucket and use that.

Do you have any thoughts on what you’d like to see here?

**Comment by mediaformat** [comment]
A common enough UI pattern is to show only the last typed character. 
See: [https://github.com/source2git/YouShallPass/](https://github.com/source2git/YouShallPass/)

But the input type password exists for a reason as well, and I imagine if the password is wrong, an error message would be shown and the user would be able to retry...

Great plugin btw!

**Comment by afragen** [comment]
Seems reasonable enough and should be straightforward. Stay tuned, as I’m not sitting in front of my personal computer at my day job it might be a few days.

**Comment by afragen** [comment]
The `develop` branch has these fixes. LMK what you think.

**Comment by henrywright** [comment]
@afragen I think using password as the field type is a good idea. ac9ec24 looks good
