### ISSUE TITLE
Updating from Bitbucket doesn't work

### ISSUE THREAD

**Issue by stevenkellow** [afragen/github-updater#647]
There doesn't appear to be any clear update process for Bitbucket, and using the Install Plugin feature fails with the following message:
---

Downloading install package from https://bitbucket.org/{username}/{repo}/get/master.zip…

Unpacking the package…

Installing the plugin…

Destination folder already exists. /{host}/wp-content/plugins/{repo}/

Plugin install failed.

**Comment by afragen** [comment]
Can you describe your installation? This doesn’t normally happen and seems like there’s a problem with the WP setup. 

Can you replicate this locally?

**Comment by afragen** [comment]
Closed for lack of activity. If this still exists, please reopen
