### ISSUE TITLE
Support for repository subfolders

### ISSUE THREAD

**Issue by emirpprime** [afragen/github-updater#648]
Hi,

Would it be possible to support repository sub-folders?

My use case is particularly for plugins where we I have repositories that group related plugins.
I also have some that contain a theme and custom plugins required for it.

It would be great if a subfolder could be specified when remote installing / in headers. I realise this would mean pulling in the whole repository zip, then moving out the relevant subfolder - but that's not a problem for me at least.

What do you think?

Thanks.

**Comment by afragen** [comment]
[GitLab Groups](https://about.gitlab.com/features/subgroups/) is what you’re really looking for and GitHub Updater does support them. This is not available for either GitHub or Bitbucket at this time and only works because GitLab treats groups and subgroups as individual repositories.

**Comment by emirpprime** [comment]
To be honest I was thinking more of a 'hack':
- pulling down the zip of the whole repository to the tmp location (presuming this is what this plugin does),
- expanding it,
- moving just the selected subfolder to the destination directory
- deleting the zip and expanded folder from the tmp location
I presume this would mean that, should there be more than one plugin / theme / combination in a repository, you can only have one version number for them all. 

I realise this is probably a niche case - but I thought it worth asking / suggesting. It's the one feature another similar plugin has that this doesn't - but this one has a lot of others so i'll be sticking with this regardless!

**Comment by afragen** [comment]
This has everything to do with how GitHub and GitLab work as opposed to how GHU works. In GitHub a download URL that creates a zip file is the entire repository. GitLab Groups allows for each repository in a group to downloaded individually.

Much of the reason that GHU does very well with WP updates is that the function of bringing the zip down and processing it is entirely core’s function. GHU does a lot of renaming after the fact to account for the download but even that is from a hook in core.

You should really try GitLab Groups. I think it has exactly what you’re describing and does work with GHU.

**Comment by emirpprime** [comment]
Thanks for the detailed explanation @afragen! I'll have a good look at GitLab and see if it would be practical to switch.
