### ISSUE TITLE
Plugin is unable to connect to github API

### ISSUE THREAD

**Issue by majiix** [afragen/github-updater#653]
Hi,
Installation of plugin or theme works perfect with private access token. But after installing, update is not working and in setting's page under github tab there is a red warning icon next to the name of plugins and themes with this tooltip: "This repository has not connected to the API or was unable to connect.".
I changed private token. Deactivated and activated the plugin. But nothing make it works. even for public repositories. My Wordpress is on VPS. What is the reason of this problem? Can it be because of firewall? any special port that i may not know?

**Comment by afragen** [comment]
It’s more likely that wp-cron hasn’t run the API  checks. Give it a minute and refresh the page. You can add a filter to bypass wp-cron. Look in the wiki for the filter.

**Comment by afragen** [comment]
The tooltip is changed in the `develop` branch to indicate waiting for wp-CRON to finish.

**Comment by majiix** [comment]
Although that was a good idea, but it remind me that there must be some problem with wp-cron. So after many server checks i found this issue: "cURL error 7: Failed to connect to ... port 443: Connection refused".
And that was because of using Cloudflare SSL and no local SSL. After installing let's encrypt on server every thing was fixed and the issue is resolved.
