### ISSUE TITLE
Force update?

### ISSUE THREAD

**Issue by ykukuych** [afragen/github-updater#655]
I'm using GitHub Updater plugin 7.5.0 to update my plugin located on BitBucket.
My plugin have correct url in header ( * Bitbucket Plugin URI: https://bitbucket.org/ykukuych/plugin-plugin).
Does GitHub Updater support pressing force update button in admin panel?
I am pushed new version of my plugin to bitbucket, but don't see any notification that update available.

**Comment by afragen** [comment]
You may force an update by using the _Refresh Cache_ button in the Settings. API calls are cached for 12 hours so that may be why you don’t yet see a notification.

**Comment by ykukuych** [comment]
i tried next:
1) latest version of my plugin installed
2) i commit new version to bitbucket
3) pressed Refresh Cache button

Expected result: get notice about new plugin version
Got: no notice

I tried this on exist site and also create new local site and test on it. Same result for both sites.
Also as small feature request: can be cache refreshed automatic after hit force update button in Updates section?

**Comment by afragen** [comment]
API calls are very time expensive and I believe that using the _Check Update_ button would cause some confusion and lead to additional overhead.

You can edit the code to change the timeout, but it will be overwritten with any update. https://github.com/afragen/github-updater/blob/f446ec3f02f6d83491bd8c4998b0310b287f8629/src/GitHub_Updater/API.php#L38

If you want a continuous updating workflow you can consider using a webhook. https://github.com/afragen/github-updater/wiki/Remote-Management---RESTful-Endpoints#restful-endpoints-for-remote-management
