### ISSUE TITLE
Fatal error: Uncaught Error: Maximum function nesting level of '5000' reached, aborting!

### ISSUE THREAD

**Issue by danieldekay** [afragen/github-updater#656]
When trying to access /wp-admin/update-core.php I get a white page. Enabling WP_DEBUG and displaying the error message I get the following:

`Fatal error: Uncaught Error: Maximum function nesting level of '256' reached, aborting!`

Increasing the nesting level in `wp-config.php` via

`ini_set('xdebug.max_nesting_level', 5000);`

does not help.
it is stuck here, and loops through the latter lines...

> 0.5426   12124688   6. Fragen\GitHub_Updater\Settings->page_init() /public/wp-includes/class-wp-hook.php:286
    0.5440   12132872   7. Fragen\Singleton::get_instance() /public/wp-content/plugins/github-updater/src/GitHub_Updater/Settings.php:351
    0.5440   12133768   8. Fragen\GitHub_Updater\API\GitLab_API->__construct() /public/wp-content/plugins/github-updater/src/Singleton.php:47
    0.5440   12134144   9. Fragen\GitHub_Updater\API\GitLab_API->set_default_credentials() /public/wp-content/plugins/github-updater/src/GitHub_Updater/API/GitLab_API.php:58
    0.5446   12138776  10. Fragen\GitHub_Updater\Messages->create_error_message() /public/wp-content/plugins/github-updater/src/GitHub_Updater/API/GitLab_API.php:77
    0.5446   12138816  11. Fragen\Singleton::get_instance() /public/wp-content/plugins/github-updater/src/GitHub_Updater/Messages.php:67
    0.5446   12139712  12. Fragen\GitHub_Updater\API\GitLab_API->__construct() public/wp-content/plugins/github-updater/src/Singleton.php:47
    0.5447   12139448  13. Fragen\GitHub_Updater\API\GitLab_API->set_default_credentials() public/wp-content/plugins/github-updater/src/GitHub_Updater/API/GitLab_API.php:58

**Comment by afragen** [comment]
Which branch and version are you using?

**Comment by danieldekay** [comment]
Version 7.5.0.9

**Comment by afragen** [comment]
Can you paste tail of the last 100 or so lines from the PHP error log to a gist?

**Comment by afragen** [comment]
Can you try switching to the `no-backtrace` branch too?

**Comment by danieldekay** [comment]
https://gist.github.com/danieldekay/0b00bdb97a63235ba3ba7c0d64c54e87

**Comment by afragen** [comment]
Can you try switching to a default theme and removing any GitLab plugins?

**Comment by danieldekay** [comment]
Don't know how to switch to the `no-backtrace`branch. Can't activate the plugin because of the error.

**Comment by afragen** [comment]
Try switching to a default theme and removing any GitLab plugins first.

**Comment by danieldekay** [comment]
OK, I did the following:
1. Activate Debug Mode
1. Deactivate all plugins
2. Switch to Twentyseventeen
3. Activate Github-Updater

Here's the debug.log when activating github-updater

> [07-Mar-2018 12:36:43 UTC] PHP Fatal error:  Uncaught Error: Maximum function nesting level of '256' reached, aborting! in /home/dk/domains/tangomarathons.com/public/wp-includes/load.php:796
Stack trace:
#0 /home/dk/domains/tangomarathons.com/public/wp-includes/load.php(828): is_multisite()
#1 /home/dk/domains/tangomarathons.com/public/wp-includes/option.php(1186): get_current_network_id()
#2 /home/dk/domains/tangomarathons.com/public/wp-includes/option.php(1109): get_network_option(0, 'ghu-94615ed13c0...', false)
#3 /home/dk/domains/tangomarathons.com/public/wp-content/plugins/github-updater/src/GitHub_Updater/API.php(318): get_site_option('ghu-94615ed13c0...')
#4 /home/dk/domains/tangomarathons.com/public/wp-content/plugins/github-updater/src/GitHub_Updater/API/GitLab_API.php(51): Fragen\GitHub_Updater\API->get_repo_cache()
#5 /home/dk/domains/tangomarathons.com/public/wp-content/plugins/github-updater/src/Singleton.php(47): Fragen\GitHub_Updater\API\GitLab_API->__construct(Object(stdClass))
#6 /home/dk/domains/tangomarathons.com/public/wp-content/plu in /home/dk/domains/tangomarathons.com/public/wp-includes/load.php on line 796

**Comment by danieldekay** [comment]
https://gist.github.com/danieldekay/38432ca94a31a4fe65f4a7c167a4308a

**Comment by danieldekay** [comment]
Tried to install the no-backtrace branche via `wp plugin install --activate https://github.com/afragen/github-updater/archive/no-backtrace.zip` -- alas, still white page on plugin list (/wp-admin/plugins.php)

**Comment by afragen** [comment]
It’s odd the error seems to be related to getting the cached data from the database. Can you delete all the GHU related data from the database?

Running this plugin should do it. https://github.com/afragen/clear-github-updater-cache

**Comment by afragen** [comment]
Fixed in both `develop` and `no-backtrace` 👍
