### ISSUE TITLE
Can't force updates in background or foreground

### ISSUE THREAD

**Issue by covertnine** [afragen/github-updater#658]
Hey,

We've been using this plugin for awhile now, and as of recently we've been having issues with it not recognizing GitHub theme and plugin updates. It simply insists there is no new version available, even though we have a new version on GitHub, (I committed at least 3 version tags and we're still working off an old one) and the version in the style.css of our theme is much lower than the current GitHub one.

This was working previously on some of our sites with no issues recognizing new theme and plugin updates. But now, no matter what I try (adding the force updates filter, manually clearing out the GitHub cache, and everything listed in the wiki) I still can't seem to get the update notification to show up.

Knowing that this had been working for us previously, and that we're using the latest version of the plugin, (7.5) and we're using all proper WP permissions, is there any possible explanation for why this wouldn't work? I know that we have had some issues with curl on one of our servers, but the only way I can get our themes and plugins from the github repos updated now is by manually using Git from the command line--something that won't work for our maintenance work flow.

Happy to make a donation for the additional support as I have a feeling this is related to our server security setup in some way, but we're at a point here where this works so infrequently the way it should that we may just use git hooks to auto-update our plugins rather than go through the WordPress admin or our maintenance tool, though we'd prefer to have updates show up from within the backend when new ones are available, but can't seem to get that properly working since there aren't any errors about being able to read the repo or anything like that.

We do have HTTP Auth turned on for these sites--not sure if that is a factor or not--but it's hard for me to tell with no errors. We also have a personal access token since our repo is private, and we have the full URLs in our style.css and plugin files since our site is remotely hosted.

I'm happy to provide backend, sFTP or whatever access needed to troubleshoot.

**Comment by afragen** [comment]
Can you share a screenshot of the GitHub tab on the Settings?

Can you share the theme’s headers?

What version of WP?

I might need a `read-only` access token and the repo URI to test locally. Have you tried testing locally?

**Comment by covertnine** [comment]
WP 4.9.4
Zip file includes style.css of the theme and the header.php file

Repo is private, I can grant you access to it. I haven't tested locally--this is on a live development environment I have setup.
![screen shot 2018-03-07 at 6 12 23 pm](https://user-images.githubusercontent.com/10245479/37125623-1a924b5a-2233-11e8-90a5-ef8b25c17524.png)



[Archive.zip](https://github.com/afragen/github-updater/files/1791348/Archive.zip)

**Comment by afragen** [comment]
Read-only access to one of the repos would be helpful. From the screenshot it appears as if everything is normal. But I guess that’s the problem. I’ll try to take a look at it this evening.

**Comment by covertnine** [comment]
I have it running on a development site, would that suffice? What's the best way to privately send that to you?

**Comment by afragen** [comment]
You can email me andy (at) thefragens.com

**Comment by covertnine** [comment]
Problem solved. (Changed the way we did version numbering making it simpler and it worked)

Simpler, semantic versioning and this thing works like a charm. Thanks for the help Andy!
