### ISSUE TITLE
Bitbucket login form fields autofill problem.

### ISSUE THREAD

**Issue by swedishboy** [afragen/github-updater#665]
Hello.

My browser Safari is excellent at filling out my wordpress login data in the form fields automatically everytime I visit the Bitbucket login settings.

This is very irritating since I might accidentally replace the login.
I actually came up with a small hack to stop this from happening (tested in Safari).

If you'd add this to **print_section_bitbucket_username()**

`
<input disabled type="password" size="1" style="background: none; border: 0 none; box-shadow: none; -webkit-appearance: none;" />
`

That will trick Safari at least to not autofill the fields with wp-login data since there are 2 password fields and it finds that odd.

**Comment by afragen** [comment]
Safari has an option not to autofill.

This seems like an issue better handled at the browser level where it appears.

**Comment by swedishboy** [comment]
I don't agree. This is not a login form in that sense and since the password is stored in plain text in the database you might as well let the password field be a text field instead.

Since autofill of passwords is something almost everyone uses and it's on by default in the browser the solution shouldn't be to switch it off (even temporarily).

**Comment by swedishboy** [comment]
I guess though that future versions of GU will use Bitbucket's Auth API? Which means the problem will be gone.

**Comment by afragen** [comment]
I would really prefer to use oAuth but I don’t really know how to add it. Any help would be appreciated.

**Comment by swedishboy** [comment]
Ok. If I have time over I will look into it.

Thanks!

**Comment by afragen** [comment]
I actually change the password field from text to password as a result of several users requesting. I guess they were in open office settings and didn’t want someone looking over their shoulder.
