### ISSUE TITLE
Bitbucket update not working

### ISSUE THREAD

**Issue by FORTE-WP** [afragen/github-updater#667]
Hi Andy! This is the new issue you requested. I installed a test theme on a live website (single, not network) through your plugin (version 7.6.0) from a Bitbucket repository. At first it all seems OK. The credentials are noted, the theme is installed and visible as private. 

![schermopname 4](https://user-images.githubusercontent.com/19216347/38524968-d0b4fd92-3c50-11e8-9982-4149d3d7e121.jpg)

But when I refresh the cache on the Bitbucket tab, the Bitbucket tab disapears.

![schermopname 5](https://user-images.githubusercontent.com/19216347/38524980-ddbc0aee-3c50-11e8-8894-8de957ad109a.png)

When I refresh the cache on the Github Updater tab, the Bitbucket tab reapears again, but without the installed theme.

![schermopname 6](https://user-images.githubusercontent.com/19216347/38525044-21368470-3c51-11e8-8fda-edbda9c397ad.jpg)

I installed the same test theme on another website but with your plugin version 7.4.4. That one is working as expected.

**Comment by afragen** [comment]
Can you let me know the complete list of plugins that you have installed and could you give `afragen` `read` access to the theme?

I may need to install it locally for testing. Thanks.

**Comment by afragen** [comment]
Can you attach the URLs associated with the images please?

**Comment by afragen** [comment]
I think I fixed this in https://github.com/afragen/github-updater/commit/8c2fdd30ff39ddb88d4173e7c2dfcb0d5a6cc28d

**Comment by FORTE-WP** [comment]
I think so too :-) I tested both single and network install. Both are working! Thanks!

**Comment by afragen** [comment]
Excellent! Once you’re satisfied go ahead and close this issue. Thanks for helping.

**Comment by FORTE-WP** [comment]
Great it is working again. Next thursday I want to mention your plugin in a WordPress Meetup talk in Utrecht, the Netherlands. The update feature of a Bitbucket repository is a main topic of the talk. In prepairing for the talk I found the bug. I will be pleased to tell others of your great work! And of your willingness ro resolve bugs this quickly :-)

**Comment by afragen** [comment]
Sounds great! Something about time and having just made a bunch of changes made me focus on where the issue was. It seems that under certain circumstances that I really wasn’t able to replicate, the classes didn’t load before the Settings page loaded. Switching from `class_exists()` to `file_exists()` was key.
