### ISSUE TITLE
BitBucket Tab in Settings does not exist in new installs of this plugin

### ISSUE THREAD

**Issue by Kilmanagh** [afragen/github-updater#670]
I just started using this plugin. This is a **NEW** install with _no previous data_ entered in the WordPress database.

I am using Bitbucket. I was able to make a plugin that I could install plugins from Bitbucket with ease with this plugin.

The issue is that there is no Bitbucket tab on the settings next to GitHub. This makes it impossible to check for updates or stay connected to BitBucket

I have tried the _develop version and the 7.6.1 release_. I have tried **Edge and Chrome**. I have also tried different WordPress websites with different themes as well as a fresh install. All results are the same. 
The screenshot is exactly what I get in all instances. No Bitbucket tab at all. 

I think the issues you have been having extend further than what you thought.

![github](https://user-images.githubusercontent.com/3523109/38712271-88a50c64-3e98-11e8-9fad-6f9af8a57eef.jpg)

**Comment by afragen** [comment]
Can you share the headers of the Bitbucket plugin/theme that you installed?

**Comment by afragen** [comment]
You need to change the header `GitHub Plugin URI` to `Bitbucket Plugin URI`

**Comment by Kilmanagh** [comment]
Not sure how I missed that in the instructions :)
That worked! Thanks!
