### ISSUE TITLE
Unable to see Bitbucket tab

### ISSUE THREAD

**Issue by uitta** [afragen/github-updater#671]
I'm trying to use this plugin, but i'm not able to see the bitbucket tab in the settings page.
This is my header in the style.css file in the child theme.

/*
 Theme Name:   biondo
 Theme URI:    https://www.understrap.com
 Description:  UnderStrap Child Theme
 Author:       Holger Koenemann
 Author URI:   http://www.holgerkoenemann.de
 Template:     understrap
 Version:      0.2.2
 Bitbucket Theme URI: https://bitbucket.org/unit52/biondo
 License:      Commercial
 Text Domain:  understrap-child
 Tags: one-column, custom-menu, featured-images, theme-options, translation-ready

*/

I tried saving and refreshing cache.
Am i missing something?

**Comment by afragen** [comment]
How did you install the theme?

What is is the folder name in `wp-content/themes/`?

**Comment by uitta** [comment]
It's in the themes folder and the name is understrap-child

**Comment by afragen** [comment]
Can you give temporary `read` access to `afragen` for local testing?

**Comment by uitta** [comment]
Actually the website i'm working on is in local...
I'm gonna load it on a testing server later this day... do you need access to wp-admin or ftp access?
Thanks

**Comment by afragen** [comment]
I should only need `read` access to the Bitbucket repository. It should be working in local environment too. What do you use locally?

**Comment by uitta** [comment]
Ah ok.
Actually i didn't push anything on the repository yet, it's empty. I'm just trying to understand how can i use git with wordpress and i was trying your plugin.
Do i need to push before using it?

Also i'm using vagrant (vvv) locally.

Again, thank you, i'm just learning something new....

**Comment by afragen** [comment]
Interesting, I’ve always tested with empty plugins or very simple themes. Can you install `afragen/test-bitbucket-plugin` from the Install tab and see if it works? It’s a public repo.

**Comment by uitta** [comment]
I've tried but it doesn't seem to work.
![schermata 2018-04-18 alle 16 51 50](https://user-images.githubusercontent.com/25509550/38939727-e4187344-4328-11e8-95b8-c6e49804a953.png)
![schermata 2018-04-18 alle 16 51 21](https://user-images.githubusercontent.com/25509550/38939729-e43a3f7e-4328-11e8-9ebc-49f2546a6080.png)

**Comment by uitta** [comment]
damn i'm dumb.... it's a bitbucket repository and not a github.
I tried again but with the same error.

**Comment by afragen** [comment]
Can you screenshot the error?

**Comment by uitta** [comment]
Ok, it's working. 
I uploaded everything online and i was able to download the plugin and see the bitbucket tab.
I then reloaded the vagrant machine and now i can see the tab and can download the plugin.
It was just a vagrant problem, i didn't think of it because i leave it running for days and move from one wifi to another and maybe that was the problem.
Thank you again!!
