### ISSUE TITLE
Gitlab CE/Enterprise Access Token Alert Persists

### ISSUE THREAD

**Issue by evhaddad** [afragen/github-updater#672]
When configuring the plugin, I am prompted to enter a GitLab.com, GitLab CE, or GitLab Enterprise Access Token. However even after entering a Gitlab CE Access Token, the alert does not go away. Is this expected behavior?

<img width="1426" alt="screen shot 2018-04-19 at 12 07 14 pm" src="https://user-images.githubusercontent.com/38531692/39016641-05ec67b6-43ef-11e8-9221-adeadfa238a5.png">

**Comment by afragen** [comment]
Thanks Elizabeth. I’ll look into it.

**Comment by afragen** [comment]
Just making notes as my laptop is in for repairs. ☹️ 

Adjust `Base::get_running_git_servers()` to differentiate GitLab.com and GitLab self-hosted. Then adjust `GitLab::set_default_credentials()`

**Comment by afragen** [comment]
Thanks @pborreli. I do have an idea on how to fix this. It’s just that my laptop is out for repairs at the moment. 😉
