### ISSUE TITLE
Bitbucket, Composer, & MU

### ISSUE THREAD

**Issue by adleviton** [afragen/github-updater#675]
Just in case it helps anyone else:

I installed this plugin via composer as a MU plugin. I kept trying and re-trying to install a theme via a private BitBucket repository and the BitBucket tab would not appear. I read through most of the recent issues on here relating to BitBucket, but nothing helped.

All I did was move the plugin to the regular plugins folder, refresh the plugins page, and things started working. Moved the plugin back to MU and it still seems to be working OK.

**Comment by afragen** [comment]
There are specific instructions on how to set GHU up in the MU folder. https://github.com/afragen/github-updater/wiki/Installation#install-github-updater-as-a-must-use-plugin-optional

Did you do it this way?

**Comment by afragen** [comment]
You **must** install GHU in the standard fashion and then follow the instructions symlinking to the MU folder.

**Comment by adleviton** [comment]
I just found that ... sorry I skimmed right over it. Thanks for getting back to me!

**Comment by adleviton** [comment]
I can't get symlinks to work in MAMP right now, but I copied /mu/ghu-loader.php there and it works. I still have this plugin somehow working in my MU folder; I'll see how far I get with that.

**Comment by afragen** [comment]
You will need to ensure that the directory name is `wp-content/plugins/github-updater`
