### ISSUE TITLE
Installed Theme not showing on Github Tab

### ISSUE THREAD

**Issue by tregenza** [afragen/github-updater#676]
This is probably user error but ...

I have a theme [ https://github.com/tregenza/Tregenza-One ] which I've successfully installed via the GitHub-Updater Install Theme tab but it is not showing up in my Github tab of Installed Plugins & Themes.

I'm expecting it be listed (Github-Updater is listed) so I assuming I have something wrong. 

My Style.css has this header:

```
/*
Theme Name: Tregenza-One
BASED ON Theme-Name: BlankSlate
Theme URI: https://github.com/tregenza/Tregenza-One/
Author: Chris Tregenza (after TidyThemes)
Author URI: http://tregenza.com/
Description: Custom theme developed by Tregenza.com for clients. Based on 4.0.4 Blank Slate theme.
Version: 0.5.1
License: GNU General Public License
License URI: https://www.gnu.org/licenses/gpl.html
Text Domain: tregenza-one
(c) Chris Tregenza
GitHub Plugin URI: https://github.com/tregenza/Tregenza-One/
*/
```
What am I missing?

**Comment by afragen** [comment]
The header should be `GitHub Theme URI` not `GitHub Plugin URI`. 😉

**Comment by tregenza** [comment]
D'oh!

Problem fixed. Thank you for the swift response.
