### ISSUE TITLE
Error message when I'm trying to install a theme.

### ISSUE THREAD

**Issue by jpmelnik** [afragen/github-updater#677]
Notice: wpdb::prepare se llamó incorrectamente. Tipo de valor no compatible (array). Por favor consultá Depurando en WordPress para más información. (Este mensaje se añadió en la versión 4.8.2.) in /var/www/html/local.blog.todobonito.com/wp-includes/functions.php on line 4147

Warning: mysqli_real_escape_string() expects parameter 2 to be string, array given in /var/www/html/local.blog.todobonito.com/wp-includes/wp-db.php on line 1102

Notice: wpdb::prepare se llamó incorrectamente. Tipo de valor no compatible (array). Por favor consultá Depurando en WordPress para más información. (Este mensaje se añadió en la versión 4.8.2.) in /var/www/html/local.blog.todobonito.com/wp-includes/functions.php on line 4147

Warning: mysqli_real_escape_string() expects parameter 2 to be string, array given in /var/www/html/local.blog.todobonito.com/wp-includes/wp-db.php on line 1102
Error en la base de datos de WordPress: [Column 'meta_value' cannot be null]
INSERT INTO `tew_stream_meta` (`record_id`, `meta_key`, `meta_value`) VALUES ('76', 'slug', NULL)

Error en la base de datos de WordPress: [Column 'meta_value' cannot be null]
INSERT INTO `tew_stream_meta` (`record_id`, `meta_key`, `meta_value`) VALUES ('76', 'slug', NULL)

Error en la base de datos de WordPress: [Column 'meta_value' cannot be null]
INSERT INTO `tew_stream_meta` (`record_id`, `meta_key`, `meta_value`) VALUES ('76', 'slug', NULL)

Error en la base de datos de WordPress: [Column 'meta_value' cannot be null]
INSERT INTO `tew_stream_meta` (`record_id`, `meta_key`, `meta_value`) VALUES ('76', 'slug', NULL)

**Comment by afragen** [comment]
I don’t see where any of these errors point back to something in GHU.
