### ISSUE TITLE
Non-consistent branch recognition

### ISSUE THREAD

**Issue by Raruto** [afragen/github-updater#679]
During my tests I noticed a strange behavior, with these plugins: 
- https://wordpress.org/plugins/geoip-detect/
- https://wordpress.org/plugins/html-editor-syntax-highlighter/

## Steps to reproduce:

1. install the above mentioned plugins
2. add the following piece of code
3. visit the plugin page

```php
// GitHub Icon Links Stuff
add_filter( 'extra_plugin_headers', 'GHL_extra_headers'  );

include_once ABSPATH . '/wp-admin/includes/plugin.php';
$plugins = get_plugins();
foreach ( array_keys( $plugins ) as $plugin_basename ) {
	add_filter( "plugin_action_links_{$plugin_basename}", 'GHL_plugin_link', 1000, 4 );
	add_filter( "network_admin_plugin_action_links_{$plugin_basename}", 'GHL_plugin_link' , 1000, 4 );
}

function GHL_extra_headers( $extra_headers ) {
	// Keys will get lost.
	return array_merge(
		$extra_headers, array(
			'GitHubBranch'    => 'GitHub Branch',
			'GitLabBranch'    => 'GitLab Branch',
			'BitbucketBranch' => 'Bitbucket Branch',
		)
	);
}
function GHL_plugin_link( $actions, $plugin_file, $plugin_data, $context ) {
	var_dump( $plugin_data ); // <-- see here.
	return $actions;
}
```
## Actual Results:
**'branch' !== 'GitHub Branch'** (which instead points to the correct branch)
```php
array (size=44)
  'slug' => string 'geoip-detect' (length=12)
  'plugin' => string 'geoip-detect/geoip-detect.php' (length=29)
  'new_version' => string '2.9.0-beta' (length=10)
  'url' => string 'https://github.com/yellowtree/wp-geoip-detect' (length=45)
  'package' => string 'https://api.github.com/repos/yellowtree/wp-geoip-detect/zipball/2.8.2' (length=69)
  'icons' => 
    array (size=0)
      empty
  'branch' => string 'master' (length=6)
  'branches' => 
    array (size=0)
      empty
  'type' => string 'github_plugin' (length=13)
  'Requires WP' => string '3.5' (length=3)
  'Requires PHP' => string '5.4' (length=3)
  'Release Asset' => string '' (length=0)
  'GitHub Plugin URI' => string 'https://github.com/yellowtree/wp-geoip-detect' (length=45)
  'GitHub Theme URI' => string '' (length=0)
  'GitHub Languages' => string '' (length=0)
  'GitHub CI Job' => string '' (length=0)
  'Bitbucket Plugin URI' => string '' (length=0)
  'Bitbucket Theme URI' => string '' (length=0)
  'Bitbucket Languages' => string '' (length=0)
  'Bitbucket CI Job' => string '' (length=0)
  'GitLab Plugin URI' => string '' (length=0)
  'GitLab Theme URI' => string '' (length=0)
  'GitLab Languages' => string '' (length=0)
  'GitLab CI Job' => string '' (length=0)
  'Gitea Plugin URI' => string '' (length=0)
  'Gitea Theme URI' => string '' (length=0)
  'Gitea Languages' => string '' (length=0)
  'Gitea CI Job' => string '' (length=0)
  'GitHub Branch' => string 'geoipv2' (length=7)
  'GitLab Branch' => string '' (length=0)
  'Bitbucket Branch' => string '' (length=0)
  'Name' => string 'GeoIP Detection' (length=15)
  'PluginURI' => string 'http://www.yellowtree.de' (length=24)
  'Version' => string '2.8.2' (length=5)
  'Description' => string 'Retrieving Geo-Information using the Maxmind GeoIP (Lite) Database.' (length=67)
  'Author' => string 'Yellow Tree (Benjamin Pick)' (length=27)
  'AuthorURI' => string 'http://www.yellowtree.de' (length=24)
  'TextDomain' => string 'geoip-detect' (length=12)
  'DomainPath' => string '/languages' (length=10)
  'Network' => boolean false
  'Title' => string 'GeoIP Detection' (length=15)
  'AuthorName' => string 'Yellow Tree (Benjamin Pick)' (length=27)
  'update' => boolean true
```
---

**'branch'** is undefined 
**'GitHub Branch'** (points to the correct branch)
```php
array (size=43)
  'id' => string 'w.org/plugins/html-editor-syntax-highlighter' (length=44)
  'slug' => string 'html-editor-syntax-highlighter' (length=30)
  'plugin' => string 'html-editor-syntax-highlighter/html-editor-syntax-highlighter.php' (length=65)
  'new_version' => string '2.2.3' (length=5)
  'url' => string 'https://wordpress.org/plugins/html-editor-syntax-highlighter/' (length=61)
  'package' => string 'https://downloads.wordpress.org/plugin/html-editor-syntax-highlighter.2.2.3.zip' (length=79)
  'icons' => 
    array (size=3)
      '2x' => string 'https://ps.w.org/html-editor-syntax-highlighter/assets/icon-256x256.png?rev=1669116' (length=83)
      '1x' => string 'https://ps.w.org/html-editor-syntax-highlighter/assets/icon.svg?rev=1669116' (length=75)
      'svg' => string 'https://ps.w.org/html-editor-syntax-highlighter/assets/icon.svg?rev=1669116' (length=75)
  'banners' => 
    array (size=2)
      '2x' => string 'https://ps.w.org/html-editor-syntax-highlighter/assets/banner-1544x500.png?rev=1669110' (length=86)
      '1x' => string 'https://ps.w.org/html-editor-syntax-highlighter/assets/banner-772x250.png?rev=1669110' (length=85)
  'banners_rtl' => 
    array (size=0)
      empty
  'Requires WP' => string '' (length=0)
  'Requires PHP' => string '' (length=0)
  'Release Asset' => string '' (length=0)
  'GitHub Plugin URI' => string 'https://github.com/mukhortov/HESH-WordPress-Plugin' (length=50)
  'GitHub Theme URI' => string '' (length=0)
  'GitHub Languages' => string '' (length=0)
  'GitHub CI Job' => string '' (length=0)
  'Bitbucket Plugin URI' => string '' (length=0)
  'Bitbucket Theme URI' => string '' (length=0)
  'Bitbucket Languages' => string '' (length=0)
  'Bitbucket CI Job' => string '' (length=0)
  'GitLab Plugin URI' => string '' (length=0)
  'GitLab Theme URI' => string '' (length=0)
  'GitLab Languages' => string '' (length=0)
  'GitLab CI Job' => string '' (length=0)
  'Gitea Plugin URI' => string '' (length=0)
  'Gitea Theme URI' => string '' (length=0)
  'Gitea Languages' => string '' (length=0)
  'Gitea CI Job' => string '' (length=0)
  'GitHub Branch' => string 'master' (length=6)
  'GitLab Branch' => string '' (length=0)
  'Bitbucket Branch' => string '' (length=0)
  'Name' => string 'HTML Editor Syntax Highlighter' (length=30)
  'PluginURI' => string 'http://wordpress.org/extend/plugins/html-editor-syntax-highlighter/' (length=67)
  'Version' => string '2.2.3' (length=5)
  'Description' => string 'Add syntax highlighting to the all WordPress code editors using Codemirror.js' (length=77)
  'Author' => string 'Petr Mukhortov' (length=14)
  'AuthorURI' => string 'http://mukhortov.com/' (length=21)
  'TextDomain' => string 'html-editor-syntax-highlighter' (length=30)
  'DomainPath' => string '' (length=0)
  'Network' => boolean false
  'Title' => string 'HTML Editor Syntax Highlighter' (length=30)
  'AuthorName' => string 'Petr Mukhortov' (length=14)
```
## Expected Results:

- '**branch**' key should point to the correct repo.
- there should be always a '**branch**' key 

## Possible Implementations
- re-introduce headers such as "**GitHub Branch**", "**GitLab Branch**" and so on..
- provide classes that allow you to work on plugin's type in a more flexible way (eg https://github.com/Raruto/github-updater/tree/testing/src/GitHub_Updater/Model/Plugin and [guessType()](https://github.com/Raruto/github-updater/blob/f716e57bf3570748d261fd40773f9317a8ab7809/src/GitHub_Updater/Model/Plugin/PluginFactory.php#L71))

---

**PS** these tests were performed in my [testing](https://github.com/Raruto/github-updater/tree/testing) branch (anyway, I have no reason to think that this could affect the final result)

**Comment by afragen** [comment]
Branch headers haven’t existed for several versions. I believe at least v7.0.0. In the current code the branch is designated as `master` by default. Branch headers are implicitly set under the following conditions.

1. The repository is installed via the Install tab and the designated branch is saved to the options.
2. The branch switcher is used.

The above information is documented, https://github.com/afragen/github-updater/wiki/Versions-and-Branches#branch-support

I have no plans on returning the branch headers.

If the branch switch option is selected, the current branch is listed in plugins.php.

**Comment by Raruto** [comment]
as I said, these plugins have been installed by wp.org (and before GHU):
- https://wordpress.org/plugins/geoip-detect/
- https://wordpress.org/plugins/html-editor-syntax-highlighter/

(because both declare a "_GitHub Branch_" header) they are also recognized correctly here:

![github_updater](https://user-images.githubusercontent.com/9614886/39706663-67b5bad4-5212-11e8-9206-96e7b513af63.png)

---

> If the branch switch option is selected, the current branch is listed in plugins.php.

**After enabling** the branch switching option, this is the only recognized repo (installed from GHU and lacking of a "_GitHub Branch_" header):

![plugin](https://user-images.githubusercontent.com/9614886/39706730-9af5c4f2-5212-11e8-9c65-ab4332afc94e.png)
also setting `define( 'GITHUB_UPDATER_OVERRIDE_DOT_ORG', true );` doesn't change this behavior 
for example:
- '**geoipv2**' is the installed branch (not '**master**')
- geoip is not recognized as GHU plugin within the plugins.php page (ie no branch switching)

Just now now I see that this line `'type' => string 'github_plugin' (length = 13)` is present in geoip and not in the HtmlEditorSyntaxHighlighter plugin.

---

**NB** Becasue some plugins doesn't use GHU Headers i think you will need better check the PluginURI Header (some authors puts here their github-repo-url, instead of using the wp.org url). Any way, also for this reason, I suggest you take a look at the guessType function.. 

**PS** not to argue too much, why did you use the plugins.php page for the branch switching?
As I said the other day, I think healthy people use (mainly?) plugins.php page to admin installed plugins (for those who do not have access to wp-cli ... ).
Having these information separated in multiple sub-tabs (github, gitlab, bitbucket, etc. etc.) can become very difficult to manage.
Also, if you enable the `GITHUB_UPDATER_OVERRIDE_DOT_ORG` you find yourself with plugins installed by wordpress but that are automatically updated by GHU (which is ok for me, but i think this information would be better reported in the plugin page since the plugin originally comes from wp. org ..) 
Sorry for the long PS..

**Comment by afragen** [comment]
Those plugins are recognized because they have a `GitHub Plugin URI` header. The `GitHub Branch` header is ignored. 

In the case of GeoIP the branch header is wrong. That branch doesn’t exist on GitHub and if it was used it would return a 404 for the API response. 

The highlighter plugin has other issues. https://github.com/mukhortov/HESH-WordPress-Plugin/issues/52. I don’t think this issue is completely resolved. 

I think you have a misunderstanding of the override constant. It exists if you have a plugin slug that is identical to a slug on dot org that is not the same plugin. Using the override will select your plugin slug over the code on dot org. https://github.com/afragen/github-updater/wiki/WordPress.org-Directory

If plugins don’t use the correct header they aren’t recognized by GHU. In many ways this is “opt-in” by the developer. You can add the header using the https://github.com/afragen/github-updater-additions plugin. 

I put the branch switch data on the plugins page as that’s the page most users would have an expectation of managing their plugins. I see branch switching as just another management job.

**Comment by Raruto** [comment]
From what you have said before they could suffer of a similar issue (as for HESH):
- https://github.com/yellowtree/wp-geoip-detect/tree/geoipv2 
- https://wordpress.org/plugins/geoip-detect/
(different folder names?) however, from what I see the  geoipv2 branch exists (see first link)

---

I think this code snippet can help you mitigating the collision naming issue:

```php
$installed_plugins = get_plugins();
foreach ( $installed_plugins as $plugin_file => $plugin_data ) { 
   is_on_wp_org( $plugin_file );
   ...
}

function is_on_wp_org( $plugin_file ) {
   $on_wporg = false;

   _maybe_update_plugins();
   $plugin_state = get_site_transient( 'update_plugins' );
   if ( isset( $plugin_state->response[ $plugin_file ] )
     || isset( $plugin_state->no_update[ $plugin_file ] )
   ) {
      $on_wporg = true;
   }

   return $on_wporg;
}

}
```

And here is how you can get the wp.org plugin's url

```php
$plugin_state->response[ $plugin_file ]->id
$plugin_state->no_update[ $plugin_file ]->id
```
custom plugins doesn't have an associated **id** or **url** property (because they are not present on wp.org)

---

> If plugins don’t use the correct header they aren’t recognized by GHU. In many ways this is “opt-in” by the developer. You can add the header using the https://github.com/afragen/github-updater-additions plugin.

I know, it was just a suggestion for increase compatible plugins (without forcing an user intervention..)

**Comment by afragen** [comment]
Sorry, I’m on mobile and that view didn’t show all the branches. Given the age of that branch I would posit that it’s quite outdated. Additionally having an incorrect branch header, `geoipv2` in the `master` branch is just plain wrong. 

Developers who have different slugs on dot org and on GitHub are looking for problems if trying to use GHU.

**Comment by afragen** [comment]
I already have a method of checking if a plugin is on dot org. https://github.com/afragen/github-updater/blob/6792173e35e9aa0f26d3fe0fedf83325dc325d12/src/GitHub_Updater/API.php#L335

**Comment by Raruto** [comment]
> I already have a method of checking if a plugin is on dot org. 

Ok, thanks for linking it to me.

---

**just for clarity**, it is correct to say that if you enable the `GITHUB_UPDATER_OVERRIDE_DOT_ORG` you find yourself with plugins installed in wordpress but that are **_always_** updated from GitHub ? (obviously only if they are on GitHub)

**Comment by afragen** [comment]
Yes. This overrides the default behavior which is to prefer an update from dot org. Seeing as dot org is a distribution system. 

For the plugins I have on dot org, I can not use the override and use a non-master branch and GHU will update against that. 

I do not have the override enabled anywhere. It’s only for a specific use case.
