### ISSUE TITLE
Plugin not activating after update

### ISSUE THREAD

**Issue by sreinstein** [afragen/github-updater#681]
Hey there,

After I update my plugin, the plugin doesn't reactivate automatically. Any thoughts?

Running ManageWP with around 200 websites, so this is an issue with managing all of these sites.

Thanks!

**Comment by afragen** [comment]
Which plugin are you referring to?

**Comment by sreinstein** [comment]
It's a plugin that I created - maybe it's missing code that reactivates itself after updating?

**Comment by sreinstein** [comment]
Ah yeah - I actually noticed every time I update the plugin which was installed via GHU the folder name changes. For example, my repo name is mm-plugin, but after my most recent update, it's named:

sreinstein-mm-plugin-6ad588380d16004688f7442f418eaee854cfa1c9

I have a theme installed via GHU that I have no problems running updates on.

**Comment by afragen** [comment]
Yeah, that shouldn’t happen. If updated via GHU it should correctly be renamed. 

Can you give me list of the plugins you have active?

Does this happen every time?

If you use the branch switching you can re-install the current branch and correct renaming should happen. Try it. If it’s not correctly renamed let me know. 

I know lots of questions above.

**Comment by sreinstein** [comment]
I installed through GHU and updated through GHU and it's renaming it every time.

Here are my plugins: https://d.pr/i/pj5pps

I've never used the branch switching before - but obviously not a great solution when managing 200+ websites using the plugin.

Thank you!

**Comment by afragen** [comment]
Do any of your other active plugins do anything with the `upgrader_source_selection` filter hook?

**Comment by sreinstein** [comment]
Just run a find in all files in my plugins directory, your plugin was the only one that returned upgrader_source_selection

**Comment by afragen** [comment]
That’s the hook my renaming code actives on. Not sure why it didn’t fire. 

Did you use the branch switching to reinstall your plugin and get the correct naming back?

**Comment by sreinstein** [comment]
Is it possible because I'm using it for both a theme and a plugin on the same install?

**Comment by afragen** [comment]
Two different repositories so it shouldn’t make a difference. Besides I test with lots of plugins and themes.

**Comment by sreinstein** [comment]
I enabled branch switching, deleted the plugin, reinstalled it via GHU, pushed an "update" to my repo, refreshed the cache, updated the plugin, and it renamed it again.

**Comment by afragen** [comment]
Can you try switching to the `develop` branch of GHU and see if this still happens. 

Just to warn you the `develop` branch is PHP 5.6 or higher.

**Comment by afragen** [comment]
Could you also DM me the URL of the repo and an access token if it’s a private repo?

That way I can test locally.

**Comment by sreinstein** [comment]
Sent, trying develop branch now

**Comment by afragen** [comment]
You didn’t need to delete the plugin. Using the branch switching will reinstall it. It also serves as a renaming test.

**Comment by sreinstein** [comment]
I sent the info to your email - also, I switched to the develop branch, the same renaming issue happened on update.

**Comment by afragen** [comment]
Can you try disabling all other plugins and see if it still happens. Trying to see if there’s a conflict somewhere.

**Comment by sreinstein** [comment]
On develop branch and disabled all other plugins, and it worked just fine. I'm going 1 by 1 and updating after activating each plugin and will let you know which one causes the issue.

**Comment by sreinstein** [comment]
Ok, oddly enough, I deactivated all my plugins and reactivated, pushing an update to my plugin on each step, and now I'm not having the same issue. Things that are different:

1) I switched to the develop branch
2) I had Manage WP checked off in remote management, and I unchecked that

Thoughts?

**Comment by afragen** [comment]
I did find a bug, thanks, but it had to do with storing access tokens.

So using `develop` branch and unchecked ManageWP in Remote Mgmt and everything's fine? Go ahead and check the `ManageWP` option, it shouldn't effect that.

Does the issue persist?

BTW, you don't have to push updates to the plugin. You can simply lower the local version number.

**Comment by afragen** [comment]
Since most remote management tools, like ManageWP don't actually log into the wp-admin to get data from the site. I use that setting to also load GitHub Updater on the `index.php` and `admin-ajax.php` pages. https://github.com/afragen/github-updater/blob/30b7af4a3880ce14f29b750864eab8c5f4c921d8/src/GitHub_Updater/Init.php#L112-L117

**Comment by afragen** [comment]
Let me know if you continue to have issues on the `develop` branch. It should be reasonably stable, but when I push the next release you should switch back to the `master` branch.

I'll let you close this issue if the problem goes away.

**Comment by afragen** [comment]
@sreinstein please reopen this issuing the problem recurs. Thanks.
