### ISSUE TITLE
Feature request: Support for SSH deployment keys

### ISSUE THREAD

**Issue by MatthiasLohr** [afragen/github-updater#682]
Hello,

this seems to be a nice project, unfortunately it's not usable for me. I host some wordpress client templates on a private GitLab instance. Since GitLab Access Tokens always affects a whole user, it's not the desired way of connection between my Wordpress and GitLab.

For this reason i would suggest to add support for SSH keys: Many Git hosting platforms support the creation of deployment keys, SSH keys which have read only access to a single repository. As a "theme update" is actually a deployment, that would also more fit the philosophy of distributed software instead of creating a user for each wordpress instance / theme repository pair.

That would also include #133.

Yes, github-updater (currently) needs HTTP endpoints. So let's just add support for a ssh endpoint. If desired, I also can contribute some code for that.

Best regards
Matthias

**Comment by MatthiasLohr** [comment]
Why does it depend on the WP core? Is it a problem to deliver your own implementation based on http://php.net/manual/en/book.ssh2.php?

**Comment by afragen** [comment]
It depends upon WP core because GitHub Updater relies on WP core methods for updating.

**Comment by afragen** [comment]
GHU does not independently download and install the update. It hooks into WP core letting it know an update is available and using GitHub, etc. own download links to provide the zip file downloads.
