### ISSUE TITLE
Recommendations on updating plugins

### ISSUE THREAD

**Issue by blachawk** [afragen/github-updater#684]
I have a GitHub Plugin for WordPress successfully installed and active based on instructions by github-updater, but what is (are) the recommended approaches to update (or to pull) an existing plugin that has been installed already by github-updater? I'm looking over your documentation but can't find any specific steps.

Many thanks and I apologize in advance if I am overlooking on any of your instructions.

**Comment by blachawk** [comment]
Sure thing, my IT Hub plugin can be [viewed here](https://github.com/blachawk/ITHub).  The only catch is that I just updated plugin to GitHub again after reading your instructions on adding the GitHub Plugin URI.

The header can be [viewed here](https://github.com/blachawk/ITHub/blob/master/ithub-assistant.php)

If you recommend me deleting the plugin from my WordPress site and getting it again now that the GitHub Plugin URI is available, I will do so.

**Comment by blachawk** [comment]
Yes thank you very much.  That has helped me out.

**Comment by afragen** [comment]
Great! Let me know if there’s  anything else I can do.

**Comment by blachawk** [comment]
Good Morning @afragen  I apologize for jumping to conclusions so soon on this request.  I'm still having trouble with getting my plugin to automatically update when I push my changes to my remote repository, unless there is a step i'm overlooking.
 
Within my wordpress environment that my plugin is connected (screenshot below)
![screenshot-github](https://user-images.githubusercontent.com/3985279/40119668-40129b5c-58eb-11e8-8283-4e65ebf2fda4.png)
...And I am also using a token (which is probably unrelated). I also only have a single master branch.

Whenever I do a git push to my remote repository, my plugin on my development server is not automatically updating.  Would you happen to know if there is anything more in your opinion that I should check based on my [plugin header](https://github.com/blachawk/ITHub/blob/master/ithub-assistant.php) or [repository settings](https://github.com/blachawk/ITHub)? 

Many thanks

**Comment by afragen** [comment]
I cache API requests for 12 hours. This can be overridden by using the Refresh Cache button.

The curious thing about the above image is that the GitHub Updater plugin is missing. Can you try using the branch switch to reinstall it?

Your plugin and repository setting appear correct.

**Comment by blachawk** [comment]
Yes you are correct.  By enabling branch switching, I am now able to go my WordPress Plugins page, and re-click on my master branch to get it again.  It's successful for me.  I believe this solves my issue!

**Comment by blachawk** [comment]
So I did it again (while the plugin was deactivated) and it all worked.  I believe I'm good now!

**Comment by afragen** [comment]
The above looks like a permissions issue on your server.

**Comment by blachawk** [comment]
yeah I will look into it and see, but I believe you have helped me reached my goal in this issue.  Many thanks!
