### ISSUE TITLE
Recommendations on next steps in using our access token

### ISSUE THREAD

**Issue by blachawk** [afragen/github-updater#685]
I'm running into a situation with the following error page on my plugins page.
```
GitHub Updater Error Code: 403	
GitHub API's rate limit will reset in 47 minutes.
It looks like you are running into GitHub API rate limits. Be sure and configure a Personal Access Token to avoid this issue.
```
[The github-updater instructions are pretty clear](https://github.com/afragen/github-updater/wiki/General-Usage) on getting a token from GitHub.  I have a generated token, and followed all the instructions [here](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/).  

I've been working all day, but the error occurred just recently after I installed my GitHub plugin through github-updater, all on a development server I have access to.

What do I specifically do my GitHub token so that I can continue to install/update my custom plugins through github-updater as often as I like? I need more examples than just the command line to clone...

From the command line, I already have my repository settings set to SSH and that is validated.  I just don't know where to stick my token so that GitHub does not complain as I continue to push and pull.

Many thanks!

**Comment by blachawk** [comment]
Ahh - I now see that I have to see HTTPS, and not SSH if I wish to continue down this road...

**Comment by afragen** [comment]
There’s a spot for it on the GitHub tab of the Settings page.

**Comment by afragen** [comment]
SSH is not the same.

**Comment by blachawk** [comment]
Once again sir, you save my day.  Many thanks!

**Comment by afragen** [comment]
You are quite welcome.
