### ISSUE TITLE
Change Request: Better Feedback to Users

### ISSUE THREAD

**Issue by tregenza** [afragen/github-updater#687]
GHU provides very little information to the user about it's activity and status which makes identifying problems difficult. The information which is provided is on the Theme pages which isn't an intuitive place to look. 

Proposed Changes:

* On the Github (and similar) tabs display the following next to the names of the themes/plugins:  ** Current installed version number
** date / time of last update
** date / time GHU last checked the source for updates
** which branch GHU is checking.

* Record activity to debug when Wordpress' debugging is enables including:
** Date / Time GHU checks Github
** Parameters passed to Github 
** Github's Response
** Error messages relating to timeouts, errors writing files, bad passwords etc

**Comment by afragen** [comment]
The information regarding branch switching is on the page/card where the plugin/theme actions (activating, deactivating, and deleting) occur. Branch information is present in these locations when the branch switching option is checked.

Debugging is best done outside of WP-Cron. Setting the filter
```php
add_filter( 'github_updater_disable_wpcron', '__return_true' );
```
 using the Query Monitor plugin, and setting 
```php
define( 'WP_DEBUG', true );
```
are the best methods of detecting any issues.

Much of the rest is truly information overload and any developer who really needs this information can step through the code to find it. The exact time of the last check is somewhat irrelevant as the user can easily refresh the cache forcing new API checks.

There are already admin notices for bad passwords, timeouts, and other errors.

**Comment by tregenza** [comment]
Take it from a new user - there is no information overload.

As it is, GHU fails silently. I had an incorrect firewall and GHU was failing to connect to Github  and there was no indication at a user level to tell me it had failed or why. Displaying all the relevant information on the GitHub tab, the logical place for a user to check for it, would at least give me a starting point to finding the problem. As a developer, I don't want to be stepping through someone else's code just to do basic trouble shooting.

Case in point, I'm still having problems.

On the Theme's detail page, it is telling me there is an update available (which is correct) - installed version 0.5.9, Github version 0.5.91. 

Click the Update option and it says Updating ... then Updated. After refreshing the themes page, it still says 0.5.9 installed and update available. Checking the themes files, 0.5.9 is still installed. 

Wp-Cron is disabled (as per your instructions) and debug is on (this is my test environment so it is always on).

There are no messages in Debug.log (other than my normal junk) and no on-screen messages about why it has failed to update. 

I have Query Monitor installed but cannot find nothing meaningful other than a few DB queries by GHU.

Where do I start looking for the problem?

**Comment by tregenza** [comment]
Thanks as ever for the swift response, however ...

I was aware of the tag requirement but GHU reported that an update was available and went through the motions of downloading, and reported it was installed correctly. Which is pretty misleading if it required a tag release. 

For tag releases, it should not say there is an update available unless there is something there it is willing to download & install.

Also - I'm still seeing nothing from GHU in my debug.log

**Comment by afragen** [comment]
There's nothing in debug.log because there were no errors. GHU is working as it should using all the information that you, as the developer, has provided.

GHU looks to the current branch on GitHub for the current version number. If that version number is higher than the local version number, an update shows as available.

If the developer, you in this instance, tags their releases, but forgets to tag the current release and has already committed a version bump and the current branch is `master`, then the update cycle will viscously repeat.

This is clearly documented, https://github.com/afragen/github-updater/wiki/Versions-and-Branches#tagging

If you don't wish to tag your releases there are 2 choices.

1. Delete all the current tags.
2. Use a branch other than `master` and only push and tag to `master` at the same time.

**Comment by tregenza** [comment]
I had read that and the phrase 'circle of updating may ensue' did not describe the behaviour I was seeing. I've updated the wiki with a fuller description of GHU's behaviour.

I assume there there is a good reason why GHU doesn't just check for version updates by comparing tagged releases rather than the checked-in code? It's counter-intuitive to check for a version number in one place and then update from another.

**Comment by afragen** [comment]
I’m sorry I reverted your wiki changes. The information is all there on the page and I’d rather have the wiki reflect my voice and style.

If you wish to create an issue for the wiki page that might be better.

Using tags is a feature of GitHub, etc and GHU supports updating against this feature. GHU tries to follow the Git Flow style in this regard.

https://nvie.com/posts/a-successful-git-branching-model/

**Comment by afragen** [comment]
I have updated the wiki. Does it make more sense?
