### ISSUE TITLE
Bitbucket username/password instructions do not apply to multisite

### ISSUE THREAD

**Issue by nickbreen** [afragen/github-updater#689]
In the [Set the username and password Options for the Bitbucket Account](https://github.com/afragen/github-updater/wiki/WP-CLI#set-the-username-and-password-options-for-the-bitbucket-account) section add an example for multisite installs which need to use `network meta` rather than `option`. E.g.

```
wp --user=1 network meta update 1 github_updater --format=json '{"github_access_token":"qwerty","bitbucket_username":"asdf","bitbucket_password":"foobarbaz"}'
```

**Comment by afragen** [comment]
I've updated the wiki.
