### ISSUE TITLE
Bitbucket Tab Not Showing in Settings

### ISSUE THREAD

**Issue by geckomist** [afragen/github-updater#691]
After installing the plugin, the bitbucket tab is not showing.

I can find the page by going to the plugin settings, selecting Github, then replace github with bitbucket at the end of the URL.

![screen shot 2018-06-06 at 9 53 59 am](https://user-images.githubusercontent.com/18336484/41042451-ba850db8-696f-11e8-9d9a-e8482f282c5e.png)

**Comment by afragen** [comment]
Can you try the `develop` branch and see if this issue persists?

**Comment by geckomist** [comment]
The developer branch actually gave me this error:
![screen shot 2018-06-06 at 10 11 16 am](https://user-images.githubusercontent.com/18336484/41043728-8e76e8ec-6972-11e8-8313-8d3973c46fd8.png)

Including the Bitbucket Plugin URI to my custom plugin did make the tab show. I must've missed this in the wiki. I assume the github one shows by default because the plugin itself is using the updater.

**Comment by afragen** [comment]
Can you describe your installation and what you did when you got the PHP fatal?

**Comment by geckomist** [comment]
I use MAMP for development on custom plugins and testing with WP 4.9.6.

To Install the develop branch of the plugin I deactivate then deleted the current plugin, then downloaded the develop branch, removed -develop from the folder name and dropped it into my plugins folder. Then activated it to get the error.

I created a fresh install of WP and tested activating the plugin and had no errors.

**Comment by afragen** [comment]
You do realize there's a branch switcher built in to GitHub Updater 😉 

I'll see if I can reproduce. Thanks for the report.

**Comment by geckomist** [comment]
I do. I'm just in the habit of doing it the general WP way.

**Comment by afragen** [comment]
Hmm, couldn't replicate.
