### ISSUE TITLE
JS error: Can't find variable: jQuery

### ISSUE THREAD

**Issue by picasso** [afragen/github-updater#692]
I see this error on front-end when I logged out.

1. Why do I need any GHU JS on front-end?

2. The error occurs because the script is added before the JQuery which is moved to the footer on this site.

![screen-shot-js](https://user-images.githubusercontent.com/399395/41052955-9ca222fe-69ba-11e8-80b6-9da1fbeb806f.jpg)

GHU Version 7.6.2.20

**Comment by afragen** [comment]
I didn't realize it was loading on front-end, sorry. Fixed https://github.com/afragen/github-updater/commit/633056bf9d46f210e484b14e97af91108136c45d

**Comment by afragen** [comment]
Better fix, https://github.com/afragen/github-updater/commit/7e7d03f3d7a64df1a3a7111188a896955daaffa2
