### ISSUE TITLE
Feature Request: Updates via SHA

### ISSUE THREAD

**Issue by dovy** [afragen/github-updater#694]
It would be great to run on "SHA" updating instead of just versioning. That way I could commit and get a request.

You could also add in GitHub hooks so we could auto-update. That would make things really nice for a dev world.

**Comment by afragen** [comment]
@dovy take a look at the wiki, https://github.com/afragen/github-updater/wiki/Remote-Management---RESTful-Endpoints#restful-endpoints-for-remote-management

If this doesn’t solve this, let’s talk.
