### ISSUE TITLE
Minor bug and suggestion for Localization

### ISSUE THREAD

**Issue by alexclassroom** [afragen/github-updater#697]
1. In Messages.php Line 122, there is missing a ">" character.
Original: It looks like you are running into GitHub API rate limits. Be sure and configure a <a href="%s"Personal Access Token</a> to avoid this issue.
Correct: It looks like you are running into GitHub API rate limits. Be sure and configure a <a href="%s">Personal Access Token</a> to avoid this issue.

2. Add target="_blank" seems better for external links in UI.

**Comment by afragen** [comment]
Thanks Alex. I’ll get this fixed and a new POT created.

I’m not certain about forcing a new window in the link. It seems the user would have more choice in how to open the link if I don’t force this process.
