### ISSUE TITLE
Have to "update" twice before update message goes away

### ISSUE THREAD

**Issue by petemolinero** [afragen/github-updater#698]
For a while now (months) I've had to click "Update," then refresh the themes page, then click "Update" again in order for the update message to go away. If I only click "Update" once, I get the following behavior. Notice how it shows that my current version is the same as the supposed new version.

![screen shot 2018-07-05 at 2 52 11 pm](https://user-images.githubusercontent.com/1924752/42350074-d0265b9e-8063-11e8-87f9-3c5fb19dece9.png)

Other potentially important things:

- This has happened on ~10 sites that I've used Github updater on (all for themes)
- On all of the sites, I've been using `add_filter( 'github_updater_disable_wpcron', '__return_true' );`

**Comment by afragen** [comment]
I’ve seen this before but never consistently and I’ve never been able to reliably reproduce it. 

It’s really just a cosmetic thing and updating again, though not necessary, seems to make it go away. 

If you can find a way to reliably reproduce it in a local environment I can see about fixing it. Otherwise we may just have to live with it.

**Comment by AiratHalitov** [comment]
After updating **GitHub Updater plugin** cache is not cleared, and GitHub Updater proposes update twice.

![image](https://user-images.githubusercontent.com/4050715/42739123-5024d99e-88aa-11e8-810a-aad3a803fcf9.png)

**Comment by afragen** [comment]
Please let me know if it persists after 24 hours. I think it has something to do with the site’s caching but I am unable to reproduce.

**Comment by AiratHalitov** [comment]
I tried to **refresh cache** manually two times, but GitHub Updater still offers an update to v8.2.0.

**Comment by AiratHalitov** [comment]
> Please let me know if it persists after 24 hours. 

Ok, I'll write to you in 24 hours.

**Comment by AiratHalitov** [comment]
Now everything is good.
