### ISSUE TITLE
Conflict with Theme Switcha

### ISSUE THREAD

**Issue by brownsugar** [afragen/github-updater#699]
Current versions:
- GitHub Updater 8.2.0
- [Theme Switcha](https://wordpress.org/plugins/theme-switcha/) 1.6

Trying to remote update themes using api, but the request query 'theme' conflict with Theme Switcha's theme switching request, so GitHub webhook request will receive a 302 response.
![image](https://user-images.githubusercontent.com/2935980/42751868-c119995e-891e-11e8-9c56-1197452e8a0f.png)

Is it possible to create custom query for GitHub updater?

**Comment by afragen** [comment]
The webhook for GitHub Updater **is** a custom query. Nothing in GitHub Updater will create a 302 response.

A 302 response is a redirect from your server. You will need to take a look into your server logs and config (.htaccess or nginx conf files) to see what’s going on.

You might also want to ask on the Theme Switcha support forum.

**Comment by brownsugar** [comment]
Yeh, I know it's not about GitHub Updater, but if the request's url query contains 'theme' slug like https://example.com/?theme=XXXX, Theme Switcha will handle the request, it sets cookies and 302 redirect to main url(without queries) first, so GitHub Update will not get the request.
What I mean is will GitHub Updater support custom query slug to catch the theme name, for example, '_theme' instead of 'theme', so we can use /wp-admin/wp-ajax.php....&_theme=the_theme_name to avoid conflict.
If can't, I will go to ask Theme Switcha later, thanks.

**Comment by brownsugar** [comment]
Yeh, I know it's not about GitHub Updater, but if the request's url query contains 'theme' key like https://example.com/?theme=XXXX, Theme Switcha will handle the request, it sets cookies and 302 redirect to main url(without queries) first, so GitHub Updater will not get the request.
What I mean is will GitHub Updater support custom query key to catch the theme name, for example, '_theme' instead of 'theme', so we can use /wp-admin/wp-ajax.php....&_theme=the_theme_name to avoid conflict.
If can't, I will go to ask Theme Switcha later, thanks.

**Comment by afragen** [comment]
Using `theme` as a query arg is very generic. There should be something specific to Theme Switcha that ensures it’s not trying to parse and use any other instance of that query arg in a URL during its function.
