### ISSUE TITLE
Github Updater Token Distribution is deprecated since version 6.1.0

### ISSUE THREAD

**Issue by SooBahkDo** [afragen/github-updater#701]
Hello All,

Are there plans to update this?

Objectcomponent: "Plugin: github-updater-develop"file: "wp-includes/functions.php"line: 4104message: "github_updater_token_distribution is deprecated since version 6.1.0! Use github_updater_set_options instead."stack: Array(4)0: "deprecated_hook()"1: "apply_filters_deprecated()"2: "Fragen\GitHub_Updater\Base->set_options_filter()"3: "do_action('init')"length: 4__proto_: Array(0)type: "notice"proto: constructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()defineGetter: ƒ defineGetter()defineSetter: ƒ defineSetter()lookupGetter: ƒ lookupGetter()lookupSetter: ƒ lookupSetter()get proto: ƒ proto()set proto: ƒ proto()
(anonymous) @ query-monitor.js?ver=1527014145:300

Thanks

**Comment by afragen** [comment]
The answer is in the message. Use ‘github_updater_set_options’ filter hook.

**Comment by SooBahkDo** [comment]
Hello afragen,

I saw that, but I am not a coder, so I wondered if someone skilled might perform the update so a new version would be available for those less skilled.

Thanks
