### ISSUE TITLE
personal access token is stuck

### ISSUE THREAD

**Issue by cfoellmann** [afragen/github-updater#702]
I installed the plugin on a site and tried to fetch a plugin from GitLab in a private repo using a personal access token.

1st: I tried to use a deploy token - Failed: No access to the repo (won't work anyway)
2nd: I used a functional token but the install failed because the token I used first got used although I set the right token in the field.

I removed all github updater related options from the options table. This resolved the issue.
But there seems to be a bug.

**Comment by afragen** [comment]
I’m not sure I understand the difference between a deploy token and a functional token.

When you say “fetch a plugin from GitLab”, do you mean install via the Install tab? What was the error?

What settings did you remove? `github_updater*`, or `ghu-*` options?

**Comment by cfoellmann** [comment]
Sorry. Should have made my report simpler.

1. "Install Plugin" tab
2. Set values:
   1. private repo https url
   2. branch to `gh-updater` (my choice here)
   3. select gitlab
   4. insert wrong token
3. Submit
4. error was sth like `not found` - it was a 404 - sorry

Second attempt (now I have a functioning token)
1. "Install Plugin" tab
2. Set values:
   1. private repo https url
   2. branch to `gh-updater` (my choice here)
   3. select gitlab
   4. insert __right__ token
3. submit
4. same error - displayed URL has still the wrong token in it

I deleted both options prefixes-

**Comment by afragen** [comment]
There should absolutely be a GitLab tab, if the plugin has the `GitLab Plugin URI` header.

And yes, there should be a per-plugin/per-theme token if set during the Install.

**Comment by afragen** [comment]
If you give user `afragen` `read` access to the repository I can take a closer look, if needed.

**Comment by cfoellmann** [comment]
now I realize.
My tab situation is because the header was missing. I was under the impression that the header was optional if I installed via the "Install Plugin" tab.

So that one is resolved and maybe the token issue is because of that, too.
Will test

**Comment by afragen** [comment]
GHU is able to install any plugin or theme hosted in any of the supported git hosts. 

GHU requires the header for updating and to be _seen_ by GHU.
