### ISSUE TITLE
WP-Cron does not finish

### ISSUE THREAD

**Issue by maxleistner** [afragen/github-updater#703]
The following message does not stop appearing even after 1h 15 min of waiting and reloading the sites front-end and admin. This happens since the latest commit. Any ideas? 
```
GitHub Updater Information	
Please be patient while WP-Cron finishes making API calls.
```

**Comment by afragen** [comment]
A couple of questions.

Has updating via WP-Cron ever successfully worked for you or is the first time you’ve used the plugin?

If you have previously used GHU successfully, what version was it?

Is something on your server set to disable WP-Cron?

**Comment by maxleistner** [comment]
Thanks @afragen for the fast response. No i did not use the plugin on this site before. 
I tried it on another page and after several hours it updated the repo information, but on this on page the message still does not disappear. 
WP Cron works fine on other tasks.

**Comment by afragen** [comment]
Can you install https://github.com/afragen/github-updater-support ? It adds a couple of other plugins to assist in figuring out the issue. It also overrides the WP-Cron updating which helps in troubleshooting.

**Comment by maxleistner** [comment]
Alright - i get the following error after installing the support-plugin: 
```GitHub Updater Error Code: cURL error 35: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version```

**Comment by afragen** [comment]
Is there an HTTP GET that the error is associated with? It seems like that particular server may have an SSL issue.

**Comment by maxleistner** [comment]
As it seems i might be a problem with cURL and SSL in relationship with an older php version (5.6.10). I will ask the administrator to check the certificate and update to php 7.* 
I will recheck and get back to you. Thanks!

**Comment by afragen** [comment]
Can you share the repo URL?

**Comment by maxleistner** [comment]
https://github.com/hingst/layotter
What do you mean with plugin headers?

**Comment by afragen** [comment]
A link to the repo is fine.

I was able to install and update without any issue. Are you still having issues?

**Comment by blachawk** [comment]
I'm facing this same issue of having the notification show up at the top of my wp-admin windows.  its also preventing me from having options to switch branches.  Is there anyway we can dig in and find out what the technical hold up is?

**Comment by afragen** [comment]
@blachawk I'm attempting to _dig_ into this. Please install the GitHub Updater Support plugin, referenced above and activate it. Activation results in GitHub Updater not using WP-Cron which helps figure out what the actual issue may be.

Specifically, look into Query Monitor HTTP API Calls and the debug.log

Please let me know the results.

**Comment by blachawk** [comment]
Many thanks for investigating this!  The latest wordpress notification that now shows up is...
```
GitHub Updater Error Code: There may be a problem with WP-Cron. A GitHub Updater WP-Cron event is overdue.
```

**Comment by afragen** [comment]
That error usually shows if WP-Cron is  not running on your server. 

https://github.com/afragen/github-updater/wiki/Background-Processing

**Comment by blachawk** [comment]
@afragen I installed the support plugin successfully. But the first notification to pop up once it was active was the following:

> Notice: Undefined index: source in C:\Users\...\wordpress\ithub\wp-content\plugins\github-updater-support-develop\vendor\afragen\wp-dependency-installer\wp-dependency-installer.php on line 427

**Comment by blachawk** [comment]
I discovered the source for the notification.  I had the following setup on wp-config.php file. Once I commented it out, the notification went away.  This was a practice I found online in order to reduce posts from being automatically saved so often.  It's ok in my situation to comment it out...

>  //NFFA- Disable WP Post Revisions
    define('AUTOSAVE_INTERVAL', 600); // seconds to help reduce auto save increments
    define('WP_POST_REVISIONS', 5);

...I'm now waiting to see if the WP cron job will fix itself now and process the way it should...

**Comment by blachawk** [comment]
I believe I found the source of my error with the help of your support plugin.  For some reason, GitHub Updater is tracking the "Search Everything" Plugin, and that is causing the issue.  How do I keep the WordPress "Search Everything" plugin active in WordPress, but remove it from being tracked by the GitHub updater?

Many thanks!

**Comment by afragen** [comment]
Well the Search Everything plugin as an incorrectly set `GitHub Plugin URI`.

https://wordpress.org/support/topic/error-in-github-plugin-uri-header/

If this is causing the issues, I would remove the `GitHub Plugin URI` headers from Search Everything. It doesn't appear that it has been updated recently.

**Comment by afragen** [comment]
> @afragen I installed the support plugin successfully. But the first notification to pop up once it was active was the following:
> 
> > Notice: Undefined index: source in C:\Users...\wordpress\ithub\wp-content\plugins\github-updater-support-develop\vendor\afragen\wp-dependency-installer\wp-dependency-installer.php on line 427

Does this persist?

**Comment by blachawk** [comment]
No it, no longer persists because I removed...
> define('AUTOSAVE_INTERVAL', 600); 

from my wp-config.php file.  which I was using for other purposes.

**Comment by afragen** [comment]
@maxleistner are you still having issues?

**Comment by blachawk** [comment]
No, this issue can be closed.  Thanks for the work-arounds!

**Comment by rob** [comment]
This message constantly shows for us.

We do have cron disabled in `wp-config.php` because we're running it manually via `crontab` on the server. Maybe that's why?

**Comment by afragen** [comment]
@rob take a look at 
https://github.com/afragen/github-updater/wiki/Background-Processing and make sure that you run the cronjob at least once a day.

**Comment by afragen** [comment]
@rob you might want to look at WP-Crontrol to see if there are any other wp-cron issues. 😉

**Comment by afragen** [comment]
@rob could you create a new issue for your particular problem?

**Comment by rafaelurben** [comment]
**For future readers:** I also got this problem, but after activating the debug mode, I realized, that Firefox has put py password in the GitHub-Access-Token field and so there was a wrong token which stopped the update process from working.
