### ISSUE TITLE
E_WARNING: file_get_contents(.../tmp-readme.txt), No such file or directory

### ISSUE THREAD

**Issue by soderlind** [afragen/github-updater#704]
New Relic reports the  E_WARNING below. I also have the issue in #703, maybe they are related? 

Stack trace
```
E_WARNING: file_get_contents(/opt/wordpress/wp-content/tmp-readme.txt): failed to open stream: No such file or directory
in file_get_contents called at /opt/wordpress/wp-content/plugins/github-updater/vendor/class-parser.php (168) 
in WordPressdotorg\Plugin_Directory\Readme\Parser::parse_readme called at /opt/wordpress/wp-content/plugins/github-updater/vendor/class-parser.php (159) 
in WordPressdotorg\Plugin_Directory\Readme\Parser::__construct called at /opt/wordpress/wp-content/plugins/github-updater/src/GitHub_Updater/Readme_Parser.php (43) 
in Fragen\GitHub_Updater\Readme_Parser::__construct called at /opt/wordpress/wp-content/plugins/github-updater/src/GitHub_Updater/API/GitHub_API.php (207) 
in Fragen\GitHub_Updater\API\GitHub_API::get_remote_readme called at /opt/wordpress/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php (314) 
in Fragen\GitHub_Updater\Base::get_remote_repo_meta called at /opt/wordpress/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php (280) in Fragen\GitHub_Updater\Base::run_cron_batch called at /opt/wordpress/wp-includes/class-wp-hook.php (286) 
in WP_Hook::apply_filters called at /opt/wordpress/wp-includes/class-wp-hook.php (310) 
in WP_Hook::do_action called at /opt/wordpress/wp-includes/plugin.php (515) 
in do_action_ref_array called at /opt/wordpress/wp-cron.php (126)
```

**Comment by afragen** [comment]
I think I've gotten this fixed.

**Comment by soderlind** [comment]
excellent, sorry for not providing the info you asked for (summer and different timezone)

**Comment by afragen** [comment]
No problem. I was able to figure it out without it, I think. 😉

**Comment by bishless** [comment]
I realize this issue is old and has been marked 'fixed', but I've been seeing a very similar error on one of my sites for a while: (Haven't been able to nail down what else is happening at the time)

```
[Apr 21, 09:22:08] PHP Warning: file_get_contents(/tmp/c51bc10caf2e7ecfe093be1c1fb8a1fa-tmp-readme.txt): failed to open stream: No such file or directory in /home/beachfle/public_html/wp-content/plugins/github-updater/vendor/afragen/wordpress-plugin-readme-parser/class-parser.php on line 168
[Apr 21, 09:13:47] PHP Warning: file_get_contents(/tmp/eac24bebe3cb212eac1f6e502e5bfffe-tmp-readme.txt): failed to open stream: No such file or directory in /home/beachfle/public_html/wp-content/plugins/github-updater/vendor/afragen/wordpress-plugin-readme-parser/class-parser.php on line 168
[Apr 21, 08:57:16] PHP Warning: file_get_contents(/tmp/eac24bebe3cb212eac1f6e502e5bfffe-tmp-readme.txt): failed to open stream: No such file or directory in /home/beachfle/public_html/wp-content/plugins/github-updater/vendor/afragen/wordpress-plugin-readme-parser/class-parser.php on line 168
[Apr 21, 08:55:20] PHP Warning: file_get_contents(/tmp/c51bc10caf2e7ecfe093be1c1fb8a1fa-tmp-readme.txt): failed to open stream: No such file or directory in /home/beachfle/public_html/wp-content/plugins/github-updater/vendor/afragen/wordpress-plugin-readme-parser/class-parser.php on line 168
```

I'm also seeing this output when I visit my [Redirection](https://wordpress.org/plugins/redirection/) page in the admin:

```
Plugin: 4.7.1
WordPress: 5.4 (single)
PHP: 7.3.16
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
JavaScript: https://beachfleischman.com/wp-content/plugins/redirection/redirection.js
REST API: https://beachfleischman.com/wp-json/

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Raw: <br />
<b>Warning</b>:  file_get_contents(/tmp/c51bc10caf2e7ecfe093be1c1fb8a1fa-tmp-readme.txt): failed to open stream: No such file or directory in <b>/home/beachfle/public_html/wp-content/plugins/github-updater/vendor/afragen/wordpress-plugin-readme-parser/class-parser.php</b> on line <b>168</b><br />
{"items":[{"id":1,"name":"Redirections","redirects":327,"module_id":1,"moduleName":"WordPress","enabled":true,"default":true},{"id":2,"name":"Modified Posts","redirects":39,"module_id":1,"moduleName":"WordPress","enabled":true}],"total":2}
```

**Comment by afragen** [comment]
@bishless can you let me know what version of GHU you are using? I can try putting another check for the success of the `file_put_contents()` of https://github.com/afragen/github-updater/blob/165e6af2f83e21ac42a9566c999f6f8e18db6203/src/GitHub_Updater/Readme_Parser.php#L58 and we can see if that works.

**Comment by afragen** [comment]
@bishless can you test with the `develop` branch v9.5.0.1 and let me know if this still exists.

My problem is that I can't seem to reproduce this error. I'm testing for the file and putting it in that location before calling the `parent::__construct()` for `class-parser.php`

**Comment by afragen** [comment]
@bishless is it possible that you don't have write permissions on the `/tmp/` directory? As I said earlier I'm writing the file to the specified file path immediately before the call to `file_get_contents` so I'm having a difficult time trying to determine precisely what's going on in your site. FWIW I've never been able to reproduce this. 🤷🏻‍♂️

**Comment by bishless** [comment]
Sorry for the delayed response - I'm using 9.5.0 of GHU. And, I checked the perms on `/tmp/` ... 755.

Not quite sure how to test w/ the develop branch. (Sorry)

**Comment by afragen** [comment]
@bishless to test the `develop` branch just check branch switching in the Settings and go to the plugins page. You should see how to do it from there.

**Comment by bishless** [comment]
/facepalm I should have realized it'd be that simple. Sorry.

When I attempted to switch to develop, I got the following error (in Query Monitor):
![screenshot 2020-04-23 at 11 11 04](https://user-images.githubusercontent.com/170618/80134282-66b2e000-8553-11ea-98e6-d3eb49d23c5a.png)

When I look at the Plugins page, it indicates that I'm still on the master branch, but shows 9.5.0.1 as the version. 🤔

How should I proceed?

**Comment by afragen** [comment]
That 400 error is standard for a redirect, don't worry about it.

How much caching do you have in place? The branch should say `develop` and I can assure you the version number is correct for a `develop` branch. You should be able to tell what was installed from the branch switch update messaging.

**Comment by afragen** [comment]
You can always try switching to the branch again. The end result is simply a re-install of the plugin.

**Comment by bishless** [comment]
I have Siteground's SG-Cache plugin installed, but assumed - it was only caching front end views/assets. Maybe that's an incorrect assumption. 

I'll try disabling it temporarily to see if the behavior changes (gonna wait to do this until late tonight, though - have a ton of traffic hitting our site re: a semi-viral _Paycheck Protection Program_ post #yikes)

**Comment by afragen** [comment]
It might also be helpful to know which plugins are causing these issues. Maybe there’s some commonality.

**Comment by afragen** [comment]
@bishless anything new to report?

**Comment by bishless** [comment]
I'm so sorry for the delay. I deactivated our caching plugin temporarily, attempted to switch to the development branch of GHU, but it still displays "master".
![screenshot 2020-05-05 at 07 15 39](https://user-images.githubusercontent.com/170618/81086955-ff2f5580-8ead-11ea-9f84-4023d3f82bb9.png)

I still have the caching plugin deactivated and, unfortunately, I'm still getting those warnings written to my PHP error log:
```
Warning: file_get_contents(/tmp/c51bc10caf2e7ecfe093be1c1fb8a1fa-tmp-readme.txt): failed to open stream: No such file or directory in /home/beachfle/public_html/wp-content/plugins/github-updater/vendor/afragen/wordpress-plugin-readme-parser/class-parser.php on line 168
```

Scratchin' my head here.

**Comment by afragen** [comment]
@bishless this is very strange. As I said before this file is created immediately before the `file_get_contents()` call.

Can I ask what files are in the `/tmp/` directory?

Have you tried testing this in a local dev environment and seeing if it persists?

Can you screens

**Comment by afragen** [comment]
My current guess is that your server doesn't have a `/tmp/` directory. I'll see if I can figure some way around this.

**Comment by afragen** [comment]
Re-install the `develop` branch and let me know if this is fixed. I'm now writing the temp file to the uploads dir instead of the system temp dir. It seems there might be an issue if the system didn't report back the temp dir correctly from `get_temp_dir()`

**Comment by bishless** [comment]
The server does have a `/tmp` dir... but it's up one level from the wp directory. 

I'll clear the log and reinstall the develop branch and let you know what I see in a couple hours.

**Comment by chesio** [comment]
I had a similar issue on one webhost recently - I found out that the `/tmp` dir on the webhost was for some reason restricted to 16 MB of space only, so I guess it occasionally filled up.

Anyway, I solved the issue by creating custom `tmp` directory next to `public_html` and told WordPress to use it instead of default `\tmp` via [`WP_TEMP_DIR`](https://developer.wordpress.org/reference/functions/get_temp_dir/) constant.

**Comment by afragen** [comment]
I moved it to store in the uploads directory in the develop branch. I want a consistent location. I'd hoped servers would have a properly located `tmp` directory but it seems that's not always the case. 

It's hard to have nice things. 😢

**Comment by chesio** [comment]
> I want a consistent location.

I don't think changing the location for temporary files via `WP_TEMP_DIR` constant makes the location inconsistent. The location is constant, just different than default.

In my case, I actually prefer to have temporary files outside of publicly accessible part of the website. So if you plan to use `uploads` directory, please make the location filterable.

Another reason why I prefer the old way is that I can assume that only temporary files are placed in a designated temporary directory, so I can safely purge its contents in case it happens to fill up for some reason. This logic does not apply to files in `uploads` directory.

I agree it's hard to have nice things sometimes (and time consuming), but I wouldn't just give up in this case :-) All in all half of this thread was about not being able to switch branches.

**Comment by afragen** [comment]
Thanks for the information @chesio. Based on this I will revert back and recommend the use of setting `WP_TEMP_DIR` if there are issues.

**Comment by afragen** [comment]
@bishless @chesio I've reverted back to the original behavior of using the temp directory. 

@bishless can you set the location of your temp directory using `WP_TEMP_DIR` and let me know if that works?

**Comment by bishless** [comment]
Oh! This sounds promising! I'll do my best to get this set this evening and will report back.

**Comment by bishless** [comment]
Well, I afraid I'm still seeing similar behavior w/ a different directory declared. ( _/ghutmp/_ )

```
Warning: file_get_contents(/home/beachfle/ghutmp/c51bc10caf2e7ecfe093be1c1fb8a1fa-tmp-readme.txt): failed to open stream: No such file or directory in /home/beachfle/public_html/wp-content/plugins/github-updater/vendor/afragen/wordpress-plugin-readme-parser/class-parser.php on line 168
```

That said, maybe I don't have the permissions set correctly on the new directory? Let me know what they should be and I'll get them adjusted.

**Comment by afragen** [comment]
@bishless your webserver should have read/write permissions. Setting the directory to 755 should be more than enough.

**Comment by bishless** [comment]
Ok, I've adjusted the permissions. I'll take another look at the logs in an hour or two.

**Comment by bishless** [comment]
Shoot. Perhaps I'm defining the constant incorrectly?

`define( 'WP_TEMP_DIR', '/home/beachfle/ghutmp');`

![screenshot 2020-05-13 at 12 54 23](https://user-images.githubusercontent.com/170618/81858663-edd2f280-9518-11ea-98b6-c9b69fdab7e3.png)

**Comment by afragen** [comment]
The only thing I can think to do is test a `file_get_contents()` on a known path in your server. Perhaps there's more to the path.

**Comment by afragen** [comment]
The constant declaration is working. Maybe just a question of whether the path is correct.

**Comment by afragen** [comment]
@bishless you can comment out the following line and all the temp files should remain.

https://github.com/afragen/github-updater/blob/ebe9541f9d88dc1e1ee2966ba20b71b9611aeed3/src/GitHub_Updater/Readme_Parser.php#L97

**Comment by afragen** [comment]
@bishless any more info? While I may occasionally see similar error notices they are not consistent and as the View details links all contain data, it must be working.

**Comment by afragen** [comment]
Please reopen if this still seems to be a consistent issue.
