### ISSUE TITLE
Add tagged release version check instead of master branch

### ISSUE THREAD

**Issue by JimmyAppelt** [afragen/github-updater#708]
Allow comparing installed versions against tagged releases instead of comparing against a branch

Especially for repos not using a `develop` branch. 
I'm not open to discuss which kind of flow is better or worse (which is not the point of the request), but I and many others are not using such flow.

This allows us to up `master` branch version to e.x. `1.1.0-dev` when current tagged release would be `1.0.0` and not trigger a false update in WordPress backend.

**Comment by afragen** [comment]
Checking the tag version is not nearly as accurate as checking the version in the branch. Tagging is not required or necessary, but is accounted for when used.

https://github.com/afragen/github-updater/wiki/Versions-and-Branches

It is/was a conscious decision to use [git flow](https://nvie.com/posts/a-successful-git-branching-model/) in how GitHub Updater works.

**Comment by JimmyAppelt** [comment]
@afragen I understand the current concept of how GHU checks versions :) 

However, this is a genuine request as in fact already proposed 4+ years ago by @scarstens https://github.com/afragen/github-updater/issues/40#issuecomment-32493411

At least please consider an option to only check against tagged releases.

**Comment by afragen** [comment]
So @JimmyAppelt how would you do it and what happens when someone doesn’t tag releases?

**Comment by JimmyAppelt** [comment]
> GHU can’t be all things to all people.

You already did doing a great job! Agree you can't do everything for everybody 🙂 

> how would you do it and what happens when someone does not tag releases

Unfortunately, you can't force users to tag (even this is the correct way of releasing). But might be an idea to either have a plugin header or plugin filter which could be specified by the plugin/theme creator to only use tags. Then the tagging is up to the users.

This is just how I would have expected updates to work on `master`:

- branch: version 1.0.0
- latest tagged: 1.1.0
- update gets triggered
---
- branch: version 1.1.0
- latest tagged: 1.0.2
- nothing happens

Thanks for thinking about it, everything works fine if `master` is not bigger then the latest tag as you mention, so not unworkable (just need to be more carefully).

If you find it to difficult to implement or not worth the time, thats fine. It would just be that little bit more versatile for more users (not forcing a specific flow).

**Comment by JimmyAppelt** [comment]
😞 to bad 🙂

**Comment by afragen** [comment]
Sorry Jimmy. I couldn’t think of a way to alternately determine which version would be canonical, in `master` or tag. I believe that the branch version should be canonical.

Tagging releases is not required, but as I state in the README, if tagging is used it must be continued or updating issue can occur. 
https://github.com/afragen/github-updater/wiki/Versions-and-Branches

**Comment by JimmyAppelt** [comment]
No worries @afragen 🙂

Have a great weekend!
