### ISSUE TITLE
GitLab.com Theme URI: Not Found Error

### ISSUE THREAD

**Issue by marbetschar** [afragen/github-updater#709]
The GitLab.com Theme URI with the following format leads to a Not Found Error:

```
https://gitlab.com/{group_name}/{subgroup_name}/{project_name}
```

Can this be fixed? Since GitLab.com allows to create multiple levels of groups/subgroups.

**Comment by afragen** [comment]
This should already work. Can you give `afragen` `read` access to the repo.

**Comment by marbetschar** [comment]
added you as Guest in the repo.

**Comment by afragen** [comment]
When I go to the repo in the browser there’s an error about not being able to load the commits. I don’t see any code.

**Comment by marbetschar** [comment]
Upgraded you to a `Reporter`. FWIW: I can see the commit signatures message too, but I'm not sure it really has any effect. I imported the repo to GitLab and since then the message appears. But as a user I can work with the repo without any issues (push, pull, fetch etc. all works without problem.)

**Comment by afragen** [comment]
I was able to install and use the branch switch to re-install the theme. 

There will be issues as you have tags but they are not up to date so any version bump will show an issue but try to install the latest tag, which may them have different headers.

**Comment by afragen** [comment]
@marbetschar are you still having issues? It was working for me with the above caveats.

**Comment by afragen** [comment]
@marbetschar I’m going to close this. Please reopen if you’re still having an issue.
