### ISSUE TITLE
Support for subdirectories

### ISSUE THREAD

**Issue by jhotadhari** [afragen/github-updater#716]
Hi,
does the updater work for plugins inside a repository subdirectory?

Why? My plugin repository is structured in source and distribution subdirectories.
For Example (I know GitHub Plugin URI declaration still missing):
  - the repository url: https://github.com/jhotadhari/geo-masala
  - the plugin within repository: https://github.com/jhotadhari/geo-masala/tree/master/dist/trunk

This is not really an issue. Hope this is the right place for my question.

Thank you. If it works for my structure, I'll use it for all my projects.

**Comment by afragen** [comment]
GHU wasn’t designed to use GitHub subdirectories. Much of the reason is how GitHub functions as GHU uses its native downloading the repository’s zip file. Much of the requirement means that the plugin’s base file be available in the root directory of the repo.

If your plugin uses a build command you can use the release asset to add it to your GitHub repository’s release and GHU will use that for updating, but the root directory of your repo must contain a dummy main plugin file that is named identically to your main plugin file. This dummy file must have the updated version number as this is the file that GHU query’s for updates.

https://github.com/afragen/github-updater/wiki/Settings#release-assets

**Comment by jhotadhari** [comment]
Hi, thanks for your fast reply. And sorry for my late reply, didn't find time.

I tried your solution with this plugin: https://github.com/jhotadhari/labeled-list-block
Added `GitHub Plugin URI` and `Release Asset` to the main plugin file.
Added a dummy main plugin file with same header and file name to the repository root.
Published a new release with title `0.1.2` and a release asset `labeled-list-block-0.1.2.zip`.

Installed GHU and added personal access token.
(manually added the two required lines to the header of installed labeled-list-block plugin so GHU checks for updates. And manually decreased the version number).
Now I can see, that a new update is available.

When updating, I get the positive green update-message notice that says: _Labeled List Block updated!_
But the `wp-content/plugins/labeled-list-block/` directory is empty afterwards.

`debug.log`:
`[17-Dec-2018 14:44:13 UTC] PHP Warning:  copy(): The first argument to copy() function cannot be a directory in /htdocs/wp-admin/includes/class-wp-filesystem-direct.php on line 243`
`[17-Dec-2018 14:44:13 UTC] PHP Warning:  array_keys() expects parameter 1 to be array, boolean given in /htdocs/wp-admin/includes/class-wp-upgrader.php on line 510`

Made another test and manually decreased the version number of the installed GHU plugin.
Update is available and updating successful. No errors, no warnings.

Do you have any suggestions?
Can you tell me another plugin that uses GHU and release assets? So I can test with this plugin?

Thanks a lot. Will reply faster this time ;)

WordPress Version 5.0.1
GitHub Updater Version 8.5.2
PHP Version 7.2.9

**Comment by afragen** [comment]
The problem here is your release asset zip. It should have the following structure.

```
labeled-list-block
  |
  labeled-list-block.php
  src
  ...
```

In other words the zipfile should unzip to a containing folder with the appropriate plugin slug and all plugin files go in that folder.

This is a WP Core thing.

**Comment by afragen** [comment]
https://github.com/cedaro/satispress also uses release assets.

**Comment by jhotadhari** [comment]
Thanks a lot,
to restructure the release assets zip solved the problem.
Now it's working great!
