### ISSUE TITLE
New release broke my plugins/themes.

### ISSUE THREAD

**Issue by bahia0019** [afragen/github-updater#717]
Earlier today I released a commit for a theme, updated it, no problem.
Updated a handful of plugins Github Updater was one.
Went to update another commit, and no go. Looked in my Add Plugins/Themes area, and there's nothing there.

Thoughts?

**Comment by afragen** [comment]
What's your theme URI?

**Comment by bahia0019** [comment]
https://github.com/FlauntSites/padang-padang

**Comment by afragen** [comment]
Can you describe how it broke? Screenshot?

**Comment by afragen** [comment]
Related? https://github.com/afragen/github-updater/wiki/Background-Processing

**Comment by bahia0019** [comment]
After the update, it just wouldn't update. I hit refresh cache a few times, and still nothing.

Here's a screenshot. The fields for Access Token weren't there before. They just showed up.
Should I re-enter, or is there something else going on?

<img width="950" alt="screen shot 2018-09-18 at 5 15 00 pm" src="https://user-images.githubusercontent.com/1586037/45723512-8bb8c300-bb66-11e8-8efb-a9c3d04944fd.png">

**Comment by afragen** [comment]
The tabs not being there is a because of the background processing.

You get control of your admin faster, but not everything may display if you immediately head to those tabs.

You DID you something. Time heals. 😉

**Comment by afragen** [comment]
Same issue as #715 I believe.
