### ISSUE TITLE
Updates not showing up

### ISSUE THREAD

**Issue by MCOAugusta** [afragen/github-updater#718]
Updates are not showing up in WP admin. I've pushed several updates to github, incremented stylesheet. Updates are not coming through to WP. Reinstalled theme and updater plugin. Updates are showing in github updater settings, but not WP updates.
![screen shot 2018-09-26 at 3 23 09 pm](https://user-images.githubusercontent.com/32741136/46103942-1bcabe00-c1a0-11e8-94c6-4bdc62ad6b50.png)
When I refresh cache, the GitHub tab disappears.
![screen shot 2018-09-26 at 3 23 53 pm](https://user-images.githubusercontent.com/32741136/46104002-38ff8c80-c1a0-11e8-83ff-05c8d45284d7.png)
Plugin version 8.3.1.4

**Comment by afragen** [comment]
You should configure a GitHub Personal Access Token to avoid the error in the notice.

For your first image, give it some time. The background processing just hasn’t finished. There’s a notice about that.

If you want to turn off background processing and add a few other troubleshooting plugins, you can install the [GitHub Updater Support plugin](https://github.com/afragen/github-updater-support).

**Comment by rafasashi** [comment]
I have replaced` !array( $response)` with` is_string( $response )` in github-updater\src\GitHub_Updater\Traits\API_Common.php line 80

but you could also add !is_object instead.

**Comment by afragen** [comment]
@rafasashi I’m not sure that your PR will fix the OP’s issue as I really think the background processing simply hasn’t finished. It does seem to fix your issue.
