### ISSUE TITLE
Updating theme using private bitbucket repo creates a duplicate theme

### ISSUE THREAD

**Issue by creative2020** [afragen/github-updater#72]
When updating a theme from Bitbucket it updates with the new version, but duplicates the theme folder and appends the folder name with -a82fea825177 (some version number) and does not delete the old one and automatically make the new theme active. So every time I run the update it adds another theme directory.

Things to note
- I tried this on 2 different servers
- I am getting the plugin updating to work correctly on the same server, where it updates and deletes and old plugin folder and makes the new plugin active.

Let me know if you have run across this or what I might check

Thank You!

**Comment by adampatarino** [comment]
@afragen @creative2020 what was the resolution here? This is causing issues with my sites on Media Temple, also using a private bitbucket repo. Updates install a second version of theme, leaving the old theme active and adding the updated version as a new theme.

This is only an issue because I have customization settings saved against the theme, so switching to the updated theme loses all the customizations.

**Comment by adampatarino** [comment]
Turning the repo public, does not solve this for me.

**Comment by afragen** [comment]
What version of GHU are you using?

**Comment by adampatarino** [comment]
@afragen  I'm on 5.3.4

**Comment by creative2020** [comment]
Thanks for the reply, I was having too many problems, so I have since not been using the plugin. I will reach out if I decide to try it again at some point.

**Comment by afragen** [comment]
Can you give `afragen` `read` access to the repo so I can test locally? Also, can you tell me is this on single site install or multisite install, is it the current active theme?

What is the current directory name of the theme in `wp-content/themes/`?

**Comment by adampatarino** [comment]
Theme is public on bitbucket for now: https://bitbucket.org/Aytoo/a2theme

It's on a single site install, the theme to be updated is currently active. The Directory name is `a2theme`

**Comment by afragen** [comment]
@adampatarino I was able to install and update your theme locally. The only issues I had were likely related to not having specific plugins installed and activated. There was a PHP fatal for `get_field()` not defined as called in `header.php` on line 23.

All renaming was fine. What I did was initially install/activate the them via GHU's Install pane. This ensured that the theme's directory was properly named from the start.

To check renaming I decreased the theme's version number locally and an update notice was triggered. This way you don't have to wait for the transients to time out.

When I directly downloaded and installed the theme from the zip file, then decreased the local version number, I only saw an update notice in the core update page, not on the themes page. I assume this is related to the theme having a different directory name than expected or as retrieved from Bitbucket.

`Aytoo-a2theme-79a95f6f590c` vs `a2theme`

The updating provides for the correctly named directory structure, but as the previous theme is active and there are not 2 themes identified as the same theme. This can be confusing.

In this case the problem can be averted by correctly naming theme's directory structure initially and subsequent updates will work as expected.

Can you provide a listing of your themes directory?

**Comment by adampatarino** [comment]
Interesting, will it always be `Aytoo-a2theme-79a95f6f590c`? Or will that change for each update / change.

Media Temple's managed WP hosting comes with quite a few themes:
http://cl.ly/37390x362N03

Would deleting those help at all?

**Comment by afragen** [comment]
It should be named the same as the repo, `a2theme`

It's usually a good security practice to delete plugins and themes that are not being used. :+1: 

> Interesting, will it always be Aytoo-a2theme-79a95f6f590c? Or will that change for each update / change.

Unfortunately, this name might be different depending upon how the user downloads and installs the theme. The best way to ensure proper naming is to actually use the GHU Install pane. :wink: 

Otherwise, as described in the README, you should unzip the download, rename it correctly ( in this case to `a2theme`), rezip it, then upload/install.

**Comment by adampatarino** [comment]
OK that helps, I'll try to install via GHU pane and delete the other themes.
Thanks!

**Comment by afragen** [comment]
Let me know how that works.

@creative2020 were you having similar problems.
