### ISSUE TITLE
No GitHub settings tab in a multisite install

### ISSUE THREAD

**Issue by pbiron** [afragen/github-updater#725]
I've got GitHub Updater installed on a number of single sites and am using it to update from a private repo and use the _GitHub_ tab to enter the access token for the private repo:

![github-updater-github-settings-in-singlesite](https://user-images.githubusercontent.com/3824560/47606837-c7507380-d9d5-11e8-91ec-35ed9e25d932.png)

I've also got it installed on a multisite and am trying to update the same plugin from the private repo.  However, the _GitHub_ settings tab doesn't appear on the multisite installation:

![github-updater-no-github-settings-in-multisite](https://user-images.githubusercontent.com/3824560/47606850-067ec480-d9d6-11e8-9847-71f7aff0e435.png)

All sites are running WP 4.9.8 and GitHub Updater 8.4.1.

**Comment by afragen** [comment]
From the notice displayed you need to wait until WP-Cron starts/finishes. This is a consequence of the modular construction of these tabs. Refresh the page or go to another page and come back. One of those things should get WP-Cron started.

https://github.com/afragen/github-updater/wiki/Background-Processing

**Comment by pbiron** [comment]
Thanx for the quick reply.  With only GitHub Updater and the private repo plugin in question, that background processing should take more than a minute or so, right?

Because the _Please be patient..._ has been there for 10-15 minutes.  Maybe there is something wrong with wp-cron on the site.  Let me try disabling background processing and I'll get back to you.

**Comment by pbiron** [comment]
I'll have to see what is wrong with wp-cron on the multisite, because disabling background processing worked, so closing this.

**Comment by pbiron** [comment]
yea, I'll try that.  Again, thanx for the quick response!
