### ISSUE TITLE
Error trying to configure a Remote Management

### ISSUE THREAD

**Issue by franzarmas** [afragen/github-updater#727]
Hello, I am receiving a page error when I try to configure a Remote Management .. here a video where I show it --> http://take.ms/Nm7BF

**Comment by karbaapinfinityhub** [comment]
I'm having the same issue.

**Comment by afragen** [comment]
Thanks for reporting. I see something strange on my end too. Odd that I have changed anything here lately.

**Comment by franzarmas** [comment]
@afragen  It seems to me that the URL to which it redirects after saving is not correct.

I hope I can release a version path as soon as possible for this.

Thank you!

**Comment by afragen** [comment]
This should be fixed in the `develop` branch. Can someone else test and I'll push a release. Thanks.

**Comment by franzarmas** [comment]
I now try it and I tell you.

**Comment by franzarmas** [comment]
All right, it worked for me ... http://take.ms/jHSu8

**Comment by afragen** [comment]
Thanks for confirming. I'll push a release tonight.
