### ISSUE TITLE
Wordpress extensions page shows changelog from 'develop' branch

### ISSUE THREAD

**Issue by dregad** [afragen/github-updater#729]
When a new version of GHU is available, the Wordpress extension page shows the changelog from the _develop_ branch instead of the one from _master_ branch, even though the latter is the active branch, which is confusing.

![selection_001](https://user-images.githubusercontent.com/449891/47964950-df14a100-e040-11e8-9b4c-0949e042cdca.png)

![selection_002](https://user-images.githubusercontent.com/449891/47964956-f81d5200-e040-11e8-9a8f-2306318770a7.png)

Comparing _master_ and _develop_ branches as of this writing: https://github.com/afragen/github-updater/compare/358d4ba...464ea14

I guess this happens because the changelog is retrieved from the repo's default branch (which is _develop_)... If so, I think you should make sure to pick up the changelog from the currently active branch as configured in Wordpress, instead.

As a side note, IMHO the changelog in _master_ branch should not contain an `[unreleased]` section.

**Comment by afragen** [comment]
This should now be fixed.
