### ISSUE TITLE
"update now"

### ISSUE THREAD

**Issue by jucajuca** [afragen/github-updater#730]
is there somewhere a button "Update this theme now?"

And also: "last updated on".

For me there is no way to know if the github-updater is working or not.

**Comment by afragen** [comment]
There’s a Settings page designated by git server that should contain the plugin/themes name.

**Comment by afragen** [comment]
You can use the Refresh Cache button on the Settings page and once all the background API processing has completed any update notices should show.

**Comment by jucajuca** [comment]
ok, thanks for the info
