### ISSUE TITLE
Idea: Activate Override Dot Org -> add Exceptions

### ISSUE THREAD

**Issue by erikmolenaarnl** [afragen/github-updater#731]
Hi,

I have a duplicate theme name which required me to set **GITHUB_UPDATER_OVERRIDE_DOT_ORG** to **True**. Works great!

But, here comes: I have other plugins which I -_do_- want to update from Dot Org _instead_ of Github.

It would be a great idea to **set exception**s for plugins/themes when this setting is active.

I hope my idea is of any use. Thanks for this great piece of code and keep rockin' !

**Comment by erikmolenaarnl** [comment]
Hi Andy

Thanks for your quick reply!

I use a theme called "Latest" -> https://github.com/ArrayHQ/latest. This is a duplicate theme name already in use on dot org for another theme. This is why I have set the override to true.

But setting the override also suggests updating FontAwesome to the latest beta on Github: https://www.screencast.com/t/6QO0ATWj. Which I do not want to use in a production environment.

Looking forward to your reply. Thanks again!

**Comment by afragen** [comment]
I’ll see what I can do about adding a filter to override my override.

**Comment by erikmolenaarnl** [comment]
Awesome. Where can I give a donation for this awesome plugin project?

**Comment by afragen** [comment]
There’s a donate link on the README, and thanks.

**Comment by afragen** [comment]
Just making notes to myself.

Refactor `GHU_Trait::is_override_dot_org()` to accept array of slugs/file to override instead of blanket override of any potential plugin/theme. This could end up as a breaking change but I’ll try to simply deprecate the constant.

**Comment by erikmolenaarnl** [comment]
The donation page on your website is not found btw.

**Comment by afragen** [comment]
Oops, gotta fix that. 🤦🏻‍♂️

**Comment by afragen** [comment]
@erikmolenaarnl donate link fixed. 😄

**Comment by afragen** [comment]
@erikmolenaarnl take a look at latest develop branch and above commit.
https://github.com/afragen/github-updater/wiki/WordPress.org-Directory

**Comment by erikmolenaarnl** [comment]
@afragen I got the development branch but the new filter seems to be ignored:

![2018-11-09_13-40-16](https://user-images.githubusercontent.com/22014267/48263132-638e6780-e425-11e8-8acb-31bb641d0e42.jpg)

**Comment by afragen** [comment]
I didn’t do anything with the dashicon, but any updates should come from the correct place. Looks like I have another part to fix.

**Comment by afragen** [comment]
@erikmolenaarnl the above commit should fix this dashicon issue.

**Comment by erikmolenaarnl** [comment]
It works great! Thanks for the quick fix :-)

**Comment by afragen** [comment]
@erikmolenaarnl what do you think of 
https://github.com/afragen/github-updater/commit/1d1821812f8a2dd49027241e9aa0017cb4c7de15?

**Comment by erikmolenaarnl** [comment]
Hi @afragen I was just wondering when [1d18218 ](https://github.com/afragen/github-updater/commit/1d1821812f8a2dd49027241e9aa0017cb4c7de15) will be added to the stable/master version?

Sorry if this is a newby question, I am new to Github. Thanks :-)

**Comment by afragen** [comment]
I will probably add release the next version this week.
