### ISSUE TITLE
GitHub Updater Fehlercode: There may be a problem with WP-Cron. A GitHub Updater WP-Cron event is overdue.

### ISSUE THREAD

**Issue by Netzlichter** [afragen/github-updater#737]
Hello,

I get the following error:
[12-Nov-2018 10:16:31 UTC] PHP Notice:  Undefined property: stdClass::$file in /html/wordpress-2018/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 301
 

[12-Nov-2018 10:16:31 UTC] PHP Notice:  Undefined property: stdClass::$git in /html/wordpress-2018/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 304

And all time this notice:
GitHub Updater Fehlercode: There may be a problem with WP-Cron. A GitHub Updater WP-Cron event is overdue.

WP Cron is active and only guthub updater has problems,.

Would be rgeat if you can help me!

**Comment by afragen** [comment]
Can you do a few things for me?

Download and activate the [GitHub Updater Support](https://github.com/afragen/github-updater-support) plugin. It will install several other plugins and cause GHU to run not using wp-cron. You might also install WP-Crontrol from the wp.org.

If that notice for having a problem with WP-Cron doesn’t go away then you do have an issue with WP-Cron.

**Comment by Netzlichter** [comment]
Hi there,

I installed the Updater Support plugin before. Then I got the errors from the log:
[12-Nov-2018 10:16:31 UTC] PHP Notice: Undefined property: stdClass::$file in /html/wordpress-2018/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 301

[12-Nov-2018 10:16:31 UTC] PHP Notice: Undefined property: stdClass::$git in /html/wordpress-2018/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 304

One of the support plugins caused a fatal error with updraft plus plugin so I had to deactivate all Updater support plugins. Because my site is live.

I have no issues with WP Cron so far...

**Comment by afragen** [comment]
Can you tell me which support plugin caused the issue with Updraft plus plugin?

Can you post a screenshot of the GitHub Updater Settings pages?

**Comment by afragen** [comment]
That error would indicate an issue with one of the plugins that GHU is attempting to parse.

**Comment by Netzlichter** [comment]
Image of settings:
https://www.dropbox.com/s/nsoh1ht9hwm51yc/github.jpg?dl=0

Im using updraft plus newest version. "Github updater support" hadn't caused the error but another plugin I had to install after the first 2(?).  After I removed the folder via ftp the site was back online...

Thank you.

**Comment by afragen** [comment]
I’m asking which plugin cause the issue and what that error was.

**Comment by afragen** [comment]
Is this your first time using GitHub Updater?

Can you install WP-Crontrol?

What plugins are you intending to use GHU’s updating with?

**Comment by Netzlichter** [comment]
Yes I know. But I don't know the exact plugin and error. I cannot test it again beause it's a onlineshop which is live.

Because of the plugin that GHU is attempting to parse. Maybe it has something to do with "PayPal for WooCommerce" from Angell EYE? Because today I found out, that there was a newer version that my installed one (I got no update information). I installed it and it was in a new folder "paypal-for-woocommerce" and the old version was in "paypal-for-woocommerce-213923 (or soemthing simliar)...

I have it running on other sites too. I want to update "Contact Form DB" only...

**Comment by Netzlichter** [comment]
It seems that settings are missing, because I filled in an own API-Key but I cannot find it again?!

**Comment by afragen** [comment]
I’m getting confused. Let’s try the following. Deactivate and remove the GitHub Updater Support plugin and all the plugins it installs and activates.

Add the following to your theme’s functions.php file.
`add_filter( 'github_updater_disable_wpcron', '__return_true' );`

**Comment by Netzlichter** [comment]
> I’m getting confused. Let’s try the following. Deactivate and remove the GitHub Updater Support plugin and all the plugins it installs and activates.

I did this right after one of the plugins caused a fatal error.

here you can find a image of my GHU Settings:
https://www.dropbox.com/s/nsoh1ht9hwm51yc/github.jpg?dl=0

Before there were more options, like paste Github API key... and some plugins connected. At the moment there is nothing (check the image).

Regarding the "PayPal for WooCommerce" from Angell EYE. Because today I found out, that there was a newer version that my installed one in WordPress repository (I got no update information). I installed it and it created a new plugin folder "paypal-for-woocommerce" and the old version was in "paypal-for-woocommerce-213923 (or something simliar). That was really strange.

https://de.wordpress.org/plugins/paypal-for-woocommerce/
https://github.com/angelleye/paypal-woocommerce

Maybe that is causing some conflict?

**Comment by afragen** [comment]
Have you added the filter to your theme’s functions.php file?

**Comment by Netzlichter** [comment]
I added it. Screenshot of settings: https://www.dropbox.com/s/rkhei9pt35pgai8/github2.jpg?dl=0

**Comment by afragen** [comment]
Can you install the WP-Crontrol plugin from WordPress.org?

Are you still getting the errors?

**Comment by Netzlichter** [comment]
I installed WP-Crontrol.

Nothing changed.

**Comment by afragen** [comment]
Is there any information in the WP-Crontrol Settings?

Can you manually run any overdue cron jobs?

**Comment by Netzlichter** [comment]
The only cron jo that is not working properly is from "ghu_get_remote_plugin". There are many lines of arguments (round about 300). and 2017-11-29 20:39:23 (jetzt). 2017?!

There are no overdue cronjobs...

**Comment by afragen** [comment]
Can you run or delete that?

**Comment by Netzlichter** [comment]
I cnanot delete it. If I click on remove, site is refreshing and it's still there. Im a bit afraid to hit run? Can I destroy something?

**Comment by afragen** [comment]
There is no issue with deleting the cron job.

**Comment by Netzlichter** [comment]
I made another screenshot after hitting delete: https://www.dropbox.com/s/0qsj7ugjz1udzkk/github3.jpg?dl=0

**Comment by afragen** [comment]
https://github.com/afragen/github-updater/wiki/Background-Processing

**Comment by afragen** [comment]
It wasn’t deleted if it’s still there.

**Comment by Netzlichter** [comment]
Maybe it has something to do with my staging setup I used before? Because wordpress path ist like .../html/wordpress-staging/wp-content/... It's not possible to delete that cron job. Nothing happens when I click delete.

**Comment by afragen** [comment]
I have no idea about what is going on with your wp-cron. What I do know is that you shouldn’t be seeing any more errors in your logs from GHU. If you are please let me know.

You can ignore the notice for overdue WP-Cron but it does indicate a problem.

**Comment by afragen** [comment]
What happens if you try to run the cron job?

**Comment by Netzlichter** [comment]
When I deactivate GHU I cannot delete that cron job too:
https://www.dropbox.com/s/2ggbxi6r8a3dvpy/github4.jpg?dl=0

Can I destroy something when I lick "Run"?

**Comment by afragen** [comment]
No, can’t hurt anything.

**Comment by afragen** [comment]
Do you have WP-CLI access to the site?

**Comment by Netzlichter** [comment]
https://www.dropbox.com/s/9use0utcrpy3ird/github5.jpg?dl=0 hit run. still there.

**Comment by Netzlichter** [comment]
yes I have WP-CLI access.

**Comment by Netzlichter** [comment]
"local_path": "/html/wordpress-staging/wp-content/plugins/contact-form-7-to-database-extension/",

under arguments is wrong... it is from staging site...

**Comment by Netzlichter** [comment]
If I click on edit next to "ghu_get_remote_plugin" and the remove all arguments. Then save. Nothing changed...

**Comment by afragen** [comment]
It seems like you're having some sort of permissions/user capabilities issue on that site.

**Comment by afragen** [comment]
Using wp-cli should override any permissions or user capabilities issues. Did you try running the above command in wp-cli?

**Comment by Netzlichter** [comment]
Nothing happend. Cron job is still there. Is it save to remove the whole value in database? GHU caused MASSIVE information in that field...

**Comment by afragen** [comment]
Sure you should be able to delete the whole cron job using wp-cli.

`wp cron event delete ghu_get_remote_plugin`

**Comment by afragen** [comment]
No idea but it clearly indicates that there is a problem on your site with WP-Cron. Using the provided filter will bypass WP-Cron for background updating on GHU. Once you have your WP-Cron issue solved you should be able to safely remove the filter.

**Comment by Netzlichter** [comment]
All other cron jobs are fine and working correct. Only the "ghu_get_remote_plugin" is stuck since 2017 and I cnanot delete it...

**Comment by afragen** [comment]
I'm not sure what else I can do for you in this instance. Having the overdue cron job won't cause an issue but will cause the notice to persist. I'm not sure how else to try to delete the cron job other than using wp-cli.

**Comment by afragen** [comment]
You might try `wp option delete cron`. This will delete all current cron events but they should repopulate.

**Comment by Netzlichter** [comment]
I delete the value of that cron event manually in database. Now it is working. Thank you for your time.
