### ISSUE TITLE
502 Errors in wp-admin

### ISSUE THREAD

**Issue by reggieofarrell** [afragen/github-updater#738]
With this plugin activated I'm getting pretty frequent 502 errors in wp-admin.  Host is WP Engine if that helps.  Any ideas?

**Comment by afragen** [comment]
Is there a direct error pointing to GHU?

**Comment by reggieofarrell** [comment]
There's not, but it only happens when I activate GHU.  We have a lot of plugins so it could be that something just isn't playing nice.  I just put in a ticket with WP Engine about it so hopefully they can shed some light from looking at the logs.  GHU would be a huge help if I can get the site to cooperate.  I'll report back either way.

**Comment by afragen** [comment]
Maybe this will help. https://www.lifewire.com/502-bad-gateway-error-explained-2622939

If WP Engine comes up with anything relating to GHU please let me know.

**Comment by afragen** [comment]
Can you post the WP Engine issue URL?

**Comment by reggieofarrell** [comment]
It was a chat actually, but this is what they said...

> When that plugin is activated it is trying to access something and causing the overload.
> I don't know the inner workings of that plugin however, so I couldn't say why that is happening.
> so to clarify... 
> processes are being killed by our long process killer when the plugin is enabled
> so it could be making a ton of requests, or using up too much memory, etc

So far, they haven't been able to give me any more info.

**Comment by afragen** [comment]
The plugin normally does all it's processing in WP-Cron as a background task. If you are bypassing WP-Cron with the filter and you have a  lot of plugins/themes using GHU you certainly could time out.

**Comment by reggieofarrell** [comment]
I know we are using something at WP Engine called Alternate Cron that was recommended by a different plugin developer to solve an issue we were having.  I'll raise that with WP Engine in regards to this issue and see what they say.

**Comment by afragen** [comment]
This might help. 
https://github.com/afragen/github-updater/wiki/Background-Processing

**Comment by reggieofarrell** [comment]
Thanks for the link.  I'll pass that along.  Would there be any negative impact from using foreground processing?  What will be functionally / noticeably different if I go that route?  Any site performance impacts?

**Comment by reggieofarrell** [comment]
More info from the developer...

https://github.com/afragen/github-updater/wiki/Background-Processing

**Comment by afragen** [comment]
Foreground processing has the possibility of timing out depending upon how many plugins/themes are using GitHub Updater. I’ve caused  it in testing.

**Comment by afragen** [comment]
@reggieofarrell any news?

**Comment by afragen** [comment]
I do have other WPE users successfully using GHU.

Not that it should make a difference, but there is a new release.
