### ISSUE TITLE
Repo not found on update

### ISSUE THREAD

**Issue by nskraus** [afragen/github-updater#739]
I successfully connected to Bitbucket to install my theme, and when I pushed an update it recognized it, however when I update it says it could not find the repo.

**Comment by afragen** [comment]
Can you share the URL or post the theme’s headers? What was the actual error?

**Comment by afragen** [comment]
I think I just found the issue. @nskraus you are using the `develop` branch?

**Comment by afragen** [comment]
https://github.com/afragen/github-updater/commit/901d64c03f664a2ef4b1dfdab5e64bb39e3c49f0 should fix the problem.

**Comment by lincolnlemos** [comment]
Awesome. I got the same bug here. I updated the plugin and It's working now. Thanks, Andy. Your plugin rocks!

**Comment by lincolnlemos** [comment]
To register, this is the message that I was getting. 
In english will be "Failed to update: Download failed. Not Found."
![screenshot 2018-11-22 13 18 16](https://user-images.githubusercontent.com/1391743/48922120-490eb200-ee59-11e8-8b38-4e4c009310db.png)

**Comment by afragen** [comment]
@lincolnlemos thanks. To be clear you no longer see the error?

**Comment by nskraus** [comment]
Just want to confirm this is fixed for me, thanks for the quick update and a great plugin!
