### ISSUE TITLE
Doesn't Auto Update

### ISSUE THREAD

**Issue by sagescrub** [afragen/github-updater#740]
I am using this plugin for the first time. So far I am loving the features and the UI but having problems with the cron updater.  

My private github plugins and theme downloaded and installed perfectly. However they don't update. My host is wpengine and the wp-cron is running. Yet the wait for wp-cron to finish message doesn't go away and there is the red exclamation next to each project.

I tried running with the debug plugin and the logs are not providing any clues that I can see. There is no option to manually update each plugin or theme.

Furthermore my theme is not in the list of repositories so I am not sure if that is in the list to update automatically. 

Please help!

**Comment by afragen** [comment]
You might want to install the WP-Crontrol plugin to help troubleshoot whether there is a cron issue.

If you have the [GitHub Updater Support](https://github.com/afragen/github-updater-support) installed and activated then WP-Cron will be bypassed. It might be best to start from here and make sure everything else works first.

Can you provide the headers for all the repositories you are having issues updating?

**Comment by afragen** [comment]
Also, please ensure you are using the latest release, version 8.5.0

**Comment by sagescrub** [comment]
Thanks for the quick reply.

The updater support plugin did not help me. The exclamation marks went away but the updates were still not automatically performed. I did not see any button to update manually. 

Here is one of my plugin's headers:

<?php
/**
 * Plugin Name:       WooCommerce Steem Custom Currencies
 * Description:       Adds STEEM & SBD currencies to WooCommerce
 * Plugin URI:        
 * Version:           1.0.1
 * Author: sagescrub
 * Author URI:  https://steemit.com/@sagescrub
 * GitHub Plugin URI: https://github.com/sagescrub/woocommerce-steem-custom-currencies
 *
 * @package Theme_Customisations
 */

**Comment by sagescrub** [comment]
Yes I am using the latest 8.5.0

**Comment by afragen** [comment]
If the icons went away then the API was correctly queried for each plugin. The cache is stored for 12 hours. You can manually clear the cache, forcing another API query (actually about 5-6 queries) and see more immediate results. If you are looking to have the update happen automatically with a git push you can set up a webhook. Please refer to the wiki for this.

It appears the plugin’s headers are correct.

**Comment by afragen** [comment]
Let’s make sure everything works before venturing on to webhooks and continuous integration. I really just wanted to let you know what’s possible.

**Comment by sagescrub** [comment]
OK! It turns out my cron jobs was disabled and I got it enabled. Now I ran the update plugins job manually. It looks like it ran and the exclamation marks went away. But my plugin did not update. What I did was simply update my plugin file and change the version from 1.0.2 to 1.0.3. I refreshed my plugins page and the version is still 1.0.2. Any idea here?

**Comment by afragen** [comment]
Excellent. Please close this issue once you’ve confirmed.

What about the theme that didn’t show up in the repository listing?

**Comment by sagescrub** [comment]
Im so sorry. I thought it updated but it did not. What I did was update the version number in my plugins file from 1.0.2 to 1.0.3 and pushed it to github. I ran the update plugins cron job and the exclamation  marks went away. But my plugin still says 1.0.2. Shouldn't it have updated the version number?

**Comment by sagescrub** [comment]
The theme still does not show up under GitHub tab. Should it appear there? I have made customizations and don't want to delete it. what can i do to make sure my theme will be synced?

**Comment by sagescrub** [comment]
The theme is also a private repository in case that makes a difference.

**Comment by sagescrub** [comment]
OK I got the plugin to update. Apparently it needed an actual code change, not just the version change. So that is all good now! Great!

Regarding the theme it is not registering the updates I just pushed including the GitHub Theme Uri. Does this mean I need to delete the theme and re-add? Or can I re install over it?

**Comment by afragen** [comment]
You will need to edit the theme on your site to fix the `GitHub Theme URI` or you could delete the theme and reinstall from the Install tab.

**Comment by sagescrub** [comment]
oh that's great! ok good point. I will try that.

**Comment by afragen** [comment]
Anything that sees the `Version` header bump will show an update. It doesn’t require actual code.

**Comment by afragen** [comment]
BTW, you can do a re-install by using the branch switching feature.

**Comment by sagescrub** [comment]
Yes!! The theme showed up in the list and it is updating! Wonderful! This is great. Thanks for the quick replies and helping me get up and running faster! I really appreciate it :) I am looking forward to using your plugin now that I understand how to use it :)

**Comment by sagescrub** [comment]
Thanks for the tip about branch switching. I will keep that in mind, it may come in handy for future updates.

**Comment by afragen** [comment]
@sagescrub you caught me at the right time. 😉

**Comment by sagescrub** [comment]
I feel very fortunate. I hope you have a wonderful evening :)
