### ISSUE TITLE
Notice: Trying to get property 'slug' of non-object...

### ISSUE THREAD

**Issue by tharindutpk** [afragen/github-updater#741]
I'm getting this notice on the WordPress admin dashboard.

`Notice: Trying to get property 'slug' of non-object in /var/www/{sitename}.com/public_html/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 767`

However this notice only appears in certain number of pages and it goes away after some time.

**Comment by afragen** [comment]
Thanks for the report. I saw it earlier, already fixed. 
https://github.com/afragen/github-updater/commit/b83b24d49761bf7e242be2ee445e3cc708e9acf8
