### ISSUE TITLE
Class Conflict

### ISSUE THREAD

**Issue by cbratschi** [afragen/github-updater#743]
GitHub Updater 8.5.0 conflicts with classes in our theme. We are getting the following Google_Client error:

> Fatal error: Uncaught Error: Class 'TBGAPI\Google_Client' not found 

We are using a separate namespace so this should never conflict. Probably a require import is wrong in GitHub Updater.

**Comment by cbratschi** [comment]
It must be caused by those changes:

https://github.com/afragen/github-updater/commit/2eb3d1517c85afd6b17bc6da58d805e6957c00c8#diff-db879e3912cb89846c96050510cbb110

**Comment by cbratschi** [comment]
Our failing code:

```
        //load
        require_once __DIR__ . '/vendor/autoload.php';

        //init
        $client = new TBGAPI\Google_Client();
```

**Comment by cbratschi** [comment]
We have this issue on all our systems. The GitHub Updater 8.5.0 updated is causing this issue. As soon as we disable the plugin everything works fine again. We also tried to disable the Opcode cache but this made no difference.

**Comment by afragen** [comment]
This makes no sense. Is there a URI for you code I can look at and possibly install your plugin and see.

**Comment by cbratschi** [comment]
It was an autoloader issue.
