### ISSUE TITLE
Downloading from GitLab repos no longer working

### ISSUE THREAD

**Issue by phodge** [afragen/github-updater#744]
It looks like a recent release of GitLab changed the .zip archive URL scheme from `https://<hostname>/<group>/<project>/repository/archive.zip?ref=master` to `https://<hostname>/<group>/<project>/-/archive/master/<project>-master.zip`. Has anyone else experienced this problem?

**Comment by phodge** [comment]
I've had another go installing my WP theme using the the latest github-updater version from `develop`.

GHU is trying to download the WP theme using URL:
```https://<hostname>/projects/<group>%2F<project>/repository/archive.zip?sha=master&private_token=<secret>```

However the correct URL is:
```https://<hostname>/<group>/<project>/repository/archive.zip?sha=master&private_token=<secret>```

The correct URL is missing the `/project` and also the `%2F` between `<group>` and `<project>` must be a literal `/` character.

We are running a private GitLab CE installation on our network, version `11.5.1`

**Comment by afragen** [comment]
I’m trying to get this all fixed in the develop branch. I thought I had everything fixed.

Is it only installs that you have an issue on?

**Comment by afragen** [comment]
Just a not to myself.
`
https://framagit.org/api/v4/projects/afragen%2Ftest-plugin-gitlab-ce/repository/archive.zip?sha=master&private_token=Xxxxxxxxx`

**Comment by afragen** [comment]
@phodge https://github.com/afragen/github-updater/commit/a696e38a9f318d7e764fc7d45f180df0d883b426 should fix this for both GitLab.com and GitLab CE.

**Comment by tdavidrussell** [comment]
Development 8.5.0.4 broke the GitLab.com, rolled back to 8.5.0.3, public and private repos works fine. I don't a CE version to test with.

**Comment by afragen** [comment]
@tdavidrussell I can’t reproduce this as they both work for me in 8.5.0.4.

Can you provide more specifics about what doesn’t work, what does the URL that doesn’t work look like.

**Comment by tdavidrussell** [comment]
development 8.5.0.4 is working for me now.

**Comment by afragen** [comment]
Strange, but glad it's working. This is likely to be the release version today or tomorrow.
