### ISSUE TITLE
Disable fetching updates if on wp.org

### ISSUE THREAD

**Issue by Raruto** [afragen/github-updater#746]
I realized that plugin is present on github with a major version number github updater adds it to the list of plugins to be updated and, of course, if you try to update it wordpress will fail trying...

## Steps to reproduce:

0. install: **GHU v. 8.5.2**  (with WP v. 5.0.1)
1. install this plugin directly from wp.org: https://wordpress.org/plugins/geoip-detect/ (**v. 2.9.2**)
2. visit your plugins.php page (or force **check of wordpress updates**)

![geoip](https://user-images.githubusercontent.com/9614886/49957348-cdf46500-ff07-11e8-95b7-5e5b8cdbe494.png)

3. now you should see a new update for the version **v. 2.9.3-beta** (current version for: https://github.com/yellowtree/wp-geoip-detect)
4. if you try to install this update it will fail (because it does not exist in the wp.org directory...)

## Actual Results:

![geoip-2](https://user-images.githubusercontent.com/9614886/49957494-41967200-ff08-11e8-9e19-785bf7728e5c.png)

the plugin is not updated (ie. wordpress will still always notify an available update) or the update fails (with some older WP / GHU versions)

## Expected Results:

- avoid seeking for updates from GitHub if a plugin/theme is also on wp.org

---

**NB** I have not checked yet, but I think this problem is slightly different from the problem solved by using this filter: _github_updater_override_dot_org_

**Comment by afragen** [comment]
The issue is that this plugin has a different slug on GitHub than it does on dot org. This is compounded by the fact that the dot org file has the `GitHub Plugin URI: https://github.com/yellowtree/wp-geoip-detect`. 

What is happening is WP and GHU are seeing 2 different plugins because there are 2 different plugin slugs. But GHU is using the GitHub repository to check for updates.

Unfortunately the solution is to have the owner change the GitHub repository to match the plugin slug on dot org. Then everything will work as expected.

**Comment by afragen** [comment]
https://github.com/yellowtree/wp-geoip-detect/issues/55

**Comment by Raruto** [comment]
Ok, for other possible future similar cases it would be possible to introduce a filter (analogous to the _github_updater_override_dot_org_) to selectively disable some GHU's remote checks?

**Comment by afragen** [comment]
It seems what you’re looking for is a way to disable GHU for a specific plugin. That exists, just remove the relevant headers from the plugin. This is likely a lot simpler and in the meantime try to have the plugin author fix the issue. It can be as simple as removing the headers in the version that goes to dot org.

**Comment by afragen** [comment]
Under normal circumstances if the plugin is on dot org and on GitHub, with identical slugs and the version is `master`, then all updates will come from dot org.

**Comment by afragen** [comment]
It is also the case that the releases are being tagging and the version is bumped in `master` but not a tagged release. As the wiki states this will result in an endless update cycle.

https://github.com/afragen/github-updater/wiki/Versions-and-Branches#tagging

**Comment by afragen** [comment]
Circular updating.

GitHub Updater reads the current version information from the main plugin’s `Version` header. In this case the current version in `master` is `2.9.3-beta`. The most current tag is `2.9.2`. Once the developer starts tagging releases they must continue as if a tag is present it will be used as the download link for the update. 

What happens is that the `master` branch has a higher version number than the installed version. An update notice is shown, however, and the most recent tagged release is used as the download link. If the tag is for the _old_ version then it will be installed and an update notice will still show.

The philosophy behind GitHub Updater necessarily requires that any releases and the `master` branch are in sync. If development occurs on the `master` branch then tagging should likely not be used. This is why I almost always have a `develop` branch.

**Comment by Raruto** [comment]
Ok, so this is what would happen in this specific case (if the plugin was not also present on wp.org ...)

> What happens is that the master branch has a higher version number than the installed version. **An update notice is shown, however, and the most recent tagged release is used as the download link.** If the tag is for the old version then it will be installed and an update notice will still show.

But this happens because you can not directly check the version of the plugin from the tagged release? (eg. because the github API doesn't allow a direct access to single files of the release, as instead happens for the branches, without first having to download the entire zip file?)

**Comment by afragen** [comment]
Yes, you can check the headers of an individual file in the branch but you can only check the tag name, nothing inside of the tag.

GitHub Updater is opinionated. It works best if the `master` branch is identical to the current tag or if there are no tags at all. Development is better done is a different branch. GHU will look to the installed branch for the version number.

**Comment by Raruto** [comment]
OK, thank you for everything,

_.. over and out .._
