### ISSUE TITLE
Rest_Update log_exit hook

### ISSUE THREAD

**Issue by Raruto** [afragen/github-updater#747]
Always for the reasons that led me to the create the [log branch (#L312)](https://github.com/afragen/github-updater/blob/85d2f967849fdb342ca371acd82c57931baec2a7/src/GitHub_Updater/Rest_Update.php#L312)

It could be possible to add, within the Rest_Update::log_exit, a hook like this?
```php
do_action( 'github_updater_after_rest_process_request', $response, $status_code );
```

```php
/**
 * Append $response to debug.log and wp_die().
 *
 * @param array $response
 * @param int   $code
 *
 * 128 == JSON_PRETTY_PRINT
 * 64 == JSON_UNESCAPED_SLASHES
 */
private function log_exit( $response, $code ) {
	$json_encode_flags = 128 | 64;
	error_log( json_encode( $response, $json_encode_flags ) );

        < -- INSERT HOOK HERE -->

	unset( $response['success'] );
	if ( 200 === $code ) {
		wp_die( wp_send_json_success( $response, $code ) );
	} else {
		wp_die( wp_send_json_error( $response, $code ) );
	}
}
```

**Comment by afragen** [comment]
Adding a filter is pretty simple but what’s the use case?

What are you planning on doing with the hook?

**Comment by afragen** [comment]
Please note the name is slightly different.

**Comment by Raruto** [comment]
ok, thank you for adding it (I also updated it in the main question..)

---

**note tor the readers:** with this set of hooks (you can see the others here: [GHU_Rest_Update.php#L62](https://github.com/Raruto/wp-devops/blob/7e58d87404a790b2cc4891da9f0505ddb0fd753b/src/Controller/GHU_Rest_Update.php#L62)) it is now possible to keep track of all the RESTful calls performed toward wordpress, without necessarily keeping the _WP_DEBUG_ constant active ...

---

Happy thoughts,
Raruto
