### ISSUE TITLE
404 Errors

### ISSUE THREAD

**Issue by adamcoulombe** [afragen/github-updater#748]
I am getting 404s when trying to install with this plugin
![image](https://user-images.githubusercontent.com/469038/50044874-fc815580-0057-11e9-870f-292327a57e59.png)

it is trying to hit the URL `https://api.github.com/repos/{USERNAME}/{REPO}/zipball/master?_wpnonce=36b1470d77`

It returns 
```
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
```

however if I remove `?_wpnonce=36b1470d77` from the url it downloads fine when I hit the URL in my browser

**Comment by afragen** [comment]
GitHub usually returns a 404 if the repository is private and you don't have access.

I don't think GitHub Updater is adding the nonce. This is when you are attempting to install a plugin via the _Install Plugin_ tab?

**Comment by adamcoulombe** [comment]
Yes, install plugin tab. 

Further testing revealed it’s not the nonce param causing the issue. 

The repo is not private.

Initially When I try to install, instead of installing, the API “not found” result comes up.  But if I type the same URL in my browser bar, the zip file downloads.

**Comment by afragen** [comment]
Can you share the URL so I can test?

**Comment by adamcoulombe** [comment]
sure. I am just trying this: 
[https://github.com/adamcoulombe/demo-plugin](https://github.com/adamcoulombe/demo-plugin)

Result: [Imgur](https://imgur.com/wU7n45u)

**Comment by afragen** [comment]
What URL are you using for the install?

**Comment by adamcoulombe** [comment]
this is the URL I am inputting:

https://github.com/adamcoulombe/demo-plugin

GitHub Plugin URI: https://github.com/adamcoulombe/demo-plugin

**Comment by adamcoulombe** [comment]
Ok. That could be the problem. In this particular case I don’t have the ability to edit the wp-config, but I will try on another server and see if it works that way
