### ISSUE TITLE
Filter ZIP URL before running the update

### ISSUE THREAD

**Issue by sc0ttkclark** [afragen/github-updater#749]
I'd like to filter the ZIP URL before the update itself is run. I don't want to filter it every time it fetches information about the plugin, it's only needed on the context for me to filter it just before the update process runs since it may add an additional few seconds.

**Comment by sc0ttkclark** [comment]
I'd like this to work with branch switching too. The filter should at minimal have access to the plugin slug and the branch being used for the ZIP.

**Comment by afragen** [comment]
https://github.com/afragen/github-updater/commit/7b989516f6c12eb9fc42a61951b9abaa0b92fba0 should fix this. 😉 

Thanks for working through this with me.
