### ISSUE TITLE
Edge case with GitHub release missing assets

### ISSUE THREAD

**Issue by figureone** [afragen/github-updater#750]
Aloha, we ran into an edge case where a mistaken release on a GitHub repo caused WordPress to fail ungracefully during a theme update process (leaving the `.maintenance` file in place until WP Cron cleaned it up, resulting in a longer outage). 

The bad release did not include any assets, so this line wasn't replacing `$response` with the download URL string, leaving it as an object (which caused WordPress to fail):
https://github.com/afragen/github-updater/blob/develop/src/GitHub_Updater/Traits/API_Common.php#L73

Quick fix would be to verify that `parse_release_asset()` is returning a string.

Details are here:
https://github.com/pressbooks/pressbooks-book/issues/427

Not really a bug, but figured you might want to know if case you wanted to harden GitHub Updater for this specific edge case. Thanks!

**Comment by afragen** [comment]
So a tag was created but the release asset wasn’t produced by Travis? Or a version bump was done without a tag?

**Comment by figureone** [comment]
I'm unclear on the details, just aware of the end results (missing `assets` attribute in API response). @greatislander might be able to provide more details.

**Comment by afragen** [comment]
Perhaps returning `false` would be better. 🤔

**Comment by figureone** [comment]
Yeah, the author pulled the invalid release, so I can't comment on how it ended up that way. But I can confirm that it is possible to have a GitHub release without `assets`! :)

Here is where WordPress choked because it was expecting a URI (string) and got an object:
https://github.com/WordPress/WordPress/blob/5.0.2/wp-admin/includes/class-wp-upgrader.php#L258

A little further down there there's an `empty($package)` check which returns a `WP_Error`, so probably an empty string would be fine. That should fail gracefully at least.

**Comment by afragen** [comment]
Thanks for the report!

**Comment by greatislander** [comment]
The issue was: we set Release Asset to true in the GitHub Updater config. Our Travis build script builds and uploads a release asset for tagged versions. However, I accidentally published a release for a subpackage and which did not match the expected version numbering pattern, so no release asset was built. Entirely an issue on our end, as far as I can tell—GitHub Updater was behaving as expected.
