### ISSUE TITLE
tmp-readme.txt file

### ISSUE THREAD

**Issue by AiratHalitov** [afragen/github-updater#754]
After github-updater plugin update you can find file `tmp-readme.txt` in `/wp-content/` directory. 
Is this how it should be?
I usually delete this file. Or can you delete it automatically?

**Comment by afragen** [comment]
That file is written out as part of parsing the readme.txt files. It gets constantly overwritten as new readme.txt files are parsed. If GitHub Updater is uninstalled the file is removed. I don’t delete it automatically as I ran into the occasional timing issue where it might be deleted before it is needed and this caused a PHP error. It was easier to leave it in place.

I can look into it again to see if I can avoid the previous issue. Feel free to delete it but it will be recreated several times every 12 hours.

**Comment by AiratHalitov** [comment]
Ok, you can close this issue
