### ISSUE TITLE
Could not copy file

### ISSUE THREAD

**Issue by fahdi** [afragen/github-updater#758]
` {
    "success": false,
    "data": {
        "messages": [
            "Downloading update from <span class=\"code\">https://bitbucket.org/.../.../get/master.zip</span>&#8230;",
            "Unpacking the update&#8230;",
            "Could not copy file. r-luxury-afa8bb0bdc83/404.php"
        ],
        "webhook": {
            "action": "github-updater-update",
            "key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "theme": "luxury",
            "webhook_source": "browser"
        },
        "elapsed_time": "1131.75 ms"
    }
}`

**Comment by afragen** [comment]
You will have to look at your folder permissions. The unpacking and installing code is pure WP Core.
It looks like the webhook fired correctly.

Is this the first time this has been tried? Can you update or switch branches from the dashboard?

**Comment by fahdi** [comment]
@afragen Thanks, I am on wpengine and it was definitely the file permissions.

**Comment by squarecandy** [comment]
After experiencing a similar error on WP Engine, I actually just got told by their support that using this plugin in combination with github webhooks is not compatible with their platform.

> Hey again Peter,
> So after digging a bit both into past tickets here regarding the plugin specifically; as well as inspecting those screenshots you provided in greater detail - we can isolate the UA that github is using as github-hookshot - and see that it's getting a 417 return message 'Expectation Failed'.
> Since this goes beyond allowing that UA to make the call - it's unlikely that plugin will perform as expected on our platform.
> If utilizing git, you'll need to use our platform for that. (some additional information regarding that here https://wpengine.com/git/)
> Appreciate the patience again while I investigated the issue itself, and the errors present in your push using the plugin!

**Comment by afragen** [comment]
🤯 @squarecandy is there any way you can put me in contact with someone from WPE?

**Comment by afragen** [comment]
BTW, I intentionally return a 417 error if there’s an error. It’s more likely something isn’t responding as expected. What does the response from the webhook show?
