### ISSUE TITLE
Something changed in Gitlab API -404

### ISSUE THREAD

**Issue by giedrius** [afragen/github-updater#759]
Some things changed in Gitlab API and I can no longer access projects through project name (e.g. giedrius.majauskas/project name when not logged in. Only by project id number ( e.g 235235 ) 
So, Github updater breaks on gitlab.  I am unsure if it is a bug, or some permanent change on gitlabs behalf. 
If I change Gitlab Theme url in theme to gitlab.com/523523  (or something like that), the updater does not parse it as a valid theme (I think). 
Is there a way to specify project ID to use with Gitlab API requests?

**Comment by afragen** [comment]
Are you using the current version of GitHub Updater? GitLab did change their API recently.

I don’t have any issues with GitLab repositories in testing. Can you provide the URL?

**Comment by giedrius** [comment]
It looks like gitlab API requires FULL access  permissions (including account read) to access private repositories, except when using their numeric  IDs so the old repository read tokens stopped working :( 

Thank you.
