### ISSUE TITLE
Traditional Chinese (Taiwan) Localization is complete

### ISSUE THREAD

**Issue by alexclassroom** [afragen/github-updater#763]
Hi,

Please get the latest zh_TW PO and MO file from https://suo.fyi/GitHubUpdater.

This download link is fixed, I will always upload the latest files to this location.

Regards,
Alex Lion

**Comment by afragen** [comment]
Thanks Alex. I've [referenced the link in GitHub Updater Translations](https://github.com/afragen/github-updater-translations/issues/23)

**Comment by alexclassroom** [comment]
Updated zh_TW language pack is complete, please get the files from the same link, thanks.

**Comment by alexclassroom** [comment]
Updated zh_TW language pack for 9.2.0 is complete, please get the files from the same link, thanks.

**Comment by alexclassroom** [comment]
2020/1/29: Updated zh_TW language pack for 9.2.1 is complete, please get the files from the same link, thanks.

**Comment by afragen** [comment]
@alexclassroom you are wonderful, thank you.
