### ISSUE TITLE
Warning: sprintf(): Too few arguments

### ISSUE THREAD

**Issue by catapultcc** [afragen/github-updater#764]
Fantastic plugin! It works, but i get one error when clicking on: wordpress menu appearance > Themes > Themedetails. The popup is showing a error:

There is a new version of Stichting catent available. 
Warning: sprintf(): Too few arguments in xxxxxxxx\wordpress\wp-content\plugins\github-updater-develop\src\GitHub_Updater\Theme.php on line 548
View version 1.1.4 details or update now.

Note: the update is working. But just getting this error each time i view the details before updating the theme.

![tempsnip](https://user-images.githubusercontent.com/5636812/52419506-88f84380-2af0-11e9-9517-6f88637a676b.png)

**Comment by afragen** [comment]
Try refreshing the cache. It seems that you didn’t pick up the branches from an API call.

**Comment by catapultcc** [comment]
> Try refreshing the cache. It seems that you didn’t pick up the branches from an API call.
> 
> Also, make sure that GHU has completed all it’s updating, i.e. no admin notice in the Settings page reporting that updates are still waiting to happen.

Thanks. Unfortunately, that solution does not work. Tried several times.

**Comment by afragen** [comment]
Can you give me the theme URL? Perhaps I can replicate.

**Comment by catapultcc** [comment]
> Can you give me the theme URL? Perhaps I can replicate.

Sure! I send you a message

**Comment by catapultcc** [comment]
https://github.com/catapultcc/slingshot-catent


Met vriendelijke groet,
Jurre Hengstman



Reggeweg 5|7447 ANHellendoorn|jurre@catapult.nl
T +31 548 654 954|KvK nr: 060.51683
catapult.nl|blog.catapult.nl
De informatie verzonden met dit e-mailbericht is uitsluitend bestemd voor de geadresseerde(n) en kan persoonlijke of vertrouwelijke informatie bevatten, beschermd door een beroepsgeheim. Gebruik van deze informatie door andere(n) dan de geadresseerde(n) en gebruik door hen die niet gerechtigd zijn van deze informatie kennis te nemen, is verboden. Indien u niet de geadresseerde bent of niet gerechtigd bent tot kennisneming, is openbaarmaking, vermenigvuldiging, verspreiding en/of verstrekking van deze informatie aan derden niet toegestaan en wordt u verzocht dit bericht terug te sturen en het origineel te vernietigen.
Van: Andy Fragen <notifications@github.com>
Verzonden: donderdag 7 februari 2019 16:31
Aan: afragen/github-updater <github-updater@noreply.github.com>
CC: Techniek <techniek@catapult.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [afragen/github-updater] Warning: sprintf(): Too few arguments (#764)


Can you give me the theme URL? Perhaps I can replicate.

**Comment by afragen** [comment]
First, you only need one `GitHub Theme URI` header. 😉

It seems to work for me.

![screenshot_01](https://user-images.githubusercontent.com/1296790/52426164-4e6fb600-2ab2-11e9-9ff9-fc619d28e5e0.png)

Can you try testing with https://github.com/afragen/test-child ?
