### ISSUE TITLE
Using repos in an organization

### ISSUE THREAD

**Issue by sreinstein** [afragen/github-updater#765]
I recently switched my repos to an organization. I'm able to clone them with Github Updater but I'm having trouble getting them to recognize updates. Is the process different for using repos in an organization?

**Comment by afragen** [comment]
I would need an example. Though as there is still an owner and a repo it shouldn’t matter. Just need to ensure you’re pointing to the correct URI.

**Comment by ChristopheSeguinot** [comment]
I've just tested GitHub-Updater with my new organisation [lab-hal](https://github.com/cnrs-webkit/lab-hal). Everything works fine.
