### ISSUE TITLE
Allow user to choose an alternate location to write tmp-readme.txt

### ISSUE THREAD

**Issue by doomcrewinc** [afragen/github-updater#766]
Create an option to allow the user to choose an alternative path to write the 'tmp-readme.txt' to.  

We do not allow plugins to write to the 'wp-content/' directory (security reasons) when there are other good directories to write to such as 'wp-content/uploads/' or a folder within wp-content such as the 'wflogs' folder that Wordfence uses.

As a result of attempting to write to 'wp-content' our logs are filling up with a lot of file permission errors and it makes troubleshooting more cumbersome.

Thanks

**Comment by afragen** [comment]
I will see about a change and let you know.

**Comment by afragen** [comment]
@doomcrewinc can you test this for me? It in the latest `develop` branch.

**Comment by doomcrewinc** [comment]
@afragen I've installed it, and looking through the changes you made I see you set a filter 'github_updater_temp_readme_filepath', but I can't see it that it actually changed the location.

**Comment by afragen** [comment]
The filter allows you to set the location.

```php
add_filter( 'github_updater_temp_readme_filepath', function() {
	return ABSPATH . 'wp-content/uploads/tmp-readme.txt';
} );
```

**Comment by doomcrewinc** [comment]
@afragen just an update.  This **does** work, I'm wonder though if it'd be possible to do this via a Form Field on the GitHub Updater Settings page.  The reasoning behind this is, as much as your solution works, it's going to require cloning then submitting 100's of pull requests to update all of our sites.  If you could configure it via the Settings page, it'll allow it to be theme independent, and store it in the database.  It'd be much easier to update a field per schema than to clone/pull.

**Comment by afragen** [comment]
There will not be a new setting. 

It might be simpler to create a small plugin to put this and any other platform specific code in. You could use wp-cli to install and activate.

**Comment by doomcrewinc** [comment]
Okay.  If you could keep the ability to set a filter, I will make the changes needed on my end.

Thanks.

**Comment by afragen** [comment]
It was my plan to keep the filter and put in next release.

**Comment by doomcrewinc** [comment]
Thank you.
