### ISSUE TITLE
Bitbucket Forbidden error 

### ISSUE THREAD

**Issue by v-galkevich** [afragen/github-updater#767]
Hi,
I have some problem installing plugin from bitbucket repo via Github Updater Plugin.
I migrated plugin repository from Github to Bitbucket and tried to install it using GitHub Updater from bitbucket but I got an error "Download failed. Forbidden".
I entered my login and password to Bitbucket.
this repository is private.
may be I missed something while doing all this stuff.

**Comment by v-galkevich** [comment]
And I have the permission for reading/writing - I am an admin

**Comment by afragen** [comment]
Make sure the username is your Bitbucket username and not an email address.

**Comment by v-galkevich** [comment]
Yes, I entered the username, not email. So, the problem is solved. The issue was in my password.
Password should be app password (user profile - settings - app passwords).
