### ISSUE TITLE
Set GitHub API key in plugin / theme

### ISSUE THREAD

**Issue by cocodedesigns** [afragen/github-updater#769]
Is it possible to set the GitHub personal access token directly into my plugin?  I know there is the possibility to set it in the plugin's admin page, but could I set it in the plugin, as I can for the Theme and Plugin URI?

**Comment by afragen** [comment]
Absolutely. Take a look at the `github_updater_set_options` hook. 

https://github.com/afragen/github-updater/wiki/Developer-Hooks
