### ISSUE TITLE
Enterprise hosted bitbucket - download not found

### ISSUE THREAD

**Issue by allrite** [afragen/github-updater#770]
Hi, 

We have a self-hosted bitbucket installation and I'm getting the error:

Downloading installation package from https://bitbucket.csiro.au/rest/archive/1.0/projects/WP/repos/csiro-nba/archive?prefix=csiro-nba/&at=master…

Download failed. Not Found

The URI is set to https://bitbucket.csiro.au/WP/csiro-nba/

The download path from the Bitbucket web interface is:

https://bitbucket.csiro.au/rest/api/latest/projects/WP/repos/csiro-nba/archive?format=zip

Note that this repository is not publicly accessible. It is running on Bitbucket v5.8.2

**Comment by afragen** [comment]
Is there any way I could have a temporary account on your server? I don’t have access to a Bitbucket Server to test.

I know Bitbucket recently changed lots of stuff in their API and I tried to update the Bitbucket Server code to accommodate but I clearly still have issues.

**Comment by afragen** [comment]
I’ll see what I can figure out if I can’t get an account.

If you could create a public repository with a dummy plugin and send the URL it would be helpful.

**Comment by allrite** [comment]
Thanks for your prompt response! 

I've created a new public repository at https://bitbucket.csiro.au/projects/WP/repos/wpgh-test/browse
and get the same error when I use https://bitbucket.csiro.au/WP/wpgh-test

**Comment by afragen** [comment]
Give me a couple of days to see if I can come up with a solution.

**Comment by allrite** [comment]
Thank you, really appreciated!

**Comment by afragen** [comment]
@allrite unfortunately I really do need a login to be able to figure this out. Any possibility of get me a test account on this Bitbucket Server instance?

**Comment by allrite** [comment]
Hi @afragen,
I have created a partner account for you on our system and you should have received an email about that. I believe that you need to log into https://bitbucket.csiro.au/ first using this account before I can assign permissions.

**Comment by allrite** [comment]
Okay, you have read permissions. I have also removed the public setting for https://bitbucket.csiro.au/projects/WP/repos/wpgh-test/browse

**Comment by afragen** [comment]
It's easier for me to test using some of my own test plugins and themes. I've uploaded these so I shouldn't need access to your test theme.

**Comment by allrite** [comment]
Hi @afragen if you need additional permissions then please let me know and I'll see what can be done. I'm not an expert on Bitbucket .

**Comment by afragen** [comment]
So far perfect. I'm working through how to determine the API. Unfortunately it's not well documented.

I'm making progress though I won't likely finish until Thursday.

**Comment by afragen** [comment]
@allrite can you test out the `fix-bbserver` branch and let me know what's still broken?

**Comment by afragen** [comment]
Use `Bitbucket Theme URI: https://bitbucket.csiro.au/WP/wpgh-test` In your header as an example. 

`Bitbucket Theme URI: https://bitbucket.csiro.au/<owner>/<repo>`

**Comment by allrite** [comment]
Hi @afragen ,

I've tried and am now getting: 

Downloading installation package from https://bitbucket.csiro.au/rest/api/latest/projects/~WP/repos/wpgh-test/archive?prefix=wpgh-test/&at=master&format=zip…

Download failed. Unauthorized

**Comment by allrite** [comment]
I'm going to try again a bit later. We may be having issues with Bitbucket on our end.

**Comment by afragen** [comment]
You need to make sure your use/password I enters on the Bitbucket Server Settings page and that the repository is checked as private.

**Comment by allrite** [comment]
I've tried again and am getting 

Downloading installation package from https://bitbucket.csiro.au/rest/api/latest/projects/~WP/repos/wpgh-test/archive?prefix=wpgh-test/&at=master&format=zip…

Download failed. Not Found

When I try to view the url  https://bitbucket.csiro.au/rest/api/latest/projects/~WP/repos/wpgh-test/archive?prefix=wpgh-test/&at=master&format=zip directly I get the error message:

{"errors":[{"context":null,"message":"Project ~WP does not exist.","exceptionName":"com.atlassian.bitbucket.project.NoSuchProjectException"}]}

Note that visiting https://bitbucket.csiro.au/rest/api/latest/projects/WP/repos/wpgh-test/archive?prefix=wpgh-test/&at=master&format=zip (no tilde in front of WP) redirects to the ~WP link above.

In our setup WP is the project and wpgh-test is the repository, rather than WP being the user.

**Comment by allrite** [comment]
Okay, it doesn't seem to like the tilde. I tried typing https://bitbucket.csiro.au/rest/api/latest/projects/WP/repos/wpgh-test/archive?prefix=wpgh-test/&at=master&format=zip directly in and it does download. 

I think adding the tilde back into the address bar was a browser artefact, so please ignore that bit.

**Comment by afragen** [comment]
So here’s the issue. You must be set up as a group `WP`. I am set up as a user `andy.6`. All the URI for a user have the tilde. Non of the URI for group have the tilde. I do add the tilde to the URI.

I’ll have to figure out a solution. I have an idea but won’t be able to test it until tomorrow. I think it will involve setting the `Bitbucket Theme URI: https://bitbucket.csiro.au/group-<owner>/<repo>` for a group account and `Bitbucket Theme URI: https://bitbucket.csiro.au/<owner>/<repo>` for a user account.

**Comment by afragen** [comment]
So I think I found a solution. You will need to more particular for the URI you use in the header.

For groups it will look like `Bitbucket Theme URI: https://bitbucket.csiro.au/projectsWP/csiro-nba/`

For individual users it will look like `BitBucket Plugin URI: https://bitbucket.csiro.au/users/andy.6/test-bitbucket-plugin/`

Use the branch switching to switch to the current branch, `fix-bbserver`. Make sure to update your header.

**Comment by allrite** [comment]
Hooray! I think you've got it! So I changed the URI to 

Bitbucket Theme URI: https://bitbucket.csiro.au/projects/WP/csiro-nba/

Used the same URI in the Bitbucket settings and made certain Private Repository was checked. 

The theme downloaded successfully. (Also for the test theme).

Thank you so much!

**Comment by afragen** [comment]
@allrite you should switch to the `develop` branch for now and at next release, back to `master`.

**Comment by photocurio** [comment]
I'm having the same issue with an enterprise Bitbucket server.  None of my themes and plugins can connect to the server. I have tried setting the Bitbucket URI with these formats:

- https://bitbucket.dev-intranet.fbcna.com:8443/projects/FMCMEW/repos/helpdeskwiki
- https://bitbucket.dev-intranet.fbcna.com:8443/projects/FMCMEW/helpdeskwiki
- https://bitbucket.dev-intranet.fbcna.com:8443/FMCMEW/helpdeskwiki

I have entered my username and password of course.  None of the themes or plugins can connect to their repos, as you can see by the red mark:
![image](https://user-images.githubusercontent.com/5224038/71100632-5fce2800-2183-11ea-9528-d86186a2c503.png)
