### ISSUE TITLE
After a successful theme update - the theme folder is empty

### ISSUE THREAD

**Issue by cawa-93** [afragen/github-updater#771]
I'm trying to implement theme updates from a private repository.
At the root is a `style.css` file with the following content:
```css
/**
 * Theme Name: Askio
 * Text Domain: askio
 * GitHub Theme URI: https://github.com/korzhikk/askio
 * Release Asset: true
 * Version: 0.0.6
 * License: UNLICENSED
 * Theme URI: https://github.com/korzhikk/askio#readme
 * Description: 
 * Author: Alex Kozack
 * Author URI: https://t.me/kozack
 *
 * This file was created automatically. Please do not edit it manually.
 */
```

Also, I create an asset for release. I created an archive in which the theme files were at the root, as well as the archive in which the theme files lay in the subdirectory with name `askio`. The result is the same. Your plugin sees the update and is updated successfully, however, after the update the **theme folder is empty**.

**Comment by afragen** [comment]
Can you give me temporary access to the repository?

**Comment by cawa-93** [comment]
@afragen Any news?

**Comment by afragen** [comment]
I was on call at hospital all day yesterday. I’ll have some time today to investigate.

**Comment by afragen** [comment]
I think I figured out the issue. WP Core is looking for a download that unzips to a folder named for the slug that contains all the files. Your release asset contains all the files in the root after being unzipped. You need to have a containing folder.

```php
askio -
    | - style.css
    | - index.php
    | - functions.php
```

Where your asset would be a zip of the `askio` directory.

**Comment by afragen** [comment]
@cawa-93 is it now working Alex?

**Comment by cawa-93** [comment]
Yes, it works. I forgot to answer. thanks
