### ISSUE TITLE
Contributors profile link in View details iframe

### ISSUE THREAD

**Issue by ChristopheSeguinot** [afragen/github-updater#773]
Thank you for this Nice plugin. 

I just published my first Wordpress plugin [lab-hal](https://github.com/cnrs-webkit/lab-hal/tree/0.5.1) on GitHub. Everything works fine, however, some of my contributors (including myself) do not have a Wordpres.org profile.

It's seems that every contributor name is used to generate a wordpress.org profile: for example my contributor name is _Christophe Seguinot (lab-HAL)_ which point to http://profiles.wordpress.org/Christophe%20Seguinot%20(lab-HAL)

- Is it possible to point to github profile or some external link as it's made in your [Readme.md](https://github.com/afragen/github-updater/blob/develop/README.md)? 

I think this is not possible in the current Github-Updater plugin. So I took a look at the code. 
- Wordpress code _/wp-admin/includes/plugin-install.php_ profile link are defined in  _$api->contributors_
- In GitHub-updater code _.../wordpress-plugin-readme-parser/class-parser.php_ array $this->contributors is used. 

Would it be possible to extract profile link from the readme.txt file ?

**Comment by afragen** [comment]
@ChristopheSeguinot the idea is to mirror the Plugin Directory. This involves using dot org data or mimicking dot org data. This data is parsed from the `readme.txt` file using the dot org parser.

What I do is use the dot org profile in the this View Details iframe and I use my GitHub profile in the `README.md` file so it is seen in the GitHub repository.

**Comment by afragen** [comment]
I do hope GitHub Updater works well for you otherwise.
