### ISSUE TITLE
Notice: Undefined index: github_access_token

### ISSUE THREAD

**Issue by ChristopheSeguinot** [afragen/github-updater#775]
Hi, 
This is a simple PHP notice I encountered while installing my plugin ([lab-hal](https://github.com/cnrs-webkit/lab-hal)) from a public GitHub repo  and using Github-Updater 8.7.2 . I did not set/use any GitHub token . This notices does not breaks the install which was successful . 
`Notice: Undefined index: github_access_token in .../wp-content/plugins/github-updater/src/GitHub_Updater/API/GitHub_API.php on line 527`
Its seems that static::$options['github_access_token'] is not set or may be the use of static:: here is wrong (however I'm not used to the new static:: command). 

Regards, Christophe

**Comment by afragen** [comment]
The issue is that the the token isn’t set. I should probably check for it’s existence here first.

**Comment by afragen** [comment]
But it is better if you simply set one in the GitHub settings tab.

**Comment by afragen** [comment]
@ChristopheSeguinot can you test latest `develop` branch and see if this doesn't fix the issue for you?

Thanks.

**Comment by ChristopheSeguinot** [comment]
Yes it fixes the Notice. 
Thanks
