### ISSUE TITLE
Not detecting my plugin

### ISSUE THREAD

**Issue by numediaweb** [afragen/github-updater#777]
I can install my private Github hosted plugin using github-updater (github token) but I don't see it on the list "Installed Plugins and Themes": I just see GitHub Updater.

My header is:
```
<?php
/*
Plugin Name: My plugin!
Plugin URI: https://example.com
GitHub Theme URI: numediaweb/my-plugin
Description: Demo
Version: 1.0.5
Author: Me
Author URI: https://example.com
*/
...
```

**Comment by numediaweb** [comment]
Thanks to https://github.com/afragen/github-updater-support I could figure out that the issue was with the private token not having enough scopes: would be great to mention what scopes does this plugin needs.

Thanks

**Comment by afragen** [comment]
Your header above is also incorrect. It should be `GitHub Plugin URI`.
