### ISSUE TITLE
GitHub Updater don't update plugins if I use external cron job

### ISSUE THREAD

**Issue by m266** [afragen/github-updater#778]
Hi Andy,
first, your plugin is very good. Thanks for your job.
I use external cron jobs and deactive the WordPress cron job in wp-config.php with this code:
define('DISABLE_WP_CRON', true);
Plugin updates from WordPress work fine, but your plugin "GitHub Updater" don't update my own plugins at GitHub.
I see this information with plugin "WP Crontol":
Hook Name: ghu_get_remote_plugin, ghu_get_remote_theme
Recurrence: Non-repeating
When I delete this code:
define('DISABLE_WP_CRON', true);
then worked your plugin again.
What do you think?
Thank for your help.

**Comment by afragen** [comment]
Please take a look at this documentation. 
https://github.com/afragen/github-updater/wiki/Background-Processing

You will need to add a cronjob either running `wp-cron.php` or a WP-CLI command as indicated.

**Comment by m266** [comment]
Thanks for your fast answer!
My cronjob calls this url: http://mysite.com/wp-cron.php
WordPress-Plugins need this code in wp-config.php:
define('DISABLE_WP_CRON', true);

GitHub Updater add additionally this code in functions.php:
add_filter( 'github_updater_disable_wpcron', '__return_true' );

This worked for me. Is this so ok?

Best regards.

**Comment by afragen** [comment]
Adding that filter bypasses WP-Cron entirely. It’s fine that’s one of the reasons I made the filter.
