### ISSUE TITLE
theme installs into wp-content/themes/repository-name, not /theme-name

### ISSUE THREAD

**Issue by jhotadhari** [afragen/github-updater#779]
want to use GHU to install/update a theme from private repository via release asset.

**The theme-name differs from the repository-name.**

style.css contains:
```
	GitHub Theme URI: https://github.com/owner/repository-name
	Release Asset: true
```
release tag is: `x.x.x`

release asset zip is structured like this:
```
	repository-name-x.x.x.zip
	   |
	  theme-name
		 |
		 theme-name.php
		 src
		 ...
```

GHU can find the theme and installs it without errors.

But it installs it into `wp-content/themes/repository-name`
Should be installed into `wp-content/themes/theme-name`

Can't rename the repository to match the theme-name.

Is it possible to change this behaviour? Or possible to hook a filter into the installation path

if I install the theme via /wp-admin/theme-install.php -> upload theme, wp installs it correctly into `wp-content/themes/theme-name` 

Thanks

**Comment by jhotadhari** [comment]
Just realized that GHU didn't install via release asset. But installed it from the root of the repository.

**Comment by afragen** [comment]
You might be able to use the release asset URL and install as a Zipfile.

**Comment by afragen** [comment]
I also believe the repository name and the theme name should be the same as this will likely cause issues with updating.

**Comment by jhotadhari** [comment]
tried to install as a zipfile and used the release asset URL.
But can't set an access token, so Download failed. Not Found.
Apparently the access token, set in GHU github settings is not used.

well, for me its good if updates are working. alternative way to install is no problem

**Comment by jhotadhari** [comment]
Tried to install a plugin via GHU.
The plugin repo is private and the plugin-slug differs from repo-name
plugin gets installed into `wp-content/plugins/repository-name` 

Removed `wp-content/plugins/repository-name` 
And installed a manually into `wp-content/plugins/plugin-slug`
Decreased version manually in `wp-content/plugins/plugin-slug/plugin-slug.php`
GHU recognizes the plugin and updates without without problems.

Manually installed the theme into `wp-content/themes/theme-name`
Decreased version manually in `wp-content/themes/theme-name/style.css`
GHU doesn't recognize the theme.

**Comment by jhotadhari** [comment]
Would be nice, if repository-name and theme-name were the same. But repository-name has to follow our naming convention.

**Comment by afragen** [comment]
Unfortunately GHU has no real ability to infer a plugin or theme slug that is different from the repository name. If you want a specific slug you will need to change the repository name. If you don’t care what the slug is it really doesn’t matter except if your looking in the directory structure. 

Whatever method you choose the slug and the repository really need to be the same. 

If the updates don’t show when this is true we can try working through that.

**Comment by jhotadhari** [comment]
> Whatever method you choose the slug and the repository really need to be the same.
Ok, renaming the slug to match the repository name, is good enough for me.

Tested successfully with private theme and plugin. 
Tested with repository names that contain upper-case letters and underscores (maybe these characters will make problems somewhere else. For GHU it works). 
Updates show up, and updating works as expected.

**Comment by afragen** [comment]
One of the only characters that creates an issue for a directory name is anything with a `.` in it as `parse_url()` has issues.
