### ISSUE TITLE
Bitbucket API Changes

### ISSUE THREAD

**Issue by djnolder** [afragen/github-updater#781]
Just wanted to make you guys aware of this...

https://developer.atlassian.com/cloud/bitbucket/bbc-gdpr-api-migration-guide/

**Comment by afragen** [comment]
I’m actually not sure what to make of this. I’m already using Bitbucket API 2.0. What I don’t see is a way to determine the `account_id` when what you have is the `username`.

Thanks for the warning, but without some way to use the `username` to at least find the `account_id` I don’t really know what to do.

We’ll see.

**Comment by afragen** [comment]
It may be that the solution will need to be a change of the header to use the `account_id` and not the `username`.  I know everyone will love changing to the following.

`Bitbucket Plugin URI: https://bitbucket.org/557058:0437b0e1-39e3-4313-8d00-bb19db86dbd4/test-bitbucket-plugin`

**Comment by afragen** [comment]
I can’t even see where you would find your own `account_id`.

**Comment by afragen** [comment]
https://stackoverflow.com/questions/53983942/how-to-find-bitbucket-account-uuid

**Comment by djnolder** [comment]
> It may be that the solution will need to be a change of the header to use the `account_id` and not the `username`. I know everyone will love changing to the following.
> 
> `Bitbucket Plugin URI: https://bitbucket.org/557058:0437b0e1-39e3-4313-8d00-bb19db86dbd4/test-bitbucket-plugin`

I was worried about that as well.

**Comment by afragen** [comment]
It doesn’t appear that is is going to be a problem for how GHU functions. At least not at this time. 😉
