### ISSUE TITLE
Customizing HTTP arguments for all requests

### ISSUE THREAD

**Issue by pawelkmpt** [afragen/github-updater#783]
I wanted to ask why this plugin appends HTTP arguments for all requests (or at least requests in custom WP-CLI commands)? It'd be better to add it only when GitHub Updater actions are performed.

Current behavior breaks my plugin in which I need custom user agent and skip SSL verification.

**Comment by afragen** [comment]
Can you give me an example of this?

**Comment by pawelkmpt** [comment]
I use `wp_remote_post()` and `wp_remote_get()` to perform requests and customize them with passing array of arguments to these functions, eg.

```php
$args = [
    'timeout'    => 180,
    'user-agent' => 'my-plugin-name/WP-CLI',
    'sslverify'  => false,
];

$response = wp_remote_post( $url, $args );
```

When GitHub Updater is network activated, request arguments look like this:

```
[
    "user-agent" => "my-plugin-name/WP-CLI; GitHub Updater - https://github.com/afragen/github-updater",
    "sslverify"  => true
]
```

Your plugin appends changes using `http_request_args` filter which overrides my customizations.

**Comment by afragen** [comment]
I was asked several years ago by someone at GitHub to add a header specifically identifying GHU. 

Just as I use the `http_request_args` filter to add these you can use it to remove them. Simply call the filter at a higher priority like 15.

**Comment by pawelkmpt** [comment]
> I was asked several years ago by someone at GitHub to add a header specifically identifying GHU.

That's understandable, but it affects whole WordPress installation.

> Just as I use the `http_request_args` filter to add these you can use it to remove them. Simply call the filter at a higher priority like 15.

I'm aware I can remove it, but it's not a perfect solution to have to think about removing hooks for every plugin which uses `wp_remote_*()` functions

**Comment by afragen** [comment]
GitHub GET requests are on HTTPS. If your plugin makes different requests you can filter based upon the URL as it is passed in the filter. 

I’m on mobile today. But I’ll look to see if I don’t/can’t remove this filter after it’s used.

**Comment by afragen** [comment]
@pawelkmpt can you test and confirm this fix? Thanks.

**Comment by pawelkmpt** [comment]
@afragen  yes, it's fine now. Thank you!
