### ISSUE TITLE
Consider using latest running filter to set transient 

### ISSUE THREAD

**Issue by afragen** [afragen/github-updater#784]
Consider changing to `site_transient_update_plugins` as later firing hook. Lots of testing will be needed.

**Comment by afragen** [comment]
I'm having a seriously great time removing lots of code after switching from `pre_set_site_transient_{$transient}` to `site_transient_{$transient}`

It's the difference between adding to set_site_transient or get_site_transient and reading into get_site_transient is much better.

**Comment by afragen** [comment]
https://github.com/afragen/github-updater/commit/cbdee73e0d7ccace4a3c62267c6c3b24ccc46cdd should fix this issue.

**Comment by HonzaKopecky** [comment]
I can confirm it solved the issue for me. Gravity Forms plugin is hooked to site_transient_update_plugins so originally it would overwrite any updates from GitHub Updater. Now it works just fine.

**Comment by afragen** [comment]
Try the following for Events Calendar PRO. 
`define( 'TRIBE_DISABLE_PUE', true );`

**Comment by afragen** [comment]
The following should work. Tested on my end.

```php
add_filter( 'site_transient_update_plugins', function( $transient ) {
	$ecp = 'events-calendar-pro/events-calendar-pro.php';
	if ( in_array( $ecp, array_keys( $transient->response ), true ) ) {
		unset( $transient->response[ $ecp ] );
	}

	return $transient;
}, 10, 1 );
```

**Comment by HonzaKopecky** [comment]
Sorry for my inactivity. Just a note here.

My goal was to override Events Calendar PRO update notices with the ones produced by GitHub Updater. There are actually two things one needs to do. 

Firstly hide the update notices that are custom added:
```php
add_filter( 'tribe_plugin_notices', 'filter_pre_set_site_transient_update_plugins', 20, 0 );
function filter_pre_set_site_transient_update_plugins() {
	return [];
};
```

And secondly Events Calendar PRO deregisters default update notice hook so it needs to be added again (had to go to core to figure this out, auch):
```php
add_action( "after_plugin_row_events-calendar-pro/events-calendar-pro.php", 'wp_plugin_update_row', 100, 2 );
```

Thanks @afragen for your help!
