### ISSUE TITLE
Github updater does not download versions 0.0.1xx

### ISSUE THREAD

**Issue by AlphaDE** [afragen/github-updater#785]
I use the optimization plugs o10n for several wordpress sites. Github updater made updates of those a lot easier.

They just released v 0.0.100 of a plugin. Github updater recognizes the new version but nevertheless downloads and installs 0.0.99. 

Any hint?

**Comment by afragen** [comment]
If you are tagging releases are you up to date with your tags?

**Comment by AlphaDE** [comment]
Good question, I'm just a user of the plugin... what do I need to do?

**Comment by afragen** [comment]
Ask the developer to look at this issue. What’s the URL?

**Comment by AlphaDE** [comment]
https://github.com/o10n-x/wordpress-css-optimization

**Comment by afragen** [comment]
So here’s the problem. The developer tagged a release as 0.99 and unless they delete it, a higher release will need to be 0.991 or greater. 0.0.100 is lower than 0.99 and that’s why 0.99 is being served.

**Comment by AlphaDE** [comment]
Ok, I pass that one, so it's a string comparison and not a value based evaluation.

**Comment by afragen** [comment]
It’s a version_compare.

**Comment by AlphaDE** [comment]
Thanks for the explanation there :) I did not notice, that there was a 0.99 instead of the 0.0.99.
