### ISSUE TITLE
When installing as MU Plugin CSS throws 404: /plugins/github-updater/css/github-updater.css

### ISSUE THREAD

**Issue by maxchirkov** [afragen/github-updater#786]
We have a standard process loading our MU Plugins on client's sites, which is direct deployment to the mu-plugins directory without the symlinks.  In such case the CSS file is not being found since its registration method assumes it's installed in the plugins folder:

https://github.com/afragen/github-updater/blob/develop/src/GitHub_Updater/Base.php#L150

Could you accommodate for MU Plugin case?

Thank you!

**Comment by afragen** [comment]
@maxchirkov I have created a process for loading the plugin as an mu-plugin. This allows for the plugin to be updated as I'm sure you know mu-plugins can't be updated in the normal plugin update process.

Have you tried installing as a mu-plugin using the provided instructions?

**Comment by maxchirkov** [comment]
I read the instructions, but it's not the point really... we service
thousands of sites and have a process of installing and updating MU
Plugins. Doing the symlink is not an option at the moment. While I
understand the premise, the "standard way" should not break either.

Max Chirkov

**Comment by afragen** [comment]
If you don't wish to do a symlink. I would suggest simply adding the https://github.com/afragen/github-updater/blob/develop/mu/ghu-loader.php file as an mu-plugin and installing GitHub Updater as a regular plugin.

This way you might not get updates to the `ghu-loader.php` file, but you would still get updates to the GHU plugin.

**Comment by afragen** [comment]
I still think the above is the correct way to include this as a mu-plugin, but the error you encountered should be fixed in the latest develop branch.

**Comment by maxchirkov** [comment]
Thank you, Andy!

Max Chirkov
