### ISSUE TITLE
Accept POST or update

### ISSUE THREAD

**Issue by clarkewd** [afragen/github-updater#787]
Github allows configuring a webhook after a repo has been updated:

[![webhook][1]][1]

But it can only send a POST request and it looks like this updater expects a GET request, something in this format:

    https://mysite.com/wp-admin/admin-ajax.php?action=github-updater-update&key=1234&theme=myTheme

Shouldn't there be a way to accept POST requests so that when working on a site the updates could be automatically deployed?

  [1]: https://i.stack.imgur.com/TUwpE.png

**Comment by afragen** [comment]
@clarkewd what git host is this?

**Comment by afragen** [comment]
I’ve been using Webhooks with GitHub for quite a while. Just enter the URL as your payload and set which action you wish it to send on.

GitHub Updater uses the $REQUEST so it doesn’t matter if it’s a GET or POST request.

**Comment by clarkewd** [comment]
great - I wasn't getting any response body with POST but looks like it's working. thanks!
