### ISSUE TITLE
Repo Homepage URL not correct in wp-admin / plugin details popup

### ISSUE THREAD

**Issue by klihelp** [afragen/github-updater#791]
Using WP 5.2, the plugin details popup shows wrong homepage url.

**Comment by afragen** [comment]
What does the plugin details pop up show you for the GitHub Updater plugin?

**Comment by afragen** [comment]
I think I see where the issue might be and unfortunately it’s a bit intermittent. Thanks for bringing this to my attention.

**Comment by afragen** [comment]
This really wasn't particular to any WP version. I simply used the parsed `GitHub Plugin URI` instead of the `Plugin URL`. If a short syntax URI was used this resulted in an incorrect homepage link.

Let me know if this is fixed for you in the `develop` branch.

**Comment by klihelp** [comment]
Works, at plugin details popup the Plugin Homepage link shows the Github project url.
