### ISSUE TITLE
Public Repo Gitlab API returns 404

### ISSUE THREAD

**Issue by rwsss** [afragen/github-updater#793]
I have a public test repo at https://gitlab.com/eugene.gorelikov/wp-plugin-repo

Submitting either aforementioned repo URL or /eugene.gorelikov/wp-plugin-repo

Results in the following API URL: 
https://gitlab.com/api/v4/projects/eugene.gorelikov%2Fwp-plugin-repo%2F-%2Farchive%2Fmaster%2Fwp-plugin-repo-master/repository/archive.zip
?sha=master

returns:
{"error":"404 Not Found"}

could you please look into it?

**Comment by afragen** [comment]
I’m almost certain the issue is that your user has a `.` in it and the `parse_url()` cannot correctly handle that. 

I realize it’s a limitation but the ability to parse the URI is essential to proper function.

**Comment by rwsss** [comment]
Seems like removing the dot really worked. Thank you very much.
