### ISSUE TITLE
GitHub Updater Error Code: 401

### ISSUE THREAD

**Issue by PthPndr** [afragen/github-updater#796]
OK, here's an odd one,

I have to make a couple of hard-coded language changes to the "The Events Calendar" so I keep a copy of it in a private repo on BitBucket. I use your wp.org override filter so it only looks to my copy for updates.

![Home](https://user-images.githubusercontent.com/11739012/59425621-5020f180-8da4-11e9-8750-fd5df64e5847.png)

When using your "The Events Calendar Category Colors" plugin I get the 401 error on it that it cannot connect.

![Category Colors](https://user-images.githubusercontent.com/11739012/59425937-ef45e900-8da4-11e9-95b6-26855baee0f9.png)

I mention this because it only appears to fail if "The Events Calendar" is in the override filter. When testing I tried other plugins such as "Event Tickets" and "WooCommerce" and everything worked fine.

The problem also only seems to appear after about a day, It does not occur immediately.

I hope that makes sense?

**Comment by afragen** [comment]
Can you install the support plugin. https://github.com/afragen/github-updater-support

It will install the WP Debugging plugin and ask you to install Query Monitor. QM will let you see any HTTP request errors. Those should provide more information.

**Comment by PthPndr** [comment]
OK, I'm getting a 401 Unauthorized error:

https://api.github.com/repos/afragen/the-events-calendar-category-colors/contents/the-events-calendar-category-colors.php?ref=master&access_token=759cc7afdfb5c5867ab1164e57f1d4ef20b765db

Which is odd, because when I first set it up the category colors does look at the WordPress repository (has WP logo next to it).

**Comment by afragen** [comment]
What’s odd is that I can put that URL into a browser and it works fine. Can you screenshot the QM error?

It seems the issue is with your override of `The Events Calendar`. Can you share the code you use in your override filter.

**Comment by afragen** [comment]
Was this previously working correctly? I may need access to your version of TEC to test.

**Comment by PthPndr** [comment]
Sure thing. Here's the filter:

`
	/*-----[GITHUB UPDATER DON'T USE WP.ORG REPO]-----*/
	add_filter( 'github_updater_override_dot_org', function() {
		return [
			'event-tickets/event-tickets.php',
			'the-events-calendar/the-events-calendar.php',
			'woocommerce/woocommerce.php',
		];
	});
`

![Query Monitor](https://user-images.githubusercontent.com/11739012/59449812-dace1480-8dd5-11e9-9a61-79de1cd4dec9.png)

We've only used this combination for a few months, I don't recall it working correctly.

**Comment by PthPndr** [comment]
I added you to the repository. Here's the url:
https://bitbucket.org/mystudioengine/the-events-calendar

**Comment by afragen** [comment]
I’ll take a look later today and see if I can replicate this.

**Comment by afragen** [comment]
Wow, this was a real edge case. @PthPndr let me know if it's fixed for you. I works for me.

**Comment by PthPndr** [comment]
Haha, I'm sure it was. It's been running for a day, all looks good. Thank you very much for taking care of this.

**Comment by afragen** [comment]
I fixed another related bug where I wasn't saving a proper response if no tags were present. It caused GHU to constantly send the API call looking for a good response.

https://github.com/afragen/github-updater/commit/1550833b6f5084ca2d9f4fa90a331baf10378adc

**Comment by PthPndr** [comment]
Yeah, that looks like it fixed the other problem I was seeing with all the front-end requests. Looks a lot better now.
