### ISSUE TITLE
Pages load slow in on the front-end

### ISSUE THREAD

**Issue by PthPndr** [afragen/github-updater#797]
OK, so I have another one. Starting with 8.8.0, I noticed that going between pages on the front-end (while logged in, for admin users) is a lot slower than before.

Using Query Monitor I noticed that there are no github-updater HTTP API Calls while using 8.7.3 but with 8.8.1 there are 23 calls for a total of 5.4 seconds.

**Comment by afragen** [comment]
If you have any of the Remote Management preferences checked that’s the only way for GHU to run in the front end. Also, using the support plugin bypasses background processing so the combination might be what’s happening. But even so this should only happen when the cache is expired.

If you are seeing the same HTTP requests then something isn’t saving correctly to the options table or you’re having a cache issue with an installed object cache.

**Comment by PthPndr** [comment]
Gotcha. We do use one of the Remote Management options and deselecting it got rid of the API  calls so that is it. Thanks.
