### ISSUE TITLE
Cron not finishing and some php warnings

### ISSUE THREAD

**Issue by SparkleGear** [afragen/github-updater#798]
Getting this message at the top of my admin pages,
```
GitHub Updater Information	
Please be patient while WP-Cron finishes making API calls.
```
and while trying to figure out why I noticed some entries in my debug.log
```
[02-Jul-2019 18:27:16 UTC] PHP Notice:  Undefined index: github_updater in /
var/www/dcr8r.com/wp-content/plugins/github-updater/src/GitHub_Updater/Settings.php on line 641
[02-Jul-2019 18:27:16 UTC] PHP Warning:  array_merge(): Argument #2 is not an array in /var/www/dcr8r.com/wp-content/plugins/github-updater/src/GitHub_Updater/Settings.php on line 641
```
I am using a cron triggered of of crontab with the WordPress cron turned off. I can get the github updater cron to complete using rhe "run now" option in crontrol.

Not sure if I have two issues or just one?

**Comment by afragen** [comment]
The first issue is that you will need to wait until your crontab fires. Out of curiosity what is your cronjob?

The second is just a notice. Have you saved any Settings?

**Comment by SparkleGear** [comment]
The crontab was firing, nothing overdue. I gave it a day to clean up. And the problem persisted

This is the crontab entry I am using 
`*/5 * * * * wget -q  https://mydomainname.com/wp-cron.php?doing_wp_cron >/dev/null 2>&1`

So here is the weird part...I installed the debug plugin and the message went away. I don't have an explanation but I will watch and see if updates propagate and the errors come back.

I have saved settings, and another weirdish behavior is my settings were lost. I had to re-enter my token to get things going again. No idea where that went.

I did notice something that might be easy to track down. When I installed the debug plugin it seems to have rewritten my wp-config.php with the wrong EOL characters. And I now have a double spaced wp-config.php file. 

If I figure any of this out I will post back

**Comment by afragen** [comment]
Can you try using `curl` instead of `wget`? https://github.com/afragen/github-updater/issues/795#issuecomment-501084305

The debug plugin bypasses wp-cron and background updating.

**Comment by afragen** [comment]
It’s possible the EOL character change came from https://github.com/wp-cli/wp-config-transformer/blob/e1024d71d695c19fed1bd32bebfe9004e4d6c090/src/WPConfigTransformer.php#L69

**Comment by afragen** [comment]
Closing issue. Please reopen if this is still an issue.
