### ISSUE TITLE
Multisite

### ISSUE THREAD

**Issue by marbaque** [afragen/github-updater#799]
Have you tried this plugin in multisite install?
I am able to install a theme but I can't update it or change branch.

**Comment by afragen** [comment]
This plugin has worked with multisite since it’s inception. It is recommended to network activate the plugin. As such, you will need to do all the updates and branch switching from the Network Admin pages, just like for any other multisite.

**Comment by afragen** [comment]
I have installed your theme `pemscores` and was able to see an update by decreasing the local version number and update successfully. I was also able to switch to the other branch, but the other branch doesn’t have the `GitHub Theme URI` so it doesn’t work with GHU.
