### ISSUE TITLE
Remote Management through WPMU DEV's The Hub

### ISSUE THREAD

**Issue by warudin** [afragen/github-updater#800]
Hi,

GitHub Updater has some options for remote management. Currently it can be done with iThemes Sync, InfiniteWP, ManageWP and MainWP.

We're using The Hub from WPMU DEV as our remote management tool. Would it be possible to make GitHub Updater work with this tool as well?

**Comment by afragen** [comment]
I’m not familiar with that one. Try checking any of the other boxes and see if it works. They all do the same thing.

**Comment by afragen** [comment]
I've created a universal remote updater for GitHub Updater repositories. [Git Bulk Updater](https://github.com/afragen/git-bulk-updater).

You can read more about it on this issue, https://github.com/afragen/github-updater/issues/803
