### ISSUE TITLE
Vagrant/VVV and Fopen

### ISSUE THREAD

**Issue by jshwlkr** [afragen/github-updater#801]
I'm running VVV locally, and I keep getting fopen errors when I try to install a theme or plugin (from GitLab). The error looks like this, for a theme (though it's basically identical for a plugin):  
  
`Warning: fopen(/srv/www/wordpress-one/public_html/wp-content/upgrade/archive-mwaSZv/microsite/style.css): failed to open stream: No such file or directory in /srv/www/wordpress-one/public_html/wp-includes/functions.php on line 5568`

`Warning: fread() expects parameter 1 to be resource, boolean given in /srv/www/wordpress-one/public_html/wp-includes/functions.php on line 5571`

`Warning: fclose() expects parameter 1 to be resource, boolean given in /srv/www/wordpress-one/public_html/wp-includes/functions.php on line 5574`

**Comment by afragen** [comment]
Unfortunately those errors are coming from inside wp core. It’s possible that it’s a permissions issue inside your VVV container. I’m not certain that I can help with this.

**Comment by jshwlkr** [comment]
Thanks!
