### ISSUE TITLE
GitHub Updater doesn't find my plugins

### ISSUE THREAD

**Issue by gregoriopellegrino** [afragen/github-updater#804]
I have installed the plugin on 5 WordPress installations and it works correctly, but on one (which is on the same server as the others) I don't get the two plugins managed on BitBucket.

I also tried to install from BitBucket, through the GitHub Updater plugin process, but once installed correctly, the plugin is not recognized...

Can you tell me how to debug the problem?

Gregorio

**Comment by afragen** [comment]
It almost seems as if there is no not a header set correctly.

Can you post the headers for one of the plugins in question?
Do the plugins show up in the Bitbucket tab of the Settings?

**Comment by gregoriopellegrino** [comment]
Here you have.

```
/*
	Effatà Multi Ecommerce

	@author      Gregorio Pellegrino
	@copyright   2016 Effatà Editrice
	@license     private

	@wordpress-plugin
	Plugin Name: Effatà Multi Ecommerce
	Plugin URI:  https://bitbucket.org/effata/eme.git
	Description: Settings and functions for multi ecommerce by Effatà
	Version:     0.1.0
	Author:      Gregorio Pellegrino
	Author URI:  https://effata.it
	Text Domain: effata-multi-ecommerce
	License:     private
	Bitbucket Plugin URI: https://bitbucket.org/effata/eme/
   */
```

The strange thing is that on other sites it works without problems...

**Comment by afragen** [comment]
Do you have the username/password set up correctly in the Bitbucket tab?

You can install and activate the [GitHub Updater Support](https://github.com/afragen/github-updater-support) plugin while you’re trying to work this out. It will install and ask to install a couple of other plugins to assist.

**Comment by gregoriopellegrino** [comment]
In this site the tab does not appear (this is what is strange), in the other sites inserted everything correctly and works.

**Comment by afragen** [comment]
Very strange. You might try re-installing the GitHub Updater plugin on that site. The simplest way to do this is to check the branch switch option and select the `master` branch.

**Comment by afragen** [comment]
How many Bitbucket plugins are installed on that site?

**Comment by gregoriopellegrino** [comment]
Reinstalled, but nothing.

There are two bitbucket plugins installed.

Is there a way to debug the function that parses plugins to look for URI information? I think the problem is there...

**Comment by afragen** [comment]
It would be a lot easier to give me `read` access to one of those plugins for testing. My Bitbucket username is `afragen`.

**Comment by afragen** [comment]
The fact that is seems to work correctly on your other sites seems to indicate that there might be issues with that particular site.

 What other plugins do you have installed and which ones are supposed to be interacting with GitHub Updater?

**Comment by gregoriopellegrino** [comment]
BitBucket asks me for an email address to add a user.

I'm debugging: the problem seems that `static::$extra_headers` on line 95 of file `src/GitHub_Updater/Plugin.php` is empty.

I'm continuing to investigate...

**Comment by afragen** [comment]
My email is on my profile. 

I wonder if you have any different plugins on that site that may be conflicting.

**Comment by gregoriopellegrino** [comment]
Ok, found.

The problem is with the line 273 on file `wp-admin/includes/plugin.php` (https://core.trac.wordpress.org/browser/tags/5.2/src/wp-admin/includes/plugin.php#L271)

On this installation the `wp_cache_get` loads a version of the plugin array without `extra_headers`.

Now I'm going to investigate which plugin is causing the problem.

**Comment by gregoriopellegrino** [comment]
Ok, found. The problem is with the plugin _Campaign Tracker for WordPress_ by _HelpForWP.com_ (https://helpforwp.com/)

In the `construct` method of their plugin they call `get_plugins()`:

```
if ( ! function_exists( 'get_plugins' ) ) {
	require_once ABSPATH . 'wp-admin/includes/plugin.php';
}
$all_plugins = get_plugins();
```

**Comment by afragen** [comment]
I’ll have to take a closer look at this. I think I’ve seen it before.

**Comment by gregoriopellegrino** [comment]
Thanks
