### ISSUE TITLE
Can't install theme via Settings

### ISSUE THREAD

**Issue by zandalartribe** [afragen/github-updater#805]
I've been developing a WP theme offline, and then pushing to a public GitHub and incrementing the version number. But when I try to install it on a live site via Settings > GitHub Updater > Install Theme, I get the following error:

```
Downloading installation package from https://api.github.com/repos/zandalartribe/zandalartribe/zipball/master…

Download failed. Not Found
```

Any idea why I'd be getting this error? It sounds like the zip isn't being found, but I don't know if your error messages are specific enough to discount something else (e.g. write permissions on the server).

**Comment by afragen** [comment]
This issue is that you can’t use a `.` in your repository name. The `parse_url()` function will give inaccurate results. The only solution, if you wish to use this plugin, is to rename your repository.

**Comment by zandalartribe** [comment]
@afragen Ah, thanks - I had seen that comment in reference to a previous bug, but never made the connection. Thanks for the super-fast response too! :)
