### ISSUE TITLE
Composer install failed

### ISSUE THREAD

**Issue by zecka** [afragen/github-updater#809]
I have the following error when i try to install with composer:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - afragen/github-updater 8.8.2 requires afragen/wordpress-plugin-readme-parser dev-master -> satisfiable by afragen/wordpress-plugin-readme-parser[dev-master] but these conflict with your requirements or minimum-stability.
    - afragen/github-updater 8.8.1 requires afragen/wordpress-plugin-readme-parser dev-master -> satisfiable by afragen/wordpress-plugin-readme-parser[dev-master] but these conflict with your requirements or minimum-stability.
    - afragen/github-updater 8.8.0 requires afragen/wordpress-plugin-readme-parser dev-master -> satisfiable by afragen/wordpress-plugin-readme-parser[dev-master] but these conflict with your requirements or minimum-stability.
    - Installation request for afragen/github-updater ^8.8 -> satisfiable by afragen/github-updater[8.8.0, 8.8.1, 8.8.2].
```

**Comment by zecka** [comment]
I add this on into composer.json:
  "minimum-stability": "dev"

But the update seems not work. Is it the right way to include update into a plugin ?

**Comment by afragen** [comment]
I’m not sure about this as I’ve never tried to install the plugin via composer. I do use composer to keep the requirements in GHU up to date.

I’ll have to see if I can duplicate it and if there’s a solution. You could use `WP-CLI` to install it.

`wp plugin install https://github.com/afragen/github-updater/archive/master.zip`

**Comment by afragen** [comment]
What does your `composer.json` file look like?

**Comment by zecka** [comment]
I tried to install the plugin via composer, so people who use my plugin doesn't have to install github updater plugin, this is my goal.

And this is my composer.json

```json
{
  "require": {
    "intervention/image": "^2.4",
    "rosell-dk/webp-convert": "^1.3",
    "afragen/github-updater": "dev-master"
  },
  "require-dev": {},
  "minimum-stability": "dev"
}
```

**Comment by afragen** [comment]
I’ll try to test that.

You should take a look at https://github.com/afragen/wp-dependency-installer I built it for exactly this and it’s much more versatile.

**Comment by afragen** [comment]
An example is at https://github.com/afragen/group-plugin-installer

**Comment by afragen** [comment]
Instead of `”minimum-stability”: “dev”` have you tried `“prefer-stabile”: true`

Don’t copy/paste as this keyboard is using smart quotes.

**Comment by afragen** [comment]
This might help, https://stackoverflow.com/a/21697174

**Comment by afragen** [comment]
The real problem with using `composer install` to install a WordPress plugin is that unless it designed to install into the `wp-content/plugins` directory it will never see an update.

**Comment by afragen** [comment]
I'll see if I can update the `composer.json` here to automatically put the plugin in `wp-content/plugins` and not in `vendor`.

**Comment by zecka** [comment]
But any chance to get the plugin work inside an other plugin ?

**Comment by afragen** [comment]
The plugin was not designed for that. It's possible but I don't recommend it at all.

I've pushed an update to the `develop` branch that will correctly install the plugin in `wp-content/plugins`. The only potential issue is the duplication of some vendor directory contents in both the site root and in the plugin root.

**Comment by afragen** [comment]
And yes, you do need the `"minimum-stability":"dev"`. Good advice.

**Comment by zecka** [comment]
Ok thank for your help.

So finaly i choose to use [TGM Plugin Activation](http://tgmpluginactivation.com/) to suggest to add github updater

**Comment by afragen** [comment]
That works.

I wrote [WP Dependency Installer](https://github.com/afragen/wp-dependency-installer) as a lighter weight option to TGMPA.

**Comment by afragen** [comment]
If you wanted to use my framework all you would need  to do is the following.

`composer require afragen/wp-dependency-installer:"^2"`

Add a `wp-dependencies.json` file to your plugin root with the following.

```json
[
  {
    "name": "GitHub Updater",
    "host": "github",
    "slug": "github-updater/github-updater.php",
    "uri": "afragen/github-updater",
    "branch": "master",
    "optional": false,
    "token": null
  }
]
```

Put the following after you have done your `require_once( __DIR__ . '/vendor/autoload.php' );`
```php
WP_Dependency_Installer::instance()->run( __DIR__ );
```

**Comment by brandonjp** [comment]
> Add a `wp-dependencies.json` file to your plugin root with the following.

Just a note, as of [April 2021](https://github.com/afragen/git-updater/commit/45d80d65c839cb45c063fe14d5560ab772996841), the `github-updater` repo was renamed to `git-updater` 

So if you're using [the code example above](https://github.com/afragen/git-updater/issues/809#issuecomment-536322718), you should use the code sample below instead, which changes `github-updater` to `git-updater` (otherwise you'll end up with some weirdness when it downloads the plugin twice)

```json
[
  {
    "name": "Git Updater",
    "host": "github",
    "slug": "git-updater/git-updater.php",
    "uri": "afragen/git-updater",
    "branch": "master",
    "optional": false,
    "token": null
  }
]
```
