### ISSUE TITLE
Install from release artifacts on GitLab doesn't work

### ISSUE THREAD

**Issue by jofbe** [afragen/github-updater#810]
Hi,
I'm very happy that I found this plugin. I comes really handy for my projects. Thank you!
In my current project, I have a wordpress theme, that has to be built before it can be installed. I want to store the source files only, so I thought that I can just upload the build to a release as an attachment. So this is what I do now:
- I push to master
- a CI script builds my theme, and uploads it to the commit as an artifact
- I create a tag with the same name as the version header in the style.css file
- I try to install the theme with github updater

At this point, the updater downloads the code from a link like this: `https://self_hosted_gitlab/api/v4/projects/group_name%project_name/repository/archive.zip?sha=master&private_token=xxxxx…` instead of `https://self_hosted_gitlab/api/v4/projects/{$this->response['project_id']}/jobs/artifacts/{$this->type->newest_tag}/download`. Of course it can't install the theme, because it tries to install the source files, not the built theme.

Can you advise please?

![Screenshot 2019-10-10 at 15 58 59](https://user-images.githubusercontent.com/2345809/66576165-86665600-eb77-11e9-9086-a61aa72bdc0c.png)
![Screenshot 2019-10-10 at 15 59 17](https://user-images.githubusercontent.com/2345809/66576166-86665600-eb77-11e9-97d8-a38fb97c2eac.png)
![Screenshot 2019-10-10 at 16 00 53](https://user-images.githubusercontent.com/2345809/66576167-86feec80-eb77-11e9-9623-4718c4b6880e.png)
![Screenshot 2019-10-10 at 16 01 27](https://user-images.githubusercontent.com/2345809/66576169-86feec80-eb77-11e9-8998-83a6430719f2.png)

**Comment by jofbe** [comment]
No, I didn't, sorry. Now I added it as well as `GitLab CI Job`. But how can I install the theme for the first time? What should be the Theme URI? When I go to the pipelines, and want to download the zip, the download link is `https://self_hosted_gitlab/group/project/-/jobs/10474/artifacts/download`

**Comment by afragen** [comment]
To install a release asset theme for the first time, Use the release asset URL in the Install Theme tab and select the Zipfile option. You will need to set the slug for the theme manually.

**Comment by jofbe** [comment]
Sorry for being so bothersome, but I still couldn't manage to install the theme. These are the setting I've tried:

`Theme URI: https://self_hosted_repo/group/slug/-/archive/1.1.2/slug-1.1.2.zip`
`Zipfile Slug: slug`
_Download failed. Not found_

`Theme URI: https://self_hosted_repo/group/slug/-/archive/1.1.2/`
`Zipfile Slug: slug-1.1.2` or `Zipfile Slug: slug` or `Zipfile Slug: slug-1.1.2.zip`
_The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature_

Can you tell me where in the documentation I should look for guidelines?

Also, when I downloaded the zip file manually, I saw, that the folder name in the zip file is not `slug`, but `slug-1.1.2`. Could that be a problem? In the `.gitlab-ci.yml` file I have `artifacts: paths: - slug.zip` set.

Thank you for your support.

**Comment by afragen** [comment]
You must be using an incorrect URL to install. Perhaps it would be easier to download the theme to your computer and simply upload it to your WordPress site to install, using the standard upload theme method.

**Comment by afragen** [comment]
I believe the issue for a direct install is that the asset requires a redirect. This redirect is picked up for updates but not for a direct install. That means that the initial install needs to happen from a download to your computer and then use the upload plugin pathway.

**Comment by jofbe** [comment]
When I'm trying to install from a zip file from a remote url, this is the message I get:

![Screenshot 2019-10-14 at 23 48 14](https://user-images.githubusercontent.com/2345809/66785394-6a4b1780-eedd-11e9-8c7e-3d3e3570bfbc.png)

So the main folder gets created, but it's empty.

**Comment by afragen** [comment]
I can’t really help much if all the relevant data is hidden. 

Can you DM me the URL in the Slack?

**Comment by afragen** [comment]
I've discovered that through the redirect of the asset URL, while it works in the browser, catching the redirect URL isn't present in the install process. 

This means that updating will work, but you will need to install from a downloaded zip file on your computer using the `Upload Plugin` or `Upload Theme` buttons that WP core uses.
