### ISSUE TITLE
Azure devops

### ISSUE THREAD

**Issue by crsanghani** [afragen/github-updater#812]
Will this work for a theme hosted in Azure devops?

**Comment by afragen** [comment]
As written the plugin shouldn't work with Azure devops. Depending upon Azure's API it might be possible. I have no way to test though.

It might be simpler to install a self-hosted git server like Gitea. Works on a Raspberry Pi.

**Comment by moshbopayoneer** [comment]
@afragen any chance you added support for Azure dev ops? is there an option to use Azure with the pro version?

**Comment by afragen** [comment]
@moshbopayoneer, As I previously said, if Azure's API can return the appropriate data then yes, an add-on plugin can be created similar to the other git host plugins. 

However, I don't have access to Azure to test or develop. This doesn't mean that someone else can't develop the add-on. I would be happy to help where I can.
