### ISSUE TITLE
Issue getting remote management to work

### ISSUE THREAD

**Issue by graemewetenhall** [afragen/github-updater#815]
Hello, 
First off thanks for this awesome plugin. Im probably getting stuck somewhere due to user error but cant get round it. Your help would be greatly appreciated. 

I started off with a private bitbucket repo but after hunting around I think this has not yet be solved as it requires user name and password to be saved within the theme?

Anyhow, I now have a private github repo with my theme files. 

https://github.com/graemewetenhall/bae-wp-theme

in the plugin settings I have added my GitHub Personal Access Token and saved it. 

After this I have gone to Remote Management and copy pasted my key into Github as a web hook adding theme name to the key url.

https://staginghylands.wpengine.com/wp-admin/admin-ajax.php?action=github-updater-update&key=000mykey000&theme=bae-wp-theme

My theme style.css is correct as when I try to update my theme manually using the plugin it says its not possible as the directory already exists. So i know its pulling the theme in ok. 

How ever the web hook gives me an error when pushing / checking via re deliver on the github website. 

{"success":false,"data":{"messages":"Theme not found or not updatable with GitHub Updater: bae-wp-theme","webhook":{"action":"github-updater-update","key":"000MYKEY0000","theme":"bae-wp-theme","webhook_source":"GitHub webhook"},"elapsed_time":"5.23 ms"}}

I cant seem to get past this error. 
Graeme

**Comment by afragen** [comment]
@graemewetenhall you're in luck. I've been re-writing the core functions to pulling data from plugins and themes so that the webhook works.

Thanks for the praise. 😊

GHU absolutely works with private Bitbucket repos. https://github.com/afragen/github-updater/wiki/Settings#bitbucket-private-repositories

Try using the branch switch feature to switch to the `develop` branch and let me know if these issues are fixed.

**Comment by afragen** [comment]
The BitBucket user/password is stored in the database, not in the theme.

**Comment by afragen** [comment]
@graemewetenhall you should take a look at [Git Remote Updater](https://github.com/afragen/git-remote-updater)

**Comment by afragen** [comment]
FWIW, you will need to ensure that everything is set up to correctly update from the dashboard to ensure that updating via webhook will work.

**Comment by graemewetenhall** [comment]
Hi Afragen, 

Thanks for taking the time to reply. 

- So iv taken some time today looking into Git Remote Updater. 
- I went into the Git Updater > Remote Management
- I generated a Jason File by clicking the button. 
- I then added my Git Repo to the Json file file and uploaded it. 
- I can now see the repo in the Git Remote Updater dash. 
- when i click update I get 

probrickhill.wpengine.com: bae-wp-theme
417 Expectation Failed
Theme not found or not updatable with GitHub Updater: bae-wp-theme

Same error message from earlier? 

I modified the WebHook in gtithub so now its exactly the same as the url provided to me in the github updater dashboard page. Same page I generate the Json file from? 

I cant figure out what im missing?

**Comment by afragen** [comment]
@graemewetenhall you shouldn't need to add anything to the generated JSON file. It should automatically contain data for all installed GitHub Updater based plugins and themes.

Do you have the theme installed on your site?

Are you using the most updated version of GitHub Updater on your site? Use the branch switching to re-install the `develop` branch.

**Comment by graemewetenhall** [comment]
@afragen hummm I thought that might be the case how ever when I add my branch details to the install theme tab they dont appear to be saved anywhere? Should i be able to see my branch in remote management with the checkbox next to it?

**Comment by afragen** [comment]
Solved in Slack. Missing `GitHub Theme URI`
