### ISSUE TITLE
Missing Github Tab

### ISSUE THREAD

**Issue by webdiner** [afragen/github-updater#817]
I need to add my personal api key, but the Github tab is missing.

See: https://www.evernote.com/l/ALH81UjumJ5K3JBD6GI_IqeYfO1mRH0wk4s

**Comment by afragen** [comment]
What version and branch of the plugin are you using?

**Comment by webdiner** [comment]
Version 8.9.0.6 default branch

**Comment by webdiner** [comment]
Got it figured out. It was a cron issue.
