### ISSUE TITLE
Since last update it stopped finding theme updates

### ISSUE THREAD

**Issue by martifenosa** [afragen/github-updater#818]
Since the last update the plugin stopped finding updates when the theme on 'master' is updated. 
The only way we have to update the theme is to delete it and then 'Install theme' again. Its quite a small process but before was way faster. 

We use gitlab, maybe they changed something?

We have been using this plugin for a time now so I don't think we do anything wrong or different now.

**Comment by martifenosa** [comment]
We also have this on the 'Gitlab' tab:
![Screenshot 2019-11-06 at 13 50 06](https://user-images.githubusercontent.com/12196520/68299656-6a81a180-009c-11ea-8693-5827e6333dc2.png)
But it's weird because we are able to install the theme without any trouble, the problem start when we want to update. 

Thank's a lot!

**Comment by afragen** [comment]
Can you post the theme headers?

**Comment by martifenosa** [comment]
Sure. 
`
/*
 Theme Name: LLOS& Template
 Description: LLOS& Template
 Version: 1.3.2
 Author: LLOS&
 Author URI: http://llos.co
 License: GNU General Public License v2 or later
 License URI: http://www.gnu.org/licenses/gpl-2.0.html
 Text Domain: llos
 GitLab Theme URI: https://gitlab.com/llos/cett
 */
`

Is that alright? That was working for us until recently.

**Comment by afragen** [comment]
Can you try installing the support plugin, https://github.com/afragen/github-updater-support

It will install the Query Monitor plugin. Specifically I'm looking to see if there are any HTTP errors.

**Comment by martifenosa** [comment]
Done!

**Comment by afragen** [comment]
Are there any errors?

**Comment by martifenosa** [comment]
Hi again, sorry for the delay. 

It's the 'HTTP Api Calls' what you need? I have two 'Not found' errors in there. (I've erased the private token, not sure if it was necessary :P)
![Screenshot 2019-11-12 at 13 09 26](https://user-images.githubusercontent.com/12196520/68670768-fb012b80-054d-11ea-8959-95bf691dd834.png)

If you are after something else just tell me. 

Thank's!

**Comment by afragen** [comment]
Are you certain your access token is correct? Often a 404 error is what happens when you visit a private repo that you don't have privileges for. 

You might want to re-enter and save the token.

**Comment by dhrvuraj** [comment]
I have installed this plugins and also added my GIT Access token but It's not display the list of theme and plugins. Also its not auto-updated the installed plugins. So can you let me know what is wrong over here?

**Comment by afragen** [comment]
@dhrvuraj thank you for creating a separate issue.

**Comment by martifenosa** [comment]
Hi again,
sorry for the delays. 

I've tried what you say, enabling all privileges on the token. It keeps failing to update.

The weird thing is that it was working fine few weeks ago and all of a sudden it stopped working on the new sites. I'm not the only one experiencing this on the office.  

May be something gitlab has updated for the new generated tokens? We all use the same private company repo. As I said it's weird because the old sites (pointing to the same repos) still work fine, it's just the new ones. 

Do you have any other ideas on what may be causing this?

**Comment by martifenosa** [comment]
One member of the team just said to me that one of the repos started working again. I'll keep you posted.

**Comment by afragen** [comment]
Several months ago GitLab _updated_ it's API and I seem to remember needing to make new tokens and I had to update GHU to work with the new, _relatively undocumented_, API.

**Comment by afragen** [comment]
Should I assume everything's working?

**Comment by martifenosa** [comment]
Yes! Sorry, I completely forgot to tell you. 
I don't know what changed, my guess is this was a Gitlab issue, not an issue of the plugin.
Thank's!
