### ISSUE TITLE
Didn't get the list of Plugins and themes

### ISSUE THREAD

**Issue by dhrvuraj** [afragen/github-updater#821]
Hi @afragen,

I have installed this plugins in my latest WP site, and added GIT access token to setting(http://prntscr.com/pzced1) but I didn't get the list of plugin and theme here so can you let me know what is wrong here? 

Also if I try to installed single-single plugins using plugin URL with AccessToken than its worked but If I make the changes in plugins and push changes in GIT than after updated plugins is not automatically updates in WP or not display notification. 

So please let me know what is wrong so I will make it working. and you want site access then let make now how I can send you securely? 

Thanks

**Comment by afragen** [comment]
Do the plugins you added have the required `GitHub Plugin URI` header?

Can you share the headers for the plugins?

**Comment by saurabhshyara** [comment]
Hi @afragen - Thank you for your reply. Can I share my WP admin login? is there your skype or email so I will sent you details.

**Comment by dhrvuraj** [comment]
Hi @afragen <https://github.com/afragen> - Thank you for your reply. Can I
share my WP admin login? is there your skype or email so I will sent you
details.

**Comment by afragen** [comment]
I don't need access to your WP install. I could use a look at whatever plugins/themes you are saying don't work.

**Comment by dhrvuraj** [comment]
i can not see updates available for plugins or any list of plugins

**Comment by afragen** [comment]
Please take a look at the wiki, https://github.com/afragen/github-updater/wiki

My guess is that your plugins/themes don't have the appropriate header that enables them to work with GitHub Updater.

**Comment by dhrvuraj** [comment]
header means i have multiple plugins and themes to update

**Comment by afragen** [comment]
There needs to be a specific header in each plugin or theme that you wish GitHub Updater to work with. Please read the wiki, there's a lot of information there.

The header means a header in the main plugin file or in the theme style.css file.

**Comment by dhrvuraj** [comment]
hi Afragen/Github-Updater

i got this message after plugin update can you please help
Thanks for your help

**Comment by afragen** [comment]
@dhrvuraj we seem to be going in circles.

Let's pick a single plugin that you wish to update using GitHub Updater. What is the URL for that plugin?

**Comment by ahmader** [comment]
@dhrvuraj There is no list of plugins to be shown, you must install each plugin/theme alone. Then you will get the updates for the installed plugins/themes.

**Comment by dhrvuraj** [comment]
Now working thanks for help
