### ISSUE TITLE
Bootstrap::check_requirements() always returns true

### ISSUE THREAD

**Issue by chesio** [afragen/github-updater#824]
Hi Andy,

I noticed that (probably due to some refactoring) the [`Bootstrap::check_requirements()`](https://github.com/afragen/github-updater/blob/f14291d71b9ab0606fcf2a22df0d32de42ac6157/src/GitHub_Updater/Bootstrap.php#L89-L109) method always returns true as the actual check is done in the anonymous function hooked to `admin_init` hook - this function returns false if requirements are not met, but the return value is ignored in that context.

All in all, the [if-check](https://github.com/afragen/github-updater/blob/f14291d71b9ab0606fcf2a22df0d32de42ac6157/src/GitHub_Updater/Bootstrap.php#L63-L65) is currently useless.

**Comment by afragen** [comment]
Thanks, I'll fix that as soon as I can.

**Comment by afragen** [comment]
There was something about that not being loaded for translations if it wasn't in the hook but I'll test more.

**Comment by chesio** [comment]
In my plugins I tend to follow the advice given here: https://make.wordpress.org/plugins/2015/06/05/policy-on-php-versions/ It's an old post, but I think the advice still holds. Your implementation is fairly similar, but not entirely identical - the main difference is that when version check is done in main plugin file, only the main plugin file has to run on whatever minimum PHP version WordPress currently supports.

Here's an example of PHP 5.3 safe main plugin file that loads plugin that otherwise depends on PHP 7+ features: https://github.com/chesio/bc-cache/blob/develop/bc-cache.php I think it works fine with the translations, although I've never really tested that.
