### ISSUE TITLE
Multisite: theme and plugin disappearing in GitHub Updater list

### ISSUE THREAD

**Issue by Larzans** [afragen/github-updater#827]
I copied a multisite to a different domain, changed the urls and everything (GitHub Updater was already installed) and then removed the old theme and plugin and reinstalled it with GitHub Updater.

Everything went fine at first, installed theme + plugin from GitLab, but now (now idea what changed) i can't see the plugin and theme in the GitHup Updater configuration.
Also, when i try to reinstall them, the third input for the access token is not appearing, so i can't reinstall.

Clearing cache doesn't help, and when i activate the 'change branch option', save it, deactivate it and try saving again, i get an 
`Warning: array_merge(): Expected parameter 2 to be an array, null given in .../wp-content/plugins/github-updater/src/GitHub_Updater/Settings.php on line 649`
Warning.

Any idea where i can start looking for the configuration data of GitHub Updater and maybe figure out if sth. is missing?

**Comment by afragen** [comment]
Can you share the URL of either the plugin or theme you are trying to make work?

**Comment by afragen** [comment]
You might try re-saving the GHU settings.

**Comment by Larzans** [comment]
@afragen thanks for the quick answer, unfortunately i can't, it is an internal test site.
As i said, i already tried changing the branch options to force a GHU settings refresh, but got the second error.

Is there a way to reset all the GHU settings? Where do you store them?

**Comment by Larzans** [comment]
I also deleted the them, deleted the plugin, reinstalled the plugin, but still i can't see the 'access token' field when i try to a dd the gitlab repo again.

**Comment by afragen** [comment]
The plugin settings are in a site option 'github_updater'. If you delete the plugin from the plugins page all the settings should be deleted. You can then install the plugin again.

**Comment by afragen** [comment]
Are there any notices showing on the Settings page?

**Comment by Larzans** [comment]
No, no notices on the settings page, and i already deactivated + deleted, then reinstalled the plugin, but the access token input field still doesn't appear when i try to install a theme or plugin

**Comment by afragen** [comment]
How are you installing the new theme? If you use the Install Theme tab there will be an space for the token.

**Comment by afragen** [comment]
Can you screenshot the Settings page?

**Comment by Larzans** [comment]
Thats exactly the problem, it does not appear:
![image](https://user-images.githubusercontent.com/2615234/70639698-20f81980-1c3b-11ea-8d0b-d03ee34b6634.png)
No errors in the js console, the div is just not there (GHU 9.0.1)

**Comment by afragen** [comment]
Very curious. I haven't touched that particular code in a while.

Are the extra settings present for other remote repository host types?
Are they present on the Install Plugin tab? It uses the same code.

What does the Settings tab look like?

You must have something that is modifying the `label` as I don't have anything that adds `data-children-count`.

**Comment by Larzans** [comment]
Yes, only GitHub + GitLab don't have the extra fields.
Install Plugin behaves the same.

Settings normal (i think)
![image](https://user-images.githubusercontent.com/2615234/70649199-edbe8600-1c4c-11ea-8dfb-caff4f1cb28c.png)

**Comment by afragen** [comment]
Something is clearing not working on your installation. There should always be a `GitHub` tab as the GitHub Updater plugin should show here.

Can you install and activate the support plugin? https://github.com/afragen/github-updater-support

**Comment by afragen** [comment]
If you create a new default local environment with only the GitHub Updater plugin, what does it look like?

Also, what are you using for your local environment, what version of WP, etc. This info can be found under _Environment_ in the Query Monitor plugin. It will be installed with the support plugin.

Do you have anything running that would alter the DOM or add elements like the `data-children-count` above?

**Comment by Larzans** [comment]
good questions, the problem is that this is our test system, i don't have it installed locally, i will try to replicate the problem on a local install when i find time, to see whats happening there.

**Comment by afragen** [comment]
@Larzans can you post the plugin and theme headers?

**Comment by Larzans** [comment]
I now also get this error on the system:

`GitHub Updater Error Code: There may be a problem with WP-Cron. A GitHub Updater WP-Cron event is overdue.`

It looks like the updater does not even instatiate the GitHub_API class...

**Comment by afragen** [comment]
That notice says that WP-Cron is overdue. You can bypass WP-Cron by using the GitHub Updater support plugin.

**Comment by Larzans** [comment]
I also realized that the webpage i copied from has the following error when i want to update the theme:

    Warning: printf(): Too few arguments in .../wp-content/plugins/github-updater/src/GitHub_Updater/Theme.php on line 399

Don't know if that might be related.

**Comment by afragen** [comment]
Unfortunately I've never been able to recreate these issues.

Can you start with a fresh WP install and only include the relevant GHU related plugins?

**Comment by afragen** [comment]
Without a copy of either the plugin or theme to test with, I am unable to determine where the issue exists.

**Comment by Larzans** [comment]
Hi, i activated the the "Bypass WP-Cron Background Processing for Debugging" setting, and that fixed my problem, i can now add the GitLab access tokens and the updates show up as they should, even when i deactivate the setting again.

Even though we still don't know what the source was, with that setting the plugin works again.

Thank you very much for the support and the great plugin!

**Comment by afragen** [comment]
I believe the issue is related to having an invalidated access token. Bypassing the background updating allows GHU to show all the errors.
