### ISSUE TITLE
can't connect to Bitbucket Server

### ISSUE THREAD

**Issue by photocurio** [afragen/github-updater#830]
I'm having an issue connecting to an enterprise Bitbucket server. None of my themes and plugins can connect to the server. I have tried setting the Bitbucket URI with these formats:

- https://bitbucket.dev-intranet.fbcna.com:8443/projects/FMCMEW/repos/helpdeskwiki
- https://bitbucket.dev-intranet.fbcna.com:8443/projects/FMCMEW/helpdeskwiki
- https://bitbucket.dev-intranet.fbcna.com:8443/FMCMEW/helpdeskwiki

I have entered my username and password of course. None of the themes or plugins can connect to their repos, as you can see by the red mark:
![image](https://user-images.githubusercontent.com/5224038/71101848-62ca1800-2185-11ea-92b7-618785a04029.png)

**Comment by afragen** [comment]
Please refer to the wiki. https://github.com/afragen/github-updater/wiki/Self-Hosted-or-Enterprise-Installations#bitbucket-server-support

Unfortunately a simple copy paste of the URL for Bitbucket server doesn’t work. 

Your last example should work, though I’m not certain if WP core is doing something it shouldn’t with the port. I don’t have a server on a different port to check.

**Comment by afragen** [comment]
This might be related. https://github.com/afragen/github-updater/issues/491

**Comment by photocurio** [comment]
@afragen I tried adding the "allow_unsafe_urls" filter, but this does not permit connections to Bitbucket. In any case, allowing all unsafe connections seems like a crude (and not so safe) solution.

**Comment by afragen** [comment]
@photocurio can you temporarily install the support plugin, https://github.com/afragen/github-updater-support

It will add a bunch of debugging stuff including Query Monitor. What are the HTTP GET errors?

**Comment by afragen** [comment]
Please make sure your installation of Bitbucket Server is up to date.

**Comment by Idealien** [comment]
Potentially encountering same issue.
Bitbucket Plugin URI: https://privatebitbucketserver.com/wp/exampleplugin/

When I debug down to github-updater\src\GitHub_Updater\API\Bitbucket_Server_API.php and the multiple get_remote series functions, the API call is going out to https://privatebitbucketserver.com/rest/api/1.0/wp/repos/exampleplugin/

However for all versions BB Server [v5 - v7 at least the docs reference](https://docs.atlassian.com/bitbucket-server/rest/7.0.0/bitbucket-rest.html) https://privatebitbucketserver.com/rest/api/1.0/**projects**/wp/repos/exampleplugin/

I can confirm via Postman that I get a 404 response if I do not have the projects portion of path.

If there's a valid case where different versions/types might be required, I am working on a branch that would submit as PR following this pattern if it would be accepted to add filters to support such as:

```
public function get_remote_tag() {
		/**
		* Filter to return the Bitbucket API path for the selected repository tags
		*
		* @since 9.3.2.3
		* @return string
		*/
		$path = apply_filters( 'github_updater_bitbucket_api_tags', '/1.0/:owner/repos/:repo/tags' );
		return $this->get_remote_api_tag( 'bbserver', $path );
	}
```

**Comment by afragen** [comment]
@Idealien my problem is I don’t have an account on a Bitbucket server install, makes testing difficult. Can you confirm your Bitbucket server is on latest version?

**Comment by Idealien** [comment]
@afragen Sadly no (5.4) but the linked API docs confirm the path changes from [v5](https://docs.atlassian.com/bitbucket-server/rest/5.0.0/bitbucket-rest.html) thru [v7](https://docs.atlassian.com/bitbucket-server/rest/7.0.0/bitbucket-rest.html) as latest all match.

I will submit PR with the filters that I've now confirmed make it customize-able for any most API endpoint changes that are/may introduce in future.

FYI - The github_updater_set_options is amazing pattern. I wish so many more WP plugins had configuration-as-code options like it. Thanks!

**Comment by afragen** [comment]
I would rather try to ensure the API calls are correct than put a filter in that I’m not sure I would be able to assist a user in figuring out what they need to add. I’ll take a look at the referenced API and see if I can figure it out. Having a temp account would help me test, hint hint 😉

**Comment by photocurio** [comment]
@afragen I suspect that my problem was connected to the certificate chain used by the corporation.  The plugin seems to think its a self-signed cert.

**Comment by Idealien** [comment]
> I suspect that my problem is connected to the certificate chain used by the corporation. The plugin seems to think its a self-signed cert.

I encountered that in addition to issue with the endpoints being called. I was able to address that via https://developer.wordpress.org/reference/hooks/http_request_host_is_external/ or customizing the sslcertificates attribute to add what bundle is needed for the wp_remote_get/post to work. See https://developer.wordpress.org/reference/classes/WP_Http/request/ for more detail.

Can you confirm for your BB Server setup what version you are using and whether both of the example URLs below return a JSON data for one of your repos? Changing WP and exampleplugin to match your env along with the hostname.

https://privatebitbucketserver.com/rest/api/1.0/projects/wp/repos/exampleplugin/
https://privatebitbucketserver.com/rest/api/1.0/projects/wp/repos/exampleplugin/

**Comment by afragen** [comment]
@photocurio @Idealien can you test the latest `develop` v9.3.2.3 and see if it fixes these issues?

**Comment by photocurio** [comment]
@afragen I'll test it tomorrow.

**Comment by Idealien** [comment]
@afragen - No luck with latest in develop. But seeing where you're aiming with it,
[idealien/bb_api_strings](https://github.com/Idealien/github-updater/blob/feature/bb_api_strings/src/GitHub_Updater/API/Bitbucket_Server_API.php) has a set of strings which do work for 5.4.1.

Basically it's a swap of /projects/1.0/~:owner/ --> /1.0/projects/:owner/

**Comment by afragen** [comment]
Let's see if https://github.com/afragen/github-updater/commit/2bca6decaf789f1c1701bee3426844b4f3f8f0bc fixes it.

**Comment by afragen** [comment]
I don't see `latest` in any of the current API calls. Are we sure it's correct?

Currently found in remote install and branch switching for tags.

**Comment by Idealien** [comment]
Confirmed that 9fcaee60 does work with my environment. Thx so much!

I have a separate issue on when the WP environment is aware of new versions from BB, but I think that is a combination of wp-cron and the constants I do/don't have set. Will open separate ticket if/when I can accurately reproduce.

**Comment by afragen** [comment]
@Idealien have you tested the download for update and the branch switching to both branch and older tag? I just want to be certain that the download links, without `latest` are correct.

**Comment by Idealien** [comment]
@afragen - Yes. Both work as expected.

Only odd thing I encounter, which I expect is a case of working as designed versus bug and having not used the branch option previously, is that under the 'Try another version' link, there is no way to select the most recent tag. In this screenshot case latest tag being 1.5.
![image](https://user-images.githubusercontent.com/4549984/76425281-c4aeae00-637f-11ea-870d-be2f45980e94.png)
Selecting Master from the branches, or the 'update now' link are the two ways to get it to update to 1.5.

**Comment by afragen** [comment]
@Idealien that is a case of _working as designed_. 

The idea is that `master` should be the latest release, therefore they should be identical. Perhaps that's just me forcing development practices of having a `develop` and a `master` branch as bases. Oh well.

In the above screenshot the update would be served from the tag.

**Comment by afragen** [comment]
@Idealien thanks for testing. 🥰
