### ISSUE TITLE
Can't change bitbucket settings

### ISSUE THREAD

**Issue by danieldekay** [afragen/github-updater#831]
I can't connect to my private bitbucket theme and plugins. 
I tried to change my BB app password, and enter that into the Github updater settings page, but it will not save them, but revert to the old bitbucker login/pw.
Even after deleting the plugin, reinstalling, and also deleting the corresponding item in the database itself, it STILL reverts to the old bitbucket login/pw.
Even changing the settings in the database directly won't work.

**Comment by afragen** [comment]
That’s bizarre. The data is only stored in the database in side the `github_updater` option. 

It’s likely that you have a caching issue either in some object cache or in the browser. Try clearing all of these.

**Comment by danieldekay** [comment]
Totally.

I tried it again, after disabling caching.

1. I enter my bitbucket info, and click save. It shows my bitbucket info, as entered.
2. I switch over to the github tab, enter my api key there, and save.
3. When i switch back to the bitbucket tab I see my old data there.

**Comment by danieldekay** [comment]
I am getting PHP errors from the Github updater: 
<img width="1144" alt="Screenshot 2019-12-18 at 17 52 02" src="https://user-images.githubusercontent.com/1238268/71106219-3b903c80-21bf-11ea-8d56-b5d2017742d2.png">

Maybe that's an issue?

**Comment by danieldekay** [comment]
Maybe one step further, or down a different rabbithole:

There is an error message after I save my new bitbucket credentials (username/app key):
cURL error 56: GnuTLS recv error (-110): The TLS connection was non-properly terminated.

could be related to this? https://github.com/curl/curl/pull/3148

**Comment by afragen** [comment]
I have no idea what progressive basic auth is. Bitbucket provides 2 methods of authorization that I’m aware of, oAuth and Basic Auth. 

If you can give `afragen` read privileges I might be able to test. Have you tried testing in a local environment?

Can you also use a private browser window?

**Comment by danieldekay** [comment]
Can't add `afragen` - must be invited by email (? duh).

I tried in private browser window after you first replied... no difference.

**Comment by afragen** [comment]
My email is on the profile page.

**Comment by afragen** [comment]
Please reopen if this persists.
