### ISSUE TITLE
Option to remove Github access token

### ISSUE THREAD

**Issue by vinhtvu2** [afragen/github-updater#834]
I put in the wrong access token, and that token didn't have access to all of the repos.

Didn't see an option anywhere to remove the token.

**Comment by afragen** [comment]
You should be able to replace the token in the GitHub settings tab.

**Comment by vinhtvu2** [comment]
The "Github" tab goes away after putting in the key.

I'm on the latest version of Github and latest version of Github Updater.

Maybe it's only an issue on WordPress Multisite? I'll test on a single site instance to see if it's an issue.

Uninstalling and reinstalling the plugin will remove the token.

**Comment by afragen** [comment]
I'll look into this more too.

**Comment by vinhtvu2** [comment]
Nevermind. Ignore. I wasn't on the latest Github Updater 👎 It updated and now I can see it.

**Comment by vinhtvu2** [comment]
Thanks for the fast support!!!

**Comment by afragen** [comment]
I found I had this issue when I invalidated a previous access token and didn't change it prior to the cache timeout. 5e solution is in the latest release which adds an extra setting to bypass wp-cron. With this option checked the GitHub tab will display, along with several error notices, and allow you to re-enter a valid token. 😅💪
