### ISSUE TITLE
Delete cron events in uninstall.php

### ISSUE THREAD

**Issue by afragen** [afragen/github-updater#835]
From https://digwp.com/2019/11/wordpress-uninstall-php/

// delete cron event
$timestamp = wp_next_scheduled('myplugin_cron_event');
wp_unschedule_event($timestamp, 'myplugin_cron_event');

**Comment by chesio** [comment]
I'd suggest to do so on plugin deactivation already: https://developer.wordpress.org/plugins/plugin-basics/activation-deactivation-hooks/ I can't see any use for cron jobs set by inactive plugin.
