### ISSUE TITLE
PHP Warnings 

### ISSUE THREAD

**Issue by maxchirkov** [afragen/github-updater#836]
These PHP Warnings were thrown during WP-CLI `wp option get stylesheet` call. This is part of my automated process, which was thrown off by the warning. To overcome the issue I added `(array)` notation in front of `$repos_arr` on line #135:
[https://github.com/afragen/github-updater/blob/develop/src/GitHub_Updater/Theme.php#L135](https://github.com/afragen/github-updater/blob/develop/src/GitHub_Updater/Theme.php#L135)

```
[root@] out: PHP Warning:  array_filter() expects parameter 1 to be array, null given in /var/www/html/www.test.net/wp-content/mu-plugins/github-updater/src/GitHub_Updater/Theme.php on line 141
[root@] out: Warning: array_filter() expects parameter 1 to be array, null given in /var/www/html/www.test.net/wp-content/mu-plugins/github-updater/src/GitHub_Updater/Theme.php on line 141
[root@] out: PHP Warning:  array_merge(): Argument #1 is not an array in /var/www/html/www.test.net/wp-content/mu-plugins/github-updater/src/GitHub_Updater/Theme.php on line 156
[root@] out: Warning: array_merge(): Argument #1 is not an array in /var/www/html/www.test.net/wp-content/mu-plugins/github-updater/src/GitHub_Updater/Theme.php on line 156
```

**Comment by afragen** [comment]
Are you using the `develop` branch? The fix is not yet in the `master` branch, but should be soon.

This was fixed here, https://github.com/afragen/github-updater/blob/develop/src/GitHub_Updater/Theme.php#L128

**Comment by afragen** [comment]
#823
