### ISSUE TITLE
Admin Dashboard Menu positions

### ISSUE THREAD

**Issue by Raruto** [afragen/github-updater#838]
Since this is also a tool to install components.

Don't you think it would be better to also **add a submenu in the Tools section**? 

_isn't it somewhat counterintuitive to install something via the Settings menu?_

**Comment by afragen** [comment]
But the method to install a plugin or theme is in the Plugin and Theme menu, sometimes more hidden than other times. 

The benefit of having it in the GHU Settings is no one will confuse what’s doing the install. I think having settings and functions in many different locations may cause confusion and I don’t think I’ve ever ever had a user report it was confusing.

**Comment by Raruto** [comment]
> But the method to install a plugin or theme is in the Plugin and Theme menu, sometimes more hidden than other times.

I agree, but I don't think we're going to change the default behavior of those pages ...

> The benefit of having it in the GHU Settings is no one will confuse what’s doing the install. I think having settings and functions in many different locations may cause confusion and I don’t think I’ve ever ever had a user report it was confusing.

This is conceptually wrong and a UI design error:

a. the **Settings** section should only be used to **customize the default behavior** of a plugin / wordpress.
b. the **Tools** section should only contain functions that allow you to **perform operations** on the wordpress database
c. for **hybrid solutions**, you should instead use a **Parent Menu** ...

Currently, the only setting that can be edited from UI is _branch switching_, the rest are _import_ / _export_ and _reset_ functions ...

---

**Example Cases:**
- ( a + b )
  - **BuddyPress** [Settings](https://mercime.files.wordpress.com/2016/04/bp-options.png) / [Tools](https://plugintests.com/results/bu/dd/ypress/4.1.0/screenshots/admin-8-tools-buddypress.png)
  - **BBPress** [Settings](https://ps.w.org/bbpress/assets/screenshot-4.png?rev=872931) / [Tools](https://plugintests.com/results/bb/pr/ess/2.6.3/screenshots/admin-8-tools-forums.png)
- ( c )
  - **WooCommerce** [Menu](https://ps.w.org/woocommerce/assets/screenshot-1.jpg?rev=2074177): 
  - **JetPack** [Menu](https://dab1nmslvvntp.cloudfront.net/wp-content/uploads/2016/09/1473888433WordPress-Jetpack-Interface-New.gif)

---

Moreover, adopting the (a + b) solution it would be also easier to define some default global settings (eg. Git Host tokens and the [other ones](https://github.com/afragen/github-updater/wiki/Developer-Hooks))

**Comment by afragen** [comment]
Does this mean I'll need to create 2 different _settings_ pages? One for tools and one for settings.

**Comment by Raruto** [comment]
In case (a + b), this should be the correct division:

![screenshot-5](https://user-images.githubusercontent.com/9614886/72275799-ed8c1e80-362e-11ea-8d2f-c2c95e2f80b8.png)

Furthermore, the **Settings Page**, should always display the following tabs: **GitHub, GitLab, Bitbucket, etc.**, even if there are no relative plugins / themes installed.

**Comment by afragen** [comment]
I'm going to have to think about this. I'm not sure the added complexity is worth it.

**Comment by afragen** [comment]
> Furthermore, the **Settings Page**, should always display the following tabs: **GitHub, GitLab, Bitbucket, etc.**, even if there are no relative plugins / themes installed.

If there are repositories registered with these git servers then the tab will display.

**Comment by Raruto** [comment]
> I'm going to have to think about this. I'm not sure the added complexity is worth it.

OK thanks for the info.

**Comment by afragen** [comment]
I think the majority use of this plugin is to set it and forget it. Yes you can install plugin/themes but thats an bonus feature, not the primary feature.

**Comment by Raruto** [comment]
Can anything be done regarding the following point?

> We could have a filter within the [`add_plugin_page`](https://github.com/afragen/github-updater/blob/a956811342eadc9cc3c990d7e8c97fe491c77f35/src/GitHub_Updater/Settings.php#L185) function? (to easily override those parameters)

_https://github.com/afragen/git-remote-updater/issues/3#issuecomment-575113590_
