### ISSUE TITLE
Show current plugin version in REST API Repos

### ISSUE THREAD

**Issue by Raruto** [afragen/github-updater#839]
Example call: [/github-updater/v1/repos](https://thefragens.com/wp-json/github-updater/v1/repos) + `?key=c5i7tys26be3we0ziz8o2wgbs07me6c2`

```
...

 {
   "slug": "github-updater",
   "type": "plugin",
   "branch": "master"
   "version": "9.1.0" <-- current installed version
 },

...
```
In this way you could view some more useful info witihn the [Git Remote Updater](https://github.com/afragen/git-remote-updater) plugin.

**Comment by afragen** [comment]
So what happens when the user is checking multiple sites and they have different versions of the plugin installed?

**Comment by Raruto** [comment]
> So what happens when the user is checking multiple sites and they have different versions of the plugin installed?

I think this is a problem related to the operation of **GRU**, which does not influence what information **GHU** could expose ...

**Comment by afragen** [comment]
I wasn't really trying to replicate something like MainWP or any of the other remote management plugins that report when the plugin needs updating. I was only trying to create a method of force updating a repo on multiple sites.

**Comment by Raruto** [comment]
> I wasn't really trying to replicate something like MainWP or any of the other remote management plugins that report when the plugin needs updating. I was only trying to create a method of force updating a repo on multiple sites.

OK, but I still don't understand why this type of information could not be included within the **GHU API**.

_It couldn't be useful to other developers too?_
