### ISSUE TITLE
Tips to force check for updates

### ISSUE THREAD

**Issue by Raruto** [afragen/github-updater#840]
Relying on the current **WordPress Updates** page:

![wordpress-update-notification](https://user-images.githubusercontent.com/9614886/72255046-03391e00-3606-11ea-8bc4-4692f26269c5.png)

I think it would be a good thing:
- **add an info line** about the last run of wp-cron
- **rename the button** to something more explanatory
- **disable or gray the button** when waiting for a forced execution of wp-cron

---

![screenshot-12](https://user-images.githubusercontent.com/9614886/72255232-80fd2980-3606-11ea-8e73-c46d96f3b7b3.png)

**Comment by afragen** [comment]
What problem does this solve?

It's clear from the Settings page if WP-Cron is running or needing to run. The 12 hour cache is noted in the wiki, https://github.com/afragen/github-updater/wiki/Settings

What text for the `Refresh Cache` button do you think would be more clear?

**Comment by Raruto** [comment]
> What problem does this solve?

The user experience would be more similar to how **Wordpres Updates** already works.

In particular:
- `Refresh Cache` **is not** a **self-explanatory** button ( which of the many caches? )
- if you want to `Check for Updates`, clearing cache isn't the first thing that comes to your mind...
- if you want to quickly see when the last check was executed ( without installing additional software )

> It's clear from the Settings page if WP-Cron is running or needing to run. 

Good, but i think it would be better to add a link like [`» learn more`](https://github.com/afragen/github-updater/wiki/Background-Processing) within the nag notification.

> The 12 hour cache is noted in the wiki, https://github.com/afragen/github-updater/wiki/Settings

Ok, but you can't expect everyone to remember it ...

_However, if in addition you know when the last correct execution was performed, you can easily understand if there are problems with your wp-cron system_

**Comment by afragen** [comment]
I have another notice that displays if it's been more than 24 hrs since WP-Cron has run.

**Comment by afragen** [comment]
There really is only one cache in GHU, yes there is a cache for each repository but the refresh clears all of them.

**Comment by Raruto** [comment]
> I have another notice that displays if it's been more than 24 hrs since WP-Cron has run.

Well, but this does not assure you that your system clock (or cron system) is working properly.
Only by seeing the date+time of the last cron-job run can you be absolutely sure.

In addition, **nag notifications are a good thing**, but the large distance between the action (click of the button) and the message displayed (notification at the top of the page) **does not always perform a fluid user experience** (so-called action and reaction system).

Nag mesagges are **more useful** if you want to display the **same message on multiple pages** (e.g. _waiting for wp-cron_) or inform the user of a **change of status** (e.g. _cache correctly cleared_).

> There really is only one cache in GHU, yes there is a cache for each repository but the refresh clears all of them. 

Ok, what i mean is that you should **see that button** more **from your end user point of view**.

---

This is what an average user expects to see (because this is **how updates works**):

![72255046-03391e00-3606-11ea-8bc4-4692f26269c5](https://user-images.githubusercontent.com/9614886/72356061-e590b500-36e8-11ea-9463-95ab8843ff05.png)


It is obvious that doing so **it will also update the cache** (but this is not the user's primary purpose...).

**Comment by afragen** [comment]
GHU is not meant to be everything. There are other plugins, among them WP Crontrol that are excellent at showing cron issues and solving those problems.

Originally the Refresh Cache was not a separate button but tied to the Check Update button. This was problematic as the Check Update button checks a GET request for the query arg and the user could potentially refresh the page and never see updates as they may not have time to complete. The Refresh Cache works on a POST request specifically to stop this.

I'm closing this issue. I understand your passion but after thinking about it I don't have plans to alter the current process.

**Comment by Raruto** [comment]
OK, just for clarification,

what I meant was something like this:

![72255232-80fd2980-3606-11ea-8e73-c46d96f3b7b3](https://user-images.githubusercontent.com/9614886/72362078-cb5bd480-36f2-11ea-967e-c034e83b50b3.png)

---

_and **NOT** to hook / alter the default behavior of the **WordPress Updates** page..._

---

Have a nice day,
Raruto
