### ISSUE TITLE
Conflict with translation gives error "Warning: printf()"

### ISSUE THREAD

**Issue by nuriaheep** [afragen/github-updater#841]
Hi,

I get the error "Warning: printf(): Too few arguments in /usr/home/mywebsite.com/web/new/wp-content/plugins/github-updater/src/GitHub_Updater/Theme.pgp on line 556" instead the link with version number to update a theme that usually shows.

I found that if i deactivate the WPML plugins (WPML String Translation, WPML Multilingual CMS and WPML Translation Management) the error disappears and the link to update to the new version shows again and it can be updated with no more problems.

It is a conflict with the last version of WPML maybe? When i added the WPMLs the name of the plugin in the left menu of WP was automatically translated and I could not recognize the name until I went to String Translation, search for "GitHub Updater" and translate the string manually.

**Comment by afragen** [comment]
The issue seems to be with the WPML plugins changing something. You might want to raise the question on their forum.

I'm happy to help them debug, but I don't use WPML.

**Comment by nuriaheep** [comment]
Thanks! I will ask to WPML what happened
