### ISSUE TITLE
Installing theme is fine, updating theme no

### ISSUE THREAD

**Issue by paperplanefactory** [afragen/github-updater#842]
Hi Andy,
I've a strange issue: when installing this theme [paperplane-photography-theme](https://github.com/paperplanefactory/paperplane-photography-theme) (with github-updater) everything goes fine.
When I update theme the process completes without problems but it's like if the updater looks for a very old version of this theme with a completly different folders structure (but in fact it exhisted two weeks ago).
Is that ever happened? If you need more info just ask.

**Comment by afragen** [comment]
You will need to include the `Version` header in `style.css` so that GHU can parse it for it's update check.

GHU is able to Install a plugin or theme regardless of whether it can update it.

**Comment by paperplanefactory** [comment]
Isn't it already [there](https://github.com/paperplanefactory/paperplane-photography-theme/blob/master/style.css)?

**Comment by afragen** [comment]
Sorry, I need more ☕️ 

When you say the updater looks for an older version what do you mean?

**Comment by afragen** [comment]
I see what's happening. Your tagged release is problematic. If you tag releases any update will _always_ use the latest tagged release for updates. 

Deleting the tag should make it work as expected.

**Comment by paperplanefactory** [comment]
Sorry, I'm new to GitHub :)
It seems that updater looks for an old version of the master like [this one](https://github.com/paperplanefactory/paperplane-photography-theme/tree/da7606dbaf4a51fa9b5bc4a33e69ac16e9fa20ee)

**Comment by paperplanefactory** [comment]
Super! Thanks for your support and "complimenti" for your plugin!
