### ISSUE TITLE
BitBucket cURL Error 56

### ISSUE THREAD

**Issue by cbratschi** [afragen/github-updater#843]
Since today one of our servers returns the following error message:

cURL error 56: OpenSSL SSL_read: No error: 0
GET https://api.bitbucket.org/2.0/repositories/xxx/yyy/src/master/style.css

This is one of our dev servers. The staging copy of this dev server however works fine.

Strange is that this requests gets repeated on all page requests. There seems to be something wrong. We tried to clear the cache but this call is still there. This issue blocks us from updating themes on this system.

Any ideas?

**Comment by afragen** [comment]
Errors like that are typically server issues related to the GET request and not inherently within GitHub Updater. They are merely exposed via GitHub Updater.

I have found that similar errors clear within a short period of time.

I don't know if this is the issue but a quick Google search shows the following, https://stackoverflow.com/questions/46232906/git-clone-error-rpc-failed-curl-56-openssl-ssl-read-ssl-error-syscall-errno

If you can trace this back to GitHub Updater please let me know.

**Comment by cbratschi** [comment]
The callstack is:

```
Fragen\G\API->api()
wp-content/plugins/github-updater/src/GitHub_Updater/API.php:203
Fragen\G\API->get_remote_api_info()
wp-content/plugins/github-updater/src/GitHub_Updater/Traits/API_Common.php:114
Fragen\G\A\Bitbucket_API->get_remote_info()
wp-content/plugins/github-updater/src/GitHub_Updater/API/Bitbucket_API.php:101
Fragen\G\Base->get_remote_repo_meta()
wp-content/plugins/github-updater/src/GitHub_Updater/Base.php:291
Fragen\G\Theme->get_remote_theme_meta()
wp-content/plugins/github-updater/src/GitHub_Updater/Theme.php:233
Fragen\G\Base->get_meta_themes()
wp-content/plugins/github-updater/src/GitHub_Updater/Base.php:183
Fragen\G\Base->load()
wp-content/plugins/github-updater/src/GitHub_Updater/Base.php:167
do_action('init')
wp-includes/plugin.php:478
```

**Comment by afragen** [comment]
As I said above, GHU is making a GET request as you initially described. The error displayed is response from your server to Bitbucket's server. GHU is simply surfacing the error, it is not causing the error.

**Comment by cbratschi** [comment]
Sure, the same call works fine on our staging server. We will try it tomorrow again and see if this issue disappeared.

**Comment by afragen** [comment]
FYI you should take a look at [Git Remote Updater](https://github.com/afragen/git-remote-updater)

**Comment by cbratschi** [comment]
@afragen Thanks, just integrated the remote updater into our build system and it works fine.

The failing network call is still there. Just checked the configured cron jobs but could not find anything unusual.

**Comment by afragen** [comment]
I’m glad the Git Remote Updater plugin is working for you. 

Are there any other Bitbucket hosted repos causing the same issues or so others work?

**Comment by afragen** [comment]
I’d really like your impressions on the Git Remote Updater if you have time.

**Comment by cbratschi** [comment]
All other repos work and the remote updater works too on the dev system. So this is quite strange. I guess some zombie settings are still active on this server.

The Remote Updater is very useful for us. We have a lot of WordPress instances and this will help a lot. Thinking about automatic testing and scheduler based updates.

Some ideas:

Getting the messages in realtime would be nice but probably this is too complicated to integrate.

Having a two-way communication could be useful i.e. get the version of the current theme and its installation date. In general: getting access to some WP CLI features through web calls could be very useful but probably out of scope for your plugin. For instance looking for missing plugins and automatic installations.

A Docker container for easy theme installations. We are already using Docker with theme folders on the local file system but not remotely.

Thanks again for the great work. Your plugins saved us a lot of time.

**Comment by afragen** [comment]
The REST API endpoints for `repos` does return the version number, but I have no way to properly display that data if there are different versions of the same repository on different sites. There’s really no way to get the installation date. 

The plugin was simply meant to push an update, not to see if an update was available or necessary.

**Comment by afragen** [comment]
You should take a look at https://github.com/afragen/wp-dependency-installer for automatically installing plugins.
