### ISSUE TITLE
Should warning messages displaying on plugins.php?

### ISSUE THREAD

**Issue by Raruto** [afragen/github-updater#844]
Is there a particular reason why a message like the following:

```
GitHub Updater Information
Please be patient while WP-Cron finishes making API calls. 
```
cannot / will not be inserted on the `plugins.php` page?

[source code](https://github.com/afragen/github-updater/blob/c1f02674571522c78496452440b546c8d4369117/src/GitHub_Updater/Messages.php#L53)  I'm referring to

**Comment by afragen** [comment]
I specifically try to only display notices on certain pages. Mostly just GHU Settings pages. Many people get annoyed with notices all over the place.

**Comment by Raruto** [comment]
Ok, then would it make sense to insert some info / warning inside the branch switcher?

![branch-switch](https://user-images.githubusercontent.com/9614886/72902901-88ba7d80-3d2c-11ea-953b-51486fca8ef2.png)

_... damn it worked until yesterday !_

**Comment by afragen** [comment]
That’s odd looking. I have no plans to add notices to anything other than an actual admin notice.

**Comment by Raruto** [comment]
> I have no plans to add notices to anything other than an actual admin notice.

Just for advice, when the calls are not ended you could also:

1. completely disable the branch switching selector
2. insert a warning icon in the branch switching selector

> That’s odd looking.

Could it be because the ['icons'](https://github.com/afragen/local-development) branch no longer exists?

**Comment by afragen** [comment]
The branch switching reports nothing is available. It would always show the default branch when the API checks are complete.

**Comment by Raruto** [comment]
> The branch switching reports nothing is available. It would always show the default branch when the API checks are complete.

But since wp-cron cannot end precisely because that branch does not exist anymore, the only solution is to uninstall it?

**Comment by afragen** [comment]
I'm sorry. That's my fault for deleting the branch before you had the opportunity to switch. I've done that to myself before too. 🤦🏻‍♂️

**Comment by Raruto** [comment]
> I'm sorry. That's my fault for deleting the branch before you had the opportunity to switch. I've done that to myself before too. 🤦🏻‍♂️

ok, I was just trying to understand better
