### ISSUE TITLE
Problem with WP-CLI

### ISSUE THREAD

**Issue by chesio** [afragen/github-updater#845]
Hi,

I'm not sure if anything changed in GitHub Updater or WP-CLI, but I'm getting the following error with GitHub Updater 9.2.1 and WP-CLI 2.4.0 on PHP 7.3:

```bash
> wp cli info
Error: Callable "Fragen\\GitHub_Updater\\WP_CLI\\CLI" does not exist, and cannot be registered as `wp github-updater`.
```

When I move the [following lines](https://github.com/afragen/github-updater/blob/7bf534e866013a95d3c6b4009e6380c4380fb62d/src/GitHub_Updater/WP_CLI/CLI.php#L18-L19) to the bottom of the [respective file](https://github.com/afragen/github-updater/blob/develop/src/GitHub_Updater/WP_CLI/CLI.php) (ie. after `CLI` class declaration), everything works again:

```php
// Add WP-CLI commands.
WP_CLI::add_command( 'github-updater', 'Fragen\\GitHub_Updater\\WP_CLI\\CLI' );
```

It seems like WP-CLI cannot resolve the class name at the point of registration and treats it as a callable and thus fails...

**Comment by tyrann0us** [comment]
I can confirm the error on PHP 7.1.

**Comment by afragen** [comment]
Is this error on a local environment or on you server?

**Comment by afragen** [comment]
I don't know if anything changed in WP-CLI but I saw this error too. I was attributing it, incorrectly, to a local environment.

I can confirm that @chesio's fix works and will be adding that to a release today.

**Comment by tyrann0us** [comment]
I get it in cronjob warn emails from my host. The cronjob runs a bash script with the following contents every 30 minutes:
```
#!/bin/bash
cd /path/to/project
php /path/to/project/bin/wp-cli.phar core update --quiet
php /path/to/project/bin/wp-cli.phar plugin update --all --quiet
php /path/to/project/bin/wp-cli.phar theme update --all --quiet
php /path/to/project/bin/wp-cli.phar cron event run --due-now --quiet
```

(It's a [SatisPress](https://github.com/cedaro/satispress) instance.)

**Comment by afragen** [comment]
Switch to the `develop` branch and confirm the fix please.

**Comment by afragen** [comment]
I found a better fix, I think. Unless I heard otherwise, will merge this later today.

**Comment by scoutbranding** [comment]
Confirmed. The changes in the `develop` branch fixed the issue.

**Comment by chesio** [comment]
Hi @afragen,

thanks a lot for fixing this so promptly! I can confirm the problem is gone in version 9.2.2.
