### ISSUE TITLE
PHP Warning: Creating default object from empty value

### ISSUE THREAD

**Issue by kingkool68** [afragen/github-updater#846]
Using the Query Monitor plugin a PHP warning was triggered when visiting my site

Message: `Creating default object from empty value`
Location: `wp-content/plugins/github-updater/src/GitHub_Updater/Plugin.php:469`

![image](https://user-images.githubusercontent.com/867430/73371269-72a84200-4283-11ea-9b5e-0d8e67c85a43.png)

**Comment by kingkool68** [comment]
Here is where the warning is triggered https://github.com/afragen/github-updater/blob/develop/src/GitHub_Updater/Plugin.php#L469

**Comment by kingkool68** [comment]
I just updated to version 9.2.1 and the issue appears to have gone away.

**Comment by afragen** [comment]
I'm glad, I was just looking at this and I don't know how that would be possible in current code. `$response` is clearly defined before that line.
