### ISSUE TITLE
Callable "Fragen\\GitHub_Updater\\WP_CLI\\CLI" does not exist

### ISSUE THREAD

**Issue by TBarregren** [afragen/github-updater#847]
WP CLI abort with following error message with github-updater version 9.2.1 installed:

    Error: Callable "Fragen\\GitHub_Updater\\WP_CLI\\CLI" does not exist, and cannot be registered as `wp github-updater`.

**Comment by chesio** [comment]
@TBarregren, update to version 9.2.2, see also #845.
