### ISSUE TITLE
Deprecation notice for authentication via URL query parameters

### ISSUE THREAD

**Issue by swinggraphics** [afragen/github-updater#850]
I have just a couple sites using Github updater, and I am inundated by these emails.

> On [date] your personal access token [token name] using WordPress/5.3.2; [site url]; GitHub Updater - https://github.com/afragen/github-updater was used as part of a query parameter to access an endpoint through the GitHub API:

> https://api.github.com/repositories/11239863/contents/github-updater.php

> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated.

> Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.

> Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

> Thanks,
The GitHub Team

**Comment by afragen** [comment]
See #848
