### ISSUE TITLE
9.3.0 upgrade breaks WP Mail SMTP email sending

### ISSUE THREAD

**Issue by EricBusch** [afragen/github-updater#852]
Hi

First, thank you for your plugin. It's super useful.

I use the [WP Mail SMTP](https://wordpress.org/plugins/wp-mail-smtp/) plugin along with Mailgun to send email from my website.

My site was sending emails just fine until upgrading to 9.3.0. Now my attempts to send email from the server returns a "Forbidden" message from Mailgun even though connecting to Mailgun via the command line + cURL works fine.

After deactivating the Github Updater plugin, my server can send emails again. Re-activate the Github Updater plugin and email sending breaks agains.

Any ideas what could have caused this?

Thanks
Eric

**Comment by afragen** [comment]
It’s possible that the Basic Auth header is interfering. I’ll see what I can do about removing it as soon after using it as I can.

**Comment by EricBusch** [comment]
Cool, thanks! Once you push out a fix, I'll test again.

**Comment by afragen** [comment]
Is it possible for you to let me know what the URL is that shows the Basic Auth header? I didn't think I was adding it except to appropriate GitHub, Bitbucket, etc URLs.

**Comment by afragen** [comment]
Strange as I have WP Mail SMTP installed and I can send email without a problem.

**Comment by EricBusch** [comment]
> Is it possible for you to let me know what the URL is that shows the Basic Auth header?

Yes, but I'm not sure where to find that. Can you tell me where to look?

**Comment by afragen** [comment]
I just added a filter `GitHub_updater_unset_auth_header` that the user can add the URL host to to remove Basic Auth header. Switch to the current `develop` branch and add the following code somewhere.

```php
add_filter(
	'github_updater_unset_auth_header',
	function( $hosts ) {
		return array_merge( $hosts, [ 'api.mailgun.com' ] );
	}
);
```

LMK if that works.

**Comment by afragen** [comment]
If that works. I’ll probably keep a running list and the filter.

**Comment by EricBusch** [comment]
Still no luck. I installed Version 9.3.0.1 of the updater plugin and added the above code to an active custom plugin and I'm still getting the same error message. And deactivating the updater plugin still allows email sending to work.

**Comment by afragen** [comment]
I thought, looking at Mailgun’s docs, that that snippet should work. Any way to find out the URL that is not authenticating?

**Comment by EricBusch** [comment]
This is the URL that Mailgun uses in the [cURL example](https://documentation.mailgun.com/en/latest/quickstart-sending.html#send-with-smtp-or-api):

`https://api.mailgun.net/v3/mail.MYSITE.com/messages`

I replaced `api.mailgun.com` with `api.mailgun.net` but still no luck.

**Comment by afragen** [comment]
Hmm, `api.mailgun.net` should’ve worked. 

I put the filter in the location that I use to unset the Auth header for release asset redirects.

**Comment by soderlind** [comment]
fwiw, sending via mailgun using https://nb.wordpress.org/plugins/mailgun/ works fine.

**Comment by EricBusch** [comment]
That's weird... for now I'll leave it as-is until I have more time to debug the issue. I can just leave the Github Updater plugin disabled until I push changes to my repo. Then activate the plugin, update my plugin, then deactivate.

Thanks for your help! Really appreciate it.

**Comment by soderlind** [comment]
eh .. I'm sending using the mailgun api.

**Comment by afragen** [comment]
So that plugin seems to add the Basic Auth header as I expected. My plugin hooks into `http_request_args` with a priority of 5 and removes with a priority of 15.

Leaving GHU inactive and reactivating as needed seems like a lot of work. If you can figure out the priority or when the conflict occurs, probably by a detailed look into what's hitting the filter and when it would be helpful.

**Comment by EricBusch** [comment]
I'll take a deeper look but it will have to be late next week. Thanks!

**Comment by afragen** [comment]
No problem. I hope we can find some more info. I took a quick look through WP Mail SMTP and I see it is setting a Basic Auth header for Mailgun. I just can figure out when in the cycle it fires.

**Comment by Raruto** [comment]
Hi Andy,

I can confirm that there are analogous issues with the cloudflare integration ( [Official Plugin](https://wordpress.org/plugins/cloudflare/) / [WP Fastest Cache Integration](https://www.wpfastestcache.com/tutorial/wp-fastest-cache-cloudflare/) ) In the next several days I try to look at it better, but I believe that the cause may connected to the new oauth api...

_Sorry for the intrusion._

**Comment by afragen** [comment]
@Raruto it’s not using OAuth, it’s using Basic Auth headers.

**Comment by morganhvidt** [comment]
I'm having this issue as well. I get 401 error messages in the logs when trying to send emails with the Github Updater is active.

Happens for SendGrid plugin with the SendGrid API. 
Also WP Mail SMTP with Mailgun API. 

Sorry I don't any more details, I'm away from my office.

**Comment by afragen** [comment]
I have another idea. Stay tuned for an update to the `develop` branch for testing.

**Comment by afragen** [comment]
I don't use Mailgun or any of the other services. I can't seem to create an account on Mailgun, no idea why. Could someone send me a private API key via email, andy@thefragens.com and the domain name entry. I'm testing this in a local dev environment and I'm not sure what the domain name entry will be.

**Comment by afragen** [comment]
Update to latest develop. OK, I was able to get a Mailgun account and I think this is working now. It seems to pass along the correct header and I get a success but I don't see the email. 

There might still be something broken but I can't seem to follow it. Help please?!

**Comment by afragen** [comment]
OK, I think I've gotten this fixed. Please update to v9.3.0.3, test, and let me know if it works -- PLEASE!!

**Comment by Raruto** [comment]
> @Raruto it’s not using OAuth, it’s using Basic Auth headers.

You are right.

> OK, I think I've gotten this fixed. Please update to v9.3.0.3, test, and let me know if it works...

It seems to be fine for me too 👍

**Comment by EricBusch** [comment]
@afragen Nice! It's working again even with the `github_updater_unset_auth_header` filter removed. Thanks! 

What was the issue?

**Comment by afragen** [comment]
@EricBusch the issue really was that I was inserting the header in more places than I should've. I fixed this by checking to see that the `$slug` was populated in `get_credentials()`. So far that seems to work and not break anything. At least nothing that I'm aware of yet.

Now pushed to v9.3.1
