### ISSUE TITLE
New Basic Auth method doesn't play nicely with installing new Plugins from GitHub

### ISSUE THREAD

**Issue by d4mation** [afragen/github-updater#855]
I've only tested this with a Private Repo'd Plugin on GitHub, but it may impact Themes too.

If you have a "global" Auth Token saved under GitHub Updater -> Settings -> GitHub and then go to install a Plugin from a Private Repo, it will tell you that it doesn't exist. However, if you copy/paste that same Auth Token into the installation dialog/form, it will be able to find it properly and then install it.

**Comment by afragen** [comment]
I will dig into this. Thanks for the report.

**Comment by afragen** [comment]
@d4mation I think I fixed this. Can you test the `develop` branch and confirm?

**Comment by d4mation** [comment]
Tested with `develop` and it indeed works. Thanks!
