### ISSUE TITLE
Invalid archive structure error

### ISSUE THREAD

**Issue by f8k8** [afragen/github-updater#856]
I'm trying to set up GHU on a Multisite install, but whenever I try to install a theme I get `The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Invalid archive structure`. I've tried with your http://www.github.com/afragen/test-child theme and get the same error:

```
Downloading installation package from https://api.github.com/repos/afragen/test-child/zipball/master…

Unpacking the package…

The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Invalid archive structure
```

I've installed the `github-updater-support` plugin and can see the HTTP API Call with a status of:
```
200 OK-
HTTP API Transport: fsockopen
```

**Comment by afragen** [comment]
That's usually an authentication issue. Can you remove and re-save your access token?

**Comment by f8k8** [comment]
I've just tried that and get the same error. If I change the auth token to something invalid, I get

```
Downloading installation package from https://api.github.com/repos/afragen/test-child/zipball/master…

Download failed. Unauthorized
```

So it doesn't look like an auth issue. I can download the zipball with the auth token using cURL.

**Comment by afragen** [comment]
I'll check this out.

**Comment by afragen** [comment]
I think this may be fixed in https://github.com/afragen/github-updater/commit/6bd5a83772ebaa74e5e6301ec015b8cfc58284f8

Can you test the latest `develop` branch and confirm? Thanks.

**Comment by f8k8** [comment]
It's still not working unfortunately, but I've come across something strange. I modified Wordpress so that it doesn't delete the temporary Zip file, and compared it to the same file downloaded with cURL. They're almost identical, but the one that Wordpress downloads has the chunk sizes from `Transfer-Encoding: chunked` written into it and so is corrupt:

![image](https://user-images.githubusercontent.com/1764665/74540173-389f9700-4f37-11ea-8d9a-491c4aac9c7f.png)

For some reason, when Wordpress is downloading the file, it seems to be ignoring the `Transfer-Encoding: chunked` response header and assuming the chunk sizes in the response are part of the file. This doesn't seem to happen on any other downloads (e.g. updating plugins), as that all works fine. It only seems to be happening on files that github-updater is downloading.

**Comment by afragen** [comment]
The downloading and installation of plugins is all part of WordPress core. This plugin will rename the directory correctly but otherwise it's all core.

Can you try on a fresh installation of WordPress in a local environment with only GitHub Updater active and a default theme? That way we can keep the variables to a minimum.

**Comment by afragen** [comment]
<img width="993" alt="screenshot_42" src="https://user-images.githubusercontent.com/1296790/74544515-1b99a280-4efc-11ea-8caf-90baf3d10ef0.png">

**Comment by f8k8** [comment]
I finally figured out what was causing this. Wordpress uses the Requests library for downloading files, which has an open issue (https://github.com/rmccue/Requests/issues/189) where the fsockopen implementation doesn't support chunked transfer. Installing `php-curl` on the server fixed the issue, as Wordpress now uses the cURL implementation.

Thanks for your help :)
