### ISSUE TITLE
Error message shows on front-end. Also does not remove when disabling plugin.

### ISSUE THREAD

**Issue by bahia0019** [afragen/github-updater#857]
This is actually the Debugger plugin. And possibly a Multisite situation (haven't tested on single install).
I Network Activated the Debugger to see if there was a reason a plugin wasn't updating, and got the message "The WP Debugging plugin must have a wp-config.php file that is writable by the filesystem."

I deactivated the plugin. But the error message persisted. It also shows on the admin & front-end of all subsites. It also oddly shows in one of my dashboard widgets.
Screenshots below.

<img width="1440" alt="Screen Shot 2020-02-13 at 1 03 57 PM" src="https://user-images.githubusercontent.com/1586037/74478589-8ac2b880-4e62-11ea-9f38-fc305622cf1b.png">
<img width="1064" alt="Screen Shot 2020-02-13 at 1 06 48 PM" src="https://user-images.githubusercontent.com/1586037/74478605-90b89980-4e62-11ea-83cf-deea7ab6eb78.png">

**Comment by bahia0019** [comment]
Testing on Incognito window, it doesn't show on Frontend. I think it's WP Query Monitor displaying the error for me while I'm logged in.

**Comment by afragen** [comment]
This is a notice from the [WP Debugging](https://github.com/afragen/wp-debugging) plugin.

If this is an issue let's move it over there.

Also, as the notice states, you **must** have a writable `wp-config.php` file for the plugin to function.
