### ISSUE TITLE
Can't install plugin via GitLab private repo via global token

### ISSUE THREAD

**Issue by dfragac** [afragen/github-updater#859]
Hi!

I'm trying to install several own plugins via my private GitLab repos and, since 9.3.1 it's always returnning "not found".

But, if I specify the key on the "intall plugin tab" for each plugin installation (same key as general each time), it worked fine.

¿Can you check on it?

Regards

**Comment by afragen** [comment]
Can you try using the develop branch. There are many authentication updates that are still being tested and not yet released. LMK

**Comment by dfragac** [comment]
I've tried version 9.3.1.4 just now and it works fine! :-)

If you want you can pull it to master :-P
