### ISSUE TITLE
Install plugin from "Plugins > Add new"

### ISSUE THREAD

**Issue by dfragac** [afragen/github-updater#860]
This is more like a request for a new feature of your excelent plugin.

¿Can you add the possibility to add a plugin from the "plugins > add new" page?

I'm thinking about it and it could be like a new button (there's one for "upload plugin" for uploading through zip file) with something like "from git"... when you click on it it requests a url and a button to "install". It parses the common git public repos through the url you paste (gitlab, github, bitbucket...) to install like if you did it in "GilLab Updater > Install Plugin > GitHub". If it's none of these, plugin could try it like a private repository and it checks if it's a key registered, etc...

I don't know if I'm explaining right but I hope so.

Best regards and thank you so much for your excelent contribution and plugin.

**Comment by afragen** [comment]
Have you seen the option in Install Plugin for Zipfile?

**Comment by afragen** [comment]
<img width="789" alt="screenshot_52" src="https://user-images.githubusercontent.com/1296790/74870089-fb0f8500-530d-11ea-8add-0694e097cc0d.png">

**Comment by dfragac** [comment]
Hi @afragen !

Yep! I've seen it. The thing I've suggested it's more like a "seemless" or "easy" integration on WordPress backend than a "new" functionality.

Regards!

**Comment by afragen** [comment]
I'm reasonably happy with how this currently works and I don't wish to expand it in this manner.

I'm glad you like the plugin, but I'm sorry I cannot accommodate this request.
