### ISSUE TITLE
Install most recent release asset from bitbucket

### ISSUE THREAD

**Issue by Gaffen** [afragen/github-updater#861]
Hi there,

I had encountered a similar issue to  #752; I pushed a new release to master with an updated tag, and github updater downloaded a copy of the previous release asset. I think it may have been something to do with when I pushed the tag, but am unsure.

However I had noticed that if the theme was reinstalled the issue was fixed so I gave this a try, now when I attempt to install the theme from the bitbucket repo (having deleted the theme from the server), the master repo is downloaded as a zip, rather than the most recent release asset; which contains compiled files and dependencies as the result of a pipeline build.

I'm unable to give repo access at the moment as it's a private client, but if you require more information let me know.

To reproduce, try installing a repo from bitbucket that has release assets - I believe this should recreate the issue if it's not something specific to the configuration of my specific repository.

**Comment by afragen** [comment]
A release asset is not able to be used with the install tab unless you use the URL to the release asset and the Zipfile option.
