### ISSUE TITLE
Not using GitHub but getting 401 errors

### ISSUE THREAD

**Issue by cbratschi** [afragen/github-updater#867]
I am getting this error message:

GitHub Updater Fehlercode: 401
Wahrscheinlich ist Ihr Access-Token oder Passwort fehlerhaft auf der GitHub Updater Einstellungsseite.

But all GitHub credentials are empty because we are using BitBucket.

The following call fails:

https://api.github.com/repos/afragen/github-updater/contents/github-updater.php
?ref=master

I guess this is the update check which seems to require a valid GitHub access token.

**Comment by afragen** [comment]
What version of GHU are you currently using?

**Comment by afragen** [comment]
Can you screenshot your Bitbucket tab?

**Comment by afragen** [comment]
As you're testing you should have the _Bypass WP-Cron_ checked in the Settings.

**Comment by cbratschi** [comment]
Version 9.3.1 is installed.

GitHub tab:

<img width="699" alt="Bildschirmfoto 2020-04-02 um 18 54 01" src="https://user-images.githubusercontent.com/3909121/78276554-7b332800-7513-11ea-845f-bf6c6896fbf8.png">

BitBucket works normally.

Bypass WP-Cron is activated.

Thanks,
Christoph

**Comment by afragen** [comment]
Are there any notices? Click the _Refresh Cache_.

Can you use the branch switching to re-install the `master` branch and see if the error persists?

If the error persists can you use the branch switching to switch to the `develop` branch?

Let me know.
