### ISSUE TITLE
Github-updater and Jetpack Authorisation Conflict (resolved)

### ISSUE THREAD

**Issue by allrite** [afragen/github-updater#868]
Hi,

Just wanted to let you know that we were experiencing a Jetpack authorisation issue similar to that mentioned in issue #122 , despite using the latest master release of the github-updater plugin. A reinstall of github-updater appears to have resolved the issue.

Note that it only occurred on a couple of sites with the Jetpack/github-updater combination (1 multisite, 1 standalone). Other sites with a similar configuration have had no issues.

Hopefully this will assist anyone else who encounters this problem.

**Comment by afragen** [comment]
I wish I could explain why a re-install solved the issue.

If this happens again I would greatly appreciate 
- reopen this issue
- the PHP errors
- specific versions of both Jetpack and GitHub Updater
- any specific steps to reproduce

Fortunately a lot has changed since #122 in 2014 😉
