### ISSUE TITLE
Please help me with access token settings

### ISSUE THREAD

**Issue by Hube2** [afragen/github-updater#870]
I've read all the documentation and it is as clear as mud.

Can someone tell me what the minimum scopes I need to set are to allow this plugin to install and update a plugin of theme from one of my private repos?

Please explain, I've read the documentation and it is obtuse. If you don't already understand the settings then there is no way you can get an understanding by reading it what is provided.

**Comment by afragen** [comment]
Sorry, I'll try to clear it up. For GitHub, create a personal access token that has `read` access for **repos** and **repo:packages**

**Comment by Hube2** [comment]
Thank you, I'll give those setting a go.

It wasn't necessarily this dos for this plugin, I was more referring to the doc explaining the permissions from github or what permission allowed who and I didn't want to try every possible combo to figure out the minimum permissions needed. I was getting a little frustrated with it and couldn't figure out what was making the difference between it working and not working.  I wouldn't be concerned if this was for my own site but I'm trying to set this up so that I can install private plugins to client sites and I don't want them to be able to mess with repos should they figure out how to get the token from the admin.

**Comment by afragen** [comment]
There's absolutely no need for any sort of `write` or `delete` permissions. The plugin doesn't need them and the security risk isn't worthwhile.

I added this info to the wiki too.
