### ISSUE TITLE
Hide repository tags

### ISSUE THREAD

**Issue by noesteijver** [afragen/github-updater#871]
Hello,

Is it possible to hide the repository tags from the Theme screen when selecting a branch?

What I want to achieve: only a list with actual branches to select.

Hope to hear from you!
-Kevin

**Comment by afragen** [comment]
Currently the branches are listed first and then the most recent 3 tags. Let me think about it, perhaps a filter might work here.

**Comment by afragen** [comment]
I have been refactoring parts of this in the `develop` branch and have decided to limit the rollback to only the current tag.

Removing all tags doesn't allow the user to re-install the current release and I don't think a global filter turning this off for all repositories is prudent.

I hope the pending change is satisfactory.
