### ISSUE TITLE
New releases only installing via branch switching but not as updates

### ISSUE THREAD

**Issue by Gaffen** [afragen/github-updater#873]
I am distributing a wordpress theme as a release asset, setting both the version number and the release asset name using the release tag.

Everything worked as expected at first, but now new updates never appear in the wordpress interface, and can only be installed via the branch switcher; which shows the current branch as master, the develop branch, and the most recent release number. After installation of the most recent release the branch switcher once again shows the current branch as 'master'.

I can provide read access to the repo but I will need a bitbucket username or email address to send it to.

**Comment by afragen** [comment]
My Bitbucket username is `afragen` and my email is andy@thefragens.com

**Comment by afragen** [comment]
It is the expected behavior that an installed release asset will display as `master`. 

Please switch to the `develop` branch for testing this as I have made a number of changes to how release assets are handled.

**Comment by afragen** [comment]
If you want you can test with https://bitbucket.org/afragen/test-bitbucket-ra

This is a public test plugin for release assets on Bitbucket.

**Comment by Gaffen** [comment]
I've given you read access now - I checked with the test plugin and I can confirm that it seems to be specific to my theme. I'm using the `develop` branch of github-updater now.

Yeah, I wasn't sure if the `master` this was expected functionality or not; I just wanted to give as much information as possible.

I have a suspicion that a messy merge resolution changed the branching hierachy somehow. Let me know if you need more information!

**Comment by afragen** [comment]
So here's the problem. You **must** set the current version number in you theme's style.css file on Bitbucket.org. Having it set automatically during a build is not sufficient as GitHub Updater checks this file for the current version.

You currently have it set as `CURRENT_VERSION_TAG`.

**Comment by Gaffen** [comment]
Ahhh Ok, damn I was trying to be clever.

I think it would be nice to have a way to tie releases to the codebase a bit more directly - it seems odd to have to duplicate the version number in two places. Do you think this is something that could work as a feature proposal?

In any case that seems to solve this specific problem, thanks for taking a look!

**Comment by afragen** [comment]
GitHub Updater specifically checks the main plugin/theme files for the current version of the repository. It is the only consistent location that exists.

Some build processes create the entire style.css file and I tell devs that they must keep a stub file that contains the current version header.
