### ISSUE TITLE
I can't install the theme in GitLab.

### ISSUE THREAD

**Issue by kusokamayarou** [afragen/github-updater#874]
# Install Theme

- Theme URI : https://gitlab.com/00000000
- Repository Branch : master
- Remote Repository Host : GitLab
- GitLab Access Token : ****

https://gitlab.com/api/v4/projects/%2F00000000/repository/archive.zip?sha=master

"% 2F" is added to the url.

**Comment by kusokamayarou** [comment]
The same phenomenon occurs in "Install Plugin".

**Comment by kusokamayarou** [comment]
github-updater/src/GitHub_Updater/API/GitLab_API.php

Line : 600

$id                       = rawurlencode( $install['github_updater_repo'] );
----
$id                       = $install['github_updater_repo'];

OK ???

**Comment by afragen** [comment]
Can you share the actual theme URL?

**Comment by afragen** [comment]
You can test with this repository if you want.

https://gitlab.com/afragen/test-gitlab-plugin

**Comment by kusokamayarou** [comment]
I solved.
Thanks.
