### ISSUE TITLE
Plugin being conflicted with WordPress.org

### ISSUE THREAD

**Issue by elvishp2006** [afragen/github-updater#876]
I had instaled this plugin with GitHub Updater: https://github.com/WP-API/jwt-auth but the updates are being conflicted with another plugin with the same slug at WordPress.org: https://wordpress.org/plugins/jwt-auth/

![image](https://user-images.githubusercontent.com/7463100/81121536-5876a380-8f05-11ea-9a7b-d8ebb4357d88.png)

![image](https://user-images.githubusercontent.com/7463100/81121580-6fb59100-8f05-11ea-8a7b-3418fb4d2a49.png)

When I update this plugin, It's being replaced with WordPress.org version

**Comment by afragen** [comment]
See filter `github_updater_override_dot_org`


https://github.com/afragen/github-updater/wiki/Developer-Hooks

**Comment by afragen** [comment]
Example,

```php
add_filter(
	'github_updater_override_dot_org',
	function () {
		return [
			'jwt-auth/jwt-auth.php',
		];
	}
);
```

**Comment by elvishp2006** [comment]
That's a thing that I can declare on another plugin, or it should be declared at https://github.com/WP-API/jwt-auth ?

**Comment by afragen** [comment]
You could declare it anywhere. Personally I use a site specific plugin. That way if you have more you can include them there too.

You can add it to the actual plugin if you change it a bit so it can work if the filter is called by another plugin too.

```php
add_filter(
	'github_updater_override_dot_org',
	function ( $overrides ) {
		return array_merge( $overrides, [
			'wp-simple-calendar/wp-simple-calendar.php',
		] );
	}
);
```
