### ISSUE TITLE
API Authentication through query string

### ISSUE THREAD

**Issue by pftaylor61** [afragen/github-updater#877]
At the moment, my Github-hosted plugins, which use Github Updater, are registering a warning message from Github, which is found at:

https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/

Are there any plans for Github Updater to take these changes into account? Github want the authentication moved into the header.

**Comment by afragen** [comment]
You really should update to the current release. This was fixed months ago. 🙃

https://github.com/afragen/github-updater/blob/master/CHANGES.md#930--2020-02-06

**Comment by pftaylor61** [comment]
Apologies. I had thought Github Updater updated itself. Downloading the new version now!

**Comment by pftaylor61** [comment]
Scrub that! Your plugin HAS updated itself. I just hadn't checked its README recently, so I haven't altered the code in my own plugins and themes. Sorry again... all good now!
