### ISSUE TITLE
Specify version to install by tag

### ISSUE THREAD

**Issue by binaryfire** [afragen/github-updater#878]
Hey Andy,

Awesome project! Is there a way of specifying the version to install by tag? I'd like to disable automatic updates and just use WP CLI / remote management. That way I'm in full control of when things update and most importantly, I can roll back to previous versions. Basically a scriptable alternative to composer...

Cheers

**Comment by afragen** [comment]
This is very doable. 

https://github.com/afragen/github-updater/wiki/Remote-Management---RESTful-Endpoints

Let me know if you have specific questions but there’s a REST API endpoint for this. Look at the Remote Management tab in Settings. 

You should also look at https://github.com/afragen/git-remote-updater

**Comment by binaryfire** [comment]
Nice. Must have missed that. Any chance of getting a WP CLI command for this too?

**Comment by afragen** [comment]
Refer to https://github.com/afragen/github-updater/issues/776
