### ISSUE TITLE
Github Updater Showing "No Automatic Update Available" In Wordpress Dashboard Updater

### ISSUE THREAD

**Issue by salty-walty** [afragen/github-updater#880]
I should note, this is taking place in a multisite environment, this issue hasn't come up on single-site installs (as far as I can remember). That said, on the multisite, when updates are available, I have been having to download them manually and install up uploading the update. 

Any ideas on how to fix this? Thanks!

**Comment by afragen** [comment]
I'm reasonably certain I cause this issue.

- In the Settings check the `Bypass WP-Cron background processing`
- Click _Refresh Cache_
- Clear your site object cache if present
- If there is a timeout error you might need to wait until it expires
- Set a GitHub person access token to avoid the timeout error.
- If there is still an error you may need to create a new access token with `read` for `repos` and `read:packages`

This should not occur in v9.5.2

**Comment by salty-walty** [comment]
Nice! Thanks for the help. It would seem that 9.5.2 resolved the issue as the latest update went off without a hitch. Much appreciated!
