### ISSUE TITLE
When installing 9.5.2 the GitHub Tab is missing

### ISSUE THREAD

**Issue by lisandi** [afragen/github-updater#882]
When installing 9.5.2 the GitHub Tab is missing.
We can only see it if we check the box at 
Settings-GitHub Updater - Bypass WP-Cron Background Processing for Debugging
Then enter the Access Token and refresh the cache in that order

Refreshing cache before won't bring that missing Tab.

The Tab stays visible after the Access token had been entered and the check in the Box for bypassing is gone too.

I woudl suggest to add a short note on the GitHub Updater Tab so people check that "Bypass" checkbox when accessing the first time - otherwise they can't enter the access token.

And all FILE permissions seem to be 0754 instead of 0644

**Comment by afragen** [comment]
Is this on a fresh installation or on an update? If on an update, what was the previous version?

**Comment by lisandi** [comment]
It was on a fresh install of the plugin - first install!

With kind regards,
Mit freundlichen Grüßen,
Con un cordial saludo,
Cordialement,
с сердечным приветом,
เรื่องที่เกี่ยวกับชนิด,
與親切的問候,
*
<https://about.me/andibecker?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=edit_panel&utm_content=thumb>
Andreas Becker about.me/andibecker
<https://about.me/andibecker?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=edit_panel&utm_content=thumb>
**LisAndi Co. Ltd.*, Phuket, Thailand (lisandi.com)
15/21 M.2 Viset Road, Rawai, Muang, Phuket, Thailand 83130

Phone: +66 (0)76 530 595
VoIP: +49 (0)711 50 88788 50
Fax:   +49 (0)711 50 88788 50
GTalk/Facetime/eMail:  andi@lisandi.com
Mobile/WhatsApp: +66 (0)81 606 3378
Facebook/Line/Messenger: andibecker
Appear.In/Skype: lisandi
--------------------------------------------------

**Comment by afragen** [comment]
Thanks. I’ll see if I can replicate locally.

**Comment by lisandi** [comment]
[https://www.dropbox.com/s/purz6fowofmiro3/Screenshot%202020-05-20%2017.48.28.png?dl=0](Dropbox)

That just happened after I installed the github plugin fresh as we have 9 plugins which should get updated via github. At the beginning all went good an I was able to enter the api key data but then I saved it and the TAB was gone like you see in the screenshot.

When I set then the hook in Bypass wpCron and click on save the Tab reappears. and you can open the Tab again and do settings there. 

one of the plugins which should get updated had one letter too much in its file ending myplugin/myplugin1.php while myplugin.php was correct. I deleted the 1 in the filename and all went good after refreshing the cache.

I tried to replroduce the procedure but could not reproduce it in the same site - only in a site where the plugin has not been installed before. It looks like the TAB is disappearing after pressing refresh when the tab is open and one of the plugins is faulty in its filename. If it is the first time you do the refresh the Tab disappears and you can only make it visible again by setting the byPass hook. It is not reproducable in the same site again when you i.e. change the filename back and go again to the Tab and press refresh from there.

**Comment by afragen** [comment]
I’ve seen something similar happen when the access token was entered incorrectly.

**Comment by afragen** [comment]
I cannot replicate locally unless the saved access token is incorrect.
