### ISSUE TITLE
Lots of PHP notices

### ISSUE THREAD

**Issue by Ryvix** [afragen/github-updater#883]
Hello,

I was debugging and noticed tons of PHP notices. Sure I could disable notices but sometimes they are important to see when things don't work right. So I just thought I'd report it here for you.

`PHP Notice:  Undefined index: github_access_token in /home/USER/public_html/wp-content/plugins/github-updater/src/GitHub_Updater/Traits/Basic_Auth_Loader.php on line 141
`

Thanks!

**Comment by afragen** [comment]
Just save the settings at least once and it should go away.

**Comment by Ryvix** [comment]
Oh awesome, thanks! Easier than I thought I guess.

**Comment by nicomollet** [comment]
@afragen For people that do not go the settings (and won't aknowledge this issue), I think this should be fixed.

**Comment by afragen** [comment]
@nicomollet are you experiencing this issue? If you are could you let me know which version you are using?

**Comment by nicomollet** [comment]
I am sorry @afragen I double checked and this one site is using v9.3.1.
Gonna update manually since auto update is not triggering.
Thank you
