### ISSUE TITLE
Integrate more seamlessly with core plugin and theme installation

### ISSUE THREAD

**Issue by westonruter** [afragen/github-updater#884]
When the GitHub Update plugin is installed, it adds its UI under the Settings menu. This was 
unexpected for me. I was expecting there to be a way to install a plugin from the plugins screen when clicking the Upload Plugin button:

![image](https://user-images.githubusercontent.com/134745/82761251-3490da00-9dae-11ea-9a67-0ae51a9cbe46.png)

It would be great if the GitHub Updater plugin installation form were included here somehow:

![image](https://user-images.githubusercontent.com/134745/82761298-876a9180-9dae-11ea-93fa-d22d6a759b18.png)

This would make it much more discoverable for how to install plugins from GitHub, as right now I feel the GitHub Updater UI is somewhat buried.

The same applies to the theme installation flow.

**Comment by afragen** [comment]
Everything in GHU is quite modularity designed. All the tabs and sub tabs of the Settings can be installed relatively independently of all the others. This is one of the reasons that adding Gist support was relatively easy. 

I’m not a big fan of inserting my plugin behaviors directly into core locations and I imagine it would take more effort and add to the complexity. It makes support simpler as in only need to point to one location. 

I haven’t yet added WP-CLI support for Gist installations but you can certainly use it for everything else.

**Comment by afragen** [comment]
Also, the core upload plugin/theme is fundamentally different that installing form a remote location.
