### ISSUE TITLE
Feature request: Incorporate rollback functionality from WP Rollback

### ISSUE THREAD

**Issue by binaryfire** [afragen/github-updater#885]
I'd love to see the ability to roll back to previous versions of plugins and themes. I think the code from https://wordpress.org/plugins/wp-rollback/ could more or less be dropped straight in to add this functionality?

**Comment by afragen** [comment]
I have recently removed or at least limited this functionality to reinstalling the most current tagged release. This was for a new release asset functionality.

Why would you want to easily install an outdated release? The goal is to stay updated.

**Comment by afragen** [comment]
Use the new `GitHub_updater_number_rollbacks` filter to return an integer for the number of rollback tags to include.

```
add_filter( `github_updater_number_rollbacks`, function() {
    return 3;
});
```

Also documented in https://github.com/afragen/github-updater/wiki/Developer-Hooks

**Comment by binaryfire** [comment]
@afragen Perfect, thank mate

If a plugin conflict comes up, I can roll that client's site back to a previous version until I can push out a fix. And being able to quickly switch between versions on my dev server without the terminal will be handy too.
