### ISSUE TITLE
Support for principal branch other than 'master'

### ISSUE THREAD

**Issue by afragen** [afragen/github-updater#889]
There has been lots of  discussion on the web about changing the principal branch name from `master` to something different.

It appears that GitHub is planning on a change where a newly created repository will initialize with a branch named `main` instead of `master`.

WordPress seems to have opted to switching all their primary branches from `master` to `trunk`. https://make.wordpress.org/core/2020/06/18/proposal-update-all-git-repositories-to-use-main-instead-of-master/

It is my intention to support whatever naming scheme the developer/user of this plugin desires to use. I am currently testing a branch locally to allow for a `Release Branch` header to accomplish this. This would require a header in your repository with `Release Branch: trunk` or `Release Branch: main` if your move from the previous default of `master`.

At present I'm using the term `Release Branch` as this is how git flow interprets the `master` branch as _production-ready_.

Unfortunately there are parts of the code that still require a default branch of `master`. This is when I am unable to read in a repository preference, such as installing a repository and when using WP-CLI.

Comments welcome.

**Comment by afragen** [comment]
Should I name the header `Production Branch` as `master` implied a _production-ready_ branch?

**Comment by bueltge** [comment]
It would be fine that the updater supporting all names for the branch. We discussed the topic also and we would wait for GitHub and his final name for the branch. Background is that we would have the default name after creation of a repository as principal branch.

**Comment by afragen** [comment]
@bueltge the default branch isn't necessarily the same as the principal/production branch. Personally, many of my repositories have `develop` as the default branch and `master` as the production-ready branch.

Currently GHU supports updates from any branch, but this is specifically aimed at devs who wish to switch from `master` to something else. There never has been a way to tell what a dev was using as the principal branch all other branches were branched off. This has been `master` but seems like GitHub plans a change to `main`. 

In order not to break the current function we/I need to have a method of identifying the new principal branch. Currently I'm leaning towards using a header, `Production Branch`. I don't know if `Principal Branch` is better or not.

**Comment by afragen** [comment]
Naming things is hard

**Comment by afragen** [comment]
I had an informal discussion/poll on Post Status and the highest vote getter was `Primary Branch`.

**Comment by afragen** [comment]
https://github.com/afragen/github-updater/wiki/Settings#primary-branch
