### ISSUE TITLE
Deleted theme still shows up as needing an update

### ISSUE THREAD

**Issue by swinggraphics** [afragen/github-updater#891]
A theme I deleted still shows up as needing an update. I even tried deleting the GU plugin and manually deleting the "gu-" rows from the options table.

**Comment by afragen** [comment]
I would need to see the Settings page to show the theme present in the subtab and a listing of the themes directory.

If the theme is gone it shouldn't show an update.

**Comment by swinggraphics** [comment]
It cleared up on its own after about 30 minutes, fortunately. :)
