### ISSUE TITLE
Updater does not work if theme with same name already exists in wordpress.org theme repository

### ISSUE THREAD

**Issue by wolffe** [afragen/github-updater#893]
Updater does not work if theme with same name already exists in wordpress.org theme repository.

I have it setup correcty, I already have 2 plugins being correctly updated from private GitHub repositories, but not the theme.

There is a very old theme in the wordpress.org theme repository with the same name/slug.

Any workarounds aside from renaming my theme?

**Comment by chesio** [comment]
Have you seen https://github.com/afragen/github-updater/wiki/WordPress.org-Directory#overriding-wporg-directory-updates ?

**Comment by wolffe** [comment]
Nope, I haven't seen it.

I added the code to my theme and it's working perfectly. Thanks!

**Comment by jessuppi** [comment]
Related:

https://github.com/afragen/git-updater/issues/581
https://github.com/afragen/git-updater/issues/876

Also see my StackOverflow thread:

https://stackoverflow.com/questions/74822705/prevent-wordpress-org-from-overriding-git-updater-for-new-versions

And here is the new link to relevant documentation:

https://git-updater.com/knowledge-base/wordpress-org-directory/
