### ISSUE TITLE
Plugin can't copy for sites having FS_METHOD != direct

### ISSUE THREAD

**Issue by ploplu** [afragen/github-updater#894]
Hi, as you were replacing the $wp_filesystem->move() by your own function a new problem appeared. For those who are using FS_METHOD with "direct", it is working like a charm. But for all the others (FS_METHOD=ftpext,...) the function is running endles until the server dies because you are copying as long as there are files left. My debug.log grows every time over 1GB ;)
![bug](https://user-images.githubusercontent.com/47015058/88457799-b625e680-ce89-11ea-92b5-a7145356a152.png)

**Comment by afragen** [comment]
Thank you. I think I see a solution. I'll try to get a fix in the `develop` branch soon. I'll ping this thread so you can test.

Should I assume that that updates happen correctly, just that the debug.log fills with these messages?

**Comment by ploplu** [comment]
No updates can't be installed because there files can't be copied.
Debug.log is my own choice, I needed to see why everything crashes ;)

**Comment by afragen** [comment]
If you use FS_METHOD = direct, what happens?

**Comment by afragen** [comment]
Your error seems to show that no files are in the download directory or rather that the download directory doesn't exist.

**Comment by ploplu** [comment]
It works without any problem. If FS_METHOD is f.ex. ftpext, it turns infinite because you are using unlink,etc instead of the Wordpress filesystem.
Sure there are files ... ;)

**Comment by afragen** [comment]
The initial error seems to be the `opendir()` fails and this returns a boolean (false). LMK if the change still updates the plugin and doesn't litter your logs.

**Comment by ploplu** [comment]
The logs are not the problem, I will disable them as soon as the site will work in production. If there is no problem, the logs won't be flooded ;)

**Comment by afragen** [comment]
Can I ask why not use the direct method? Does it not work for you?

**Comment by afragen** [comment]
I have another thought on fixing for ftpext and others but I won't be able to patch until later.

**Comment by afragen** [comment]
LMK how v9.7.1.3 of the `develop` branch works for you.

**Comment by ploplu** [comment]
Works like a charm !! 👍 
You are doing a great job !
