### ISSUE TITLE
Performance Impact

### ISSUE THREAD

**Issue by AMCodeHub** [afragen/github-updater#895]
First, amazing work! Amazing! 

However, I do have an an issue I was hoping you might be able to help with. I have 10 plugins that are held in private gitlab repos. When logged in as an admin, I can see the API calls being made on every page load, front-end and wp admin back-end. Because of the number of http requests, it can hang a page load 10-15 seconds. Any suggestions on how to minimize that impact? Maybe limiting the frequency of calls by limiting to the plugins admin page only? Maybe using wp-cron to only check hourly... or daily? I know the issue is a little unique because of the volume of plugins, but the frequency of calls and the wait time for responses is a hurdle I would love your help with. Thanks!

**Comment by afragen** [comment]
The API calls are cached for 12 hours and the default method of making the calls is via WP-Cron.

Can you screenshot your Settings tab and ensure you're using the latest releases?

**Comment by AMCodeHub** [comment]
Thanks @afragen !

I spun up a sandbox to dig a little deeper and can see that the http requests are 404ing... see attached screenshot. 
![GitHub_Updater_Settings_‹_My_New_Website_—_WordPress](https://user-images.githubusercontent.com/19928918/89832058-1ff5ef80-db1c-11ea-94fd-8a81f6abc6d4.jpg)

What's strange is that there are still updates recognized... so it looks like it is working correctly. If I click update, they are indeed updating correctly.

**Comment by afragen** [comment]
That 500 error is from your gitlab.advicemedia.com

**Comment by AMCodeHub** [comment]
yep, sorry for the false alarm... but thank you for letting me bounce it off you until I figured it out. Thanks!

**Comment by AMCodeHub** [comment]
@afragen I am trying to dig into this a little further... looking into gitlab API documentation, project calls are formed this way:
/projects/:id/share/:group_id
calls formed that way are returning correct results, but using the slug in place of the ID is returning a 500. The gitlab documentation doesn't have requests formed that way either... If that API call is working for you, do you know why?

**Comment by afragen** [comment]
> So... digging even further, I can get an API response from gitlab when using the repo ID, but not the repo name.

You can use the URL encoded `user/repo` as the project id.

https://gitlab.com/gitlab-org/gitlab-foss/-/issues/28342#note_23852124
