### ISSUE TITLE
Access Token Error on Multisite with Bitbucket Repo

### ISSUE THREAD

**Issue by salty-walty** [afragen/github-updater#896]
Hello! I thought I would open an issue as I am getting the following error on a WordPress multisite install receiving updates from a Bitbucket repo via version 9.8.1 of this plugin:

GitHub Updater Error Code: 401
There is probably an access token or password error on the GitHub Updater Settings page. 

The access token and passwords are both correct, so I'm wondering if you might have any other insights. Wondering if it may have to do with the fact that it is on a multisite, or perhaps that it is connected with Bitbucket rather than Github. 

Anyhow, I'll be curious to hear your thoughts, and I appreciate your attentiveness to issues!

**Comment by afragen** [comment]
That error is very specific to an issue with your pseudo-token.

Please try to re-enter and re-save it. Pay attention to the format. Make sure your Bitbucket application password has correct permissions to use with the API. https://support.atlassian.com/bitbucket-cloud/docs/app-passwords/

**Comment by salty-walty** [comment]
Looks like re-entering the Bitbucket user/pass did the trick! Thanks for the help!
