### ISSUE TITLE
Notice: Undefined property: stdClass::$primary_branch

### ISSUE THREAD

**Issue by naokipeter** [afragen/github-updater#897]
After upgrading to PHP 7.4.X Cron keeps running into this problem:

ErrorException /wp-content/plugins/github-updater/src/GitHub_Updater/API.php in Fragen\GitHub_Updater\API::set_file_info
Notice: Undefined property: stdClass::$primary_branch
<img width="813" alt="Bildschirmfoto 2020-09-01 um 08 57 50" src="https://user-images.githubusercontent.com/3439906/91812442-6927f380-ec31-11ea-84e4-a9247449dca9.png">

What could be the issue?

**Comment by afragen** [comment]
I have stepped through this in PHP 7.4.x and I can't reproduce this.

The errror refers to `$this->type->primary_branch` not being set, however, this is set in https://github.com/afragen/github-updater/blob/a194662de51a593d44a4442877df89ad3a040e23/src/GitHub_Updater/Traits/GHU_Trait.php#L602

I tested this on a new installation with only GitHub Updater present and active.

**Comment by afragen** [comment]
Please reopen if this is still an issue.
