### ISSUE TITLE
GET requests for bitbucket.org

### ISSUE THREAD

**Issue by seojacky** [afragen/github-updater#899]
Hi! Why the plugin constantly makes GET requests https://api.bitbucket.org/2.0/repositories/meowapps/meow-lightbox/src/master/meow-lightbox.php?
I see this error in the admin panel.
<img src="https://i.imgur.com/iIT7HUD.jpg">

**Comment by afragen** [comment]
It would appear the meow-lightbox plugin might have an error in the Bitbucket Plugin URI.

**Comment by afragen** [comment]
You seem to have a discrepancy in the upstream version where the main plugin file is `meow-lightbox-pro.php` and the 3.0.0 update file is `meow-lightbox.php`

**Comment by seojacky** [comment]
Thanks for the answer. I removed the plugin Meow. It's okay now.
