### ISSUE TITLE
Error when running in PHP 7 because of ionCube Encoder

### ISSUE THREAD

**Issue by leandrogbreve** [afragen/github-updater#900]
Hello, 

My website uses ThemeChilly and from what I've noticed, it uses the 'github-updater'. 

When using PHP 7, my website gives error 500, and logs below error in 'error_log':

```
[14-Sep-2020 14:20:06 UTC] PHP Fatal error:  The file /home/neopro/public_html/wp-content/plugins/github-updater/vendor/wp-update-php/src/WPUpdatePhp.php was encoded by the ionCube Encoder for PHP 5.3 and cannot run under PHP 7.1 or later.
 Please ask the provider of the script to provide a version encoded with the ionCube Encoder for PHP 7.1. in Unknown on line 0
```
I was able to put the website online when renaming the 'github-updater' folder through cPanel, however, the folder keeps being re-created over and over again.

Would it be possible to publish a version of it encoded in a ionCube Encoder for PHP 7? Or is there a workaround for that?

Thank you in advance. I look forward for hearing from you.

**Comment by afragen** [comment]
That file is not contained in my plugin. Whoever installed it used a modified version of GitHub Updater. 

My recommendation is to delete that version and install it from GitHub.
