### ISSUE TITLE
Branch switching issue

### ISSUE THREAD

**Issue by NoWorries** [afragen/github-updater#901]
I switched to a branch, but can't switch back to `master`? I cleared the cache but it doesn't show any other branches?

![image](https://user-images.githubusercontent.com/803064/93537203-078cb680-f99f-11ea-9258-56c4e445fea5.png)

**Comment by NoWorries** [comment]
I realised, i had just deleted the branch the site was using (jharwood/approachReview). When i restored the branch i was able to see all the other branches including `master`.

![image](https://user-images.githubusercontent.com/803064/93538023-3310a080-f9a1-11ea-9e13-b02970b26c8c.png)

**Comment by pdobrescu** [comment]
I bumped into exactly the same issue. Would it make sense to have some option to default to the main/master branch of the repo? It looks like there's no other alternative but to restore the branch, switch the plugin to another branch and then remove it again. Branch removal is quite a common practice, therefore I'd love to have something like this (or any other solution). Thanks!

**Comment by afragen** [comment]
You can use WP-CLI to change the branch setting of the particular repo in the `github_updater` option. 

The actual solution is to switch back to the default branch prior to deleting the branch you are on.

**Comment by afragen** [comment]
The problem with setting a default is getting a 404 response could simply be an authentication issue.

**Comment by pdobrescu** [comment]
Ok, understood, the WP-CLI solution is good, so thank you!
