### ISSUE TITLE
Use release asset version?

### ISSUE THREAD

**Issue by thefrosty** [afragen/github-updater#902]
Was testing this out for a new plugin [thefrosty/wp-login-locker](https://github.com/thefrosty/wp-login-locker). I'm using composer to manage my dependencies, and a GitHub action to create the zip without the files and directories for development and the autoload + vendor built into the bundle then attaches to the tagged "release", see the most recent [releases/tag/v2.1.1](https://github.com/thefrosty/wp-login-locker/releases/tag/v2.1.1) where it has an asset `wp-login-locker.zip`. 

Is there a way to use the release asset over the branch zipball?

**Comment by afragen** [comment]
Add the `Release Asset: true` header. 

https://github.com/afragen/github-updater/wiki/Settings#release-assets

**Comment by thefrosty** [comment]
Ahh shoot, sorry I missed that.
