### ISSUE TITLE
more of a question -- enabling branch switching on install via wp cli? 

### ISSUE THREAD

**Issue by eriksays** [afragen/github-updater#904]
is it possible to enable branch switching via wp cli? I'd like to install the plugin via wp cli and enable branch switching automatically.

**Comment by afragen** [comment]
In as much as you can add `'branch_switch = '1'` to the `github_updater` settings array option in the database, the answer is yes.

**Comment by afragen** [comment]
FYI you can switch branches using WP-CLI too.

`wp plugin branch-switch <repo> <branch>` or `wp theme branch-switch <repo> <branch>`

**Comment by eriksays** [comment]
thanks for the response! love this plugin
