### ISSUE TITLE
Question: would downgrading (based on releases) be possible ?

### ISSUE THREAD

**Issue by pdobrescu** [afragen/github-updater#905]
First of all thank you for a great plugin! It works super great and solves many development struggles :-) 

During the development however, there are cases when you need to test how a feature worked on a previous version of a plugin or to test that you can reproduce a bug on a previous version. In this case, would it be possible to add an option in the plugin to switch the versions based on the releases (which usually have git tags behind)?

**Comment by afragen** [comment]
You can use the branch switching option and the filter `github_updater_number_rollbacks`. 

It's documented in https://github.com/afragen/github-updater/wiki/Developer-Hooks

**Comment by pdobrescu** [comment]
@afragen thanks a lot for this, it works like a charm ;-) It might be worth adding it to the plugin settings sometimes ;-)
