### ISSUE TITLE
This repository has not connected to the API or was unable to connect...

### ISSUE THREAD

**Issue by zebrastribe** [afragen/github-updater#907]
I am unable to connect to the github API.
I have entered the token from github and the header information the style.css

![Skærmbillede 2020-10-26 kl  16 21 03](https://user-images.githubusercontent.com/6557899/97191512-40425b80-17a7-11eb-99ef-8cfdd03b8fe8.png)

**Comment by afragen** [comment]
From the GitHub Updater tab check the bpbox to bypass WP-Cron and save. Install Query Monitor and let me know what the HTTP error shows.

It is likely an access token issue and you might need to re-enter and save.

**Comment by zebrastribe** [comment]
Thank you so much for your answer :-)
The repo is set to private.
 
![Skærmbillede 2020-10-27 kl  08 54 42](https://user-images.githubusercontent.com/6557899/97272355-108c6580-1832-11eb-8e0a-47a11a3f61d9.png)

**Comment by afragen** [comment]
The 404 error is GitHub's way of saying you have an authentication error. You will need to re-enter and save your access token. 

Make sure your access token has all the proper privileges. 

https://github.com/afragen/github-updater/wiki/Settings#github-private-repositories

**Comment by zebrastribe** [comment]
Great. But I feel like I have done the right things to set it up:

1. Set the personal token at github with the correct permissions:
![Skærmbillede 2020-10-27 kl  12 16 42](https://user-images.githubusercontent.com/6557899/97294433-48090b00-184e-11eb-8853-96a53e7a2dc6.png)
2. Enter the token to wordpress the all the fields
3. Click save

Have I missed something?

**Comment by afragen** [comment]
That all looks correct. I can check more if you give me `read` privileges for one of the repos.

**Comment by afragen** [comment]
I think I see the issue. You have `main` as your primary branch. You must add the following header. 

`Primary Branch: main` to your plugin headers. 

https://github.com/afragen/github-updater/wiki/Versions-and-Branches#versions

**Comment by zebrastribe** [comment]
Cool. That solved you problem.

:-)
