### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by eriksays** [afragen/github-updater#908]
when running wp cli commands, I'm getting the following

PHP Warning:  Declaration of Fragen\GitHub_Updater\CLI_Plugin_Installer_Skin::feedback($string) should be compatible with WP_Upgrader_Skin::feedback($string, ...$args) in /sites/[site]/wp-content/plugins/github-updater/src/GitHub_Updater/CLI_Integration.php on line 225

it appears my plugin is running the latest version:
github-updater                   | active   | none      | 6.3.3

**Comment by afragen** [comment]
You really should update to the latest version of GitHub Updater. Latest version is 9.9.0
