### ISSUE TITLE
Frequent/Constant 401 despite access token, nothing in log

### ISSUE THREAD

**Issue by fwolfst** [afragen/github-updater#911]
Using v9.9.3 on a shared hosting I cannot update a custom child theme from github anymore. Cache refresh does not work either/results in the error message regarding access token. The token was granted all the `repo` and the `read:packages` permissions.

As a feature request, I'd like to see more (debugging) info if wordpress is configured to use its debug.log .

**Comment by afragen** [comment]
A 401 error is an authentication issue. Do you have other repos using GHU successfully or is it just a single repo?

Can you please share the repo URL?

I'll see what I can do about adding HTTP errors to the the debug log.

**Comment by fwolfst** [comment]
Thanks @afragen.



> Do you have other repos using GHU successfully or is it just a single repo?

I have other repos, but there I did not do any new releases. The theme in question is: https://github.com/ecovillage/hueman-7l-child .

**Comment by afragen** [comment]
I was able to download, install, switch to older version, and update the child theme. You do have a problem though in that 1.0.11 is installed as it is the latest tag. You need to tag a version for 1.0.12

**Comment by fwolfst** [comment]
A crap. I did not push the tag, only had it locally. And then, I overlooked that the error box in the backend regarding 404 has to be clicked away. But with the logging-patch this will not happen again.
@afragen Thanks a ton for that support.
