### ISSUE TITLE
on-update hook

### ISSUE THREAD

**Issue by tobyink** [afragen/github-updater#912]
Suggestion: after updating a theme or plugin, github-updater should check to see if the repository contains a file called:

    ./.github-updater/on-update.php

And if that file exists, should run it.

People could use the file to perform tasks like rebuilding SASS files, creating minified versions of Javascript files, updating dependencies, etc — basically setting stuff up that you might not want to keep in your repository.

**Comment by afragen** [comment]
GitHub Updater uses WP core update methods. It doesn't have it's own. You would need  to do something on your end.

GitHub Updater does allow for updating to release assets and you could build the repository and add the build zip to your release. https://github.com/afragen/github-updater/wiki/Settings#release-assets

**Comment by tobyink** [comment]
So will `upgrader_process_complete` hooks run? Even if I push a change to GitHub which doesn't alter the plugin version number?

**Comment by afragen** [comment]
Any hooks would need to be in the currently installed plugin to run, but they should. You could use the branch switching to re-install.

**Comment by afragen** [comment]
It really would be simpler to create a release asset and just let GitHub Updater use that. You cannot guarantee that a user will have all the installed applications for your build process.

**Comment by tobyink** [comment]
Well, if I'm the user, I can guarantee it.
