### ISSUE TITLE
Initialization Time

### ISSUE THREAD

**Issue by cbratschi** [afragen/github-updater#913]
We had some performance issues on a WordPress site and profiled the page loading performance with Laps. Here we found that about 170 ms are spent in the init hook by GitHub Updater. With GitHub Updater disabled it took less than 40 ms to process all other plugins. This delay happens on all pages.

In Query Monitor I could not find anything suspicious.

Any idea what is causing this and how to reduce the load time?

**Comment by cbratschi** [comment]
Sometimes it takes even more than 400 ms. In the 170 ms case I don't see any outgoing HTTP calls.

**Comment by cbratschi** [comment]
All WordPress requests are slowed down, including REST API calls.

**Comment by afragen** [comment]
If you find out specifically what might be an issue I'll be happy to look at it. Performance often ends up being very specific to many variables.

**Comment by cbratschi** [comment]
This is a site which uses a lot of third-party plugins. I am seeing that the Plugin class uses get_plugins() which does a full plugin scan during every WordPress load. This is the reason why our site is getting permanently slower.

We only need GitHub Updater in certain conditions:

- REST API to updates themes remotely
- manually update themes on the themes screen

The full code should only be loaded in these cases and not during every WordPress load.

**Comment by cbratschi** [comment]
Getting the themes slows down the site by 15 ms (50% more time spent in the init action). The main bottleneck is the get_plugins() call.

As a temporary workaround we return no plugins in get_plugin_meta().

**Comment by afragen** [comment]
And how long does the core function `get_plugins()` take?

I'm not really into trying to improve the performance of this core function. Sorry.

**Comment by afragen** [comment]
Interestingly the `get_plugins()` call is cached by core. https://core.trac.wordpress.org/browser/tags/5.6/src/wp-admin/includes/plugin.php#L280

**Comment by cbratschi** [comment]
We are using LiteSpeed Cache and the memcached cache is active. However, LiteSpeed excludes those values by default:

- comment
- counts
- plugins

https://blog.litespeedtech.com/2018/02/07/object-cache-support-in-lscache/

**Comment by cbratschi** [comment]
Below are some more details. Still looking for a solution for our environment.

I could not get it to work with LiteSpeed Cache. The following code always returns false:

```
error_log(json_encode(wp_cache_get('plugins', 'plugins')));
```

We also measured the time it takes:

get_plugins() time: 0.11537504196167 s
GHU plugin init time: 0.035265207290649 s

The get_plugins() call is not cached and takes about 110 ms. GitHub Updater processes the plugins afterwards in the same method and takes another 35 ms.

**Comment by afragen** [comment]
It seems to be an issue with you caching setup. When I step through the code, the vast majority of the time I step into `get_plugins()` the cache is returned and it's timed for me at 0 ms.

**Comment by cbratschi** [comment]
Feedback from LiteSpeed support:

"Actually I tested LiteSpeed Cache and at least 2 other object-cache plugin , none of them works with plugins group."

Which cache plugin are you using?

**Comment by afragen** [comment]
That test was done without a cache. But my site is running on a Digital Ocean droplet using SpinupWP. I believe there's a Redis cache somewhere. Site loads in under 1 sec which is fine for me.

**Comment by cbratschi** [comment]
The site above is using Memcached and there we don't see any improvements.

Today we took over a project from another agency. This site uses no caching solution at all and so far delivers the homepage in about 280 ms. Once GitHub Updater was installed rendering the homepage took about 570 ms for not logged in users. Here we use a BitBucket based theme and plugin with GHU. This is way too slow and we have no workaround yet other than to enable/disable GitHub Updater all the time.

In general we operate quite different WordPress installations with different cache and hosting solutions. Other GHU users will operate similar instances and having a fallback would be a good solution. For instance the list of installed plugins could be written to transients which fall back to the database if no in-memory cache is active. The list of installed themes and plugins does not change that often. On top of that the plugin should only be active in case of admin users and REST API calls. The latter would already considerably improve the current situation.

**Comment by cbratschi** [comment]
I benchmarked the new staging environment from above again and 70 ms are due to GHU. The remaining time is spent by the latest versions of WordPress and the Yoast SEO plugin.
