### ISSUE TITLE
[Feature request] Rollback...

### ISSUE THREAD

**Issue by zebrastribe** [afragen/github-updater#919]
Hi 
Thanks for a very useful plugin. It simplifies my work a great deal.
I have a feature request or idea. It could be nice with a rollback funktion. 
Like the "WP rollback" have for the wordpress repos.

Keep up the good work,
Be safe
Jesper

**Comment by afragen** [comment]
It can already do this with branch switching. There is a filter to set the number to tags visible. Documented in the wiki.
