### ISSUE TITLE
Option to remove the icon shown next to "View details"

### ISSUE THREAD

**Issue by EusebiuOprinoiu** [afragen/github-updater#920]
Hello, Andy!

Would you, please, consider adding a checkbox under the plugin settings (or at least a filter) to disable the icon shown next to the "View details" link?

I like having my Dashboard as clean as possible and I go to great lengths to clean it of non-essential elements. In most cases, this means dashboard widgets, upsell pages in free plugins, etc.

While the icon is not intrusive, I don't feel it provides any real benefits. If I really want to see which plugins rely on Github Updater for updates, I can always check the settings page.

![icon](https://i.imgur.com/NAC2EIS.png)

**Comment by afragen** [comment]
I think we'll have to agree to disagree. I believe that the small icon provides data and is as unobtrusive as possible. I will not be creating another preference to remove this. 

I have no upsells or advertising. In fact, at present, I don't sell anything. I don't think the comparisons apply.

**Comment by EusebiuOprinoiu** [comment]
Hello, Andy!

This wasn't meant to be a comparison to upsells or advertising. I was only trying to say that I like to clean and customize my admin dashboard to satisfy my OCD. Perhaps my example wasn't the best one to get my point across.
And as I mentioned above, I don't think the icon is intrusive in any way. I'm sure many people find it useful. But since I don't, I would really like to have a way of hiding it.

If a checkbox on the settings page is out of the question, please, consider adding a filter, like the many you already provide.
It's a simple way of doing it with no changes to the UI.

Also, if you mistook my request as criticism, I apologize. It wasn't meant to be perceived that way.
I appreciate the work you do, and I admire your commitment to maintaining open-source software. I know it involves a lot of work with little to no monetary compensation. The WordPress ecosystem wouldn't be what it is today without the involvement of developers like you.

If you don't like the idea of a filter either, I will respect your decision and won't bother you again with mentions of this request.

**Comment by afragen** [comment]
I took no offense to anything you you wrote.  No need to worry. But as I said we'll have to agree to disagree on removing the icon. 

I'm sorry you don't like it but perhaps it will grow on you. I think it's value is self evident and I have no plans to remove it. 

I hope you can get used to its subtle presence to the information it provides.

**Comment by EusebiuOprinoiu** [comment]
Hello, Andy!

I managed to remove it by using the `plugin_row_meta` filter.
I searched for common image file extensions (including SVGs) in the plugin meta and removed from it the keys that contain one.
No need for a filter anymore. Thank you for taking the time to reply...
