### ISSUE TITLE
Stuck on non-existing 'master' branch

### ISSUE THREAD

**Issue by therealgilles** [afragen/github-updater#921]
I was trying to update the pods-framework plugin, which does not have a 'master' branch.
It was on the 'main' branch and things seemed to work. It chose a different tag '2.7.24' and somehow that switched the version to 'master'. Now I cannot change the version anymore. It says 'No previous tags to rollback to.'.

This seems like a bug (or two) in the updater:
1) It switched to a non-existent 'master' branch even though I chose a specific version tag.
2) I cannot switch it to a different version anymore.

**Comment by therealgilles** [comment]
I was able to get back to the 'main' branch by doing an 'Install Plugin' through GitHub Updater. Even though the installation failed because it said 'Destination folder already exists', it still switched the branch back to 'main'.

**Comment by afragen** [comment]
Strange. I installed Pods at the `main` branch and was able to install the 2.7.24 tag and even update again. It's all still on the main branch.

I can't seem to replicate based on your description. Is there more?

**Comment by therealgilles** [comment]
I just tried again by selecting the 2.7.25 tag and again it switched to the non-existent 'master' branch.

**Comment by afragen** [comment]
I did the same thing and found the branch also shows `master`. I then refreshed the cache and it was back to `main`.

I'll have to look closer as to why.

**Comment by afragen** [comment]
I think I fixed it. Stay tuned.

**Comment by afragen** [comment]
Switch to `develop` branch to test.

**Comment by therealgilles** [comment]
Did a quick test and it seems to be working for me. Thank you!
