### ISSUE TITLE
Passing a large readme to file_exists() throws errors whenever cron runs

### ISSUE THREAD

**Issue by trevorawest** [afragen/github-updater#922]
The condition needs some sort of length check on the string to prevent the following error:
`PHP Warning:  file_exists(): File name is longer than the maximum allowed path length on this platform (4096) in /github-updater/vendor/afragen/wordpress-plugin-readme-parser/class-parser.php on line 162`
The readme file for understrap is over 11K characters, so that string is too long to be handled by that function.

Suggestion:
```
if (strlen($string) <= 4096 && file_exists( $string ) || ... ) ) {
```

**Comment by afragen** [comment]
Do you have any idea which file is causing this?

**Comment by trevorawest** [comment]
It is caused by README file in our understrap theme. Back in their May 18th 2017 release they integrated with github updater.
The length of their readme is what causes that condition to throw an error, so this would occur within any other integrated plugin with a similarly large readme file being passed to the `file_exists()` call. 
Did that help by chance?

**Comment by afragen** [comment]
I try to keep the class-parser.php in sync with the version on dot org. I'll run this issue by the maintainer and see if we can find a suitable solution. Thanks for letting me know about it. I'll leave this open until there's some some solution.

Of course I'm not sure why the README is 11k.

**Comment by afragen** [comment]
This should fix the issue until `class-parser.php` is updated at dot org.
