### ISSUE TITLE
When my theme should be updated after new commit received on GitHub?

### ISSUE THREAD

**Issue by aakatheeri** [afragen/github-updater#923]
I am using Github Updater on my WordPress website, and I followed instructions on the plugin repository here like including theme URL on style.css. On the plugin admin page, it shows that my theme on GitHub is linked with my WordPress website.

But when I refresh the page there are no changes, I made a change on the theme style sheet already. Is there a specific time or expected delay for the update or it should update the theme directly?

**Plugin Version: 9.9.4**

Thanks.

**Comment by afragen** [comment]
The API data from GitHub is cached for 12 hours. If you want to see sooner if it works you can decrease the locally installed version number or you can refresh the cache.

**Comment by amalahoff** [comment]
By refresh the cache do you mean delete any transients? Run wp cache flush? Something else?

**Comment by afragen** [comment]
In the GitHub Updater Settings there's a `Refresh Cache` button.

https://github.com/afragen/github-updater/wiki/Settings#refreshing-cache
