### ISSUE TITLE
Installation failed because API rate limit was exceeded / first cron did not finish

### ISSUE THREAD

**Issue by programmieraffe** [afragen/github-updater#927]
I just did a fresh install with 9.9.7, and it seems that my server ip was immediately blocked by Github API (maybe rate limit was exceeded before because of a shared server ip):

```
21-Jan-2021 21:25:02 UTC] PHP Notice:  Undefined index: base_uri in /html/wordpress/wp-content/plugins/github-updater/src/GitHub_Updater/Plugin.php on line 188
[21-Jan-2021 21:25:02 UTC] PHP Notice:  Undefined index: owner_repo in /html/wordpress/wp-content/plugins/github-updater/src/GitHub_Updater/Plugin.php on line 188
[21-Jan-2021 21:25:02 UTC] GitHub Updater Error: GitHub Updater (github-updater) - API rate limit exceeded for 46.30.XX.XX (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```

The cron just runs again and again, there is no way to add a personal token to avoid the api rate limit exceeding because the dashboard options are not accessible:

![image](https://user-images.githubusercontent.com/777278/105414832-4c1fab80-5c38-11eb-9010-42397f2e2bdb.png)

On another server with a different IP the installation and first cron execution worked fine.

WP: 5.6
PHP: 7.4

Thanks for providing this software! :+1:

**Comment by afragen** [comment]
Check the Bypass WP-Cron background checking and you should be able to add the access token. 

You might want to in check it afterwards.

**Comment by programmieraffe** [comment]
Thanks for the reply! 

IIRC I tried to activate both checkboxes and could not save the settings either (because cron restarted very fast?).

**Comment by afragen** [comment]
I don't understand. Nothing cron should reload that page preventing you from saving changes.

**Comment by programmieraffe** [comment]
If i remember correctly, I could not save a the bypass setting and saw the cron triggered every second in my log files. I don't have time to reproduce this right now, therefore I close it. Thanks for providing it as open source 👍

**Comment by afragen** [comment]
If something is triggering your cron to run every second that's a problem. It would likely be an actual cronjob on your server.

I also don't quite understand why a cronjob would reload the page.
