### ISSUE TITLE
Unable to update plugin from private repo

### ISSUE THREAD

**Issue by ericp-mrel** [afragen/github-updater#929]
Hi,

I am trying to update a plugin of mine from a private Github repo using this plugin, but I keep getting a **download failed, bad request** response.

But, what's weird is when I visit the URL that it prints and visit it directly from my browser, it downloads the plugin file just fine.
I am using the `Release asset: true` for my plugin, so it is trying to download the asset bundle that I generate through CI. (Just like this plugin does)

Let me know if there's anything I can do to help debug this issue as I'm not really sure if there is a way to turn on logging for this plugin that would show the specific issue.

Thanks

**Comment by afragen** [comment]
I see something like this in another plugin. I'm looking into it.

**Comment by afragen** [comment]
It seems that AWS changed the URL for the GitHub release asset redirect and so it missed my check to remove the Auth header. Having the Auth header when not needed is what caused the error.

**Comment by afragen** [comment]
Fixed in v9.9.8
