### ISSUE TITLE
Wiki missing branch header option

### ISSUE THREAD

**Issue by sc0ttkclark** [afragen/github-updater#931]
If a plugin wants to specify a branch to recognize, what's that header option? I didn't find it in the wiki but I could be looking at the wrong place.

`GitHub Plugin Branch: some-other-branch`

Or maybe:

`Branch: some-other-branch`

Not sure here.

**Comment by sc0ttkclark** [comment]
I found a reference to `Primary Branch: some-other-branch` header support, but I wasn't sure. I'll go with that.

**Comment by sc0ttkclark** [comment]
That was it, my bad here

**Comment by afragen** [comment]
If there's a way I can make this more obvious, please let me know.

**Comment by afragen** [comment]
I think this is better, https://github.com/afragen/github-updater/wiki/Versions-and-Branches#primary-branch

**Comment by sc0ttkclark** [comment]
Much better, thanks!
