### ISSUE TITLE
Update statistics

### ISSUE THREAD

**Issue by wolffe** [afragen/github-updater#932]
Can I see how many users have triggered an update from a private GitHub repository? A webhook maybe? Or any idea where to start looking?

**Comment by afragen** [comment]
If you have WP_DEBUG and WP_DEBUG_LOG set to true, these data should be in your debug.log file. Only the site owner sees this data, you can't see this data from GitHub or elsewhere. There is no phone hime or anything like that.

**Comment by wolffe** [comment]
I'm interested in knowing how many users have downloaded/updated my plugin. Is there any way I could do this? Maybe using a GitHub action?

**Comment by afragen** [comment]
There might be a way to get the download count of a release asset, but you would need to look into that. A quick Google search found a few other solutions. 

Generally this is out of scope to for this project.

https://github.community/t/counting-number-of-downloads-of-a-release/359

https://hanadigital.github.io/grev/

**Comment by afragen** [comment]
This one seems to work, https://tooomm.github.io/github-release-stats/

**Comment by afragen** [comment]
I have no idea of the accuracy. It reports this project has been downloaded a total of  61 ,225, 968 times.🤨

**Comment by afragen** [comment]
This might be best, https://github.com/badges/shields/issues/4682#issuecomment-590142747

**Comment by wolffe** [comment]
Thanks for researching this :) I have found a similar solution last night by counting the release downloads. It might work. Note that this is only for me to know how many downloads I have and maybe to display them in a nice way on my plugin store - "this plugin has been downloaded X times".

Thanks, I'll check everything you sent above.
