### ISSUE TITLE
Can't install a new plugin from Github since version 9.9.9

### ISSUE THREAD

**Issue by hisaveliy** [afragen/github-updater#933]
When rolling back to version 9.5.0.7 it works, however at the 9.9.9 version when I leave Github URL with Access Token and click Install, the page is being just reloaded. 

Didn't work when disabled all plugins and themes.

WordPress version 5.6.1.

Let me know if any details needed.

**Comment by ralphjsmit** [comment]
I can confirm this for themes. You fill in the details and click install theme/plugin and the page reloads and gone is your info.

**Comment by afragen** [comment]
This should be fixed in 9.9.10 https://github.com/afragen/github-updater/commit/3e5febead068b209a58c58a0335a5639e9804bbb
