### ISSUE TITLE
Conflicts with Yoast SEO

### ISSUE THREAD

**Issue by herrschuessler** [afragen/github-updater#934]
Yoast SEO has a plugin settings page at `wp-admin/admin.php?page=wpseo_titles`. It contains a form that has `wp-admin/options.php` as target in the `action` attribute.

When GitHub Updater is active, saving changes in that form is not possible because after submitting, the page `wp-admin/options-general.php?page=github-updater&tab=github_updater_settings&subtab=github_updater` is opened instead of `wp-admin/admin.php?page=wpseo_titles`.

I'm not sure if that is an issue on Yoast SEOs part, but as soon as I deactivate GitHub Updater, saving data on the settings page works again.

**Comment by afragen** [comment]
Is this on the current version, 9.9.9?

**Comment by afragen** [comment]
I think I know what I did, reverting and new release now. LMK if 9.9.10 fixes
