### ISSUE TITLE
Error when installing the plugin

### ISSUE THREAD

**Issue by katwag** [afragen/github-updater#935]
Hi!

I'm trying to install the plugin but it gets automatically deactivated because of the plugin file is missing: github-updater-develop/github-updater.php. But I can see the file in the file structure. What can be the problem? 

/ Katarina

**Comment by afragen** [comment]
So that's a feature as installing the develop branch will automatically renames its directory  correctly to `github-updater` where it would normally install itself as `github-updater-develop`. The former is the correct naming. Simply reactivate the plugin.
