### ISSUE TITLE
Unable to update themes via InfiniteWP

### ISSUE THREAD

**Issue by ransoing** [afragen/github-updater#94]
Hello,
I've managed to successfully automatically update my GitHub-hosted theme using this plugin, using the wp-admin area for an individual site. However, my hope is to be able to update the theme simultaneously on many sites using InfiniteWP. I'm unable to do so as InfiniteWP never shows that the theme needs to be updated. I can recreate the problem by doing the following steps:

• Update the theme in the GitHub repo and wait a few minutes
• Log into WP site which uses that theme--the update notifications appear on the Themes page, Updates page, and the admin bar. Looks good so far.
• Log into my InfiniteWP site. InfiniteWP then automatically checks all my sites to see if any updates are available. It incorrectly shows that no updates are available.
• Back on the WP site, refresh the Themes page or Updates page. It now says no updates are available (nothing has actually been updated!).
• Wait a few minutes, then refresh the Themes/Updates page again. It once again says updates are available.

My guess is that, when InfiniteWP checks my sites for updates, it does a force check, clearing the transients and removing the update notifications. So then, how can I ever update my GitHub-hosted theme using InfiniteWP if the very act of checking for updates removes the update notifications?

I am using WordPress v4, the latest version of github-updater (2.8.1), and the latest version of InfiniteWP (2.3.5).

thanks.

**Comment by arabscimitar** [comment]
i am using infiniteWP i  have the same problem but i follow  afragen  instruction that version in style.css must be as tag version number and it works  for me now my bitbucket private theme update from infiniteWP panel 
 thank you  afragen
